### ISSUE TITLE
Add a "highwater" mark to standard runtime, for memory profiling purposes

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#1005]
We have some profiling code that we use to track the high-water mark of memory used by Halide filters; this basically involves overriding halide_malloc() and halide_free(), and doing some threadsafe bookkeeping with globals (along with a few extra runtime functions to get / reset / etc the highwater mark).

I think we should consider just making this part of the standard Halide runtime:
-- The extra overhead for tracking this is pretty minimal
-- Reasonably-scheduled Halide filters make few calls to halide_malloc()/free, so the overhead is likely to be insignificant in real-world use
-- If we added it to the standard runtime, it could be made independent of actual halide_malloc() overrides (ie we could track usage regardless of the memory allocator used)
-- Having it easily available would make it easy to add memory-used reality-checks to tests both inside and outside of Halide

**Comment by abadams** [comment]
We can minimize overhead by making the profiling mode do this
instrumentation.

**Comment by abadams** [comment]
See #1078

**Comment by abadams** [comment]
Fix merged.
