### ISSUE TITLE
match_types cannot handle two vectors with differing bits

### ISSUE THREAD

**Issue by pranavb-ca** [halide/Halide#1010]
If we tried to use match_types in IROperator.cpp with two arguments, say a 'u8x64' type and the other a u16x64 type, then the following code asserts because we ignore the lanes in the arguments.
```c++
} else if (!ta.is_float() && !tb.is_float()) {
    // int(a) * (u)int(b) -> int(max(a, b))
    int bits = std::max(ta.bits(), tb.bits());
    a = cast(Int(bits), a);  // !!! Converting a vector into a scalar, i.e going from lanes > 1 to 1 lane
    b = cast(Int(bits), b);
}
```

**Comment by pranavb-ca** [comment]
A fix is simple and I'll post one in a bit.

**Comment by abadams** [comment]
Thanks Pranav, I pushed your suggested code.
