### ISSUE TITLE
Request: mention in installation docs that using versions after 4.9 of GCC gives errors

### ISSUE THREAD

**Issue by JobLeonard** [halide/Halide#1012]
I know this is probably just me being a noob, but it's just a one-line hint during installation that can save some trouble and wasted time for other beginners ;).

I downloaded the 4.9 binaries, and then immediately got stuck trying to compile the tutorials because they wouldn't compile. I was puzzled by that for over an hour, because my version of GCC was new enough - I'm on an Ubuntu with GCC 5.2. Turns out that was exactly the problem - fixed it by installing "g++-4.9" on the side, and compiling with that.

Anyway, thanks. I'm off to exploring the tutorials again :)

**Comment by JobLeonard** [comment]
On a similar note, copy/pasting this from the second tutorial didn't work:

```
g++ lesson_02*.cpp -g -I ../include -I ../tools -L ../bin -lHalide `libpng-config --cflags --ldflags` -lpthread -ldl -o lesson_02 -std=c++11

g++-4.9: error: `libpng-config: No such file or directory
g++-4.9: error: unrecognized command line option ‘--cflags’
g++-4.9: error: unrecognized command line option ‘--ldflags`’
```

Running `libpng-config --cflags --ldflags` separately yielded `-I/usr/include/libpng12-lpng12`, and replacing it with that output worked of course. But it's still the kind of thing that a newbie can struggle with due to the lack of useful feedback from the command line.

**Comment by zvookin** [comment]
Do you still have the error output with gcc 5.2? Ideally we'd prefer to fix
the errors so it works with newer gcc versions. (We require a fairly recent
minimum due to using C++11 features, but anything newer should be
supported.)

-Z-

**Comment by JobLeonard** [comment]
I can just compile it again with GCC 5.2 and create them. I thought I'd give you a full log for every tutorial, in case there might be something tutorial-specific, but gave up after tutorial eight: [gccerror.txt](https://github.com/halide/Halide/files/109621/gccerror.txt)

**Comment by zvookin** [comment]
The errors are indeed a binary compatibility issue resulting in link failures while using pre-built binaries. Fixing this will likely require adding another set of prebuilt libraries to our set. (The errors are likely due tot he Standard C++ library, not the compiler itself. This may be solvable with compiler flags or switching to a different library.)

In the meantime, Job is correct that the documentation should be fixed. My desire in getting more info is that if these problems are common, we either need to have a lot of different pre-built libraries, or strongly encourage building from source. Another way to go would be to try and integrate with existing Linux distro packaging systems and possibly some automated service that builds package. This would basically make Halide installation similar to how one installs a binary of gcc or clang. This is a longer term solution however.

**Comment by abadams** [comment]
I'll set up some gcc 5.2 builds on the buildbots

**Comment by abadams** [comment]
We now have releases for gcc 4.8, 4.9, 5.1, 5.2, 5.3
