### ISSUE TITLE
Alignment calculation in visit(const Store *) and visit(const Load *) in Codegen_LLVM.cpp is messed up.

### ISSUE THREAD

**Issue by pranavb-ca** [halide/Halide#1013]
It seems that we are overly optimistic about alignment when generating LLVM bitcode for a vector store of type, say, int16x64.

The relevant code is 

```c++
  int alignment = value_type.bytes();
  const Ramp *ramp = op->index.as<Ramp>();
  if (ramp && is_one(ramp->stride)) {

      int native_bits = native_vector_bits();

      // Boost the alignment if possible, up to the native vector width.
      ModulusRemainder mod_rem = modulus_remainder(ramp->base, alignment_info);
      if (!possibly_misaligned) {
         while ((mod_rem.remainder & 1) == 0 &&
                  (mod_rem.modulus & 1) == 0 &&
                    alignment < native_bits) {
           mod_rem.modulus /= 2;
           mod_rem.remainder /= 2;
           alignment *= 2;
          }
      }
```

The check `alignment < native_bits` is wrong because `alignment` is in bytes whereas `native_bits` deals in bits.

Secondly, lets say we do 64x64 tiles and vectorize by 32. `ramp->base` will look something like
((x) * 32 + (y * 64). We get `mod_rem.modulus = 32` and `mod_rem.remainder = 1`. Going by while loop above, that'll result in an alignment of 64 for int16x64, which may or may not be correct; If we use the posix_allocator for intermediate buffers, then it aligns to a 32 byte boundary.

Lastly, should we be relying on `ramp->base` without knowing the alignment of the buffer which could be an intermediate buffer too.

This is a problem on HVX because wrong alignment can lead to wrong answers.

**Comment by abadams** [comment]
The check being wrong isn't fatal - that's just the point at which it
decides there's no more gain in trying to infer greater alignment. It's
assumed that halide_malloc returns buffers that are aligned at the maximum
meaningful alignment for the platform in question (or greater). This should
probably be documented explicitly. I'll make some tweaks...

**Comment by pranavb-ca** [comment]
Hey Andrew,

I am tempted to reopen this issue. I have a case with the same problem except that the vector is stored to and loaded from the stack. I noticed that small constant allocations go on the stack. The other way to go about this is to align stack elements to a 128 byte boundary, which isn't the case presently on HVX.

**Comment by pranavb-ca** [comment]
I added some debug(4) statements and set HL_DEBUG_CODEGEN to 4.
These are some of the messages that were printed.

Allocating 4896 bytes on the stack for f2
Generating a load with alignment: 64
Type: uint16x32
Index: ramp(((((f2.s0.v1*2) - (processed.s0.ty.ty*32))*64) + 128), 1, 32)

The ramp base is a multiple of 64 but the f2 is not aligned to a 64 byte boundary, which is the natural vector width in HVX single mode.

**Comment by abadams** [comment]
In CodeGen_LLVM::create_alloca_at_entry, the AllocaInst returned from
builder->CreateAlloca has a setAlignment method. Currently we just cast it
to a Value *. See if the following works:

   AllocaInst *alloca = builder->CreateAlloca(t, size, name);
   alloca->setAlignment(native_vector_bits()/8);
   Value *ptr = alloca;

**Comment by pranavb-ca** [comment]
Ok, I am aligning vector types on the stack on native vector width boundary.

```c++    
AllocaInst *alloca = builder->CreateAlloca(t, size, name);
if (t->isVectorTy() || n > 1)
      alloca->setAlignment(native_vector_bits()/8);
Value *ptr = alloca;`
