### ISSUE TITLE
skip_stages doesn't always skip memoized Funcs

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#1014]
I don't (yet) have a small demo case, but reporting before I forget:

I have code that calls an extern function to load a LUT; this is expensive, so in a default case, we try to skip it via select(), e.g.

    Expr lut_arg = whatever();

    // some_extern_func just fills in a LUT based on extern_func_arg
    Func load_lut{"load_lut"};
    load_lut.define_extern("MyExternFuncName", {lut_arg}, Halide::Float(32), 1);
    load_lut.compute_root();

    Func lut;
    // skip expensive extern call in the common default case where LUT is unity
    lut(x) = select(lut_arg == 0.f, 1.f, load_lut(lut_arg)(x));
    // Do something with lut

inserting logging into the extern func shows that we do indeed skip the load in this case.

I recently tried to upgrade this to memoize for the lut:

    load_lut.compute_root().memoize();  // lut depends only on lut_arg, so this is cool

only to find that the extern func is getting called (and memoized) in all cases now, even the 'default' case that we skipped before. This is not technically wrong, but is clearly suboptimal. Perhaps skip_stages needs some code to special-case memoize somehow (it doesn't appear to at present)?

**Comment by psuriana** [comment]
Fixed
