### ISSUE TITLE
Atomic updates

### ISSUE THREAD

**Issue by abadams** [halide/Halide#1017]
We should be able to parallelize associate operations across RDoms in several ones, one of which is using atomic operations, e.g:

```
RDom r(0, 100);
f() = 0
f() += g(r);
f.update().atomic().parallel(r);
```

**Comment by abadams** [comment]
See https://lists.csail.mit.edu/pipermail/halide-dev/2016-February/002194.html for a discussion.

**Comment by BachiLi** [comment]
Hi,

Is there still any plan to add the atomic updates? This would be useful for general scattering operations, e.g.,
```
f(g(r.x)) += h(r.x) 
```
This happens a lot when computing the gradients. We hacked it in the gradient-halide by having atomics for all += in the PTX backend ( https://github.com/jrk/gradient-halide/blob/master/src/CodeGen_PTX_Dev.cpp#L247 ), but something like what is proposed in this issue would be very useful.

**Comment by BachiLi** [comment]
Hi,

Is there still any plan to add the atomic updates? This would be useful for general scattering operations, e.g.,
```
RDom r(0, 1000001);
f(clamp(r.x, 0, 1000000)) += g(r.x) 
```
This happens a lot when computing the gradients. We hacked it in the gradient-halide branch by having atomics for all += in the PTX backend ( https://github.com/jrk/gradient-halide/blob/master/src/CodeGen_PTX_Dev.cpp#L247 ), but something like what is proposed in this issue would be very useful.
