### ISSUE TITLE
Cannot vectorize dimension x.v3 of function .. because the function is scheduled inline

### ISSUE THREAD

**Issue by robstewart57** [halide/Halide#1025]
When trying to compile the parallelised `blurX` function, as suggested http://stackoverflow.com/a/35398082/1526266 , I'm getting this error:

```
Error at ./blur-failing.cpp:36:
Cannot vectorize dimension x.v3 of function blur_x because the function is scheduled inline.
```

Line 36 is this:

``` c++
continuation.realize(result);
```

The complete program is this:

``` c++
#include <iostream>
#include "Halide.h"
using namespace Halide;
#include "halide_image_io.h"
using namespace Halide::Tools;

Func blurX(Func continuation)
{ Var x("x"), y("y"), c("c");
  Func input_16("input_16");
  input_16(x, y, c) = cast<uint16_t>(continuation(x, y, c));
  Func blur_x("blur_x");
  blur_x(x, y, c) =
    (input_16(x-1, y, c)
     + 2 * input_16(x, y, c)
     + input_16(x+1, y, c)) / 4;
  blur_x.vectorize(x, 8).parallel(y);
  Func output("outputBlurX");
  output(x, y, c) = cast<uint8_t>(blur_x(x, y, c));
  return output;
}

Func rgb_to_grey(Image<uint8_t> input)
{  Var x("x"), y("y"), c("c");
  Func clamped("clamped");
  clamped = BoundaryConditions::repeat_edge(input);
  Func greyImg("greyImg");
  greyImg(x,y,c) =
    clamped(x,y,0) * 0.3f
    + clamped(x,y,1) * 0.59f
    + clamped(x,y,2) * 0.11f;
  return greyImg;
}

void imwrite(std::string fname, int width, int height, Func continuation)
{ Image<uint8_t> result(width, height, 1);
  continuation.realize(result);
  save_image(result, fname);
}

int main()
{ Var x("x"), y("y"), c("c");
  Image<uint8_t> input = load_image("input.png");
  Func inputImg("inputImg");
  inputImg = rgb_to_grey(input);
  Func img1Fun("img1Fun");
  img1Fun(x, y, c) = cast<uint16_t>(inputImg(x, y, c));
  Func img2Fun = blurX(img1Fun);
  Func outputFun("outputFun");
  outputFun(x, y, c) = cast<uint8_t>(img2Fun(x, y, c));
  imwrite("output.png",input.width()-1,input.height()-1, outputFun);
  return 0;
}
```

Where is my mistake?

**Comment by zvookin** [comment]
By default Func's are scheduled inline, which means they are computed on
demand and do not have storage. Inline Funcs cannot be scheduled as they
take on the scheduling of whichever Func they are used in (which can
include multiple ones). To schedule storage for a Func, use compute_root or
compute_at. Then computation strategy, such as vectorization can be
assigned as well.

In general you are using a high degree of abstraction by defining multiple
C++ functions which has very little value and makes the code more difficult
to deal with. Once you have a handle on the language, breaking things up
into multiple C++ functions or building reusable peices of functionality
may be productive, but at this point I would stick to a single function. (I
also encourage people to move to using a Generator sooner rather than
later, but the main function is fine too.)

-Z-

**Comment by robstewart57** [comment]
Hi @zvookin , thanks very much for this insight, I really appreciate the assistance.

> To schedule storage for a Func, use compute_root or
compute_at. Then computation strategy, such as vectorization can be
assigned as well.

With that in mind, I'm pleased that the following `blurX` implementation works (or at least, doesn't throw a runtime error):

```c++
Func blurX(Func continuation)
{ Var x("x"), y("y"), c("c");
  Func input_16("input_16");
  input_16(x, y, c) = cast<uint16_t>(continuation(x, y, c));
  Func blur_x("blur_x");
  blur_x(x, y, c) =
    (input_16(x-1, y, c)
     + 2 * input_16(x, y, c)
     + input_16(x+1, y, c)) / 4;
  blur_x.vectorize(x, 8).parallel(y);
  blur_x.compute_root();
  Func output("outputBlurX");
  output(x, y, c) = cast<uint8_t>(blur_x(x, y, c));
  return output;
}
```

> In general you are using a high degree of abstraction by defining multiple
C++ functions which has very little value and makes the code more difficult
to deal with. Once you have a handle on the language, breaking things up
into multiple C++ functions or building reusable peices of functionality
may be productive, but at this point I would stick to a single function.

That's a very useful anecdote, thanks. I'm currently exploring the use of Halide for writing an image processing library, rather than for writing applications directly. That is, generating `.o` files containing reusable image processing functions that (Halide based) applications may wish to link in the future should they wish.

So perhaps...

> Once you have a handle on the language

must try harder.
