### ISSUE TITLE
Would be useful to tell Halide to assume an expression is bounded

### ISSUE THREAD

**Issue by abadams** [halide/Halide#1033]
E.g. a new intrinsic:

Expr unsafe_promise_bounded(Expr v, Expr min, Expr max);

This would also handle declaring bounds on the values loaded from input images.

**Comment by zvookin** [comment]
I'm guessing we would wrap this in a language construct that takes a
parameter to decide whether to assert the bound or not. This would provide
a way to run the code with failure checking for validation.

-Z-

**Comment by kgnk** [comment]
How about the intrinsic name **`ranged`** and using the already existing `Target::Feature::NoAssert`

**Comment by dsharletg** [comment]
We now have `unsafe_promise_clamped`
