### ISSUE TITLE
Add ability to prefetch loads from a Func

### ISSUE THREAD

**Issue by abadams** [halide/Halide#1043]
f(x) = ... g(x) ...

f.prefetch(g, x, 3);  // Prefetch the loads from g at the loop over x three iterations ahead.

It's unclear whether or not this would be helpful, but I see explicit prefetch instructions in the inner loops of well-optimized blas libraries. Step 1 of this project would be to hack something together and try to measure perf improvements.

**Comment by kgnk** [comment]
I have it on good authority from Intel that prefetch just wastes instruction loads by their presence. The CPU detects loads that walk through memory and begins streaming that memory into the CPU in anticipation of it being read.

**Comment by abadams** [comment]
I believed that too, but for every good blas implementation I can find,
when I break in the middle of the inner loop for sgemm I see explicit
prefetch instructions, even though they all take pains to walk through
memory in order. Hence my feeling that this needs to be investigated a
little more.

**Comment by kgnk** [comment]
The corollary to "don't use prefetch" is: let performance measurements be your ultimate decision factor. The corollary to **that** statement is: every CPU family has its own implementation details.

**Comment by zvookin** [comment]
@abadams Has enough prefetch support landed to allow closing this bug?

**Comment by abadams** [comment]
Yeah, we have prefetching now. It can possibly be improved on CPU targets, but that doesn't warrant an open issue.
