### ISSUE TITLE
Move allocation constraints out of halide_malloc and into codegen.

### ISSUE THREAD

**Issue by zvookin** [halide/Halide#1044]
Currently the following is in default_malloc in src/runtime/posix_allocator.cpp:

`// We want to return an aligned address to the application.
    // In addition, we should be able to read a double beyond the
    // buffer. So we allocate more space than what was asked for.
    const size_t alignment = 128;
`

The end padding definitely needs to be accounted for by codegen and moved out of this routine. (I will update the comment to refer to this Issue.)

In general, it may be better to pass the alignment constraint into halide_malloc. And possibly both alignment and padding needs.

We should definitely do some measurement to see how 128-bytes affects performance. I doubt it will have negative impact, but it is starting to feel pretty large. It is also too large to depend on for general inputs and outputs. If a situation comes up that requires this to go larger, we should definitely support variable alignment and pass the required alignment in to the allocation call.

-Z-

**Comment by dsharletg** [comment]
I'm working on part of this now: https://github.com/halide/Halide/compare/alignment-padding?expand=1

I'm going to benchmark some stuff with this branch now to see how it affects things.

**Comment by dsharletg** [comment]
I think I addressed part of this above, and #3738 is a dup of the rest.
