### ISSUE TITLE
NoRuntime & RegisterMetadata can't be combined

### ISSUE THREAD

**Issue by gssafar** [halide/Halide#1060]
When building a module with both Target::NoRuntime & Target::RegisterMetadata, the (successfully compiled) Halide code generator binary crashes with

```
Internal error at /usr/local/google/home/ssafar/local/Halide/src/CodeGen_LLVM.cpp:793
Condition failed: register_metadata
Could not find register_metadata in initial module

```
which seems to be caused by the fact that the module didn't yet have the symbol `halide_runtime_internal_register_metadata` (& `_halide_runtime_internal_registered_filter_t`) yet.

Example code to repro:
```
#include "Halide.h"
using namespace Halide;

int main(int argc, char** argv) {
  Var x;
  Func f;
  f(x) = x;

  Target t = get_host_target();
  t.set_features({Target::NoRuntime, Target::RegisterMetadata});

  f.compile_to_file("no_runtime_repro", {}, t);
}
```

**Comment by steven-johnson** [comment]
Just a plain bug -- apparently no one has tried this combination before. (RegisterMetadata is very lightly used.) Patches welcome.

**Comment by abadams** [comment]
Is this bug still a problem? I can't repro it with the attached code. The
entrypoints being listed in the array in src/runtime/runtime_api.cpp should
be enough.

**Comment by gssafar** [comment]
Just tried it with the latest version, it indeed seems to have been fixed since. Thanks a lot for having taken a look though!
