### ISSUE TITLE
Reduction over an Expr of dynamic size?

### ISSUE THREAD

**Issue by ppwwyyxx** [halide/Halide#1074]
In all the tutorials I noticed that the `RDom` object are defined with constant integers.
Suppose I want to write a Halide function that takes an image of arbitrary size, how should the reduction domain be defined?
Thanks

**Comment by zvookin** [comment]
RDom arguments can be any Expr that is not dependent on corrdinates.
Generally this means Params or methods on ImageParams such as min() and
extent() (or width()/height()).

-Z-

**Comment by ppwwyyxx** [comment]
Thanks. I'm aware of these methods for ImageParams, but if I'm to apply reduction on a Func object, what would be the equivalent?

**Comment by abadams** [comment]
Funcs don't have well-defined mins, maxes, or extents. They're defined over
an infinite domain. You'll have to construct the Expr you want from the
size of the inputs or some Param.
