### ISSUE TITLE
aottests rely on cmake FILE(GLOB) order

### ISSUE THREAD

**Issue by ibtaylor** [halide/Halide#1095]
test source filenames are evaluated in glob order (inode order?? `ls -liU`) here:
https://github.com/halide/Halide/blob/master/test/CMakeLists.txt#L105
later `LIB_c_plus_plus_name_mangling` is set here
https://github.com/halide/Halide/blob/master/test/CMakeLists.txt#L189
but, if `c_plus_plus_name_mangling_define_extern_aottest.cpp` was in the file list before `c_plus_plus_name_mangling_aottest.cpp` as it was on my machine, then within its if block `${LIB_c_plus_plus_name_mangling}` is empty.

I worked around this by adding `list(SORT TESTS)` after the glob on line 105, but both of these methods seem very fragile.

**Comment by jiapei100** [comment]
Yes, abadams:
You are right.
add "list(SORT TESTS)" after line 105 solved my problem....

**Comment by zvookin** [comment]
Fixed by https://github.com/halide/Halide/commit/a0b7889d0d52cf4386bde3ddf7725c18647f1130 .
