### ISSUE TITLE
problem build project with halide library

### ISSUE THREAD

**Issue by christianPetrucci** [halide/Halide#1130]
i have a project smartgaze at https://github.com/trishume/SmartGaze and i have installed all libs.
i have used this command for install halide 
cd llvm3.7
mkdir build
cd build
cmake -DLLVM_ENABLE_TERMINFO=OFF -DLLVM_TARGETS_TO_BUILD="X86;ARM;NVPTX;AArch64;Mips;PowerPC" -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_BUILD_TYPE=Release ..
make 

in halide dir:
export LLVM_CONFIG=../llvm3.7/build/bin/llvm-config
export CLANG=../llvm3.7//build/bin/clang

mkdir cmake_build
cd cmake_build
export LLVM_ROOT=/path/to/llvm3.7/build
cmake -DLLVM_BIN=${LLVM_ROOT}/bin -DLLVM_INCLUDE="${LLVM_ROOT}/../include;${LLVM_ROOT}/include" -DLLVM_LIB=${LLVM_ROOT}/lib -DLLVM_VERSION=37 ..
make

and for build smartgaze project in it's folder:
mkdir build
cd build
cmake ../

but i have cmake error:
the following variable are used in this project, but they are set to NOTFOUND LIBHALIDE_INCLUDE_DIR used as include directory in directory /home/osboxes/SmartGaze-master/src
LIBHALIDE_LiBRARY linked by target "SmartGaze" in directory /home/osboxes/SmartGaze-master/src

the build of halide is ok and it is in separate folder of llvm3.7. i have osboxes/Halide, osboxes/llvm3.7 osboxes/SmartGaze-master, is it wrong?
help me please

**Comment by abadams** [comment]
The libHalide part of it looks correct to me. I'd ask the SmartGaze devs for advice.

**Comment by christianPetrucci** [comment]
how can i change the cmakelist.txt of project to solve this problem?
now is:

PROJECT( SmartGaze_project )
FIND_PACKAGE( OpenCV REQUIRED )
cmake_minimum_required(VERSION 2.8)

SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/bin)
set(CMAKE_BINARY_DIR ${PROJECT_BINARY_DIR}/bin)

add_subdirectory(src)

**Comment by christianPetrucci** [comment]
I don't have halide in usr/local with other lib And this i The problem. Ho Can i sole The problem? Can You write me The location To open terminal And The right commands To have halide in default path of library?

**Comment by christianPetrucci** [comment]
i have llvm in /ust/local/include OK

what modifies can add to Halide's Makefile and where?

i don't understand why llvm and clang are in url/local/include but halide not. where i use export command?

now i have:
home/
     /llvm3.7/......
     /Halide/ .......
it's right? help me please

**Comment by alexreinking** [comment]
Closing because this issue is stale (LLVM 3.7 is no longer supported)
