### ISSUE TITLE
Missing Includes for Win32 MSVC14 VS2015 in Float16.cpp

### ISSUE THREAD

**Issue by TimmvonderMehden** [halide/Halide#1131]
i could not compile Halide with above compiler until adding those lines to Float16.cpp at the end of the includes:

#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"

please add them to float16.cpp

C:\dev\src3\Halide\src\Float16.cpp

**Comment by abadams** [comment]
Fixed. Thanks.
