### ISSUE TITLE
distrib_windows.ps1 doesn't match Makefile

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#1138]
There are files copied by the Makefile version that aren't by the Windows version (eg tools/halide_image.h). Easy to fix, but
(1) I don't have a quick way of testing so I'm not going to make the fix right now, and 
(2) Would be good to find a way to avoid replicating this code in Make and Powershell and etc.

**Comment by abadams** [comment]
distrib_windows no longer exists
