### ISSUE TITLE
Generators - How to specify input ImageParam datatype for AOT 

### ISSUE THREAD

**Issue by ashishUthama** [halide/Halide#1140]
Is it possible to change the datatype of the inputs (ImageParam) in the generator framework?

For example, here is a test case I trying out:

```
//test_halide.cpp
#include <Halide.h>
#include "GenGen.cpp"

using namespace Halide;

class testGenerator : public Halide::Generator<testGenerator> {
public:
  GeneratorParam<Halide::Type> datatype{"datatype", UInt(8)};
  ImageParam im{datatype, 2, "im"};

  Func build(){
    Func test("test");
    Var x("x"), y("y");
    test(x,y) = im(x,y)+1;
    return test;
  }
};

RegisterGenerator<testGenerator> testGenerator{"test_halide"};

```

I was hoping I could do this to get a double datatype version:

`test_halide -g test_halide target=x86-64 datatype=float64 -o . -e html`

But the generated code indicates that the type of im is `uint8`. 

I couldnt easily tell if I was doing something wrong, or if this aspect is not satisfied by the Generators (i.e, you can only change the output type as the tutorial shows). Is there a better way to express what I am trying to achieve?

**Comment by abadams** [comment]
Datatype hasn't been read from the command line yet when im is constructed,
so it still has its default value. It's a bit ugly, but you need to
recreate im at the top of build():

    Func build() {
        im = ImageParam(datatype, 2, "im");
        ....
    }

**Comment by ashishUthama** [comment]
Thanks for the quick response!
