### ISSUE TITLE
Compile and dispatch to a halide generated library without linking in libHalide

### ISSUE THREAD

**Issue by ashishUthama** [halide/Halide#1157]
Setup:
- Obtained a .so using tutorial 15 (Generators). 
- In the process of writing a dispatch layer on top of this

Issue:
The dispatch layer  ( #879 ) needs to create buffer_t objects, hence needs to include Halide.h. But otherwise, this module ought not to have any link dependency with libHalide or the generated .so itself. 

However, if I dont link in libHalide when compiling this dispatch layer, I see:

> glnxa64/Halide/include/Halide.h:1809: undefined reference to `Halide::Internal::Introspection::get_source_location()'

Suggestions?

**Comment by abadams** [comment]
Don't include Halide.h. Include HalideRuntime.h

**Comment by ashishUthama** [comment]
ah! I missed that bit.
Thanks!
