### ISSUE TITLE
Provide Bazel wrappers for libHalide

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#1159]
Bazel isn't Windows-compliant enough (yet) to use for building Halide itself, but it does allow us to use prebuilt libHalide with Bazel projects. We should provide and maintain this wrapper; this issue will track the work.

**Comment by steven-johnson** [comment]
Landed initial version in https://github.com/halide/halide_bazel. Leaving issue open as more work is likely to be done.

**Comment by alexreinking** [comment]
This has gone stale and we've sailed on with CMake. Closing for now, but feel free to re-open if the tides change.
