### ISSUE TITLE
OpenCL EP

### ISSUE THREAD

**Issue by bredfield** [halide/Halide#1203]
I'm working with a Cortex-A9 SoC with the following GPU support:
- OpenGL ES 1.1/2.0/3.0
- OpenCL 1.1 EP

Does Halide support GPU operations under those constraints?

**Comment by zvookin** [comment]
It should be able to work with either, though OpenGL has more constraints
on what can be compiled than OpenCL does. I won't be surprised if there are
some minor issues getting this to work, though they'll likely be minor. I
won't be surprised if there are some significant challenges getting
performance via either OpenGL ES or OpenCL on an SOC GPU.

-Z-
