### ISSUE TITLE
Travis should run all tests/

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#1215]
kgnk@ reports: "while Travis builds everything, it only runs most correctness tests".

We should verify that Travis runs everything under tests/; if not, we should fix it.

**Comment by abadams** [comment]
Unfortunately it won't give us reliable data for performance tests, can't
run GPU tests, and I think it times out if you ask it to run *all* of the
correctness tests. I should figure out how to integrate buildbot support
for github PRs.

**Comment by steven-johnson** [comment]
Ack. Didn't consider those factors. Need more coffee. 

Is it (at least) also doing generator/ tests?

**Comment by abadams** [comment]
Don't look like it. It runs this script in a slightly indirect way:

https://github.com/halide/Halide/blob/master/test/scripts/build_generic.sh

**Comment by zvookin** [comment]
@steven-johnson @abadams Can this be closed now that we have buildbot based CI?

**Comment by abadams** [comment]
Yes, we now have CI coverage of all the tests.
