### ISSUE TITLE
Compile Error 127

### ISSUE THREAD

**Issue by shwfc** [halide/Halide#1226]
I am trying to compile Halide on Ubuntu 14.04, with gcc4.8 and llvm3.5. Come across following error:

IRPrinter test passed
CodeGen_C test passed
ir_equality_test passed
Bounds test passed
expr_match test passed
deinterleave_vector test passed
modulus_remainder test passed
common_subexpression_elimination test passed
Simplify test passed
Solve test passed
Target test passed
/home/shared/halide-build/Halide/bin/test_internal: symbol lookup error: /home/shared/halide-build/Halide/bin/test_internal: undefined symbol: _ZN6Halide8Internal21cplusplus_mangle_testEv
make: **\* [test_internal] Error 127

Any idea?

**Comment by zvookin** [comment]
It seems like the test is failing trying to find a function in
CPlusPlusMangle.cpp. Is it possible you have stale Makefiles of some sort?
E.g. didn't rerun cmake? CPlusPlusMangle.cpp was added around a month or
two ago IIRC.

-Z-

**Comment by alexreinking** [comment]
Closing because this issue is stale (LLVM 3.5 is no longer supported)
