### ISSUE TITLE
Error compile Halide with gcc5.3 and llvm3.7

### ISSUE THREAD

**Issue by zdong01** [halide/Halide#1243]
I have error compiling Halide.
gcc: 5.3.0
llvm: 3.7.1

Linking CXX executable ../bin/runtime.generator
../lib/libHalide.so: undefined reference to `llvm::TargetRegistry::lookupTarget(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
../lib/libHalide.so: undefined reference to `llvm::RTDyldMemoryManager::getSymbolAddressInProcess(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../lib/libHalide.so: undefined reference to `llvm::sys::DynamicLibrary::getPermanentLibrary(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
../lib/libHalide.so: undefined reference to `llvm::SectionMemoryManager::finalizeMemory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
../lib/libHalide.so: undefined reference to `llvm::ModulePass::createPrinterPass(llvm::raw_ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
../lib/libHalide.so: undefined reference to `llvm::RTDyldMemoryManager::getPointerToNamedFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/runtime.generator] Error 1
make[1]: *** [tools/CMakeFiles/runtime.generator.dir/all] Error 2
make: *** [all] Error 2

Any idea?

**Comment by abadams** [comment]
It looks to me like your llvm was not compiled with c++11, so it's
expecting std::string from the older libstdc++.

**Comment by zdong01** [comment]
@abadams you are right. I confirmed llvm was built long time ago. Thanks.
