### ISSUE TITLE
Vectorized dimension cannot be less than vector width

### ISSUE THREAD

**Issue by kgnk** [halide/Halide#1246]
I have an algorithm that works but breaks when vectorized. I've put together a sample that illustrates this. The proper output is produced when the line to vectorize the result is commented out.

I'm compiling and running this on a Mac. About this Mac says:

> MacBook Pro (Retina, 13-inch, Mid 2014)
> 2.6 GHz Intel Core i5

The detected host target is `x86-64-osx-avx-f16c-fma-sse41`

[EvnOdd.zip](https://github.com/halide/Halide/files/283156/EvnOdd.zip)

**Comment by abadams** [comment]
Turn off NoAsserts :)

**Comment by kgnk** [comment]
I see. If i vectorize a function across the width, the width had better be at least a vector size wide. I really thought there would be a scalar loop epilog

**Comment by kgnk** [comment]
Nevermind. Vectorize has TailStrategy

**Comment by abadams** [comment]
Note that GuardWithIf is currently broken for vectorize (it scalarizes)

**Comment by kgnk** [comment]
I'm seeing that. It should scalarize in the epilog, but still vectorize the main loop. I'll stop trying to get it to do that if it's a known issue.
