### ISSUE TITLE
linear algebra fails to build

### ISSUE THREAD

**Issue by hongborong** [halide/Halide#1260]
Halide/apps/linear_algebra$ make
......
g++ -std=c++11 -I ../../include/ -I ../../tools/ -I ../../apps/support/  -O3 -fopenmp -Wall -std=c++11 -march=native -c -o src/halide_blas.o -I ../../include/ -I ../support -Isrc/kernels src/halide_blas.cpp
In file included from src/halide_blas.cpp:3:0:
src/halide_blas.h:7:31: fatal error: halide_scopy_impl.h: No such file or directory
compilation terminated.
Makefile:92: recipe for target 'src/halide_blas.o' failed
make: *** [src/halide_blas.o] Error 1

**Comment by abadams** [comment]
Can repro. Fixing.

**Comment by abadams** [comment]
Fixed in d5e319f666e4571ffd6bd86ca074f05798f92b67

**Comment by hongborong** [comment]
benchmarks/eigen_benchmarks.cpp src/libhalide_blas.a ../../lib/libHalide.a -L/usr/lib/llvm-3.8/lib  -lrt -ldl -ltinfo -lpthread -lz -lm
benchmarks/eigen_benchmarks.cpp:16:23: fatal error: Eigen/Eigen: No such file or directory

**Comment by abadams** [comment]
You need to have eigen, openblas, and Atlas installed
