### ISSUE TITLE
restrict pointers in OpenCL code gen

### ISSUE THREAD

**Issue by ronghongbo** [halide/Halide#1264]
I searched the source code, and cannot find any place generating a "restrict" keyword for pointer parameters in OpenCL kernels. This seems a missing feature. It can be important for performance.

**Comment by zvookin** [comment]
@dsharletg @abadams Can this be closed now? I thought we did this in at least some situations.

**Comment by dsharletg** [comment]
Yeah, we should be doing this now: https://github.com/halide/Halide/blob/master/src/CodeGen_OpenCL_Dev.cpp#L594

I'm pretty sure a few users have reported success after updating to get that change too.
