### ISSUE TITLE
Implement C++11 only thread pool.

### ISSUE THREAD

**Issue by zvookin** [halide/Halide#128]
It would be useful to have a pure C++11 thread pool. This is a fairly easy immigration project for someone interested in starting to do development on Halide itself. The task is basically to convert src/runtime/posix_thread_pool.cpp to use C++11 concurrency functionality.

**Comment by alexreinking** [comment]
Has this been done? If not, is there still interest in doing this? The referenced source file `src/runtime/posix_thread_pool.cpp` no longer exists.

**Comment by abadams** [comment]
The addition of async would make it extremely challenging, I think. It's no longer a good starter project.
