### ISSUE TITLE
Intel Thread Building Blocks support.

### ISSUE THREAD

**Issue by zvookin** [halide/Halide#129]
Intel Thread Building Blocks (TBB) is a rich task parallelism library. Having support for this in Halide would be great, but it is difficult to do inside the Halide runtime as we try to minimize external dependencies that must be installed to build Halide. (And we have so far avoided any sort of autocon mechanism.)

The best way to support TBB would be via a single .cpp file that exports the Halide runtime thread pool API (e.g. halide_do_par_for) and calls TBB. This .cpp file could be included in the binary for any app or project that wants to use TBB with Halide. A good implementation of this would use the TBB runtime_loader interface to access TBB both to allow optional use with fallback to the built-in thread pool if TBB is not installed and to ensure Halide code uses the same TBB instance that other code in the same process uses.

**Comment by bhack** [comment]
::+1::

**Comment by ashishUthama** [comment]
I am trying to integrate TBB into our Halide build architecture and I am now trying to figure out where such a .cpp file would fit in with the AOT scheme. 

Am I right in assuming that a halide_do_par_for (custom implementation invoking TBB) symbol should be linked in the last step of : http://halide-lang.org/tutorials/tutorial_lesson_15_generators_usage.html ?

**Comment by abadams** [comment]
Yes, or use set_custom_do_par_for to redirect to a TBB-based thread-pool at
runtime.

**Comment by zvookin** [comment]
The main thing is the file implementing this has to be compiled with the
project using Halide. It would be pretty tricky to make i part of the
Halide runtime I believe.

If strictly AOT, I would try to implement the correct symbols directly to
eliminate the built-in threading runtime support.

-Z-

**Comment by abadams** [comment]
Please let us know if you see a performance win from this, it might tell us
a way in which we can improve our thread pool.

**Comment by ashishUthama** [comment]
Thanks, statically linking at that stage worked.

@abadams  - for the prototype I have, TBB was slower than Halide's pool by ~20-30% (glnxa64, 6 core x86_64). Plan to tweak this and see if I can change anything since I need to use TBB to play well with the bigger system I plan to integrate this into. Will update here if I find anything interesting.

**Comment by ashishUthama** [comment]
While trying to statically link a custom halide_do_par_for invoking TBB, I notice the I still need to link in -pthread.  Varying the TBB thread count had a impact on performance, so I think TBB does get used. 
Is this just the side effect of the weak linking architecture? 

```
halide_runtime.a(halide_runtime.a.o): In function `halide_spawn_thread':
standalone_runtime:(.text.halide_spawn_thread+0x3d): undefined reference to `pthread_create'
halide_runtime.a(halide_runtime.a.o): In function `halide_join_thread':
standalone_runtime:(.text.halide_join_thread+0x1a): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
```

**Comment by abadams** [comment]
Halide also uses pthreads for its built-in sampling profiler, so calls to
pthreads exist even with the thread pool clobbered. It might be possible to
strip it out if it's a problem for you - I'm not entirely sure why the
profiler always goes in.

**Comment by ashishUthama** [comment]
Trying a similar approach on VS 2015, running into:
`
halide_runtime.lib(halide_runtime.lib.obj) : error LNK2005: halide_do_par_for already defined in tbbPool.obj
`
Tried changing the order of the files specified to link, no help. (i.e having the tbbPool.obj which contains the TBB override before or after halide_runtime.lib didnt make a difference). 

I dont fully understand weak linkages on Windows, thought I would post here for suggestions while I continue hacking...

**Comment by abadams** [comment]
Weak linkage isn't really a thing on Windows (or mingw). We have our builds
setup to never rely on it. Instead of defining your own symbol
halide_do_par_for, do something like
halide_set_custom_do_par_for(my_do_par_for) at process startup.

**Comment by ashishUthama** [comment]
@abadams - thanks for the quick response, you saved me some time with that rabbit hole!

About halide_set_custom_do_par_for, this goes back to what @zvookin mentioned. I am using AOT compilation using generators to create a shared library which is then used like any other C library by the main process. The main process will not link/know about Halide. I am not sure how to plug in halide_set_custom_do_par_for in this scenario. 

I'll explore some way to  have halide_set_custom_do_par_for run on library load and see if that's possible/works.

**Comment by ashishUthama** [comment]
Thanks for the pointers.
I was able to use the snippet below to use TBB on glnxa64 and win64. 

Performance: For a small test prototype, on linux 6 core, the performance went down by ~20 %, whereas on a win64, 8 core machine, the performance actually improved by ~50%. 
I am not sure how to make a rigorous evaluation - but will post if I see any trends different from the above.

For reference, I compiled the below into a single .obj file and linked it in with all the generator outputs (as seen in Tutorial 15, Part 2). Note that the parent process sets up the TBB pool.

```
#include <HalideRuntime.h>
#include <Halide.h>
#include <tbb/tbb.h>
using namespace tbb;

// Using TBB for threading
// http://halide-lang.org/docs/class_halide_1_1_func.html#afd38942fde8f87b6851d47bf99513ba1
extern "C" int tbb_do_par_for(void *user_context,
                                 int (*f)(void *, int, uint8_t *),
                                 int min, int extent, uint8_t *state) {
    int exit_status = 0;
    tbb::parallel_for(int (min), min+extent, [&](int idx) {
        int job_status = halide_do_task(user_context, f, idx, state);
        if (job_status) exit_status = job_status;
    });
    return exit_status;
}


#ifdef _MSC_VER
BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved){
  if (fdwReason == DLL_PROCESS_ATTACH){
    halide_set_custom_do_par_for(&tbb_do_par_for);
  }
  return TRUE;
}


#else
__attribute__((constructor))
void overRideWithTBB(){
  halide_set_custom_do_par_for(&tbb_do_par_for);
}
#endif
```

**Comment by zvookin** [comment]
Sounds like we should open an issue to do some analysis of thread pool
performance on Windows.

**Comment by abadams** [comment]
That's very interesting indeed, thanks for reporting your results. I'll go
find vtune and take a look at what's happening on Windows. Maybe there's an
easy improvement we could make.

**Comment by ashishUthama** [comment]
Oops! I wasnt able to get the same numbers with subsequent function tests. TBB has been consistently ~10-20% slower than Halide on both glnxa64 and win64. Plan to test this on maci64, will post if thats different.
Sorry for the false alarm, I was messing around with too many different versions. 
(@abadams  - if you have some test functions you would like me to try on TBB, I would be glad to help.)

A curious observation though: I try to take the 'min' runtime from multiple runs to compare. tbb run times are fairly consistent across these multiple runs, while Halide has a lot more variation. (Something I have observed when comparing TBB to OpenMP too).

**Comment by abadams** [comment]
We don't pin worker threads to cores. Maybe TBB does? That might reduce
variability.

I've been digging into windows performance, and I've discovered that local
laplacian spends 20% of its time freeing a handful of large allocations at
the end. Still have no idea why. Heap debugging doesn't seem to be on.
Using a private heap doesn't help. Is it normal to require 4ms to free a
58MB allocation?

**Comment by anton-potapov** [comment]
While TBB has an API for worker thread pinning it does not do that by default.

**Comment by abadams** [comment]
Yes that should be sufficient, provided you don't intend to support the async branch - that makes the thread pool way more complicated. Those results don't sound surprising. We know our thread pool is great on linux, but we haven't battle-tested it to the same degree on windows. If the results hold up we should learn from what TBB does to improve our built-in windows thread pool too.

**Comment by zvookin** [comment]
The performance data above is very stale as we replaced a lot of the low-level thread pool synchronization. One should remeasure. (Especially on Windows and Mac.) The direction Halide is headed in makes replacing the thread pool in this way somewhat of a nonstarter as we will be supporting a more powerful concurrency model than most systems support. Easily at least. (Theoretically TBB supports quite a bit, but mapping our model onto theirs is pretty tricky and I'm not 100% convinced they guarantee deadlock freedom for the result.)

The async branch will be integrated fairly soon. (It's way overdue and we have a couple things that are blocked by it not being there.) If one does not use ```.async()``` in a schedule, then the existing thread pool replacement mechanism will still work. But this is already off the bat a significant constraint on Halide developers for one's system and I'm increasingly convinced it is not a good bet for the future.

**Comment by abadams** [comment]
Oh, I misread Marco's post as fresh data rather than a quoted reply.

**Comment by ashishUthama** [comment]
@zvookin  - thanks for sharing that vision, good to know this early since this would impact us.

I havent looked yet, but I assume there is a way to set the thread count with the Halide thread pool. That might allow me to switch over from TBB.

**Comment by steven-johnson** [comment]
halide_set_num_threads() should do what you want

**Comment by ashishUthama** [comment]
@steven-johnson  - I recall an early discussion that this function was not guaranteed to work on all platforms, especially mac - which is when I fell back to using TBB. Went looking for it and found #1371. From the comments/code there it looks like the only thing not supported now is setting N threads on OS X/iOS for N>1 (I guess there is a good reason for it.) 

That's not ideal, but should be good enough for us. Thank you!

**Comment by abadams** [comment]
Async makes TBB not particularly useful, and we still haven't seen any evidence that TBB is fast now that we use our linux strategy on all platforms. Looking forward, I think what people really want is a way to not have multiple thread pools in their app. We should consider a way to have the Halide task system just borrow threads from an existing task system. E.g. you'd enqueue a single tbb task which meant "act as a halide worker thread until you run out of work". It would be a fairly small change to the existing code I think. The worker thread function would just return in some circumstances instead of sleeping on a condition variable.

**Comment by zvookin** [comment]
Maybe. One has to be very careful that we do not get false dependencies via call frame ordering on the stack of a single thread. Likely the invariant has to be that there is never more than one Halide worker task on a given threadpool thread at a time. (The worker task may stack up multiple Halide tasks per our current design, but it cannot have any sort of reentry from the external thread pool.)

**Comment by abadams** [comment]
I think our conclusion is that async makes this impossible, and we don't believe it would be faster on any platform now. I don't want to discourage further experimentation, but this probably shouldn't be an open issue any more without fresh data.
