### ISSUE TITLE
profiler divide by zero

### ISSUE THREAD

**Issue by ibtaylor** [halide/Halide#1305]
https://github.com/halide/Halide/blob/master/src/runtime/profiler.cpp#L321

`p->time / 100` results in `0` when `p->time < 100`
causing a divide by zero exception in the expression `fs->time / (p->time / 100)`

identical behavior seems like
`percent = static_cast<int>(100.0f * fs->time / p->time)`
 (rounds down due to truncation)

**Comment by psuriana** [comment]
Fixed 41132ecd53f7eaea49a6cd16b7339da568e91cc8
