### ISSUE TITLE
halide blas: result not copied back to host when targeting OpenCL

### ISSUE THREAD

**Issue by ronghongbo** [halide/Halide#1306]
apps/linear_algebra/src/halide_blas.cpp: There are two issues. First, in this function
void init_vector_buffer(const int N, const float _x, const int incx, buffer_t *buff) {
    memset((void_)buff, 0, sizeof(buffer_t));
    buff->host = (uint8_t_)const_cast<float_>(x);
    buff->extent[0] = N;
    buff->stride[0] = incx;
    buff->elem_size = sizeof(float);
}
The function seems to have missed this statement: 
    buff->host_dirty = true;
Without it, the initialized values are not copied to device when execution. After adding it, the copy happens as expected. 

However, there is still another issue: the output is not copied from device back to host after the OpenCL kernel is executed.  The generated code is like this: 
......
%__halide_scopy_impl_result = # call i32 @**__halide_scopy_impl**(float %a, %struct.buffer_t\* %x.buffer, %struct.buffer_t\* %y.buffer, %struct.buffer_t\* %output.buffer) #9 **//Here the OpenCL kernel is called, but after it, there is no copy back to host, as you can see from the following code**
  %9 = icmp eq i32 %__halide_scopy_impl_result, 0
  br label %init_kernels

init_kernels:                                     ; preds = %entry
  %10 = call i32 @halide_opencl_initialize_kernels(i8\* null, i8*\* @module_state_halide_scopy_impl_opencl, i8\* getelementptr inbounds ([891 x i8], [891 x i8]\* @halide_halide_scopy_impl_opencl_kernel_src, i32 0, i32 0), i32 891)
  %11 = icmp eq i32 %10, 0
  br label %12

; <label>:12                                      ; preds = %init_kernels
  br label %destructor_block 

destructor_block:                                 ; preds = %12
  %13 = phi i32 [ 0, %12 ]
  ret i32 %13
}

**Comment by abadams** [comment]
We intentionally never copy back from the device in the generated code. The
user might want to pass the buffer into another function that operates on
it on the gpu. Call halide_copy_to_host on the buffer_t to do any copy-back
required.

Basically the linear algebra app was never written to use the GPU.
