### ISSUE TITLE
Error using vectorize(x,8): Can't use vector types when compiling to C (yet)

### ISSUE THREAD

**Issue by RileyLee** [halide/Halide#1365]
So I'm trying to compile the following code using genGen. But I got the error like this. The error comes up when I added vectorize in the line hor_convolved.compute_root().vectorize(x,8).parallel(y); Can anyone help me with this? Thank you so much!!!

Error:
Can't use vector types when compiling to C (yet)
make: **\* [build/halide/gaussblur_cpu.h] Abort trap: 6
make: **\* Deleting file `build/halide/gaussblur_cpu.h'
make: *** [build/halide/gaussblur_cpu.h] Deleting file`build/halide/gaussblur_cpu.o'

Here's my code. 

`#include "Halide.h"
# include "math.h"

using namespace Halide;
class Gaussblur: public Halide::Generator<Gaussblur>
{
public:
    float PI = 3.1415926f;
    Halide::ImageParam input{Halide::UInt(8), 3, "input"};
    float sigma = 2.0f;
    Halide::Expr width = input.width();
    Halide::Expr height = input.height();
    Halide::Var x, y, c;

```
Halide::Func build()
{
    Halide::Func filter;
    filter(x,y,c) = gaussBlur(input)(x,y,c);

    input.set_stride(0, 4);
    input.set_stride(2, 1);
    input.set_bounds(2, 0, 4);

    filter.output_buffer().set_stride(0, 4);
    filter.output_buffer().set_stride(2, 1);
    filter.bound(c, 0, 4);

    //if (get_target().has_feature(Halide::Target::OpenGL))
    //{
    //    filter.glsl(x,y,c);
    //}
    //std::cerr << "registered: " << (get_target().has_feature(Halide::Target::RegisterMetadata) ? "yes" : "no") << std::endl;

    return filter;
}

Halide::Func gaussBlur(const Func in)
{
    // Gaussian Blur using separable filters from x and y directions.
    Var xi, yi;
    Func buf_in;
    buf_in(x,y,c) = Halide::cast<float>(in(x,y,c))/255.0f;
    const float norm = 1.0f / sqrt(2.0f * PI * sigma * sigma);
    const int radius = ceil(3.0f * sigma);
    const int size = 2 * radius + 1;
    Func gaussian("FunGaussian"), kernel("KernelGaussian"), hor_convolved("hor_convolved"), out("gauss_blurred"), final;

    Halide::RDom i(-radius, size);
    gaussian(x) = exp(-pow(cast<float>(x), 2.0f) / (2.0f * sigma * sigma));
    gaussian.bound(x,-radius, 2*radius+1);
    gaussian.compute_root();

    kernel(x) = (norm * gaussian(x-radius)) / sum(norm * gaussian(i));
    kernel.bound(x, 0, 2*radius+1);
    kernel.compute_root();

    hor_convolved(x,y,c) = conv1d(buf_in, kernel, size, false)(x,y,c);
    hor_convolved.compute_root().vectorize(x,8).parallel(y);
    final(x,y,c) = conv1d(hor_convolved, kernel, size, true)(x,y,c);
    out(x,y,c) = cast<uint8_t>(clamp(final(x,y,c)*255.0f,0.0f,255.0f));
    out(x,y,3) = cast<uint8_t>(255);
    return out;
}

Halide::Func conv1d(const Func in, const Func kernel, const int kernellen, const bool dir)
{
    //Function con1d convolves input 2D array in with the input directional 1D filter kernel.
    //in -- input 2d array.
    //kernel -- input 1d kernel array.
    //kernellen -- kernel length
    //dir -- bool variable controls direction. true horizontal. false vertical.
    Func out("Conv1D");

    Halide::RDom kern(0, kernellen);
    Expr coordx = clamp(x+kern-(kernellen/2), 0, width-1);
    Expr coordy = clamp(y+kern-(kernellen/2), 0, height-1);

    out(x,y,c) = select(!dir, sum(kernel(kern) * in(coordx, y, c)), sum(kernel(kern) * in(x, coordy, c)));
    return out;
}
```

};

Halide::RegisterGenerator<Gaussblur> gaussblurGenerator{"gaussblur"};`

**Comment by zvookin** [comment]
Are you using gengen to emit C code as output? If so, the vectorize
scheduling directive will not work.

-Z-

**Comment by ravi-teja-mullapudi** [comment]
Halide does not currently support vectorize when generating C. One thing
that could possibly be done is to transform the vectorize directive to
#pragma simd or a #pragma ivdep so that the downstream compiler can handle
the vectorization if it deems so.

I did this at one point in a fork of the Halide repository it should not be
very hard to make a pull request based off of this.
https://github.com/ravi-teja-mullapudi/Halide/blob/master/src/CodeGen_C.cpp#L1358

**Comment by ravi-teja-mullapudi** [comment]
This change should also be accompanied by skipping the vectorization pass
when emitting C.
https://github.com/ravi-teja-mullapudi/Halide/blob/master/src/Lower.cpp#L236

**Comment by RileyLee** [comment]
Thank you so much Ravi and zvookin. Yeah you're right. I changed my makefile using Gengen. I should not generate cpp code which include vectorize command.

**Comment by zvookin** [comment]
Likely will be fixed by https://github.com/halide/Halide/pull/2067, which has the C backend generate vector operations for gcc and clang.
