### ISSUE TITLE
How to efficiently use param?

### ISSUE THREAD

**Issue by RileyLee** [halide/Halide#1387]
I'm building high-performance image processing filters using halide. Users are able to move a slider to adjust multiple controlling parameters. But these parameters are basically Expr like `Halide::Param<float> sigma{"coherence",2.0f,0.0f,20.0f};`. When I use this in reduction domain `RDom(1,cast<int>(sigma*3.0f))`, my code runs way slower than simply define those parameters in float format. Could anyone think of a way, so I can use slider while maintaining high performance? Thanks.

**Comment by zvookin** [comment]
@RileyLee IS this still an issue? Without example code, it will be tricky to do anything here. There are a number of reasons more complicated loop bounds can make things slower due to less simplification of the code inside loops.
