### ISSUE TITLE
OpenGL backend broken by commit 5a9ccc23

### ISSUE THREAD

**Issue by shoaibkamil** [halide/Halide#1418]
Multiple tests no longer pass (e.g. `opengl_lut`).  I bisected, and the commit causing the breakage is 5a9ccc23215c98f64cff216648f6279cdf15787e.

I realize the OpenGL backend *shouldn't* be vectorizing etc before the vectorization passes, but we should work around that until someone has a chance to rewrite the backend to be more reasonable.

**Comment by abadams** [comment]
Working on it.
