### ISSUE TITLE
Commit db0db0 breaks OpenGL backend

### ISSUE THREAD

**Issue by shoaibkamil** [halide/Halide#1462]
Commit db0db0d5cd breaks the OpenGL backend; running a test results in a segfault.  It looks like the string representing the shaders (passed to `halide_opengl_init_kernels()`) is incomplete.  Commit eee04c6 seems to work fine.

**Comment by abadams** [comment]
I don't think it could be that commit itself - it doesn't do anything that could effect opengl codegen. But here's the diff of the repo in between those commits:

https://github.com/halide/halide/compare/eee04c664c003071c8fde397be3b5657638ae443...db0db0d5cd99960ea089e2b70f5508b7ce6105f5

It must be something in one of the last few opengl PRs.

**Comment by abadams** [comment]
Hopefully fixed by 5008fe4e658bda4a7db4e15ae36863c3241df70b ?

**Comment by shoaibkamil** [comment]
Yup, fixed.  This one was all my fault-- thanks for the quick fix!
