### ISSUE TITLE
Hexagon 3.0 tools build

### ISSUE THREAD

**Issue by victorv** [halide/Halide#1482]
Error may be related to using unsupported Hexagon 3.0 tools. Waiting for access to 3.1 tools. This is just for others who may get this error. I will update with results after getting 3.1 tools.

[ 98%] Linking CXX executable ../../../../bin/clang
/usr/bin/ld: ../../../../lib/libLLVMHexagonDesc.a(HexagonMCInstrInfo.cpp.o): bad reloc symbol index (0x6c6c344e >= 0x169) for offset 0x24 in section `.text._ZN4llvm18HexagonMCInstrInfo12isExtendableERKNS_11MCInstrInfoERKNS_6MCInstE'
../../../../lib/libLLVMHexagonDesc.a: error adding symbols: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [bin/clang-3.9] Error 1
make[1]: **\* [tools/clang/tools/driver/CMakeFiles/clang.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....

**Comment by zvookin** [comment]
@dsharletg @ronlieb @victorv Can this bug be closed now? Much has changed in this area since it was filed.

**Comment by victorv** [comment]
Yes - thanks.
