### ISSUE TITLE
Compilation gives unexpected output

### ISSUE THREAD

**Issue by guusleijsten** [halide/Halide#1492]
I am not sure if this is an error on my side, or the machines side, but I am getting an ".a" file while expecting a ".o" file. 

I have been going through the tutorials, during lesson 10, I already got stuck on the second step. Got a " lesson_10_halide.o" not found error. This makes sense because the generator had generated a  "lesson_10_halide.a" instead. Obviously replacing  lesson_10_halide.o with  lesson_10_halide.a in the command gave a lot more errors..

Well now I am at lesson 15, again there is this line of code in the sh file of the second part:
check_file_exists my_first_generator.o

I am sure that it will fail as it generated check_file_exists my_first_generator.a instead.

Any suggestions how to resolve this problem that I am having?

I am running on a Ubuntu virtual machine on a windows host machine.

**Comment by guusleijsten** [comment]
not an issue, in the tutorial is ".o", however from the newest git clone there is an ".a" instead. :)

**Comment by abadams** [comment]
Thanks, I've updated the online tutorials to match the last release
