### ISSUE TITLE
Difficulties with non-linear domain

### ISSUE THREAD

**Issue by guusleijsten** [halide/Halide#1517]
I am working on an Halide implementation of a multistage pipeline for raw image processing.
One of these stages is to correct defect pixels. I am given a list of defect pixels that are given as comma-separated values from an XML file.

The problem is that I have been focusing do this for each x and each y, now I want a operation to be performed only by specified x and y coordinates.

Is there a special var that can have the values 3, 6, 7 for x-domain and 581,  51, 10 in the y-domain?
Are there any examples that I overlooked that tackle a similar problem?

Perhaps it is possible to construct a Var from a std::vector?

Any ideas that might be helpful? Thanks in advance.

Kind regards.

**Comment by guusleijsten** [comment]
One approach may be to build a for loop to traverse the pixel list. Then use the values to reference a Halide::Func.
For example if list was {(1,3), (5,15)}, and assuming that there is a method that returns Halide::Func, named fixPixels. I thinking about implementing it similar to the pseudo code below:
for each item in list // gives x and y for item
do
  fixPixel(item.x, item.y);
endfor

And then merge it with the full pixel list.

I am not sure if it is unusual to mix Halide code with a for loop that traverses over an std::vector.
Again, I am open to any suggestions.

**Comment by guusleijsten** [comment]
From the docs and some knowledge about RDom I think I found a suitable type to achieve my goal.
From the description I found that I can construct an RDom from an std::vector this is exactly what I need!

From the online documentation:
NO_INLINE  RDom (const std::vector< std::pair< Expr, Expr >> &ranges, std::string name="")

I will try this later today, or tomorrow morning, as it is almost 6pm here.

**Comment by abadams** [comment]
I think what you want to do is take the list of bad pixel locations as an
input ImageParam, and then use an RDom to iterate over it:

ImageParam bad_pixel_locations(Int(32), 2)
RDom r(0, bad_pixel_locations.extent(1))

f(bad_pixel_locations(0, r), bad_pixel_locations(1, r)) = ...

**Comment by guusleijsten** [comment]
This might be what I am looking for, thanks!
I will try it out later.

**Comment by guusleijsten** [comment]
When implementing this in the way described by @abadams I get the following error:
Buffer processed may be accessed in an unbounded way in dimension 0,
Is there a way to bound the values of the image so that I can specify that the way I use them is bounded?

**Comment by guusleijsten** [comment]
Nevermind, this has been solved by using clamp. However I encountered a different problem so I am trying a completely different approach

**Comment by ck3d** [comment]
I implemented the proposal from @abadams and I got the same error same error message as @guusleijsten .
```
Buffer<int32_t> input{100, 100};

Buffer<int32_t> pixels{2, 1};
pixels(0, 0) = 2;
pixels(1, 0) = 3;

RDom r(pixels.dim(1).min(), pixels.dim(1).max());
Func clamped = BoundaryConditions::repeat_edge(input);
Var x, y;
Func copy;
copy(x, y) = clamped(x, y);
copy(pixels(r, 0), pixels(r, 1)) = 0;
Buffer<int32_t> output = copy.realize(4, 4);
```
raises error:
`Buffer f0 may be accessed in an unbounded way in dimension 0`

Any idea how to solve the issue?

**Comment by ck3d** [comment]
Sorry, I could fix it by using clamp(pixels(r, 0)).
