### ISSUE TITLE
correctness_fuzz_simplify segfaults with seed=1475018664 on Linux-x86-64.

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#1524]
Randomly found during unrelated testing. Interestingly, does not fail for me on OSX-64.

**Comment by steven-johnson** [comment]
Looks like it's endless recursion in Simplify stomping on the stack.

**Comment by steven-johnson** [comment]
The failing expression is:

((select((int32x2(uint8x2(x2((uint1)1))) < (int32x2(ramp((uint16)65422, (uint16)38, 2)) - x2(-16))), ramp(int32(e), int32(c), 2), (x2(int32(e)) % x2(int32(e)))) + (ramp(int32(d), -17, 2) % x2(int32(b)))) - ramp(int32(d), int32(b), 2))

**Comment by psuriana** [comment]
See #1525 for the fix.

**Comment by steven-johnson** [comment]
I'll follow up on my own to figure out why OSX is *not* crashing as it should be.
