### ISSUE TITLE
Non-terminating pipeline for demosaic implementation

### ISSUE THREAD

**Issue by guusleijsten** [halide/Halide#1528]
I have been translating a c++ file into Halide. I got it functionally correct however it takes a really long time to execute.
I was waiting with the schedule, but I guess I really do need it now. because It is taking around 6 seconds to execute when isolated, and it never terminates when put together with some other stages of the pipeline. 
Hence I was wondering how to do the automatical scheduling from the paper "Automatically Scheduling Halide Image Processing Pipelines". Is this currently being done automatically or is it normal that my pipelines have been executing without me ever specifying a schedule?

**Comment by guusleijsten** [comment]
One last remark, the demosaic alg. currently takes around 6 seconds, this is way too long. So I am looking for alternative implementations, however it should produce the exact same output.

**Comment by guusleijsten** [comment]
A simplified version of the demosaic process (however not simple enough :p):

Func MeasureHorizontalChange(Func raw) {
	Var x, y;
	Expr sum_r_1_1 = raw(x-2, y) - raw(x, y); //compares raw(x-2, y) to raw(x, y)
        //compares raw(x-2, y-2) to raw(x, y-2)
        //compares raw(x-2, y+2) to raw(x, y+2)
        //also compares raw(x+2, y...) to raw(x, y...)\
        //and x+-1, y... as well.
        Func change(x, y) = sum of above expressions / 4.
}
Func MeasureVerticalChange(Func raw) {
  //similar to the above method.
}

Then I have a method 'Func demosaic(Func raw)' that calls the above two methods and then some more Expressions are followed and a three level deep select statement. To perform either horizontal, vertical or bi-directional interpolation of neighboring pixels.

I am currently working on reimplementing it in a more efficient manner, because for each pixel the whole MeasureHorizontalChange table is recompute while it could have used the values of the neighboring pixel.

I will post again with my progression

**Comment by guusleijsten** [comment]
This again is one classic example why Halide is so powerful. Look at the following implementation, it represents a direct translation of a c++ file where you take an array of 25 elements, and put 5x5 grid around the pixel in there and do the following:
`Func MeasureHorizontalChange(Func raw) {
	Expr sum_r_1_1 = raw(x-2, y) - raw(x, y);
	Expr sum_r_1_2 = raw(x-2, y-2) - raw(x, y-2);
	Expr sum_r_1_3 = raw(x-2, y+2) - raw(x, y+2);
	Expr sum_r_1 = abs(sum_r_1_1) + abs(sum_r_1_2) + abs(sum_r_1_3);
	
	Expr sum_r_2_1 = raw(x+2, y) - raw(x, y);
	Expr sum_r_2_2 = raw(x+2, y-2) - raw(x, y-2);
	Expr sum_r_2_3 = raw(x+2, y+2) - raw(x, y+2);
	Expr sum_r_2 = abs(sum_r_2_1) + abs(sum_r_2_2) + abs(sum_r_2_3);
	
	Expr sum_g_1 = raw(x-2, y-1) - raw(x, y-1);
	Expr sum_g_2 = raw(x-2, y+1) - raw(x, y+1);
	Expr sum_g_3 = raw(x+2, y-1) - raw(x, y-1);
	Expr sum_g_4 = raw(x+2, y+1) - raw(x, y+1);
	Expr sum_g = abs(sum_g_1) + abs(sum_g_2) + abs(sum_g_3) + abs(sum_g_4);
	
	Expr sum_gr_1_1 = raw(x-1, y-2) - raw(x, y-2);
	Expr sum_gr_1_2 = raw(x-1, y) - raw(x, y);
	Expr sum_gr_1_3 = raw(x-1, y+2) - raw(x, y+2);
	Expr sum_gr_1 = abs(sum_gr_1_1) + abs(sum_gr_1_2) + abs(sum_gr_1_3);
	
	Expr sum_gr_2_1 = raw(x+1, y-2) - raw(x, y-2);
	Expr sum_gr_2_2 = raw(x+1, y) - raw(x, y);
	Expr sum_gr_2_3 = raw(x+1, y+2) - raw(x, y+2);
	Expr sum_gr_2 = abs(sum_gr_2_1) + abs(sum_gr_2_2) + abs(sum_gr_2_3);
	
	Expr sum_bg_1 = raw(x-1, y-1) - raw(x, y-1);
	Expr sum_bg_2 = raw(x+1, y-1) - raw(x, y-1);
	Expr sum_bg_3 = raw(x-1, y+1) - raw(x, y+1);
	Expr sum_bg_4 = raw(x+1, y+1) - raw(x, y+1);
	Expr sum_bg = abs(sum_bg_1) + abs(sum_bg_2) + abs(sum_bg_3) + abs(sum_bg_4);
	
	Expr sum_gha = cast<double>(raw(x-1, y) + raw(x+1, y)) / 2.0f;
	
	// LH is for measuring horizontal change.
	Func output;
	output(x, y) = sum_r_1 + sum_r_2 + sum_g +
        (sum_gr_1 + sum_gr_2 + sum_bg + sum_gha) / 4.0f;
	return output;
}`

Note that it takes for each row and each column the difference between the outermost with the middle, and the neighbor of the middle element of each row/col.
This is why it is performing so badly, similar to the original c++ implementation you do all there calculations multiple times. But this is a typical producer-consumer pattern so I will rewrite it as such.
Can you verify the final schedule once done? I need high performance in this part because it is the bottleneck of the original RAW pipeline that I am trying to optimise.

**Comment by guusleijsten** [comment]
I got to reduce it to this: 
Expr diff(Expr a, Expr b, Expr c, Expr d, Expr e)
{
	return abs(a - c) + cast<double>(abs(b - c))/4.0f + cast<double>(abs(d - c))/4.0f + abs(e - c);
}

Func measureChange(Func in) {
	Func rowDiff("row"), horDiff("hor"), colDiff("col"), verDiff("ver");
	rowDiff(x, y) = diff(in(x-2, y), in(x-1, y), in(x, y), in(x+1, y), in(x+2, y));
	horDiff(x, y) = rowDiff(x, y-2) + rowDiff(x, y-1) + rowDiff(x, y+1) + rowDiff(x, y+2);

	colDiff(x, y) = diff(in(x, y-2), in(x, y-1), in(x, y), in(x, y+1), in(x, y+2));
	verDiff(x, y) = colDiff(x-2, y) + colDiff(x-1, y) + colDiff(x+1, y) + colDiff(x+2, y);
}

in the tutorial you use producer.compute_at(consumer), so it should be rowDiff.compute_at(horDiff), right?

**Comment by guusleijsten** [comment]
Thank you for having such an instructive tutorial and I am getting more impressed with Halide, that is if I get this to run with an reasonable execution time.

**Comment by dsharletg** [comment]
You might be interested in the camera pipe app, which contains a demosaic example (https://github.com/halide/Halide/blob/master/apps/camera_pipe/camera_pipe.cpp#L51). The demosaic there is not very high quality, but the basic concepts are applicable to most demosaic algorithms.

**Comment by guusleijsten** [comment]
Thanks, I will look at it once more. It was indeed a low quality version of the algorithm. I need identical functional behaviour as an existing implementation. However I did use parts of "camera pipe app” for chromatic aberration reduction.

Kind regards.
