### ISSUE TITLE
Producing multiple outputs where outputs have different extends for each free variable. 

### ISSUE THREAD

**Issue by kgeorgen** [halide/Halide#1529]
**How can I produce multiple outputs from a Halide application where outputs have different extends for each free variable?** 

To elaborate, I am trying to develop a Halide application that accepts an RGB image and produces the corresponding Y, U and V channels. Additionally, I want the U and V channels to be subsampled by a factor 2 along with the width and height. Therefore, if Y(x,y), U(x,y) and V(x,y) are values for each channel at (x,y), and RGB(x,y) is the color values at pixel (x,y), 
    Y(x,y) = f(RGB(x,y))
    U(x,y) = f(RGB(x_2,y_2), RGB(x_2+1,y_2), RGB(x_2, y_2+1), RGB(x_2+1, y_2+1)) 
    V(x,y) = f(RGB(x_2,y_2), RGB(x_2+1, y_2), RGB(x_2, y_2+1), RGB(x_2+1, y_2+1))

How can we model this computation in Halide? 

Thanks in advance for any suggestions.

**Comment by zvookin** [comment]
Combine multiple Funcs into a Pipeline.
See: test/correctness/multiple_outputs.cpp.

-Z-

**Comment by kgeorgen** [comment]
That seems like what I was looking for. Thank you very much!

**Comment by kgeorgen** [comment]
I am reopening this issue because the approach of generating multiple outputs mentioned above (i.e., by combining **Func**s into a **Pipeline**) does not seem to work for some targets. While generating OpenCL code, each **Func** in the **Pipeline** is generated as separate kernel. However, I want to generate a single kernel that produces multiple outputs. 

Is it possible to generate a single OpenCL kernel that produces multiple outputs? 

Thanks in advance!

**Comment by abadams** [comment]
We have a branch with a prototype feature compute_with that I think would
solve this.

@psuriana - I think this would be an interested example to test - computing
multiple outputs of different sizes or dimensionalities in the same gpu
block loop.

**Comment by kgeorgen** [comment]
That's great! I would definitely take a look. Thank you for the quick reply. 

@psuriana - If you test this new feature and are able to generate multiple outputs from the same gpu block, can you please let us know? 

Thanks again!

**Comment by psuriana** [comment]
@kgeorgen - Yes it is possible to fuse the GPU blocks of multiple outputs. See `multiple_outputs_on_gpu_test` in #1546. This feature needs #1641 to land first to work however.

**Comment by dsharletg** [comment]
I think this has been fixed by the two PRs psuriana mentioned.
