### ISSUE TITLE
Implementation problems, demosaic alg

### ISSUE THREAD

**Issue by guusleijsten** [halide/Halide#1531]
Hi, 

I encountered some inconveniences. The first one which is also simplest to solve. it is that I am performing a demosaic process in Halide. Now I was using select statements but instead of that I will use tuples. But the first element is green, so I want to put it in the middle of the tuple. Now the next value is red, so put it left in the tuple... and so on. 

POST REMOVED**

**Comment by dsharletg** [comment]
select is really the right thing to use here. Especially for something like a demosaic, the benefits of being able to vectorize will significantly outweigh the compute wasted on unused values.

**Comment by guusleijsten** [comment]
Okay, so I am still playing with how to compute horizontal- and vertical_change, this is 
implemented in 7 lines (and put in function 'div'). However the if-else statement in the pseudo code above ended up as follows.

So i use one select statement to pick the correct expression that interpolates the values of the pixels (horizontally, vertically or bidirectional). Then another select to make sure only non-green pixels perform interpolation. Would it be better to just calculate each interpolation method and select the correct one??

```
    // Interpolate Green pixels: bipolair, vertically and horizontally respectively.
	Expr Gbi = cast<double>(raw(x, y-1) + raw(x, y+1) + raw(x-1, y) + raw(x+1, y))
		/ 4.0f + cast<double>(4.0f * raw(x, y) - raw(x, y-2) - raw(x, y+2) -
		raw(x-2, y) - raw(x+2, y)) / 8.0f;
    Expr Gver = cast<double>(raw(x, y-1) + raw(x, y+1)) / 2.0f +
        cast<double>(2.0f * raw(x, y) - raw(x, y-2) - raw(x, y+2)) / 4.0f;
    Expr Ghor = cast<double>(raw(x-1, y) + raw(x+1, y)) / 2.0f +
        cast<double>(2.0f * raw(x, y) - raw(x-2, y) - raw(x+2, y)) / 4.0f;
	
	// Some helper variables
	Expr RG_line = (y%2) ^ RGLINE;
	Expr Green_start = (x%2) ^ GSTART;
	Expr Edge_threshold = 1.5f;
	Expr self = cast<double>(raw(x, y));
	
	// RGRGRG -> R or GBGBGB -> B
	Expr HorORVer = select(div(x, y)[0] > div(x, y)[1],
					select(div(x, y)[0] > Edge_threshold, Gver, Gbi),
					select(div(x, y)[1] > Edge_threshold, Ghor, Gbi));
	// Whole if-else nests pack inlined.
	// Selects either raw(x,y), namely if you are at green pixel in raw image.
	// Or takes Gver if LHoverLV > horizontal and above threshold, similar for
	// Ghor or Gbi if none of the above.
	Expr green = select(RG_line == 0, select(Green_start == 0, HorORVer, self),
									  select(Green_start == 0, self, HorORVer));
	Func R("r"), G("g"), B("b");
	G(x, y) = cast<uint16_t>(clamp(green, 0, 4095));
```

**Comment by guusleijsten** [comment]
Hmm computing them all in tuples, is the alternative I was trying to explain,
interpolates(x, y) = {Gbi(x, y), Gver(x, y), Ghor(x, y)} 
Now I compute all of these for each pixel. However I just want to compute them for the green pixels. That is where the second select comes in.

My running time now is around 2s, any ideas on how to optimise this?

**Comment by guusleijsten** [comment]
Are there any alternatives to select statements?

The select is nested too deeply to see what is going on. The execution is too slow and I would like to optimize this part in particular.
