### ISSUE TITLE
target.set_feature(Target::Debug); doesn't do anything

### ISSUE THREAD

**Issue by fbriggs** [halide/Halide#1542]
The tutorial on using the GPU says,
"If you want to see all of the OpenCL, Metal, or CUDA API calls done by the pipeline, you can also enable the Debug  flag. This is helpful for figuring out which stages are slow, or when CPU -> GPU copies happen."

I have the following code in my generator:
```
  Target target = get_target_from_environment();
  target.set_feature(Target::OpenCL);
  target.set_feature(Target::Debug);
```

Adding the last line 'target.set_feature(Target::Debug);' doesn't seem to do anything. It is not printing any more debug information than it did before. I am using OS X 10.11.6, LLVM 3.7, and the latest commit of Halide.

Is there something else I am supposed to do to see debug messages? Is this feature broken? Thanks...

**Comment by abadams** [comment]
How are you using the target object after setting it up?

Also, are some of your stages scheduled with .gpu_tile or similar?

I use the feature often, so it's not broken.

- Andrew

**Comment by fbriggs** [comment]
Hi Andrew,
Thanks for your quick response. There are gpu_tile scheduled parts of the pipeline. The target object is used in part of an AOT compilation. Specifically I call compile_to_static_library and compile_to_assembly, then in another phase of compilation the halide generated code is linked with the host project code.

**Comment by abadams** [comment]
Hrm, that should work. It should be calling halide_print at runtime when
the pipeline runs whenever it invokes an opencl or similar call. If you're
on android that goes to adb logcat, but otherwise it comes out of stdout.

**Comment by fbriggs** [comment]
I found the problem... I needed to build with HL_TARGET=host-opencl-debug instead of HL_TARGET=host-opencl. After using HL_TARGET=host-opencl-debug, I get a lot more debug output.
