### ISSUE TITLE
can't find a valid GPU-only schedule for Gaussian blur

### ISSUE THREAD

**Issue by fbriggs** [halide/Halide#1545]
I am trying to implement optical flow in Halide with GPU acceleration, and one piece of that is a Gaussian blur. I have this working on CPU, but while trying to make it run on GPU, I am running in to the problem that I can't find any valid schedule that does the whole computation on the GPU and avoids doing parts of it on the CPU.  As a side note, I haven't been able to get set_feature(Target::Debug) to work (see https://github.com/halide/Halide/issues/1542), so I'm not 100% sure where copies between CPU and GPU are happening (instead I am trying to infer this from the print_loop_nest() output).

First, here is all of the code involved in an AOT compiled test case for Gaussian Blur (the name of the halide generator is HalideOpticalFlowGen, but all it is doing in this case is the blur). The host application uses OpenCV, so there is an interface/wrapper converting opencv's Mat class to Halide Buffers. I am using LLVM 3.7, Mac OS X 10.11.6, and the latest commit of Halide (5ec44551f19a873f6a2445d679fdbbbc6a0a54f7).

Halide code for Gaussian blur, working CPU version:

```
Func gaussianBlur(Expr w, Expr h, Func I, const int boxSize, const float sigma) {
  assert(boxSize % 2 != 0 && "boxSize must be odd");

  const int radius = (boxSize - 1) / 2;
  vector<float> k(radius * 2 + 1);
  float ksum = 0.0f;
  for (int i = -radius; i <= radius; ++i) {
    const float ki = exp(-i * i / (2.0f * sigma * sigma));
    k[i + radius] = ki;
    ksum += ki;
  }
  Image<float> kernel(radius * 2 + 1);
  for (int i = 0; i < k.size(); ++i) {
    kernel(i) = k[i] / ksum;
  }

  Var x("x"), y("y");
  RDom r(-radius, 2 * radius + 1);
  Func blurY("blurY"), blurX("blurX");
  blurY(x, y) = sum(kernel(r + radius) * I(clamp(x, 0, w - 1), clamp(y + r, 0, h - 1)));
  blurX(x, y) = sum(kernel(r + radius) * blurY(clamp(x + r, 0, w - 1), clamp(y, 0, h - 1)));
  return blurX;
}
```

Wrapper/interface between Halide Buffer and opencv Mat:

```
struct CvMat2HalideBuffer {
  Halide::Buffer<float, 2> buffer;
  buffer_t* bufferPtr;

  CvMat2HalideBuffer(cv::Mat& mat) {
    assert(mat.type() == CV_32F);
    static const int kChannels = 1;
    static const int kDepth = 1;
    halide_dimension_t shape[2] = {
      {0, mat.cols, 1},
      {0, mat.rows, mat.cols}};

    buffer = Halide::Buffer<float, 2>(
      Halide::type_of<float>(), mat.data, 2, shape);
    bufferPtr = buffer.raw_buffer();
  }
};
```

Halide generator main(), CPU-version:

```
int main(int argc, char** argv) {

  cout << "halide optical flow generator" << endl;

  ImageParam I0(Halide::type_of<float>(), 2, "I0");
  vector<Argument> args = {I0};

  Var x("x"), y("y");
  Func I0func("I0func"); // convert from ImageParam to Func
  I0func(x, y) = I0(x, y);

  Func output("output");
  output = gaussianBlur(I0.width(), I0.height(), I0func, 15, 5.0);

  output.print_loop_nest();
  Target target = get_target_from_environment();

  output.compile_to_static_library("HalideOpticalFlowGen", args, "HalideOpticalFlowGen");
  output.compile_to_assembly("HalideOpticalFlowGen.s", args, "HalideOpticalFlowGen");

  return EXIT_SUCCESS;
}
```

Test code, compiled in second pass after Halide generator runs:

```
void testGaussianBlur() {
  Mat imgRBG = imreadExceptionOnFail(FLAGS_image0, -1); // -1 = load RGBA
  Mat imgMat;
  cvtColor(imgRBG, imgMat, CV_BGR2GRAY);
  imgMat.convertTo(imgMat, CV_32F, 1.0f / 255.0f);

  CvMat2HalideBuffer inBuffer(imgMat);
  Mat outMat(imgMat.size(), CV_32F);
  CvMat2HalideBuffer outBuffer(outMat);

  const double startTime = getCurrTimeSec();
  HalideOpticalFlowGen(inBuffer.bufferPtr, outBuffer.bufferPtr);
  const double endTime = getCurrTimeSec();
  cout << "runtime HalideOpticalFlowGen=" << (endTime - startTime) << endl;

  imshow("outMat", outMat);
  waitKey(0);
}
```

So all of that works, and produces the expected output. However, I run into lots problems trying to run this on the GPU. For example, suppose I change the generator main to use OpenCL, then the part where it sets up the target looks like this:
```
  ...
  Target target = get_target_from_environment();
  target.set_feature(Target::Debug);
  target.set_feature(Target::OpenCL);
  ...
```
and the Gaussian blur code is modified by adding this schedule at the end:
`  blurX.gpu_tile(x, y, 8, 8);
`
With these changes, I get a runtime error:
```
Error: CL: clEnqueueWriteBufferRect failed: CL_INVALID_VALUE
Abort trap: 6
```
Next, I modify the code for Gaussian blur so that it doesn't use the sum() halide reduction:

```
  ...
  Var x("x"), y("y");
  RDom r(-radius, 2 * radius + 1);
  Func blurY("blurY"), blurX("blurX");

  blurY(x, y) += kernel(r + radius) * I(clamp(x, 0, w - 1), clamp(y + r, 0, h - 1));
  blurX(x, y) += kernel(r + radius) * blurY(clamp(x + r, 0, w - 1), clamp(y, 0, h - 1));

  blurX.gpu_tile(x, y, 8, 8);

  return blurX;
```
This version runs OK, but the output from print_loop_nest() is:
```
produce blurX:
  parallel y.__block_id_y:
    parallel x.__block_id_x:
      parallel y.__thread_id_y in [0, 7]:
        parallel x.__thread_id_x in [0, 7]:
          blurX(...) = ...
  for y:
    for x:
      for r4:
        produce blurY:
          for y:
            for x:
              blurY(...) = ...
          for y:
            for x:
              for r4:
                blurY(...) = ...
        consume blurY:
          blurX(...) = ...
consume blurX:
```
I could be confused here, but my interpretation of this output is that it is only using the GPU for the initialization of blurX, and that the updates to blurX and blurY are actually happening on the CPU.

Next, I tried a different schedule:
```
  blurX.compute_root().gpu_tile(x, y, 8, 8);
  blurY.compute_root().gpu_tile(x, y, 8, 8);
  blurX.update(0).gpu_tile(x, y, 8, 8);
  blurY.update(0).gpu_tile(x, y, 8, 8);
```
This produces the following loop structure, which looks like it will be all on the GPU:
```
produce blurY:
  parallel y.__block_id_y:
    parallel x.__block_id_x:
      parallel y.__thread_id_y in [0, 7]:
        parallel x.__thread_id_x in [0, 7]:
          blurY(...) = ...
  parallel y.__block_id_y:
    parallel x.__block_id_x:
      parallel y.__thread_id_y in [0, 7]:
        parallel x.__thread_id_x in [0, 7]:
          for r4:
            blurY(...) = ...
consume blurY:
  produce blurX:
    parallel y.__block_id_y:
      parallel x.__block_id_x:
        parallel y.__thread_id_y in [0, 7]:
          parallel x.__thread_id_x in [0, 7]:
            blurX(...) = ...
    parallel y.__block_id_y:
      parallel x.__block_id_x:
        parallel y.__thread_id_y in [0, 7]:
          parallel x.__thread_id_x in [0, 7]:
            for r4:
              blurX(...) = ...
  consume blurX:
```
This version crashes with a runtime error:
```
Error: Output buffer blurX is accessed at 455, which is beyond the max (449) in dimension 0
Abort trap: 6
```

Here is another version of gassianBlur, which uses 1 pass instead of 2 passes (definitely less efficient for CPU, maybe not for GPU):

```
Func gaussianBlur(Expr w, Expr h, Func I, const int boxSize, const float sigma) {
  assert(boxSize % 2 != 0 && "boxSize must be odd");

  const int radius = (boxSize - 1) / 2;
  vector<float> k(radius * 2 + 1);
  float ksum = 0.0f;
  for (int i = -radius; i <= radius; ++i) {
    const float ki = exp(-i * i / (2.0f * sigma * sigma));
    k[i + radius] = ki;
    ksum += ki;
  }
  Image<float> kernel(radius * 2 + 1, radius * 2 + 1);
  for (int j = 0; j < k.size(); ++j) {
    for (int i = 0; i < k.size(); ++i) {
      kernel(i, j) = k[i] * k[j] / (ksum * ksum);
    }
  }

  Var x("x"), y("y");
  RDom r(-radius, 2 * radius + 1, -radius, 2 * radius + 1);
  Func blur("blur");
  blur(x, y) += kernel(r.x + radius, r.y + radius) * I(clamp(x + r.x, 0, w - 1), clamp(y + r.y, 0, h - 1));

  return blur;
}
```
This version is CPU only, and works as expected. Adding a GPU schedule:
`blur.compute_root().gpu_tile(x, y, 8, 8);`
... works but mixes CPU and GPU.
Another schedule:
```
  blur.compute_root().gpu_tile(x, y, 8, 8);
  blur.update(0).gpu_tile(x, y, 8, 8);
```
...crashes with error:
```
Error: Output buffer blur is accessed at 455, which is beyond the max (449) in dimension 0
Abort trap: 6
```

I have tried a lot of other variations, but so far I haven't found anything that is 100% GPU and doesn't crash. Some other variations have triggered the internal_assert(!device_read && !device_wrote); on line 301 of InjectHostDevBufferCopies.cpp.

I have also tried using Metal instead of OpenCL on OS X. If I change the target to Target::Metal and use env variable HL_TARGET=host-metal, then I get the following error at link time:
```
Undefined symbols for architecture x86_64:
  "_MTLCreateSystemDefaultDevice", referenced from:
      _halide_metal_acquire_context in HalideOpticalFlowGen.a(HalideOpticalFlowGen.a.o)
ld: symbol(s) not found for architecture x86_64
```

Any ideas on how to schedule this code for OpenCL or how to use Metal are appreciated.... thanks!

**Comment by zvookin** [comment]
Seems like you've already figured out that you need to schedule both the
pure stage and the update stages for any reductions.

The error:
    Error: Output buffer blur is accessed at 455, which is beyond the max
(449) in dimension 0
is one of boundary conditions. How are you handling the edges of the image?
Generally speaking, tiling can expand the area of the input that is read
and you can either handle that by making sure the input buffer is large
enough, including any expansion due to splits, or using the
BoundaryConditions functions to assert a boundary condition on the input.
You can also try passing TailStrategy::GuardWithIf to the gpu_tile calls.

Generally to get all the computation on the GPU, you want anything that has
storage to be scheduled with gpu_tile or compute_at on something that is.

The Metal error and the InjectHostDevBufferCopies.cpp assertion are very
likely bugs. I'll try to look at the Metal one. Ditto the debug issue. I
expect the MEtal one will be relatively easy to track down. For the debug
one, one of us should get you a simple test example with instructions on
how it generates debug output for us. I'd love to get a test case for
the InjectHostDevBufferCopies.cpp
assertion if possible.

-Z-

**Comment by fbriggs** [comment]
Thanks for the fast reply! I'll have more comments as I work through your suggestions, but a few notes so far:

1) For the InjectHostDevBufferCopies.cpp assert issue, I had it reproducing consistently but that was in my full implementation of optical flow (which I don't have permission to share yet). I tried to simplify everything down to just a test case of gaussian blur for this post, and I haven't seen it since then. If I get it to happen again, I'll post the test case if I can.

2) Regarding BoundaryConditions, it is my understanding that these can be applied to ImageParams, but not to Funcs. In the full pipeline that uses the gaussian blur, I need to apply it to a Func that is computed from earlier steps of the pipeline, i.e. not directly to an input ImageParam. In the test code I posted, I take the input ImageParam and just copy it into a Func to simulate that. My assumption is that to enforce boundary conditions on Funcs, I need to write out the clamp code explicitly. Please let me know if I have some misunderstanding here.

You asked:
"How are you handling the edges of the image?"
--> with clamps, e.g.,
blurY(x, y) = sum(kernel(r + radius) * I(clamp(x, 0, w - 1), clamp(y + r, 0, h - 1)));
blurX(x, y) = sum(kernel(r + radius) * blurY(clamp(x + r, 0, w - 1), clamp(y, 0, h - 1)));

**Comment by fbriggs** [comment]
Here's a schedule with TailStrategy::GuardWithIf, for the 1-pass version:
```
  blur.compute_root().gpu_tile(x, y, 8, 8);
  blur.update(0).gpu_tile(x, y, 8, 8, TailStrategy::GuardWithIf);
```
This gives a runtime error:
```
Error: CL: clEnqueueWriteBufferRect failed: CL_INVALID_VALUE
Abort trap: 6
```

**Comment by zvookin** [comment]
A BoundaryConditions functions can be applied to a Func, but you must
provide the bounds explicitly. My apologies for not noticing the clamps,
which do the same thing, though BoundaryConditions is clearer and can be
faster. Your problem is not on the input buffers anyway.

I'm not sure how we are failing to get the bounds of blurX right here.
Unless there are some extent assertions being applied to the output_buffer,
this seems like a bug. I'll have to copy the code into a test case and
look, which I won't be able to get to until tomorrow. Perhaps someone else
has an idea.

Really we need to get debug working for you. If I type:
    HL_JIT_TARGET=host-opencl-debug make correctness_hello_gpu
on the command line on my Mac, I get a page or two of output. Does that
work for you?

-Z-

**Comment by fbriggs** [comment]
Thanks for looking into this. Here is my output from running HL_JIT_TARGET=host-opencl-debug make correctness_hello_gpu from the Halide root directory:
[halide_gpu_test.txt](https://github.com/halide/Halide/files/528453/halide_gpu_test.txt)

Tomorrow I will try using BoundaryConditions instead of clamp.

**Comment by zvookin** [comment]
So that is the debug output you would expect from the GPU runtime. You can
see all the calls to do buffer copies and to run kernels, etc. If you run
your test in this way, hopefully it will give some more info around the:
    Error: CL: clEnqueueWriteBufferRect failed: CL_INVALID_VALUE
error.

-Z-

**Comment by fbriggs** [comment]
Here's another version which uses BoundaryCondition::repeat_edge with the bounds passed in so it can be applied to a Func..

```
Func gaussianBlur(Expr w, Expr h, Func I, const int boxSize, const float sigma) {
  assert(boxSize % 2 != 0 && "boxSize must be odd");

  const int radius = (boxSize - 1) / 2;
  vector<float> k(radius * 2 + 1);
  float ksum = 0.0f;
  for (int i = -radius; i <= radius; ++i) {
    const float ki = exp(-i * i / (2.0f * sigma * sigma));
    k[i + radius] = ki;
    ksum += ki;
  }
  Image<float> kernel(radius * 2 + 1, radius * 2 + 1);
  for (int j = 0; j < k.size(); ++j) {
    for (int i = 0; i < k.size(); ++i) {
      kernel(i, j) = k[i] * k[j] / (ksum * ksum);
    }
  }

  Func I_ = BoundaryConditions::repeat_edge(I, {{0, w - 1}, {0, h - 1}});
  Var x("x"), y("y");
  RDom r(-radius, 2 * radius + 1, -radius, 2 * radius + 1);
  Func blur("blur");
  blur(x, y) += kernel(r.x + radius, r.y + radius) * I_(x + r.x, y + r.y);

  blur.compute_root().gpu_tile(x, y, 8, 8);
  blur.update(0).gpu_tile(x, y, 8, 8);

  return blur;
}
```
This version gives the same error as before:
```
Error: Output buffer blur is accessed at 455, which is beyond the max (449) in dimension 0
Abort trap: 6
```

The next idea I am considering is to pass the dimensions w and h around as Params instead of Exprs.

**Comment by abadams** [comment]
The problem is the bounds of the output, so boundary conditions won't help.
The gpu_tile call on the update stage requires that the output has a size
that's a multiple of 8. Adding GuardWithIf to that call is the right way to
get past the bounds problem at least, which leaves the CL_INVALID_VALUE
problem.

**Comment by fbriggs** [comment]
Cool, what I am seeing now is consistent with your note about GaurdWithIf. Using this schedule:
```
  blur.compute_root().gpu_tile(x, y, 8, 8);
  blur.update(0).gpu_tile(x, y, 8, 8);
```
If I run it on an image with size that is not a multiple of 8, I get:
`Error: Output buffer blur is accessed at 455, which is beyond the max (449) in dimension 0`
but if I run it on a multiple of 8 sized image, I instead get:
`Error: CL: clEnqueueWriteBufferRect failed: CL_INVALID_VALUE`

However, if I change the schedule to:
```
  blur.compute_root().gpu_tile(x, y, 8, 8, TailStrategy::GuardWithIf);
  blur.update(0).gpu_tile(x, y, 8, 8, TailStrategy::GuardWithIf);
```
then I can get to the CL_INVALID_VALUE error with a non multiple of 8 sized image.

Moving on to the next problem, since I now have Target::Debug working after changing HL_TARGET=host-opencl to HL_TARGET=host-opencl-debug, here is the full debug output leading up to the CL_INVALID_VALUE:
```
CL: halide_opencl_init_kernels (user_context: 0x0, state_ptr: 0x109b34fc0, program: 0x1096a2a20, size: 9360
    load_libopencl (user_context: 0x0)
    create_opencl_context (user_context: 0x0)
    Got platform 'Apple', about to create context (t=49901)
    Multiple CL devices detected. Selecting the one with the most cores.
      Device 0 has 12 cores
      Device 1 has 24 cores
      Device 2 has 24 cores
    Selected device 2
      device name: AMD Radeon HD - FirePro D500 Compute Engine
      device vendor: AMD
      device profile: FULL_PROFILE
      global mem size: 3072 MB
      max mem alloc size: 768 MB
      local mem size: 32768
      max compute units: 24
      max workgroup size: 256
      max work item dimensions: 3
      max work item sizes: 256x256x256x0
    clCreateContext -> 0x7ff9de102bf0
    clCreateCommandQueue 0x7ff9de103b70
    clCreateProgramWithSource -> 0x7ff9de103fa0
    clBuildProgram 0x7ff9de103fa0 -D MAX_CONSTANT_BUFFER_SIZE=65536 -D MAX_CONSTANT_ARGS=8
    Time: 1.410301e+00 ms
halide_copy_to_device 0x7fff577f2768, host: 0x10cefe020, dev: 0, host_dirty: 1, dev_dirty:0
halide_device_malloc: 0x7fff577f2768 interface 0x109a72e70 host: 0x10cefe020, dev: 0, host_dirty: 1, dev_dirty:0 buf current interface: 0x0
CL: halide_opencl_device_malloc (user_context: 0x0, buf: 0x7fff577f2768)
    Allocating buffer of 675000 bytes, extents: 450x375x0x0 strides: 1x450x0x0 (4 bytes per element)
    clCreateBuffer -> 675000 0x7ff9de1055c0
Creating device wrapper for interface 0x109a72e70 handle 0x7ff9de1055c0 wrapper 0x7ff9de1057a0
    Allocated device buffer 0x7ff9de1057a0 for buffer 0x7fff577f2768
    Time: 2.130700e-02 ms
halide_copy_to_device 0x7fff577f2768 host is dirty
CL: halide_opencl_device_malloc (user_context: 0x0, buf: 0x7fff577f2768)
Getting device handle for interface 0x109a72e70 device_handle 0x7ff9de1055c0 at addr 0x7ff9de1057a0
CL: validate 0x7ff9de1055c0: asked for 675000, actual allocated 675000
CL: halide_opencl_copy_to_device (user_context: 0x0, buf: 0x7fff577f2768)
Getting device handle for interface 0x109a72e70 device_handle 0x7ff9de1055c0 at addr 0x7ff9de1057a0
CL: validate 0x7ff9de1055c0: asked for 0, actual allocated 675000
Getting device handle for interface 0x109a72e70 device_handle 0x7ff9de1055c0 at addr 0x7ff9de1057a0
    clEnqueueWriteBufferRect ((0, 0), (0x10cefe020 -> 140711149196736) + 0, 675000x1x1 bytes, 0x0)
    Time: 7.807789e+00 ms
CL: halide_opencl_run (user_context: 0x0, entry: kernel_blur_s0_y___block_id_y, blocks: 57x47x1, threads: 8x8x1, shmem: 0
    clCreateKernel kernel_blur_s0_y___block_id_y ->     Time: 4.942700e-02 ms
    clSetKernelArg 0 4 [0x177000001c2 ...] 0
    clSetKernelArg 1 4 [0x177 ...] 0
    clSetKernelArg 2 4 [0x0 ...] 0
    clSetKernelArg 3 4 [0x1c200000000 ...] 0
    clSetKernelArg 4 4 [0xde1057a0000001c2 ...] 0
    clSetKernelArg 5 8 [0x7ff9de1057a0 ...] 1
Getting device handle for interface 0x109a72e70 device_handle 0x7ff9de1055c0 at addr 0x7ff9de1057a0
Mapped dev handle is: 0x7ff9de1055c0
    clSetKernelArg 6 0 [NULL]
    clEnqueueNDRangeKernel 57x47x1, 8x8x1 -> CL_SUCCESS
    Releasing kernel 0x7ff9de807c00
    clReleaseKernel finished0x7ff9de807c00
    Time: 5.817600e-01 ms
halide_copy_to_device 0x7fff577f2768, host: 0x10cefe020, dev: 140711149197216, host_dirty: 0, dev_dirty:1
halide_copy_to_device 0x109a72f30, host: 0x1096a2440, dev: 0, host_dirty: 1, dev_dirty:0
halide_device_malloc: 0x109a72f30 interface 0x109a72e70 host: 0x1096a2440, dev: 0, host_dirty: 1, dev_dirty:0 buf current interface: 0x0
CL: halide_opencl_device_malloc (user_context: 0x0, buf: 0x109a72f30)
    Allocating buffer of 900 bytes, extents: 15x15x0x0 strides: 1x15x0x0 (4 bytes per element)
    clCreateBuffer -> 900 0x7ff9db7014c0
Creating device wrapper for interface 0x109a72e70 handle 0x7ff9db7014c0 wrapper 0x7ff9db701570
    Allocated device buffer 0x7ff9db701570 for buffer 0x109a72f30
    Time: 1.489000e-02 ms
halide_copy_to_device 0x109a72f30 host is dirty
CL: halide_opencl_device_malloc (user_context: 0x0, buf: 0x109a72f30)
Getting device handle for interface 0x109a72e70 device_handle 0x7ff9db7014c0 at addr 0x7ff9db701570
CL: validate 0x7ff9db7014c0: asked for 900, actual allocated 900
CL: halide_opencl_copy_to_device (user_context: 0x0, buf: 0x109a72f30)
Getting device handle for interface 0x109a72e70 device_handle 0x7ff9db7014c0 at addr 0x7ff9db701570
CL: validate 0x7ff9db7014c0: asked for 0, actual allocated 900
Getting device handle for interface 0x109a72e70 device_handle 0x7ff9db7014c0 at addr 0x7ff9db701570
    clEnqueueWriteBufferRect ((0, 0), (0x1096a2440 -> 140711105139904) + 0, 900x1x1 bytes, 0x0)
Error: CL: clEnqueueWriteBufferRect failed: CL_INVALID_VALUE
Abort trap: 6
```

**Comment by fbriggs** [comment]
It seems plausible that this is an issue with how I set up the output buffer. I don't have a solution yet, but just to reiterate from my earlier wall of text, here's how I set that up:

```
struct CvMat2HalideBuffer {
  Halide::Buffer<float, 2> buffer;
  buffer_t* bufferPtr;

  CvMat2HalideBuffer(cv::Mat& mat) {
    assert(mat.type() == CV_32F);
    halide_dimension_t shape[2] = {
      {0, mat.cols, 1},
      {0, mat.rows, mat.cols}};

    buffer = Halide::Buffer<float, 2>(
      Halide::type_of<float>(), mat.data, 2, shape);
    bufferPtr = buffer.raw_buffer();
  }
};
```

**Comment by abadams** [comment]
The args look OK:

    clEnqueueWriteBufferRect ((0, 0), (0x1096a2440 -> 140711105139904)
+ 0, 900x1x1 bytes, 0x0)

but a CL_INVALID_VALUE seems to indicate an out-of-bounds write.
There's a malloc for that buffer which indicates it's 900 bytes
though, so a copy of 900x1x1 should be ok.

Perhaps there's something I'm not getting about
clEnqueueWriteBufferRect. You could try nuking the ifdef path here:

https://github.com/halide/Halide/blob/master/src/runtime/opencl.cpp#L788

**Comment by fbriggs** [comment]
I think the 900 bytes is for the 15x15 kernel (15*15*4 = 900). The output is a difference size (e.g, 512x512 lena.png).

**Comment by fbriggs** [comment]
I'm pretty sure the crash with clEnqueueWriteBufferRect  returning CL_INVALID_VALUE is related to referencing 'Image<float> kernel' inside the reduction. If I change the code to the listing below, it no longer crashes when running on the GPU with the listed schedule:
```
  Var x("x"), y("y");
  Func blur("blur");
  blur(x, y) = I(x, y) + 0.1f;
  blur.compute_root().gpu_tile(x, y, 8, 8, TailStrategy::GuardWithIf);
```
Running this on the GPU doesn't crash, but the output is all zeros. If I remove the GPU schedule and run it on the CPU, it gives the expected output (a slightly brighter version of the input).

**Comment by abadams** [comment]
The output is probably all zeros because it's still on the GPU. We don't
copy back by default in case you want to pass the buffer into another GPU
pipeline. Call copy_to_host to get the output back in the host-side
allocation.

The CL_INVALID_VALUE is still a mystery to me. It does indeed seem to be
related to copying the kernel to the GPU.

**Comment by fbriggs** [comment]
Thanks for your continued help on this. Calling copy_to_host() on the Buffer fixes the 'all zeros' problem, and now it produces the expected output when running on the GPU. I'll keep poking the kernel issue. One hack solution would be to meta-program an Expr that has all of the kernel values hardcoded into it...

**Comment by fbriggs** [comment]
Is there anything I need to do to copy an Image<T> to the GPU, or does that happen automatically?

**Comment by zvookin** [comment]
You can force it to happen at a certain time/place via
halide_copy_to_device, but it should not be necessary to call this for
correctness in Halide only code.

-Z-

**Comment by fbriggs** [comment]
Here's one more version of gaussianBlur, which doesn't use Halide::Image or RDom's at all, and instead statically unrolls the convolution. This version runs successfully on the GPU, but it is about 12x slower than OpenCV's CPU implementation for a 15x15 box, on an image sized 375 x 450 (not counting time to copy the solution back from GPU to CPU). Please let me know if you have any ideas how to make this faster...

```
Func gaussianBlur(Expr w, Expr h, Func I, const int boxSize, const float sigma) {
  assert(boxSize % 2 != 0 && "boxSize must be odd");

  const int radius = (boxSize - 1) / 2;
  vector<float> k(radius * 2 + 1);
  float ksum = 0.0f;
  for (int i = -radius; i <= radius; ++i) {
    const float ki = exp(-i * i / (2.0f * sigma * sigma));
    k[i + radius] = ki;
    ksum += ki;
  }
  for (int i = 0; i < boxSize; ++i) {
    k[i] /= ksum;
  }

  Var x("x"), y("y");
  Func I_ = BoundaryConditions::repeat_edge(I, {{0, w - 1}, {0, h - 1}});

  Func blurY("blurY");
  Expr sumExprY = 0.0f;
  for (int u = -radius; u <= radius; ++u) {
    const float coef = k[u + radius];
    sumExprY += Expr(coef * I_(x, y + u));
  }
  blurY(x, y) = sumExprY;

  Func blurX("blurX");
  Expr sumExprX = 0.0f;
  for (int u = -radius; u <= radius; ++u) {
    const float coef = k[u + radius];
    sumExprX += Expr(coef * blurY(x + u, y));
  }
  blurX(x, y) = sumExprX;

  blurX.compute_root().gpu_tile(x, y, 16, 16, TailStrategy::GuardWithIf);
  return blurX;
}
```

**Comment by fbriggs** [comment]
It looks like the 12x slower comment I made before was wrong/related to bad measurement. Here are some new results, repeating the blur 100 times within the same process, then measuring only the last repetition:
Halide blur: 0.000638008 sec
Time to copy GPU->CPU: 0.000841856 sec
OpenCV blur: 0.000976086 sec

So in this test, the Halide GPU version is coming out slightly ahead of the OpenCV version (not counting copy time).

Thanks for your help getting this far... onward to the next steps.

**Comment by fbriggs** [comment]
I figured out how to make it run with Metal. I am compiling/linking with CMake. I added this path to the list of libraries being linked:

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Metal.framework
