### ISSUE TITLE
Tutorial lesson 10 compilation

### ISSUE THREAD

**Issue by Baharehm** [halide/Halide#1552]
When I compile the lesson 10 tutorial as described in the file, no object files are created, it's just the header (.h) and a .a file so I can't do the linking in order to get the final executable. When I build the same tutorial with make, I am able to get the final executable file but even then there's no object file generated. Is the linking done differently than what's explained in the lesson_10 file?

**Comment by guusleijsten** [comment]
See this issue: [https://github.com/halide/Halide/issues/1492](url)

I hope this answers your question.
Kind regards.

**Comment by Baharehm** [comment]
@guusleijsten Thanks for your answer but apparently that issue doesn't exist.

**Comment by guusleijsten** [comment]
I encountered similar issue, apperently I closed it. I realized that the .a is the object file, previously they used .o however this is different in the latest git clone.
```
// On linux, you can compile and run it like so:
// g++ lesson_10*generate.cpp -g -std=c++11 -I ../include -L ../bin -lHalide -lpthread -ldl -o lesson_10_generate
// LD_LIBRARY_PATH=../bin ./lesson_10_generate
// g++ lesson_10*run.cpp lesson_10_halide.a -lpthread -o lesson_10_run
// ./lesson_10_run
```
I replaced lesson_10_halide.o to lesson_10_halide.a.

**Comment by Baharehm** [comment]
I found that issue in the close issues but still didn't help. Apparently, the implementation has changed from using an object file to a static library. But when I try using the .a file I get the following errors:

> lesson_10_halide.a(/tmp/JTcgFg/lesson_10_halide.a.o): In function `halide_get_symbol':
brighter:(.text.halide_get_symbol+0xe): undefined reference to `dlsym'
lesson_10_halide.a(/tmp/JTcgFg/lesson_10_halide.a.o): In function `halide_load_library':
brighter:(.text.halide_load_library+0xc): undefined reference to `dlopen'
brighter:(.text.halide_load_library+0x19): undefined reference to `dlerror'
lesson_10_halide.a(/tmp/JTcgFg/lesson_10_halide.a.o): In function `halide_get_library_symbol':
brighter:(.text.halide_get_library_symbol+0x6): undefined reference to `dlsym'

Also, I'm on the latest commit but the comments in lesson 10 explaining the compilation process haven't changed.

**Comment by abadams** [comment]
Add the flag "-ldl"

I'm fixing the comments.

**Comment by Baharehm** [comment]
Thanks!
