### ISSUE TITLE
what is the difference between schedule for OpenCL and CUDA?

### ISSUE THREAD

**Issue by Eirclew** [halide/Halide#1590]
For unsharp app in the repository 
 https://github.com/ravi-teja-mullapudi/Halide/tree/master/apps/unsharp  

The original schedule is said for CUDA, as follow:
 if (target.has_gpu_feature()) {
            Var xi, yi;
            unsharp.compute_root()
                .reorder(c, x, y)
                .gpu_tile(x, y, 16, 16);
            ratio.compute_at(unsharp, Var::gpu_threads());
            gray.compute_at(unsharp, Var::gpu_blocks())
                .tile(x, y, xi, yi, 2, 2)
                .unroll(xi)
                .unroll(yi)
                .gpu_threads(x, y);
            blur_y.compute_at(unsharp, Var::gpu_blocks())
                .unroll(x, 2)
                .gpu_threads(x, y);
        }

When I try to use the schedule for OpenCL for both AMD or CUDA(Also run as OpenCL program) platforms, there are we encounter the same errors as follow, it seems  halide generate OpenCL with std::min/max under the schedule.
Error: CL: clBuildProgram failed: CL_BUILD_PROGRAM_FAILURE
Build Log:
 <kernel>:59:11: error: use of undeclared identifier 'std'
 int _6 = std::min(_3, _5);
          ^
<kernel>:64:12: error: use of undeclared identifier 'std'
 int _11 = std::min(_8, _10);
           ^
<kernel>:73:13: error: use of undeclared identifier 'std'
  int _17 = std::min(_15, _16);

And in the last I try to set the schedule as below, it can run correctly,but the performance gains is very small.
      kernel.compute_root();                                                                                                                                                
      blur_y.compute_at(unsharp, y).vectorize(x, 8);// works
      unsharp.vectorize(x, 8).parallel(y).reorder(x, y);

My questions are:
1) Are there differences between the schedule for OpenCL and CUDA?
2) Why under some schedule, it will generate code with std::min/std::max?
3) Are there more detailed tutorials to understand the scheduling except these examples?(lesson1-12)
It seems difficult to set the schedule for a beginner.

**Comment by dsharletg** [comment]
The std::min issue just looks like a bug in https://github.com/ravi-teja-mullapudi/Halide/blob/master/src/CodeGen_C.cpp#L810. Note that Halide master doesn't have this: https://github.com/halide/Halide/blob/master/src/CodeGen_C.cpp#L825

**Comment by Eirclew** [comment]
To Dsharletg, Yes, the Halide master now does not have the bug. Thanks!
