### ISSUE TITLE
Simplifier fuzz-test failure

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#1601]
An unrelated Travis test found this random failure (Linux gcc3.8 build):

Simplify fuzz test seed: 1478203894
a = uint1(d)
b = uint1(d)
c = uint1(b)
d = uint1(b)
e = (uint1)1
(select(((ramp(uint1(e), uint1(e), 2) || (uint1x2(x2((uint16)60144)) && !x2(uint1(a)))) > x2(((uint1(c) || (uint1)0) && !uint1(c)))), (x2((uint1)1) && uint1x2(ramp((uint32)1919502394, (uint32)1603628257, 2))), !(x2(uint1(d)) && uint1x2(ramp(int8(e), int8(c), 2)))) == (!((ramp(uint1(d), uint1(b), 2) || x2(uint1(b))) || (ramp(uint1(a), uint1(a), 2) != x2(uint1(e)))) && (uint1x2(select((uint16(d) <= (uint16)36058), x2(uint16(b)), x2(uint16(b)))) && (select((x2(uint1(c)) == ramp(uint1(a), uint1(b), 2)), ramp((uint1)0, uint1(b), 2), ramp(uint1(c), (uint1)0, 2)) && (ramp((uint1)0, (uint1)0, 2) && ramp(uint1(e), uint1(e), 2))))))
((ramp(uint1(e), uint1(e), 2) <= x2((uint1)0)) && (!(x2(uint1(d)) && uint1x2(ramp(int8(e), int8(c), 2))) == x2((uint1)0)))
In vector lane 0:
(((uint1)0 < uint1(e)) || (!(uint1(d) && uint1(e)) == (uint1)0)) -> (uint1)1
((uint1(e) <= (uint1)0) && (!(uint1(d) && uint1(e)) == (uint1)0)) -> (uint1)0

**Comment by psuriana** [comment]
Fixed

**Comment by abadams** [comment]
Nice catch @psuriana, this one was subtle. Nice to see the fuzz tester continuing to pay off too.
