### ISSUE TITLE
[X86 Backend] Add support for AVX512 target features

### ISSUE THREAD

**Issue by ZviRackover** [halide/Halide#1608]
The latest supported target feature is AVX2. It would be beneficial for code running on KNL to generate  AVX512 machine code.

**Comment by abadams** [comment]
Last time we tried (see the avx512 branch), the llvm avx512 backend wasn't
quite there yet. We'll try again.

**Comment by ZviRackover** [comment]
Thanks. There was significant work on AVX512 support in past months, so i hope this time it will go more smoothly. We can report any issues to llvm.org/bugs.

**Comment by abadams** [comment]
llvm bug number 1:

https://llvm.org/bugs/show_bug.cgi?id=30947

**Comment by ZviRackover** [comment]
Bug number 1 was fixed in r286342.

**Comment by ZviRackover** [comment]
Thanks for merging the AVX512 branch. As far as I'm concerned this issue can be closed.
