### ISSUE TITLE
Importing HelloAndroid into Android Studio 2.2.2

### ISSUE THREAD

**Issue by yaksharaja** [halide/Halide#1609]
Hello,
I get the following error:
_Error:(37, 0) Could not find method sources() for arguments [build_bpvwmhrdi32y28rhl0u7ukyom$_run_closure2@18aaedec] on root project 'HelloAndroid' of type org.gradle.api.Project.
<a href="openFile:/Users/yaksharaja/projects/Halide-master/apps/HelloAndroid/build.gradle">Open File</a>

when I try to import HelloAndroid project into Android Studio 2.2.2

Any help is greatly appreciated.
Thanks!

_

**Comment by steven-johnson** [comment]
Yep, I'm seeing the same thing -- this build has clearly gone stale, but
I'm not sure how to fix it (I know basically nothing about Gradle).
Volunteers would be welcome :-)

**Comment by steven-johnson** [comment]
(On a related note, though: in a separate branch I have gotten Bazel's android support working with Android Studio -- it requires installing the Bazel Support plugin but seems to work quite well and is a much simpler build file setup than Gradle IMHO. It's not ready to land yet but hopefully in a week or three.)

**Comment by yaksharaja** [comment]
Thanks, steven-johnson. It will be interesting to see where Google goes with Bazel.

**Comment by steven-johnson** [comment]
FYI: I have pushed out a PR that (hopefully) fixes the manual and
AndroidStudio builds (https://github.com/halide/Halide/pull/1626); please
take a look.

Caveat: Android Studio will ask you to upgrade the version of Gradle in the
build rules; don't do this, as it won't work with the newer Gradle rules.
(Still not sure how to fix those.)

I'll be pushing an example of Bazel-for-Android usage out to another branch
soon.

**Comment by yaksharaja** [comment]
I will give this a try. Thank you, Steven!

**Comment by steven-johnson** [comment]
See also PR#1631 for further improvements.

At this point I think we are functional again, so I'm going to close this.
