### ISSUE TITLE
See if there is a way to coalesce the indexing code (Expr operator()(...), etc.) in Image.h and Param.h ,

### ISSUE THREAD

**Issue by zvookin** [halide/Halide#162]
There is a fair bit of duplicated code between Param.h and Image.h due to both supporting the ability to index an image across its dimensions.

**Comment by zvookin** [comment]
@abadams Isn't this is totally obsolete now with Buffer<T>, etc. Just close it?

**Comment by abadams** [comment]
Yeah, this is obsolete.
