### ISSUE TITLE
Consider using C++11 variadic templates to support arbitrary number of dimension overloads.

### ISSUE THREAD

**Issue by zvookin** [halide/Halide#163]
There are many places in Halide where an exhaustive list of overloaded methods or operators is used to allow a function-like construct with a variable number of arguments corresponding to dimensions. This code with both become more maintainable and support more dimensions than e.g. six, if variadic templates are used instead of repeated overloads. The use of such requires C++11 and thus we either need to keep the existing code under an #ifdef or wait until C++11 is widely enough used to require it for Halide compilation.

**Comment by abadams** [comment]
I think all of the explicit overload lists have been cleaned up now. Or at least they will be when the new_buffer_t branch is merged.
