### ISSUE TITLE
HelloAndroidCamera2 build fails - workaround

### ISSUE THREAD

**Issue by yaksharaja** [halide/Halide#1632]
1. Generated object files (edge_detect, deinterleave) in jni/halide_generated_<ARCH> are expected to have the .o extension instead of .a. 
2. Android.mk needs to be modified to include -latomic for LOCAL_LDLIBS.

With these two changes I was able to get the project built on both mac and ubuntu 15.10.

**Comment by steven-johnson** [comment]
See PR #1633
