### ISSUE TITLE
apps/ should only rely on distrib/ folder?

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#1637]
Some of the apps/ rely on details of the build layout, and/or internal bits of Halide; to promote them as examples for real-world usage, they would ideally rely only on the contents of the distrib/ folder.

Problem #1: AFAIK the CMake build doesn't produce a distrib/ folder; we'd need to add a way to do that

Problem #2: this potentially makes experimenting with apps/ a little less convenient, since internal changes to Halide would require rebuilding distrib/ as well as the app itself.

**Comment by dsharletg** [comment]
Is this done? I think it might be?

**Comment by steven-johnson** [comment]
Pretty sure this is done
