### ISSUE TITLE
Code cannot compile against new and old Halide versions

### ISSUE THREAD

**Issue by kgnk** [halide/Halide#1662]
I'm in the situation where I want to compile against the August 2016 release as well as CI trunk nightly builds. Really, the only complaint is that `Halide::Tools::Image` and `tools/halide_image.h` went away.

Here is a `tools/halide_image.h` that I'm using with new releases to bring the type back. It maps `Halide::Tools::Image` to a `Halide::Buffer`. It also defines `USING_HALIDE_BUFFER` so that other code can conditionally compile with old or new Halide versions.

This allows older, working code to work with the newer Halide version. At some point, that code will be transitioned to use `Halide::Buffer` directly, but this buys me some time.

https://gist.github.com/kgnk/b993e4c2924af0fac0d05811471d2307

**Comment by abadams** [comment]
Sure, this makes sense. If you'd prefer this was upstream, open a PR and we'll merge it.

**Comment by kgnk** [comment]
See PR #1663
