### ISSUE TITLE
Metal runtime fails Xcode's "Metal API Validation" assertions

### ISSUE THREAD

**Issue by estollnitz** [halide/Halide#1681]
The Metal runtime triggers three different assertions when running with "Metal API Validation" enabled, indicating problems with at least three of the runtime's calls to Metal.

Metal API Validation is enabled by default when running inside Xcode (controlled by Product > Scheme > Edit Scheme… > Run > Options > Metal API Validation). It's ordinarily disabled when running outside Xcode, but can be enabled by setting `METAL_DEVICE_WRAPPER_TYPE=1`.

To reproduce the assertion failures, run the following command on a Mac:
```
HL_JIT_TARGET=host-metal METAL_DEVICE_WRAPPER_TYPE=1 make -i run_tests
```

Three assertion failures appear repeatedly:
```
MTLDebugComputeCommandEncoder.mm:475: failed assertion `length(4) must be a multiple of 16 bytes.'
MTLDebugBuffer.mm:163: failed assertion `didModifyRange: only applies when resourceOptions(0x0) & MTLResourceStorageModeMask(0xf0) == MTLResourceStorageModeManaged(0x10).  NOT MTLResourceStorageModeShared'
MTLDebugBlitCommandEncoder.mm:810: failed assertion `synchronizeResource: only applies when resourceOptions(0x0) & MTLResourceStorageModeMask(0xf0) == MTLResourceStorageModeManaged(0x10).  NOT MTLResourceStorageModeShared'
```

I'm working on fixing these issues in `metal.cpp`.

**Comment by zvookin** [comment]
Thank you for spotting this. Let me know if there is anything I can do to
help. I expect the only way to avoid the warning on didModifyRange and
synchronizeResource is to query the storage mode (storageMode property) on
the resource and not dispatch to the method unless the mode is
MTLResourceModeManaged.

-Z-

**Comment by estollnitz** [comment]
Yes, that's what I'm doing to fix those issues. Is it sound practice to increase the shared memory size to the next larger multiple of 16 bytes in metal.cpp? That would satisfy the API requirement of `MTLComputeCommandEncoder::setThreadgroupMemoryLength`, but it's not clear if there are any side effects for Halide.

**Comment by shoaibkamil** [comment]
> Is it sound practice to increase the shared memory size to the next larger multiple of 16 bytes in metal.cpp? That would satisfy the API requirement of MTLComputeCommandEncoder::setThreadgroupMemoryLength, but it's not clear if there are any side effects for Halide.


I don't think this should be a problem, since we won't hit any memory limit by rounding up that we would have not hit otherwise (the max on iOS devices seems to 16KB and max on OS X seems to be 32KB).

**Comment by zvookin** [comment]
I don't think there is a problem rounding up the shared memory size inside
the runtime. I must not have noticed the constraint in the docs when
writing the code.

-Z-

**Comment by estollnitz** [comment]
OK, I've created [PR 1696](https://github.com/halide/Halide/pull/1696). Not sure how to request review...
