### ISSUE TITLE
We need a Windows build server

### ISSUE THREAD

**Issue by jrk** [halide/Halide#169]
It's clear that the Windows build will never survive without this.

I am looking into it on multiple fronts.

**Comment by nathanaeljones** [comment]
Do you have a windows build script and/or llvm/clang artifacts? AppVeyor has most things, but llvm/clang do not come preinstalled.

**Comment by abadams** [comment]
The windows build script is in test/scripts/distrib_windows.ps1. It should
acquire and build trunk llvm, provided you've got all the dependencies
installed (see the path modifications at the top of the script for a list).
You probably want to comment out the pnacl bits.

We also have precompiled windows builds here:
https://github.com/halide/Halide/releases
