### ISSUE TITLE
Can't Enable WITH_TEST_GENERATORS?

### ISSUE THREAD

**Issue by jiapei100** [halide/Halide#1724]
Whenever I tried to enable WITH_TEST_GENERATORS, I got the following error message while **make**:

> [ 96%] Building CXX object test/CMakeFiles/generator_aot_cxx_mangling.dir/generator/cxx_mangling_aottest.cpp.o
> ....../Halide/test/generator/cxx_mangling_aottest.cpp:9:30: fatal error: cxx_mangling_gpu.h: No such file or directory
> compilation terminated.
> test/CMakeFiles/generator_aot_cxx_mangling.dir/build.make:62: recipe for target 'test/CMakeFiles/generator_aot_cxx_mangling.dir/generator/cxx_mangling_aottest.cpp.o' failed
> make[2]: *** [test/CMakeFiles/generator_aot_cxx_mangling.dir/generator/cxx_mangling_aottest.cpp.o] Error 1
> CMakeFiles/Makefile2:12039: recipe for target 'test/CMakeFiles/generator_aot_cxx_mangling.dir/all' failed
> make[1]: *** [test/CMakeFiles/generator_aot_cxx_mangling.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....

Any solutions?

Cheers
Pei

**Comment by alexreinking** [comment]
Closing because the issue has apparently been abandoned.
