### ISSUE TITLE
Halide::Buffer::operator() has type-checking overhead

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#1768]
Minor Friday-afternoon nit:

Every call to Halide::Buffer::operator() has to call get(), which has to call as(), which has to call can_convert_from(), to verify that the conversion from Buffer<> to Buffer<T> is valid. In non-optimized builds, profiling shows that this can amount to ~5% of runtime in tests that heavily use this operator (e.g. mul_div_mod).

Since every ctor (etc) of Halide::Buffer already verifies that the Halide::Runtime::Buffer is compatible, this is totally unnecessary checking.

(Simplest fix would be to make BufferContents a templated type too, thus allowing a Runtime::Buffer<T> that matches the Buffer<T> declaration; however, IntrusivePtr doesn't allow for templated types.)

**Comment by steven-johnson** [comment]
Edit: ~5% of runtime in *non-optimized builds*. Overhead is much smaller in optimized builds, so probably not a huge needle-mover.

**Comment by zvookin** [comment]
@abadams Can the issue be closed now?
