### ISSUE TITLE
Vectorized absd is broken

### ISSUE THREAD

**Issue by kgnk** [halide/Halide#1771]
I saw this when working with a nightly build from 2016-12-05 or 2017-01-20. It works with the 2016-10-25 release.

The target for the sample is x86-64-windows-avx-f16c-jit-sse41 but I saw it using AOT.

Simple reproduction code:

    #include <Halide.h>

    #include <stdio.h>
    #include <math.h>

    using namespace std;
    using namespace Halide;

    int main()
    {
        int const L = 256;

        Buffer< uint16_t > inp( L );
        Buffer< uint16_t > out( L/2 );
        Var x("x");

        for (int i = 0; i < L; ++i)
            inp(i) = (uint16_t)( ( i & 1 ) ^ ( i >> 1 ) );   // 0 1 1 0 2 3 3 2 ...

        Func input( inp );
        Func dif("dif");
        dif( x ) = absd( input( x * 2 ), input( x * 2 + 1 ) );

        dif.realize( out );

        for (int i = 0; i < L/2; ++i)
        {
            int correct = abs( inp( i * 2 ) - inp( i * 2 + 1 ) );

            if (out(i) != correct)
            {
                printf("out(%d) = %d instead of %d\n", i, out(i), correct);
                return -1;
            }
        }

        printf("Success!\n");

        return 0;
    }

**Comment by abadams** [comment]
Can repro. Passes with -avx2 on. Investigating.

**Comment by abadams** [comment]
If you manually vectorize it with Halide it passes. If you let LLVM
autovectorize it it fails. That combined with the avx2 thing makes me
suspect that this is an LLVM bug.

**Comment by abadams** [comment]
https://llvm.org/bugs/show_bug.cgi?id=31714

Craig Topper may have already found the problem.

**Comment by kgnk** [comment]
As noted in the llvm bug comments, this is fixed in r293299. How can I know what version of llvm was used to build Halide? For that matter, how can I know what version of Halide I'm looking at? The modified dates on the files are potentially not stable across OSes and version control systems.

**Comment by zvookin** [comment]
Can we close this issue now? Feel free to open another requesting that Halide binary builds (releases) need to be tagged with the llvm version they include.

**Comment by abadams** [comment]
Apparently this was a long-standing bug in LLVM. We should check if with older LLVM versions and consider a workaround if it's an issue.

**Comment by ZviRackover** [comment]
If LLVM versions older than 4.0 are no longer supported. can this issue be closed?
