### ISSUE TITLE
about find_direct_call

### ISSUE THREAD

**Issue by were** [halide/Halide#1772]
This interface has been deprecated so how can I achieve the same effect? If I want to manipulate the schedule of a internal function like `sum`

**Comment by were** [comment]
Anyone help me to resolve this problem?

**Comment by zvookin** [comment]
I'm having trouble reconstructing what changed and why it is causing a problem. Halide::Internal::find_direct_calls is defined in FindCalls.h and should be in Halide.h . I don't see any indication it is deprecated. That said, identifiers in Halide::Internal are subject to change, more importantly, the internal structure of sum is likely to change as well.

Per the high level issue, we need to address scheduling inline reductions. There is at least one issue open on this: https://github.com/halide/Halide/issues/813, perhaps others.

**Comment by were** [comment]
I am sorry about my carelessness. Thank you for your warm help.
