### ISSUE TITLE
Reduction Functions could make Sliding-Window Optimizations, but don't

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#180]
Say we have code like:

```
Var x, y;
const int radius = 10;  // arbitrary
Halide::RDom range(-radius, 2 * radius + 1);

Func horizontal;
horizontal(x, y) = sum(src(x + range, y)); // src is an arbitrary root
horizontal.compute_root();
```

A sliding-window approach to calculating each sum would seem to remove a lot of redundant work, but AFAICT isn't ever attempted.

**Comment by MDBrothers** [comment]
Any update on this?

**Comment by jrk** [comment]
http://www-sop.inria.fr/reves/Basilic/2015/CRPDD15a/recfilter.pdf
http://mit-gfx.github.io/recfilter/

**Comment by dsharletg** [comment]
It seems at this point that the way we're going to do this is explicitly in Halide programs, or with layers on top (e.g. recfilter).
