### ISSUE TITLE
Can't compile Camera Pipe and Non Local Means

### ISSUE THREAD

**Issue by abhijangda** [halide/Halide#1803]
I am working with Camera Pipe and Non Local Means benchmarks in this Halide repo: https://github.com/ravi-teja-mullapudi/Halide . Unfortunately, I am not able to compile both these benchmarks. 
Executing make in Halide/apps/camera_pipe gives the following error:

```
./camera_pipe 8 0 # 8-bit output,
Error at ./camera_pipe.cpp:294:
Can't provide an esitmate on variable tx of function processed because tx is not one of the pure variables of processed.

```
Running make in Halide/apps/non_local_means gives the following error:

```
filter.cpp:6:29: fatal error: non_local_means.h: No such file or directory
 #include "non_local_means.h"
```

It will be great, if anyone could provide any insight over this issue.

Thank You,

**Comment by abadams** [comment]
This error is specific to the code changes in that repo. Your best bet for an answer is from @ravi-teja-mullapudi

**Comment by bondhugula** [comment]
@ravi-teja-mullapudi  anything on this?

**Comment by zvookin** [comment]
@psuriana Do you mind determining if this still needs to be open now that the autoscheduler has been merged?

**Comment by bondhugula** [comment]
We've now ported these and a few more benchmarks to the current autoscheduler, and they all work. I'll be creating a few pull requests in the next couple of days - so that their addition could be considered.

**Comment by steven-johnson** [comment]
Pretty sure this is resolved. Closing.
