### ISSUE TITLE
evaluating individual elements of an output Tuple can cause obscure errors

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#1827]
Still trying to track down the exact minimum case(s) that cause this, but here's a smallish example:

    Var x("x");

    RDom r(0, 1, "r");
    Func b("b");
    b(x) = 0;
    b(x) += 1;

    Func output("output");
    output(x) = Tuple(42, b(x));

    int result0 = Halide::evaluate<int>(output(0)[0]);
    printf("output0 = %d\n", result0);

result:

    Condition failed: injector.found_store_level && injector.found_compute_level

**Comment by abadams** [comment]
I think I've figured it out. PR in a min.

**Comment by steven-johnson** [comment]
Fixed in https://github.com/halide/Halide/pull/1828
