### ISSUE TITLE
Consider CMake-based build

### ISSUE THREAD

**Issue by jrk** [halide/Halide#184]
I've been rebuilding LLVM so often lately, and have enjoyed the process much more since switching from the old automake toolchain to their CMake toolchain.

Our Makefile setup is a nice balance of autoconfiguration, portability, and simplicity—for those platforms where it works, and especially with the simplest defaults (no NaCl, no Android SDK, only dependencies which can be discovered by a few pkg-config tools).

Our Windows setup is a hand-twiddled morass of vcxproj files.

At some point, it seems at least worth considering switching to a single, CMake-based build. Standard CMake practice of building in user-chosen subdirectories could also remove the need for using a `BUILD_PREFIX` when building multiple versions from a single checkout.

The biggest disadvantage I see in CMake is the confusing and non-discoverable way of specifying configuration arguments (`-DCMAKE_SOME_MAGIC_VAR=something`). Hopefully sane defaults and a minimal README should be enough; if not, perhaps a trivial utility script.

(Extremely low priority for the time being.)

**Comment by nyotis** [comment]
any updates on this for OS X? building halide on OS X seems to be time-consuming

**Comment by delcypher** [comment]
@nyotis I'm working on this. I had a pull request ( #825 ) that fixed a lot of things that had to be reverted. I will be redoing these changes over the next few days that will fixing **a lot** of issues.

**Comment by nyotis** [comment]
looking forward to this!

**Comment by abadams** [comment]
The current makefile and cmakefile should both work on OS X. See the readme
for building instructions.

If you're a homebrew user, jrk recently made a homebrew recipe for OS X:

https://github.com/halide/homebrew-halide

**Comment by nyotis** [comment]
nice brew!

**Comment by nyotis** [comment]
I clone https://github.com/halide/homebrew-halide but running the ruby script fails..

nik@Niks-iMac ~/Developer/homebrew-halide $ #!/usr/bin/env ruby
nik@Niks-iMac ~/Developer/homebrew-halide $ chmod +x halide.rb 
nik@Niks-iMac ~/Developer/homebrew-halide $ ./halide.rb 

./halide.rb: line 1: Formula: No such file or directory
./halide.rb: line 2: desc: command not found
./halide.rb: line 3: homepage: command not found
./halide.rb: line 4: url: command not found
./halide.rb: line 5: version: command not found
./halide.rb: line 6: sha256: command not found
./halide.rb: line 8: def: command not found
./halide.rb: line 9: lib.install: command not found
./halide.rb: line 10: include.install: command not found
./halide.rb: line 11: system: command not found
./halide.rb: line 12: system: command not found
./halide.rb: line 13: system: command not found
./halide.rb: line 14: share.install: command not found
./halide.rb: line 15: end: command not found
./halide.rb: line 18: system: command not found
./halide.rb: line 19: system: command not found
./halide.rb: line 20: end: command not found
./halide.rb: line 21: end: command not found

**Comment by nyotis** [comment]
The current makefile and cmakefile *do not* work on OS X without any modifications.. See image below:

![screen shot 2015-07-17 at 15 29 08](https://cloud.githubusercontent.com/assets/658719/8748131/b6f27008-2c98-11e5-9c11-9863ec3ba8cb.png)

**Comment by nyotis** [comment]
any updates @delcypher ? thanks

**Comment by abadams** [comment]
Both the CMakeFile and the Makefile need you to tell it where llvm is. For
the makefile, if llvm-config and clang are in the path, that should be
sufficient. For the CMakeFile you currently need to set all those variables
yourself. The readme has examples for all of this.
