### ISSUE TITLE
correctness/tuple_undef has undefined behavior

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#1845]
The first clause of the test appears to rely on undef<int>() being interpreted as zero; interestingly, this is apparently ~always true in Halide Travis (etc) test conditions, but some other nonpublic C++ environment produce other results, which are... well, undefined.

Fixing the test to be meaningful but well-specified is necessary, but it would probably be worthwhile to figure out why we seem to be reliably getting a predictable result as well.

**Comment by steven-johnson** [comment]
> why we seem to be reliably getting a predictable result as well

Haven't verified, but the likely answer is that the malloc() implementation being used by Buffer<> is zero-initing in the cases that are passing, and is (deliberately) garbage-initing in the cases that are failing.

**Comment by zvookin** [comment]
@steven-johnson Can issue be closed now?

**Comment by steven-johnson** [comment]
Yep.
