### ISSUE TITLE
#include "halide_image_io.h"

### ISSUE THREAD

**Issue by 0luoyanhong** [halide/Halide#1846]
When i use #include "halide_image_io.h" in VS2015, the build error "fatal error C1083: Cannot open include file: 'png.h': No such file or directory" occurred. How can i sovle it?

**Comment by steven-johnson** [comment]
If you are using CMake, this should be handled for you (CMakeLists.txt:148-157). If you are using VS2015 directly, you'll have to take your own steps to ensure that libpng is available to the compiler.

**Comment by 0luoyanhong** [comment]
I used CMake to generate a VS2015 project of halide. I saw (CMakeLists.txt:148-157). Does it mean that i can not use all Apps under VS2015 ？

**Comment by steven-johnson** [comment]
I doubt anyone has tried to make Apps work using that approach. We'd welcome a patch to enable that, I suspect.

**Comment by Rickan5500** [comment]
I have tried `sudo apt-get install libpng-dev` and then the build proceeded.

**Comment by zhang-xun** [comment]
https://github.com/halide/Halide/blob/main/tools/halide_image_io.h
