### ISSUE TITLE
bitwise_and(a, b) simplifies to b when b is a uint32_t

### ISSUE THREAD

**Issue by joelkoerwer** [halide/Halide#1860]
In the modified version of `test/correctness/bitwise_ops.cpp` below, `input(x) & mask` gets simplified to `mask`. 

`mask & input(x)` is fine. Also works if `mask_val` is an `int32_t`.

The output with `HL_DEBUG_CODEGEN=2` shows `bitwise_and` getting replaced after "Lowering after first simplification," but I haven't been able to track down exactly where it's happening.

```c++
#include "Halide.h"
#include <stdio.h>

using namespace Halide;

int main(int argc, char **argv) {
  Buffer<uint32_t> input(256);
  for (int i = 0; i < 256; i++) {
    input(i) = rand();
  }

  uint32_t mask_val = 0xaaaaaaaa;
  Expr mask(mask_val);

  Func f3;
  Var x;
  f3(x) = input(x) & mask;
  Buffer<uint32_t> im3 = f3.realize(128);
  for (int x = 0; x < 128; x++) {
    uint32_t correct = input(x) & mask_val;
    if (im3(x) != correct) {
      printf("%#010x & %#010x -> %#010x instead of %#010x\n", input(x),
             mask_val, im3(x), correct);
      return -1;
    }
  }

  printf("Success!\n");
  return 0;
}
```
Example output:
```ShellSession
~/Code/temp$ DYLD_LIBRARY_PATH=~/Code/halide-binary/bin ./a.out
0x000041a7 & 0xaaaaaaaa -> 0xaaaaaaaa instead of 0x000000a2
```

**Comment by zvookin** [comment]
Thank you for the bug report. Should have a fix shortly. (One of the branches in the handling of bitwise_and in simplify does not set the result expr properly.)

**Comment by zvookin** [comment]
Fixed by https://github.com/halide/Halide/commit/5371cd01b9702403ca3a6f3c6f05aba59e7fe3e6 .
