### ISSUE TITLE
How to link halide runtime extern functions to generated C++?

### ISSUE THREAD

**Issue by were** [halide/Halide#1884]
`````C++
Func f;
f.compile_to_file("f", {params}, "f");
`````
If I use Halide generator in this fashion, I can easily link the `.h` & `.o` by passing `libHalide.a` to the linker, which works well.
`````
g++ f.o test.cpp libHalide.a  -o test #it is OK
`````

`````C++
Func f;
f.compile_to_header("f.h", {params}, "f");
f.compile_to_c("f.cpp", {params}, "f");
`````

`````
g++ f.cpp test.cpp libHalide.a -o test #it crashes
`````
Something like this happens:

Undefined symbols for architecture x86_64:
  "__halide_buffer_init", referenced from:
      __top(buffer_t*, buffer_t*) in f-780ab8.o

I know these are halide runtime functions, but how can I link these extern functions?

My Platform is OS 10.12 with the latest Halide.

**Comment by zvookin** [comment]
You should not need to pass libHalide.a to the linker when linking
generated output from Halide. You only need libHalide.a when using the
compiler.

Can you look in f.cpp to see if "_halide_buffer_init" is declared as an
inline routine there? It should be. If so, the question is why it isn't
being found.

-Z-

**Comment by were** [comment]
Yep, it is inlined.

What should I do to get rid of this problem?

**Comment by were** [comment]
Not only `_halide_buffer_init` but also something like `_halide_malloc` and `_halide_free`.
Cuz `_halide_buffer_init` seems to be defined inside the `.cpp` file?

**Comment by zvookin** [comment]
Are you calling this routine from somewhere other than in f.cpp? If not, we
need to determine why an inlined function in f.cpp is not satisfying the
link time requirement here. If you are calling it from another file, then
that explains why the link is failing.

The easiest way to get an entire runtime is to generate a standalone
runtime using gengen, but I don't think _halide_buffer_init is an exported
runtime function. Our suggested way of getting such functionality outside
of Halide generated code is to use the Buffer (template) class in
HalideBuffer.h .

-Z-

**Comment by abadams** [comment]
It sounds like the runtime is just missing. I don't think
_halide_buffer_init gets inlined, and halide_malloc certainly doesn't.
You'll need to link to a Halide runtime. You can generate one with the -r
option on any generator. See apps/c_backend for an example.

**Comment by were** [comment]
For the first issue:
Actually, I am doing something like this:
`````
g++ f.cpp g.cpp test.cpp -o test
`````
Both `f.cpp` and `g.cpp` are Halide generated C++ code and both of them call that routine. However, I don't think it is the problem.

I used `Buffer` in `test.cpp` and it is convenient. 

Return to the origin problem: even though I only compile the generated `f.cpp` and the caller `test.cpp`, the compiler throws error when linking.

**Comment by were** [comment]
I tried to study the example inside `c_backend` folder, but I got nothing useful by reading the compiling options.
What should I do? I am not very used to using Generator.

**Comment by zvookin** [comment]
Are there two declarations for _halide_buffer_init in f.cpp, one inlined
and one extern "C"? That is our current theory for the bug.

-Z-

**Comment by were** [comment]
Yes, there are two.
One is inlined and embraced by #ifdef macro and the other is embraced by extern "C" {}.

**Comment by abadams** [comment]
Delete the extern "C" declaration, we shouldn't be emitting it. We'll fix
that in master. Sorry, the C backend is not widely used.

I guess the c_backend doesn't actually demonstrate a standalone runtime,
sorry. To resolve halide_malloc and halide_free

make bin/runtime.generator
./bin/runtime.generator -r halide_runtime -o . target=host

That should produce halide_runtime.a for the host target in the current
directory.

**Comment by were** [comment]
And then, I pass the halide_runtime.a to the compiler and compile them together?
OK, I will erase the extern emission in the compiler, too.

**Comment by were** [comment]
Thank you! It works! Close this issue!

**Comment by were** [comment]
So, the `_halide_buffer_init` in `extern "C"` is determined by `ExternCallPrototypes`, right?

**Comment by zvookin** [comment]
Closing this. Please reopen if I'm missing something.
