### ISSUE TITLE
How to enable cross platform target?

### ISSUE THREAD

**Issue by were** [halide/Halide#1888]
I am now on RedHat Linux and I want to make the Halide targeted to arm-core Linux.

What should I do to build Halide, which enables arm-core Linux target.

**Comment by zvookin** [comment]
If your llvm has ARM configured, Halide itself should already support
generating code for ARM.

To compile Halide for a different target, the Halide::Target passed to the
compile call just needs to specify the correct options. How that is done
depends on how you are building. It can be  in C++ code, passed in via the
HL_TARGET environment variable, specified on the command line to gengen.sh,
or in a build rule for bazel or a CMake macro argument.

-Z-

**Comment by were** [comment]
I mean, even for ARM core, there are different ARM targets., like `arm-linux-gnueabihf` and `arm-linux-gnueabi`. Does it work for both of them?

**Comment by were** [comment]
Yesterday, my Halide worked well locally. Today I just deployed it on the server. It was built successfully and passed tests, but I cannot run any examples. I get something like this:

g++ -std=c++11 -I ../../include/ -I ../../tools/ -I ../../apps/support/ -fno-rtti halide_blur_generator.cpp ../../lib/libHalide.a ../../tools/GenGen.cpp -o bin/halide_blur_exec  -ldl -lpthread -lz
../../lib/libHalide.a(llvm_514_Process.cpp.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
Process.cpp:(.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0x76): undefined reference to `setupterm'
Process.cpp:(.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0xa0): undefined reference to `tigetnum'
Process.cpp:(.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0xa9): undefined reference to `set_curterm'
Process.cpp:(.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0xb1): undefined reference to `del_curterm'
collect2: error: ld returned 1 exit status
make: *** [bin/halide_blur_exec] Error 1

**Comment by abadams** [comment]
It looks like your LLVM was compiled with libterminfo. Try adding
-lterminfo to the link line, or compile llvm without it.

**Comment by abadams** [comment]
For the other question: I think arm-linux-gnueabihf corresponds to the
halide target arm-32-linux (or arm-64-linux), and the version without hard
float is arm-32-linux-soft_float_abi

**Comment by were** [comment]
No, it does not work. There's no -lterminfor on the server at all.

**Comment by kgnk** [comment]
From experience I can say that the llvm build will look for TERM and, if it is present, use terminfo for colored output. Build llvm without terminfo with `cmake -DLLVM_ENABLE_TERMINFO=OFF ...`

**Comment by were** [comment]
Actually, on the server, the llvm has been compiled, so I have to find somewhere else to re-download and re-compile it.

When executing `cmake`, I got this error message:
`````
Host compiler must support std::atomic!
`````

**Comment by were** [comment]
My host compiler is gcc 6.1.0

**Comment by were** [comment]
OK, for the second problem, it should be -ltinfo rather than -lterminfo

**Comment by zvookin** [comment]
Is there a Halide issue here? If so, can it be identified more clearly? If not, may we close this issue? (My quick perusal shows a series of problems with llvm build dependencies.)

Halide itself strives to always be able to cross compile from any host to any target, so long as llvm is built with the proper support. It is possible Halide's Target does not have flags for the exact ARM options needed. If this is the case, please let us know which options you need and we will endeavor to provide a way to get the right compilation configuration in llvm.

**Comment by were** [comment]
Close this one. I am no longer facing this issue now.
