### ISSUE TITLE
Halide::Func::gpu(...) wrong order of arguments

### ISSUE THREAD

**Issue by takanokage** [halide/Halide#1898]
Hi,

I've been trying Halide for a couple of weeks now and stumbled upon what might be an issue.
func.gpu(x_out, y_out, z_out, x_in, y_in, z_in); // THIS IS WHAT THE DOCS SAY
func.gpu(z_in, z_out, y_out, y_in, x_in, x_out); // THIS IS WHAT ACTUALLY WORKS

Any ideas?
Thanks!

The current revision I'm using (from the continuous build server):
170301: halide-win-32-trunk-09f406a034f40f8552e68a05bad3b11208e567d9.zip

The release from 161022 seems to be broken also, although the order of arguments seems different yet again.
161022: halide-win-32-trunk-aa5d5514f179bf0ffe1a2dead0c0eb7300b4069a.zip 

This is my use case:
- 3D func
- I explicitely split the dimensions
- pls. ignore the actual values of the inner dimensions below; just a random combination
- I explicitely schedule the execution on the GPU given the above split dimensions

func.split(x, x_out, x_in, 16);
func.split(y, y_out, y_in, 1);
func.split(z, z_out, z_in, 1);
func.gpu(x_out, y_out, z_out, x_in, y_in, z_in); // THIS IS WHAT THE DOCS SAY
func.gpu(z_in, z_out, y_out, y_in, x_in, x_out); // THIS IS WHAT ACTUALLY WORKS

**Comment by psuriana** [comment]
For the given schedule above, it will generate the following loop nests:
```
for z_out:
  for z_in:
    for y_out:
      for y_in:
        for x_out:
          for x_in:
             ....
```
You will need to reorder the loop dimensions first by calling `f.reorder(x_in, y_in, z_in, x_out, y_out, z_out)` before calling `func.gpu(x_out, y_out, z_out, x_in, y_in, z_in)`. Otherwise, it won't be valid since you can't have interleaving GPU block and GPU threads.

Alternatively, you can use the following instead:
`f.gpu_tile(x, y, z, x_out, y_out, z_out, x_in, y_in, z_in, 16, 1, 1);`
This will do the splits, reorder, and mark the GPU threads/blocks.

**Comment by jrk** [comment]
To be extra explicit: the issue you ran into is that `Func::gpu` just marks the loops to map to GPU thread and block dimensions, *but it does not actually reorder the loops*. A valid mapping to the GPU requires *both* that the desired loops are marked to be mapped to the corresponding kernel dimensions, *and* that those loops have a specific structure:

- the block loops have to be outside the thread loops
- no computation or storage can come between any of the block loops, or between any of the thread loops. (Storage can exist at the boundary between the block and thread loops, and the body of the innermost block loop can be a sequence of nests of thread loops.)

Roughly speaking, the loop nest has to look like:

    for all blocks:
      // potentially some allocations
      for all threads:
        // arbitrary code
      // arbitrarily many more threads sub-loops of this form...
      for all threads:
        // arbitrary code
      // ....

`for all blocks` and `for all threads` can each be 1, 2, 3, or 4 deep, depending on how many you've mapped, but the relative order within each of them doesn't matter.

For example:

    for a-block-var:
      for another-block-var:
        allocate block-data
        for a-thread-var:
          for another-thread-var:
            // arbitrary code
        for another-thread-var:
          for a-thread-var:
            // arbitrary code
        for a-thread-var:
          for another-thread-var:
            // arbitrary code

Notice that the relative ordering between `a-block-var` and `another-block-var`, or between `a-thread-var` and `another-thread-var` doesn't matter, but that:

- Nothing happens *between* the different block loops (or the different thread loops), just either all the way inside or outside all of them.
- Blocks are outside threads.
- There are the same number of block and thread variables.

Again, `Func::gpu(…)` doesn't change the loop order and so doesn't enforce any of this ordering, it just marks the given loops as corresponding to the given GPU kernel dimensions. If you don't also be sure that the structure of those loops is valid, the compiler will tell you you've asked for something invalid.
