### ISSUE TITLE
apps/fft no longer compiling

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#1925]
As of (at least) 555da1fcc3a536e35922736e1eb2f9a4cfa49847, "make fft_aot_test" fails with `Cannot vectorize dimension x.v436 of function constant_exterior because the function is scheduled inline.` The FFT app itself hasn't been changed recently, so presumably a recent change to Halide itself has triggered this.

**Comment by psuriana** [comment]
This PR #1920 should fix the problem.
