### ISSUE TITLE
Typo in Tutorial 5?

### ISSUE THREAD

**Issue by multigrid101** [halide/Halide#1930]
Is it possible that there is a small typo in `lesson_05_scheduling_01.cpp` in the section on parallelizing across tiles, specifically in the "equivalent C code"? The halide code is processing an 8x8 picture, but in the C-code, it seems like a 16x16 picture is being processed.

Might be a dumb question but I only just got started on the tutorials so I wanna make sure that I got this right :)

**Comment by abadams** [comment]
You are right, the outer loop should have extent 4, because there are 4
tiles being processed. With the two inner loops, that makes 4x4x4 in the
inner loop, which compute the 8x8 pixels in the output.

**Comment by multigrid101** [comment]
Thanks a lot for the clarification
