### ISSUE TITLE
Add compute_together() to make Tuple at schedule time.

### ISSUE THREAD

**Issue by kgnk** [halide/Halide#1943]
Given a few `Func` definitions that use the same input data region:

```
Func adder("adder"), suber("suber");
adder(x) = input(x - 1) + input(x + 1);
suber(x) = input(x - 1) - input(x + 1);
```

The way to calculate these two to take advantage of data cache is to put them in `Tuple`:

```
Func mathing("mathing");
mathing(x) = Tuple(adder(x), suber(x));
...
mathing.gpu_tile(x ,256).compute_root();
```

But that is an algorithm construct to accomplish a scheduling task. Instead, I propose:

```
compute_together(adder, suber, "mathing").gpu_tile(x, 256).compute_root();
```

It would create `Func mathing("mathing")` as a tuple of the pure definitions of its parameters and redefine the parameter `Func`s to extract the `Tuple` value. This allows `adder` or `suber` to be used in algorithm code to mean one of the `Tuple` values.

**Comment by shoaibkamil** [comment]
There's also the approach in #1546, which does this in a more general way.  This approach requires the `min`s and `extent`s to be the same in each dimension, I believe.

**Comment by psuriana** [comment]
The mins/extents don't have to necessarily be equal. `compute_with` will compute the union of the two and add guard the loops with predicates. Only the loop dimension ordering needs to be the same.

**Comment by kgnk** [comment]
Super. That PR is 5 months old and now has conflicts.
