### ISSUE TITLE
Buffer is unallocated in simple pipeline on Windows.

### ISSUE THREAD

**Issue by dkurt** [halide/Halide#1952]
Hi! Catched error in simple pipeline on Windows. Works on Ubuntu 16.04 and worked on Windows some time ago. Thank you!
```cpp
Halide::Func f("f");
Halide::Var x("x");
f(x) = x;
f.bound(x, 0, 16);
Halide::Buffer<int> output(16);
f.realize(output);
```

```
Error:
Buffer at 000002B2CE89ACE0 is unallocated. The Buffers in a Realization passed to realize must all be allocated
```

Commit: d8f1ff287ee389da1f52101eb65b6b8c284da01f
OS: Windows 64bit

Update: problem since 749be8636d89fc30141244a65dfbb3b04fd69a28.

**Comment by abadams** [comment]
Works for me locally. If this were generally broken then our windows buildbots would be very unhappy. I could imagine this happening with mismatched Halide.h and Halide.dll or something. Try a clean rebuild?

**Comment by dkurt** [comment]
Thank you @abadams ! I will try.

**Comment by dkurt** [comment]
Solved by placing Halide.dll near .exe.
