### ISSUE TITLE
Generating stmt html failed in the sample camera_pipe app

### ISSUE THREAD

**Issue by xiaoyongaz** [halide/Halide#1956]
I am trying to understand more about scheduling so added below into the camera_pipe_generator.cpp in apps/camera_pipe 
processed.compile_to_lowered_stmt("processed.html", {}, HTML);

during make, I got below error, what does this mean? thanks
----------------------------------------------------------------------------
User error triggered at Halide/src/Pipeline.cpp:507
Error:
Generated code refers to image parameter input, which was not found in the argument list.

Argument list specified: curved 

Parameters referenced in generated code: input matrix_3200 matrix_7000 blackLevel color_temp contrast gamma whiteLevel 

Makefile:12: recipe for target 'bin/camera_pipe.a' failed
make: *** [bin/camera_pipe.a] Aborted

**Comment by shoaibkamil** [comment]
I believe you need to pass in the input parameters to the function `compile_to_lowered_stmt()`.  In this case, it looks like the inputs are all the `ImageParam`s and `Param`s in lines 16-23 in `camera_pipe_generator.cpp`.  Try something like:
```
processed.compile_to_lowered_stmt("processed.html", 
                  {input, matrix_3200, matrix_7000, color_temp, gamma, contrast, blackLevel, whiteLevel},
                  HTML);
```

**Comment by xiaoyongaz** [comment]
thanks a lot, that is the problem. the message about "Argument list specified: curved" confused me, should have read the doc:)
