### ISSUE TITLE
apps/forward_fft_r2c runs much slower than apps/inverse_fft_c2r in AOT mode

### ISSUE THREAD

**Issue by yichang** [halide/Halide#2002]
I have benchmarked the performance of 16-by-16 forward_fft_r2c and 16-by-16 inverse_fft_c2r in AOT mode by injecting timing code in the apps/fft/fft_aot_test.cpp:

@@ -75,6 +77,16 @@ int main(int argc, char **argv) { 
         int halide_result;
      clock_t begin = clock();
      for(int i = 0; i < 100000; ++i){
           halide_result = fft_forward_r2c(&in, &out);
       }
        clock_t end = clock();
        double elapsed_secs = double(end - begin) / CLOCKS_PER_SEC;
       std::cout<<"r2c time (100ktimes)= " << elapsed_secs <<std::endl;

and similarly for c2r version. What I found is that the c2r version is 200x slower than r2c version. The benchmark from JIT mode indicates the two function call runs about the same. In theory the two function call should have similar speed.

Git version: release_2016_10_25
Target: x86-64-linux-avx-avx2-f16c-fma-no_asserts-no_bounds_query-no_runtime-sse41
Environment: Ubuntu VM-ware on MPR
Compilation: use the provided Makefile in the release.

I wonder if this is a limitation or a bug, or something I went wrong. Thanks.

**Comment by dsharletg** [comment]
There are some bugs in this schedule. I'm pushing up a PR to fix this. I'm finding that c2r is now ~10x faster than it was, and r2c is now ~160x faster than it was.
