### ISSUE TITLE
Todo: Rebuild tutorials @ http://halide-lang.org/tutorials/

### ISSUE THREAD

**Issue by sschnug** [halide/Halide#2005]
Hi,

while currently trying to understand and use Halide, it was really annoying to debug at least (i think there are missing linker-options too in earlier tutorials; but continue reading) the chapters:

- AOT compilation part 1 / AOT compilation part 2
    - (function-name generated in header changed; old vs. new buffer).

At first i thought, that these are just not well-maintained, but seeing those updated versions within this repository, someone should really rebuild the docs [here](http://halide-lang.org/tutorials/)

Sascha

**Comment by abadams** [comment]
In theory the tutorials match the last binary release. Perhaps I forgot to
update them last time? They generally won't be up to date with trunk.

**Comment by sschnug** [comment]
I don't have much overview yet, but:

- Both tutorial sources [here](http://halide-lang.org/tutorials/tutorial_lesson_10_aot_compilation_run.html) and [here](http://halide-lang.org/docs/tutorial_2lesson_10_aot_compilation_run_8cpp-example.html) are outdated and don't use the new Buffer-Interface (besides other problems)
    - **Extra:** Both are also out of sync (different chapters)
- The new BufferInterface is mentioned in the comments on release **Halide 2016/10/22**
    - It looks, like there is a missing update for 6 months now

**Comment by abadams** [comment]
I need to finish working on the new tutorial about Func::in and get it
merged. Then I'll do a fresh release and update the tutorials on the
website. Plan to work on this over the next few days.

**Comment by sschnug** [comment]
Maybe there is some merit to add [this example](https://gist.github.com/sschnug/c8eeaf5cd81eb1ec04220fb36bb202c7) too in the next iteration, which is based on [this SO-question](http://stackoverflow.com/questions/43455570/halide-how-to-process-image-in-overlapping-blocks) answered by @dsharletg.

This operation feels very natural/common and i think it would be a good addition for newcomers, either as:

- Tutorial (most amount of work)
- App
- Test

**Comment by abadams** [comment]
Yeah, tiled processing is probably a good idea for a tutorial. It comes up
frequently and it's not obvious how to do it for newcomers. I'll add it to
my todo list.

**Comment by jph00** [comment]
Any update on this? I'd really like to teach halide in an upcoming class, but I feel nervous without current tutorials...

**Comment by abadams** [comment]
I did a release and updated the tutorials about a week ago. There's no tiled processing tutorial yet.
