### ISSUE TITLE
CSE on non-pure function calls

### ISSUE THREAD

**Issue by SanderVocke** [halide/Halide#2052]
I noticed that one of my apps, which has multiple side-effecty function calls, has a CSE problem. CSE restructures the code so that the side-effecty call is made only once (although I want the side-effect to occur multiple times and/or in a different order).

Shouldn't CSE leave Calls of type Intrinsic and Extern untouched (as opposed to PureExtern and PureIntrinsic)? After all, the compiler doesn't know whether moving the side-effecty versions around may influence correctness of the code.

If this is indeed the case, I can submit test code exposing the problem and/or a fix, but first I wanted to check if this is really unintended behavior.

**Comment by abadams** [comment]
That seems like a bug. Not intended behavior.

**Comment by abadams** [comment]
(and a patch would be welcome)

**Comment by SanderVocke** [comment]
Made a fix in pull request: #2055

**Comment by abadams** [comment]
Fixed. Thanks for the bug report and your PR.
