### ISSUE TITLE
Buffer move constructor forgets to call `assert_can_convert_from`

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2057]
Reported externally:

I ran into a bug in Halide::Runtime::Buffer. This is erroneous code is currently allowed, but should be catchable at compile time:

```
Buffer<uint8_t> Foo() { ... }
Buffer<float> buffer = Foo();
```

Looks like the problem is that this move constructor forgets to call  `assert_can_convert_from(other)`:

```
template<typename T2, int D2>
Buffer(Buffer<T2, D2> &&other)
```

**Comment by dsharletg** [comment]
It looks like this is fixed.
