### ISSUE TITLE
undefined reference to `Halide::Internal::Introspection::get_source_location()'

### ISSUE THREAD

**Issue by hrishikeshv** [halide/Halide#2062]
I am trying to compile **interpolate.cpp** using llvm3.8. llvm3.8 was built with clang and polly. However I am getting an undefined reference error. The following command is being used to compile the cpp file.

**clang++ -O3 -std=c++11 -I ../../include/ -I ../../tools/ -I ../../apps/support/ interpolate.cpp ../../lib/libHalide.a -lpng12 -ljpeg -I/usr/include/libpng12 -I/usr/include/libpng12/..  -ldl -lpthread -lz -ltinfo** 

Any help is appreciated..!!

**Comment by zvookin** [comment]
How are you building, or getting libHalide.a?

-Z-

**Comment by hrishikeshv** [comment]
Just executing **make** in the Halide home folder.

**Comment by codestamp** [comment]
@hrishikeshv did you get the solution? I am also getting undefined reference to all Halide functions.

**Comment by hrishikeshv** [comment]
_@codestamp_ I faced linker issues with llvm version 3.7 and 3.8. Following that I built llvm 3.9 and was able to compile Halide programs.

**Comment by codestamp** [comment]
Thanks @hrishikeshv I will try llvm 3.9.

**Comment by codestamp** [comment]
@hrishikeshv sorry to bother you. How were you able to link the llvm-3.9 to halide?

**Comment by steven-johnson** [comment]
Is this still an open issue? If not, will close.

**Comment by codestamp** [comment]
Yes Steven you can ahead and close this issue. Personally, I am off this topic.

**Comment by shipingli** [comment]
I am using Halide 2.0 and stuck on this issue, any solutions?

Thanks

**Comment by dliang0406** [comment]
I met the same issue with the Halide v2.0 downloaded from Qualcomm:
https://developer.qualcomm.com/software/hexagon-dsp-sdk/tools

The generator cannot be generated due to this issue:
/home/dliang/Qualcomm/HALIDE_Tools/2.0/Halide/include/Halide.h:415: undefined reference to `Halide::Internal::Introspection::get_source_location[abi:cxx11]()'
