### ISSUE TITLE
Suspect oversimplification of concatenated adjacent vector loads

### ISSUE THREAD

**Issue by SanderVocke** [halide/Halide#2068]
Hi,

I noticed a simplification on adjacent, dense vector loads that seems strange. It may be an issue.

If two loads are concatenated, and those loads are to adjacent vectors in memory, the simplifier turns this into a single load of double width. This is happening only since sometime in the last month.

 The following code demonstrates it:

```
#include "Halide.h"

using namespace Halide;
using namespace Internal;

int main(int argc, char **argv) {

    Expr ld1 = Load::make(Int(32,4), "dummy",
                            Ramp::make(0, 1, 4), Buffer<>(),
                            Parameter(), make_bool(true,4));
    Expr ld2 = Load::make(Int(32,4), "dummy",
                            Ramp::make(4, 1, 4), Buffer<>(),
                            Parameter(), make_bool(true,4));
    Expr shuffle = Shuffle::make_concat({ld1, ld2});

    Expr simplified = simplify(shuffle);

    debug(0) << "Before:\n" << shuffle << "\nAfter:\n" << simplified << "\n";
    return 0;

}
```

output:

```
Before:
concat_vectors(dummy[ramp(0, 1, 4)], dummy[ramp(4, 1, 4)])
After:
dummy[ramp(0, 1, 8)]
```

The reason it seems strange is that Halide is making an assumption that the code generation back-end supports the double-width load. Also, although I don't know exaclty how the simplifier works, I was unable to find a simplification rule which seems to target this particular transformation (something seems to be there, but it is targeting only concatenated Ramps, not Loads).

 Is this a bug?

**Comment by abadams** [comment]
We require backends support arbitrary-width vectors, and slice them up into
native vectors in the backend if it must. Normally llvm does that
legalization. Another transformation that might create large vectors is in
Deinterleave.cpp, so it's not just this simplifier rule.

Note that the simplifier doesn't know the target, so on a machine with
avx2, for example, this would be a good optimization.

**Comment by SanderVocke** [comment]
Thanks, got it!
