### ISSUE TITLE
C/C++ backend doesn't emit _argv() wrapper or _metadata() accessor

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2071]
These are rarely used, and thus not necessarily a deal-breaker for many users, but it does make the C/C++ backend incomplete relative to other backends.

**Comment by zvookin** [comment]
Is it possible to generate Halide IR which compiles to these accessors? If
so, it would be cool to change the way we make these to go through IR (e.g.
adding a couple of LoweredFuncs to the Halide::Module) instead of being
specific to LLVM codegen.

-Z-

**Comment by steven-johnson** [comment]
Good question. I'm not sure.

**Comment by steven-johnson** [comment]
Fixed by #6179
