### ISSUE TITLE
C/C++ backend should clarify C vs C++ requirement

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2085]
Some of the code seems to assume we might be compiling for straight C, but this is already violated in several places (eg using destructors for cleanup). If we want to require C++ code, let's make that clear and remove and dangling cruft.

**Comment by zvookin** [comment]
The backend is a C++ backend. Headers need to be includable in C code,
hence there may be some ifdefs testing cplusplus the the generated headers.
I absolutely agree that as we make this a more first class thing, we should
document the requirements on code produced and give insight into the
mechanisms it uses, but it would require a fairly significant reversal of
direction to make its output compile with a C compiler.

**Comment by steven-johnson** [comment]
Marking as resolved. I'll keep it in mind as I fix the various C++ backend issues I've found.
