### ISSUE TITLE
C++ backend should be able to use Halide runtime for parallel.

### ISSUE THREAD

**Issue by zvookin** [halide/Halide#2093]
Currently, the C++ backend uses "#pragma omp parallel" to emit parallel for loops. We should make this an option under a Target flag and also put in code to call halide_do_par_for with appropriate closures.

**Comment by abadams** [comment]
Also, #pragma omp parallel needs some more love if it's to work - right now we try to return from inside parallel blocks on error (e.g. allocation failure), which is not allowed in openmp.

**Comment by zvookin** [comment]
We also need to do something about async in C++ codegen. Adding to this bug as moving to our own runtime would fix this.
