### ISSUE TITLE
C++ Backend should offer option to do vectorization via short explicit loops

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2107]
Until recently, the C++ backend simply refused to emit code that used vectorization. PR#2067 (still pending at the time of this issue being opened) proposes to support vectors via the builtin vector extensions in Clang/GCC; however, this has some drawbacks that are concerning:

- GCC doesn't support vectors that are non-power-of-two in size, and probably never will
- GCC doesn't support conversion between element size/types (must go thru memory)
- The support in both GCC and Clang is nonstandard, so will likely be flaky as compiler versions are revised, and other compilers still won't work at all (most notably, MSVC)

Suggested workaround is to write our own templated "cpp_vector" class, complete with appropriate operator overloading, that can serve as (mostly) a drop-in replacement for the clang/gcc code; it will do everything using plain C++ code and will serve as a functional (though not performant) replacement. Idea is to use it as a fallback for cases we can't serve above, or (if user requests it) in place of everything else, e.g.

```
#if HALIDE_USE_SIMPLE_CPP_VECTORIZATION
   // use cpp_vector everywhere
#else
   #if CLANG
      // use Clang's vector support
   #elif GCC
      // use GCC's vector support for power-of-2, cpp_vector otherwise
   #else  // MSVC, etc
      // always use cpp_vector
   #endif
#endif
```

**Comment by steven-johnson** [comment]
Note also that (AFAICT), neither GCC nor Clang offer any way to use vectorized versions of commonly-available-in-SIMDS ops like floor/ceil (->roundps/roundpd, etc), min/max, etc.

**Comment by zvookin** [comment]
Yes, we effectively have to scalarize all function calls.

**Comment by kgnk** [comment]
There should be free functions that accept `cpp_vector` values for functions like floor/ceil, min/max, etc. They should be provided separately so they can be replaced. For instance, rather than using scalar C runtime library calls, using x86 intrinsics.

See also [Boost.SIMD](https://github.com/NumScale/boost.simd)
