### ISSUE TITLE
Reduction of vector into scalar

### ISSUE THREAD

**Issue by SanderVocke** [halide/Halide#2114]
Hi,

Has it been considered at any point to extend Halide's vectorization to deal with vector-to-scalar reductions - at least in the front end? 

Such an extension would allow back-ends to select more vector instructions, for example:
- taking the maximum element of a vector (result of vectorizing a reduction loop taking the max of N elements)
- likewise, but taking the sum / average / minimum / etc. of a vector.

Currently, trying to force something like this by calling allow_race_conditions() in combination with vectorize() on an RVar, the result is something which is incorrect (although fair enough, Halide warns the user about that).

When vectorizing:
```
for x in (0..N):
  out(0) += in(x)
```
the result is:
```
out( xN(0) ) += in( ramp(x, 1, N) )
```

Which implies not summing the elements, but "storing them over each other".

Maybe this should produce a Halide intrinsic which back-ends can recognize? For example:

```
out(0) += internal_sum( in( ramp(x, 1, N) )
```

To be fair, I don't know of a whole lot of architectures with such instructions available. One that comes to mind is the SSE4.1 minpos_epu16 instruction, which takes the minimum element (and as a byproduct, its position) of a vector. I don't know about Hexagon.

What are your thoughts on this?

**Comment by kgnk** [comment]
I was able to work out a maximum value of an entire image in OpenCL by breaking it down to blocks, each block having threads, each thread working in a vector over some area before reducing the vector to a single element, reducing the thread results at the block level in vectors and reducing that to a single element per block, reducing the block results in a vector and, finally, reducing the vector to get the final result.

Although I implemented this using a function for each level at the algorithm side of things, the proper place for this kind of subdivision is on the scheduling side. This can be done by first splitting the domain into the appropriate sizes with `split` and then breaking each level out into its own function using `rfactor`.

Although the code for the above might be a good illustration of what can be done with `rfactor`, how the levels are broken down is based on the hardware I wanted to run it on.

**Comment by zvookin** [comment]
It is a bit unclear which part of the question is algorithm specification,
which is scheduling, which is lowering, and which is code generation.

Theoretically we have RDom/reductions at the algorithm level and rfactor at
the scheduling level. Any change to lowering would likely need either some
new input from scheduling or some target dependent decisions as horizontal
ops are very processor dependent. I believe rfactor gets you the storage
reduction, but I may be missing something.

At codegen time, one can theoretically peephole something, but it gets to
be a fairly large pattern, possibly involving a loop over a fixed size,
maybe with some loads or stores. This is not an incredibly productive
approach. Packaging up reduction loops over a single vector into some sort
of IR node, or scoped bit of IR might well be a win. We currently have a
constraint in IR that requires all nodes except Broadcast and Shuffle to
preserve the vector width. This would be another node type that changes
vector width. (Currently any such reduction likely goes to memory and then
uses a scalar loop. It could also be a loop over Shuffle operations, each
extracting one lane.)

One specific case I've though about which is similar, if not exactly the
same, is special casing "all true" and "all false" conditions in masks.
which code is vectorized. Most processors end up providing cheap horizontal
reductions of booleans on vectors. (E.g. all true -> horizontal-and, all
false -> not-horizontal-or.) These come up in handling masks in graphics as
well as other contexts. The question is how to handle specifying that it is
worthwhile to special case the condition by putting an if around a larger
block of vectorized code. It also has similar issues of IR representation
once it has been decided to put in the if. I thought about having
"all_true(some_vector_of_bool)" and "all_false(some_vector_of_bool)" but it
didn't seem very satisfying. Certainly any design that surfaces the
intrinsic to a programmer seems to fail horribly as vectors themselves are
not really visible to users.

One could do something like:
    select(all_false_likely(mask(x)), processed(x), input(x));
which would indicate to the compiler that after vectorization, there should
be an if per vectorized unit. (Theoretically we could overload the likely()
intrinsic for this.) I believe the same addition to IR that solved the
above would be useful here.

-Z-

**Comment by abadams** [comment]
To the extent that vectors exist in the front end, they are Vars. Vectors
correspond to a data-parallel axis of a Func, not one of our element types.
Reductions over an axis operate over RVars, and so rfactor does indeed get
you what you want by turning those RVars into Vars that can then be vector
lanes. I believe it addresses this almost entirely at the scheduling level,
though it can be awkward to use. At the codegen level, this might not get
you what you want just because there are still many missing peepholes for
the individual reduction-by-2/4x steps. E.g. we don't generate vrmpy this
way.

On a related topic to vectorized selects, note that vectorizing
if_then_else(likely(mask(x)), processed(x), input(x)) already generates an
all-true branch, but it does it by statically deriving a sufficient scalar
condition for all the lanes of mask(x) to be true, not by generating the
whole vector of bools and then reducing it horizontally. See
VectorizeLoops.cpp line 708.

- Andrew

**Comment by zvookin** [comment]
One other comment on this: often horizontal op instructions are partial.
E.g. the horizontal adds on X86 generally reduce the vector by 2x per
instruction. So one uses a sequence of them. I don't think we want to
surface that level of detail anywhere close to the frontend or programmer,
but this does mean the scheduling space is even larger. (I expect the only
thing that ever makes sense for a complete reduction is to reduce the
entire vector to a scalar, but one can imagine algorithms where adjacent
pairs are summed and then more work is done. In that case, one is
effectively vectorizing a vector reduction of 2-wide vectors.)

-Z-

**Comment by SanderVocke** [comment]
@abadams : I don't think that _rfactor_ has much to do with the question. It turns reduction domains partially into pure Vars which can be parallelized. But what I was referring to was a reduction of a vector into a scalar (a "horizontal" operation that reduces vector lanes). I believe you only describe this when directly vectorizing over an RVar, not applying _rfactor_.

I am assuming that what @kgnk described also used rfactor, parallelizing only over pure Vars.

But as @zvookin also mentioned, the horizontal style of reduction cannot be adequately described using Halide's IR, because nodes preserve vector width. And I think the tiny example I gave illustrates that: the result is awkward, and in my opinion incorrect. To elaborate it a bit more (for example with an 8-way vector):

``` 
for x in 0...8 [vectorized]:
  out(0) += in(x)
```

If this passes through the Vectorize lowering step, we get:

```
out( x8(0) ) = out( x8(0) ) + in( ramp(0, 1, 8) )
```

In other words, what the IR describes is:

1. broadcast out(0) into a vector
2. load a dense vector from in
3. add them together (normal SIMD, non-reducing)
4. somehow store all 8 elements of the result into the same element in memory.

Step 4 is the reduction (it has been put in the store, not in the addition itself). And it is a nasty race condition with unclear semantics. You can actually do this by using allow_race_conditions() and vectorizing by 8 on x86. The resulting output is incorrect.

@zvookin : We could then do peephole optimization in the code generator and somehow turn this back into a proper horizontal accumulation operation, but in my opinion that is the wrong way to fix something that is now ambiguously represented in the IR. Also, we would still get warnings by the lowering passes about race conditions, before getting to code generation.

I have to admit that all I could find was one obscure x86 operation which actually does a full vector-to-scalar reduction of min(). The "hadd" ops only add subsets of the vector's elements. But this may be of interest for people working on new back-end targets, including FPGA code generation. I wouldn't be surprised if the Hexagon also has some instructions that could be targeted, but I don't have access to the HVX instruction set.

A new node could be an option. Maybe something called "Reduce" or "Merge", taking one or more vectors and an operation identifier ('+', '-', 'Max', ...) as node fields. As long as the semantics of the node are well-defined, I don't see why additional scheduling information would be needed from the user to peephole-optimize this onto target instructions (for example mapping onto a tree of 'hadd' ops on x86), or otherwise just serialize the operation again in the back-end.

**Comment by SanderVocke** [comment]
I only just noticed that the HVX instruction set reference is public. There are some instructions in there that could be targeted: basically any instruction of which the name starts with "vector reduce" (for example, _vraddub_).

**Comment by SanderVocke** [comment]
@zvookin Regarding your comment on partial reductions: that's a good point. Describing those kind of things would require new scheduling (or maybe even new functional) tools in the language. How would one describe, using Halide, a vectorized reduction by 2 of adjacent elements?

On the other hand, the simpler case of complete vector-to-scalar reduction can already be straightforwardly described with the existing scheduling primitives (simply vectorize over an RVar). It is just not supported by the lowering process and back-ends. Maybe it is best to stick with that for the time being.

**Comment by dsharletg** [comment]
I think we can do this pretty well now with atomic vectorization of reduction variables.
