### ISSUE TITLE
Undefined halide_weak_device_free

### ISSUE THREAD

**Issue by kgnk** [halide/Halide#2126]
Compiling for MacOS and using `Halide::Runtime::Buffer` but with no runtime.

    $ clang++ --version
    Apple LLVM version 8.1.0 (clang-802.0.42)
    Target: x86_64-apple-darwin16.6.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by kgnk** [comment]
I forgot to mention: Halide nightly build from May 24. a5fb99a

**Comment by abadams** [comment]
Addressed by #2036, which I intend to get back to once async done

**Comment by kgnk** [comment]
I'll leave this here until that lands and supply the missing function (which it isn't calling, anyway) until then.

**Comment by zvookin** [comment]
@abadams can we close this now?
