### ISSUE TITLE
Auto-schedule a Halide  pipeline processing an ImageParam

### ISSUE THREAD

**Issue by rcorvino** [halide/Halide#2141]
Hi,

I would like to generate a Halide static library taking as input an ImageParam.
And I would like to schedule the pipeline with the auto-scheduler.
Below you will find an example of vanilla Halide doing what I need.  

When I use the auto-scheduler, I must specify the size of input image, but this will create a library where the image size is a compile-time constant and it is explicitly used in the loop bounds and kernel computations. Below an example of a Halide code using the auto-scheduler and having this problem. 

Is there a way to fix my current Halide version using the auto-scheduler? 

  
```
	//without Auto-scheduler
	{
		ImageParam image(type_of<uint8_t>(), 2, "input_image");
		Param<uint8_t> factor;
		Var x("x"), y("y");
		Var x_vo("x_vo"), x_vi("x_vi");
		factor.set_range(0, 1);

		Func producer("producer"), consumer("consumer");
		producer(x, y) = image(x, y);
		consumer(x, y) = cast<uint8_t>((producer(x, y) +
			producer(x, y + 1) +
			producer(x + 1, y) +
			producer(x + 1, y + 1) + factor) / 4);


		Pipeline pipeline(consumer);

		//copy paste of the autoscheduler result
		pipeline.get_func("consumer")
			.compute_root()
			.split(x, x_vo, x_vi, 32)
			.vectorize(x_vi)
			.parallel(y);

		pipeline.compile_to_static_library("vanilla/file_name", { image, factor }, "function_name");


		//local test
                Buffer<uint8_t> input = Tools::load_image("images.png");
         	printf("Image size: %d, %d\n", input.width(), input.height());

		image.set(input);
		factor.set(1);
		pipeline.compile_jit();
		Buffer<uint8_t> output(input.height() - 1, input.width() - 1);
		pipeline.realize(output);
		save_image(output, "output.png");

	}

```

```
	//Auto-scheduler
	{
		Buffer<uint8_t> input = Tools::load_image("images.png");
         	printf("Image size: %d, %d\n", input.width(), input.height());

                ImageParam image(type_of<uint8_t>(), 2, "input_image");
		Param<uint8_t> factor;
		Var x("x"), y("y");
		factor.set_range(0, 1);

		Func producer("producer"), consumer("consumer");
		producer(x, y) = input(x, y);
		consumer(x, y) = cast<uint8_t>((producer(x, y) +
			producer(x, y + 1) +
			producer(x + 1, y) +
			producer(x + 1, y + 1) + factor) / 4);

		consumer.estimate(x, 0, input.height());
		consumer.estimate(y, 0, input.width());

		Pipeline pipeline(consumer);
		std::string r = pipeline.auto_schedule(get_host_target());
		pipeline.compile_to_static_library("auto/file_name", { image, factor }, "function_name");
		printf("Autoscheduler result: %s\n", r.c_str());


		//local test
 		factor.set(1);
		//image.set(input); <-- not needed
		pipeline.compile_jit();
		Buffer<uint8_t> output(input.height() - 1, input.width() - 1);
		pipeline.realize(output);
		save_image(output, "output.png");

	}
```

**Comment by psuriana** [comment]
You can use `set_bounds_estimate(min, extent)` to set the estimate on ImageParam. In your case, the code will look something like this:
```
    ImageParam input(UInt(8), 2, "input_image");
    Param<uint8_t> factor;
    Var x("x"), y("y");

    Func producer("producer"), consumer("consumer");
    producer(x, y) = input(x, y);
    consumer(x, y) = cast<uint8_t>((producer(x, y) +
                                    producer(x, y + 1) +
                                    producer(x + 1, y) +
                                    producer(x + 1, y + 1) + factor) / 4);

    // Provide estimate on Param
    factor.set_estimate((uint8_t)3);
    // Provide estimate on input ImageParam
    input.dim(0).set_bounds_estimate(0, 1536);
    input.dim(1).set_bounds_estimate(0, 2560);
    // Provide estimate on Output
    consumer.estimate(x, 0, 1536);
    consumer.estimate(y, 0, 2560);

    Pipeline pipeline(consumer);
    std::string r = pipeline.auto_schedule(get_host_target());
    printf("Autoscheduler result: %s\n", r.c_str());
```
Also, instead of `factor.set_range(0, 1)`, please use `set_estimate(val)` to provide estimate on a Param. The param range is not currently use by the auto-scheduler. Although it is not necessary to provide estimate on a Param, it is highly recommended since it may simplify the computed bounds by auto-scheduler into literal values. The current auto-scheduler doesn't handle symbolic constant. If it find one, it will give up and default to `compute_root` when deciding the tile grouping.

**Comment by rcorvino** [comment]
Hi @psuriana, thanks a lot for your answer. 
However, when I try this code, I have the following internal error
```
Internal error at $HALIDE\Halide_auto_scheduler_src\src\IR.cpp:21
Condition failed: a.type() == b.type()
Add of mismatched types

```
this goes away when I remove the call to the auto-scheduler. Any idea? 


p.s. I am using the Halide_autoscheduler on Windows. The initial version was not compiling so I had to change the AutoSchedule.cpp code source as specified below. 
Is it possible that these changes cause the previous internal order? p.s. I cannot currently debug as I have compiled Halide_auto_schedule in release mode only.

1) in struct RegionsRequiredQuery change the  bool operator< to be a strict total order
2) in Partitioner::GroupAnalysis Partitioner::analyze_group, I changed the code as follows:

```
 // Linear dropoff
    float load_slope = (float)arch_params.balance / arch_params.last_level_cache_size;
    for (const auto &f_load : group_load_costs) {
        internal_assert(g.inlined.find(f_load.first) == g.inlined.end())
            << "Intermediates of inlined pure fuction \"" << f_load.first
            << "\" should not have been in the group_load_costs\n";
	if (alloc_regions.find(f_load.first) == alloc_regions.end()) continue; //<-- I added this line
        const auto &alloc_reg = get_element(alloc_regions, f_load.first);
```
3) in $(Halide_source)/tools/halide_image_io.h
replace all occurrences of fopen and sscanf  with fopen_s and sscanf_s respectively

**Comment by psuriana** [comment]
You should pull the newest changes. I just committed the fix this morning. That should fix the mismatch error.

**Comment by rcorvino** [comment]
ok I will try this next week. Is your last change also tested on Windows? Are you planning to provide Windows binary any time in the future?

**Comment by kgnk** [comment]
Although building llvm and Halide is kind of a pain, it isn't that terrible really. Just follow the instructions in the [Halide readme](https://github.com/halide/Halide). Your other option is to download the latest [continuous integration build](https://buildbot.halide-lang.org/). Be careful to check the dates as they are sorted by SHA.

**Comment by rcorvino** [comment]
Hi @kgnk, 
thanks for your suggestion, I have indeed followed this readme, but as I explained I had problems compiling the Halide autoscheduler branch. No problems with the main branch, for which I found the binaries [here](https://github.com/halide/Halide/releases)
