### ISSUE TITLE
Arrays of Buffers aren't implemented for a generator.

### ISSUE THREAD

**Issue by dzo** [halide/Halide#2143]
Arrays can be Funcs but not Buffers. 

Input<Func[]>  frame{"frame",UInt(8),3};

is OK, but not:

Input<Buffer<uint8_t>[]> frame{"frame", 3};

This means we can't do things such as set the stride for an array input.

**Comment by steven-johnson** [comment]
Fixed by https://github.com/halide/Halide/pull/2799
