### ISSUE TITLE
Translating an older generator with a dataype as a GeneratorParam

### ISSUE THREAD

**Issue by ashishUthama** [halide/Halide#2170]
I am trying to update my prototype from the older style generators:

> #include <Halide.h>
> #include <halideBinder/GenGen.hpp>
> 
> using namespace Halide;
> 
> class bwlookupGenerator : public Halide::Generator<bwlookupGenerator> {
> public:
>     GeneratorParam<Halide::Type> datatype{"datatype", UInt(8)};
>     ImageParam im{UInt(8), 2, "im"}, lut{datatype,2,"lut"};
> 
>     Func build(){
>         // Redeclare to ensure command line specification of datatype is picked up
>         ImageParam im{UInt(8), 2, "im"}, lut{datatype,2,"lut"};
> 
>         Func bwlookup("bwlookup");
>         // < A 2x2/3x3 neighborhood based lookup implementation goes here> 
>         return bwlookup;
>     }
> };
> 
> RegisterGenerator<bwlookupGenerator> bwlookupGenerator{"bwlookup_halide"};
> 
> 

Could not easily convert this to a generate/schedule format with Output declaration. 
Is this approach still possible?

**Comment by steven-johnson** [comment]
```
struct Foo : Generator<Foo> {
    // Use "im.type" and "lut.type" on command line to specify type
    Input<Func> im{"im", 2};
    Input<Func> lut{"lut", 2};

    // Use "bwlookup.type" on command line to specify type
    Output<Func> bwlookup{"bwlookup", 2};

    Var x, y;

    void generate() {
      bwlookup(x, y) = some_combination_of(im, lut);
    }

    void schedule() {
      bwlookup.vectorize().parallel().whatever().schedule().directives();
    }
}
```

**Comment by ashishUthama** [comment]
@steven-johnson Thanks!

Can im and lut now be treated just like any other Func? The following:

        Func imPadded("imPadded");
        imPadded = BoundaryConditions::constant_exterior(im,0);
Now gives:

> Halide.h:15007:53:   required from ‘Halide::Func Halide::BoundaryConditions::constant_exterior(const T&, Halide::Expr) [with T = Halide::GeneratorInput<Halide::Func>]’
> bwlookup_halide.cpp:19:62:   required from here
>Halide.h:15000:98: error: ‘const class Halide::GeneratorInput<Halide::Func>’ has no member named ‘dim’
>          object_bounds.push_back({ Expr(func_like.dim(i).min()), Expr(func_like.dim(i).extent()) });
> 

Also, I am unable to access the dimensions of im/lut to specialize schedules. (lut.height() or im.width()).

> bwlookup_halide.cpp:47:27: error: ‘Halide::Internal::GeneratorBase::Input<Halide::Func>’ has no member named ‘height’
>          Expr use2x2 = lut.height()==16;
>

**Comment by ashishUthama** [comment]
Just found https://github.com/halide/Halide/wiki/Generator-Enhancements
Will try out some of the stuff there and post back.

**Comment by ashishUthama** [comment]
From my understanding, any `Input<Func>` will not have dimensions associated with it, hence the use of a separate width input in the above wiki. So this rules creating any dynamic schedules based on image size using `specialize()`. And this is also most likely why `BoundaryConditions::constant_exterior` fails above.

The wiki says older GeneratorParam will continue to be supported, but I get this compilation error with my code (in the the first post):

>  Error:
> The GeneratorParam datatype cannot be read before build() or generate() is called.
> Aborted
>

**Comment by steven-johnson** [comment]
Yes, Input<Func> can be treated like any other Func, but Funcs do not have boundaries -- they are defined across the entire integer space for each variable. 

You can use Input<Buffer<>> if you want to specify an input that is guaranteed to be backed by a fully-realized buffer and has finite dimensions.

**Comment by ashishUthama** [comment]
Steven, sorry - I am still stuck.

Earlier (I can dig up the version if that helps), I was able to do this:
* Use GeneratorParams to obtain a datatype from the command line
* Define ImageParam which uses the datatype from above, but NOT specify a size
* Call methods like BoundaryConditions::constant_exterior on the ImageParam successfully

I was then able to use a script around this to create symbols for datatypes specified at compile time, but sizes only specified at runtime.

Now, with no change in my code (in the first post above), I run into:

> Error:
> The GeneratorParam datatype cannot be read before build() or generate() is called.
> Aborted

i.e something that worked is now broken.

So, I then tried to move my code to the newer generate/schedule framework, but I cant see a way to get the same functionality. With your help, I think I can specify datatype at compile time, but I dont see a way to delay specification of input size till runtime.

**Comment by steven-johnson** [comment]
It would help if you would post the code you are trying now which is failing, but generally, what you are describing should be doable with

```
struct MyGen : Generator<MyGen> {
    Input<Buffer<>> dim_only_input_buffer{ "dim_only_input_buffer", 3 }; 
    ...
};
```

Then, in your build/make/etc file, specify
```
# specify UInt(8) as the type for dim_only_input_buffer
cmd.to.run.mygen.generator dim_only_input_buffer=uint8  ...other-args...
```

test/generator/metadata_tester_generator.cpp should have examples of this (and similar variants).

**Comment by ashishUthama** [comment]
Getting further, thanks for the link to the test!
Here is the full code. I am trying to prototype [bwlookup](https://www.mathworks.com/help/images/ref/bwlookup.html)


```
#include <Halide.h>
#include <halideBinder/GenGen.hpp>

using namespace Halide;

class bwlookupGenerator : public Halide::Generator<bwlookupGenerator> {
public:
    Input<Buffer<uint8_t>> im{"im", 2};
    Input<Buffer<>> lut{"lut", 2};
    Output<Func> bwlookup{"bwlookup", 2};
    Var x{"x"}, y{"y"};

    void generate (){
        Func imPadded("imPadded");
        imPadded = BoundaryConditions::constant_exterior(im,0);

        Func computeLUTIndex2x2("computeLUTIndex2x2");
        computeLUTIndex2x2(x,y)  =
                cast<uint8_t>(imPadded(x,y))
                | cast<uint8_t>(imPadded(x,y+1))  <<1
                | cast<uint8_t>(imPadded(x+1,y))  <<2
                | cast<uint8_t>(imPadded(x+1,y+1))<<3;

        Func computeLUTIndex3x3("computeLUTIndex3x3");
        computeLUTIndex3x3(x,y)  =
                cast<uint16_t>(imPadded(x-1,y-1))
                | cast<uint16_t>(imPadded(x-1,y))  <<1
                | cast<uint16_t>(imPadded(x-1,y+1))<<2
                | cast<uint16_t>(imPadded(x,y-1))  <<3
                | cast<uint16_t>(imPadded(x,y))    <<4
                | cast<uint16_t>(imPadded(x,y+1))  <<5
                | cast<uint16_t>(imPadded(x+1,y-1))<<6
                | cast<uint16_t>(imPadded(x+1,y))  <<7
                | cast<uint16_t>(imPadded(x+1,y+1))<<8;

        Func bwlookup2x2("bwlookup2x2");
        bwlookup2x2(x,y) = lut(0,clamp(computeLUTIndex2x2(x,y),0,15));

        Func bwlookup3x3("bwlookup3x3");
        bwlookup3x3(x,y) = lut(0,clamp(computeLUTIndex3x3(x,y),0,511));

        Func bwlookup("bwlookup");
        // ISSUE 1 - cant do this anymore. Is this possible with the Buffer<>?
        //Expr use2x2 = lut.height()==16;
        //bwlookup(x,y) = select(use2x2, bwlookup2x2(x,y), bwlookup3x3(x,y));
        bwlookup(x,y) = bwlookup3x3(x,y);
    }

    void schedule(){
        /* Same as ISSUE 1
        Expr canVectorize = im.width()>16;
        Expr use2x2 = lut.height()==16;
        // Pull out the 2x2 nhood or 3x3 nhood decision to the top
        bwlookup
                .specialize(use2x2);

        // 2x2 lut, vectorizable
        bwlookup
                .specialize(use2x2)
                .specialize(canVectorize)
                .vectorize(x,natural_vector_size(lut.type()))
                .parallel(y);

        // 3x3 lut, vectorizable
        bwlookup
                .specialize(canVectorize)
                .vectorize(x,natural_vector_size(lut.type()))
                .parallel(y);
        */
        bwlookup
                .vectorize(x,natural_vector_size(lut.type()))
                .parallel(y);
    }

};

RegisterGenerator<bwlookupGenerator> bwlookupGenerator{"bwlookup_halide"};

```

* I am trying to specialize two things, one the decision to use 2x2 vs 3x3 nhood, and another about whether the image has enough elements for vectorization. Both have to happen at runtime.
* With the above commented out code, the compilation works, but generation aborts with:

>  Error:
> In schedule for bwlookup, could not find split dimension: x
> Vars:
> Abort
>

**Comment by ashishUthama** [comment]
Never mind, this works:

`        Expr use2x2 = lut.dim(0).extent()==16;`
