### ISSUE TITLE
apps/local_laplacian appears to be broken for GPU targets

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2181]
More investigation needed here, but at current head, something seems amiss with gpu_tile():
-- HL_TARGET=host make bin/out.png gives expected output
-- HL_TARGET=host-opencl make bin/out.png gives black output (on my Mac)
-- editing local_laplacian_generator.cpp to remove the calls to gpu_tile() makes the host-opencl target once again give useful output
-- selectively removing some of the gpu_tile() calls gives other interesting-but-wrong results

**Comment by abadams** [comment]
Looks like load_and_convert isn't setting host_dirty, so it's processing junk input.

**Comment by steven-johnson** [comment]
...and of course removing gpu_tile() fixes it, since it no longer runs on GPU. D'oh.

**Comment by steven-johnson** [comment]
https://github.com/halide/Halide/pull/2183
