### ISSUE TITLE
Enable Bazel-on-Travis after Bazel 0.5.3 released

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2195]
Bazel 0.5.2 will not install if JDK9 is installed (even if JDK8 is also installed, and the default), and AFAIK there isn't an easy way to prevent this situation on our Travis setup. Bazel 0.5.3 should fix this; we should disable Bazel testing on Travis until then.

**Comment by alexreinking** [comment]
We no longer use Bazel _or_ Travis.
