### ISSUE TITLE
generator for iOS simulator

### ISSUE THREAD

**Issue by awakecoding** [halide/Halide#2207]
I know the iOS simulator isn't useful for production usage, but it simplifies development. I'm trying to get my generator to correctly produce object files for the simulator, but it fails like this:

./wayk-halide-generator -g YCoCgR420ToRgb -e o -o /opt/wayk/dev/WaykNow/build/generated/halide -n YCoCgR420ToRgb_x86-64 target=ios-x86-64-no_runtime
Internal error at /opt/wayk/tmp/Halide/src/LLVM_Output.cpp:38
Warning: module's data layout does not match target machine's
e-m:o-i64:64-f80:128-n8:16:32:64-S128
e-m:e-i64:64-f80:128-n8:16:32:64-S128
Abort trap: 6

The same generator works file for all ARM-based iOS platforms. If I replace "ios" with "osx", it generates, but for the wrong target platform. I looked at LLVM_Output.cpp and LLVM_Runtime_Linker.cpp, and both seem to correctly handle the case for the ios platform + x86-32/64 architectures.

The target triplet looks fine, so there appears to be a broken check somewhere in the code, but I can't find it. There is only one place that may be worth looking into:
https://github.com/halide/Halide/blob/master/src/LLVM_Runtime_Linker.cpp#L232

Looking at the code, the DataLayout for the iOS + x86 case would fallback to the same case used by Linux/Android, which I guess is pretty much wrong. I don't know much about the DataLayout formats, so I don't really know how to try to fix this.

**Comment by abadams** [comment]
Inside LLVM_Runtime_Linker.cpp, in get_data_layout_for_target, try changing
(target.os == Target::OSX) to (target.os == Target::OSX || target.os ==
Target::IOS) in the X86 section.

- Andrew

**Comment by awakecoding** [comment]
I was actually trying the exact same thing when you replied, it now generates without errors:
https://github.com/wayk/Halide/commit/3a3dd0f335ca84eb8060602e5f45948ed06f79d9

I will now try it out and let you know if it works at runtime to be certain :)

**Comment by awakecoding** [comment]
@abadams I confirm that the generated code runs properly in the simulator, thanks! I can make a pull request if you want.

**Comment by zvookin** [comment]
A pull request is welcome. I would have thought this configuration was used
and tested regularly, but perhaps not...

-Z-

**Comment by steven-johnson** [comment]
Can we consider this fixed?

**Comment by awakecoding** [comment]
@steven-johnson yes, my pull request was merged, and it fixed the issue.
