### ISSUE TITLE
fail to build lesson_02 by g++

### ISSUE THREAD

**Issue by samsun639** [halide/Halide#2210]
run 
g++ lesson_02*.cpp -g -I ../include -I ../tools -L ../bin -lHalide -I/usr/include/libpng12 -L/usr/lib/x86_64-linux-gnu -lpng12 -lpthread -ldl -o lesson_02 -std=c++11
or run 
g++ lesson_02*.cpp -g -I ../include -I ../tools -L ../bin -lHalide `libpng-config --cflags --ldflags` -lpthread -ldl -o lesson_02 -std=c++11

get errors:
> 
> /tmp/ccpiJ8lK.o: In function `bool Halide::Tools::Internal::load_jpg<Halide::Buffer<void>, &Halide::Tools::Internal::CheckFail>(std::string const&, Halide::Buffer<void>*)':
> /root/Halide/tutorial/../tools/halide_image_io.h:682: undefined reference to `jpeg_std_error'
> ......
> /tmp/ccpiJ8lK.o: In function `bool Halide::Tools::Internal::save_jpg<Halide::Buffer<void>, &Halide::Tools::Internal::CheckFail>(Halide::Buffer<void>&, std::string const&)':
> /root/Halide/tutorial/../tools/halide_image_io.h:747: undefined reference to `jpeg_std_error'
> ......
> collect2: error: ld returned 1 exit status

There is no error by running 
**make tutorial_lesson_02_input_image**

**Comment by ashishUthama** [comment]
Could you try adding a -ljpeg to the compile line to see if it works? That should link in the JPEG library which defined the jpef_* symbols.

**Comment by abadams** [comment]
-ljpeg was indeed missing. Fixed in master.

**Comment by yukoba** [comment]
Please update http://halide-lang.org/tutorials/tutorial_lesson_02_input_image.html too.
