### ISSUE TITLE
issue while integrating with Opencv 3.2

### ISSUE THREAD

**Issue by ravispatil** [halide/Halide#2220]
Hello,
I am loading caffe model for image classification in opencv.
For performance improvement trying to use halide as backend and target as opencl in mobile device.
But when i trying to compile my opencv test am getting below error.
-----------------------------------
lib/libopencv_dnn.a(op_halide.cpp.o): In function `cv::dnn::HalideBackendWrapper::HalideBackendWrapper(int, cv::Mat const&)':
/home/abuild/rpmbuild/BUILD/opencv-3.2.0/modules/dnn/src/op_halide.cpp:87: undefined reference to `halide_opencl_device_interface'
-------------------------------------
Can you please help us what i am making mistake ?
If I want to rebuild halide with opencl as target, how to do that so that my halide library should contain this symbol.

**Comment by abadams** [comment]
It looks like there's no Halide runtime linked in. So either the Halide op was compiled without opencl support (the target needs to include -opencl), or it was compiled with -no_runtime but no suitable runtime was linked in.

**Comment by ravispatil** [comment]
Thank you Andrew.
But i am still not getting how to do that.
I have exported HL_TARGET

**Comment by dkurt** [comment]
@ravispatil, the issue was solved at OpenCV side.

**Comment by steven-johnson** [comment]
Can we consider this fixed?

**Comment by dkurt** [comment]
@steven-johnson, I think it may be freely closed. Thanks!
