### ISSUE TITLE
Question about Lesson05

### ISSUE THREAD

**Issue by DavieHR** [halide/Halide#2228]
Hi, I'm studying the lessons in tuturial. But I'm confused about the lesson_05_fast part. Is the total count of tile_index is 4×3? I think it should be 6×4. 
Might be a dumb question but I only just got started on the tutorials so I wanna make sure that I got this right :)   
THX

**Comment by kgnk** [comment]
I agree with you. Probably the size (35x250) got changed to better illustrate something and that loop size didn't also get changed. In comparing Halide results to hand written C functions, I've found a few bugs in my C functions because Halide does provable refactoring.

**Comment by abadams** [comment]
The output is size 350 x 250. The tiles are 64 x 64, so there are ceil(250/64) x ceil(350/64) tiles, which is 24, as you say. Will fix.

**Comment by chiz01** [comment]
Should bellow also be changed?
 int y_outer = tile_index / 4;       //6
int x_outer = tile_index % 4;      //6
