### ISSUE TITLE
Compile error: lesson_10_aot_compilation_generate

### ISSUE THREAD

**Issue by samsun639** [halide/Halide#2234]
Followed below step, error at step 3
 On linux, you can compile and run it like so:
step 1. g++ lesson_10*generate.cpp -g -std=c++11 -I ../include -L ../bin -lHalide -lpthread -ldl -o lesson_10_generate
step 2. LD_LIBRARY_PATH=../bin ./lesson_10_generate
step 3. g++ lesson_10*run.cpp lesson_10_halide.a -lpthread -ldl -o lesson_10_run

error as below:
lesson_10_aot_compilation_run.cpp:16:26: fatal error: HalideBuffer.h: No such file or directory
 #include "HalideBuffer.h"
                          ^
compilation terminated.
--------------------------------------------------------------------------------------------------------

Then I tried to locate HalidBuffer.h and include it, compiling still fail with lots of errors:
1)find .. -name "HalideBuffer.h"
../src/runtime/HalideBuffer.h
../distrib/include/HalideBuffer.h
../include/HalideBuffer.h
2)g++ lesson_10*run.cpp lesson_10_halide.a -lpthread -ldl -I../include -o lesson_10_run

     Buffer(const buffer_t &old_buf) {
     ^
../include/HalideBuffer.h:468:5: note:   candidate expects 1 argument, 2 provided
../include/HalideBuffer.h:462:5: note: Halide::Runtime::Buffer<T, D>::Buffer(const halide_buffer_t&) [with T = unsigned char; int D = 4; halide_buffer_t = halide_buffer_t]
     Buffer(const halide_buffer_t &buf) {
     ^
../include/HalideBuffer.h:462:5: note:   candidate expects 1 argument, 2 provided
../include/HalideBuffer.h:455:5: note: Halide::Runtime::Buffer<T, D>::Buffer() [with T = unsigned char; int D = 4]
     Buffer() {
     ^
../include/HalideBuffer.h:455:5: note:   candidate expects 0 arguments, 2 provided
lesson_10_aot_compilation_run.cpp:61:43: error: no match for call to ‘(Halide::Runtime::Buffer<unsigned char>) (int&, int&)’
             uint8_t input_val = input(x, y);
                                           ^
lesson_10_aot_compilation_run.cpp:62:45: error: no match for call to ‘(Halide::Runtime::Buffer<unsigned char>) (int&, int&)’
             uint8_t output_val = output(x, y);

**Comment by abadams** [comment]
The other thing that's missing is -std=c++11. 

I'll fix the comment.

**Comment by bhargav-sudo** [comment]
I am getting this error 

 **fatal error: Halide.h: No such file or directory**
can any one help me out..?

Iam new to this.
