### ISSUE TITLE
[Autoscheduler] Missing intrinsics in RegionCosts cause autoscheduler to fail

### ISSUE THREAD

**Issue by SanderVocke** [halide/Halide#2248]
https://github.com/halide/Halide/blob/bea3f0e2939d30e04c8484bb5bf41ed60de5f382/src/RegionCosts.cpp#L144-L164

The RegionCosts pass fails when encountering an "if_then_else" or "return_second" intrinsic call. Such a call appears when using the "print_when" functionality. Maybe it should be added to the list of +5 cost intrinsics here.

Edit: There are many more unhandled intrinsics. IMO the list in RegionCosts.cpp should either be complete, or alternatively a 0 cost should just be default for unhandled intrinsics. The list:

debug_to_file,
        reinterpret,
        bitwise_and,
        bitwise_not,
        bitwise_xor,
        bitwise_or,
        shift_left,
        shift_right,
        abs,
        absd,
        rewrite_buffer,
        random,
        lerp,
        popcount,
        count_leading_zeros,
        count_trailing_zeros,
        undef,
        return_second,
        if_then_else,
        glsl_texture_load,
        glsl_texture_store,
        glsl_varying,
        image_load,
        image_store,
        make_struct,
        stringify,
        memoize_expr,
        alloca,
        likely,
        likely_if_innermost,
        register_destructor,
        div_round_to_zero,
        mod_round_to_zero,
        call_cached_indirect_function,
        prefetch,
        signed_integer_overflow,
        indeterminate_expression,
        bool_to_mask,
        cast_mask,
        select_mask,
        extract_mask_element,
        require,
        size_of_halide_buffer_t;

**Comment by SanderVocke** [comment]
Just noting that this is still an issue now that the autoscheduler was merged into master. "print_when" cannot be used in autoscheduled apps.

**Comment by psuriana** [comment]
What was the issue you encountered with print_when? It is lowered to if_then_else under the hood, so I would imagine the auto-scheduler should work.

**Comment by SanderVocke** [comment]
Maybe I was not clear: if_then_else and return_second both cause the autoscheduler to crash, since they are not handled in the code snippet I posted in the top post.

To be sure to avoid crashes, the entire list I posted should be handled.

Maybe instead of erroring out, it would be better to generate a warning when an unhandled intrinsic occurs? the list of intrinsics is huge.

**Comment by psuriana** [comment]
The if_then_else with return_second are now handled in #2331. It also uses cost of 1 and prints out user warning for unhandled intrinsics.
