### ISSUE TITLE
BoundaryConditions on Func

### ISSUE THREAD

**Issue by olegarch** [halide/Halide#2274]
```
void process(Mat& _input, Mat& _output, float scale)
{
    Var x("x"), y("y");
    _output.create(_input.size(), CV_32F);

    Buffer<uint8_t> input( _input.data, _input.cols, _input.rows );
    Buffer<float> output( reinterpret_cast<float*>(_output.data), _output.cols, _output.rows );

    Func in;
    in(x,y) = input(x,y);

    Func input_with_border = BoundaryConditions::mirror_interior(in);
...
}
```

Compiler throws an error:

> /home/oleg/Halide/include/Halide.h: In instantiation of ‘Halide::Func Halide::BoundaryConditions::mirror_interior(const T&) [with T = Halide::Func]’:
> /home/oleg/Halide/oleg/test1.cpp:267:72:   required from here
> /home/oleg/Halide/include/Halide.h:15447:98: error: ‘const class Halide::Func’ has no member named ‘dim’
>          object_bounds.push_back({ Expr(func_like.dim(i).min()), Expr(func_like.dim(i).extent()) });
>                                                                                                   ^
> /home/oleg/Halide/include/Halide.h:15447:98: error: ‘const class Halide::Func’ has no member named ‘dim’
> /home/oleg/Halide/include/Halide.h:15447:98: error: no matching function for call to ‘std::vector<std::pair<Halide::Expr, Halide::Expr> >::push_back(<brace-enclosed initializer list>)’
> /home/oleg/Halide/include/Halide.h:15447:98: note: candidates are:
> In file included from /usr/include/c++/4.8/vector:64:0,
>                  from /home/oleg/Halide/oleg/test1.cpp:3:
> /usr/include/c++/4.8/bits/stl_vector.h:901:7: note: void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = std::pair<Halide::Expr, Halide::Expr>; _Alloc = std::allocator<std::pair<Halide::Expr, Halide::Expr> >; std::vector<_Tp, _Alloc>::value_type = std::pair<Halide::Expr, Halide::Expr>]
>        push_back(const value_type& __x)
>        ^
> /usr/include/c++/4.8/bits/stl_vector.h:901:7: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const value_type& {aka const std::pair<Halide::Expr, Halide::Expr>&}’
> /usr/include/c++/4.8/bits/stl_vector.h:919:7: note: void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = std::pair<Halide::Expr, Halide::Expr>; _Alloc = std::allocator<std::pair<Halide::Expr, Halide::Expr> >; std::vector<_Tp, _Alloc>::value_type = std::pair<Halide::Expr, Halide::Expr>]
>        push_back(value_type&& __x)
>        ^
> /usr/include/c++/4.8/bits/stl_vector.h:919:7: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘std::vector<std::pair<Halide::Expr, Halide::Expr> >::value_type&& {aka std::pair<Halide::Expr, Halide::Expr>&&}’
> make[2]: *** [CMakeFiles/test1.dir/test1.cpp.o] Error 1
> make[1]: *** [CMakeFiles/test1.dir/all] Error 2
> make: *** [all] Error 2

It works okay if I impose BoundaryConditions directly on Buffer<> input.

**Comment by dsharletg** [comment]
The problem is that this version of mirror_interior only works on Buffer<> or ImageParam, where the bounds are available. Funcs can be evaluated at any point, and so don't have bounds that can be applied automatically. You need to use one of the versions of mirror_interior that accepts the bounds you want to apply, e.g.: https://github.com/halide/Halide/blob/master/src/BoundaryConditions.h#L241

The error you get in this case is pretty unhelpful though, unfortunately.

**Comment by olegarch** [comment]
Yep. It works with explicit bounds. Thanks.

**Comment by steven-johnson** [comment]
This isn't the first time someone has made this mistake. I wonder if we could find a way to make the compiler error more helpful?

**Comment by abadams** [comment]
Perhaps an overload that takes a Func and no other arguments and has a
helpful static_assert in it
