### ISSUE TITLE
Documentation on enhanced generators missing info for BoundaryConditions.

### ISSUE THREAD

**Issue by mcourteaux** [halide/Halide#2277]
I'm trying to use the new generator syntax. Converting `ImageParam` to `Input<Func>` yields an issue with `BoundaryConditions::repeat_edge()`: 
```
error: no member named 'dim' in 'Halide::GeneratorInput<Halide::Func>'
    object_bounds.push_back({ Expr(func_like.dim(i).min()), Expr(func_like.dim(i).extent()) });
                                   ~~~~~~~~~ ^
```

I also tried to use: `Input<Buffer<..>>`, which successfully compiled the generator, but the generator itself gave this issue:

```
Dimensions is not defined for Input buffer; you may need to specify a GeneratorParam.
```

How to deal with this properly?

**Comment by steven-johnson** [comment]
Declare it as

    Input<Buffer<..>> {"name", number-of-dimensions}

**Comment by mcourteaux** [comment]
👍  Yes, it works! Thank you. 😄 

I just updated the docs. First section here:
[https://github.com/halide/Halide/wiki/Generator-Enhancements](https://github.com/halide/Halide/wiki/Generator-Enhancements)

Please validate my changes. Will close for now. Reopen if necessary.

**Comment by steven-johnson** [comment]
Changes look good. Thanks!
