### ISSUE TITLE
apps/glsl doesn't build with Makefile

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2286]
Building with CMake works, but building with Makefile (on OSX) yields link error:

warning: (x86_64)  could not find object file symbol for symbol _halide_ycc_glsl
warning: (x86_64)  could not find object file symbol for symbol _halide_ycc_glsl_argv
warning: (x86_64)  could not find object file symbol for symbol _halide_ycc_glsl_metadata
warning: (x86_64)  could not find object file symbol for symbol _halide_ycc_glsl_old_buffer_t
warning: (x86_64)  failed to insert symbol '__ZZ20halide_default_traceE3ids' in the debug map.
warning: (x86_64)  failed to insert symbol '__ZZ25halide_profiler_get_stateE1s' in the debug map.
warning: (x86_64)  failed to insert symbol '__ZZ38halide_default_can_use_target_featuresE11initialized' in the debug map.
warning: (x86_64)  failed to insert symbol '__ZZ38halide_default_can_use_target_featuresE12cpu_features' in the debug map.
warning: (x86_64)  failed to insert symbol '__ZZ30halide_opengl_get_proc_addressE5dylib' in the debug map.
warning: (x86_64)  could not find object file symbol for symbol _module_state_halide_ycc_glsl_opengl

**Comment by mcourteaux** [comment]
(Off topic) What's actually the point in having both Makefiles and CMake?

**Comment by steven-johnson** [comment]
Historically: 
-- Makefiles, because we want to show how to use Halide at a "lowest common denominator" level
-- CMake, mainly to provide support for Windows

You could argue that it would make sense to consolidate on just one, in which case CMake would be the obvious choice, but the current core Halide contributors tend to heavily prefer Make at the present time.

**Comment by steven-johnson** [comment]
This appears to be related to using the -g flag on OSX: static variables inside weak runtime functions are getting debug symbols attached wrongly.

**Comment by steven-johnson** [comment]
Also note: the description above is wrong in that these are warnings, not errors; it actually builds and runs fine.

**Comment by steven-johnson** [comment]
"fixed" by inserting comment.

**Comment by khourig** [comment]
Possibly relevant:

Mac executable DWARF information points to stabs information in the object files and is therefore specific to the build machine. While extracting symbols to a dSYM, they go though a process similar to linking. 

https://stackoverflow.com/questions/10044697/where-how-does-apples-gcc-store-dwarf-inside-an-executable
