### ISSUE TITLE
CMake build rules for Generators need improvement

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2293]
The current CMake build rules for using Generators are, well, terrible:

- They aren't quite usable outside of the Halide tree (i.e., the rules aren't copied into the distributions, and even if they were, they aren't quite standalone)
- usage is awkward and clunky; they aren't idiomatic to typical CMake usage. (Mimicking the Bazel build rules for Generator would be a good starting point)
- The rules aren't quite cross-platform; extra libraries and such have to be hacked in depending on platform, LLVM config, etc.

**Comment by steven-johnson** [comment]
(I've already got work underway to improve this; opening an official issue to track it.)

**Comment by mcourteaux** [comment]
I have done quite some good work on this as well. Only problem is that I don't know what the whole point of this is with these cpp stubs. So, these don't work, but everything else works brilliant: cmake only invokes the generator when needed. I can make a PR today.

**Comment by mcourteaux** [comment]
Actually, I won't make a PR, since there is too much work to make it back compliant with what it was.
However, here is my version of the `HalideGenerator.cmake` file:
https://gist.github.com/mcourteaux/66ada94604d1122fb1c3b99f43dca380

**Comment by steven-johnson** [comment]
Thanks for the feedback! I have a work-in-progress that (I think) will be a more complete fix, that will also work for stubs and some other issues; unfortunately, I have some yak shaving to do first (e.g., https://github.com/halide/Halide/pull/2292) to make it work more cleanly. Look for a PR on this topic from me within a few days.

**Comment by mcourteaux** [comment]
Alright, if you have any trouble with CMake dependency resolving, do ask (or examine my gist). I spent two days fiddling around to make it work correctly, so that it only recompiles the generator, and reinvokes the generator when needed.

**Comment by steven-johnson** [comment]
Initial PR for the proposed revision are at https://github.com/halide/Halide/pull/2323 -- I'd welcome your feedback on them.

**Comment by alexreinking** [comment]
This system is getting redone in #4644
