### ISSUE TITLE
VULKAN support

### ISSUE THREAD

**Issue by hlide** [halide/Halide#2296]
Is there any plan for VULKAN support? as far as I know, VULKAN is multi-platform and be used as well for graphics rendering as for computing. It has more granularity, allows to use several devices and so on. It sounds as a very good candidate for more flexible scheduling than OPEN CL/GL.

**Comment by abadams** [comment]
There is, but nobody has started working on it yet. We expect that it will be the right way to get gpgpu on android.

**Comment by zvookin** [comment]
Would love to hear use cases for this. E.g. we'll likely be targeting SPIR-V directly.

**Comment by jzupka** [comment]
+1

**Comment by liquidmetal** [comment]
Would be happy to contribute if someone can help me understand how to get started on this.

**Comment by zvookin** [comment]
There is now a branch https://github.com/halide/Halide/tree/vulkan where this is being worked on. Early stages yet, but patches welcome.

**Comment by tansinpo** [comment]
@zvookin Hi, where can I get the header file "mini_vulkan.h"?

**Comment by zvookin** [comment]
I added this file to the branch. Other things seem wrong and it will need
to be made a clean diff against master. I'll try to make a new branch in
the next few days.

-Z-

**Comment by zvookin** [comment]
Current work is at https://github.com/halide/Halide/tree/vulkan2 (dues to the history rewrite).

**Comment by ib00** [comment]
Any progress on Vulkan backend?

**Comment by alexreinking** [comment]
Initial Vulkan support landed between #6829 #6882 #6924 #6605 -- will not likely be ready for the next release, but hopefully will in v16!

**Comment by alexreinking** [comment]
Assigning @derek-gerstmann just so he can remember to close this issue when Vulkan support is done :slightly_smiling_face:

**Comment by derek-gerstmann** [comment]
Done! 🙂
