### ISSUE TITLE
Halide with llvm-4.0 ?

### ISSUE THREAD

**Issue by jiapei100** [halide/Halide#2314]
Hi, 

I'm trying to build **Halide git (August 30, 2017)** with **llvm-4.0**, under **Ubuntu 16.04.3**, but got the following error messages:

> .../Halide/src/LLVM_Output.cpp:83:36: error: ‘WriteBitcodeToFile’ was not declared in this scope
>      WriteBitcodeToFile(&module, out);
> 
> .../Halide/src/LLVM_Runtime_Linker.cpp:17:9: error: ‘parseBitcodeFile’ is not a member of ‘llvm’
>          llvm::parseBitcodeFile(bitcode_buffer, *context));
>          ^
> src/CMakeFiles/Halide.dir/build.make:5339: recipe for target 'src/CMakeFiles/Halide.dir/LLVM_Runtime_Linker.cpp.o' failed

I looks Halide is still NOT compatible with llvm-4.0 yet? Can anybody give me a hand?

Cheers
Pei

**Comment by steven-johnson** [comment]
I'm building against LLVM4.0 even as we speak, so, yes, it still works and is supported.

How are you configuring LLVM and Halide?

**Comment by steven-johnson** [comment]
Ping. Can you give any more details?
