### ISSUE TITLE
Difference between generate() and build()

### ISSUE THREAD

**Issue by zhenkaiwang** [halide/Halide#2317]
When building a generator, I found that build() is used in tutorials examples, while generate() and schedule() is used in apps examples. What is the difference between them?

**Comment by zvookin** [comment]
Separation of constructing the IR and scheduling it into two methods was
intended to be the new way to do things. Tne methods generate() and
schedule() were going to replace build. The idea is to provide flexibility
in scheduling, such as allowing one to chose a manual schedule or to use
the auto scheduler. The build() method is the original design.

Not everyone likes the new model so it is somewhat up in the air.
Separating generate() and schedule() requires intentionally declaring the
Vars and Funcs which can participate in scheduling by declaring them at
class scope. Whether this additional structure is productive or a
hinderance is one of the main points of debate in the design. There is
ongoing work to try to come up with a design that everyone feels is
superior.

**Comment by zhenkaiwang** [comment]
Thanks. I also found that using generate() is much slower than using build() in my algorithm. Not sure why.

**Comment by zvookin** [comment]
Slower to compile or slower runtime for the filter? There should be no
difference between the two mechanisms if the scheduling is the same. My
guess is the IR or schedule is somehow different between the two cases.

**Comment by steven-johnson** [comment]
> using generate() is much slower than using build()

Can you please give an example of this? That shouldn't be possible.

**Comment by zhenkaiwang** [comment]
I have modify the dilate3x3_generator.cpp in hexagon_benchmark as follows:
`class Dilate3x3 : public Generator<Dilate3x3> {
public:
    // Takes an 8 bit image; one channel.
    // Input<Buffer<uint8_t>> input{"input", 2};
    ImageParam input{UInt(8), 2, "input"};
    // Outputs an 8 bit image; one channel.
    // Output<Buffer<uint8_t>> output{"output", 2};

    // void generate() {
    //     bounded_input(x, y) = BoundaryConditions::repeat_edge(input)(x, y);
    //     max_y(x, y) = max(bounded_input(x, y-1), bounded_input(x, y), bounded_input(x, y+1));

    //     output(x, y) = max(max_y(x-1, y), max_y(x, y), max_y(x+1, y));
    // }

    // void schedule() {
    //     Var xi{"xi"}, yi{"yi"};

    //     input.dim(0).set_min(0);
    //     input.dim(1).set_min(0);

    //     output.dim(0).set_min(0);
    //     output.dim(1).set_min(0);

    //     if (get_target().features_any_of({Target::HVX_64, Target::HVX_128})) {
    //         const int vector_size = get_target().has_feature(Target::HVX_128) ? 128 : 64;
    //         Expr input_stride = input.dim(1).stride();
    //         input.dim(1).set_stride((input_stride/vector_size) * vector_size);

    //         Expr output_stride = output.dim(1).stride();
    //         output.dim(1).set_stride((output_stride/vector_size) * vector_size);
    //         bounded_input
    //             .compute_at(Func(output), y)
    //             .align_storage(x, 128)
    //             .vectorize(x, vector_size, TailStrategy::RoundUp);
    //         output
    //             .hexagon()
    //             .tile(x, y, xi, yi, vector_size, 4)
    //             .vectorize(xi)
    //             .unroll(yi);
    //     } else {
    //         const int vector_size = natural_vector_size<uint8_t>();
    //         output
    //             .vectorize(x, vector_size)
    //             .parallel(y, 16);
    //     }
    // }
    Func build(){
        Func output("output");
        bounded_input(x, y) = BoundaryConditions::repeat_edge(input)(x, y);
        max_y(x, y) = max(bounded_input(x, y-1), bounded_input(x, y), bounded_input(x, y+1));
        output(x, y) = max(max_y(x-1, y), max_y(x, y), max_y(x+1, y));
        Var xi{"xi"}, yi{"yi"};

        // input.dim(0).set_min(0);
        // input.dim(1).set_min(0);

        // output.dim(0).set_min(0);
        // output.dim(1).set_min(0);

        if (get_target().features_any_of({Target::HVX_64, Target::HVX_128})) {
            const int vector_size = get_target().has_feature(Target::HVX_128) ? 128 : 64;
            // Expr input_stride = input.dim(1).stride();
            // input.dim(1).set_stride((input_stride/vector_size) * vector_size);

            // Expr output_stride = output.dim(1).stride();
            // output.dim(1).set_stride((output_stride/vector_size) * vector_size);
            bounded_input
                .compute_at(Func(output), y)
                .align_storage(x, 128)
                .vectorize(x, vector_size, TailStrategy::RoundUp);
            output
                .hexagon()
                .tile(x, y, xi, yi, vector_size, 4)
                .vectorize(xi)
                .unroll(yi);
        } else {
            const int vector_size = natural_vector_size<uint8_t>();
            output
                .vectorize(x, vector_size)
                .parallel(y, 16);
        }
        return output;

    }
private:
    Var x{"x"}, y{"y"};
    Func max_y{"max_y"};
    Func bounded_input{"bounded_input"};
};`

Then I make run-host. The original runtime is "Done, time (dilate3x3): 0.0020259 s (cpu)". After using build() it gives "Done, time (dilate3x3): 0.000252 s (cpu)".
That is 10 times faster....

**Comment by zhenkaiwang** [comment]
And on Android platform, 
the original gives "Done, time (dilate3x3): 0.0036808 s (cpu)"
the modified gives "Done, time (dilate3x3): 0.0009015 s (cpu)"

**Comment by ronlieb** [comment]
Please try adding the set_min and set_stride back to the version that uses “build()” and then see if it gets 10 times slower?

 

 

---

Qualcomm Innovation Center, Inc. is a member of Code Aurora Forum, hosted by The Linux Foundation

**Comment by zhenkaiwang** [comment]
Hi ron,
Yes. I added  input.dim(0).set_min(0);  input.dim(1).set_min(0); back and it gets 10 times slower.
Zhenkai

**Comment by steven-johnson** [comment]
OK, so that explains the discrepancy... but brings up a new issue: 

adding a constraint of min=0 doesn't seem like it should make the resulting code *slower*.

**Comment by zhenkaiwang** [comment]
Yes..That's wierd.. The result doesn't seems different with or without set_min=0. Also, the problem only occurs on cpu schedule. The follows is the results running with or without set_min=0 on benchmark examples.
 
with set_min=0
> Running dilate3x3...
Done, time (dilate3x3): 0.0040239 s (64 byte mode)
Running median3x3...
Done, time (median3x3): 0.0031801 s (64 byte mode)
Running gaussian5x5...
Done, time (gaussian5x5): 0.0029901 s (64 byte mode)
Running sobel...
Done, time (sobel): 0.0032136 s (64 byte mode)
Running conv3x3a32...
Done, time (conv3x3a32): 0.003362 s (64 byte mode)
Running dilate3x3...
Done, time (dilate3x3): 0.0029318 s (128 byte mode)
Running median3x3...
Done, time (median3x3): 0.0032331 s (128 byte mode)
Running gaussian5x5...
Done, time (gaussian5x5): 0.0033292 s (128 byte mode)
Running sobel...
Done, time (sobel): 0.003259 s (128 byte mode)
Running conv3x3a32...
Done, time (conv3x3a32): 0.0033455 s (128 byte mode)
Running dilate3x3...
Done, time (dilate3x3): 0.0036808 s (cpu)
Running median3x3...
Done, time (median3x3): 0.0038447 s (cpu)
Running gaussian5x5...
Done, time (gaussian5x5): 0.0139257 s (cpu)
Running sobel...
Done, time (sobel): 0.003707 s (cpu)
Running conv3x3a32...
Done, time (conv3x3a32): 0.0068752 s (cpu)
Success!

without set_min=0:
> Running dilate3x3...
Done, time (dilate3x3): 0.0045313 s (64 byte mode)
Running median3x3...
Done, time (median3x3): 0.0048984 s (64 byte mode)
Running gaussian5x5...
Done, time (gaussian5x5): 0.0034933 s (64 byte mode)
Running sobel...
Done, time (sobel): 0.0032449 s (64 byte mode)
Running conv3x3a32...
Done, time (conv3x3a32): 0.0039863 s (64 byte mode)
Running dilate3x3...
Done, time (dilate3x3): 0.0034737 s (128 byte mode)
Running median3x3...
Done, time (median3x3): 0.0038304 s (128 byte mode)
Running gaussian5x5...
Done, time (gaussian5x5): 0.0032656 s (128 byte mode)
Running sobel...
Done, time (sobel): 0.003489 s (128 byte mode)
Running conv3x3a32...
Done, time (conv3x3a32): 0.0038493 s (128 byte mode)
Running dilate3x3...
Done, time (dilate3x3): 0.0009 s (cpu)
Running median3x3...
Done, time (median3x3): 0.0013138 s (cpu)
Running gaussian5x5...
Done, time (gaussian5x5): 0.0027812 s (cpu)
Running sobel...
Done, time (sobel): 0.0013196 s (cpu)
Running conv3x3a32...
Done, time (conv3x3a32): 0.0023032 s (cpu)
Success!

**Comment by pranavb-ca** [comment]
In fact, we are giving a constant value to what should appear as a variable otherwise. I would have expected it (addition of set_min) to have improved codegen if at all.

 

Thanks,

Pranav

**Comment by zhenkaiwang** [comment]
It is still confusing me that why adding set_min will make the resulting code slower. And why this only happens on cpu schedule... Is it safe to delete all set_min(0）？

**Comment by pranavb-ca** [comment]
It should certainly be safe to delete all set_min(0) but we certainly need to look into why adding set_min(0) is creating slower code.

**Comment by steven-johnson** [comment]
I'm going to close this; please reopen if it still needs attention.
