### ISSUE TITLE
Harris auto schedule performance regression: 2x drop on Haswell

### ISSUE THREAD

**Issue by bondhugula** [halide/Halide#2325]
Problem size: 4256 x 2832

On a 16-core Xeon Haswell, auto_schedule_harris now runs in about 22 ms (Sep 1  
commit dad036fab907b441992304976c12901c52913312)
It used to run in 12 ms at commit a6df6f1d5ec116855fbf595450065749342f0d05 (Feb '17, auto_scheduler branch).   

The corresponding manual schedule performs at 32ms (both commits). 

The following Halide schedule will roughly be three times faster than the current Halide manual schedule and two times than the auto schedule (on the above arch and similar ones). 

            shifted.reorder(y,x).tile(x, y, xi, yi, 256, 23)
                    .vectorize(xi, 8).parallel(y);
            Ix.store_at(shifted, x).compute_at(shifted, yi).vectorize(x, 8);
            Iy.store_at(shifted, x).compute_at(shifted, yi).vectorize(x, 8);
            det.store_at(shifted, x).compute_at(shifted, yi).vectorize(x, 8);
            trace.store_at(shifted, x).compute_at(shifted, yi).vectorize(x, 8);
            Sxx.store_at(shifted, x).compute_at(shifted, yi).vectorize(x, 8);
            Syy.store_at(shifted, x).compute_at(shifted, yi).vectorize(x, 8);
            Ixy.store_at(shifted, x).compute_at(shifted, yi).vectorize(x, 8);        
            Ixx.store_at(shifted, x).compute_at(shifted, yi).vectorize(x, 8);        
            Iyy.store_at(shifted, x).compute_at(shifted, yi).vectorize(x, 8);
            gray.store_at(shifted, x).compute_at(shifted, yi).vectorize(x, 8);

Other information: 
LLVM 3.9
HL_NUM_THREADS=16 taskset -c 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 make auto_schedule_harris
Intel Xeon E5-2630 v3 @ 2.40GHz (2-socket) - 2 x 8 cores

**Comment by psuriana** [comment]
Fixed in #2347
