### ISSUE TITLE
`infer_input_bounds` with `BoundaryConditions`?

### ISSUE THREAD

**Issue by ronen** [halide/Halide#2330]
I'm writing image processing filters, to be usable in situations such as doing tiled processing of images too large to load into memory all at once.  So I'd like to use `infer_input_bounds` to determine the input region that will be examined for a given output tile.    And within the filters of course I want to use `BoundaryConditions` to handle the situation where the filter is looking for data that's beyond the edge of the inputs.  But I'm not getting the behavior I want...

Supposing I'm processing the output in 1024x1024 tiles, for the [3,5]th tile I'd have:

```c++
Halide::ImageParam input(Halide::UInt(8), 3, "input");
Halide::Buffer<uint8_t> output(1024, 1024);
output.set_min(3072, 5120);
```

As an example, here's a trivial filter which just shifts the image over a few pixels. Without `BoundaryConditions` this does what I'd want:

```c++
Halide::Func shift("shift");
shift(x,y,c) = input(x+5, y-10, c);
shift.infer_input_bounds(output);
printf("%d,%d %dx%d\n", input.get().left(), input.get().top(), input.get().width(), input.get().height())
// prints => 3077,5110 1024x1024
```

But to guard against my not actually having input data available throughout that region, I'd use BoundaryConditions.  But then the inferred input bounds aren't what I was expecting/hoping for:

```c++
bounded = Halide::BoundaryConditions::repeat_edge(input);
shift(x,y,c) = bounded(x+5, y-10, c);
shift.infer_input_bounds(100,200);
printf("%d %d %d %d\n", input.get().left(), input.get().top(), input.get().width(), input.get().height())
// prints => 0,0 1x1
```

In some sense that's technically correct, a single pixel is sufficient and the value will be replicated so the filter won't crash.  

But that's not useful to me, since my goal is to find out which window of the input domain the filter will attempt to read from so that I can provide that data if possible.  I.e. I believe I want the `BoundaryConditions` function to be a no-op regarding the input bounds inference.

Is that the intended behavior?  Is there some way to achieve what I want?   Or some other way of thinking about this? 

Thanks!

PS. BTW to add an extra wrinkle, in my real application I'm using AOT compilation, so `infer_input_bounds` isn't actually available to me AFAIK; instead I'm emulating it myself using the same loop as in the source at https://github.com/halide/Halide/blob/master/src/Pipeline.cpp#L931

PPS. Complete example program at [bounded.cpp](https://github.com/halide/Halide/files/1282566/bounded.cpp.txt)

**Comment by abadams** [comment]
I can't think of a way to do this without compiling two versions of the pipeline - one with and without the boundary condition, and doing the bounds query on the one without.

We should move to a model where the bounds query is done by a separate function - then the unused code would at least be dead-stripped.

**Comment by zvookin** [comment]
Either I'm missing something here or this is not a good idea. In order for a boundary condition to be correct in a tiled computation, the boundary has to be at the boundary of the image, not the boundary of the tile being processed. It is almost always a bug to use anything from BoundaryConditions with the bounds of a tile. As in doing so produces imaging artifacts. If the boundary condition is specified on the boundary of the entire image area, bounds inference should do the right thing.

**Comment by ronen** [comment]
@abadams 

> I can't think of a way to do this without compiling two versions of the pipeline...

Bummer.

> We should move to a model where the bounds query is done by a separate function - then the unused code would at least be dead-stripped.

Doesn't sound like a small change...

@zvookin 

> Either I'm missing something here or this is not a good idea. In order for a boundary condition to be correct in a tiled computation, the boundary has to be at the boundary of the image, not the boundary of the tile being processed

Unless I'm not understanding something, that's exactly what I'm trying to accomplish:  For a each output tile, I want to find out what region of input would be examined so that I can provide an input buffer with sufficient minimum and size to avoid triggering the BoundaryConditions.    At the edges of the input I wouldn't be able to provide such a buffer, so the BoundaryConditions would be triggered.
I.e., in pseudocode:

    input_rectangle = pipeline.infer_input_bounds(output_rectangle)
    input_rectangle = input_rectangle.intersect(entire_image_area) 
    buffer = load_image_rectangle(image_file, input_rectangle)  // creates buffer with min & size
    pipeline.input.set(buffer)

Does that still seem wrong?

Thanks both

**Comment by abadams** [comment]
I see, so you're inside code that has an existing tiling and loading-on-demand system you want to integrate with.

Another option might be a boolean param that turns on and off the boundary condition. You'd do the bounds query with it off, and then turn it back on for the actual computation if the boundary condition is necessary. Some Func::specialize might be required to get it to do the right thing.

**Comment by abadams** [comment]
Wait, I'm an idiot, and Zalman is right. Pass the bounds of the true input in as int params, and use those in your boundary condition - not the bounds of the input ImageParam

**Comment by abadams** [comment]
(by true input I mean the entire image area)

**Comment by ronen** [comment]
> I see, so you're inside code that has an existing tiling and loading-on-demand system you want to integrate with.

Yep

> Wait, I'm an idiot, and Zalman is right.

Actually I think I'm the idiot here...

> Pass the bounds of the true input in as int params, and use those in your boundary condition - not the bounds of the input ImageParam

...I didn't know that BoundaryConditions took a bounds parameter.  Passing in the entire image area works as expected.  I should have RTFM'd.

Though passing in the image area is awkward: it makes the filter code more complex, and in my application the entire image bounds might not easily be known at the time I'm doing the inference -- but those are my problems not yours.  (In fact your suggestion of compiling twice might actually be cleanest for me.)

That said, having RTFM'd a bit more, what I originally tried almost seems like in principle it ought to work.  As per the doc for `BoundaryConditions`: _You may pass undefined Exprs for dimensions that you do not wish to bound._  And as per the doc for `infer_input_bounds`, it will _determine the bounds required of all unbound ImageParams referenced._   Putting those together, it'd seem that if the `ImageParam` is unbound its dimensions would be undefined, and so the boundary condition ought to be a no-op.

(Though... as I should have realized since I copied that code myself... in fact the implementation of `infer_input_bounds` works by creating buffers with dimension 0 for all the unbound inputs.  So naturally the boundary condition kicks in and clamps everything to zero size and that's what gets reported.)

Anyway I understand better what's going on, and I'll ponder what to do in my application.

Thanks for the help
