### ISSUE TITLE
LLVM 6.x builds don't generate pavgb/pavgw on x86

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2342]
Recent builds of LLVM removed these intrinsics; in theory LLVM IR is supposed tol natively support them, but in practice they aren't being generated. We need to figure out how to properly generate them in these versions of LLVM.

**Comment by abadams** [comment]
The usual trick is to check llvm's unit tests for the IR that generates these intrinsics

We can then provide our own implementation of the intrinsics in x86_?.ll using precisely that IR

**Comment by steven-johnson** [comment]
https://github.com/halide/Halide/pull/2339
