### ISSUE TITLE
Choose a uniform minimum-CMake version

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2343]
As of right now:
- Our main CMakeLists.txt has `cmake_minimum_required(VERSION 3.1.3)`
- python_bindings has` cmake_minimum_required(VERSION 3.0)`
- Trunk LLVM has `cmake_minimum_required(VERSION 3.4.3)`
- Our .travis.yml has a comment saying `grab a version of CMake >= 3.4` and actually installs `3.5.2`

Would be nice to settle on something uniform and sane. Since LLVM has settled on 3.4.3 with no obvious issues, I'd like to propose making that our minimum everywhere.

**Comment by alexreinking** [comment]
CMake 3.14 is now the minimum.
