### ISSUE TITLE
Consider dropping Halide support for LLVM < 4.0

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2356]
Halide promises to support llvm-trunk, plus at least the two previous releases. With the final release of LLVM 5.0, this means we could consider dropping support for all 3.x versions, supporting 4.0 + 5.0 + trunk.

**Comment by ckun5** [comment]
So LLVM 3.9 will be OK?

**Comment by steven-johnson** [comment]
Halide's goal of record is to support (at least) trunk + two previous versions, so at some point 3.9 could be dropped, but for now, I'm inclined to keep it. Are you using Halide for LLVM3.9 and cannot migrate to 4.0?
