### ISSUE TITLE
auto_schedule is worse for low resolutions

### ISSUE THREAD

**Issue by olegarch** [halide/Halide#2369]
For low resolution 320x240 auto_schedule performs badly compare to simple manual schedule.
Is it expected? Am I doing something wrong?

Platform: Intel CPU x64 

**Source code:**

`#include <vector>
#include <iostream>
using namespace std;

#include "Halide.h"
#include "halide_benchmark.h"

using namespace Halide;
using namespace Halide::Tools;
using namespace Halide::ConciseCasts;

double run_test(bool auto_schedule)
{
    int W = 320;
    int H = 240;

    Var x("x"), y("y");    
    Func producer1("producer1"), producer2("producer2"), consumer("consumer");
    producer1(x, y) = x*y;
    producer2(x, y) = x+y;

    RDom r(0, 3, 0, 3);
    
    consumer(x, y) =  sum(producer1(x+r.x, y+r.y),"sum1")/4.0f +
                      sum(producer2(x+r.x, y+r.y),"sum2")/4.0f;

    consumer.estimate(x, 0, W).estimate(y, 0, H);

    Pipeline p(consumer);
    Target target = get_jit_target_from_environment();         
    //target.set_feature(Target::Profile);   

    if(!auto_schedule)
    {
        Var x_outer, y_outer, x_inner, y_inner, tile_index;
        consumer.tile(x, y, x_outer, y_outer, x_inner, y_inner, 8, 8);
        consumer.fuse(x_outer, y_outer, tile_index).parallel(tile_index);

        producer1.store_at(consumer,tile_index).compute_at(consumer,y_inner);
        producer2.store_at(consumer,tile_index).compute_at(consumer,y_inner);
    }
    else
    {
        p.auto_schedule(target);
    }

    consumer.print_loop_nest();

    // Run the schedule
    Buffer<float> out(W, H);
    double t = benchmark(3, 10, [&]() {
        p.realize(out);
    });

    return t*1000;    
}

int main(int argc, char **argv) {
    std::cout << "======= Manual ===============" << std::endl;
    double manual_time = run_test(false);
    std::cout << "========Auto =================" << std::endl;
    double auto_time = run_test(true);

    std::cout << "======================" << std::endl;
    std::cout << "Manual time: " << manual_time << "ms" << std::endl;
    std::cout << "Auto time: " << auto_time << "ms" << std::endl;
    std::cout << "======================" << std::endl;

    if (!get_jit_target_from_environment().has_gpu_feature() &&
        (2 * auto_time > manual_time)) {
        printf("Auto-scheduler is much much slower than it should be.\n");
        return -1;
    }

    printf("Success!\n");
    return 0;
}`

**Output:**

> ======= Manual ===============
> produce consumer:
>   parallel x.x_outer.tile_index:
>     store producer1:
>       store producer2:
>         for y.y_inner in [0, 7]:
>           produce producer1:
>             for y:
>               for x:
>                 producer1(...) = ...
>           consume producer1:
>             produce producer2:
>               for y:
>                 for x:
>                   producer2(...) = ...
>             consume producer2:
>               for x.x_inner in [0, 7]:
>                 produce sum2:
>                   for y:
>                     for x:
>                       sum2(...) = ...
>                   for y:
>                     for x:
>                       for r:
>                         for r:
>                           sum2(...) = ...
>                 consume sum2:
>                   produce sum1:
>                     for y:
>                       for x:
>                         sum1(...) = ...
>                     for y:
>                       for x:
>                         for r:
>                           for r:
>                             sum1(...) = ...
>                   consume sum1:
>                     consumer(...) = ...
> ========Auto =================
> Warning at /home/oleg/Halide/oleg/test2.cpp:44:
> Outer dim vectorization of var "x" in function "sum1$1.update(0)"
> Warning at /home/oleg/Halide/oleg/test2.cpp:44:
> Outer dim vectorization of var "x" in function "sum2$1.update(0)"
> produce sum1:
>   parallel y:
>     for x.x_vo:
>       vectorized x.x_vi in [0, 3]:
>         sum1(...) = ...
>   parallel y:
>     for x.x_vo:
>       vectorized x.x_vi in [0, 3]:
>         for r:
>           for r:
>             sum1(...) = ...
> consume sum1:
>   produce sum2:
>     parallel y:
>       for x.x_vo:
>         vectorized x.x_vi in [0, 3]:
>           sum2(...) = ...
>     parallel y:
>       for x.x_vo:
>         vectorized x.x_vi in [0, 3]:
>           for r:
>             for r:
>               sum2(...) = ...
>   consume sum2:
>     produce consumer:
>       parallel y:
>         for x.x_vo:
>           vectorized x.x_vi in [0, 7]:
>             consumer(...) = ...
> ======================
> Manual time: 1.0529ms
> Auto time: 2.3381ms
> ======================
> Auto-scheduler is much much slower than it should be.

**Comment by psuriana** [comment]
Sorry for late response. You're not doing anything wrong. In general, there is really no guarantee that auto-scheduler will perform better than the manual schedule, especially if the manual schedule is optimized for certain case. Also note that scheduling directives generated by auto-scheduler don't encompass the whole Halide's scheduling directives (e.g. auto-scheduler will never generate fuse()).

For low resolution in particular, there is often the case the memory and the arithmetic costs (redundant compute vs locality costs) don't really differ that much, which play a huge roll in deciding if it should tile or compute_root. You can play around with different MachineParams (especially with the balance factor which tells the auto-scheduler how much more expensive is the memory vs arithmetic costs). For your case, if you use high balance factor (e.g. 400), you'll get a schedule that prefer less compute_root. 

```
======================
Manual time
======================
produce consumer:
  parallel x.x_outer.tile_index:
    store producer1:
      store producer2:
        for y.y_inner in [0, 7]:
          produce producer1:
            for y:
              for x:
                producer1(...) = ...
          consume producer1:
            produce producer2:
              for y:
                for x:
                  producer2(...) = ...
            consume producer2:
              for x.x_inner in [0, 7]:
                produce sum2:
                  for y:
                    for x:
                      sum2(...) = ...
                  for y:
                    for x:
                      for r:
                        for r:
                          sum2(...) = ...
                consume sum2:
                  produce sum1:
                    for y:
                      for x:
                        sum1(...) = ...
                    for y:
                      for x:
                        for r:
                          for r:
                            sum1(...) = ...
                  consume sum1:
                    consumer(...) = ...

======================
Auto-Scheduler
======================
produce consumer:
  parallel y:
    for x.x_o:
      produce sum1:
        for y:
          for x.x_vo:
            vectorized x.x_vi in [0, 7]:
              sum1(...) = ...
        for y:
          for x.x_vo:
            vectorized x.x_vi in [0, 7]:
              for r:
                for r:
                  sum1(...) = ...
      consume sum1:
        produce sum2:
          for y:
            for x.x_vo:
              vectorized x.x_vi in [0, 7]:
                sum2(...) = ...
          for y:
            for x.x_vo:
              vectorized x.x_vi in [0, 7]:
                for r:
                  for r:
                    sum2(...) = ...
        consume sum2:
          for x.x_i.x_i_vo:
            vectorized x.x_i.x_i_vi in [0, 7]:
              consumer(...) = ...
======================
Manual time: 2.36459ms
Auto time: 0.835457ms
======================
```
