### ISSUE TITLE
autoscheduler and the new generators interface

### ISSUE THREAD

**Issue by palindromoroz** [halide/Halide#2380]
All the autoschedule examples use the old style generators with Param and ImageParam. Not clear if the new generator style with Input and GeneratorParams supports passing estimates on values? Could not find how.

**Comment by steven-johnson** [comment]
There should be an estimate() method exposed on Input<>. If not, that's a bug. (We should definitely have auto_schedule examples on new-style Generators, since we are gradually migrating everything in that direction; @psuriana and I will get together to ensure that happens.

**Comment by palindromoroz** [comment]
There is indeed estimate method on Input<> however not trivial to translate an example with ImageParam and Param bounds to an example with new generator interface. Also not clear to me what happens with GeneratorParams. Will the autoscheduler pick those values as fixed automatically?

**Comment by psuriana** [comment]
The new generator has been updated to support this.
