### ISSUE TITLE
Extracting DAG information about the pipe

### ISSUE THREAD

**Issue by SanderVocke** [halide/Halide#2395]
Some of us have been using some handmade tools to visualize the Halide programs we are writing. In particular, a tool to print the DAG of algorithm functions to a dot file with some annotations.

This tool relied on some internal symbols of the Halide compiler ( which was admittedly bad practice ). Basically it performed a partial lowering until the DAG could be extracted.

Since recently, we can no longer use this tool because the default visibility of symbols in the shared library has been set to invisible ( #2295 ), prohibiting this tool from using lowering functions.

We are wondering what is the best thing we could do to have this functionality in the future. I see a few paths:
- Push the dot printing tool to be part of the Halide project itself. I could use internal functionality and will not be broken by future updates.
- Request or propose some kind of interface for DAG information about the pipe to be passed out of Halide during lowering. This could be by using a special compile command similar to "print_loop_nest", or maybe a special Target.

For either path, we would need to propose a pull request to Halide.

The DAG information is quite useful to understand the code you are writing, to visualize it for explaining to others, and also for optionally visualizing aspects such as memory usage, data types, complexity, etc. This kind of information is not always easy to see by using "print_loop_nest".

What do you think?

**Comment by abadams** [comment]
The reason we marked it all as internal was so that we hit the same pain points on linux as people would on Windows when they try to do this sort of thing.

Feel free to open a PR that just marks everything you need with EXPORT.

**Comment by steven-johnson** [comment]
I think that sounds like a wonderful tool that would be useful to all Halide users. If it doesn't make sense to contribute it to Halide directly, I hope you'd consider making it available elsewhere.

**Comment by SanderVocke** [comment]
It is not as sophisticated as it may have sounded - what we have now is a basic DOT graph printer containing the function's names, with options to show their types and/or their definitions. But it has already proven to be a useful programming aide.

It would become really nice if we also back-annotate it with profiling data, bounds inference results, etc.

I think the best way forward, if you also see value in this, is to push it into Halide. The alternative is exposing internal functions like `find_direct_calls` in the shared lib, which were not meant for external usage and really can't be expected to stay stable over a long period of time.

I will refactor the implementation into the Halide codebase and make an initial pull request. Look forward to hearing your suggestions!

**Comment by dsharletg** [comment]
I think we stopped selectively exporting the Halide API and now export everything.
