### ISSUE TITLE
Line numbers on errors

### ISSUE THREAD

**Issue by SanderVocke** [halide/Halide#2396]
I am guessing that you have discussed this topic before. I am curious to hear your thoughts about it.

In my experience, the majority of user errors are thrown before lowering starts. For example, when trying to combine Exprs with incompatible types. In these cases there is typically a clear location the error originates from (the line on which the function or overloaded operator was called).
In complex applications, it can be very tricky for the user to figure out where the error comes from, especially when the objects involved have no names (Exprs) or haven't been named explicitly by the user (Funcs, Buffers). 
I usually have to fall back to starting a debugger and inspecting the call stack to find where the error is actually coming from.

Getting access to the original line number and file, for printing it in error messages, would be tricky. I don't think C++ has the reflection/introspection features to make that happen. There is the non-portable backtrace() which would allow programmatic call stack inspection, but even that would not give file/line information.

Do you know of a method that could make this happen? Maybe some advanced preprocessor tinkering? I understand this may not be very elegant, but everyone I have talked to agrees that this problem of locating the source location of errors is probably the biggest usability weakness of Halide.

**Comment by SanderVocke** [comment]
I haven't been able to find any way to make this happen, except using __LINE__ / __FILE__ in combination with macros. But that would only work for functions, not for overloaded operators.

**Comment by abadams** [comment]
Are you compiling with debug symbols on? On linux and OS X we parse the
binary's own DWARF debug sections to generate line numbers for those sorts
of errors.

**Comment by SanderVocke** [comment]
That sounds great!

Could you elaborate a bit more on how to compile with these debug symbols? Until now, whenever I wanted to have debug symbols in the Halide compiler, I manually added -g to the CXX_FLAGS in the Makefile.

I am also interested in how this works. Do you somehow parse every binary that is linked to the Halide library to find all calls from it to Halide functions?

**Comment by abadams** [comment]
You shouldn't need to compile libHalide with debug symbols on - just the binary that links to it (i.e. the Generator). Try running "make correctness_introspection" and see if it reports success.

**Comment by abadams** [comment]
Regarding how it works, the implementation is in Introspection.cpp. I just read the dwarf spec and implemented a parser for it. 

To determine a line number we walk up the call stack until we leave the Halide:: namespace, and then take the return address, look it up in the debug metadata, and use that to find a line number and a file.

To name a stack variable we walk up the call stack trying to figure out which stack frame it's in and where, and then refer to the debug metadata to figure out what the variable's name is.

Naming globals works similarly, but is a little easier. We can't really name heap variables (they don't have names - the pointers to them do). Naming members of heap objects works though. Before the members are constructed (using CRTP) we make a stack pointer variable with the same type as the heap object, look up its type in the metadata, remove the pointer part, then assume that the heap object being constructed has the same memory layout and member names. When the members are constructed, they discover that they have names registered to their addresses waiting for them.

**Comment by SanderVocke** [comment]
Ah, never realized this was there!
Thanks for the details about the implementation too - that's a very creative way to solve the problem.

**Comment by SanderVocke** [comment]
On second thought, maybe this is worth reopening for a small thing: I think it would be great if this feature was mentioned in the README and on [this wiki page](https://github.com/halide/Halide/wiki/Debugging-Tips). Because it stayed under the radar (at least for me).

Can also do this myself if you don't mind.

**Comment by abadams** [comment]
Feel free to edit the wiki or open a PR for the readme

**Comment by SanderVocke** [comment]
Edited the Wiki. I removed the mention of the deprecated HL_TRACE variable, and added some more information. Maybe you'd like to have a read to see if you agree with the edit: https://github.com/halide/Halide/wiki/Debugging-Tips

**Comment by abadams** [comment]
Thanks Sander, that's some great content.

**Comment by steven-johnson** [comment]
+1. 

See also https://github.com/halide/Halide/issues/2444 -- if we take steps in that direction this definitely belongs there.
