### ISSUE TITLE
Tutorial comments cite incorrect number of stores

### ISSUE THREAD

**Issue by chrisjhebert1973** [halide/Halide#2415]
Around line 165 in lesson_08_scheduling_2.cpp, shouldn't the number of stores be 41? (25 for the producer root and 16 for the consumer?) and not 39, or am I missing something?

// Full inlining (the default schedule):                                                                             |
    // - Temporary memory allocated: 0                                                                                   |    LOGI("Evaluating producer compute_root()");
    // - Loads: 0                                                                                                        |    consumer.realize(4,4);
    // - Stores: 16                                                                                                      |
    // - Calls to sin: 64                                                                                                |    float result[4][4];
                                                                                                                         |    float producer_storage[5][5];
    // producer.compute_root():                                                                                          |
    // - Temporary memory allocated: 25 floats                                                                           |    for(int y=0;y<5;++y){
    // - Loads: 64                                                                                                       |      for(int x=0;x<5;++x){
    // - Stores: 39                                                                                                      |        producer_storage[y][x] = sin(x*y);
    // - Calls to sin: 25                                                                                                |      }

**Comment by abadams** [comment]
You are correct - fixed in master. Thanks.
