### ISSUE TITLE
Memoized buffers are not machine aligned

### ISSUE THREAD

**Issue by ongjunjie** [halide/Halide#2422]
The code below generates a `vmovaps` instruction on memory that is not 32-byte aligned. As far as I can tell, `bound` causes Halide to assume that the memoized buffer is properly aligned.

```cpp
#include <Halide.h>
int
main()
  {
    using namespace Halide;
    Func f, g;
    Var x;

    g(x) = cast<float>(x);
    f(x) = g(x);

    const int vector_size = get_host_target().natural_vector_size(Float(32));
    f.bound(x, 0, 64).vectorize(x, vector_size);
    g.compute_root().memoize();

    Buffer<float> a = f.realize(64);

    return 0;
  }
```

**Comment by ongjunjie** [comment]
`bound` allowed simplication of load address, so we get in codegen phase:

```
Vectorize predicated dense vector load:
    f1[ramp((f0.s0.v0.v0*8), 1, 8)]
```

LLVM Codegen assumes all internal buffers to be aligned. That's fine, except that in [cache.cpp](src/runtime/cache.cpp#L399), we have

```
buf->host = ((uint8_t *)halide_malloc(user_context, buf->size_in_bytes() + extra_bytes_host_bytes));
...
buf->host += extra_bytes_host_bytes;
```

And `extra_bytes_host_bytes` is hardcoded
```
const size_t extra_bytes_host_bytes = 16;
```

The simple fix is to change the value from 16 to 32. I'm hessitating to open a PR because
- The comments left in the code suggests it's still work in progress (although nothing has changed much in the last 2 years)
- Hardcoded alignments sounds like a very bad idea when there are so many backends to support
- This may affect performance of code already in production

Would the core team please look into this and give directions? Thanks.

**Comment by abadams** [comment]
Thanks for diagnosing. This will break even worse on Hexagon, which uses
128-byte alignment... I can't immediately see a way to fix this without
just changing extra_bytes_host_bytes to 128 (and maybe putting the constant
in runtime_internal.h).

**Comment by abadams** [comment]
Here's an option: a new runtime module just for querying the native alignment size. Contains a single always_inline function int halide_get_minimum_alignment() that returns the required alignment. In theory we could have a different version of this file per alignment, but we'll probably just do 128 and 32.

**Comment by ongjunjie** [comment]
Aren't modules and always_inline mutually exclusive, or am I missing something about Halide AOT/JIT process?

`halide_default_malloc` uses hardcoded alignment of 128 bytes. If that's the accepted speed/space trade-off, then the same can be applied to memoize cache.

**Comment by abadams** [comment]
The modules are pasted together as bitcode into a single thing before being compiled, which gives an opportunity for things to be inlined. The rule for the runtime is that everything in it must be always_inline or weak.
