### ISSUE TITLE
Consider adding a "docs" dir to Halide

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2444]
We don't really have a good place for documentation in Halide; we've put some stuff in the wiki up to now (e.g. FAQs, some Generator docs), but that isn't tracked with the rest of version control, and at a certain point just stuffing things into the README is weird.

Strawman: add a "docs/" folder with Markdown files for various topics that could use nontrivial documentation that doesn't fit into the Doxygen format or the Tutorial format.

**Comment by alexreinking** [comment]
We now _have_ a docs dir that contains CMake rules for running Doxygen on the main source. There is no reason this couldn't be extended to contain additional Markdown/RST/Sphinx/whatever additional documentation we want.

We can also always use the wiki...
