### ISSUE TITLE
[Bug] RDom initialize_from_ranges bug when Expr is not defined

### ISSUE THREAD

**Issue by palindromoroz** [halide/Halide#2457]
This code leads to SIGSEGV - Segmentation violation signal

    Halide::Expr maxdisp;
    Halide::RDom  searchDom( 0, maxdisp );

Probably needs some extra checks in RDom::initialize_from_ranges. Was not sure the best way to fix it.

**Comment by steven-johnson** [comment]
It's not legal, but SIGSEGV is bad. Proper fix is probably to simply assert-fail.

**Comment by steven-johnson** [comment]
Fixed.
