### ISSUE TITLE
Access violation on Windows (looks like buffer overrun/stack corruption)

### ISSUE THREAD

**Issue by eldakms** [halide/Halide#2478]
Hi,

I would appreciate if somebody could give me debugging hints in the following situation.

I have a complex graph of functions in my pipeline: several inputs/outputs, all inner nodes that are consumed by at least two other nodes are scheduled with `compute_root`. I had a problem jit_compiling it, but this was resolved by increasing the stack size.

If I realize the pipeline without any vectorization, everything works as expected.

If I try to vectorize the functions with compute_root, I'm getting access violation (stack looks corrupt) from time to time (the error is intermittent). The vectorization is done as simply as
`func.vectorize(func.args()[0], vectorizationWidth, TrailStrategy::GuardWithIf)`.
vectorizationWidth is always smaller than the corresponding dimension.

I double-checked the input/output buffers, all seems in tact and correct. I thought that given GuardWithIf, there should be no reads/writes happening outside of inferred dimensions, so there should be no stack corruption/access violations.

I am still trying to get a smaller repro bisecting the graph and see what causes this AV with Target::Debug, Trace... It could well be that I still messed up something with buffers.

OS: Win 10 64 bit, using latest Halide pre-build binaries from May, the "runner" program is developed in VS2015 Update 3, the problem is both in Debug and Release mode.

All suggestions are highly appreciated.
Thanks!

**Comment by zvookin** [comment]
Just to check, do you have Halide bounds checking on? (That is NoAsserts is
*not* specified in the target. They are on by default.)

The only way it should fail if that flag is not present is if the
addressable memory of the buffers you have passed in does not match the
mins/extents/strides of those buffers.

Are you in an environment where you can use clang's address sanitizer?

-Z-

**Comment by eldakms** [comment]
All asserts are in place, NoAsserts is not specified.

I am not sure whether clang address sanitizer will work in my case, haven't used it before. I have some binary dependencies with C++ interfaces that were compiled with VS2015 and I cannot port them to clang. I am not sure whether this will be a problem for the sanitizer, but I will try.

I checked the input buffers, all dimensions seems to be correct.
Thank you very much for you help!

**Comment by zvookin** [comment]
Just noticed the text "using latest Halide pre-build binaries from May"
which is rather an embarrassingly long time for us to not have made a newer
blessed release. I would suggest trying the nightly build before putting
too much effort into debugging. (See:
https://github.com/halide/Halide/releases/tag/release_2016_10_25 .)

-Z-

**Comment by eldakms** [comment]
where can I get the latest nightly? do I need to compile from the latest master locally? thanks!

**Comment by zvookin** [comment]
Does:

https://github.com/halide/Halide/releases/download/release_2016_10_25/halide-win-64-trunk-aa5d5514f179bf0ffe1a2dead0c0eb7300b4069a.zip

Work for you?

-Z-

**Comment by eldakms** [comment]
But this one seems older than the one I use (this one from may 2017 https://github.com/halide/Halide/releases/tag/release_2017_05_03, whereas yours is from October 2016). Is it more stable? Sorry, maybe I missing something, thanks!

**Comment by zvookin** [comment]
Sigh, didn’t even look at the year...

https://buildbot.halide-lang.org/ Has the latest.  E.g.
https://buildbot.halide-lang.org/halide-win-64-distro-trunk-f94148d74f29776f4c213eea0e07b3b39d12488d.zip

-Z-

**Comment by eldakms** [comment]
Thanks, I can still reproduce the issue on the above build.

**Comment by eldakms** [comment]
A question regarding buffer alignment: I have reduced the size of the graph to 7 functions and three external buffers. In this setup I still can reproduce the issue. What I noticed is the following:
2 buffers are allocated using Buffer, the third one - by wrapping external pointer into a buffer. Then the function is created out of this buffer as `func(var) = buffer(var)` which is later consumed.

When this third buffer is aligned to 32 bytes all runs as expected (or if I allocate it using Buffer and copy data there), whereas in cases when it is not aligned - I see the crash. I thought that there was no requirements on alignments for the buffers, am I wrong in this regard? 
Thank you very much for your help and time!

**Comment by eldakms** [comment]
Btw, the operation that is performed on the `func` later is vectorized *. thanks!

**Comment by zvookin** [comment]
Inputs and outputs should not have alignment requirements unless one adds
the explicitly via the schedule. (One can impose alignment requirements to
get better code generation.)

Is the exception a an unaligned access violation or are you getting memory
corruption when the buffer is unaligned? I don't think we have great test
coverage for unaligned host pointers. (Most tests allocate buffers that are
aligned.)

Anything you can do to get us a small test case will help. Thank you for
working to narrow it down.

-Z-

**Comment by eldakms** [comment]
Thanks a lot! I will try to prepare a small repro, though can take a bit of time.

When you say "Inputs and Outputs", do you mean all buffers? or only buffers that get assigned to ImageParam/passed to Realize? The special thing about this buffer is that we simply wrap it as Func.

Really appreciate your answers!

**Comment by zvookin** [comment]
So it is getting compiled in as a constant at compile time? And you are
using the JIT -- i.e. realize? We likely assume constant buffers are
aligned and I can see how this would fail. In AOT mode, that buffer data
gets copied. I guess in JIT mode, we don't copy the data. If this is the
issue, then it would happen on all platforms and a repro case should be
trivial.

That said, I'm not sure how we'd resolve the problem. I feel like it should
assert the alignment, but I'm not sure there's a way to specify the buffer
can be unaligned and allow that to work. (There's a performance cost to
doing so and constant buffers are almost always aligned.)

-Z-

**Comment by eldakms** [comment]
Hey, sorry for the delay, here is a small repro. I would appreciate if you can point out what is wrong with the code. Most operations do not make much sense :), but this just for reproduction. It leads to a crash during realize in VS2015 Update 3, Win 10 x64 (binaries both from master and latest official release):

```
            std::vector<float> vec00;
            vec00.resize(90);
            auto buf00 = Halide::Buffer<float>(vec00.data(), 90);
            Halide::ImageParam i1(Halide::type_of<float>(), 1);

            auto wrap = [](const Halide::Buffer<>& b)
            {
                Halide::Var x;
                Halide::Func result;
                result(x) = b(x);
                return result;
            };

            auto mod = [](const Halide::Func& input)
            {
                Halide::Var x;
                Halide::Func output;
                output(x) = (input(x % 80));
                return output;
            };

            auto slice = [](const Halide::Func& input, int from, int to)
            {
                Halide::Var x;
                Halide::Func output;
                output(x) = input(Halide::min(from + x, to - 1));
                return output;
            };

            Halide::Var x, y;

            auto f709 = mod(i1);
            f709.compute_root(); // Weird, if i comment this one out - it starts passing on my machine.

            auto f711 = slice(f709, 512, 1536);
            auto f738 = slice(f709, 2048, 3072);

            // Make sure we have unalignment for the buffer
            float b[1025];
            float* v = b;
            if ((size_t)v % 32 == 0)
                v++;

            std::vector<float> v1;
            v1.resize(1024);

            auto buf1 = Halide::Buffer<float>(v, 1024);
            //auto buf1 = Halide::Buffer<float>(v1.data(), 1024); // <-- if you uncomment this one, it will pass, vectors are aligned on my machine.

            Halide::Func f748;
            f748(x) = f738(x) *  wrap(buf1)(x);

            Halide::Func f750;
            f750(x) = f748(x) + f711(x);

            f750.compute_root().vectorize(f750.args()[0], 8, Halide::TailStrategy::GuardWithIf);

            auto f760 = mod(f750);
            f760.compute_root();

            i1.set(buf00);
            auto outputBuffer = Halide::Buffer<float>(512);
            Halide::Target t = Halide::get_jit_target_from_environment()
                .with_feature(Halide::Target::Profile)
                .with_feature(Halide::Target::TraceRealizations)
                .with_feature(Halide::Target::Debug);
            f760.realize(outputBuffer, t);
```

**Comment by eldakms** [comment]
Hey guys,

Any update on this? Thanks!

**Comment by steven-johnson** [comment]
Sorry, I was out of town the last few days, and it's going to be a few days before I get a chance to investigate. Please keep pinging us if we don't respond :-)

**Comment by eldakms** [comment]
thanks, will do :)

**Comment by zvookin** [comment]
Crash reproduces on Mac OS X. Looking now.

**Comment by zvookin** [comment]
Should be  fixed by https://github.com/halide/Halide/pull/2559 .
