### ISSUE TITLE
Traversing halide_buffer_t inside a define_extern function

### ISSUE THREAD

**Issue by ashishUthama** [halide/Halide#2481]
Spinning my wheels on this.

What is the right way to traverse the input and output halide_buffer_t's in an external C function? I looked at the correctness tests, and I didnt see an example getting the raw pointers for a 2d/3d buffer.

In the code below, I think I have the input buffer traversal correct, but I cant seem to get the output right. I played around a bit with using the strides/and not including the min - cant seem to get the right mental model for this.

```
extern "C" int incr1(halide_buffer_t *in, halide_buffer_t *out ) {
    if(in->host==nullptr){ //inference
        for (uint32_T dInd =0; dInd<3; dInd++){
            in->dim[dInd].min    = out->dim[dInd].min;
            in->dim[dInd].extent = out->dim[dInd].extent;
        }
    }else{ //compute
       for(int32_T zInd = out->dim[2].min; zInd < out->dim[2].min + out->dim[2].extent; zInd++){
            for(int32_T yInd = out->dim[1].min; yInd < out->dim[1].min + out->dim[1].extent; yInd++){
                for(int32_T xInd = out->dim[0].min; xInd < out->dim[0].min + out->dim[0].extent; xInd++){
                    *(reinterpret_cast<real32_T*>(out->host + (zInd-out->dim[2].min)*out->dim[0].extent*out->dim[1].extent
                                                            + (yInd-out->dim[1].min)*out->dim[0].extent
                                                            + (xInd-out->dim[0].min))) =
                    *(reinterpret_cast<uint8_T*> (in->host  + zInd*in->dim[2].stride + yInd*in->dim[1].stride + xInd)) + 1;
                }
            }
        }
    }
    return 0;
}

```

**Comment by abadams** [comment]
Looks like you're multiplying by extents instead of strides.

Use (or see the source code for) halide_buffer_t::address_of in HalideRuntime.h

**Comment by ashishUthama** [comment]
Had tried using strides, that didnt seem to populate the final output.
Thanks for the pointer, will look at the source code...

```
                    // *(reinterpret_cast<real32_T*>(out->host + (zInd-out->dim[2].min)*out->dim[2].stride
                    //                                         + (yInd-out->dim[1].min)*out->dim[1].stride
                    //                                         + (xInd-out->dim[0].min))) =
```

**Comment by ashishUthama** [comment]
Got it, I think its the `*type.bytes()` that I missed. Checking.

**Comment by abadams** [comment]
Ah yeah, maybe the mismatch between expectation and reality was that our strides are in elements, not bytes.

**Comment by ashishUthama** [comment]
Yup, that was it. Thanks @abadams.
