### ISSUE TITLE
Build failed with LLVM 5.0 on macOS

### ISSUE THREAD

**Issue by chengluyu** [halide/Halide#2489]
Here's the output:

![jietu20171028-130013](https://user-images.githubusercontent.com/2239547/32131409-fcdab35e-bbdf-11e7-9bb3-8573b802e960.jpg)

I think this is a syntax error and should be fixed.

**Comment by zvookin** [comment]
We really shouldn't call a FILE * "file_desc" as that implies a small integer on UNIX. (Though even then testing for "> 0" is problematic as 0 is a valid value for a file descriptor.) Decided not to rename everything in the interest of making the minimal obvious fix quickly.

**Comment by chengluyu** [comment]
@zvookin Well, clang indicates this is an error. I think people should fix it.

**Comment by steven-johnson** [comment]
zalman@ fixed this in https://github.com/halide/Halide/commit/b182205ead79df030ecc831f4b42daaff1f1189a, just forgot to tag it in this issue. All good now.

**Comment by zvookin** [comment]
The commit added an item to the comments and I assumed that was all that was needed. Is there another thing you have to poke?
