### ISSUE TITLE
Halide should provide a non-fast-math option

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2498]
It would be useful to have a way for Halide to produce floating-point code that doesn't use -ffast-math optimizations:
- Some users may need the extra stability (or at least think they do)
- Some users may legitimately need to deal with NaN/Inf values
- It would provide a non-hack way to actually measure how much performance with -ffast-math is  giving us on current LLVM/Hardware combinations

Most reasonable way to add this is probably via a new Target::Feature.

**Comment by zanbri** [comment]
There exists a `-fno-finite-math-only` flag which may resolve the no NaN/Inf assumption, though I'm not sure whether the behavior is consistent across all machines/compilers. See: https://stackoverflow.com/questions/22931147/stdisinf-does-not-work-with-ffast-math-how-to-check-for-infinity

**Comment by zvookin** [comment]
@steven-johnson Can we close this now that Target::StrictFloat is a thing?

**Comment by steven-johnson** [comment]
Yep
