### ISSUE TITLE
Negation of signed integer max value

### ISSUE THREAD

**Issue by ashishUthama** [halide/Halide#2511]
I traced a subtle bug in my code to this:

```
// im is of type Int(8)
im(x,y) = -cast(Int(8), -128);

```

I was expecting the output to be 127, but instead the buffer had -128. Is this expected?

**Comment by abadams** [comment]
Yes, negation should be one to one and it's own inverse, which makes -128
the only possible value for -(-128). It's also consistent with modular
arithmetic, and the hardware implementation (flip the bits and add one). It
is definitely surprising the first time you see it. In C this is
technically undefined behavior, but I think you'd typically get the same
thing.

**Comment by ashishUthama** [comment]
Did not know that, thanks Andrew!
