### ISSUE TITLE
undefined reference to `Halide::Internal::Introspection::

### ISSUE THREAD

**Issue by shipingli** [halide/Halide#2532]
I am trying to build HelloeHexagon on Linux Halide 2.0, stuck on below error. No idea on how to proceed, any help?

Thanks

+ g++ -std=c++11 -I /home/Halide/include -I/home/Halide/support -g -fno-rtti pipeline.cpp /home/Halide/tools/GenGen.cpp -g /home/Halide/lib/libHalide.a -o bin/pipeline -ldl -lpthread -lz
/tmp/ccTtcODD.o: In function `Halide::Internal::check_introspection(void const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
/home/Halide/include/Halide.h:415: undefined reference to `Halide::Internal::Introspection::get_source_location[abi:cxx11]()'
/home/Halide/include/Halide.h:416: undefined reference to `Halide::Internal::Introspection::get_variable_name(void const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

**Comment by abadams** [comment]
Looks like a C++ abi mismatch issue. What g++ version are you using, and how did you acquire or compile Halide?

**Comment by shipingli** [comment]
I got Halide 2.0 from https://developer.qualcomm.com/software/hexagon-dsp-sdk/tools, and I am using  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 

What version is required?

Thanks

Shiping

**Comment by abadams** [comment]
Ah, then it depends on how the qualcomm folks compiled their libHalide. I'm guessing they used an older compiler. I would just checkout and compile Halide from source.

**Comment by abadams** [comment]
I'll ping one of the qualcomm people @ronlieb

**Comment by shipingli** [comment]
Thanks, I also tried to communicate with them yesterday.  They asked g++ version too.

**Comment by ronlieb** [comment]
We think they need to use g++ 4.8.4 , that is what our Halide 2.0 release is built with , and built on ubuntu 14.04

 

---

Qualcomm Innovation Center, Inc. is a member of Code Aurora Forum, hosted by The Linux Foundation

**Comment by khourig** [comment]
This is the dual-ABI thing again. TLDR: compile your code with `-D _GLIBCXX_USE_CXX11_ABI=0`

https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

**Comment by shipingli** [comment]
I am using HALIDE_Tools/2.1 now, any idea what g++ version I should use? or is there a solution that does not require the end user using old g++?

Thanks

**Comment by shipingli** [comment]
Sorry, did not read it clearly, using -D _GLIBCXX_USE_CXX11_ABI=0 fixed issue
