### ISSUE TITLE
Link-time errors when building with cmake – missing the IRMutator2 vtable

### ISSUE THREAD

**Issue by fish2000** [halide/Halide#2537]
I’m aware that you guys – specifically @steven-johnson – have been iteratively redoing a lot of the IR structs, of late. In fact, I’m not sure that work is being called “done” at this point; in any case, I can report that I get the same build error(s) now when trying to build Halide from HEAD with `cmake` as I did when I tried to build Halide from HEAD with `cmake`, like, two weeks ago. They look like this:

![screen shot 2017-11-15 at 4 20 59 pm](https://user-images.githubusercontent.com/378969/32861132-d7694360-ca21-11e7-89ab-39eb7ea46b05.jpg)

… this error arises irrespective of the Clang version used (both the current LLVM HEAD build and the current Apple Xcode shipping version).

Since the Halide codebase around this seems to be in flux, I’m reporting this as an “issue” rather than sending in a fix, if there are changes still to come in the pipeline. However, I did manage to get things compiling and running just fine on my fork, by festooning the new IR structs in question with some defaulted constructors and other doodads:

https://github.com/fish2000/Halide/commit/9a6d612bcebc0e7c3d613caf2fe7653847725d00
https://github.com/fish2000/Halide/commit/7cf5d3c39b72f7aa48f7b2b92ed1e89ae5852b43
https://github.com/fish2000/Halide/commit/072fd22f52774ae18e85f33894ebab8202f8c47d
https://github.com/fish2000/Halide/commit/186034e361b75101e7c973c3e7149045e3f64666
https://github.com/fish2000/Halide/commit/bca20f19177ec27da40ee7a55a5f078133343785
https://github.com/fish2000/Halide/commit/7773951d9d89c628f76e6e39d6b6b43831ce979d
https://github.com/fish2000/Halide/commit/db8e461179232dd6717f03053179d1f9e46e6500
https://github.com/fish2000/Halide/commit/6cc25816ddb63e3d78916ea5ae149c80082cf97e
https://github.com/fish2000/Halide/commit/eb1011a9f9b71e5a79d2990fb9a184c014906521

… if someone can take a look, as if by some chance these changes are along the lines of what is ultimately desired, do let me know. I would be happy to do a clean and legible implementation of these constructors, ensuring that the vtable linkage for these symbols is superlatively robust.

**Comment by steven-johnson** [comment]
What version of XCode is this? I've been building with v8.3.3 and not seeing any such issues.

**Comment by fish2000** [comment]
Whoops, nevermind – on closer inspection, my environment was retaining a `-std=c++17` flag, the removal of which solved the problem. My bad.
