### ISSUE TITLE
Create Android library

### ISSUE THREAD

**Issue by shipingli** [halide/Halide#2542]
Is there a way to build an Android library (.so) that it can be used by other application? Do we have any examples/apps on this?  
Thanks

**Comment by guoyejun** [comment]
i have the same question, how to build halide within android source tree, looks that there is no Android.bp nor Android.mk. Did I miss anything? I'm new to halide and android. thanks.

**Comment by steven-johnson** [comment]
I believe that apps/HelloAndroid and apps/HelloAndroidCamera2 give examples of building .so files with a Gradle/AndroidStudio build system.

I don't think we have any examples of using the Android.mk-style build systems, and don't really plan to add any; as far as I can tell, most new Android development is moving away from using that build system, so we're not inclined to actively support it.
