### ISSUE TITLE
Use align_storage/align_bounds for vectorization without guards

### ISSUE THREAD

**Issue by eldakms** [halide/Halide#2551]
Hi,

To allow vectorization without guards, I would like to make sure the resulting storage has the correct number of elements.
Is it possible to use align_storage or bounds for that?

i.e. instead of this:
```
matrixPad(x, y) = Halide::BoundaryConditions::constant_exterior(matrix, Halide::cast(dataType, 0),
            { { 0, matrixRowDimension } })(x, y);
head(i, y) = Halide::sum(matrixPad(k*vectorizationWidth + i, y), "Reduce2DMSumHead" + name);
output(y) = Halide::sum(head(kVector, y), "Reduce2DMSumOutput" + name);
head.vectorize(i);
head.compute_at(output, y);

output.compute_root().vectorize(y, vectorizationWidth, Halide::TailStrategy::GuardWithIf);
```

Something like this:
`output.compute_root().align_storage(y, vectorizationWidth).vectorize(y, vectorizationWidth);`

If not, what can I use instead to accomplish this?
Thank you!

**Comment by abadams** [comment]
The simplest solution is probably:

output.compute_root().vectorize(y, vectorizationWidth, TailStrategy::RoundUp)
