### ISSUE TITLE
Windows buildbots not running correctness tests

### ISSUE THREAD

**Issue by abadams** [halide/Halide#2562]
https://buildbot.halide-lang.org/master/#/builders/58/builds/314

It makes the build really fast, so we've got that going for us...

Presumably something is messed up with the cmake build. We still have build-breakage coverage on windows. This can probably wait until after thanksgiving.

**Comment by dsharletg** [comment]
Is #2548 by chance the fix for this? The tests look good on that branch.

**Comment by dsharletg** [comment]
Wait, no they don't. Same problem on that branch.

**Comment by dsharletg** [comment]
I was looking at this to see when this started. I went back 2 months and didn't find a build where the correctness tests (or any tests) ran. So for a very long time, we've only had build coverage on windows...

**Comment by abadams** [comment]
Oh yeah, you can tell by the runtime of the build. Looks like it started here:

https://github.com/halide/Halide/commit/7187acdec4d075470b84826b7f4919398d0c79f9

**Comment by steven-johnson** [comment]
> Is #2548 by chance the fix for this? The tests look good on that branch.

They were intended to be. I'll put this at top of my list when I return Monday.

**Comment by steven-johnson** [comment]
Ugh, I see the problem: the names of the .exe's being output no longer match the patterns expected by the buildbot; I updated the Travis build script to just use the 'make' commands, but buildbot uses something completely different. Should be a simple fix.

**Comment by steven-johnson** [comment]
https://github.com/halide/build_bot/pull/6

**Comment by alexreinking** [comment]
Looks like this was resolved, but never closed.
