### ISSUE TITLE
[Q] cmake error while compiling on LLVM

### ISSUE THREAD

**Issue by chamcham115** [halide/Halide#2570]
I met a error while cmake configure. 
Below is error message:

-- Constructing LLVMBuild project information
CMake Error at build/LLVMBuild.cmake:1:
  Parse error.  Expected "(", got bad character with text "".
Call Stack (most recent call first):
  CMakeLists.txt:670 (include)

-- Configuring incomplete, errors occurred!

What is that?

My OS is Windows 7 64bit. 
I use the Visual Studio 2015 community with update 3.

Why is not working?

**Comment by steven-johnson** [comment]
What version of LLVM are you using?
What are the CMake command(s) you are issuing?

**Comment by chamcham115** [comment]
LLVM version is 4.0.0. 
cmake command is below:

cmake -DLLVM_ENABLE_TERMINFO=OFF -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=D:\\BACKEND\\llvm400\\ -G "Visual Studio 14 Win64" D:\\BACKEND\\llvm-4.0.0.src\\

I also use the python 2.7.

I don't understand why it doesn't work. 
A few days ago, I compiled the LLVM on another PC. 

If you know this problem, I wanna any advice.

**Comment by steven-johnson** [comment]
I don't see any obvious errors in the cmake command, and I have not seen this particular error before. Anyone else seen anything like this?

**Comment by alexreinking** [comment]
Closing because the issue has gone stale. LLVM 4 isn't supported anymore. Please open a new issue if you still have problems.
