### ISSUE TITLE
Evaluate CMake WINDOWS_EXPORT_ALL_SYMBOLS

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2571]
This feature purports to allow exporting all symbols on Windows; we should try it out to see if it works as advertised. If it does, we could consider using it instead of the EXPORT macro.

**Comment by alexreinking** [comment]
Closing because 

But should we really be exporting all our symbols? Even our inlined template instantiations and cpp-file-only implementation details? Could cut down a lot on binary size by being selective about this.
