### ISSUE TITLE
Passing generator Input to helper functions

### ISSUE THREAD

**Issue by ashishUthama** [halide/Halide#2581]
Whats the best way to architect helper functions (for reuse) that work on generator Inputs?
For example:

```
// Create an RDom from a strel
RDom strel2rdom(Buffer<bool> strel){
    Expr xmin = cast(UInt(32), floor(Expr((strel.dim(0).extent()+1)/2))-Expr(1));
    Expr ymin = cast(UInt(32), floor(Expr((strel.dim(1).extent()+1)/2))-Expr(1));
    RDom r(-xmin, strel.dim(0).extent(),
            -ymin, strel.dim(1).extent());
    r.where(strel(r.x+xmin, r.y+ymin)==1);
    return r;
}


class myfun : public Halide::Generator<myfun> {
public:
    Input<Buffer<bool>> strel{"strel", 2};
    void generate (){
        RDom r = strel2rdom(strel);
   }
    void schedule(){
    }
}
```

This gives me:

`error: could not convert ‘(({anonymous}::myfun*)this)->{anonymous}::myfun::strel’ from ‘Halide::Internal::GeneratorBase::Input<Halide::Buffer<bool> > {aka Halide::GeneratorInput<Halide::Buffer<bool> >}’ to ‘Halide::Buffer<bool>’
`
How do I get at the Buffer in the input to pass around?

**Comment by steven-johnson** [comment]
Input<Buffer<>> isn't a concrete Buffer<> and can't be used interchangeably. For helper functions I'd recommend using Halide::Func instead (passing in explicit dimensions/extents where necessary).

**Comment by abadams** [comment]
apps/cuda_mat_mul uses an OutputImageParam for this purpose.

**Comment by ashishUthama** [comment]
Thanks for that tip, I'll be using a wrapped Func + additional Expr arguments with each extent approach.
