### ISSUE TITLE
Use define_extern() to import externel C function fail

### ISSUE THREAD

**Issue by alynn340** [halide/Halide#2659]
Dear all,

I modify the lesson_11 source code to use define_extern() to import external C function, but in the extern C function always get "input->dim[0].extent = 0". 
And the program would crash in external C function when read the input->host buffer.
Anyone can help me?
================================================================
extern "C" int extern_c_add(halide_buffer_t *input, halide_buffer_t *output)
{
    int p = 0;
    printf("input->dim[0].extent %d \n",input->dim[0].extent); // "0"
    printf("input->dim[1].extent %d \n",input->dim[1].extent); // "0"
    printf("output->dim[0].extent %d \n",output->dim[0].extent); //"640"
    printf("output->dim[1].extent %d \n",output->dim[1].extent); //"480"

    for(int x=0; x<output->dim[0].extent; x++)
        for(int y=0; y<output->dim[1].extent; y++, p++)
            output->host[p] = input->host[p] + 2;

    return 0;
}
================================================================
    Func brighter;
    Var x, y;

    // Declare the arguments.
    Func make_a_root{"make_a_root"};
    Func extern_c_add{"extern_c_add"};
    Param<uint8_t> offset;
    ImageParam input(type_of<uint8_t>(), 2);
    std::vector<Argument> args(2);

    make_a_root(x,y) = input(x, y);
    ExternFuncArgument extern_arg = make_a_root;   
    args[0] = input;
    args[1] = offset;

    extern_c_add.define_extern("extern_c_add", { extern_arg }, Halide::type_of<uint8_t>(), 2, NameMangling::Default, Halide::DeviceAPI::Host);
    brighter(x,y) = extern_c_add(x,y)+1;
    brighter.vectorize(x, 16).parallel(y);
    extern_c_add.compute_root();
    make_a_root.compute_root();

**Comment by ashishUthama** [comment]
The first call is likely 'bounds inference', this is when Halide is trying to figure out how much of the input data is needed by this stage. Maybe this test helps figuring it out:
https://github.com/halide/Halide/blob/master/test/correctness/extern_stage.cpp

**Comment by alynn340** [comment]
Thank you, ashishUthama
    if (input->is_bounds_query()) {
        input->dim[0] = output->dim[0];
        input->dim[1] = output->dim[1];
        printf("is_bounds_query\n");
    }
Program run successfully after I add the above code, but why it runs 2 times "is_bounds_query" ?

**Comment by ashishUthama** [comment]
Try printing out the output-dim, most likely its because you had two threads that were working on two different parts of the data.

**Comment by abadams** [comment]
Also, depending on the compute_at location of various things, Halide may
need to make multiple bounds queries to extern stages. E.g. one for the
whole output, and then one for each tile.

**Comment by alynn340** [comment]
I call the prebuilt shared library from the extern C function, but it brings endless for loop.
Is it a bug in Halide ?

extern "C" int extern_c_add(halide_buffer_t *input, halide_buffer_t *output)
{
    if (input->is_bounds_query()) {
        input->dim[0] = output->dim[0];
        input->dim[1] = output->dim[1];
        printf("is_bounds_query\n");
    }
    else
    {
        printf("NO is_bounds_query\n");
        test_assign(&input->host[0], input->dim[0].extent, input->dim[1].extent, &output->host[0]);
    }
    return 0;
}

And I pre-compile the below funtion to the shared library which can be used in extern C func.
int test_assign(unsigned char* in, int w, int h, unsigned char* out)
{
    printf("enter test_assign func...w %d h %d\n",w,h); 
    int p=0;
        if(in == NULL)
            printf("in null ptr\n");
        if(out == NULL)
            printf("out null ptr\n");
    
    for(int j=0; j<4; j++)
    {
        printf("h limit %d (4)\n",h);
        for(int i=0; i<w; i++, p++)
        {
            printf("i %d j %d \n",i,j); //program running even j>=4
            out[p] = in[p] + 2; 
        }
    }
}
