### ISSUE TITLE
Float(64).min() does not seem to return -inf

### ISSUE THREAD

**Issue by ashishUthama** [halide/Halide#2660]
Hi folks - I am seeing something that I cant make sense of, hope its something simple that you can point me to!

I am using generators, and debugging a convoluted generator code lead me to:
```
         //1 - this returns a bit pattern 1111111111101111111111111111111111111111111111111111111111111111
        out(x,y)  = Float(64).min();
        //2 - this returns a bit pattern 1111111111110000000000000000000000000000000000000000000000000000
        //out(x,y) =Expr(std::numeric_limits<double>::infinity());
```

When I tried to test this stand alone using JIT, I get the same (2) bit pattern:
```
using namespace Halide;
int main(int argc, char **argv) {
union
    {
         float input;   // assumes sizeof(float) == sizeof(int)
         int   output;
    }    data;

    data.input = -std::numeric_limits<double>::infinity();
    std::bitset<sizeof(float) * CHAR_BIT>   bits(data.output);
    std::cout << bits << std::endl;

    Func f;
    Var x,y;
    f(x,y) = Float(64).min();
    Halide::Buffer<double> out = f.realize(1,1);

    data.input = out(0,0);
    std::bitset<sizeof(float) * CHAR_BIT>   hbits(data.output);
    std::cout << hbits << std::endl;
    return 0;
}

Outputs:
11111111100000000000000000000000
11111111100000000000000000000000
```

So I then tried to use the AOT approach:
```
#include "Halide.h"
using namespace Halide;

class inftest : public Halide::Generator<inftest> {
public:
    Input<Buffer<>> im{"im", 2};
    Output<Buffer<>> infout{"infout", 2};
    Var x{"x"}, y{"y"};

    void generate (){
        infout(x,y) = Float(64).min();
    }
    void schedule(){

    }
};
RegisterGenerator<inftest> inftest{"inftest"};

```

And am now stuck trying to interpret the generated .cpp code:
```
infb|>g++ gs.cpp tools/GenGen.cpp -I include/ -std=c++11 -lHalide -L. -o gen -fno-rtti -lpthread -ldl
infb|>./gen -f inftest -o . -g inftest target=x86-64-linux-avx2-avx-sse41 im.type=float64 -e cpp
infb|>grep float_from inftest.cpp
inline float float_from_bits(uint32_t bits) {return reinterpret<float, uint32_t>(bits);}
    ((double *)_infout)[_91] = float_from_bits(4286578688 /* -inf */);
```
However, this doesnt look like it would generate real64 -inf - so thought I would ask here first before I continued down this rabbit hole.

**Comment by zvookin** [comment]
Halide's uses fast_math which does not allow Inf and NaN to appear in
computations, hence returning -Inf as the minimum float would be highly
problematic. Perhaps we'll return the infinity values with strict_float,
when that lands, though I'm not sure that will work out well.

-Z-

**Comment by ashishUthama** [comment]
Thanks Zalman - I noticed the conversations about fast_math/strict_float - didnt tie that to this.

Most of the solutions I plan to tackle would need the ability to work with infs/nans at the input and outputs. I'll keep an eye on the strict_float work and hopefully at least contribute with some testing.
