### ISSUE TITLE
Confused about tutorial

### ISSUE THREAD

**Issue by HeGaoYuan** [halide/Halide#2664]
@abadams  @jrk  @steven-johnson @dsharletg 
    Hi, I am learning Halide through your tutorial. It is a great tutorial!
    But I got confused by the difference between the tutorial of html version and the tutorial of github version. For example, about the lesson 15, the first picture is the snap from the [halide-lang.org](http://halide-lang.org/tutorials/tutorial_lesson_15_generators.html), the second picture is the snap from [github](https://github.com/halide/Halide/blob/master/tutorial/lesson_15_generators.cpp). Obviously, they are different, I wonder to know two questions: First, are both versions right? Second, which version is recommended?
    Thank you very much!
<img width="1280" alt="halide-lang" src="https://user-images.githubusercontent.com/16939557/34288181-969adb60-e726-11e7-94c0-e32b78f60da1.png">
<img width="1280" alt="github" src="https://user-images.githubusercontent.com/16939557/34288226-e886f864-e726-11e7-8aac-7a8a8936b8fd.png">

**Comment by steven-johnson** [comment]
Whoops! It looks like the version on the website at halide-lang.org didn't get updated with the last release of Halide. We'll get to this soon. Sorry about that!

**Comment by steven-johnson** [comment]
This should finally be correct. Sorry for the delay!
