### ISSUE TITLE
Performance difference between cpp and object

### ISSUE THREAD

**Issue by kanryu** [halide/Halide#2666]
Hi,
I'm writting a image filter sample, and it works fine on standalone.

I'm generate the filter as header/object and header/cpp.
But there are the performance difference.

object is fast, cpp is 6x times slower.  

What's happend?

In addition, assemble (* .s) that halide exported can not be assembled with GNU AS.

**Comment by zvookin** [comment]
The C++ backend is a completely different compilation path which is not
expected to produce great performance. Generating C++ is useful for
debugging, as the basis for other backends like OpenCL, and as a fallback
for targetting obscure platforms without (easily usable) llvm support.

Unless I’m misunderstanding the question or there is some other context,
the report is entirely as expected. There are many detailed reasons as to
why going througg C++ is slower than using llvm directly. The only reason
one would expect similar performance is if one assumed compile_to_object
was calling compile_to_c in its implementation.

I’m sure one can construct cases where the performance difference is in
favor of C compilation. Especially with little scheduling for the Halide
cide and when the C compiler manages to autovectorize something.
