### ISSUE TITLE
GPU performance issues

### ISSUE THREAD

**Issue by djohnkirby** [halide/Halide#268]
Hey guys, still working on the benchmarking code I posted last week. The function compiles and runs, and I was able to write multiple schedules to run it. Here's the function, dead commented out code and all:
# include <Halide.h>

using namespace Halide;

int main( int argc, char *\* argv )
{
  ImageParam input(UInt(8), 2);
  ImageParam input2(UInt(8), 2);
  Halide::Func average;

  Halide::Var x("x"), y("y"), xi("xi"), yi("yi"), c("c");

  //The algorithm
  Halide::Expr value = input(x, y);
  Halide::Expr value2 = input2(x, y);
  value = value/2.0f + value2/2.0f;

  average(x, y) = Halide::cast<uint8_t>(value);

  //The Schedule
  //This schedule's performance : 2x10^6 pixels/ms <- I'm skeptical of this
  //average.split(y,y,yi,8).parallel(y).vectorize(x,8);

  //This schedule's performance: About the same as above
//  average.tile(x, y, xi, yi, 100, 100).parallel(y).vectorize(x, 8);

  //A schedule that runs on GPU and is comically slow
  average.cuda_tile(x, y, 100, 100);

  //Split y into sections of 8 scanlines
  //Compute scanlines in parallel in vectors of size 8

  average.compile_to_file("average", input, input2);
  return 0;
}

Anyway, the schedules that are commented out perform admirably. I'm running this on an 8-core machine with 6MB of cache. So I find they're really fast, about 1millisecond per 800x800 image. The cuda_tile version is comically slow, coming in at about 350milliseconds to process an 800x800 pixel image on a machine with two nVidia Quadro FX 3700 GPUs.

I know that openACC has some problems if you don't give it good hints on when to move files from the CPU memory to the GPU memory. And this kind of slowdown seems like something that would happen in this case.

Is there anything I can do to make my GPU performance more promising here?

**Comment by zvookin** [comment]
Old and not particularly actionable.
