### ISSUE TITLE
Using vpmaddubsw for 8 bit matrix-vector multiplication

### ISSUE THREAD

**Issue by eldakms** [halide/Halide#2701]
Hi,

I would appreciate any suggestions in the following situation.
I am implementing a matrix-vector multiplication for 8 bit numbers, accumulating results in 16 bit. I'm targeting AVX2 and when I generate the corresponding assembly I see that Halide spits out only a combination of  vpmullw and vpaddw, but never vpmaddubsw (a hand crafted algorithm using vpmaddubsw runs ~20% faster than Halide).
Is there any way to enable summation using this instruction? If not, what would be an alternative? Implementing an external function and using intrinsic instructions inside it?

Thanks!

**Comment by eldakms** [comment]
Any thoughts on this? Thank you!

**Comment by abadams** [comment]
@dsharletg  needed to do something similar for a hexagon instruction in https://github.com/halide/Halide/blob/master/apps/hexagon_matmul/matmul_generator.cpp

Try manually unrolling the summation in the algorithm like that. It's ugly, but it might do what you want.

**Comment by dsharletg** [comment]
This instruction is similar to pmaddwd, I think we need similar logic to support this. I doubt it will generate automatically...

I think the strategy in the Hexagon matrix multiply is something we would use if we wanted to support pmaddwd/pmaddubsw/similar instructions without the overhead of interleaving, but we would need to add new patterns to support that (like those in Hexagon).

**Comment by abadams** [comment]
Yeah, I'd look into extending the pmaddwd detection we already have. It's done via should_use_pmaddwd in CodeGen_X86.cpp, and then the implementation of the call that generates is in src/runtime/x86_avx2.ll

**Comment by eldakms** [comment]
great, thanks!
