### ISSUE TITLE
Problem with pipeline.get_func(size_t index) method

### ISSUE THREAD

**Issue by ugigugi** [halide/Halide#2711]
Hi everyone!

I've recently downloaded the latest version of Halide and some of my benchmarks that I was able to build and run with the previous version [git checkout 238f63badacf27743c8374210d2f5838aada332a] are now triggering the assertion `Cannot inspect an unlocked LoopLevel: . `. 

As far as I was able to trace it, this comes due to the call to `pipeline.get_func()` method (I am using this method just like you have explained in your tutorial lesion 21). This method calls `realization_order`, which next calls `populate_fused_pairs_list`, which finally calls `LoopLevel::is_inlined()` that triggers the assertion inside the `LoopLevel::check_locked()`. 

Since I can see that there are some major changes inside the `RealizationOrder.cpp` file (comparing the latest and 'working' version of the runtime), my question is have you tested `Pipeline::get_func()` method, does it work properly, and if yes, can you point me to some simple test-case that works for you so I can check it also on my machine. If not, any suggestion how to fix this would be more than welcomed.

All the best,
Ugi

**Comment by abadams** [comment]
@psuriana

**Comment by psuriana** [comment]
@ugigugi If you don't mind, could you please send me some of your benchmarks that failed to compile so that I can test if the fix works? Thanks.

**Comment by ugigugi** [comment]
Here it comes! Unfortunately, I am not able to send you the proprietary code we are developing, but this quite simple test-case is reproducing the same error, so go ahead and try it out.

All the best,
Ugi
[test_mamtul.tar.gz](https://github.com/halide/Halide/files/1673213/test_mamtul.tar.gz)

**Comment by psuriana** [comment]
Fixed in #2774
