### ISSUE TITLE
how to understand it's meta-programming

### ISSUE THREAD

**Issue by guoyejun** [halide/Halide#2718]
http://halide-lang.org/docs/tutorial_2lesson_01_basics_8cpp-example.html says "We're meta-programming."

from wiki:  Metaprogramming is a programming technique in which computer programs have the ability to treat programs as their data. ... The language in which the metaprogram is written is called the metalanguage. The language of the programs that are manipulated is called the attribute-oriented programming language.

so, when we are programming, it is considered that we are writing c++ code or writing Halide code? Which one is metalanguage?    

And, Halide  uses the c++ template  technique, does this relative to meta-programming? 

just want to get a clear understanding of the concepts, for this specific case, (i understood these terms do not have a definitive definition). thanks.

**Comment by abadams** [comment]
I would call C++ the metalanguage. We're constructing Halide pipelines using C++ code. The Halide "language" is really just a C++ API.

Template metaprogramming would be one level more meta still. Eigen is a great example of using C++ templates to metaprogram fused linear algebra ops. We don't do much template metaprogramming in Halide.

**Comment by guoyejun** [comment]
thanks!
