### ISSUE TITLE
fold_storage() is too conservative after recent simplification changes

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2748]
(See https://github.com/halide/Halide/commit/b4ba55deeab34ea7058fd6a48e6f49660c2b5c95 for the simplest repro case I have been able to come up with.)

Recent changes have made fold_storage bounds calculations more conservative in some cases; the change that made the problem visible happened to be improvements to simplifying expressions of the form (x*a + b)/c, but the underlying issue appears to be that StorageFolding doesn't handle compound conditionals in select() as well as it could:

Before, we had an Expr like

    select((c > 0), x+2, select((d > 0), y+2, x))

Now it turns out that `(d > 0)` uses vars (so it's not a constant expression) but turns out to have terms that cancel out in the prover, giving it an interval of [0,0] -- i.e., it's provably false in all cases -- so there's an early out. This means that the first case reduces to

    select((c > 0), x+2, select(false, y+2, x)) -> select((c > 0), x+2, x)

So the interval we end up with is

    [min: select((c > 0), Interval[x+2].min, Interval[x].min), 
     max: select((c > 0), Interval[x+2].max, Interval[x].max)]

...but `(c > 0)` is a 'constant' condition, so this will likely be simplified further downstream.

After the simplification improvements, it turns out that `y` now simplifies down into `x`, so the original Expr is simplified into a single select:

    select(((c > 0) || (d > 0)), x+2, x)

Now the gotcha here is that the condition isn't a constant expression (because of `d>0` using vars), but rather than attempting to simplify the condition into `((c > 0) || false) -> (c > 0)`, the Bounds calculation code assumes that select with a non-const condition should just fall back to the worst-case scenario:

    [min: min(Interval[x+2].min, Interval[x].min)),
     max: max(Interval[x+2].max, Interval[x].max))]

...which gives us a range that's 2 larger than we had before, which is what we're seeing.

**Comment by psuriana** [comment]
@steven-johnson @abadams  Are we still having this problem? Or is it solved by #2754?

**Comment by steven-johnson** [comment]
It seems to be fixed now, we can probably close.
