### ISSUE TITLE
ETA for the next official release

### ISSUE THREAD

**Issue by eldakms** [halide/Halide#2749]
Hi,

Is there an ETA for the next official release? We would like to use some already implemented features (in particular using a pipeline from different threads) in production.
Thanks!

**Comment by steven-johnson** [comment]
We don't have one scheduled, but are definitely overdue. I'd propose aiming for middle of next week (Feb 21 or so). Anyone have concerns or things that need to land first?

**Comment by steven-johnson** [comment]
Working on a release now based on commit 46d8e9e0cdae456489f1eddfd6d829956fc3c843. Stay tuned.

**Comment by steven-johnson** [comment]
https://github.com/halide/Halide/releases/tag/release_2018_02_15
