### ISSUE TITLE
Multiple definitions of _floor_f64 even if Target::NoRuntime is used.

### ISSUE THREAD

**Issue by Beaky2000** [halide/Halide#2816]
This problem occurs with Ahead of time compiled code on 32-bit Windows specifically. It occurs in the 2018/02/15 release as well as some earlier releases.

Even if Target::NoRuntime is used to allow using several Halide generated obj files, the _floor_f64 symbol gets defined in every obj file. As a result it is only possible to link the final program by using the /FORCE:MULTIPLE option to the (Microsoft/Visual Studio) linker, but this is inelegant and risky.

The output from linking the final program can look like this:

`1>halideAOT_AVX2_32.obj : warning LNK4006: _floor_f64 already defined in halideAOT_AVX_32.obj; second definition ignored
1>halideAOT_Fallback_32.obj : warning LNK4006: _floor_f64 already defined in halideAOT_AVX_32.obj; second definition ignored
1>halideAOT_SSE_32.obj : warning LNK4006: _floor_f64 already defined in halideAOT_AVX_32.obj; second definition ignored
1>imageScale.lib(halideAOT_AVX_32.obj) : warning LNK4006: _floor_f64 already defined in halideAOT_AVX_32.obj; second definition ignored
1>imageScale.lib(halideAOT_AVX2_32.obj) : warning LNK4006: _floor_f64 already defined in halideAOT_AVX_32.obj; second definition ignored
1>imageScale.lib(halideAOT_SSE_32.obj) : warning LNK4006: _floor_f64 already defined in halideAOT_AVX_32.obj; second definition ignored
1>imageScale.lib(halideAOT_Fallback_32.obj) : warning LNK4006: _floor_f64 already defined in halideAOT_AVX_32.obj; second definition ignored
1>C:\Dev\imagecomposer\Debug\ImageComposer.dll : warning LNK4088: image being generated due to /FORCE option; image may not run`

**Comment by steven-johnson** [comment]
Does this occur in any of the existing apps or tests in Halide, or is it specific to your build?

**Comment by zvookin** [comment]
There are certain things that are inlined into every module. I would expect
all of these to be "alwaysinline" however. We should probably check that.

**Comment by steven-johnson** [comment]
Hmm, in win32_math.ll:

    define weak_odr double @floor_f64(double %x) nounwind uwtable readnone noinline {

**Comment by Beaky2000** [comment]
@steven-johnson , I am not aware of any existing examples that use the Target::NoRuntime inorder to link several Halide generated object files into the same binary, but if there are any and you could point me in the right direction, that would be great!

I could also make a minimal example with Visual Studio solution that reproduces the problem if that would help.

**Comment by steven-johnson** [comment]
Anything that uses the halide.cmake rules (eg `halide_library`) will use NoRuntime automatically. 

A perhaps simpler example to look at is apps/linear_algebra/Makefile

**Comment by Beaky2000** [comment]
I have tried looking at the linear_algebra example, but I was unable to run cmake on it and decided to create a minimal example from scratch that reproduces the error instead. Unfortunately, my minimal example does not exhibit this problem, so there must be some combination with some specific functionality that I am using in my code. 

I will try to create a minimal example that does reproduce the error!

**Comment by alexreinking** [comment]
Is this still an active issue?

**Comment by Beaky2000** [comment]
Yes, I just tested with the latest release of Halide (release_2019_08_27) and there is no change.

Unfortunately I have been unable to create a minimal example. There is obviously something in my particular code that triggers this, but I have not been able to figure out what that is.

**Comment by Beaky2000** [comment]
I looked some more into this and it seems to only happen when I create the Halide::Target with an empty vector of features:

Halide::Target targ(Target::Windows, Target::X86, 32, {});

In this case the generated obj file contains the _floor_f64 symbol, but not for any other combination of features that I use (SSE41, AVX and AVX+AVX2).

**Comment by Beaky2000** [comment]
[HalideIssue2816.zip](https://github.com/halide/Halide/files/4255745/HalideIssue2816.zip)

So I spent some more time on this and have been able to create a minimal-ish way to reproduce this:

Extract the attached zip file.
Open the solution in Visual Studio 2019
Fix the paths to Halide includes, libraries and runtimes (I was using the release_2019_08_27)
Build the HalideAOT project. It will run itself as a post build step (If it finds Halide.dll)
Build the HalideIssue2816. It will fail to link because both files created by HaliedAOT contains _floor_f64

**Comment by steven-johnson** [comment]
I think this may have been fixed by https://github.com/halide/Halide/pull/4238 -- which landed after our last binary release. (And yes, we are way overdue for another binary release...)

**Comment by dsharletg** [comment]
This was likely fixed by the PR Steven mentioned, please reopen if it is still a problem.
