### ISSUE TITLE
Mac OSX cmake libHalide.dylib path error

### ISSUE THREAD

**Issue by LoveDaisy** [halide/Halide#2821]
I'm working on mac OSX and trying to compile my small project with cmake. I wrote my CMakeLists.txt as follows:
```shell
# my CMakeLists.txt
cmake_minimum_required(VERSION 3.9)
set(CMAKE_CXX_STANDARD 11)

# path to distribution of halide
set(HALIDE_DISTRIB_DIR "/my/halide/path")
include("${HALIDE_DISTRIB_DIR}/halide_config.cmake")
include("${HALIDE_DISTRIB_DIR}/halide.cmake")

halide_library(blf
    SRCS bilateral_filter_generator.cpp
    GENERATOR_ARGS auto_schedule=true)

add_executable(process process.cpp)
target_link_libraries(process PUBLIC blf)
```

The problem is, when I finished cmake and start make, it reports an error:
```shell
$ make
Scanning dependencies of target halide_library_runtime.generator_binary
[ 12%] Building CXX object CMakeFiles/halide_library_runtime.generator_binary.dir/path/to/halide/tools/GenGen.cpp.o
[ 25%] Linking CXX executable halide_library_runtime.generator_binary
[ 25%] Built target halide_library_runtime.generator_binary
Scanning dependencies of target halide_rt_host_runtime_gen
dyld: Library not loaded: /Users/halidenightly/build_bot_new/worker/mac-64-trunk/halide-build/bin/libHalide.dylib
  Referenced from: /path/to/my/project/build/./halide_library_runtime.generator_binary
  Reason: image not found
make[2]: *** [genfiles/halide_rt_host/halide_rt_host.a] Abort trap: 6
make[1]: *** [CMakeFiles/halide_rt_host_runtime_gen.dir/all] Error 2
make: *** [all] Error 2
```

Note that it tried to find `libHalide.dylib` at `/Users/halidenightly/build_bot_new/worker/mac-64-trunk/halide-build/bin/libHalide.dylib`, which obviously is *NOT* path on my mac. Looks like it's a path on a building server.

I'm new to cmake and I have no idea about how to figure out what is going wrong. I guess there may be some mistakes in those cmake functions defined in `halide.cmake`? Any one has met similar problems?

P.S. It is totally OK and works well when I use hand-write g++ command to build my project, as follows:
```shell
# my build.sh
g++ bilateral_filter_generator.cpp /path/to/halide/tools/GenGen.cpp -g -std=c++11 -fno-rtti \
    -I /path/to/halide/include -L /path/to/halide/bin -lHalide -lpthread -ldl -o generate
DYLD_LIBRARY_PATH=/path/to/halide/bin ./generate -g blf -o . target=host auto_schedule=true
g++ process.cpp blf.a -g -std=c++11 -fno-rtti -I /path/to/halide/include \
    -I /path/to/halide/tools -L /path/to/halide/bin -lHalide -o process
```

**Comment by huiyiqun** [comment]
same issue here.

A working workaround is using static library instead:

```cmake
set(HALIDE_DISTRIB_USE_STATIC_LIBRARY TRUE)
```

**Comment by steven-johnson** [comment]
You probably need to use `install_name_tool` to update the install name in the .dylib.

**Comment by huiyiqun** [comment]
I have no idea why but it seems that [this line](https://github.com/halide/Halide/blob/da8848dab4aca02ac260cb41b4339d199238a68f/halide.cmake#L608) is ignored on macos and when the generator is executed, the libHalide.dylib cannot be found and end up with an error.

If `install_name_tool` works, maybe we should call it automatically in `halide.cmake` or place it in `README_cmake.md`?

**Comment by steven-johnson** [comment]
What version of CMake are you using?

**Comment by LoveDaisy** [comment]
I'm not sure about Hui Yiqun's, but mine is 3.10.2.
Hui Yiqun's workaround works fine for me. And inspired by his reply I find
another workaround by placing a symbol link in /usr/local/bin/ pointing to
libHalide.dylib.

**Comment by tenomoto** [comment]
I'm trying to port halide to MacPorts. I have build error while building `test` because `cxx_mangling.generator_binary` points to `/opt/local/lib/libHalide.dylib` rather than `../lib/libHalide.dylib`. Unsetting `CMAKE_EXE_LINKER_FLAGS` didn't help. I am not allowed to install the library during the build process.
```
make[2]: Entering directory `/opt/local/var/macports/build/_Users_eno_MacPorts_ports_lang_halide/Halide/work/build'
cd /opt/local/var/macports/build/_Users_eno_MacPorts_ports_lang_halide/Halide/work/build/test && ../bin/cxx_mangling.generator_binary -e static_library,h -o /opt/local/var/macports/build/_Users_eno_MacPorts_ports_lang_halide/Halide/work/build/./genfiles/cxx_mangling -g cxx_mangling -f HalideTest::AnotherNamespace::cxx_mangling -x .s=.s.txt,.cpp=.generated.cpp target=host-c_plus_plus_name_mangling-no_runtime
dyld: Library not loaded: /opt/local/lib/libHalide.dylib
  Referenced from: /opt/local/var/macports/build/_Users_eno_MacPorts_ports_lang_halide/Halide/work/build/test/../bin/cxx_mangling.generator_binary
  Reason: image not found
```

**Comment by steven-johnson** [comment]
Unfortunately, I'm not sure what the right settings are for this task.
(FWIW, our regular build-test infrastructure uses Make rather than CMake on
OSX, so it's possible the CMake build is just slightly out of date.)
Perhaps some of the more CMake-savvy Halide users can offer suggestions
here.

**Comment by alexreinking** [comment]
Robust Apple support in CMake is a TODO in #4644
