### ISSUE TITLE
Image check assertions do not check dimensions.

### ISSUE THREAD

**Issue by zvookin** [halide/Halide#2831]
The assertions checks so not check dimensionality of input or output buffers. We do test for JIT in the call setup, but not in the generated code. See test here:
    https://gist.github.com/zvookin/3c907b36a27ccfc5e6ec9b245588131f

**Comment by zvookin** [comment]
(Copy the bad_dims_generator.cpp and bad_dims_aottest.cpp files into test/generator and "make generator_aot_bad_dims" to run.)

**Comment by zvookin** [comment]
Part of this may also have to do with legacy buffer_t support.

**Comment by steven-johnson** [comment]
https://github.com/halide/Halide/pull/2971
