### ISSUE TITLE
Build error in Linux OS

### ISSUE THREAD

**Issue by IshwaraK** [halide/Halide#2844]
Observing the below build error in Linux platform when used with cmake.

Halide-master/util/HalideTraceViz.cpp: In function ‘int {anonymous}::run(int, char**)’:
Halide-master/util/HalideTraceViz.cpp:497:53: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
                 if (config.strides.size() <= config.dims) config.strides.resize(config.dims+1, {0, 0});
                                                     ^
cc1plus: all warnings being treated as errors
make[2]: *** [util/CMakeFiles/HalideTraceViz.dir/HalideTraceViz.cpp.o] Error 1
make[1]: *** [util/CMakeFiles/HalideTraceViz.dir/all] Error 2
make: *** [all] Error 2

**Comment by steven-johnson** [comment]
We'd welcome a PR to fix this :-)
