### ISSUE TITLE
Update error when writing a conv_layer

### ISSUE THREAD

**Issue by FrancoisMoreau** [halide/Halide#2847]
Hi, 

I want to apply Halide to do calculation of Convolution. So, I refer the conv_layer in App, 
https://github.com/halide/Halide/blob/master/apps/conv_layer/conv_layer_generator.cpp

However, when I do the schedule part, for example, I set (Var)x vectorize value to 8, then when the convolution output blob is some kind of strange value(x=13, ex, the value that cannot be divided by 8), then it came out a error that the buffer is accessed beyond the max extent. 

I know this is because of the update procedure, but to make it as fast as possible, I cannot make the vectorize stride to be 1, so what should I do?
Is there any solutions?
Thank you.

**Comment by abadams** [comment]
You could try vectorize(x, 8, TailStrategy::RoundUp)

That should use predicated loads/stores in the last iteration instead of rounding up to a multiple of 8

**Comment by FrancoisMoreau** [comment]
Ok, I read the related documents of TailStrategy, it seems that Roundup/ShiftInward could solve the problems.

Thank you a lot.

**Comment by FrancoisMoreau** [comment]
Hi, @abadams , if I use auto_schedule, is there same operations as TailStrategy?

**Comment by abadams** [comment]
No, but if you give the concrete size you expect, I believe the
autoscheduler will try to do something reasonable. You can also use the
schedule that the autoscheduler produces and modify it by hand.

- Andrew

**Comment by FrancoisMoreau** [comment]
@abadams Thank you!
one last small question, when I apply generator, is there any way to set the CPU running Core numbers manually,  make the output library run for certain number of cores?

**Comment by abadams** [comment]
Not in the generator source (other than by making the parallel loop only have as many iterations as cores), but you can call halide_set_num_threads at runtime, or set the environment variable HL_NUM_THREADS.

**Comment by FrancoisMoreau** [comment]
ok, now I am quite clear with that. 
Thank you!
