### ISSUE TITLE
AVX-512 support?

### ISSUE THREAD

**Issue by oscarbg** [halide/Halide#2851]
new user here.. just can't find any info on AVX-512 support, it's supported already?
if not plans on implementing soon?

FYI from POCL devs I know LLVM mature AVX-512 support seems requires at least version 6.0

thanks..

**Comment by ashishUthama** [comment]
Looking at the [code](http://halide-lang.org/docs/struct_halide_1_1_target.html#a9398276edd5784185e1a08f8a4dfc43fa59e40bba2ff121dd95ed2420eb89e17b), there appears to be some support.

**Comment by edubois** [comment]
On AVX512 - skylake architecture we have some crashes when using the auto scheduler. Will try to make an example.

**Comment by abadams** [comment]
We had some alignment related avx512 bugs that were fixed a few months ago. Maybe it was that. In any case I'm successfully using the autoscheduler for avx512, so I think things should be good now. We still don't have an avx512 buildbot though.

**Comment by zvookin** [comment]
@oscarbg @edubois Is there anything still to be done here? I believe we have AVX-512 support that is generally useful. I believe both versions of the autoscheduler should work with it as well.)

**Comment by abadams** [comment]
We could still use a buildbot with avx 512.

**Comment by eloi-loomai** [comment]
I do not work with AVX512 anymore, I cannot tell, sorry.

**Comment by steven-johnson** [comment]
Definitely, since at least one of our apps (fft) is known to have failures
on avx512
