### ISSUE TITLE
slice buffer while preserving device memory layout

### ISSUE THREAD

**Issue by lzhangzz** [halide/Halide#2869]
Hi, 

I'm writing a lib that does image preprocessing for CNN (crop, resize, subtract mean values and construct 4D float tensor) using GPU. What I'm trying is to use a 4D buffer as output and slice the buffer into 3D slices so I can process each image independently (as they may differ in size) and store the result in the sliced buffers. However I found that when slicing a buffer, its device memory is released so an additional pass is needed to copy the sliced buffers into an single 4D buffer.

Is there a way to achieve what I'm trying without additional memory copy? like slice a buffer while preserving its memory layout? 

Thanks,
Li

**Comment by abadams** [comment]
The problem with slicing is that it requires offsetting the base pointer.
The device handles we have generally aren't things we can do pointer math
on (cuda is the exception), so we drop the device allocation in
Buffer::slice.

However there's a lower-level API that does what you want. If you use
halide_buffer_t directly, you can call halide_device_crop and then drop one
of the dimensions to take a slice.

- Andrew
