### ISSUE TITLE
bug:  and condition of print_when in python bindings

### ISSUE THREAD

**Issue by shockjiang** [halide/Halide#2889]
"and" does not work in python bindings:
   
```
 x = hl.Var('x')
 y = hl.Var('y')
 f = hl.Func('f')
 f[x, y] = hl.print_when(x == 0 and y == 0, 0, "x=",x, "y=", y)

f.realize(10,10)
```

when it outputed is:
0 x= 0 y= 0
0 x= 1 y= 0
0 x= 2 y= 0
0 x= 3 y= 0
0 x= 4 y= 0
0 x= 5 y= 0
0 x= 6 y= 0
0 x= 7 y= 0
0 x= 8 y= 0
0 x= 9 y= 0

**Comment by steven-johnson** [comment]
Unfortunately, this isn't fixable: there is no way to overload the `and` and `or` operators in Python. (Even worse, there doesn't appear to be a useful way to generate useful error messages if you use them; you just get weird results like this.) You need to use the bitwise `&` and `|` operators instead.

**Comment by abadams** [comment]
I believe "and" in python returns the first argument if it's falsey (e.g. None, 0, False), and the second argument if the first argument is truthy.

It's not possible to overload "and", but can we overload the truthiness check (__nonzero__) to throw an error?

**Comment by steven-johnson** [comment]
> can we overload the truthiness check

Maybe. I'll give it a try.

**Comment by steven-johnson** [comment]
patching `__nonzero__` and `__bool__` don't seem to address this; I can still do something like `assert (t1.bits() == 0) and (t1.lanes() == 0)` and never even get them called.

However, if I do something like 

```
b1 = hl.Bool()
assert b1.max() == 1
```

Then I *will* get that hook called with a failure:

`halide.Expr ((uint1)1 == (uint1)1) cannot be converted to bool.`

**Comment by abadams** [comment]
That all seems like the right behavior to me. t1.bits() and t1.lanes() are ints, so it should be possible to assert things about them at compile-time. b1.max() is an Expr, so b1.max() == 1 is also an Expr, so you want it to panic when you try to assert it (even though it's a constant-foldable Expr).

**Comment by steven-johnson** [comment]
>  t1.bits() and t1.lanes() are ints

Derp, right you are -- I thought they were Exprs.

**Comment by shockjiang** [comment]
according the above discussion, I got two pieces of information:
1/ bit wise & and | can be substitution of "and" "or" in python code
2/ hl.select(condition, ...,) also share the same issue.

Am I right?

**Comment by steven-johnson** [comment]
> 1/ bit wise & and | can be substitution of "and" "or" in python code

Well, yes, sorta; the gotcha is that they don't short-circuit evaluate in the same way as 'and'/'or'.

> 2/ hl.select(condition, ...,) also share the same issue.

I don't understand.

**Comment by shockjiang** [comment]
say:
` e = hl.select(x == 3 and y == 4, 1, 0)`

This should be rewrote to:
` e = hl.select(x == 3 & y == 4, 1, 0)`

**Comment by steven-johnson** [comment]
Correct.
