### ISSUE TITLE
does halide support dynamic input and multiple output?

### ISSUE THREAD

**Issue by codewdy** [halide/Halide#2891]
I'm trying use halide to optimize tensorflow.
I found two issue when using it.

1. dynamic input
I tried to change func's input buffer. But I cannot find any API about this.
I want some code like this:
```
Buffer<uint8_t> input = ...;
Func func;
func(x) = input(x);
func.realize(...);
input.set_buffer(new_buffer);
func.realize(...);

```

2. multiple output
And I found no way to get multiple output for different shape.
like this:
```
Func func0, func1, func2;
func0(x) = x;
func1(x) = func0(x);
func2(x, y) = func1(x + y);
FuncRealizer(func1, func2);
```

**Comment by abadams** [comment]
1) ImageParam is the class you're looking for
2) Pipeline is the class you're looking for: e.g. Pipeline(output1,
output2).realize(...)

You could also just skip straight to the tutorial on Generators, which have
explicit Input and Output members.
