### ISSUE TITLE
fuzz_simplifier error

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2895]
Unrelated tests came up with a new random error in fuzz_simplify for seed=1523912241:

$ ./correctness_fuzz_simplify 1523912241
Simplify fuzz test seed: 1523912241
a = int32(d)
b = int32(d)
c = -36
d = int32(d)
e = int32(a)
max((((int32(c)*-85) - 70)/3), (-21/int32(c)))
max((((int32(c)*85) + 70)/-3), (-21/int32(c)))
In vector lane 0:
max((((int32(c)*-85) - 70)/3), (-21/int32(c))) -> 996
max((((int32(c)*85) + 70)/-3), (-21/int32(c))) -> 997

**Comment by dsharletg** [comment]
fuzz_simplify with this seed is passing now (but maybe the RNG/expression generation changed since this bug was reported...).
