### ISSUE TITLE
Building apps/fft fails when trace_realizations is enabled

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2898]
$ HL_TARGET=host-trace_loads-trace_stores-trace_realizations make fft_aot_test

Internal error at /path/to/IR.cpp:599
Condition failed: 0 <= i && i < input_lanes
Shuffle vector index out of range: 4

**Comment by steven-johnson** [comment]
So do apps/interpolate and apps/lens_blur

**Comment by dsharletg** [comment]
This doesn't seem to be happening any more.
