### ISSUE TITLE
Release Halide 2018/02/15 src.zip fails to CMake with instructions on Win

### ISSUE THREAD

**Issue by hypernewbie** [halide/Halide#2922]
I built Windows LLVM. CMake fails with:

```
Found LLVM 5.0.0
Using LLVMConfig.cmake in: C:/code/llvm-5.0.0.src/build/lib/cmake/llvm
Windows: setting CMAKE_OBJECT_PATH_MAX to 260
CMake Warning at CMakeLists.txt:81 (message):
  'llvm-config --system-libs --link-static' is empty; this is possibly wrong.


CMake Error at CMakeLists.txt:98 (message):
  Tool llvm-as not found at
  C:/code/llvm-5.0.0.src/build/$(Configuration)/bin/llvm-as.exe
Call Stack (most recent call first):
  CMakeLists.txt:104 (check_tool_exists)


Configuring incomplete, errors occurred!
See also "C:/code/halide_src/build/CMakeFiles/CMakeOutput.log".
See also "C:/code/halide_src/build/CMakeFiles/CMakeError.log".
```

**Comment by hypernewbie** [comment]
C:/code/llvm-5.0.0.src/build/Release/bin/llvm-as.exe exists on the system.

**Comment by hypernewbie** [comment]
My config:
![cfg](https://user-images.githubusercontent.com/5387547/39329701-06a605f8-4954-11e8-88c3-314ffe424e05.png)

**Comment by www571859177** [comment]
I have the same problem, it shows that:
'llvm-config --system-libs' is empty; this is probably wrong.
do you solve this problem? I have no idea how to deal with it?
my wechat number is 'w_shiguang',

**Comment by alexreinking** [comment]
Closing since LLVM5 is no longer supported. If you still can't build Halide, please open a new issue.
