### ISSUE TITLE
Error at apps/linear_algebra/benchmarks/CMakeLists.txt:41 (add_executable):   Target "eigen_benchmarks" links to target "Eigen3::Eigen" but the target   was not found.

### ISSUE THREAD

**Issue by TolgaAktas** [halide/Halide#2942]
Getting the following error when I try to build with CMake:

CMake Error at apps/linear_algebra/benchmarks/CMakeLists.txt:41 (add_executable):
  Target "eigen_benchmarks" links to target "Eigen3::Eigen" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at apps/linear_algebra/benchmarks/CMakeLists.txt:41 (add_executable):
  Target "eigen_benchmarks" links to target "Eigen3::Eigen" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

**Comment by lilililijqa** [comment]
Hi, I have the same problem as you. How do you solve it?
Thank you!

**Comment by alexreinking** [comment]
This will be fixed by #4644 once #4631 is resolved.
