### ISSUE TITLE
LLVM 6.0.0 build instructions missing dependencies

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#2946]
When following the build directions in `README.md`, it is assumed that the development headers for libxml2 are installed. On Ubuntu, this entails installing the package `libxml2-dev` via

```
sudo apt install libxml2-dev
```

Additionally, it was necessary to explicitly point cmake to the LibXml2 directories with `-DLIBXML2_LIBRARIES=/usr/lib/x86_64-linux-gnu/libxml2.so -DLIBXML2_INCLUDE_DIR=/usr/include/libxml2/` since it detects the system as `x86_64-unknown-linux-gnu`, while the libxml2 libraries are installed by Ubuntu into `/usr/lib/x86_64-linux-gnu` (without the `unknown`)

This is on Ubuntu 16.04 running on WSL using GCC/G++ 8.0.1, cmake 3.5.1 and compiling LLVM 6.0.0

**Comment by asaadaldien** [comment]
libxml2 is required by LLVM libs. If you are building LLVM from source you can do:  
`-DLLVM_ENABLE_LIBXML2=OFF` then build `libHalide.so`
