### ISSUE TITLE
predicated vector store can overread

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2958]
Given a pipeline like:
```
    constexpr int vector_size = 4;
    constexpr int lut_height = vector_size + 2; // Any non-even multiple of vector-size will do.
    constexpr int dst_len = 100; // arbitrary

    Buffer<int32_t> lut(2, lut_height);
    lut.fill(0);  // arbitrary contents

    RDom r(0, lut_height);

    Var j;
    Func dst;
    dst(j) = 0.f;
    dst(clamp(lut(0, r), 0, dst_len - 1)) += 1.f;

    // This isn't necessary but makes output more readable
    dst.output_buffer().dim(0).set_min(0).set_extent(dst_len);

    dst.update(0).allow_race_conditions().vectorize(r, vector_size);

    Buffer<float> dst_buf = dst.realize(dst_len);  // ASAN will flag an overread here
```

We'll end up with IR like:

```
    dst[max(min(lut[ramp(0, 2, 4)], x4(99)), x4(0))] = (dst[max(min(lut[ramp(0, 2, 4)], x4(99)), x4(0))] + x4(1.000000f))
    if ((x4(4) < ramp(6, -1, 4))) {
      dst[max(min(lut[ramp(8, 2, 4)], x4(99)), x4(0))] = (let t11 = (x4(4) < ramp(6, -1, 4)) in ((dst[max(min((lut[ramp(8, 2, 4)] if t11), x4(99)), x4(0))] if t11) + x4(1.000000f)))
    }
```

The gotcha here is that while the lut-lookup inside the RHS is guarded with `if`, the lut-lookup inside the LHS is not. This means that we'll overread the final section of the buffer (by two in this case); for external buffers, this is a nontrivial failure since the memory may not be valid (and this will definitely get flagged by ASAN, etc).

Not sure of the right fix yet; I think the issue is that the predicate gets lost when VectorizeLoops adds an IfThenElse to wrap the predicated store, but not sure of the proper fix yet.

**Comment by abadams** [comment]
Ugh, that print is misleading. If it was an "if" statement it would be correct to leave off the condition on the inner loads, but it's not, it's a store predicate. We should have made the predicate on Stores print differently to a nested if - the meaning is different (the value and index are unconditionally evaluated).

**Comment by steven-johnson** [comment]
That print syntax was just changed to look more like a nested if. Easy enough to change it back, but the syntax we used before just tacked the "if" onto the end, making it easy to overlook.

**Comment by steven-johnson** [comment]
(Taking the liberty of assigning to psuriana@ since she originally added predicated load/store IIRC)

**Comment by psuriana** [comment]
Fixed
