### ISSUE TITLE
Internal error at src/Generator.cpp:1556

### ISSUE THREAD

**Issue by matthiaskramm** [halide/Halide#2977]
I'm at d396f6b88a1c93343d00b6aebc697c753961bb4c. 

I'm trying to run one of the generators in `python_bindings/correctness` directly, like this:

```
d python_bindings
cat >> Makefile
$(BIN)/%.gen: correctness/%_generator.cpp ../tools/GenGen.cpp $(LIBHALIDE)
        @mkdir -p $(@D)
        $(CXX) $^ $(CCFLAGS) $(LDFLAGS) -fno-rtti -o $@
[ctrl-d]
make `pwd`/bin/simplestub.gen
```

(Also see https://github.com/halide/Halide/issues/2976 regarding `-fno-rtti`.)

Now, running

```
bin/simplestub.gen -g simplestub target=host -o bin/
```

gives:

```
Internal error at /usr/local/google/home/kramm/src/Halide/src/Generator.cpp:1556
Condition failed: funcs_.size() == array_size() && exprs_.empty()
Aborted
```

Removing the following line in `python_bindings/correctness/simplestub_generator.cpp`

```
Input<Func> func_input{ "func_input", 2 };
```

and its references makes the error go away.

**Comment by steven-johnson** [comment]
This is not a bug (but is a terrible error message): you are running the Generator, which (by default) is trying to generate object code; to do this, any `Input<Func>` must have a concrete type associated with it. I will fix the code to generate a useful error.

**Comment by matthiaskramm** [comment]
Ah! That makes sense.

I can confirm that running the generator as

```
bin/simplestub.gen -g simplestub -e h -o bin/ target=host func_input.type=uint8
```

makes the problem go away.
