### ISSUE TITLE
dead code elimination

### ISSUE THREAD

**Issue by ronghongbo** [halide/Halide#3005]
Hello,

Just want to confirm: Halide does not have a DCE pass on the IR, but fully rely on the LLVM backend. Is this right? This is OK. I just want to make sure.

Thanks,
Hongbo

**Comment by abadams** [comment]
We don't have an DCE explicit pass, but the simplifier does cull things like if (false) {}, or for loops with zero extent. I don't think there should be any dead code left by the time we generate LLVM IR.
