### ISSUE TITLE
A code that crashes, seems like a malloc/free bug inside halide

### ISSUE THREAD

**Issue by edubois** [halide/Halide#3013]
Hi,

I am experiencing a very annoying problem, I have the code that follows. When I set vecIn to be 256, it works, but when I change to 256*256, it crashes (kSizeBug). My halide version is the current master.

clang version 7.0.0 (https://github.com/llvm-mirror/clang.git 05425db7451f40258ae829c3d5d443b33b5d4c15) (https://github.com/llvm-mirror/llvm.git 22634021a1589801e2f5142132183b134f682d1d)
Target: x86_64-apple-darwin15.6.0
Thread model: posix

LLVM (http://llvm.org/):
  LLVM version 7.0.0svn
  Optimized build with assertions.
  Default target: x86_64-apple-darwin15.6.0
  Host CPU: ivybridge

Main:
```
BOOST_AUTO_TEST_CASE( check_crash )
{
    using namespace Halide;

    constexpr int S = 10;
    constexpr int Z = 5;
    constexpr std::size_t kSizeBug = 256*256; // Change this to 256 makes it working
    std::vector<float> vecIn(kSizeBug);
    for(std::size_t i = 0; i < vecIn.size(); ++i)
    {
        vecIn[i] = i;
    }
    auto target = get_host_target();
    Buffer<float> bufIn(&vecIn[0], vecIn.size());
    bufIn.set_name("bufIn");
    Var x("x");
    Func fIn("fIn");
    fIn(x) = bufIn(x);
    Func vBar = crash(fIn, fIn, vecIn.size(), S, Z);
    const int kSizeOut = (S + 1)*(vecIn.size() - S / 2) + S * Z;
    std::cout << "Executing (" << kSizeOut << " bytes)" << std::endl;
    Buffer<float> result = vBar.realize(kSizeOut, target);
    std::cout << "Done." << std::endl;
    vBar.compile_to_lowered_stmt("fun.txt", std::vector<Argument>());
}

```

Here is the crashing function:

```
Halide::Func crash(Halide::Func inputRef, Halide::Func inputOther, const int N, const int S, const int Z)
{
    using namespace Halide;

    const int sizeOut = (S + 1) * (N - S / 2) + S * Z;
    const int maxU = S + 1;
    RDom vu(1, N - S - 1 + maxU, 1, S + 1);
    vu.where(vu.x <= (N - S - 1 + vu.y));
    Func vTmp("vTmp");
    Var x("x");
    vTmp(x) = 0.0f;
    Expr i = S + 1 - vu.y + vu.x;
    Expr j = vu.x;
    Expr lij = clamp(cast<int>(0.5f * (S - i + j) * (2 * N + 2 * Z - S - 1 - i + j) + j - 1), 0, sizeOut - 1);
    vTmp(lij) += inputRef(clamp(S + 1 - vu.y + vu.x - 1, 0, N - 1)) * inputOther(clamp(vu.x - 1, 0, N - 1));

    RDom kx(-Z, 2 * Z + 1);
    Func v("v");
    v(x) = cast<float>(sum(vTmp(clamp(x + kx.x, 0, sizeOut - 1))));
    v.bound(x, 0, sizeOut);
    return v;
}
```
Attached is the human readable generated code.

Sys error is:
unit_test(97354,0x7fff7479c000) malloc: *** error for object 0x7fd7dc2b0c78: incorrect checksum for freed object - object was probably modified after being freed.

[fun.txt](https://github.com/halide/Halide/files/2064496/fun.txt)

**Comment by edubois** [comment]
Ok, it seems that by adding:
    vTmp.bound(x, 0, sizeOut);
the problem goes away.

Now, when I try to auto-schedule the function, it says:
`cannot auto-schedule function "v" since it has partially specified bounds.
`
What does that means exactly?

**Comment by ashishUthama** [comment]
vTmp gets allocated/freed inside the for loop, so I dont think that's
whats causing the crash.
Do you get any bounds access violation errors?

**Comment by edubois** [comment]
I'm not sure, but changing:
`Expr lij = clamp(cast<int>(0.5f * (S - i + j) * (2 * N + 2 * Z - S - 1 - i + j) + j - 1), 0, sizeOut - 1);
`
to

`Expr lij = cast<int>(clamp(Expr(0.5) * (S - i + j) * (2 * N + 2 * Z - S - 1 - i + j) + j - 1, 0, sizeOut - 1));`

Made it working.
When looking at the code, I'm not sure I understand why there is a float overflow.

**Comment by steven-johnson** [comment]
I'm going to close this; please reopen if it still needs attention.
