### ISSUE TITLE
dot product operator

### ISSUE THREAD

**Issue by ronghongbo** [halide/Halide#3014]
Hello,

For two variables a and b, if they are small vectors like 8 floats, a*b seems to return a vector of 8 floats as well. Is there an operator that can do a dot product with a and b and return a float number instead?

Thanks,
Hongbo

**Comment by abadams** [comment]
The front-end language doesn't have explicit vector types, so I assume (based on your other questions) that you're working directly with the low-level IR.

The answer is no - we don't have any horizontal vector ops in the IR. It's typically represented as a vector store to an 8-entry allocation and then operations that load scalar elements from that allocation and sum them. You'd think this would make it hard to peephole match to dot-product instructions, but fortunately most of those only reduce by a constant factor (e.g. pmaddwd on x86 reduces pairs of lanes), and we have other ways to pattern match those.

**Comment by dsharletg** [comment]
We do now have `VectorReduce` as an IR node to do this kind of operation.
