### ISSUE TITLE
Scheduling on ARM/Neon

### ISSUE THREAD

**Issue by shipingli** [halide/Halide#3022]
Is there any special request or syntax or suggestions on optimizing and scheduling code running on ARM/Neon?  Is there any good example for it?

Thanks

**Comment by abadams** [comment]
Scheduling for arm neon is the same as for x86. I'd vectorize at least 128-bits wide though. When writing 32-bit neon by hand you can play games with aliasing the d and q registers, but llvm is not great at doing that, so better to avoid the 64-bit vector types (d registers).

**Comment by shipingli** [comment]
@abadams Thanks, sounds like a good start point.
