### ISSUE TITLE
Generating vmull.u8 + vaddw.u16 instead of vmovl.u8 + vmlal.u16

### ISSUE THREAD

**Issue by mohamedadaly** [halide/Halide#3024]
I am trying to multiply+accumulate uint8 values into uint32 accumulators:
```c++
f(x, y) = u32(0);
f(x, y) += u16(a(x, r)) * b(r, y);
```

I am trying to get the generated code to multiply the uin8 values of `a` and `b` using `vmull.u8` to produce uint16, which is then added to the uint32 accumulator using `vaddw.u16`, something like this:
```assembly
	vmull.u8 q0, d2, d3
	vaddw.u16 q4, q4, d0
	vaddw.u16 q5, q5, d1
```

However, the code I get first extends the uint8 values to uint16 and then uses `vmlal.u16` to update the accumulators:
```assembly
	vmovl.u8	q11, d20
	vmovl.u8	q9, d18
	vmlal.u16	q6, d23, d19
	vmlal.u16	q8, d22, d18
```

What's the best approach to match that pattern and force LLVM to generate the former sequence of instructions instead of the latter?

Thanks a lot!

**Comment by abadams** [comment]
It would be the same approach you took with vmlal. First find the llvm codegen test that generates vaddw, then see how the Halide-produced .ll doesn't look like that. From that point we can add code in the arm backend to generate better llvm ir, or a new wrapper intrinsic in the arm runtime .ll file.

**Comment by mohamedadaly** [comment]
It turns out it could be done in an easier way, by taking the product of `a` and `b` into its own `Func` and `compute_at` it at the correct location before being consumed by `f`. 

Thanks for your help!
