### ISSUE TITLE
Calls to Call::abs should preserve type, but doesn't

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3031]
In theory, Call::abs should enforce that the Type of the result is the same as the Type of the first argument; this is not enforced, and as a result, we have various misuses of it inside Halide; the ones I've seen have been of the uint-vs-int-of-same-size variety, but there might be others.

**Comment by steven-johnson** [comment]
In that case, the simplifier probably needs to ensure it does the correct casting operation across all transformations.

**Comment by abadams** [comment]
Yeah - for abs it's intentional that it changes the type: https://github.com/halide/Halide/blob/master/src/IROperator.h#L844

**Comment by steven-johnson** [comment]
Ouch. OK then. In that case the issue should probably be "Simplifier needs to ensure it preserves type across all mutations". Closing this one.

**Comment by abadams** [comment]
Agreed. Added such an assert in #2845
