### ISSUE TITLE
Calling crop on a buffer has a persistent behavior

### ISSUE THREAD

**Issue by slomp** [halide/Halide#3032]
Let's say one wants to load an image, crop some borders around it, do some processing, and then save the processed image with the cropped border included.

Something like this demonstrates the issue:
```
Halide::Buffer<uint8_t> Process(Halide::Buffer<uint8_t> image)
{
    const int width  = image.width();
    const int height = image.height();
    const int hBorder = 16;
    const int vBorder = 16;
    image.crop(0, hBorder,  width - 2 * hBorder);
    image.crop(1, vBorder, height - 2 * vBorder);
    // no-op processing: do nothing, just crop.
    return(image);
}

int main()
{
    Halide::Buffer<uint8_t> image = Halide::Runtime::Buffer<uint8_t, 3>::make_interleaved(512, 512, 3);
    auto widthBefore  = image.width();
    auto heightBefore = image.height();
    printf("before: %d x %d\n", widthBefore, heightBefore);
    Process(image);     // <- will .crop() the image
    auto widthAfter  = image.width();
    auto heightAfter = image.height();
    printf("after:  %d x %d\n", widthAfter, heightAfter);
    assert(widthBefore  == widthAfter );
    assert(heightBefore == heightAfter);
    return(0);
}
```

The snipped above will output:
```
before: 512 x 512
after:  480 x 480
```

The expected output is:
```
before: 512 x 512
after:  512 x 512
```

This is based on [master] branch (commit cc65b9961cb4f5f9ad76c04b0082698557af6681).

**Comment by abadams** [comment]
A Halide::Buffer acts like a ```shared_ptr<Halide::Runtime::Buffer>```. It's confusing, but the buffer classes serve many masters and this is the best we could do at the time. If you pass around Halide::Runtime::Buffer I think you'll get the behavior you expect.

**Comment by slomp** [comment]
IIRC, I should call `Halide::Buffer<>::get()` to obtain the underlying `Halide::Runtime::Buffer<>` and pass it by value to `Process()`:

```
Halide::Buffer<uint8_t> Process(Halide::Runtime::Buffer<uint8_t> image)
{
    ...
}

int main()
{
    ...
    Process(*image.get());
    ...
}
```

**Comment by steven-johnson** [comment]
Yes -- your example is (unfortunately) somewhat counterintuitive but really is WAI. (Leaving open for now for further discussion.)

**Comment by slomp** [comment]
Thank you for the feedback. It's all good now.

I agree that a `cropped()` method that returns the cropped buffer would be perhaps more intuitive.

**Comment by abadams** [comment]
It's not a hypothetical addition: Halide::Runtime::Buffer has that method. Looks like it's not forwarded through to Halide::Buffer though. Perhaps because it was hard to support device allocations at the time?
