### ISSUE TITLE
Not able to install LLVM

### ISSUE THREAD

**Issue by rajeshk7** [halide/Halide#3049]
Ubuntu 16.04

I am following the README and firstly i was trying to install llvm. 
1.Issues in cmake: All the cases weren't successful, some of them failed. 
2.Issues in make: It runs for an hour and reaches 82% and afterwards it fails. In between it says Virtual Memory Exhausted : cannot allocate memory. Waiting for unfinished job. 
 
![screenshot from 2018-06-12 16-44-47](https://user-images.githubusercontent.com/30970253/41287576-cb377ca4-6e60-11e8-810f-bca7684f9105.png)

**Comment by Naville** [comment]
``
In between it says Virtual Memory 
``
That's why. Check your RAM && HDD usage

**Comment by alexreinking** [comment]
We're not able to support failures in LLVM builds, though it sounds like the issue is with your hard drive space, anyway.
