### ISSUE TITLE
"The Buffers in a realization passed to realize must all be allocated" and GPU

### ISSUE THREAD

**Issue by 9cvele3** [halide/Halide#3060]
I am trying to integrate GPU image filters written in Halide with my existing application for image processing. In my application, I already have logic that copies data from CPU to GPU and back when needed, so when I need new image filter, only kernel is written. Recently I had problem with creating Halide::Buffer with data that is already on the GPU. Thanks to @abadams 's answer on [Stackoverflow](https://stackoverflow.com/questions/50822087/halidebuffer-on-gpu), I was able to circumvent this problem by:
```
Halide::Buffer<float> buff(nullptr, ...);
buff.device_wrap_native(Halide::DeviceAPI::CUDA, (uintptr_t) gpuPtr, ...);
```
Now when I look my exe in nvvp, I see that copy from CPU to GPU is done only once, and it is done by my existing engine, not Halide code, which is great. 

However, a there is a new problem. I want to call realize and to keep the result on the GPU so that my existing app can copy it back to CPU when needed. I tried a few approaches, but none gave expected results. 
With:
```
Halide::Buffer<float> output(in.width(), in.height());
func.realize(output)
```
I see in nvvp, that after the kernel is finished, output is allocated on CPU, than copied to GPU, then filled up with result, and then copied back to CPU. I don't need any allocation on the CPU, my app will handle that itself, so I tried with:
```
Halide::Buffer<float> output(nullptr, ...);
output.device_wrap_native(Halide::DeviceAPI::CUDA, (uintptr_t) gpuPtrForResult, ...);
func.realize(output);
```
I get error "The Buffers in a realization passed to realize must all be allocated".

I have read in the docs that 
`void realize(Realization dst, const Target &target = Target(), const ParamMap &param_map = ParamMap());`
doesn't copy data back to the CPU, while other realize overloads do.

So, can I keep the result of a pipeline on the GPU, in a GPU buffer that I already allocated, without any unnecessary CPU allocations and coping?

**Comment by abadams** [comment]
I think the check is just overzealous, and nobody has tried to use JIT combined with device-only allocations before. I opened #3063 to relax the test.
