### ISSUE TITLE
Has Differentiable Programming been supported in latest code?

### ISSUE THREAD

**Issue by QiJune** [halide/Halide#3071]
It's very exciting to see this work, [Differentiable Programming for Image Processing and Deep Learning in Halide](https://people.csail.mit.edu/tzumao/gradient_halide/gradient_halide.pdf). Could we try the Differentiable Programming feature in the latest code? Thanks!

**Comment by abadams** [comment]
Those features aren't in this Halide repo yet. I'll tag the first author who can let us know what his plans for upstreaming are @BachiLi

**Comment by BachiLi** [comment]
The plan is to have a version 0 upstreamed before siggraph (mid August).

**Comment by masahi** [comment]
@BachiLi Any update? Looking forward to this feature!

**Comment by abadams** [comment]
I'm working on a PR for the core feature. I plan to have it open by Thursday.

**Comment by BachiLi** [comment]
Hey,
The pull request is here: https://github.com/halide/Halide/pull/3220
Meanwhile you can checkout our branch which contains more features mentioned in the paper:
https://github.com/jrk/gradient-halide

**Comment by masahi** [comment]
@BachiLi Thanks! looks cool.

Is 'a Pytorch backend for Halide' mentioned in the paper going to be made public as well?

**Comment by BachiLi** [comment]
The code is already in the gradient-halide branch but there's no documentation yet.
I will come up with a quick example in a few days.

**Comment by masahi** [comment]
Found the code in the repo, thanks.

**Comment by abadams** [comment]
This has finally been merged into master.
