### ISSUE TITLE
MSVC - creating custom CUDA runtime

### ISSUE THREAD

**Issue by 9cvele3** [halide/Halide#3072]
I am trying to define custom Halide CUDA runtime in Visual Studio 2015. I need it because I don't want Halide to create separate CUDA context and similar stuff, I want to use an existing one. All I want from Halide is to generate a kernel that I can call. I tried to define my own _halide_cuda_initialize_kernels_ and _halide_cuda_run_ functions, but when I run gradient CUDA example with debug, I can see in the output in console that default functions from cuda.cpp are called instead. What should I do to make this working?
 ```
//main.cpp
 #include "Halide.h"
 #include "HalideRuntimeCuda.h"

 extern "C" 
 {
 
     int halide_cuda_initialize_kernels(void *user_context, void **state_ptr,
               const char *src, int size)
     {
         //my code goes here
     }
 
     int halide_cuda_run(void *user_context,
         void *state_ptr,
         const char *entry_name,
         int blocksX, int blocksY, int blocksZ,
         int threadsX, int threadsY, int threadsZ,
         int shared_mem_bytes,
         size_t arg_sizes[],
         void *args[],
         int8_t arg_is_buffer[],
         int num_attributes,
         float* vertex_buffer,
         int num_coords_dim0,
         int num_coords_dim1)
     {
           //my code goes here
     }
 }
 void main()
 {
     std::cout << "gradient example" << std::endl;
     Halide::Func gradient{ "gradient" };
     Halide::Var x{ "x" }, y{ "y" }, xi{ "xInner" }, yi{ "yInner" };
     gradient(x, y) = 0.1f * (x + y);
     gradient.gpu_tile(x, y, xi, yi, 32, 8);
     auto target = Halide::get_host_target();
     target.set_feature(Halide::Target::CUDA);
     target.set_feature(Halide::Target::Debug);
     auto output = gradient.realize(300, 300, target);
 }
```

**Comment by shoaibkamil** [comment]
Someone with more Windows experience may have a better answer, but AFAICT msvc [does not support weak linking](https://stackoverflow.com/questions/2290587/gcc-style-weak-linking-in-visual-studio), which is how one would override these functions.

**Comment by MDBrothers** [comment]
What I had to do on Windows was copy the Halide runtime, remove all the weak leaking stuff, and change all the functions to meet our requirements.

**Comment by 9cvele3** [comment]
What worked for me is to change cuda.cpp directly and build Halide from source. Maybe there is a easier way, something like @MDBrothers  proposed, but this is the only way I got it to work.

Also, some documentation on creating custom runtime would be nice.

**Comment by ashishUthama** [comment]
Is there a better way than modifying cuda.cpp now? 
(Doing that would prevent the use of released binaries for one.)
