### ISSUE TITLE
Internal error -> Symbol not found: inputImage.extent.2

### ISSUE THREAD

**Issue by Gobra** [halide/Halide#3073]
I've been trying to find a solution for this issue for two days now. I'm running Halide with MS Visual Studio 2017 on WIn10 x64 and JIT-compilation.

The code is pretty basic and is actually taken from some entry-level tutorial, adding my app-side `bitmap` object to load image:
```
std::vector<int> sizes = { bitmap.width(), bitmap.height()  };
auto input = Halide::Buffer<uint8_t>(bitmap.bits(), sizes, "inputImage" );

Halide::Func brighter;
Halide::Var x, y, c;
Halide::Expr value = input(x, y, c);

value = Halide::cast<float>(value);
value = value * 1.5f;
value = Halide::min(value, 255.0f);
value = Halide::cast<uint8_t>(value);
brighter(x, y, c) = value;

Halide::Buffer<uint8_t> output = brighter.realize(input.width(), input.height(), input.channels());
```

At the last line during `realize` call the app is aborted and I get the following:
`Internal error at src\codegen_llvm.cpp:1158 Symbol not found: inputImage.extent.2`

I have tried a bit different pipeline without input buffer where it's simply `brighter(x, y, c) = 0;`. That one worked.

LLVM and Halide are both compiled on my machine with MSVC2017. I have tried LLVM 6.0 and 5.0, Halide tagged as release `2018_02_15` and the fresh `master`.

Is it a kind of bug or am I missing something obvious here?
Also, on Windows it's hard to get even that error message as error text isn't in the MSVC output panel, I had to compile Debug version, load .pdb and get it from the Halide's internals.

**Comment by abadams** [comment]
Sounds like a missing error message. You input buffer is two-dimensional (width, height), but you're accessing it as if it were three-dimensional (x, y, c). You may want to initialize the buffer as (width, height, 3) or something.

**Comment by abadams** [comment]
(I'd still consider this a bug in Halide, but the bug is that we're not properly validating a dimensionality)

**Comment by Gobra** [comment]
Thanks a lot, adding channel dimension helped indeed, forgot that part.

By the way, I found my instance of Halide compiled without exceptions support - is there a special build flag for CMake to have exceptions working? As without debug version and .pdb loaded all I got was "App has been aborted" due to the direct `abort()` call at `src\Error.cpp:30`.

**Comment by steven-johnson** [comment]
Are you using current Halide master? We weren't validating dimensionality of halide_buffer_t arguments at all until a week or so ago (https://github.com/halide/Halide/pull/2971). If you have that integrated and it's not checking, that's a bug.

(We still don't validate for legacy buffer_t, but presumably you aren't using those.)

**Comment by Gobra** [comment]
I've grabbed the latest master and re-compiled, it was the same. But I grabbed it via Git's interface as zipped source so I can't check `git log` right away.

Should it be important I can grab a copy through git, checkout master and try again.

**Comment by steven-johnson** [comment]
Relevant: I was wondering why we weren't assert-failing from calling `channels()` on a 2D Buffer. Turns out that the definition is

```
    int channels() const {
        return (dimensions() > 2) ? dim(2).extent() : 1;
    }
```

... which seems like a misfeature to me; IMHO `width()/height()/channels()` should assert-fail in the same way that calling `dim()` should.

**Comment by abadams** [comment]
This is a dimensionality mismatch on an embedded buffer, which causes a problem before we get a chance to runtime-fail.
