### ISSUE TITLE
An error for multiple pipeline outputs with an external function 

### ISSUE THREAD

**Issue by liwchang** [halide/Halide#3078]
From daily build, win64

If any output is immediately from external, and there is another output consuming it.
Two are in the same pipeline.
It will trigger a Halide error. 
“Internal error at c:\build_bot\worker\win-64-distro-trunk\halide\src\Scope.h:128
Name not in Scope:”

Example:
Func external = ...
Func another;
another(x) = external(x) + 1.0f;
Pipeline({external , another });

**Comment by abadams** [comment]
Thanks for the bug report, fixing it now.
