### ISSUE TITLE
Autoscheduled pipeline accesses output buffer out of bounds

### ISSUE THREAD

**Issue by SanderVocke** [halide/Halide#3103]
Sorry, yet another case where I don't have a minimal example handy. I can make one, and I will if you need it - but as it would take some time I would like to hear your thoughts on this first. Maybe there is something wrong with my approach or a workaround I hadn't thought of yet.

At runtime, I am getting the following error from an auto-scheduled pipeline:

```
Error: Output buffer f2 is accessed at -2, which is before the min (0) in dimension 2
```

In this pipeline `f2` is the only output.

The autoscheduler applied several splits and vectorizations on the output loop, so this is likely a case of one of those splits going out of bounds. Indeed, in the schedule I don't see any mentions of explicit tail strategies (`GuardWithIf` is my usual fix for these things).

Is this a bug? I would expect an autoscheduled pipeline to work with any output size I give it (because how am I supposed to know what size constraints appeared as a result of a particular auto-schedule?)

Or is the correct usage to always use a bounds query to figure out correct output sizes? Is it guaranteed that if I do a bounds query, then update the output size to be bigger, that it won't just fail again because the updated output size again causes another split to go out of bounds?

Note that my output size estimates happen to be multiples of 8 - but I didn't expect the autoscheduler to make the assumption that this property will always hold. Also, adding 1 to the estimates so that they don't divide cleanly by 8 doesn't solve the issue.

Eager to hear your thoughts - if you do think this is a bug I will try to make a minimal example.

EDIT: I dug a little deeper, and found that this has nothing to do with alignment: I had set an estimate of 100 on one of the dimensions, and the resulting pipeline turns out to have a constraint that this dimension may not be less than 32. (the failing condition is that `output.min.2 <= ((output.min.2 + output.extent.2) + -32)`.
Setting the estimate to 30 worked around the issue, but it doesn't feel right: I still want the scheduler to optimize for 100.
Can I prevent the autoscheduler from "inventing" such constraints?

**Comment by abadams** [comment]
The autoscheduler schedules assuming the image will be at least as large as
the estimates given, so it shouldn't do that if the estimates are
conservatively set. For smaller images, yeah, use bounds queries to figure
out the minimum output size. You can also take the schedule output by the
autoscheduler and add some specializations to it for smaller images. For
bounds queries, in the general case you need to iterate until convergence,
but unless you write something really weird, you should only need to do one
call.

**Comment by SanderVocke** [comment]
Thanks for the clarification.
