### ISSUE TITLE
Vectorizing pow() with float(64) causes a segfault

### ISSUE THREAD

**Issue by zanbri** [halide/Halide#3107]
I have written a generator which uses pow() on doubles. While no error occurs with the default scheduling, I have seen that applying vectorize() on the Func can lead to invalid reads (detected in Valgrind). 

The documentation states that clean vectorization is achievable with float(32) but doesn't seem to mention whether it is possible with doubles:

>   For Float(32), cleanly vectorizable, and accurate up to the last few bits of the mantissa. Gets worse when approaching overflow. Vectorizes cleanly. 

Is this known behavior? Is there a workaround to customize the scheduling of Funcs which use pow() with doubles?

**Comment by abadams** [comment]
If you can post a small repro I'll take a look

**Comment by zanbri** [comment]
The problem occurs when the output of the generator (which contains the pow()) is used in further calculations. Without wanting to post my entire pipeline, I'll see if I can produce a smaller toy example exhibiting the same behavior.

**Comment by zanbri** [comment]
You can find the repo here: https://github.com/zanbri/Pow_Test

Actions to see the error:
```
> cd src/pow_test/
> make clean && make
> valgrind --track-origins=yes ./pow_test_test
```

The output I get:
```
==17250== HEAP SUMMARY:
==17250==     in use at exit: 1,142,909 bytes in 6,345 blocks
==17250==   total heap usage: 66,818 allocs, 60,473 frees, 9,381,591 bytes allocated
==17250== 
==17250== LEAK SUMMARY:
==17250==    definitely lost: 1,709 bytes in 3 blocks
==17250==    indirectly lost: 0 bytes in 0 blocks
==17250==      possibly lost: 0 bytes in 0 blocks
==17250==    still reachable: 1,141,200 bytes in 6,342 blocks
==17250==         suppressed: 0 bytes in 0 blocks
==17250== Rerun with --leak-check=full to see details of leaked memory
==17250== 
==17250== For counts of detected and suppressed errors, rerun with: -v
==17250== ERROR SUMMARY: 2720 errors from 205 contexts (suppressed: 0 from 0)
```

**Comment by zanbri** [comment]
To get rid of the error, you can comment out
```
E.parallel(x);                                                                                  
E.vectorize(y, 16);
```

from `include/PowFunc.h`

**Comment by zanbri** [comment]
I simplified the repo further while still getting the same error. Now the lines of code to comment out (to get rid of the error) are in `src/pow_test/pow_test_generator.cc`.

**Comment by ashishUthama** [comment]
@zanbri  - I believe this is expected. 
vectorize does not handle dimensions extents (4) less than the requested lanes  (16). 

If your dimensions are fixed, I guess you either dont vectorize, or pad the image out to a minimum of 16. The latter might be worth trying since I believe that might all happen at the register level if you schedule it right.

If you dimensions are variable, you could try something like this to enable vectorization only when the extents go beyond the required threshold:
```

        Expr canVectorize = my_vec.dim(0).extent() > natural_vector_size(my_vec.type());
        E
            .compute_root()
            .parallel(y)
            .specialize(canVectorize).vectorize(x,natural_vector_size(my_vec.type()));
```

**Comment by zanbri** [comment]
Thanks for your answer, Ashish -- it seems to have fixed it!

I'm curious though, shouldn't that imply that vectorize needs my_vec to have a length equal to an integer multiple of the natural vector size?

When I run the example with `my_vec(width)` where `width = 9` and the natural vector size is 4, I don't get any error. Shouldn't the last vectorizing step lead to the same problem of having the remaining dimension extents less than the requested lanes?

**Comment by abadams** [comment]
By default, the tail is handled by shifting the last vector computed inwards, so you get indices 0 1 2 3, 4, 5, 6, 7, and then, 5, 6, 7, 8 computed.

**Comment by zanbri** [comment]
Got it. Thank you both!

**Comment by steven-johnson** [comment]
FYI: we've been attempting to fix these sort of false positives when using Clang's ASAN/MSAN/etc modes, but I don't think anyone has attempted to do so for Valgrind.
