### ISSUE TITLE
divide by zero despite select()

### ISSUE THREAD

**Issue by matthiaskramm** [halide/Halide#3110]
I have the following body of a generator:

```
  Input<Func> input_{"input", UInt(16), 1};
  Output<Func> output_{"output", UInt(32), 1};

  void generate() {
    Var x{"x"};
    output_(x) = select(input_(x) != 0, u32(x / input_(x)), 0);
  }
```

The generated code crashes with a division-by-zero FPE, which I found confusing until I looked at the generated assembly, which is something like:

```
movzwl  <input>, %edi
mov     %esi, %eax
idivl   %edi
testl   %edi, %edi
cmovel  <zero>, %eax
```

So it first divides and *then* checks the denominator for zero.

Is there any way to prevent LLVM from doing the conditional-move-after-divide magic, or a way in Halide to deal with divide by zero?

**Comment by 9cvele3** [comment]
Checkout [https://github.com/halide/Halide/issues/477](https://github.com/halide/Halide/issues/477).
Maybe `select(is_nan(input_(x)), 0, x / input_(x))` will fix this.

**Comment by steven-johnson** [comment]
IIRC, `select()` is documented as behaving as though it can evaluate *both* the true and false exprs, then choose the correct value. This is suboptimal for cases like this, of course. Not sure of a good workaround. 

@9cvele3 - the example given above is using integer math, so #477 does not apply.

**Comment by matthiaskramm** [comment]
Best workaround I found so far is to do something like

```
safe_divisor_(x) = select(input_(x) != 0, input_(x), 1);
output_(x) = select(input_(x) != 0, u32(x / safe_divisor_(x)), 0);
```

and then do a `compute_root` on `safe_divisor_`  before computing `output_`. 

What I don't like here is that I need a change in the schedule to achieve a change in algorithm / functionality.

**Comment by steven-johnson** [comment]
>  I need a change in the schedule

You're not wrong :-(

**Comment by dsharletg** [comment]
In this case, since the data is unsigned, you could use `max(input_(x), 1)` to compute safe_divisor. 

Do you really need to `compute_root` `safe_divisor_`? It is almost certainly faster to inline it in this case (though maybe not your actual use case - but then I'd expect it probably is useful to compute it anyways...?)

**Comment by matthiaskramm** [comment]
You're right, I don't need `compute_root`. Also, neat idea about the `max()`!
