### ISSUE TITLE
how to receive multiple return values from a single Halide::Internal::Call

### ISSUE THREAD

**Issue by ronghongbo** [halide/Halide#3122]
In IR.h, 

```
struct Call : public ExprNode<Call> {
   ......
    // If that function has multiple values, which value does this
    // call node refer to?
    int value_index;
```

What if the function to call (an intrinsic in our case) returns multiple values? Is this possible for us to say:
<p>
       let  a, b = call F(args)
</p>
in the IR? If we cannot do that, is there a general way to avoid calling F twice?

To avoid any confusion: I understand it is possible to call a Func to return multiple values, but that is at the language level. What I'm asking is the internal IR.

Thanks,
Hongbo

**Comment by abadams** [comment]
For things where the value index is not one, a call is really just a load from some realized Func. I.e. it's almost always call_type = Halide. So there's no harm in having multiple calls. It does mean we have no good way to express extern calls that return multiple values.

So the answer is no, there's no general way to avoid calling F twice.
