### ISSUE TITLE
Is .o and .cpp file generated by Halide is different ?

### ISSUE THREAD

**Issue by babuya7** [halide/Halide#3123]
Hi,
I implemented conv3x3 without any scheduling in Halide , then it takes 50 ms for 20MP . I generated intermediate halide generated  .cpp file and ran this .cpp file standalone , quality-wise perfect , but it takes same latency as c -reference code about 300ms.
I don't know what is the reason.
Is there is any difference in .o file generated by halide and .cpp file ?

**Comment by zvookin** [comment]
Yes, they are completely different compilation paths. C++ code generation
is not intended to be used when the llvm based backend can be used instead.

-Z-

**Comment by babuya7** [comment]
Thanks for your response.
But how can I able to see the halide generated code , and what is the motivation behind generation of intermediate cpp file which is not any useful regarding Halide optimization.

**Comment by zvookin** [comment]
There is no intermediate C++ file in the llvm based Halide compilation
path. If you are talking about the output of compile_to_c or from the
generator front-end with extra options, that is a completely separate
backend which mainly exists to generate code for GPU languages like OpenCL
and Metal Shader Language. (Those languages are based on C/C++. Cuda is
also based on C++ syntax, but for that platform we go through LLVM to
generate PTX so the C++ backend is not used.)

Generating C++ and then compiling it is also used for some research
comparisons and for cases where compiling C++ is the only option, with the
very likely loss of performance being acceptable. (The latter is the
justification for adding generic vectorization to C++, etc. It also sort of
supports OpenMP. That is solely the result of research needs as I don't
think anyone uses it in anything like production.) Finally, sometimes it is
useful to look at the C++ code to get a better idea of what a schedule is
doing, though it is almost always better to use a .stmt file.

Generally if you want to "see" the Halide generated code for targets where
we go through LLVM, you need to look at llvm IR or final assembly. Looking
at C++ introduces a level of abstraction that doesn't exist in the main
compilation path and that level of abstraction often costs significant
performance. (As with any such comparison, one can probably find degenerate
cases where the C++ path is faster. Also, given they are different
backends, there can be artifacts of the Halide compilation process that are
independent of the fundamental issues of using C/C++ as an intermediate
language. All that said, the bottom line is Halide offers an llvm based
compiler and it is the preferred one to use.)

-Z-
