### ISSUE TITLE
var as index in expr array

### ISSUE THREAD

**Issue by rahulkodinya** [halide/Halide#3124]
Func CI{"CI"};
Var x{"x"}, y{"y"};
Expr op[2];

class Col_Increment : public Generator<Col_Increment> {
		op[0] = x + 1;
		op[1] = x + y + 1;
		Expr z = y & 0x1;
CI(x,y) = op[z];
}

**Build error**:
error: no match for operator[]  (operand types are Halide::Expr [4] and Halide::NamesInterface::Expr {aka Halide::Expr})

Intention is to switch between expressions based on y index. We ruled out func array and tuples as they write in different output buffers and the reads in next stages will suffer.

Please suggest a suitable solution for above issue.

**Comment by zvookin** [comment]
This code is mixing up levels of compilation. The array "op" is a C++ value
that exists when the generator is running, not in the output of the Halide
compiler.

Generally one uses a select expression to handle this case:

    select((y & 0x1) == 0, x + 1, x + y + 1)

-Z-

**Comment by rahulkodinya** [comment]
> Generally one uses a select expression to handle this case:
> 
>     select((y & 0x1) == 0, x + 1, x + y + 1)

Sorry, I forgot to mention: our base implementation is exactly like above. There is a switch case with 16 cases implemented using select(). Its performance is not that good.

I am trying to improve it by eliminating select and using function pointer array kind of solution. Is that possible ?

**Comment by zvookin** [comment]
The select logic usually gets unrolled in the schedule to eliminate branches. Or if the logic on each side is cheap and the condition varies in a complex fashion, the select can be vectorized which amortizes the overhead across a wide vector operation. Halide doesn't have function pointers in any direct sense.

**Comment by rahulkodinya** [comment]
> The select logic usually gets unrolled in the schedule to eliminate branches. Or if the logic on each side is cheap and the condition varies in a complex fashion, the select can be vectorized which amortizes the overhead across a wide vector operation. Halide doesn't have function pointers in any direct sense.

I got it. Thanks @zvookin for help !!
