### ISSUE TITLE
Select expression with function calls

### ISSUE THREAD

**Issue by nitish2112** [halide/Halide#3133]
Hi,

Seems like CodeGen_C does not check whether the true and false values of a Select expression are function calls with side-effect. 

```
void CodeGen_C::visit(const Select *op) {
    ostringstream rhs;
    string type = print_type(op->type);
    string true_val = print_expr(op->true_value);
    string false_val = print_expr(op->false_value);
    string cond = print_expr(op->condition);
    rhs << type << "::select(" << cond << ", " << true_val << ", " << false_val << ")";
    print_assignment(op->type, rhs.str());
}
```

So, for example in
```
y = Select(x==0; foo(&a), bar(&a));
```
the generated code will be
```
y_0 = foo(&a);
y_1 = bar(&b);
y = (x==0) ? y_0 : y_1; 
```
where foo and bar update a, both foo and bar will be called which will lead to incorrect result. Is this a bug in the implementation or something is wrong with my understanding?

Thanks

**Comment by zvookin** [comment]
Both sides of a select may be evaluated and the order is unspecified.
Potentially non-pure calls in a select should be an error. You have to jump
through some hoops to get the equivalent of &a however....

**Comment by ashishUthama** [comment]
This is as designed behavior.
`Select` is [documented](http://halide-lang.org/docs/namespace_halide.html#a9d6371892ae38e7eb681fd3f23945b06) as evaluating all arguments.

Makes sense when you think about vectorization...

**Comment by nitish2112** [comment]
Ok. Makes sense. Thanks!
