### ISSUE TITLE
clFinish enabled only when DEBUG_RUNTIME

### ISSUE THREAD

**Issue by ronghongbo** [halide/Halide#3141]
In src/runtime/opencl.cpp Line 1065, why "clFinish" is enabled only in DEBUG_RUNTIME? Is there something wrong when it is always on? 
```
WEAK int halide_opencl_run(...) {
      ...
    #ifdef DEBUG_RUNTIME
    err = clFinish(ctx.cmd_queue);
    ....
    #endif
    return 0;
}
```

Thanks,
Hongbo

**Comment by dsharletg** [comment]
Normally, we want to allow the command queue to complete processing asynchronously, only blocking when a buffer is copied back to the host.

When generating debug output, we try to show the time each command takes, which requires waiting for the command to complete.

**Comment by zvookin** [comment]
It is a huge performance hit to serialize GPU kernel execution in this way.
