### ISSUE TITLE
How to compile multi Halide::Func into one static library?

### ISSUE THREAD

**Issue by rzwm** [halide/Halide#3149]
I want to compile multi Halide::Func to one static library, but I can't find the method. Now I compile multi librarys for every Halide::Func and then merge them to one library, but doing like this will produce as many .h files as much Halide::Func. 
Is there a better way to do it?

**Comment by 9cvele3** [comment]
You can write your own code that combines all generated .h files into one. Note that each generated .h has the same beginning and the same end, and only differs in the middle, where function signatures are. 

So you should write the common beginning to the new .h file (eg. halide_aot.h) , then iterate through all generated .h files, collect function signatures from them, put the signatures in halide_aot.h, and write the common end to halide_aot.h. After this, you can even delete unnecessary .h files. 

I had the same problem and this is how I solved it. I wasn't able to find some function in Halide that will do that for me automatically.

**Comment by rzwm** [comment]
@9cvele3 Many thanks for your reply. If there hasn't an automatic way, I will keep all the header files，because merging them is so inconvenient.

**Comment by rzwm** [comment]
Now my solution is: 
1. Write a simple function, compile it to a static library with runtime;
2. Write every function you need, compile each of them to one static library with no_runtime;
3. Merge these static libraries to one, using ar.exe(linux) or lib.exe(Windows);
4. Write a .h file, which contains all the function's independent header file using `#include`;

Then you have a static library which contains all functions and related to one .h file.
