### ISSUE TITLE
Fuzz simplifier failure on unrelated test run

### ISSUE THREAD

**Issue by dsharletg** [halide/Halide#3154]
cd bin/build/tmp ; /home/travis/build/halide/Halide/bin/correctness_fuzz_simplify
Simplify fuzz test seed: 1532491752
a = int32(a)
b = int32(a)
c = int32(e)
d = 23
e = -11
(((54 - 97)*(23 + int32(uint8(e))))/int32((uint8)222))
(((int32(uint8(e))*43) + 989)/-222)
In vector lane 0:
(((54 - 97)*(23 + int32(uint8(e))))/int32((uint8)222)) -> -52
(((int32(uint8(e))*43) + 989)/-222) -> -51
make: *** [correctness_fuzz_simplify] Error 255
make: *** Waiting for unfinished jobs....
Success!

**Comment by abadams** [comment]
This is fixed in the new simplifier.
