### ISSUE TITLE
Not able to Build 32x32 block processing

### ISSUE THREAD

**Issue by babuya7** [halide/Halide#3169]
Hii, I am taking SAD of 32x32  bloack but it is not going to build.
Code is as follows:
`for ( m = 0; m < 32; m++) 
{
	for ( n = 0; n < 32; n++) 
	{
		sad+= 	abs(cast<int32_t>((src_data(xo + n  , yo + m) - trg_data(xo + n , yo + m)))) ;			
	}  
}`

**Comment by rzwm** [comment]
I think you should use "RDom":
```
RDom r(0, 32, 0, 32);
sad += abs(cast<int32_t>((src_data(xo + r.x, yo + r.y) - trg_data(xo + r.x, yo + r.y))));
```

**Comment by babuya7** [comment]
I tried that one also , but it gives error "Reduction domain referenced in pure function definition"
Code is as follows : 
`Expr Cal1(Func src_data,Func trg_data, Expr xo,Expr yo,Var x,Var y)
{
	Expr sad = cast<int16_t>(0);
	Expr sad_src = cast<int16_t>(0);
	Expr sad_tar = cast<int16_t>(0);
	Expr tmp;
	
	
	Expr ps, pt;

        Expr  ys,yt;
        Expr  xmv = xo + x ; 
	Expr ymv = yo + y;
	int n = 0;
	int m = 0;
	

	sad+= abs(cast<int16_t>((src_data(xo + r.x  , yo + r.y) - trg_data(xmv + r.x , ymv + r.y)))) ;

	return sad;
	
}

Generator<Blur> {
Expr xo = x << 5;
Expr yo = y << 5;
Expr res = Cal1(inp,tar,xo,yo,x,y)
Ouput(x,y) 	= cast<int16_t>(res);
}`

**Comment by babuya7** [comment]
we should use sum() .
