### ISSUE TITLE
How to use Generator::Output<int32_t>?

### ISSUE THREAD

**Issue by rzwm** [halide/Halide#3170]
I'm writing a function which doing a laplacian filter on a gray image, and then calculate the sum of the result's abs value, code is like below:
```
// laplacia3x3 kernel:
// 0  1  0
// 1 -4  1
// 0  1  0
class Laplacian3x3_abs_sum_8UC1 : public Generator<Laplacian3x3_abs_sum_8UC1>
{
public:
	Input<Buffer<uint8_t>> src{ "src", 2 };
	Output<int32_t> dst{ "dst" };

	Func clamped16;
	Func laplacian_abs;
	Var x, y, i;

	void generate()
	{
		clamped16(x, y) = cast<int16_t>(BoundaryConditions::mirror_image(src)(x, y));
		laplacian_abs(x, y) = Halide::abs(clamped16(x, y - 1) + clamped16(x - 1, y) - 4 * clamped16(x, y) + clamped16(x + 1, y) + clamped16(x, y + 1));
 		RDom r(0, src.width(), 0, src.height());
		//dst += laplacian_abs(r.x, r.y); // can't be compiled
	}
};

HALIDE_REGISTER_GENERATOR(Laplacian3x3_abs_sum_8UC1, halide_laplacian3x3_abs_sum_8UC1);
```
But I can't get the result like this:
```
dst += laplacian_abs(r.x, r.y);
```
, it doesn't  compile.
So how should I use the `Output<int32_t>`？

**Comment by rzwm** [comment]
I find a method:
```
 RDom r(0, src.width(), 0, src.height());
dst() = 0;
dst() += laplacian_abs(r.x, r.y);
```
But then the generated function signature is like this:
```
int halide_laplacian3x3_abs_sum_8UC1(struct halide_buffer_t *_src_buffer, struct halide_buffer_t *_dst_buffer) HALIDE_FUNCTION_ATTRS;
```
I supposed the second parameter should be `int32_t*`. Where did I go wrong?

**Comment by zvookin** [comment]
There is no syntactic sugar for scalar outputs yet. So you have to make a
halide_buffer_t that points to a single item.
HalideRuntime::Buffer::make_scalar does this.

Eventually we'll likely add support for passing a C++ ref into that
argument slot, but it's not much of a priority right now.

-Z-

**Comment by rzwm** [comment]
Thanks! Now I know the reason.
