### ISSUE TITLE
Using sum in RDom gives Error

### ISSUE THREAD

**Issue by babuya7** [halide/Halide#3179]
`Internal error at c:\bots\prod-slave\halide-20-win\src\halide\src\Scope.h:111
Symbol 'sum$3' not found`
 This error shows when I am using sum() in rdom

**Comment by rzwm** [comment]
I think you should provide more information.

**Comment by babuya7** [comment]
Actually I am calculating sum of 32x32 block for each pixel using 
`
Expr CalSum32x32()
{
RDom r(0, 32, 0, 32);
res = sum(   abs(cast<int32_t>(src_data(x + r.x , y + r.y)) - cast<int32_t>(src_data(x + r.x , y + r.y)))  ) ;
return res;
}
 main()
{
    Expr minSad = cast<int32_t>(0);

// calculate sad for x,y pixel
    Expr sad = CalSum32x32(x,y) ;
    
   minSad  = sad ;
// calculate sad for x,+1y+1 pixel
   sad  = CalSum32x32(x+1,y+1) ;

// This line gives the error
  int idx_x = select(sad < minSad  , x+1, x) ;
  sad = CalSum32x32(idx_x ,y) ;

}
`
In the above implementation , if we have select condition with rdom values then I am not able to use that select conditons.
If I use other condition which doesn't use rdom then works fine.
Will you please suggest some idea regarding this .
