### ISSUE TITLE
One complex Halide::Func vs multi simple Halide::Funcs

### ISSUE THREAD

**Issue by rzwm** [halide/Halide#3180]
I don't know much about Halide's mechanism, so I have a confusion about how to organize Halide::Func.
For example, I have an program composed by 20 functions:
```
type input;
auto a = fun1(input);
auto b = fun2(a);
auto c = fun3(b);
...
...
type output = fun20(x);
```
To write this program with Halide, I have two choices.

Firstly, I can write 20 Halide::Func, compile each of them to one static library(now I get 20 static libraries), then use these libraries in program.

Secondly, I can write 20 Halide::Func, with every Halide::Func calls last one, thus finally I get a complex Halide::func representing the whole process. Then compile this complex Halide::Func to one static library(now I get only 1 static library). Now I can use this library in program.

My question is:
Which method is better？In other words, which method makes the program run faster？

And I also want to know: when using the second method, schedule the final complex Halide::Func will be hard, is there a good way to do it?

**Comment by babuya7** [comment]
You should use a single pipeline and try to treat each func as producer consumer relationship. 
It improves Cache performance as well as Compiler internally make some temporary folded buffer/ circular buffer that enhance the performance .
If you have different pipeline for each func then load store is so expension.
