### ISSUE TITLE
vectorize(x, > 4) makes read-only float to be -nan(ind)

### ISSUE THREAD

**Issue by rzwm** [halide/Halide#3188]
When I use `vectorize(x, 4)`，there is no error. Output is:
```
src(0, 0): 0.566826 less(0, 0): 1 full(0, 0): 255 dst(0, 0): 144
```
But When I use `vectorize(x, 8)`, output is:
```
src(0, 0): -nan(ind) less(0, 0): 1 full(0, 0): 255 dst(0, 0): 255
```
Platform is Windows 10, CPU is i5-6500.
The problem is: in arm CPU, all cases are OK.

Code is like below:
```
#pragma once
#include "Halide.h"
using namespace Halide;

class HDR_Add_Detail : public Generator<HDR_Add_Detail>
{
public:
	Input<Buffer<float>> src{ "src", 2};
	Input<Buffer<uint8_t>> full{ "full", 2};
	Input<Buffer<float>> less{ "less", 2 };
	Output<Buffer<uint8_t>> dst{ "dst", 2 };

	GeneratorParam<bool> parallel{ "parallel", false };

	Var x{ "x" }, y{ "y" }, yo{ "yo" }, yi{ "yi" };
	void generate()
	{
		dst(x, y) = cast<uint8_t>(clamp((src(x, y) - less(x, y)) * 255.0f + full(x, y), 0, 255));
		dst.vectorize(x, 8);

		if (parallel)
		{
			//dst.split(y, yo, yi, 16).parallel(yo);
			dst.parallel(y);
		}
	}
};

HALIDE_REGISTER_GENERATOR(HDR_Add_Detail, halide_hdr_add_detail);
```

**Comment by shoaibkamil** [comment]
The `src` buffer shouldn't get written to; I'd first double- and triple-check that the pointers you're passing in are correct for the various buffers.

**Comment by rzwm** [comment]
Today I recompile and run the same code, there is no error, because my computer is new start, and yesterday's error happened after my computer had run several hours. So I think there are some hidden details that cause the bug. If I get the error again, I'll report it.
