### ISSUE TITLE
Ordering of LLVM Add instructions can change HVX codegen semantics

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3203]
It appears that changing the order of codegen for an Add node can alter the overall result of the pipeline when generating HVX code. My suspiction is a bug in LLVM (either in general or in the HVX backend), though I haven't entirely ruled out something in Halide's HVX-specific code.

To repeat:
- sync to branch srj-hvx-codegen-bug
- build and run on CPU and HVX-simulator:
  - `HL_TARGET=host make bin/host/generator_aot_downsample && ./bin/host/generator_aot_downsample`
  - `HL_TARGET=host-hvx_128 make bin/host-hvx_128/generator_aot_downsample && HL_HEXAGON_SIM_REMOTE=/path/to/hexagon_sim_remote ./bin/host-hvx_128/generator_aot_downsample`

Note that both output:

```
0 0 624
1 0 1264
2 0 1760
3 0 1792
```

Now, edit Codegen_LLVM.cpp by changing the `#if 1` on line 1264 to `#if 0` (swapping the codegen order for some Add operators) and repeat the above steps; notice that the  CPU run is the same, but the HVX output is now:

```
0 0 624
1 0 1264
2 0 1764   <-- ooooops
3 0 1792
```

Note that the third value is different (1764 instead of 1760); needless to say, the order of arguments to integer addition shouldn't be affecting the result.

(Note that at top-of-tree, the order of codegen is unspecified and at the mercy of how the C++ compiler decides to evaluate the arguments to `CreateAdd()`; the edits in this issue/branch are there to ensure a reliable order.)

**Comment by steven-johnson** [comment]
(Note that this is using recent LLVM trunk builds; I haven't tried older LLVM versions.)

**Comment by pranavb-ca** [comment]
I am able to reproduce this now. BTW, when I built Halide on this branch test/internal.cpp - generator_test() failed. Did you also see that?

**Comment by steven-johnson** [comment]
I did not try the other tests on this branch.

**Comment by pranavb-ca** [comment]
I have been able to isolate this to about 9 adds where in if the order is changed from code generating 'a before b' to 'b before a' the ouput toggles from incorrect to correct. I am now going over the difference in IR between the two.

**Comment by pranavb-ca** [comment]
Update: When I disable the the reassociate pass in LLVM, the test passes. This makes sense at least to the point that the reassociate pass would be sensitive to the order of instructions that it sees. Still digging...

**Comment by pranavb-ca** [comment]
Narrowed this down to a bug in the software pipeliner in LLVM that was incorrectly fixing up the PHI nodes in the kernel of a software pipelined loop. A fix for this is in review here https://reviews.llvm.org/D51167
I have verified that this test passes with LLVM built with this fix. I will close this issue once this lands and @steven-johnson  confirms.

**Comment by steven-johnson** [comment]
The LLVM portion of this landed in llvm-trunk at r340782 https://github.com/llvm-mirror/llvm/commit/6d962e337470ccb07f9de0f324fdfc5f3ac050f6; once https://github.com/halide/Halide/pull/3249 lands, this *should* be marked as fixed.
