### ISSUE TITLE
Halide not working properly on GPU when called from JNI

### ISSUE THREAD

**Issue by XZiar** [halide/Halide#3209]
I am building a demo to run Halide on android, but it is not working properly on GPU.
I am testing the plain copy operation using OpenCL, using generator to build it into static library.
It passes when I link it into executable directly, but failed when I wrap it into shared library and call it from JNI. Most value I read from Buffer is zero, with some random value at the front. 
If I turn to use CPU, everything goes well with no mistake.
By the way, I get all zero result when using OpenGL as backend with JNI.

Any idea on how to debug it?

Is there anything I should concern when building Halide into a shared library running on android's GPU? Like library linking or context management?

**Comment by abadams** [comment]
Are you calling copy_to_host on the output buffer? Adding the -debug target flag is a good way to diagnose GPU backend issues.

**Comment by XZiar** [comment]
copy_to_host has been added, and I have check the debug output of OpenCL kernel, they are identical.

**Comment by XZiar** [comment]
I have tested "generating image" in Halide, both GLSL and OpenCL is working properly. but If I change to perform "copy" operation, they both fail.
It seems that input data are not correctly sent to gpu when I am using JNI, but everything is fine when I build executable directly. 
I try to call `copy_to_device` but it requires some additional parameter...

Is that any further method I can try to find out what is going wrong?

**Comment by shoaibkamil** [comment]
As Andrew suggested, you could try using the -debug target flag in order to see the sequence of calls to the Halide runtime.  In particular, it sounds like you may want to see if the CPU->GPU and GPU->CPU copies are happening; it may be the case that data is not being copied to the GPU because the host dirty bit on the buffer is not set.

**Comment by XZiar** [comment]
You are right, `set_host_dirty` solved my problem cause I am performing memcpy directly.
