### ISSUE TITLE
Support reordering RVar if the function is associative

### ISSUE THREAD

**Issue by jingpu** [halide/Halide#3214]
Halide currently doesn't allow `.reorder` schedule on RVar hitting the following assertion. It will be useful to allow reordering reduction loops if the the function is proven to be associative.

https://github.com/halide/Halide/blob/8c2f090f40411cd370ae0dd80b98f88367a7ad38/src/Func.cpp#L1510-L1524

I think we could reuse some existing tool implemented for `.rfactor` to prove the associativity.

**Comment by abadams** [comment]
Yes, the tools are there for us to be able to prove that it's safe to reorder. I'm currently swamped with other stuff, but this has been bothering me too.
