### ISSUE TITLE
Incorrect acquire_context and release_context function names in test script

### ISSUE THREAD

**Issue by zanbri** [halide/Halide#3232]
In `test/generator/acquire_release_aottest.cpp`, there are two functions:
1 - halide_acquire_cuda_context(void *user_context, CUcontext *ctx)
2 - halide_release_cuda_context(void *user_context)

I believe the purpose of these functions is to overwrite the behavior of functions with the same identifier defined in `src/runtime/cuda.cpp`. However, the functions in `cuda.cpp` differ in function name and arguments:
1 - halide_cuda_acquire_context(void *user_context, CUcontext *ctx, bool create = true)
2 - halide_cuda_release_context(void *user_context)

The problem should be fixed simply by changing the functions name and arguments in `acquire_release_aottest.cpp` to match those defined in `cuda.cpp`.

**Comment by jingpu** [comment]
It sounds like a bug in the test to me.

**Comment by zanbri** [comment]
I'm closing this issue as I create a pull request here with the same contents: https://github.com/halide/Halide/pull/3233
