### ISSUE TITLE
Cuda Atomic Operation Error occurred while building halide

### ISSUE THREAD

**Issue by dflin96** [halide/Halide#3274]
While attempting to follow the build halide and llvm on windows according to the readme file, the following error occurred during building of Halide. 
![img_2921](https://user-images.githubusercontent.com/42079728/45651010-04475300-ba85-11e8-9f4b-28f712135758.JPG)
Looked into the cuda.cpp, cmake file, and build file and I don't find any way to pass in those options avoiding performance penalty. In addition, we're attempting to target ARM which shouldn't involve cuda being ran for our testing.
there wasn't any error during LLVM, Clang build following instructions on https://clang.llvm.org/get_started.html
I was using VS 2015, LLVM 6.0.1, and Python 3.7 during this process. 
Any guide/step to step instructions towards setting up the environment in Windows would be much appreciated. Thanks!

**Comment by alexreinking** [comment]
Closing since repro is impossible; we have dropped support for LLVM 6.
