### ISSUE TITLE
LLVM broke paddubw and paddusw codegen

### ISSUE THREAD

**Issue by dsharletg** [halide/Halide#3281]
To repro:

HL_TARGET=x86-64-linux-avx-sse41 make correctness_simd_op_check -j40

**Comment by steven-johnson** [comment]
Someone should follow up with an LLVM bug if they haven't already, and
probably reference the previous addus/subus bug that was recently fixed
(and please cc me even though I am on vacation for another week)

**Comment by dsharletg** [comment]
I've given up on a workaround. As for reporting the bug, I've asked for an LLVM bugzilla account. I don't know when I will get one (self registration disabled due to spam).

**Comment by dsharletg** [comment]
I've been digging into this. Even on LLVM 7.0, our runtime implementation of paddusb does not generate this instruction, it widens instead. I suspect that this was always super fragile, and just a small change nudged it out of expectations for the backend. In practice, generating this instruction is probably hit and miss.

**Comment by steven-johnson** [comment]
Note that as of https://reviews.llvm.org/rL345602, we are also not correctly producing psubusb/psubusw instructions. I'm going to nop out those as well for now :-(

**Comment by dsharletg** [comment]
These tests are currently enabled and working in simd_op_check.cpp
