### ISSUE TITLE
Wrong 'make' instruction given in comments in tutorial/lesson_05_scheduling_1.cpp

### ISSUE THREAD

**Issue by crteod** [halide/Halide#3284]
Wrong filename given as 'make' argument, in tutorial/lesson_05_scheduling_1.cpp at line 17:

`// If you have the entire Halide source tree, you can also build it by`
`// running:`
`//    make tutorial_lesson_05_`**schedule**`_1`
`// in a shell with the current directory at the top of the halide`
`// source tree.`

Should be
make tutorial_lesson_05_scheduling_1
instead of
make tutorial_lesson_05_schedule_1

**Comment by alexreinking** [comment]
Fixed by #4401
