### ISSUE TITLE
Is there a diagram about Inheritance relationship of HalideIR

### ISSUE THREAD

**Issue by blueyi** [halide/Halide#3297]
I’m a newer to C++, I want to visit HalideIR’s every node of a compute schedule, but I don’t know where is the root to start, and the HalideIR has a too complicated inheritance for me.
I have tried to debug an A + B compute step by step, it is too difficult for me to understand the call order, so I hope there are some simple demo code or a diagram about Inheritance relationship of the IR .
Thanks a lot

**Comment by zvookin** [comment]
It seems very unlikely that you need to know anything about C++ inheritance for the task of writing a visitor. The IRNode types themselves have no inheritance between them. An Add is an Add. However each IR node is either an Expr or a Stmt depending on whether it produces a value. Expr nodes have a type field and Stmt nodes do not.

It may help to look at the Doxygen output on halide-lang.org. It may be a bit out of date unfortunately, but will likely be fine for IR nodes and such. (We're working on making regular updates happen automatically.) http://halide-lang.org/docs/struct_halide_1_1_internal_1_1_add.html would be an example for the Add node.

**Comment by blueyi** [comment]
@zvookin  Thanks a lot, I will try it.
