### ISSUE TITLE
Adding Support for a new platform with extended OpenCL

### ISSUE THREAD

**Issue by GokulNC** [halide/Halide#3307]
Hi,

We have planned to add support for a new hardware platform which has OpenCL as a target feature, but with a few customizations.

Following are our queries to get started:

1. Is it OK to add a new feature named `CL<platform_name>` to the files ` Target.h`, `Target.cpp` and `HalideRuntime.h`, something similar to `CLHalf` feature ?

2. Where are the features like `CLHalf` set from? Or how are features set?
3. How to set multiple features for a target manually? (Both command-line & from code)
How is it parsed from [`HL_TARGET`](https://github.com/halide/Halide/blob/master/src/Target.cpp#L482) ?

4. Is there support for DMA Operations in Halide-generated OpenCL, like [async_work_group_copy()](https://www.khronos.org/registry/OpenCL/sdk/2.1/docs/man/xhtml/async_work_group_copy.html) which is responsible for copying data between local memory & global memory ?
If no, any guidance on how to proceed about it?

Any help/tips is highly appreciated :)
Thank you.

**Comment by zvookin** [comment]
1) Yes, that is exactly what you need to do. If you add the string to the appropriate table in Target.cpp, the parsing for command line tools should work. The proposed name seems reasonable, though there may be some discussion once we know specifics.

2) Features are either set explicitly using Target methods such as the constructor or ```Target::set_feature``` or passed in via environment variables such as ```HL_TARGET``` and ```HL_JIT_TARGET```. Command line tools and build system setups have their own ways of translating arguments or configuration files into the appropriate target settings. We have a fairly strict rule that any host should be able to generate code for any target. We also strive to keep features, such as OpenCL usage, orthogonal across architectures and such. Thus one should be able to use new OpenCL features from ARM, x86, MIPS, etc.

3) It depends a bit on context, but for running Halide's built-in tests one generally does something like:
    ```HL_TARGET=host-opencl-clhalf HL_JIT_TARGET=host-opencl-clhalf make run_tests```
For systems building production code, the target is usually specified by the build system. E.g. the "halide_target_features" flag in our Bazel support. (Typically the target architecture comes from somewhere else in the build system as it already knows whether it is building for ARM or x86, etc.)

4) This is a longer answer which I will try to get to later. The initial answer is we probably need to add support for compiling the ```.async()``` and ```.copy_to_host()``` directives to some GPU backends including OpenCL. There's an architectural direction here, but it is some work to do.

**Comment by GokulNC** [comment]
Thank you very much @zvookin for your quick reply.

1. One of the major changes we're planning to do is adding support for vector lanes of size 32 & 64, for example, to generate `vload32()`, `vload64()`, etc.
Shall we do this using generic feature names like `CL_64LANES` or shall it just fall under `CL<platform_name>` ?

4. So how does Halide do memory copies between host and device, atleast in OpenCL?
Any guidance on adding `async()` and other unsupported directives, and for other OpenCL calls like `async_work_group_copy()`, etc. ?

Thanks again :)
