### ISSUE TITLE
webassembly backend (was asm.js backend)

### ISSUE THREAD

**Issue by abadams** [halide/Halide#331]
Either directly, or via the fastcomp javascript llvm backend.

Especially useful combined with newer asm.js simd support, and webgl. Thread support is probably iffy due to the worker thread memory model.

**Comment by dsharletg** [comment]
@srj FYI, maybe this old issue is relevant for some of your new work.

**Comment by steven-johnson** [comment]
Addressed recently via https://github.com/halide/Halide/pull/3732
