### ISSUE TITLE
Bad performance calculation in performance/matrix_multiplication

### ISSUE THREAD

**Issue by Blealtan** [halide/Halide#3335]
GFLOPS is calculated in the benchmark as

```
    float gflops = 2.0f * matrix_size * matrix_size * matrix_size / 1e6f;
```

While it should be `1e9f` rather than `1e6f`.

It shows over 23 TFLOP/s performance on my i7 8700K (this program is not using GPU), while theoretical upper limit should be at hundred GFLOP/s magnitude. 23 GFLOP/s is a number makes much more sense and should be the actual performance of this matrix multiplication.

**Comment by abadams** [comment]
Ha, 23 TFLOP/s would be impressive indeed, even on the latest GPU. I've been reading the number as MFLOP/s I guess and did not notice the incorrect labelling.

**Comment by steven-johnson** [comment]
fixed by https://github.com/halide/Halide/pull/3340
