### ISSUE TITLE
behavior of saturated types

### ISSUE THREAD

**Issue by matthiaskramm** [halide/Halide#3337]
I have:

```
output(x) = u8_sat(input(x)) - 3
```

Since the input is cast to `u8_sat`, I would have expected the subtraction to clamp to `0`. However, turns out that `u8_sat(0) - 3` is `65533`.

So the current semantics seem to be that a cast to a `*_sat` clamps to the data type limits, but after that the type behaves like it's unsaturated equivalent.

Assuming this is intentional, what's a good way to make Halide generate a saturated subtraction without having to store the intermediate result in a larger type? I'm looking for something that gives me e.g. `u8(0) - u8(255) -> u8(0)`.

**Comment by zvookin** [comment]
Halide does not have saturating types. ```u8_sat``` is an operator that casts to ```uint8_t``` with saturation. The solution to this issue given is to promote to a wider type. There are peephole patterns to try and target instructions for doing the operation without changing the vector size/shape where such instructions exist exist as well. (We don't have complete support by any means, but that's a backend issue, not the way things are expressed in the language.)

Modeling saturation with a type has issues too in that one can have surprising saturations in the middle of a computation. It also adds a fair bit of complexity to the language as one either makes the types incompatible, requiring explicit casts, or one has to define the semantics of mixed arithmetic for all cases. Experience with signed and unsigned types in C demonstrates the difficulty of doing the latter without surprises.
