### ISSUE TITLE
how to build halide library with or without hvx for android ?

### ISSUE THREAD

**Issue by victorygogogo** [halide/Halide#3366]
how to build halide library with or without hvx for android ?

@jrk @piotrrak  @ibtaylor @guanqun

**Comment by steven-johnson** [comment]
A little more detail on what you're trying to accomplish here (and why) would be welcomed.

**Comment by piotrrak** [comment]
You may want to go to:
https://developer.qualcomm.com/software/hexagon-dsp-sdk/tools

QC used to bundle/bundels own version of Halide with their Hexagon SDK.

In section "Halide documentation" you probably will find what you need, had a brief look at "Training Slides for Halide with HVX" and had some basic hints and examples.
Switching to upstream Halide from there shouldn't be an issue, we did it for experimentation and as workaround bugs in past.
Unfortunately you'll have to create an account and you'll have to agree to few pages of some lawyer team five lifetimes of hard work...

Hope that helps to get started.

**Comment by victorygogogo** [comment]
@piotrrak  @steven-johnson    
thank you all.
