### ISSUE TITLE
Undefined reference to halide_gpu_thread_barrier()

### ISSUE THREAD

**Issue by GokulNC** [halide/Halide#3397]
Depending upon the C standards, `inline` seems to have different meaning.

Using an OpenCL compiler that I'm using which complies to C99 standard, I face the following error:
```Undefined reference to halide_gpu_thread_barrier()```

This is because of the fact that the compiler has chosen not to inline it, and it is looking for another function specification for that function which is not inlined. More details on how C99 takes care of in-lining: http://clang.llvm.org/compatibility.html#inline

So, when I changed the `inline halide_gpu_thread_barrier()` to `static inline halide_gpu_thread_barrier()` [here](https://github.com/halide/Halide/blob/5e17a20783854e158c06729a2c9b788d2e041928/src/CodeGen_OpenCL_Dev.cpp#L685), things worked fine.

So how do we fix this issue? Is it OK to add `static inline` to all the inlined functions? Or we remove `inline` altogether from all functions (since this can be taken care by today's smart compilers) ?

Is this an issue only specific to OpenCL, or should this issue be addressed for other targets too?

**Comment by zvookin** [comment]
I expect ```static inline``` is correct. In theory if we ever allowed linking multiple kernels together this might make a difference, but we don't. That said, ```halide_gpu_thread_barrier()``` not being inline doesn't make a whole lot of sense.

**Comment by abadams** [comment]
I have a nasty feeling that this is one of those things that *must* be inlined or it's not correct, because the barrier is based on the address of the instruction.

**Comment by GokulNC** [comment]
@abadams Even if so, it shouldn't be an issue, because the only behavior that would trigger this issue is different threads branching and reaching different barrier instances - i.e. a deadlock.  So, failing to inline only introduces incorrect behavior when the correct behavior is deadlock, which should be never.

@zvookin Do you mean fusing kernels? But there's already a support for that here: https://github.com/halide/Halide/pull/1546
I actually faced this issue when I was trying the above.

**Comment by GokulNC** [comment]
Shall I send a PR with the `static inline` fix? Or any other idea?
@abadams @zvookin

**Comment by zvookin** [comment]
Wouldn't it better to fix codegen to put out the proper target specific
barrier directly?

-Z-

**Comment by zvookin** [comment]
I'll fix it later today. It is sort of ugly across multiple backends now.

**Comment by zvookin** [comment]
I'm pretty sure https://github.com/halide/Halide/pull/3416 fixes this. If not too much hassle, would be great to verify the gpu_barrier_no_inline branch does fix the problem. We'll likely merge it tomorrow or the day after.

**Comment by GokulNC** [comment]
Works great now :)
Thank you..
