### ISSUE TITLE
correctness_convolution is failing for Metal on Mac Buildbot

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3408]
It appears to be related to the recent upgrade of the Buildbot to use OSX Mojave, but this isn't proven yet. (Test is disabled for Metal pending investigation.)

**Comment by steven-johnson** [comment]
(took the liberty of assigning this to @shoaibkamil since he's already doing some investigating)

**Comment by steven-johnson** [comment]
also: correctness_parallel_gpu_nested is failing and was disabled

**Comment by steven-johnson** [comment]
also: tutorial_lesson_12_using_the_gpu

**Comment by shoaibkamil** [comment]
Fixed by #3410.
