### ISSUE TITLE
Question: compile GLSL

### ISSUE THREAD

**Issue by ck3d** [halide/Halide#3412]
I like to use Halide to generate GLSL to use it in an WebGL context. But I did not find a way to generate it. Did I missed something?

**Comment by shoaibkamil** [comment]
Halide's generated GLSL isn't really meant to be used standalone; it depends on code Halide generates to set up buffers etc.  You can see the code by setting `HL_DEBUG_CODEGEN=1` at kernel compile time.

**Comment by ck3d** [comment]
Thanks! I will see how far I can go.
