### ISSUE TITLE
Using Vector Types

### ISSUE THREAD

**Issue by nitish2112** [halide/Halide#3415]
Hi,

It seems like in Halide we can create vector data types by using the "lanes". For example, Float(32, 4) is a vector of 4 floats. However, I am not sure how can I use the individual elements of the vector to do some computation. For example how can I do this? 

```
let x = .... // expr is of type Float(32,4)
for ( i, 0, 4 ) {
  temp(0) += x[i] * i
}
``` 

Thanks!

**Comment by nitish2112** [comment]
I understand how I can do a vector store to a temporary location. That is just "realize" a memory location for 1 element of vector data type. Then use Provide to do a vector store to this memory location. But how can I do scalar loads from this?

**Comment by dsharletg** [comment]
There is this: https://github.com/halide/Halide/blob/master/src/IR.h#L731

However, on some platforms, this is really slow, and the recommended approach is what Andrew said (store vector, load scalar).

**Comment by abadams** [comment]
The type of the allocation will be Float(32, 1), with an allocation size of 4. The store would use an index of ramp(0, 1, 4) to store an entire vector, and the loads would use scalar indices (e.g. '2').

**Comment by nitish2112** [comment]
Didn't know about the usage of Ramp. This makes sense. Thanks!
