### ISSUE TITLE
correctness/cast.cpp has two unused variables

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#3426]
The variables `float_expr` and `double_expr` in [test/correctness/cast.cpp:14](https://github.com/halide/Halide/blob/aa2d29d87fd5c0d28b42a846915840c41315a113/test/correctness/cast.cpp#L14) are unused and do not clearly contribute to the test (if they do at all).

What is their role supposed to be in the test?

Also: why is this not caught by `-Wall -Werror`? My understanding is that `-Wunused-variable` is a part of `-Wall`.

**Comment by abadams** [comment]
Looks like the test was never fully fleshed out. Feel free to open a PR that deletes them.
