### ISSUE TITLE
Halide does not detect NVIDIA 1080Ti

### ISSUE THREAD

**Issue by abhijangda** [halide/Halide#3439]
Hello,

I have NVIDIA GTX 1080Ti GPU with Intel i5-4670 CPU running Ubuntu 16.04. I have installed CUDA 8.0 and clang-6.0/llvm-6.0. nvcc and clang both are able to compile CUDA files for the GPU. Unfortunately, Halide does not detect that I am using a GPU. I am compiling test/auto_scheduler/harris.cpp and in case of manual schedule, `get_jit_target_from_environment().has_gpu_feature()` returns 0. I want to test the performance of manual schedules for GPU. I have cloned the latest Halide master branch and compiled it with same clang/llvm-6.0. Can anyone please let me know, how to make it work.

Thank You

**Comment by shoaibkamil** [comment]
You need to set the JIT target environment variable to include CUDA if you wish to use that function; this can be done by setting `HL_JIT_TARGET=host-cuda` (see [here in the README](https://github.com/halide/Halide#some-useful-environment-variables) for other useful environment variables.

Alternatively, you can programmatically set the target using an approach like shown in [the tutorial](https://github.com/halide/Halide/blob/005eedbc51704a184fd88b2d7e65307e149fa043/tutorial/lesson_12_using_the_gpu.cpp#L283).

**Comment by abhijangda** [comment]
Thanks, it worked.
