### ISSUE TITLE
Shouldn't need to specify input sizes to rungen

### ISSUE THREAD

**Issue by abadams** [halide/Halide#3451]
If I specify an output size, it should just use a bounds query to get input sizes. E.g. I'd like to be able to say:

`./my_generator.rungen --output_extents=[1024,1024] input1=zero input2=zero`

Additionally, it would be nice to set a policy for all inputs not otherwise specified:

`./my_generator.rungen --output_extents=[1024,1024] --input_values=random`

**Comment by steven-johnson** [comment]
offline, andrew also suggested using autoscheduler estimates for output sizes (if present) now that they are emitted in the metadata

**Comment by steven-johnson** [comment]
(Note that there isn't currently a way to use `--output_extents` for Generator with multiple Outputs that may have different dims/sizes. Would probably be useful to have a way to handle this case.)

**Comment by steven-johnson** [comment]
It could be useful to allow for either bounds-query or estimates for the 'auto' option, so how about something like this as an option:
```
input1=zero:[100,100,3]    # explicit
input1=zero:bq             # use bounds-query size. alternately, 'calc' or 'auto' for text
input1=zero:estimates      # use estimates provided in code
```

**Comment by abadams** [comment]
lgtm. Another tedious thing was just having to list every single input. It would be nice to be able to specify a value for all inputs not explicitly mentioned elsewhere:

`--input_extents=random:auto`

**Comment by steven-johnson** [comment]
Should the default-input flag apply to scalars as well as buffers?

**Comment by abadams** [comment]
Maybe via a separate flag? Ideally the person has given their input scalars default values that appear in the metadata.

**Comment by abadams** [comment]
(or estimates)

**Comment by steven-johnson** [comment]
Declaring fixed.
