### ISSUE TITLE
After compiling to host successfully. Some questions about compile to android.

### ISSUE THREAD

**Issue by PK15946** [halide/Halide#3484]
I have compiled mycode with halide-linux-64 with gcc and everything works fine. Here is an overview of CMakeLists.txt

> set(HALIDE_TARGET "host")
> ...
> add_custom_command(OUTPUT fit_and_slice_3x4.h fit_and_slice_3x4.o
>                           fit_only_3x4.h fit_only_3x4.o
>                    COMMAND HL_TARGET=${HALIDE_TARGET} ./fit_and_slice_3x4
>                   )
> ...
> add_custom_command(OUTPUT fit_and_slice_1x4.h fit_and_slice_1x4.o
>                           fit_only_1x4.h fit_only_1x4.o
>                    COMMAND HL_TARGET=${HALIDE_TARGET} ./fit_and_slice_1x4
>                   )
> ...
> target_link_libraries(bgu_cli_static ${CMAKE_CURRENT_LIST_DIR}/build/fit_and_slice_3x4.o 
>                                      ${CMAKE_CURRENT_LIST_DIR}/build/fit_only_3x4.o
>                                      ${CMAKE_CURRENT_LIST_DIR}/build/fit_and_slice_1x4.o
>                                      ${CMAKE_CURRENT_LIST_DIR}/build/fit_only_1x4.o
>                                      libpng15.a libz.a
>                                      Threads::Threads ${CMAKE_DL_LIBS}
>                      )

Then I change HALIDE_TARGET to 

> arm-64-android

and I get Relocations in generic ELF (EM: 183) error when execute 

> target_link_libraries(bgu_cli_static...)

Am I doing something in a wrong way or merely change  halide_target is not enough?

I also try to change the compiler from 

> gcc

 to 

> android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++

and compile again using halide-ARM-64(rather than halide-linux-64), this time I get a lot of undefined reference errors

> Scanning dependencies of target fit_and_slice_3x4
> [ 12%] Building CXX object CMakeFiles/fit_and_slice_3x4.dir/src/fit_and_slice_3x4.cpp.o
> clang++: warning: -lHalide: 'linker' input unused [-Wunused-command-line-argument]
> clang++: warning: -ldl: 'linker' input unused [-Wunused-command-line-argument]
> clang++: warning: -lz: 'linker' input unused [-Wunused-command-line-argument]
> [ 25%] Linking CXX executable fit_and_slice_3x4
> clang++: warning: argument unused during compilation: '-Wa,--noexecstack' [-Wunused-command-line-argument]
> /home/Android/android-ndk-r18b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libdl.so.2, needed by /home/Downloads/bgu_android/bin/libHalide.so, not found (try using -rpath or -rpath-link)
> /home/Android/android-ndk-r18b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libpthread.so.0, needed by /home/Downloads/bgu_android/bin/libHalide.so, not found (try using -rpath or -rpath-link)
> /home/Android/android-ndk-r18b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libz.so.1, needed by /home/Downloads/bgu_android/bin/libHalide.so, not found (try using -rpath or -rpath-link)
> /home/Android/android-ndk-r18b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libstdc++.so.6, needed by /home/Downloads/bgu_android/bin/libHalide.so, not found (try using -rpath or -rpath-link)
> /home/Android/android-ndk-r18b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libm.so.6, needed by /home/Downloads/bgu_android/bin/libHalide.so, not found (try using -rpath or -rpath-link)
> /home/Android/android-ndk-r18b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libgcc_s.so.1, needed by /home/Downloads/bgu_android/bin/libHalide.so, not found (try using -rpath or -rpath-link)
> /home/Android/android-ndk-r18b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libc.so.6, needed by /home/Downloads/bgu_android/bin/libHalide.so, not found (try using -rpath or -rpath-link)
> /home/Android/android-ndk-r18b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: ld-linux-aarch64.so.1, needed by /home/Downloads/bgu_android/bin/libHalide.so, not found (try using -rpath or -rpath-link)
> CMakeFiles/fit_and_slice_3x4.dir/src/fit_and_slice_3x4.cpp.o: In function `__cxx_global_var_init.1':
> /home/Downloads/bgu_android/src/fit_and_slice_3x4.cpp:22: undefined reference to `Halide::Var::Var(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
> CMakeFiles/fit_and_slice_3x4.dir/src/fit_and_slice_3x4.cpp.o: In function `__cxx_global_var_init.2':
> /home/Downloads/bgu_android/src/fit_and_slice_3x4.cpp:22: undefined reference to `Halide::Var::Var(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
> CMakeFiles/fit_and_slice_3x4.dir/src/fit_and_slice_3x4.cpp.o: In function `__cxx_global_var_init.4':
> /home/Downloads/bgu_android/src/fit_and_slice_3x4.cpp:22: undefined reference to `Halide::Var::Var(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
> ...

What should I do to make it work ?
Any suggestions will be greatly appreciated !

**Comment by KillerInk** [comment]
I would not use the android ndk clang for building. recommend way is to trigger an external clang for building wich is made for your os.

[cmake ext clang sample ](https://github.com/KillerInk/FreeDcam/blob/cmake/app/src/main/cpp/hl-pipelines/CMakeLists.txt)

[gradle aot msvs](https://github.com/KillerInk/FreeDcam/blob/dngstack-prebuilt/halide_aot/build.gradle)

[gradle generator msvs](https://github.com/KillerInk/FreeDcam/blob/dngstack-prebuilt/halide_generator/build.gradle)

all approaches trigger an external build, and run the created binary and wait till halide is done.

an alternativ way would be to create a customized toolchain wich include halide, then your approach may work. 

greets

**Comment by durgob** [comment]
Thanks for your kindly suggestion @KillerInk  and I begin with a small [example](https://github.com/f4bsch/HalideAndroidCamera2Example) found in your FreeDcam page since I saw your comment. I keep trying to build it and finally make it works!
 Thanks again!!!

**Comment by PK15946** [comment]
Really thanks for your comment, I have learned a lot from the provided sample, and I start to understand how to build an app with halide.

**Comment by PK15946** [comment]
I'm sorry to have your time @KillerInk 

Here I am going to load an image by provided file_path and then downsample it then save it. The whole thing should be done on android device. 

I am in trouble to load an image on device to Buffer_t. 

Halide::Tools::load_image didn't work on android if I use it like

```
JNIEXPORT bool JNICALL Java_com_example_boxdownsample_MainActivity_downsample(
        JNIEnv *env, jobject obj, jstring file_path) {
...
    const char *path = env->GetStringUTFChars(file_path, NULL);
    std::string work_path = path;
    LOGD("the path is:%s", path);
    std::string input_file = work_path + "input.png";
    std::string output_file = work_path + "output.png";

    Halide::Buffer<uint16_t> input = Halide::Tools::load_image(input_file);//load_image didn't work
....
    int ret = box_downsample_halide(input, downsample_factor, output_u16); //box_downsample_halide is a static lib generated by halide generator
    ...
}
}
```
So, am I use it wrong? or
I should load it use java(that would be in bitmap format) then encode it to buffer_t, but this seems a bit hard.

It would be great if you can give me some suggestions.

Thanks!

**Comment by PK15946** [comment]
Thanks for you reply @KillerInk 
I have link a libpng build for android. But I can't get it work still. May be it just works on desktop.

**Comment by steven-johnson** [comment]
When you say "it doesn't work", can you expand a bit more? Do you get an
error? Does it crash? Is the buffer returned with garbage in it? etc

**Comment by PK15946** [comment]
Hello @steven-johnson 
I am sorry for I didn't expand it before. Here is the code with LOG
```
JNIEXPORT bool JNICALL Java_com_example_wgt_boxdownsample_MainActivity_downsample(
        JNIEnv *env, jobject obj, jstring file_path) {
    const char *path = env->GetStringUTFChars(file_path, NULL);
    std::string work_path = path;
    LOGD("the path is:%s", path);
    std::string input_file = work_path + "input.png";
    std::string output_file = work_path + "output.png";
    bool save_u8 = false;
    if (save_u8) {
        LOGD("Writing output as 8-bit.\n");
    } else {
        LOGD("Writing output as 16-bit.\n");
    }

    Halide::Buffer<uint16_t> input = Halide::Tools::load_image(input_file);
    LOGD("Loaded input: %d x %d x %d\n",
           input.width(),
           input.height(),
           input.channels());
```
and the error when I run the app
```
I/InstantRun: starting instant run server: is main process
D/AccessibilityManager: AccessibilityManager status: mPackageName = com.example.wgt.my_boxdownsample, mOptimizeEnabled = true, mIsEnabled = false, mIsUiAutomationEnabled = false, mIsInterestedPackage =false
I/zygote64: Do partial code cache collection, code=29KB, data=20KB
I/zygote64: After code cache collection, code=29KB, data=20KB
    Increasing code cache capacity to 128KB
D/native: the path is:/storage/emulated/0
    Writing output as 16-bit.
Application terminated.

```
The app has loaded the compiled .so file, but it seems that it didn't run load_image successfully(terminated before LOGD("Loaded input: %d x %d x %d\n")

Here is the CMakeLists.txt
```
cmake_minimum_required(VERSION 3.4.1)

add_subdirectory(src/main/cpp/hl-pipelines)//a generator, produce .a and .h
include_directories("${HALIDE_DIR}/include")
include_directories("${HALIDE_DIR}/tools")
#include and import png header/lib
include_directories("/home/Android/Sdk/ndk-bundle/sources/android/libpng-android/jni")
add_library(libpng STATIC IMPORTED )
set_target_properties(libpng PROPERTIES IMPORTED_LOCATION "/home/Android/Sdk/ndk-bundle/sources/android/libpng-android/obj/local/arm64-v8a/libpng.a")

add_library( # Sets the name of the library.
             my-downsample-lib
             # Sets the library as a shared library.
             SHARED
             # Provides a relative path to your source file(s).
             src/main/cpp/box_downsample_cli.cpp )//part of box_downsample_cli.cpp was shown above
target_link_libraries(my-downsample-lib hl_pipelines log dl libpng z)
```
the linked png lib can be found [here](https://github.com/julienr/libpng-android)

**Comment by steven-johnson** [comment]
Thanks for the info, but this still doesn't really help much. Why did the app terminate?

**Comment by PK15946** [comment]
Hi @steven-johnson 
I am sorry, but those are all the info I get from android studio. The app just terminate without any message  when it runs into load_image.
If I make input a null buffer rather than fill it using load_image, the app runs successfully.

**Comment by PK15946** [comment]
Finally was able to find a way to load the image and compile the apk. In case someone who also need that, I upload all the source files need to my [github](https://github.com/PK15946/Load_Image_Halide_Android).

Thanks for reply in this issue @KillerInk  @steven-johnson .

**Comment by hiepthb2020** [comment]
Hi @PK15946,
Can you share the way to load image into the Halide Buffer?

**Comment by PK15946** [comment]
I just saw your comment today @hiepthb2020 , if you still need it, here is the [code](https://github.com/PK15946/Halide-Android-example)

**Comment by Samuel-Unknown** [comment]
@PK15946 your links are unavailable, can you share it please again?
