### ISSUE TITLE
Calling Hexagon code from armv8

### ISSUE THREAD

**Issue by edubois** [halide/Halide#3496]
I'm trying to compile an app with this ABI: arm64-v8a, and I'd like to know if it's possible to call an image processing algorithm for the Hexagon architecture from the ARM code. If so, how can I do this?

**Comment by zvookin** [comment]
As the question is unanswered, generally the ```.hexagon()``` scheduling directive does an RPC to the HVX processor. However the details of that actually working depends a lot on the platform and code signing. It might be best to engage with Qualcomm directly.
