### ISSUE TITLE
Matrix Multiplication is 3x slower than OpenBLAS

### ISSUE THREAD

**Issue by mratsim** [halide/Halide#3499]
Hello team,

I'm refactoring the backend of my [deep learning library](https://github.com/mratsim/Arraymancer) and decided to try Halide today to see if it could be a match as the [TVM/mxnet team](https://github.com/dmlc/tvm) and [Facebook's Tensor Comprehension team](https://github.com/facebookresearch/TensorComprehensions) reported success using it for Deep Learning.

I gave Halide a spin through the experimental branch at https://github.com/jrk/gradient-halide.

Unfortunately the matrix multiplication example in [test/performance/matrix_multiplication](https://github.com/halide/Halide/blob/9cc042c470bbb10e3898871d390b895699f49e20/test/performance/matrix_multiplication.cpp) is extremely slow.

My test machine is a i5-5257U 2.7GHz Broadwell with a **theoretical peak of 172.8 GFlops/s** without Turbo (2.7 GHz * 32 FLOPs/cycle * 2 cores)

With the following configuration:
  - type: float32
  - size: 1920*1920*1920

This is the performance I obtain:

Backend        | Average time |  Performance
---------------|--------------|------------------
OpenBLAS       |   97.464 ms  |  145.241 GFlops/s
My own code |  103.659 ms  |  136.561 GFlops/s
Apple Accelerate | 114.519 ms | 123.611 GFlop/s
Halide         |  **332.026 ms**  |   **45.635 GFlops/s**

As you can see there is a 3x perf difference with OpenBLAS.
Compilation flags: `g++ test/performance/matrix_multiplication.cpp -g -I ./include -I ./tools -L ./bin -lHalide -o matrix_multiplication -std=c++11 -O3`

## Quick loop at implementation

Looking into the benchmark implementation, the code is the following: https://github.com/halide/Halide/blob/9cc042c470bbb10e3898871d390b895699f49e20/test/performance/matrix_multiplication.cpp#L28-L50

I also looked into `halide_blas` in app/linear_algebra folder but unfortunately couldn't benchmark it as I'm missing some include files like `halide_scopy_impl.h`

In any case the implementation seems better https://github.com/halide/Halide/blob/9cc042c470bbb10e3898871d390b895699f49e20/apps/linear_algebra/src/blas_l3_generators.cpp#L32-L158

It repacks A, if I understand the s parameter correctly it arranges the tiles so that we can issue 2x fused_multiply_add per load/store.

However I feel there will still be a gap as it's not taking into account L1, L2 cache and the TLB as well.

## Dive into assembly

Back to the example that I could run in `test/performance/matrix_multiplication` the assembly generaty is suboptimal, focusing on the inner loop:

```S
LBB1_4:                                 ## %"for matrix_mul.s1.k$x.ki"
                                        ##   Parent Loop BB1_1 Depth=1
                                        ##     Parent Loop BB1_2 Depth=2
                                        ##       Parent Loop BB1_3 Depth=3
                                        ## =>      This Inner Loop Header: Depth=4
        movq    -112(%rsp), %rbp        ## 8-byte Reload
        vbroadcastss    (%rbp,%rax), %ymm0
        vmovups -96(%r13), %ymm4
        vmovups (%rdi,%r11,4), %ymm1
        vfmadd231ps     %ymm0, %ymm4, %ymm1 ## ymm1 = (ymm4 * ymm0) + ymm1
        vmovups %ymm1, (%rdi,%r12,4)
        movq    -120(%rsp), %rbp        ## 8-byte Reload
        vbroadcastss    (%rbp,%rax), %ymm1
        vmovups (%rdi,%r9,4), %ymm2
        vfmadd231ps     %ymm1, %ymm4, %ymm2 ## ymm2 = (ymm4 * ymm1) + ymm2
        vmovups %ymm2, (%rdi,%r15,4)
        vbroadcastss    (%r10,%rax), %ymm2
        vmovups (%rdi,%rsi,4), %ymm3
        vfmadd231ps     %ymm2, %ymm4, %ymm3 ## ymm3 = (ymm4 * ymm2) + ymm3
        vmovups %ymm3, (%rdi,%rdx,4)
        vbroadcastss    (%r8,%rax), %ymm3
        vfmadd213ps     (%rdi,%rcx,4), %ymm3, %ymm4 ## ymm4 = (ymm3 * ymm4) + mem
        vmovups %ymm4, (%rdi,%rbx,4)
        vmovups -64(%r13), %ymm4
        vmovups 32(%rdi,%r11,4), %ymm5
        vfmadd231ps     %ymm4, %ymm0, %ymm5 ## ymm5 = (ymm0 * ymm4) + ymm5
        vmovups %ymm5, 32(%rdi,%r12,4)
        vmovups 32(%rdi,%r9,4), %ymm5
        vfmadd231ps     %ymm4, %ymm1, %ymm5 ## ymm5 = (ymm1 * ymm4) + ymm5
        vmovups %ymm5, 32(%rdi,%r15,4)
        vmovups 32(%rdi,%rsi,4), %ymm5
        vfmadd231ps     %ymm4, %ymm2, %ymm5 ## ymm5 = (ymm2 * ymm4) + ymm5
        vmovups %ymm5, 32(%rdi,%rdx,4)
        vfmadd213ps     32(%rdi,%rcx,4), %ymm3, %ymm4 ## ymm4 = (ymm3 * ymm4) + mem
        vmovups %ymm4, 32(%rdi,%rbx,4)
        vmovups -32(%r13), %ymm4
        vmovups 64(%rdi,%r11,4), %ymm5
        vfmadd231ps     %ymm4, %ymm0, %ymm5 ## ymm5 = (ymm0 * ymm4) + ymm5
        vmovups %ymm5, 64(%rdi,%r12,4)
        vmovups 64(%rdi,%r9,4), %ymm5
        vfmadd231ps     %ymm4, %ymm1, %ymm5 ## ymm5 = (ymm1 * ymm4) + ymm5
        vmovups %ymm5, 64(%rdi,%r15,4)
        vmovups 64(%rdi,%rsi,4), %ymm5
        vfmadd231ps     %ymm4, %ymm2, %ymm5 ## ymm5 = (ymm2 * ymm4) + ymm5
        vmovups %ymm5, 64(%rdi,%rdx,4)
        vfmadd213ps     64(%rdi,%rcx,4), %ymm3, %ymm4 ## ymm4 = (ymm3 * ymm4) + mem
        vmovups %ymm4, 64(%rdi,%rbx,4)
        vmovups (%r13), %ymm4
        vfmadd213ps     96(%rdi,%r11,4), %ymm4, %ymm0 ## ymm0 = (ymm4 * ymm0) + mem
        vmovups %ymm0, 96(%rdi,%r12,4)
        vfmadd213ps     96(%rdi,%r9,4), %ymm4, %ymm1 ## ymm1 = (ymm4 * ymm1) + mem
        vmovups %ymm1, 96(%rdi,%r15,4)
        vfmadd213ps     96(%rdi,%rsi,4), %ymm4, %ymm2 ## ymm2 = (ymm4 * ymm2) + mem
        vmovups %ymm2, 96(%rdi,%rdx,4)
        vfmadd213ps     96(%rdi,%rcx,4), %ymm3, %ymm4 ## ymm4 = (ymm3 * ymm4) + mem
        vmovups %ymm4, 96(%rdi,%rbx,4)
        addq    $4, %rax
        addq    %r14, %r13
        cmpq    $128, %rax
        jne     LBB1_4
```

we have too many loads and perf is capped by memory bandwidth.

For reference, this is the assembly in Apple Accelerate

![2018-12-13_21-46-20](https://user-images.githubusercontent.com/22738317/49966561-9940d780-ff20-11e8-9661-33e51fc1ca36.png)

The assembly generated by [my own code](https://github.com/numforge/laser/tree/9fbb8d2a573d950573c7249e3a5d6cdd784a639e/laser/primitives/matrix_multiplication)

![2018-12-13_21-43-50](https://user-images.githubusercontent.com/22738317/49966573-a52c9980-ff20-11e8-8a9a-9b2d2cc4d4c1.png)

Unfortunately I can't trace easily through OpenBLAS.

**Comment by abadams** [comment]
test/performance/matrix_multiply is not a great schedule. apps/linear_algebra is competitive though (e.g. beats eigen at large sizes), but you need to change "const int s = vec * 2" to "const int s = vec * 3". It *should* generate a similar inner loop to yours (minus the prefetch calls). We're at the mercy of llvm's instruction scheduler and it sometimes has trouble using the full 12 accumulator registers and avoiding stack spills though. 

halide_scopy_impl.h is a header generated header during the build. The makefile should be building it. Try:
```
make bin/halide_benchmarks
./bin/halide_benchmarks sgemm_notrans 2000
```

That schedule is pretty good for large matrices on single-socket machines.

Meanwhile I should fix the schedule in test/performance/matrix_multiply...

**Comment by mratsim** [comment]
Indeed, it reaches between 121 to 128 GFLOP/s with the following assembly.

![2018-12-13_22-34-41](https://user-images.githubusercontent.com/22738317/49969055-d197e400-ff27-11e8-9f75-e6bf1e24a9e4.png)


However as you said it doesn't properly use the registers, in the following assembly ymm13 is always one of the FMA and broadcast arguments so it doesn't hide broadcast latency.

From my side this can be closed, unless you want a reminder to fix the matmul bench.

**Comment by abadams** [comment]
See #3500
