### ISSUE TITLE
No device support in pipelines compiled without any device target features

### ISSUE THREAD

**Issue by jingpu** [halide/Halide#3523]
Currently, if a pipeline is compiled without any device target features, the generated code for the pipeline doesn't inspect and set dirty bits. It can be an pain point when building a large application that depends on a mixed halide libraries, some of which are build without any device target features while others do use device acceleration.

I think by default a pipeline compiled without any device features should have some minimum device support, e.g. checking the input device dirty bits and seting output host dirty.

@dsharletg @zvookin

**Comment by dsharletg** [comment]
I think there are a few things we should do here:

- Minimally, generate asserts and host dirty bit manipulations. This is close to zero overhead and so will not affect very small CPU pipelines.

- @zvookin additionally suggested that we could generate an actual call to copy_to_host via the buffer's device API pointer. If we check the dirty bits in the pipeline before calling the function, it should be very low overhead as well.

**Comment by zvookin** [comment]
The motivation for directly generating the call through the interface table is to avoid adding a runtime dependency. I expect the difference in cost between calling e.g. halide_copy_to_host and calling through the function pointer directly is fairly low, but the former requires adding a bit more code to the object file.

**Comment by abadams** [comment]
We now generate the asserts and host dirty bit manipulation. Closing.
