### ISSUE TITLE
Convert data in Android platform

### ISSUE THREAD

**Issue by nafnis** [halide/Halide#3526]
I'm working to create an instance running local_laplacian on the Android platform. After executed, the output data in format: 

Halide :: Runtime :: Buffer <uint8_t> jpeg_output (width, height, 3) ;

How to convert jpeg_output to Bitmap or save as png file?

**Comment by shoaibkamil** [comment]
Perhaps you can use one of the routines in [halide_image_io.h](https://github.com/halide/Halide/blob/master/tools/halide_image_io.h)?

**Comment by nafnis** [comment]
@shoaibkamil 
I tried including <halide_image_io.h> and used the 
Halide :: Tools :: load_and_convert_image, 
Halide :: Tools :: convert_and_save_image but the app crashed.
