### ISSUE TITLE
Internal error when estimates are not pure constants

### ISSUE THREAD

**Issue by ongjunjie** [halide/Halide#3538]
```cpp
#include <Halide.h>

int main() {
  Halide::Func f;
  Halide::Var x;

  f(x) = x;
  f.estimate(x, 0, Halide::Expr(64) + 0);
  f.compile_jit(); // left out auto_schedule to keep this example minimal

  return 0;
}
```

Running the above code gives me:

    Internal error at /usr/src/Halide/src/CodeGen_LLVM.cpp:939
    Condition failed: is_const(e)
    Should never see Handle types here.

Seems to me this first appeared in d2d2f846ed51721d2cc1679b4b3e95b315d03e67

**Comment by abadams** [comment]
Ah, we started embedding the estimates in the metadata section in the compiled objects, but I guess they're not necessarily constants. Note however that the current autoscheduler won't do anything useful with them if they're not constants. Still, we didn't intend to add this restriction (I think?). @steven-johnson

**Comment by steven-johnson** [comment]
@abadams my vague recollection is that we discussed it (briefly) and decided that constraining them to integers was fine. we could back this out, but then RunGen --use_estimates wouldn't be as reliable or useful, which would be inconvenient for autoscheduler.

**Comment by abadams** [comment]
I'm in two minds. We could easily just skip over any non-constant estimates, and treat them as missing, but really the autoscheduler in master is not going to do good things if the estimates aren't constants. I guess maybe it constant-folds them and the embedding code doesn't?

**Comment by ongjunjie** [comment]
How about allowing estimates that are solvable to constants? I hit this bug while trying to estimate the output of a pyramid function as half of the input estimates.

**Comment by steven-johnson** [comment]
SGTM.
