### ISSUE TITLE
performance_async_gpu failing for d3d12compute

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3586]
Recent Win64 buildbot tests (intermittently?) fail for performance on d3d12compute targets; performance_async_gpu in particular seems to be failing:

```
  Executing performance_async_gpu
  without async: 0.253803
  with async: 0.334356
  Using async should have been faster
```

We should investigate and fix;  if no quick fix is available, we should disable the test.

**Comment by slomp** [comment]
Thanks for reporting that.
That's likely because I'm still introducing some undesired sync points in the d3d12 queues.
It's on my radar, but I probably won't be able to start working on it immediately.
I suggest we simply disable the test if the target is `D3D12Compute` for now.

**Comment by steven-johnson** [comment]
Seems to be passing now, see https://github.com/halide/Halide/pull/6450.
