### ISSUE TITLE
make test_% v.s. make correctness_%

### ISSUE THREAD

**Issue by BachiLi** [halide/Halide#3605]
Hi,

The comments of the Makefile (https://github.com/halide/Halide/blob/master/Makefile#L5) say that we can make test_foo to build and test the file in test/correctness, while I believe it is refering to the correctness_% rule (https://github.com/halide/Halide/blob/master/Makefile#L1603). So the correct command should be make correctness_foo.

It might be a good idea to update the comments in makefile or the rules.

**Comment by steven-johnson** [comment]
We would welcome a PR to correct this.

**Comment by BachiLi** [comment]
#3606
