### ISSUE TITLE
Calling round() on an int16 Expr leads to verifyModule failure in LLVM

### ISSUE THREAD

**Issue by dsharletg** [halide/Halide#3616]
I observed this when I accidentally called Halide's `round` function on an Expr with type int16, while vectorized:

Call parameter type does not match function signature!
  %665 = sitofp <8 x i16> %664 to <8 x half>
 <8 x float>  %a70 = call reassoc nnan ninf nsz contract afn <8 x float> @round_f32x8(<8 x half> %665) #6
Both operands to FCmp instruction are not of the same type!
  %666 = fcmp reassoc nnan ninf nsz contract afn ogt <8 x half> <half 0xH7800, half 0xH7800, half 0xH7800, half 0xH7800, half 0xH7800, half 0xH7800, half 0xH7800, half 0xH7800>, <8 x float> %a70
Both operands to FCmp instruction are not of the same type!
  %667 = fcmp reassoc nnan ninf nsz contract afn ogt <8 x float> %a70, <8 x half> <half 0xHF800, half 0xHF800, half 0xHF800, half 0xHF800, half 0xHF800, half 0xHF800, half 0xHF800, half 0xHF800>
Invalid operands for select instruction!
  %668 = select <8 x i1> %667, <8 x float> %a70, <8 x half> <half 0xHF800, half 0xHF800, half 0xHF800, half 0xHF800, half 0xHF800, half 0xHF800, half 0xHF800, half 0xHF800>
Call parameter type does not match function signature!

**Comment by abadams** [comment]
Ah, I see the bug

**Comment by dsharletg** [comment]
Fixed by the above referenced PR.
