### ISSUE TITLE
Missed simplification of predicated store expressions

### ISSUE THREAD

**Issue by dsharletg** [halide/Halide#3621]
I'm writing a schedule that uses GuardWithIf to deal with unaligned output sizes, and seeing lots of if statements with conditions like this:

    if ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((t13133 + yuv.s0.x.x.x) < t12876) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -1))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -2))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -3))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -4))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -5))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -6))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -7))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -8))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -9))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -10))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -11))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -12))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -13))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -14))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -15))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -16))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -17))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -18))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -19))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -20))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -21))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -22))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -23))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -24))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -25))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -26))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -27))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -28))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -29))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -30))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -31))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -32))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -33))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -34))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -35))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -36))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -37))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -38))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -39))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -40))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -41))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -42))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -43))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -44))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -45))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -46))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -47))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -48))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -49))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -50))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -51))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -52))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -53))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -54))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -55))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -56))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -57))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -58))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -59))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -60))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -61))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -62))) && (((t13133 + yuv.s0.x.x.x)*64) < (t12745 + -63))))

It seems like the simplifier ought to be able to simplify this. It looks like it recognized that t12745 is a multiple of 64 (because it simplified the first case).

Maybe the recent #3402 will actually do this already? (I haven't updated to that branch yet.)

**Comment by pranavb-ca** [comment]
Just for my own curiosity, what was the schedule you used?

**Comment by dsharletg** [comment]
Something like this. First, I assume my output is a multiple of 128, and f is int16:

    f.split(x, xo, x, f_width / 2, TailStrategy::RoundUp) 
    f.vectorize(x, 128, TailStrategy::GuardWithif) // x can only be assumed to have an extent that is divided by 64, need GuardWithIf

I was hoping that since the predication would be true or false for a whole vector, that the simplifier would figure this out.

BTW, there's a nice way to do this so this problem doesn't happen:

    f.vectorize(x, 128, TailStrategy::RoundUp) // 128 divides the extent of x, so no problem
    f.split(x, xo, x, f_width / (2 * 128), TailStrategy::GuardWithIf)  // only scalar predication!

But I still think the simplifier should be able to handle the first case :)

**Comment by abadams** [comment]
Do you have a complete repro? I've seen this sort of thing before, but am having trouble reproducing it, even with your schedule snippet.

**Comment by abadams** [comment]
Should be fixed by that PR.
