### ISSUE TITLE
simplifying is_nan(constant) triggers assertion

### ISSUE THREAD

**Issue by BachiLi** [halide/Halide#3624]
Hi,

The current simplifier fails at the following code
```
Var x; Func f;
f(x) = is_nan(0.f);
f.realize(1);
```

I get
```
Internal error at Halide/src/Simplify_Internal.h:115
Condition failed: new_e.type() == e.type()
is_nan_f32(0.000000f) -> 0
```
when realizing the function.

**Comment by steven-johnson** [comment]
I think I see the issue. Stand by.

**Comment by BachiLi** [comment]
I think I see it too (should make_bool() in Simplify_Call.cpp), but I'll wait for your fix. Thanks : )
