### ISSUE TITLE
Investigate LLVM slowdown

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3639]
Commit 7ddf5dc5b776db9e340ca6cb7c0302703c80ab27 can cause a perplexing slowdown inside LLVM compilation; here's a (horrible) example showing pathological behavior:

```
  Var x, tx;

  ImageParam im_param{Int(32), 1, "im_param"};
  Param<int> rsize("rsize");

  RDom r(0, rsize);

  Func im = BoundaryConditions::repeat_edge(im_param);

  Func fn1;
  fn1(x, tx) += im(x + tx + r);

  Func fn2;
  fn2(tx) += fn1(r, tx);

  RVar r_xo, r_xi;
  fn2
      .update(0)
      .split(r, r_xo, r_xi, 8)
      .rfactor(r_xi, x)
      .compute_at(fn2, tx)
      .vectorize(x)
      .update(0)
      .vectorize(x);

  printf("Compiling...!\n");

  HALIDE_TIC;
  fn2.compile_jit(get_host_target()
                  .with_feature(Target::DisableLLVMLoopVectorize)
                  .with_feature(Target::DisableLLVMLoopUnroll));
  HALIDE_TOC;

  printf("Done!\n");
```

Prior to that change, this would jit-compile in well under 1000ms on my laptop; with the change in place, it typically takes ~35000ms or so. (Presumably we're handing something immensely complex to LLVM, but it's not clear to me what or why.)

**Comment by asaadaldien** [comment]
@steven-johnson On master with or without #3637 the example jit-compiles in ~ 37000ms on my laptop.

Surprisingly most of this time in induction variable simplification pass.


```
===-------------------------------------------------------------------------===
                      ... Pass execution timing report ...
===-------------------------------------------------------------------------===
  Total Execution Time: 36.1794 seconds (36.2680 wall clock)

   ---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
  35.1390 ( 97.6%)   0.1028 ( 53.5%)  35.2418 ( 97.4%)  35.3304 ( 97.4%)  Induction Variable Simplification
``` 

Can you still repro the 1000 ms in current master?

**Comment by steven-johnson** [comment]
No, I am also getting 37s in current master. Is it possible that another change made since the reversion has injected another slowdown? Or that the reversion was partial and/or incorrect?

**Comment by steven-johnson** [comment]
Yeah, this is quite the mystery. It was unambiguously a difference maker when I made the change, so *something* else has changed since then that is affecting this. (In which case, it seems likely that the real pathology was somewhere else in the first place, and the inlining change just happened to alter output just enough to expose it...)

**Comment by asaadaldien** [comment]
I will track down this and see which group of commits introduced this slow down.
On current master  do u still experience a slowdown if #3637  is reverted ?

**Comment by steven-johnson** [comment]
I have not tried reverting the rest of #3637.

**Comment by steven-johnson** [comment]
I have no idea if this issue is still relevant. Anyone?

**Comment by abadams** [comment]
I don't think so. Currently takes 1s for me.
