### ISSUE TITLE
how to use profiler profiling the halide code ??

### ISSUE THREAD

**Issue by victorygogogo** [halide/Halide#3676]
how to use profiler profiling the halide code ??
can you give an example to me for android ?

**Comment by dsharletg** [comment]
Sorry to have missed this. If this is still helpful, you can profile on android by adding the `profile` target flag to your pipeline, and looking at the output with `adb logcat | grep halide`.

It can be tricky to get the profiler output to print automatically, in which case, adding a call to `halide_profiler_report(nullptr)` after running a pipeline should show the report.
