### ISSUE TITLE
SIGSEGV  when Halide::Runtime::Internal::spawn_thread_helper 

### ISSUE THREAD

**Issue by davidweigao** [halide/Halide#3679]
Hi, 

I'm trying to use the local_laplacian example in my Android app, and getting this crash from production. I cannot reproduce this locally, the crash stack looks like something to do with synchronization from Halide runtime. Does anyone know what might cause such crash? 

```
Crash reason:  SIGSEGV
Crash thread:  0

Thread 0
0  halide.so    in par_for_local_laplacian_f3.s0.v1.v1
1  halide.so     in local_laplacian
2  halide.so     in Halide::Runtime::Internal::Synchronization::unlock_bucket_pair(Halide::Runtime::Internal::Synchronization::bucket_pair&)
3  halide.so    in Halide::Runtime::Internal::worker_thread_already_locked(Halide::Runtime::Internal::work*)
4  halide.so    in Halide::Runtime::Internal::Synchronization::unlock_bucket_pair(Halide::Runtime::Internal::Synchronization::bucket_pair&)
5  halide.so   in Halide::Runtime::Internal::worker_thread(void*)
6  halide.so    in Halide::Runtime::Internal::Synchronization::unlock_bucket_pair(Halide::Runtime::Internal::Synchronization::bucket_pair&)
7  halide.so     in Halide::Runtime::Internal::spawn_thread_helper(void*)
8  libc.so     in __pthread_start(void*)
9  libc.so    in __start_thread
```

**Comment by abadams** [comment]
That's a crash in a worker thread. The stack trace is just the normal stack trace for a worker thread.
The most probable cause is that something is wrong with your input/output halide_buffer_ts, so that when Halide tries to access memory it faults. You can diagnose this using the -debug target flag (it prints out all the buffer metadata on pipeline entry).

**Comment by davidweigao** [comment]
@abadams Yeah you're right,  I just found that I accidentally use height as weight in the dimensions of input/output buffer, which caused this SIGSEGV, when tested locally I only tested squared images.    Should've check more carefully before posting here. Thanks for replying!

**Comment by hiepthb2020** [comment]
Hi @davidweigao, 
Could you share your project about local_laplacian on Android target?
Thanks.
