### ISSUE TITLE
Supporting Unicode builds on Windows

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#3682]
In `Generator.cpp:868`, there is the following code:

```
#ifdef _WIN32
        if (LoadLibrary(lib.c_str()) != nullptr) {
            cerr << "Failed to load: " << lib << "\n";
            return 1;
        }
#else
```

That `LoadLibrary` macro is designed to select either `LoadLibraryA` and `LoadLibraryW` depending on whether or not `-DUNICODE` and/or `-D_UNICODE` are/is set. But since `lib.c_str()` returns a `const char*`, it is only compilable with the "A" (ANSI) variant. [It is preferable to use UTF-8 everywhere](http://utf8everywhere.org/#windows) but still compile in Unicode mode to prevent UTF-8 characters from leaking into ANSI-only functions.

As it stands, this code will fail to compile with Unicode support and without it, it will fail if given a path name that contains foreign characters (for example, a user's home directory).

For this code to be correct, we either need to directly call `LoadLibraryA` and declare our lack of support for plugins that use non-ANSI paths or we need to compile with Unicode on Windows and use [`MultiByteToWideChar`](https://docs.microsoft.com/en-us/windows/desktop/api/stringapiset/nf-stringapiset-multibytetowidechar) to do the encoding conversion ourselves. I think the second option is preferable. There is also the Boost.Nowide library that provides good functions to help use UTF-8 in Windows applications. It has a [standalone version](http://cppcms.com/files/nowide/html/index.html#standalone_version) that would allow us to use it without pulling in all of Boost.

**Comment by steven-johnson** [comment]
Ah, the Win32 A-vs-W API nonsense: the gift that keeps on taking :-) I'm just gonna boldly assert that we don't care about supporting any Windows that doesn't have Unicode support, so, my recommendation would be:

-- Here (and everywhere else in Halide) that we rely on any Windows API that has A-vs-W variants, we explicitly call the W version so that we are immune to however the _UNICODE definitions are set
-- For places that we receive single-char strings (like this), use MultiByteToWideChar() (etc) to to the conversion.

Re: Boost, we absolutely positively will not consider using any Boost code in Halide; even a 'standalone' version is problematic, as Halide is very reluctant to bring in dependencies on any other C++ libraries. What, specifically, is the functionality in that library that you would like to use?

**Comment by alexreinking** [comment]
> -- Here (and everywhere else in Halide) that we rely on any Windows API that has A-vs-W variants, we explicitly call the W version so that we are immune to however the _UNICODE definitions are set
> -- For places that we receive single-char strings (like this), use MultiByteToWideChar() (etc) to to the conversion.

Happy to do this quickly. I _think_ that this is the only place where we're getting bitten by this. At least, if I change it to use the "A" version, the build succeeds. Which tests exercise this functionality?

> Re: Boost, we absolutely positively will not consider using any Boost code in Halide; even a 'standalone' version is problematic, as Halide is very reluctant to bring in dependencies on any other C++ libraries. What, specifically, is the functionality in that library that you would like to use?

Ok. I'm definitely not going to push for Boost libraries (since I'm pretty allergic to them, myself). The most important functionality is `std::string` -> `std::wstring` / `char*` -> `wchar_t*` (and vice-versa) conversion functions called `narrow` and `widen`. We could roll our own and put them in Util (or elsewhere).

**Comment by alexreinking** [comment]
Also, without challenging the decision, can I ask about why Halide refuses to take any external C++ dependencies? Is it a licensing thing?

**Comment by abadams** [comment]
No, it's for minimizing the number of hoops to jump through when using Halide on a new system. Getting a recent llvm is bad enough.

**Comment by abadams** [comment]
Me installing dependencies: https://www.youtube.com/watch?v=AbSehcT19u0

**Comment by shoaibkamil** [comment]
@slomp probably has an informed opinion too on all this.

**Comment by steven-johnson** [comment]
I think this has been adequately addressed; closing. (Reopen if I am mistaken.)

**Comment by alexreinking** [comment]
@steven-johnson It has been. Thanks for closing (and sorry for forgetting!)
