### ISSUE TITLE
Sub-optimal simplification with tuples and buffer constraints

### ISSUE THREAD

**Issue by shoaibkamil** [halide/Halide#3695]
May be related to #3585, but not sure.

If I constrain the strides of a tuple, I expect the constraints to propagate and trigger simplification.  Here's an example standalone compilable generator:
```
#include "Halide.h"

using namespace Halide;

class FooGenerator : public Halide::Generator<FooGenerator> {
public:

  Input<Buffer<uint8_t>> dst1{"dst1", 2};
  Input<Buffer<uint8_t>> dst2{"dst2", 2};

  Output<Func> output{"output", 2};

  Var x, y, c;

  void generate() {


    Func foo_dst{"foo_dst"};

    Func not_output;
    not_output(x, y, c) = select(x < 1, dst1(x, y), dst2(x, y));

    output(x, y) = Tuple{not_output(x, y, 0), not_output(x, y, 1)};

    auto output_func = static_cast<Func>(output);
    for (int d = 0; d < 2; d++) {
      output_func.output_buffers()[0].dim(d).set_min(dst1.dim(d).min());
      output_func.output_buffers()[0].dim(d).set_extent(dst1.dim(d).extent());
      output_func.output_buffers()[0].dim(d).set_stride(dst1.dim(d).stride());
      output_func.output_buffers()[1].dim(d).set_stride(dst1.dim(d).stride());
    }
    Var tx, ty;
    output.gpu_tile(x, y, tx, ty, 32, 16, TailStrategy::GuardWithIf);
  }
};

HALIDE_REGISTER_GENERATOR(FooGenerator, foo)

```

The generated stmt file contains:
```
...
    let t42 = ((dst1.min.0 - (output.1.min.1*output.1.stride.1)) - output.1.min.0)
    let t41 = ((dst1.min.0 - (output.0.min.1*output.0.stride.1)) - output.0.min.0)
...
output.0[((((((output.s0.v1.v1.__block_id_y*16) + dst1.min.1) + .__thread_id_y)*output.0.stride.1) + ((output.s0.v0.v0.__block_id_x*32) + t41)) + .__thread_id_x)] = output.0.value
                output.1[((((((output.s0.v1.v1.__block_id_y*16) + dst1.min.1) + .__thread_id_y)*output.1.stride.1) + ((output.s0.v0.v0.__block_id_x*32) + t42)) + .__thread_id_x)] = output.1.value
...
```

Since `output.1.min.1==output.0.min.1==dst1.min.1` and `output.1.stride.1==output.0.stride.1==dst1.stride.1` and `output.1.min.0==output.0.min.0==dst1.min.0`, I would expect `t42==t41` and the two output statements to write to the same offset in the buffer, instead of redundantly computing the offsets.

**Comment by shoaibkamil** [comment]
@abadams I'm happy to take a stab at fixing this myself, but any guidance you could offer on where in the simplifier to look would be super helpful.

**Comment by abadams** [comment]
This is not at all working as intended. I really though we only used the strides/mins/etc from the first buffer in the tuple. I don't think it's necessarily simplifier related. I'll try to repro locally and figure out what the hell is going on.

**Comment by abadams** [comment]
ok, I don't know where this went off the rails, but the simplest fix is a trivial change to the simplifier, so I'll just open a PR.

**Comment by shoaibkamil** [comment]
Thanks!  I appreciate it-- will check against the fairly complicated pipelines where I was observing it.
