### ISSUE TITLE
Should glsl() enforce chunky-RGBA layout checking?

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#371]
Currently, it appears you can use glsl() on a buffer with an arbitrary declared layout; it would probably make sense to require that a function scheduled this way have input and output layouts that are predictable... e.g.,  chunky RGBA, with extent[2]=4, stride[0]=4, stride[2]=1.

**Comment by dsharletg** [comment]
I think this issue is obsolete now that glsl is removed.
