### ISSUE TITLE
`prefetch` can't express efficient fine-grained prefetching

### ISSUE THREAD

**Issue by dsharletg** [halide/Halide#3735]
I have some intrinsics code where __builtin_prefetch helps a lot. This code reads small tiles of an input, so hardware prediction of the next address probably struggles with this. The prefetching strategy that works well is this:

    for y:
      for x:
        // Prefetch next line's x value.
        __builtin_prefetch(base + (y + 1) * stride_y) + x * 8)
        // Load current line's x value.
        uint16x8 = load(base + y * stride_y + x * 8)
        // work
        ...

The problem is that Halide's `prefetch` directive can't express this: it takes a buffer, a loop variable, and an offset to describe which iteration of *that* loop to prefetch. This can only describe either prefetching the next value of `x`, or the next whole row of `y`. The issue with the latter option is that it tends to generate a lot of overhead.

One option would be to try to reduce the overhead. I think prefetching the next whole row of y should work in some cases, but the generated code isn't as simplified as the loop itself (for example, a real loop over x gets generated that has a non-static iteration count, even though the actual loop over x does). However, even if that were to be fixed, I suspect there are pipelining advantages to just dropping a single prefetch in the middle of an instruction stream, over generating a bunch of prefetches all at once.

Another option would be to add a parameter to `prefetch`:

    Stage &prefetch(const Func &f, VarOrRVar where, VarOrRVar next, Expr offset = 1,
                    PrefetchBoundStrategy strategy = PrefetchBoundStrategy::GuardWithIf);

- `where` would be the loop to place the prefetch in
- `next` and `offset` would determine the bounds of the thing to prefetch

I think there's some trickiness to doing this. One thing in particular, if `where` is a small inner loop, we don't want any overhead surrounding the prefetch (no loops to traverse to cover a `Box` of bounds).

**Comment by steven-johnson** [comment]
Pretty sure this is addressed by #6155
