### ISSUE TITLE
Add LLVM 8, consider dropping LLVM 6

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3744]
LLVM 8 is now officially announced; we should ensure we have test coverage for it.

Since we have a policy of (generally) supporting trunk-minus-2, we should now consider a timetable for dropping LLVM6.

**Comment by steven-johnson** [comment]
https://github.com/halide/Halide/pull/3750

**Comment by dsharletg** [comment]
Fixed by #3854
