### ISSUE TITLE
Recent dramatic slowdown in compute_at + GuardWithIf splits

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3755]
Sometime since ~Mar 13 (commit 305f2cd392c72f62204dcb5af9981aea9b478397), compilation of simple code using these patterns has gotten dramatically slower, with the bulk of the time (apparently) spent in LLVM. A very simple repro:

```
    Var x, xo, xi;
    ImageParam input(UInt(8), 1);

    Func f, output;
    f(x) = input(x);
    output(x) = f(x);

    f.compute_at(output, xo).vectorize(x, 8, TailStrategy::GuardWithIf);
    output.split(x, xo, xi, 256, TailStrategy::GuardWithIf);

    HALIDE_TIC;
    output.compile_jit();
    HALIDE_TOC;
```

On my Mac laptop, the call to compile_jit() now takes ~ 75 seconds. (More complex pipelines can take dramatically longer.)

**Comment by steven-johnson** [comment]
FYI, the Halide-level IR for this is different for 'before' and 'after', the change above, but nothing that looks obviously pathological to my eye. (Interestingly, they both produce bitcode outputs of nearly the same size, but one takes much much longer to do so.)

@alinas is going to take a look from the LLVM side, to rule out the possibility that a minor change on our side has triggered some latent-but-undiscovered pathology in trunk LLVM.

**Comment by steven-johnson** [comment]
git bisect confirms the slowdown injection point is commit 94dd9b35be583a76e51b89ea805ce5cf936475eb from https://github.com/halide/Halide/pull/3720 -- tagging @abadams as an FYI.

@alinas indicates that there is possible pathology in llvm::ScalarEvolution pass (and evidence of at least one Halide-related cap there already), so there's a real possibility that this is a case of Halide tickling a latent LLVM problem via code restructuring; that said, it's not clear yet if the best fix is on the Halide side or the LLVM side (or some combination).

**Comment by alinas** [comment]
We need to fix this on the LLVM side. See: https://bugs.llvm.org/show_bug.cgi?id=41225

**Comment by abadams** [comment]
I don't have access to the IR, but looking at the .ll from that bug report, it looks like a deeply nested min/max tree in the inner loop. I wonder how many of those terms actually depend on the loop variable. We have GroupLoopInvariants in LICM to try to separate the terms that don't depend on the loop variable for chains of additions, but nothing similar for chains of mins/maxs. Might that help?

**Comment by abadams** [comment]
(The reason I go to this explanation is that a side-effect of the change is to substitute mins/maxes inwards more aggressively in some cases, potentially making deeply-nested things).

**Comment by alinas** [comment]
It's probably a good idea if Halide can refrain from generating the long min/max chains, for performance reasons. The way LLVM should treat pathological cases is to give up, not spend this long compiling. So this issue probably needs fixes on both sides: (i) in LLVM to add the cap, and (ii) in Halide to avoid generating this pattern, but not for compile time (that's solved by (i)), but for run time.

**Comment by abadams** [comment]
Steven, could you check if the IR contains expressions which could have been lifted out of an inner loop if some mins/maxes were reassociated?

**Comment by steven-johnson** [comment]
The main loop of this IR looks like this:

```
    for (output.s0.x.xo, 0, t31) {
      let f.x.extent_realized.s = (output.extent.0 - (output.s0.x.xo*256))
      allocate f[uint8 * min(f.x.extent_realized.s, 256)]
      let f.s0.x.loop_extent.s = (output.extent.0 - (output.s0.x.xo*256))
      produce f {
        let f.s0.x.x.epilogue.s = min(min((min(min((min(min((min(min((min(min((min(min((min(min((min(f.s0.x.loop_extent.s, 256) + 1), f.s0.x.loop_extent.s), 256) + 1), f.s0.x.loop_extent.s), 256) + 1), f.s0.x.loop_extent.s), 256) + 1), f.s0.x.loop_extent.s), 256) + 1), f.s0.x.loop_extent.s), 256) + 1), f.s0.x.loop_extent.s), 256) + 1), f.s0.x.loop_extent.s), (min(f.s0.x.loop_extent.s, 256) + 7))
        let t33 = max((min(f.s0.x.x.epilogue.s, 256)/8), 0)
        let t34 = ((output.s0.x.xo*256) + t32)
        for (f.s0.x.x, 0, t33) {
          f[ramp((f.s0.x.x*8), 1, 8) aligned(8, 0)] = input[ramp(((f.s0.x.x*8) + t34), 1, 8)]
        }
        let t39 = (output.s0.x.xo*256)
        let t40 = (output.extent.0 - t39)
        let t41 = min(t40, 256)
        let t42 = (t41 + 7)
        let t43 = min(min(min((min(min((min(min((min(min((min(min((min(min((min(min((t41 + 1), t40), 256) + 1), t40), 256) + 1), t40), 256) + 1), t40), 256) + 1), t40), 256) + 1), t40), 256) + 1), t40), t42), 256)
        let t36 = (max((max(t42, t43)/8), 0) - max((t43/8), 0))
        let t35 = max((min(f.s0.x.x.epilogue.s, 256)/8), 0)
        let t37 = min(f.s0.x.loop_extent.s, 256)
        let t38 = (t32 + t39)
        for (f.s0.x.x, t35, t36) {
          let f.s0.x.v4.new_max.s = (t37 - (f.s0.x.x*8))
          let t47 = (f.s0.x.x*8)
          let t44 = min(f.s0.x.v4.new_max.s, 8)
          let t45 = (t38 + t47)
          for (f.s0.x.v4, 0, t44) {
            f[(f.s0.x.v4 + t47)] = input[(f.s0.x.v4 + t45)]
          }
        }
      }
      consume f {
        let t48 = (output.s0.x.xo*256)
        for (output.s0.x.xi, 0, 256) {
          output[(output.s0.x.xi + t48)] = f[output.s0.x.xi]
        }
      }
      free f
    }
```
there are nice long chains in there, but they are heavily dependent on the loop var. (And it's a weird expression; surely it could be simplified further.)

**Comment by steven-johnson** [comment]
Seems like a simplifier rule of the sort `min(min(x, y) + c0, x) -> min(x, y + c0)` would be profitable here (assuming c0 > 0)

**Comment by alinas** [comment]
This should be resolved by https://reviews.llvm.org/rL357320.
