### ISSUE TITLE
correctness_simplify reporting 'failed to prove'

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3779]
I'm gonna assume that getting this warning from the simplify test means something is broken or suboptimal.

Do: `HL_DEBUG_CODEGEN=1 make -j8 correctness_simplify`

Output:

```
Failed to prove, but could not find a counter-example:
 (v0 != 2)
Original expression:
!(x == 2)
Success!
```

**Comment by abadams** [comment]
This is actually benign. That warning means the expression didn't simplify to true, but plugging in a bunch of random constants for the variables didn't produce any cases where it's false, so maybe this is a useful test case to improve the simplifier with. But in this case it just means it never tried the constant '2'. We should special case a few things like this in the counter-example-hunting code to avoid these less useful ones.

**Comment by steven-johnson** [comment]
Fair. Maybe also consider rewording the output text to make it clear that this is a non-bug.
