### ISSUE TITLE
'halide_library' can't link generated library

### ISSUE THREAD

**Issue by AlexanderGarmash** [halide/Halide#3810]
Hello, faced with issue, when using `halide_library`:
`No rule to make target 'genfiles/my_lib_CPU/my_lib_CPU.a', needed by 'apps/my_app`

1). Defined Halide library:
```
halide_library(my_lib${CUR_SUFFIX}
        SRCS aot_generator_my_lib.cpp
        GENERATOR_DEPS image_processing
        GENERATOR_NAME my_lib
        FUNCTION_NAME my_lib
        HALIDE_TARGET ${HALIDE_TARGET}
        HALIDE_TARGET_FEATURES ${HALIDE_TARGET_FEATURES}
        )
```
`${CUR_SUFFIX}` in this case is **CPU**, but also can be **GPU**

2). Trying to link to defined library:
```
target_link_libraries(${LIBRARY_NAME} PRIVATE my_lib${CUR_SUFFIX})
```

And now I get this error. Generated library files:
```
- my_lib.h
- my_lib.a
- my_lib.registration.cpp
```

I want my function to be called  `my_lib`, without CPU suffix, because I can change implementation in runtime, But for library, to be called `my_lib_CPU` - is OK for me.
Last commit in my source tree of Halide is
```
commit 406cd214115d6be939ecc1ef6f9f10729493189c
Merge: 3d45ba9 294133b
Author: Andrew Adams <andrew.b.adams@gmail.com>
Date:   Wed Feb 20 10:57:37 2019 -0800

    Merge pull request #3565 from jia-kai/fix-runtime-cuda-init
    
    Fix race conditions during CUDA runtime initialization
```

I would like to know, is it intended behavior or bug?
If this a bug, can I create a PR to fix it? I don't want to store another repo for Halide, just for that fix

**Comment by steven-johnson** [comment]
What build OS / compiler / etc are you using as a host system?

**Comment by steven-johnson** [comment]
(And yes, if this is a bug, we always welcome fixes :-)

**Comment by AlexanderGarmash** [comment]
Ubuntu 16.04, llvm 6.0, clang version 6.0.1 (branches/release_60 354315)
The problem was in the line `HALIDE_REGISTER_GENERATOR(TMyLibApplier, my_lib)`
So, I add suffixes to target `my_lib${CUR_SUFFIX}` through the compile definitions + `#ifdef`, then generated library name changes as expected
