### ISSUE TITLE
[discussion] Compile ALL runtime modules on Windows with LLVM target "pc-windows-msvc"

### ISSUE THREAD

**Issue by slomp** [halide/Halide#3815]
In an attempt to ease the development and reach of the d3d12 back-end, it would be nice if we could get rid of the [assembly thunks](https://github.com/halide/Halide/blob/master/src/runtime/d3d12_abi_patch_64.ll). A uniform, portable solution would automatically enable x86 32bit support as well as Windows-on-ARM.

**Comment by slomp** [comment]
*Tom Tan* from Microsoft diagnosed the following:

"It seems the COM ABI problem is caused by the 64-bit target triple as below in CMakeLists.txt. Passing caller allocated memory as hidden parameter for Windows is different than the general one. I tried change below le64-unknown-unknown-unknown to x86_64-pc-windows-msvc and replaced all the Call_* thunk by direct interface call, like descriptorHeap->GetCPUDescriptorHandleForHeapStart() and verified it works. Specify the right target triple for Windows is important to interop with other Windows components."

and prompted this question:

"Do you think we could fix the target triple for Windows target? In this way, we no longer need assembly routines for ABI adaption."

**Comment by slomp** [comment]
In a follow-up:

"I looked at the issue in more detail, I think it makes sense to change the 64-bit ABI in `CMakeLists.txt` to `x86_64-pc-windows-msvc` for all `runtime\*.cpp` files, if it is compiling for Windows x64. The LLVM bit code stored in Halide.dll are compiled with x86_64-pc-windows triple to executable code at runtime (this is set in Halide code before calling into LLVM JIT), or if it uses other non-Windows ABI, the generated code will be totally not runnable, because even the register parameter passing is different which is not solved by the current assembly thunk. Your assembly thunk only handles ABI distinction of passing hidden caller allocated return value. This part of ABI is handled by Clang front-end, not LLVM back-end.

So in brief for Windows x64 target, LLVM back-end in Halide.dll compiles bit code with x86_64-pc-windows-msvc, but some ABI are honored in Clang front-end which is specified in the previous CMakeLists.txt."

"So I think it makes sense to make this change for all runtime .cpp files, how do you think? In any case this could cause problem?"

**Comment by slomp** [comment]
"There is one potential problem of changing  the ABI globally. If x64 Halide.dll could be called to do AOT and generates objects files for non-Windows, like Linux, this change will not work. Is this supported scenario?"

**Comment by slomp** [comment]
I'm inviting @steven-johnson, @zvookin, @abadams and @shoaibkamil to join this discussion.

I am mostly concerned about the implications when compiling Halide through Cygwin or MSYS/MinGW.
There's also the issue with weak symbol linkage which, as far as I know, MSVC can't handle.

**Comment by slomp** [comment]
In the most recent follow-up:

"For weak symbols, I think it is fine because it is still compiled by Clang with MSVC ABI. I think Clang supports it even in this MSVC compatibility mode.

The name mangling issue could be solved by using simple/consistent naming scheme like `extern “c”`, but there are further issues to link LLVM IL files compiled from different triple. Like below LLVM module flag in LLVM IL file is different for the 2 triples, which triggers LLVM link error."

```
// le64-unknown-unknown-unknown
!0 = !{i32 1, !"wchar_size", i32 4}

// x86_64-pc-windows-msvc
!0 = !{i32 1, !"wchar_size", i32 2}
```

"There was some discussion on similar issue in below link.
https://github.com/halide/Halide/issues/924"

**Comment by shoaibkamil** [comment]
> "There is one potential problem of changing the ABI globally. If x64 Halide.dll could be called to do AOT and generates objects files for non-Windows, like Linux, this change will not work. Is this supported scenario?"

This is definitely a supported scenario, and making it impossible to generate AOT code for other platforms in Windows is a strong reason not to do this.

**Comment by abadams** [comment]
It would also mean we couldn't cross compile from other OSes to windows. We very intentionally do initial assembly of the runtime modules into bitcode using a generic target triple, and then fix-up the target triple later. This is problematic whenever clang does something target-triple-dependent in the initial assembly. In the past we've always been able to work around it.

**Comment by abadams** [comment]
Although for any runtime modules that are platform-and-os-specific we could specialize the initial target triple.

**Comment by ThomsonTan** [comment]
> Although for any runtime modules that are platform-and-os-specific we could specialize the initial target triple.

This problem of this approach is runtime modules compiled with different target triples might not link to each other, like for `le64-unknown-unknown-unknown` and `x86_64-pc-windows-msvc`， because each target has different data layout, and the definition of some common data type is not consistent (`wchar_size`).

**Comment by abadams** [comment]
We already deal with that issue by being very careful and explicit with our struct layouts, and only using a very narrow range of types, all with explicit widths.

**Comment by abadams** [comment]
Note that this all falls into the bucket of clang doing target-triple-dependent things. We fix the target triples on the bitcode before proceeding with compilation (e.g. linking modules), so anything target-triple-dependent that happens later is fine.

**Comment by ThomsonTan** [comment]
Yes, Clang does target-triple-dependent things for Windows ABI, like the order of hidden caller allocated memory for return value, this is hard-coded into LLVM bitcode before Halide passing the correct target triple to continue compilation.

**Comment by slomp** [comment]
One thing I find puzzling is why the C-interface to D3D12 does not work even on MSVC using the standard headers. If the C-Interface to D3D12 worked, I think we could use it to write a more portable back-end, since it does not really need to follow the COM ABI.

**Comment by abadams** [comment]
I think isolating the d3d12 calls in a single module (which they already are, I think) then assembling that module with the msvc target triple seems like a tenable solution. Interfaces between modules, where they even exist, should not rely on anything target-dependent. Mostly it's via HalideRuntime.h, which is careful to be triple-independent.

**Comment by ThomsonTan** [comment]
@slomp , some C-interfaces of D3D12 don't work is a similar but separate issue. C doesn't understand `this` pointer and always passing the hidden parameter as the first parameter, so explicit `_This` parameter for C will actually be after the hidden parameter. But in C++ mode of MSVC, hidden parameter is passed after `this` pointer, which is actually the 2nd parameter. So C caller and C++ callee don't agree on the parameters order and cause failure.

**Comment by slomp** [comment]
Yes, I am aware of that, and all methods accessed through the C-Style interface in `lpVtbl` have the object pointer as the first parameter. At the same time, I thought the goal of the C-style interface provided by COM interfaces was to circumvent any peculiarities of the C++ COM ABI. Apparently, `lpVtbl` is just aliased in memory with the C++ virtual dispatch table pointer then.

**Comment by slomp** [comment]
@ThomsonTan What do you think about @abadams proposed solution above? should we isolate the D3D12 calls into a module, build that module with the triplet, and have the d3d12compute runtime just call them?

**Comment by alexreinking** [comment]
A year later... is this still relevant?

**Comment by abadams** [comment]
I believe it's still something that could be cleaned up.

**Comment by slomp** [comment]
Still relevant; resurrecting the issue here:
https://github.com/halide/Halide/issues/5156

**Comment by slomp** [comment]
Working on it here:
https://github.com/halide/Halide/compare/slomp/d3d12-abi-fix

**Comment by slomp** [comment]
Moving the discussion permanently to here:
https://github.com/halide/Halide/issues/5156
