### ISSUE TITLE
fuzz_simplify error

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3818]
In a test using the WebAssembly branch (master= a0b07c050 plus changes that should be unrelated), a random run of correctness_fuzz_simplify failed with:

```
Simplify fuzz test seed: 1555357246
a = uint16(a)
b = uint16(e)
c = (uint16)65527
d = (uint16)95
e = uint16(d)
uint16(max(uint8(d), (max(uint8(c), uint8(d)) + (uint8)87)))
uint16((max(uint8(c), uint8(d)) + (uint8)87))
In vector lane 0:
uint16(max(uint8(d), (max(uint8(c), uint8(d)) + (uint8)87))) -> (uint16)95
uint16((max(uint8(c), uint8(d)) + (uint8)87)) -> (uint16)78
```

(Note that this is with target=host so the wasm changes should be irrelevant)

**Comment by steven-johnson** [comment]
Verified that this replicates at commit a0b07c0507266eb3f72669ccac4e1142acada32d

**Comment by abadams** [comment]
Oops, I see the problem. Fix incoming.
