### ISSUE TITLE
Unexpected "calls function in unbounded way"

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3824]
Given the following snippet:

```
    Var x, y;

    Param<uint16_t> uint16_val;
    Param<float> float_val;

    Func rate;
    rate() = u32_sat(clamp(float_val, 1.f, 1000.f));
    rate.compute_root();

    Func intermed;
    intermed(x, y) = uint16_val;
    intermed.compute_root();

    Func result;
    result(x, y) = intermed(x, y * rate());
    result.compute_root();

    result.compile_jit();

```

It's pretty clear that `rate()` is well-bounded, but running this results in 

```
The pure definition  of Function result calls function intermed in an unbounded way in dimension 1
```

Using `u32` instead of `u32_sat` makes the error go away.

**Comment by abadams** [comment]
u32_sat produces slightly more complex IR, which gets mutated by CSE to lift out a common subexpression. This ruins the ability of bounds to prove that the cast doesn't overflow, which means it can't propagate the bounds of the float to the uint. Not sure what to do about this yet.

**Comment by steven-johnson** [comment]
Here's a slightly more-complex snippet that demonstrates the same problem (even after #3825 has landed):

```
    Var x, y;

    ImageParam input(UInt(16), 2);
    Param<float> float_val;

    Expr f_rate = clamp(float_val, 1.f, 1000.f);

    Func rate;
    rate() = u32_sat(f_rate);
    rate.compute_root();

    Func ylut;
    ylut(y) = y * rate();
    ylut.compute_root();

    Func result;
    result(x, y) = input(x, ylut(y));
    result.compute_root();

    result.compile_jit();
```

->

`Buffer input may be accessed in an unbounded way in dimension 1`

**Comment by abadams** [comment]
This one isn't easily fixable and switching to u32 makes no difference. The range of ylut is genuinely unbounded, because func-value-bounds-inference assumes that the y coordinate could take on arbitrary values. In this case you'd need an explicit clamp.

**Comment by steven-johnson** [comment]
> The range of ylut is genuinely unbounded

True! I excerpted this from a case that had been previously working but started failing after a minor change was made; let me go back and find a better example.

**Comment by steven-johnson** [comment]
Closing as stale.
