### ISSUE TITLE
ARM backends are really bad at generating mlal

### ISSUE THREAD

**Issue by dsharletg** [halide/Halide#3851]
I have found that almost none of my code is generating mlal, and instead is generating widening + full width mla instructions. The problem seems to be that LLVM aggressively "optimizes" to zext instead of sext LLVM instructions for most of my operands to mul, and then LLVM's pattern fails to match (https://github.com/earl/llvm-mirror/blob/master/test/CodeGen/AArch64/aarch64-smull.ll).

Looking at arm_neon.h (https://github.com/Cronus-Emulator/clang/blob/master/include/arm_neon.h#L2074-L2085), I think the solution is to match  mull ourselves, and then LLVM will figure out the mlal part.

**Comment by abadams** [comment]
😠 

I agree with your proposed solution
