### ISSUE TITLE
Halide Select Function Question

### ISSUE THREAD

**Issue by misty7815** [halide/Halide#3866]
Why the following  select function didn't work,  just one condition is failed  , the execution result always shows , 
  "Input buffer b0 is accessed at 15, which is beyond the max (13) in dimension 0"
I have using condition to make sure x is little than "x < input.dim(0).extent()"   

=============The original code is as following======================
    Halide::Buffer<float> input(14, 14, 4, 10);
    Halide::Buffer<float> filter(3, 3, 4, 32);
    Halide::Buffer<float> bias(32);
    Halide::Buffer<float> output(14, 14, 32, 10);

    Halide::Func f_conv("conv");
    Halide::Func f_pad("pad");
    Halide::RDom r(filter.dim(0).min(), filter.dim(0).extent(),
                   filter.dim(1).min(), filter.dim(1).extent(),
                   filter.dim(2).min(), filter.dim(2).extent());

    f_pad (x, y, z, n) = select ( x < input.dim(0).extent() ,
                                  input(x, y, z, n),
                                  print (2.0f, "<- this is (", x, ") y=", y, "z=", z, "n =", n)
                                );
    f_conv(x, y, z, n) = bias(z);

    f_conv(x, y, z, n) += filter(r.x, r.y, r.z, n) * f_pad(x + r.x, y + r.y, r.z, n);
    f_conv.realize(input.dim(0).extent(), input.dim(1).extent(), input.dim(2).extent(), input.dim(3).extent());

**Comment by zvookin** [comment]
The select function is a vector select. Semantically, it always evaluates
both sides of the selection.

Generally you want to use a function from the Halide::BoundaryConditions
namespace to do the above. Something like:
    f_pad = Halide::BoundaryConditions::constant_exterior(input, 2.0f,
input.dim(0).min(), input.dim(0).extent());
(This only establishes the condition on the first dimension, x and does so
on both sides. This may or may not be what you desire.)

-Z-

*From: *misty7815 <notifications@github.com>
*Date: *Sun, May 5, 2019 at 2:22 AM
*To: *halide/Halide
*Cc: *Subscribed

Why the following select function didn't work, just one condition is failed

**Comment by misty7815** [comment]
Thanks for replay concept of select function and the solution is work for me

**Comment by misty7815** [comment]
Thanks for replay concept of select function and the solution is work for me

**Comment by steven-johnson** [comment]
Sounds like this is resolved. Closing.
