### ISSUE TITLE
Halide installation error

### ISSUE THREAD

**Issue by zendevil** [halide/Halide#3874]
Using make to install Halide gives the following error:

```
/home/zendevil/Desktop/gradient-halide/src/CodeGen_LLVM.cpp: In lambda function:
/home/zendevil/Desktop/gradient-halide/src/CodeGen_LLVM.cpp:1092:46: error: ‘createThreadSanitizerPass’ was not declared in this scope
             pm.add(createThreadSanitizerPass());
                                              ^
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
cc1plus: all warnings being treated as errors
Makefile:918: recipe for target 'bin/build/CodeGen_LLVM.o' failed
make: *** [bin/build/CodeGen_LLVM.o] Error 1
```

**Comment by abadams** [comment]
I think you may be using the gradient-halide fork of Halide, not Halide from this repository. Line 1092 in our CodeGen_LLVM.cpp is not the one indicated in your error message. That version of Halide was for a research project, and isn't necessarily kept up to date with LLVM API changes. If you want one of the features of that fork that wasn't merged into master, you could try using an older LLVM version with it.

**Comment by zendevil** [comment]
So the differentiation feature hasn't been merged into master yet?

**Comment by abadams** [comment]
Differentiation has been merged into master, but nothing else from that fork (the specialized autoscheduler and the pytorch glue).

**Comment by zendevil** [comment]
> you could try using an older LLVM version with it.
Which LLVM version specifically?

**Comment by abadams** [comment]
llvm 7 is probably a safe bet. You might also want to open an issue directly on that repository though - it's not maintained by the same people as this one.
