### ISSUE TITLE
Halide generator to auto-scheduler issue

### ISSUE THREAD

**Issue by misty7815** [halide/Halide#3875]
There are issue about the same algorithm with two different implementation get out different result , can anyone help figure out what is root cause
1. The algorithm with main function implemented as ".realize()" is successful 
2. Failed in generator with auto schedule and input / output set_estimate_bound, 

Is the reason caused by  "inBound(x + r.x - 1, y + r.y - 1, r.z, n);"  or set_estimate_bound wrong usage?

/*********************   No Generator Code  ****************************  /
   `Halide::Var x("x"), y("y"), z("z"), n("n");

    Halide::Func f_conv("conv");
    Halide::Func inBound("inBound");
    Halide::Func f_ReLU("relu");

    Halide::RDom r(filter.dim(0).min(), filter.dim(0).extent(),
               filter.dim(1).min(), filter.dim(1).extent(),
               filter.dim(2).min(), filter.dim(2).extent());

    inBound = Halide::BoundaryConditions::constant_exterior(
            input, 0, 0, input.dim(0).extent(), 0, input.dim(1).extent());

    f_conv(x, y, z, n) = bias(z);

    f_conv(x, y, z, n) += filter(r.x, r.y, r.z, z) * inBound(x + r.x - 1, y + r.y - 1, r.z, n);

    f_ReLU(x, y, z, n) = max(0, f_conv(x, y, z, n));

    Halide::Buffer<float> output = f_ReLU.realize(14, 14, 32, 10);

    p = getConv2DGolden(length);

    Halide::Buffer<float> golden(14, 14, 32, 10);

    compare(reinterpret_cast<const float*>(output.raw_buffer()->host),
            reinterpret_cast<const float*>(golden.raw_buffer()->host),
            length);
` 
/***************** With Generator to auto-schedule code **********************************/

`
void generate() {
        /* THE ALGORITHM */

        Var x("x"), y("y"), z("z"), n("n");

        Func f_conv("conv");
        Func inBound("inBound");
        RDom r(filter.dim(0).min(), filter.dim(0).extent(),
               filter.dim(1).min(), filter.dim(1).extent(),
               filter.dim(2).min(), filter.dim(2).extent());

        inBound = Halide::BoundaryConditions::constant_exterior(
            input, 0, 0, input.dim(0).extent(), 0, input.dim(1).extent());

        f_conv(x, y, z, n) = bias(z);

        f_conv(x, y, z, n) += filter(r.x, r.y, r.z, z) * inBound(x + r.x-1 , y + r.y-1 , r.z , n );

        f_ReLU(x, y, z, n) = max(0, f_conv(x, y, z, n));

        /* THE SCHEDULE */

        if (auto_schedule) {
            // Provide estimates on the input image
            input.dim(0).set_bounds_estimate(0, 14);
            input.dim(1).set_bounds_estimate(0, 14);
            input.dim(2).set_bounds_estimate(0, 4);
            input.dim(3).set_bounds_estimate(0, 32);

            filter.dim(0).set_bounds_estimate(0, 3);
            filter.dim(1).set_bounds_estimate(0, 3);
            filter.dim(2).set_bounds_estimate(0, 4);
            filter.dim(3).set_bounds_estimate(0, 32);

            bias.dim(0).set_bounds_estimate(0, 32);

            // Provide estimates on the pipeline f_ReLU
            f_ReLU.estimate(x, 0, 14)
                .estimate(y, 0, 14)
                .estimate(z, 0, 32)
                .estimate(n, 0, 10);
        }
`

**Comment by steven-johnson** [comment]
Looks like no one ever responded to this -- is it still open/actionable?

**Comment by steven-johnson** [comment]
Closing as there is no response.
