### ISSUE TITLE
Halide::Runtime::Buffer could have smaller code size. Is it worthwhile?

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3903]
From a casual inspection, it looks like many of the templated functions in  Halide::Runtime::Buffer<> have a lot of code content that doesn't really depend on any of the template arguments; some refactoring of these methods (into a well-typed public method, and an implementation method that works on a Buffer<void>, or just a halide_buffer_t) would probably lead to code size savings. (This is especially true for methods that take multiple buffers or possibly different types, e.g. make_with_shape_of(), for_each_value(), etc). 

The question is whether this code size reduction would be large enough to be worth the effort; for something like halide_image_io.h (which instantiates an insane number of combinations), it probably would (based on an inspection of `nm RunGenMain.o`), but it's not clear how much it matters to "real-world" code.

**Comment by alexreinking** [comment]
How would you suggest measuring an improvement for this? Look at the total binary sizes of the tests and apps after a build, maybe?

**Comment by abadams** [comment]
In #3619 I was mostly focused on the size of bin/build/RunGenMain.o, but yeah aggregating over the process/filter binaries in the apps is probably the right thing

**Comment by steven-johnson** [comment]
The immediate pain point has been addressed, so I'm going to close this. Reopen if you think it warrants future work.
