### ISSUE TITLE
Do we still need MinGW support?

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3908]
As discussed briefly on Gitter: MinGW support was added primarily as a developer-friendly option (to allow easier Unixy dev options on Windows systems); the advent of bash-on-windows on modern Windows 10 systems is arguably a much better solution for this use case.

Dropping this would allow us to reduce buildbot load on Windows (though we might need to add bash-on-windows instead so this might be a wash), and would also allow us to eliminate corner cases (e.g. mingw is the only Makefile-using client that doesn't support weak linkage, so incautiously written makefiles can easily break there). 

Opening an issue to see what the community thinks.

**Comment by slomp** [comment]
It would be nice to have well-tested support for MinGW, but it's probably an unnecessary burden in terms of maintainability.

**Comment by peteraarts811** [comment]
I am currently using Halide for our development. 
We use the binary download of Halide in combination with MinGW.

It is not clear to me whether the MinGW support mentioned here is about this situation, 
or the situation in which Halide is downloaded as source code only (which we do not do).

In general I consider myself a 'user' of Halide, not a 'developer' of Halide:
I use Halide to build my data processing pipelines.
We are using gnu make 4.3 in combination with MinGW 6.3 for cross compilation.

**Comment by abadams** [comment]
Thanks for the comment - I guess we know at least one person uses mingw support, so it must be useful.

**Comment by abadams** [comment]
See also PR #3917

**Comment by sinkingsugar** [comment]
I think so.

Given that mingw and bash-on-windows have no relation at all, bash-on-windows is basically in a nutshell a half baked linux vm on windows, mingw is full windows compiled with gcc rather then microsoft tools.

I know many companies including mine that prefer to use gcc for many reasons (e.g. inline asm).
I don't think it's such a big issue to support it also given it uses mostly the same tools of linux builds.

**Comment by abadams** [comment]
That's three votes. Let's close the issue and keep supporting mingw.
