### ISSUE TITLE
halide_debug_to_file does not work with interleaved images

### ISSUE THREAD

**Issue by abestephensg** [halide/Halide#391]
While investigating #390 I noticed that debug_to_file does not work when the stride is set for interleaved data.

It appears that the TIFF code in halide_debug_to_file is hard coded for planar format:
	tag++->assign16(284, 1, 2);                              // Planar configuration -- planar

**Comment by steven-johnson** [comment]
Bumping this -- it's causing me a lot of pain in debugging a complex pipeline.
