### ISSUE TITLE
apps/ are broken with HL_TARGET=host-hvx_128 on linux

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3910]
at recent master (0eb43173eeb3e9812b3abb604ecdb09d6ccfdbdf), some (many? all?) of the apps/ fail when built for host-hvx128, with "Error: Required Hexagon runtime symbol 'halide_hexagon_remote_load_library' not found." This happens on the buildbots and also on my local Linux box. Have not yet found an injection point.

**Comment by steven-johnson** [comment]
tagging @dsharletg  and @pranavb-ca to see if they have any thoughts

**Comment by steven-johnson** [comment]
on my system, `libhalide_hexagon_host.so` is failing to load, because it is looking for `libwrapper.so`, which cannot be found

**Comment by steven-johnson** [comment]
OK, this makes no sense, in that I don't see how this could ever have worked on our buildbots: AFAICT, running on the hvx simulator requires access to the HVX SDK (and to have LD_LIBRARY_PATH pointed at it appropriately), and I don't see any effort to set LD_LIBRARY_PATH on the buildbots for those tests.

**Comment by dsharletg** [comment]
It passed <24 hours ago for the correctness tests: https://buildbot.halide-lang.org/master/#/builders/24/builds/457/steps/30/logs/stdio

I'm not sure the apps were ever set up to run on the build bots though. But perhaps the configuration for the correctness tests re: the Hexagon SDK can just be copied over to the apps tests?

**Comment by steven-johnson** [comment]
Our buildbot config has:

```
  if os.startswith('linux-64-gcc53') and llvm == 'trunk':
    # Also test hexagon using the simulator
    for t in ['host-hvx_128', 'host-hvx_64']:
      targets.extend([('test_correctness', t),
                      ('test_generator', t),
                      ('test_apps', t)])
```

which has been like that for quite a while.

**Comment by pranavb-ca** [comment]
The correctness tests work because of this in the top level Makefile
```
ifneq (,$(HL_HEXAGON_TOOLS))
TEST_LD_FLAGS += -Wl,--rpath=$(ROOT_DIR)/src/runtime/hexagon_remote/bin/host
TEST_LD_FLAGS += -Wl,--rpath=$(HL_HEXAGON_TOOLS)/lib/iss
...
...
# Correctness test that link against libHalide
$(BIN_DIR)/correctness_%: $(ROOT_DIR)/test/correctness/%.cpp $(BIN_DIR)/libHalide.$(SHARED_EXT) $(INCLUDE_DIR)/Halide.h $(RUNTIME_EXPORTED_INCLUDES)
    @mkdir -p $(@D)
    $(CXX) $(TEST_CXX_FLAGS) -I$(ROOT_DIR) $(OPTIMIZE_FOR_BUILD_TIME) $< -I$(INCLUDE_DIR) $(TEST_LD_FLAGS) -o $@
```
The same cannot be said for the apps because each is run differently. We need to set something up in master.cfg for them. Cannot explain how they have been working for so long though.

**Comment by steven-johnson** [comment]
> Cannot explain how they have been working for so long though

Wowsers, yeah. I'll prep a PR for the apps fix.

**Comment by steven-johnson** [comment]
...and now as I test my fix this morning, I find that master is now successfully running on my linux box (without the change). /fliptable

**Comment by steven-johnson** [comment]
Apparently no longer an issue. Closing.

**Comment by andrewjong** [comment]
This problem just showed up on my computer. Any idea what the solution is/was?
