### ISSUE TITLE
Should HVX_64 support be deprecated?

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3925]
It's not clear that there is any active use of HVX_64 (as opposed to HVX_128), and any new users wouldn't start there. Should we deprecate-and-remove it? If nothing else, it would allow us to drop buildbot testing of it.

**Comment by steven-johnson** [comment]
Gentle ping. Worth considering?

**Comment by dpalermo** [comment]
We should keep HVX_64 for now.  The Google clips project appears to be using HVX_64 on their IOT device.  There is also still supported hardware (Pixel 1) that supports HVX_64.

**Comment by steven-johnson** [comment]
Understood. Leaving open to revisit at some point in the future.

**Comment by steven-johnson** [comment]
Circling back to reconsider this a year later.

**Comment by pranavb-ca** [comment]
Thanks for checking on this @steven-johnson. I was about to open a PR a few weeks ago to deprecate HVX_64, but then heard chatter inside that it might not go away so soon after all. So, until I have a clearer understanding of that we'll need to keep HVX_64 around.

**Comment by steven-johnson** [comment]
Thanks for the update. Can you give any more clarity on the chatter? (It's not at all clear to me what systems/chipsets/etc have historically supported it or not, and whether or not new designs supporting it are still being made, etc.... any public info you can share would be useful for everyone, I think.)

**Comment by pranavb-ca** [comment]
Unfortunately, this whole HVX_64 issue is in a sort of gray area; while the ISA *had* never been deprecated officially, for quite sometime now we haven't shipped a Hexagon core with HVX 64. Let me get the right info on the last Snapdragon chipset that supported it. Also, will circle back with more info on the "chatter" if I can share it.

**Comment by pranavb-ca** [comment]
@steven-johnson  - we are ready to do this. I'll open a PR in a day or two - quick question before that though - should we deprecate-and-remove or simply deprecate. I prefer the former because it cleans up code nicely, but I don't want to break any release policy. LMK

**Comment by steven-johnson** [comment]
Unfortunately, removing it entirely will cause some churn inside Google (there is some code that would need massaging to remove all the references, weirdly enough). It might be time to remove it though. Tagging @dsharlet for his thoughts.

**Comment by dsharletg** [comment]
I think we should just remove this, assuming our internal uses can be removed. I don't see why not, given that no devices with the instruction set have shipped in a while.

**Comment by steven-johnson** [comment]
OK, agreed with @dsharlet. Let's remove it.

**Comment by pranavb-ca** [comment]
On it.
