### ISSUE TITLE
Vectorization crashes on update step of reduction definition

### ISSUE THREAD

**Issue by slepa** [halide/Halide#3952]
```
Halide::Func f;
Halide::Var x, y;
f(x, y) = 1;
f(0, y) = 0;
f.vectorize(y, 8);
f.update(0).vectorize(y, 8);
f.realize(10, 10);
```

**Error:**
Output buffer f4 is accessed at 15, which is beyond the max (9) in dimension 1
_Aborted (core dumped)_

> halide-2018.02.15 built with clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-16.04 by gcc 7.4.0 on Ubuntu 18.04.2 LTS

**Comment by abadams** [comment]
This behavior has already been changed in master to be more user friendly.

**Comment by slepa** [comment]
Thanks!
