### ISSUE TITLE
Tracking issue for disablement of LLVM NewPassManager

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3957]
The changes made in #3868 are being temporarily disabled: they have injected a pathological compilation slowdown in some code inside Google, and while @alinas has been investigating, she's going OOO for a bit. Since this change isn't urgent (ie LLVM isn't removing the old pass managaer API anytime soon) we're going to temporarily disable it to make downstream merges simpler.

**Comment by steven-johnson** [comment]
@alinas -- where does this stand? Have there been changes upstream that would warrant retrying this?

**Comment by alinas** [comment]
IIRC, last we tried re-testing the tests that used to timeout, it was no longer the case.
So, yes, it's worth trying to re-enable this.

**Comment by steven-johnson** [comment]
Re-enabling it inside Google is producing some numerically different results in some cases (ie, not a slowdown but a change in computation).

**Comment by steven-johnson** [comment]
Looks like we needed to set `pto.SLPVectorization = true` in the new case to match the old case
