### ISSUE TITLE
CMake/CPack 'distrib' target isn't correct for Windows

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3971]
A while back, someone thoughtfully contributed CPack support to our CMake files, so that `make distrib` worked correctly for CMake as well as make; unfortunately, it needs some extra love for Windows builds in order to match the status quo for Windows:

- Windows requires separate Debug and Release builds; the CMake rules only provide a single build (presumably Release)
- The CMake rules only provide shared-library outputs (bin/Halide.dll), whereas our existing Windows distribs provide Halide.lib as well 

This would be really nice to fix, as currently, Windows distribs are produced by custom code in the buildbots, which can (and does) easily fall out of sync with the rest of Halide.

**Comment by alexreinking** [comment]
This is getting overhauled in #4644 -- I'll need to look into package managers for Windows, eg. vcpkg, chocolatey, Nuget, to see which would be easiest to publish Halide to.

**Comment by alexreinking** [comment]
It turns out that the vcpkg people are currently packaging an old version of Halide. We should work with them as we cut a new release to make sure the new CMake improvements are available to their users.

**Comment by steven-johnson** [comment]
See also https://github.com/halide/Halide/pull/4539

**Comment by alexreinking** [comment]
This can only be reasonably done with CMake 3.16 and only becomes sane in the absolute newest version, 3.17. This is because CPack only gained the ability to produce multi-configuration packages recently. We should just keep CMake on the Windows buildbots as up-to-date as possible and write `packaging/CMakeLists.txt` to detect newer features.

**Comment by alexreinking** [comment]
This will be corrected once CMake 3.18 is released due to a bug in 3.17. We will need to use the `Ninja Multi-Config` generator and then run:

```
> cmake -G "Ninja Multi-Config" ...
> cmake --build . --config Debug
> cmake --build . --config Release
> cpack -C "Debug;Release"
```

See #4980 and [the related issue on CMake](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/4825)

**Comment by steven-johnson** [comment]
Hopefully we can continue with our current CMake min of 3.16 and just require 3.18 for building windows distribs?

**Comment by alexreinking** [comment]
Yes, this is about the tool versions, not anything that's in the CMakeLists.txt files.
