### ISSUE TITLE
CMake/CPack 'distrib' target omits static libraries

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3972]
'make distrib' (using the Makefile) includes both bin/libHalide.so and lib/libHalide.a, whereas 'make distrib' (using CMake) includes only the former, not the latter. This should be fixed so that both build systems produce identical distrib folders.

(See also the ancient PR https://github.com/halide/Halide/pull/2516)

**Comment by steven-johnson** [comment]
https://github.com/halide/Halide/pull/2516 addresses part of this issue (by cleaning up static-library usage in our CMake rules), but is incomplete, as it requires rebuilding the world to switch between static and shared; in theory, I think that it should be simple-ish to produce both at once (by just adding a new `add_library` rule with a different name), but nothing with CMake is ever simple, so that should probably be done as a followup.

**Comment by alexreinking** [comment]
This can be done in CMake by creating two separate targets. Otherwise, we'll have to build twice and set `HALIDE_SHARED_LIBRARY=YES/NO` appropriately. Clients would link to either `Halide::Halide` or `Halide::HalideStatic`
