### ISSUE TITLE
Halide::Runtime::Buffer::transpose function doesn't transpose data

### ISSUE THREAD

**Issue by piotrklos-tcl** [halide/Halide#3978]
I've just spent 2h trying to hunt down a bug in my code and it turned out to be a surprising behavior of Halide::Runtime::Buffer::transpose.

Quoting from the reference docs:
```
Transpose an image in-place.

Definition at line 1162 of file HalideBuffer.h.
```
If you look at the source code though, it only changes the dimension information, not the data itself:
```
void transpose(int d1, int d2) {
         std::swap(buf.dim[d1], buf.dim[d2]);
  }
```

This is incoherent with the mathematical definition of the word and confusing to anyone who is familiar with any other library that does transposition, such as numpy or OpenCV.
https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html
https://docs.opencv.org/4.1.0/d3/d63/classcv_1_1Mat.html#aaa428c60ccb6d8ea5de18f63dfac8e11

Numpy has relevant example on the documentation page.
OpenCV transposition can be demonstrated with 
```
#include <iostream>
#include <opencv2/core/core.hpp>
#include <numeric>
using namespace std;

int main()
{
    cv::Size size(2, 3);
    cv::Mat m(size, CV_32SC1);
    int32_t* dataptr =(int32_t*)m.data;
    std::iota(dataptr, dataptr + size.area(), 0);
    for(auto p = dataptr; p < dataptr + size.area(); ++p)
        cout << *p << ", ";
    cout << endl;

    cv::Mat transposed = m.t();
    dataptr =(int32_t*)transposed.data;
    for(auto p = dataptr; p < dataptr + size.area(); ++p)
        cout << *p << ", ";
    cout << endl;
}
```
which prints
```
0, 1, 2, 3, 4, 5, 
0, 2, 4, 1, 3, 5, 
```

Please, deprecate Halide::Runtime::Buffer::transpose and provide an actual transpose function called "t" or something like that, which actually transposes the data. I don't think fixing the documentation so that it doesn't lie is enough because the function name itself is a lie.

Existing behavior could be OK under a more explicit name, although it is risky function to have, because using it makes the content of Buffer inconsistent (dims don't match the data contents), so it looks like a big source of bugs.

**Comment by abadams** [comment]
Firstly, sorry that the insufficient docs gave the wrong idea of what that method does. All of the buffer methods except for copy are just metadata operations that change how the data is indexed. Generally speaking Halide::Runtime::Buffer avoids any operations that are complex enough that you would want to schedule them (vectorization, parallelization), the idea being that those operations are better done in Halide itself.

However, I'm going to push back a little. The mathematical definition of transpose doesn't say anything about storage layouts of arrays in memory. If you transpose a matrix A, then the value formerly in A(i, j) is now found at A(j, i), and vice versa. That's what this method does. I'll fix the docs to make it clear that it's just manipulating the metadata.

**Comment by piotrklos-tcl** [comment]
@abadams OK, then I think there is a bigger documentation problem beyond a few undocumented methods in the reference docs. The Halide::Runtime::Buffer looks like the core data structure for handling arrays in Halide. When people see operations like "transpose", they will assume that it is a replacement of cv::Mat or np.ndarray, unless its clearly indicated as false on all levels of documentation (from tutorials to class-level reference docs).

I suggest making a tutorial showing how to use Buffer for storage, how operations are just metadata how to wrap it in cv::Mat (or other popular thing) for achieving actual data transformations.
