### ISSUE TITLE
Readable Halide Code Format + Variadic op

### ISSUE THREAD

**Issue by chtsao8** [halide/Halide#4014]
@asaadaldien Hi again, just two more pressing issues:

First, converting from onnx -> Halide (e.g. on alexnet) produces alexnet_model.a, alexnet_model.h, and alexnet_model.registration.cpp, but no readable file for the Halide-converted NN framework. I'm able to compile the code and run it using the .cpp and .a files, but having readable code for the scheduler and algorithm (or even just the algorithm) would be beneficial since I may have to rewrite the scheduler for the hardware I'm testing on. Is there any way to view the generated Halide NN framework (alg+scheduler) in a readable format? 

Second,  I'm still not fully familiar with the Halide syntax, and I'm not sure how to implement ConvTranspose properly. The formula (given pads) from the onnx github is:

output_shape[i] = stride[i] * (input_size[i] - 1) + output_padding[i] + ((kernel_shape[i] - 1) * dilations[i] + 1) - pads[start_i] - pads[end_i]

However, I'm not sure how to write each term into the convert_variadic_op_node Node. I've noticed that some of these operations are done below in onnx_converter.cc, but do you have any advice?

**Comment by asaadaldien** [comment]
The converter doesn't schedule anything it just build a Halide pipeline equivalent. To manually schedule your converted model, for each node in your onnx model we have the corresponding Halide::Func in a dictionary `converted_model_.tensors`. You can build a manual schedule by referencing those Funcs and do pretty much anything! 

ConvTranspose is similar to convolution the difference is it correlation kernels do upsampling (see:https://arxiv.org/abs/1603.07285). The equation you mentioned is for relating input size to output size (e.g infer convTransposes output shapes).

Feel free to implement this in Halide I think its a nice exercise or you can wait for next update soon ConvTranspose is one of the ops on my list.

**Comment by chtsao8** [comment]
I can't seem to run the Halide-converted version of the alexnet code - with a dummy input Buffer<float> input, it hangs indefinitely when run, and when I try to set Buffer<uint8_t> input = load_image(path/to/image) I get

Error: Input buffer actual_input_1 has type float32 but type of the buffer passed in is uint8

However, when I try to set the input to Buffer<float> input = load_image(path/to/image), I get this error:

alexnet: ../../distrib/include/HalideBuffer.h:671: static void Halide::Runtime::Buffer<T, D>::assert_can_convert_from(const Halide::Runtime::Buffer<T2, D2>&) [with T2 = void; int D2 = 4; T = float; int D = 4]: Assertion `can_convert_from(other)' failed.

This is probably a lack of understanding on my part, but how would I be able to run a test image through alexnet_model?

**Comment by asaadaldien** [comment]
Looks like you just need to convert your input image to float32 load it into a Halide::Buffer\<float\> .

**Comment by chtsao8** [comment]
The code still hangs indefinitely when run - calling alexnet_model(input, output) doesn't seem to work...

**Comment by chtsao8** [comment]
That seemed to work - in order to use a scheduler other than the autoscheduler, do I have to write it in onnx_converter_generator.cc so it's applied during compilation?

**Comment by asaadaldien** [comment]
Yes, you need to insert your manual schedule there.
