### ISSUE TITLE
undefined reference to `trunc_f16`

### ISSUE THREAD

**Issue by eloi-loomai** [halide/Halide#4019]
I was just wondering:
Is it possible to use float16 on arm devices?

When trying, I get that error:
```undefined reference to `trunc_f16'
undefined reference to `round_f16'```

Is there anything I can do?

**Comment by abadams** [comment]
float16 in master is half-implemented. I'm trying to fix it here: https://github.com/halide/Halide/pull/3667

It's pretty rudimentary right now though - it upcasts to float32 for any math on all platforms then narrows back to float16. I'm also not sure that it would fix the problem you have - I don't have implementations of trunc and round that are float16 native, and am not sure if the upcasting logic will do the right thing for them yet. You could try patching it in and see.

**Comment by eloi-loomai** [comment]
Ok, I thought I could probably gain speed by working on half the size of floats, but I don't think it will.

**Comment by steven-johnson** [comment]
https://github.com/halide/Halide/pull/3667 should have addressed this; closing
