### ISSUE TITLE
Bounds Inference ignores `select`?

### ISSUE THREAD

**Issue by gilbo** [halide/Halide#4036]
Found a bounds-inference bug.  For reference, “fruits.png” in the program below is a 512x512 image.

The crux of the issue is that Halide doesn't seem to be able to analyze when `Halide::select` is used to directly implement a `clamp`.

The error produced is

```
Error at ./oob_bug.cpp:43:
Input buffer b0 is accessed at 513, which is beyond the max (511) in dimension 0
Abort trap: 6
```

The source code is

```
// Template taken from Halide Tutorials

#include "Halide.h"
#include <stdio.h>

using namespace Halide;

#include "halide_image_io.h"
using namespace Halide::Tools;

int main(int argc, char **argv) {
    Var x("x"), y("y"), c("c");

    Buffer<uint8_t> input = load_image("./fruits.png");
    auto w = input.width();
    auto h = input.height();

    Func input_16("input_16");
    input_16(x,y,c) = cast<uint16_t>(input(x,y,c));

    Func clamped("clamped");
    clamped(x,y,c) = input_16(Halide::select(x<0, 0 ,
                                Halide::select( x>w-1, w-1, x )),
                              clamp(y,0,input.height()-1),
                              c);

    Func blur_x("blur_x");
    blur_x(x,y,c) = (  clamped(x-1,y,c) +
                     2 * clamped(x,y,c) +
                       clamped(x+1,y,c));

    Func blur_y("blur_y");
    blur_y(x,y,c) = (  blur_x(x,y-1,c) +
                     2 * blur_x(x,y,c) +
                       blur_x(x,y+1,c));

    Func output("output");
    output(x,y,c) = cast<uint8_t>(blur_y(x,y,c) / 16);


    Buffer<uint8_t> result(input.width(), input.height(), 3);
    result.set_min(1,1);
    output.realize(result);

    save_image(result, "./blurry_fruits.png");

    return 0;
}
```

Note that the above program works fine when the clamping on `x` is made to resemble the clamping on `y`, so the bug can be isolated to specifically that code delta.

**Comment by shoaibkamil** [comment]
Halide's `select` has different semantics than what you're trying to do here; a `select` evaluates both branches then picks between the two using the conditional.  That's why you're getting an out-of-bounds access.

Clamps are implemented using `max` and `min` so they don't have the same issue.

**Comment by gilbo** [comment]
The code above doesn't select between `A[x]` and `A[0]` based on `x>0` but between `x` and `0` based on `x>0`, so it ought to be semantically equivalent to `max` or `min`.  i.e. I don't see why macro replacing `max(x,y)` with `select(x > y, x, y)` should produce semantically different behavior since neither form does short-circuit evaluation.

**Comment by steven-johnson** [comment]
> it ought to be semantically equivalent to max or min

...so why not use `max` and `min` then, instead of `select`?

**Comment by abadams** [comment]
bounds inference is conservative, and your select relies Halide to understand the implication of the condition on the possible values. We try, but in general it's undecidable, so sometimes for selects we just take the union of both sides. max/min can be reasoned about locally.

**Comment by alexreinking** [comment]
> > it ought to be semantically equivalent to max or min
> 
> ...so why not use `max` and `min` then, instead of `select`?

Probably because @gilbo is writing a code generator that targets Halide.

**Comment by steven-johnson** [comment]
Sounds like @gilbo will have to do some special casing to make this work well, then; as mentioned above, the semantics of `select()` in Halide require different bounds rules. If the codegen wants true max-min type behavior, it will need to generate those statements.

**Comment by steven-johnson** [comment]
Is this still open/actionable?

**Comment by zhen8838** [comment]
@steven-johnson  Can you give an example to show how to use select? I have the same problem.
I want to use select to action my outputs, but it always raises error `beyond the max\min`
My code:
```cpp
template <typename BT>
Halide::Func gnne_matmul(BT &input_a, BT &input_b, BT &act, BT &value_range)
{
    Halide::Var N("N"), M("M");
    Halide::Func inner_sum("inner_sum"), inner_acted("inner_acted");
    Halide::RDom K(0, input_a.width());
    inner_sum(N, M) += input_a(K, M) * input_b(N, K);
    inner_acted(N, M) = clamp(
        select(inner_sum(N, M) < act(0),
            inner_sum(N, M) * act(1) + act(2),
            inner_sum(N, M) * act(3) + act(4)),
        value_range(0), value_range(1));
    Halide::Var xi("xi"), yi("yi");
    inner_acted.tile(N, M, xi, yi, 16, 8).parallel(yi);

    return inner_acted;
}
```
When I set input parameter to `{ 20, 40, 10 }, // M , N , K`， will get error：
```sh
Error: Output buffer inner_acted is accessed at -6, which is before the min (0) in dimension 0
```

Does it cause input_size smaller than tilting size or `select`?  Can you help me?

**Comment by steven-johnson** [comment]
> Does it cause input_size smaller than tilting size or `select`? Can you help me?

This isn't the right venue for helping with specific debugging issues. I'd recommend asking for help on the Gitter channel for Halide.
