### ISSUE TITLE
macOS build bot slow on test_correctness_3 (Metal)

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#4043]
The runtime for this test has been increasing as of late, and is up to 2.5 hours now. @steven-johnson couldn't repro on his Macbook, so it might be buildbot specific.

A bunch of different builds have exhibited this:

https://buildbot.halide-lang.org/master/#/builders/1/builds/93

Builds /92, /89 - /88, /85 - /74, /72 - /59, and /56 - /2 have the same issue. Builds /73 and /58 seem to break the pattern. All the rest are failing so don't have information either way.

/2 has a time of 1:37:06, which is still unreasonable. `correctness_1` and `correctness_2` are fast.

Unfortunately, these tests on macOS produce no output that I can see beyond an elapsed time.

**Comment by shoaibkamil** [comment]
The tests currently have Metal validation enabled; does it replicate locally if the `METAL_DEVICE_WRAPPER_TYPE` environment variable is set to 1?

**Comment by alexreinking** [comment]
I don't own any Apple hardware, so hopefully someone who does can test.

**Comment by steven-johnson** [comment]
> The tests currently have Metal validation enabled; does it replicate locally if the `METAL_DEVICE_WRAPPER_TYPE` environment variable is set to 1?

I will test this locally.

**Comment by steven-johnson** [comment]
testing locally on my MBAir, METAL_DEVICE_WRAPPER_TYPE=1 doesn't seem to meaningfully affect time. I'll test on the buildbot

**Comment by shoaibkamil** [comment]
Were you able to test/diagnose this?  I can't replicate locally either, which leads me to believe it could be related to the machines and/or their specific OS versions.

**Comment by steven-johnson** [comment]
Haven't had a chance. Will try to do so today.

**Comment by steven-johnson** [comment]
Logging into the Mac buildbot via CRD doesn't seem to be working (I can get to the login screen, but can't get function keyboard input to login)... I'm guessing the Mac needs a restart + Chrome update, but I can't do that remotely. Let me see if I can get someone in MTV office to go do so.

**Comment by steven-johnson** [comment]
OK, after fixing the OSX buildbot's remote access, applying all the OS updates, rebooting, and doing clean build and test with METAL_DEVICE_WRAPPER_TYPE=0 and METAL_DEVICE_WRAPPER_TYPE=1, I find only noise in the runtime (both run reasonably fast) -- I'm guessing that the update-plus-reboot healed whatever issue was going on. I'm going to blow away all the locally cached stuff on the machine and declare this 'fixed' for now; let's keep an eye on it and see if it recurs.
