### ISSUE TITLE
FR: add generator parameter configurations to the source

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#4054]
Currently, sets of `GeneratorParam` values are appended to the generator binary's command line when compiling a schedule. I propose extending this functionality with _named configurations_ that are specified in the source.

I think this is desirable for several reasons.

First, it facilitates compiling all desired configurations for a given generator without needing to know details about the generator's parameters. This simplifies builds that want to manage multiple configurations. 

Second, configurations become just more source. This is friendlier to developers than needing to maintain platform specific shell scripts or the like.

Third, errors in default configurations could be caught by the compiler and there would be no question about how to format strings to get the desired results.

A straightforward implementation might add macros to be used after `HALIDE_REGISTER_GENERATOR`. The name of the configuration (or a special symbol corresponding to all cfgs) would take the place of the usual generator params at the command line.

This is sort of a compile-time counterpart to #3677

**Comment by steven-johnson** [comment]
You can sorta-kinda do this with `HALIDE_REGISTER_GENERATOR_ALIAS` already.

**Comment by alexreinking** [comment]
Ohh that's good to know. I'll look into that to see how well it meets my needs.

**Comment by alexreinking** [comment]
Actually, can the generator binaries currently emit all generators and aliases they contain in a single command?

**Comment by steven-johnson** [comment]
What do you mean by "emit"? 

You can get the metadata for any Generator and inspect the available params, etc. (This is how the RunGen tool works.)

**Comment by steven-johnson** [comment]
Is this still an active issue?
