### ISSUE TITLE
AutoScheduler nomenclature needs clarity

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4057]
At present, we have two autoschedulers in our codebase, but there don't appear to be well-defined terms for each (e.g. “classic” vs “ML hotness” or whatnot); we should really settle on some terms to avoid confusion going forward. (Since there is the possibility of additional autoschedulers being added in the future, avoiding terms like 'old', 'new', etc are probably wise.)

**Comment by abadams** [comment]
One option is labelling them via the papers: Mullapudi_2016, Adams_2019. Or maybe siggraph_2016, siggraph_2019. Precise, and the most useful for academic comparisons, but not intuitive. Also using names is possibly unfair to all the other authors and developers, e.g. Patricia ultimately had as much influence on the Mullapudi code/algorithm as Ravi, and tons of people other than me worked on the newer one. We could also name them by the core algorithm involved: clustering, beam_search.

**Comment by steven-johnson** [comment]
In a private branch, I'm currently using the placeholder names "classic" and "v2019" for now.

**Comment by steven-johnson** [comment]
Update: as of https://github.com/halide/Halide/pull/4094, the 'name' of the scheduler used now is embedded in the generated `.schedule.h` file; for now, the names being used are `src/AutoSchedule` and `apps/autoscheduler/AutoSchedule`, which are... suboptimal.

**Comment by steven-johnson** [comment]
Update: soon we'll also have apps/gradient_autoscheduler, so 'v2019' is clearly a bad choice

**Comment by abadams** [comment]
I'm in favor of citation-style then: Adams2019, Mullapudi2016, Li2018.

**Comment by BachiLi** [comment]
Sounds good to me
