### ISSUE TITLE
Investigate simplifier verification/testing/logging.

### ISSUE THREAD

**Issue by zvookin** [halide/Halide#406]
Blowups in the simplifier are a common enough occurrence to merit some form of mitigation. While these are usually deterministic and not incredibly hard for someone who knows the code to debug, they are difficult for end users. I don't think there is any easy design change or automatic method to detect problematic patterns in the simplifier rules. However we could add some code to track and report the resource usage (e.g. call levels), to debug log the subject expression or statement at the top of each mutator method, and increase test coverage. E.g. for the latter, extending the check mechanism to take slightly generalized patterns so tests can be performed for a variety of interesting constants on each pattern that uses a constant, across types, etc.

**Comment by dsharletg** [comment]
I think we've done a lot of this, we have correctness_fuzz_simplify, and the random pipeline generator. I think @abadams, @shoaibkamil and colleagues have also added a lot more robustness/verification to the simplifier.
