### ISSUE TITLE
Correctness of convolution in Halide

### ISSUE THREAD

**Issue by aliericcantona** [halide/Halide#4091]
Imagine 
	int iW = 10;
	int iH = 10;

	Halide::Buffer<float> input( iW, iH);
	for( int i = 0; i < iW; ++i )
	{
		for( int j = 0; j < iH; ++j )
		{
			if ( i >= 3 && i <7  && j >= 3 && j < 7 )
				input( i, j ) = 1.0f;
			else
				input( i, j ) = 0.0f;
		}
	}

	Halide::Buffer<float> outputRef( iW, iH);
	for( int i = 0; i < iW; ++i )
		for( int j = 0; j < iH; ++j )
			outputRef( i, j ) = 0.0f;

int kW = 3;
	Halide::Buffer<float> kernel( kW, kW );
	for( int i = 0; i < kW; ++i )
		for( int j = 0; j < kW; ++j )
			kernel( i, j ) = i/static_cast<float> ( kW * kW );

	Halide::RDom r( kernel );

	Halide::Func result( "result" );
	Halide::Var x( "x" ), y( "y" );
	Halide::Expr width = Halide::Expr( 10 );
	Halide::Expr height = Halide::Expr( 10 );
	Halide::Expr kernelStartIndex = Halide::Expr( 2 );

	Halide::Func inputF( input );
	Halide::Func kernelF( kernel );
	result = Convolution( inputF, kernelF, r, width, height, kernelStartIndex );

	Halide::Buffer<float> output;
	output = result.realize( iW, iH );

Also, the convolution function is :

Func Convolution( const Func &in, const Func &kernel, const RDom &r, const Expr &W, const Expr &H, const Expr &rStart )
{
	Var x( "x" ), y( "y" );

	Func clamped( "clamped" );

	clamped(x, y) = in( clamp( x, 0, W - 1 ), clamp( y, 0, H - 1 ) );
	clamped.compute_root();

	Func filtered( "filtered" );

	filtered( x, y ) += kernel( r.x, r.y ) * clamped( x + r.x , y + r.y  );

	return filtered;

}
 

But the output is 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0.222222, 0.444444, 0.666667, 0.666667, 0.444444, 0.222222, 0, 0, 0, 
0, 0.333333, 0.666667, 1, 1, 0.666667, 0.333333, 0, 0, 0, 
0, 0.333333, 0.666667, 1, 1, 0.666667, 0.333333, 0, 0, 0, 
0, 0.333333, 0.666667, 1, 1, 0.666667, 0.333333, 0, 0, 0, 
0, 0.111111, 0.222222, 0.333333, 0.333333, 0.222222, 0.111111, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

Althouth the correct answer is:

	//  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
	//  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
	//  0. 0. 0.11111111 0.22222222 0.33333333 0.33333333 0.22222222 0.11111111 0. 0.
	//  0. 0. 0.22222222 0.44444444 0.66666667 0.66666667 0.44444444 0.22222222 0. 0.
	//  0. 0. 0.33333333 0.66666667 1. 1. 0.66666667 0.33333333 0. 0.
	//  0. 0. 0.33333333 0.66666667 1. 1. 0.66666667 0.33333333 0. 0.
	//  0. 0. 0.22222222 0.44444444 0.66666667 0.66666667 0.44444444 0.22222222 0. 0.
	//  0. 0. 0.11111111 0.22222222 0.33333333 0.33333333 0.22222222 0.11111111 0. 0.
	//  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
	//  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

**Comment by aliericcantona** [comment]
How do you guys recommend to change the code?

**Comment by aliericcantona** [comment]
Even I added rstart to the equation of filtered( x, y ) += kernel( r.x, r.y ) * clamped( x + r.x-rstart , y + r.y -rstart ); still did not get the correct answer.

**Comment by alexreinking** [comment]
Please format your issue correctly to help us help you.

**Comment by dsharletg** [comment]
Based on your desired output, it looks like you are trying to implement a 3x3 box filter convolution? If so, this line:

    kernel( i, j ) = i/static_cast<float>( kW * kW );

seems wrong, because it will produce a kernel that looks like:

    0 1/9 2/9
    0 1/9 2/9
    0 1/9 2/9

I think you instead want:

    kernel( i, j ) = 1.0f /static_cast<float>( kW * kW );

**Comment by aliericcantona** [comment]
Awesome! my typo  in the kernel. Now it works smoothly.
