### ISSUE TITLE
Unable to build with Clang that was built needing libc++

### ISSUE THREAD

**Issue by pranavb-ca** [halide/Halide#4096]
My LLVM SHA is
```
commit d82b6b2fcd8d26be273a04511139e707ae51fc94
Author: Nico Weber <nicolasweber@gmx.de>
Date:   Tue Aug 6 02:25:49 2019 +0000

    gn build: Add AMDGPU target

    Differential Revision: https://reviews.llvm.org/D65767

    git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@367972 91177308-0d34-0410-b5e6-96231b3b80d8
```

Clang SHA is
```
commit 26d2be17f068e993a0213347c158022cb5ab28b7
Author: Puyan Lotfi <puyan@puyan.org>
Date:   Tue Aug 6 01:26:46 2019 +0000

    [NFC][DirectoryWatchedTests] Unlocks mutexes before signaling condition variable

    This should not affect actual behavior, but should pessimize the threading less
    by avoiding the situation where:

      * mutex is still locked
      * T1 notifies on condition variable
      * T2 wakes to check mutex
      * T2 sees mutex is still locked
      * T2 waits
      * T1 unlocks mutex
      * T2 tries again, acquires mutex.

    Differential Revision: https://reviews.llvm.org/D65708



    git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@367968 91177308-0d34-0410-b5e6-96231b3b80d8
```
I added the following CMAKE variable because I need libc++  ```-DCMAKE_CXX_FLAGS:STRING='-std=c++11 -stdlib=libc++' ```

This causes the resulting llvm-config to require libc++, conveyed by way of its cxxflags.
```
$bld/bin/llvm-config --cxxflags
-I$src/llvm/include -I$bld/include -std=c++11 -stdlib=libc++  -fno-exceptions -fno-rtti -D_GNU_SOURCE -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
```
Now, building with G++ is not possible with the set up of the current Makefile

```
g++ -Wall -Werror -Wno-unused-function -Wcast-qual -Wignored-qualifiers -Wno-comment -Wsign-compare -Wno-unknown-warning-option -Wno-psabi  -fno-rtti  -Woverloaded-virtual -fPIC -O3 -fno-omit-frame-pointer -DCOMPILING_HALIDE -std=c++11 \
 -I/usr2/pranavb/s2/upstream_llvm_git/llvm/include -I/usr2/pranavb/b2/master/build_llvm_201985_upstream_release/include -std=c++11 -stdlib=libc++ -fno-exceptions -fno-rtti -D_GNU_SOURCE -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_\
MACROS -D__STDC_LIMIT_MACROS -I/usr2/pranavb/s2/upstream_llvm_git/llvm/tools/lld/include -DLLVM_VERSION=100    -DWITH_ARM  -DWITH_HEXAGON  -DWITH_AARCH64  -DWITH_X86  -DWITH_OPENCL  -DWITH_METAL  -DWITH_OPENGL  -DWITH_D3D12        -DWIT\
H_INTROSPECTION       -funwind-tables -c /local/mnt2/dev/Halide/halide_tip/release/Halide/src/AddImageChecks.cpp -o bin/build/AddImageChecks.o -MMD -MP -MF bin/build/AddImageChecks.d -MT bin/build/AddImageChecks.o
g++: error: unrecognized command line option ‘-stdlib=libc++’
```

**Comment by steven-johnson** [comment]
I'm not sure this is actually fixable -- I don't think GCC is capable of (easily) using libc++ (instead of libstdc++). If you need to use libc++ you are better off using clang instead of gcc.

**Comment by pranavb-ca** [comment]
So, should our build instructions call this out explicitly - to use clang to build instead of GCC if libc++ was used to build LLVM? Or, we'd need to do this https://libcxx.llvm.org/docs/UsingLibcxx.html#using-libc-with-gcc

**Comment by steven-johnson** [comment]
If there is a (reasonable) way to use libc++ with gcc, then sure, we should add pointers to that to our doc.

**Comment by pranavb-ca** [comment]
Ok, back on this after taking care of a few other things. For the moment, I am making progress by using clang/clang++ as CC/CXX. This is fine, however, test_internal at the end barfs because it needs ```-stdlib=libc++``` but the flags to compile it are not derived from ```llvm-config --cxxflags```
@steven-johnson  - Ok if i come up with a reasonable patch for this?

**Comment by steven-johnson** [comment]
I'm always ok with reasonable patches :-)

**Comment by pranavb-ca** [comment]
@steven-johnson  - Can you tell me what cmake variables you use to build Halide? I use Make to build Halide and I have this so far https://github.com/halide/Halide/commit/03e8fc9e3616efdb3874630ff2958b3530f24af7 . Want to make similar changes for cmake so, I am looking for someone to simply spoon-feed me their cmake line.

**Comment by pranavb-ca** [comment]
never mind, got the cmake line. just had to open my eyes and look :(

**Comment by steven-johnson** [comment]
:-)

**Comment by steven-johnson** [comment]
Is this still an active concern, or has it been addressed?
