### ISSUE TITLE
How to get intermediate .cpp file generated by halide compiler? 

### ISSUE THREAD

**Issue by Vivek414** [halide/Halide#4111]
I have used binary release of halide to run the halide tutorial lessons.
I want to check the c++ code generated after coupling algorithm and schedule in intermediate stages of  halide compiler.

**Comment by shoaibkamil** [comment]
Depending on the target you're using, Halide won't produce C++ intermediate code in almost every case, because it generates LLVM IR directly.  You can see the intermediate representation or the LLVM bitcode if you increase the debug level (see [tutorial 3](https://halide-lang.org/tutorials/tutorial_lesson_03_debugging_1.html) for how to do this via an environment variable).

**Comment by Vivek414** [comment]
Thanks shoaibkamil for the answer. Can you elaborate about in which case Halide will produce C++ intermediate code & in those cases, is it possible to get C++ intermediate code. If yes then how? It would be very helpful if you answer in detail.

**Comment by abadams** [comment]
The only reason we ever compile to C++ in practice is to generate OpenCL and metal shader kernels, and to satisfy some weird requirements for the apple watch toolchain. On the CPU using C++ as an intermediate results in much slower code that takes much longer to compile, so we don't do it. The functionality exists, but it's not readable, it's not debuggable, and it's not representative of Halide's performance, so it's not particularly useful. To see an example of usage, look in apps/c_backend.

**Comment by zvookin** [comment]
We have internal use cases within Google where the C++ backend is producing usable performance for stuff where wiring up to an LLVM backend is very unlikely to ever be possible. There is also ample opportunity to improve this even further. So as a top-level matter, we should perhaps consider this path more viable and valuable than we previously have.

To answer the question @Vivek414 asked, the way to produce C++ output is to call e.g. ```Pipeline::compile_to_c``` or perhaps pass ```-e cpp``` to GenGen.
