### ISSUE TITLE
Deprecate DisableLLVMLoopVectorize and DisableLLVMLoopUnroll

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4113]
Per the original commit: "There's some evidence that this increases compile time without improving code generation for *properly-scheduled* Halide code. Adding feature flags to allow opting out so that downstream code can experimentally disable it."

At present, some variants of the autoscheduler set these (ie, disables llvm loop opt), but some don't. Since we believe that "properly scheduled" Halide code should be mostly indifferent to this (ie it's just wasted cycles), we should move to disabling them by default; the gotcha (of course) is that there may be downstream code that relies on these for performance, so we'll have to be cautious.

Proposal:
- Add EnableLLVMLoopVectorize and EnableLLVMLoopUnroll features to force these on (as a backdoor for code that may have issues)
- Leave in DisableLLVMLoopVectorize/DisableLLVMLoopUnroll for now (which will continue to force them off)
- Instruct downstream integrators to try adding DisableLLVMLoopVectorize+DisableLLVMLoopUnroll to all their build targets and see if it impacts performance
- After suitable length of time (2 weeks? 1 month?), remove DisableLLVMLoopVectorize+DisableLLVMLoopUnroll and make that the default

**Comment by benoitsteiner** [comment]
FYI: we disable as many LLVM optimizations as possible in order to train a more accurate cost model. For example, it becomes really hard to predict the impact of vectorization when the compiler is allowed to vectorize loops behind your back, and does in a very unpredictable fashion. Therefore when an optimization can be driven directly by Halide through a specific scheduling instruction, we try to give Halide full control over its application.

**Comment by steven-johnson** [comment]
As an update: recent work continues to suggest that the LLVM loop optimizations are generally undesirable:

- they increase compile time
- they rarely improve performance, and when they do, it's usually a suboptimal schedule
- they can add unpredictability to final code size (e.g. because LLVM may decided to unroll or not based on internal metrics that are hard to predict)

Per my initial suggestion above, at this point I think we should move to making llvm-loop-optimizations an opt-in rather than an opt-out.

**Comment by mcourteaux** [comment]
I agree with @steven-johnson here. The code generated is extremely hard to analyze. Especially for CUDA kernels where the code becomes incredibly long and everything remains scalar anyway. Maybe this LLVM loop optimization is less sensible for GPU targets in general.
