### ISSUE TITLE
FR: consolidate the autoscheduler weights into a single file

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4121]
Since it may be desirable to save a custom-tuned set of weights (from running autotune_loop), it would be nice to make this a single file instead of a group of files. (I assume that the set-of-files was much handier during prototyping, but at this point I suspect we could consolidate them).

(While we're on that topic, would it be sensible to consider making said file text instead of binary? It might make merging/diffing less painful.)

**Comment by abadams** [comment]
They'll never be partially updated, so diffing merging shouldn't be an issue

**Comment by steven-johnson** [comment]
> diffing merging shouldn't be an issue

yeah, I was thinking more in terms of being easy to tell that there is a difference when looking at diffs in commit-reviews. 

(text format is really just gravy; consolidation into a single file is what I'm curious about.)
