### ISSUE TITLE
CSE cannot handle variables names with 't' + number properly

### ISSUE THREAD

**Issue by BachiLi** [halide/Halide#4124]
Hi,

The following code containing two variables "t0" and "t1" would break CSE:
```
    Var t0("t0"), t1("t1");
    Func x("x"), y("y");
    x(t0, t1) = t0 + t1; y(t0, t1) = t0 * t1;
    Func f("f");
    f(t0, t1) = x(t0, t1) * x(t0, t1) * y(t0, t1);
    std::cout << "f:" << f.value() << std::endl;
    Buffer<int> fb = f.realize(5, 5);
    std::cout << "fb(2, 3):" << fb(2, 3) << std::endl;
    std::cout << "Expected:" << (2 + 3) * (2 + 3) * (2 * 3) << std::endl;
```
The output is
```
f:(let t0 = x(t0, t1) in ((t0*t0)*y(t0, t1)))
fb(2, 3):375
Expected:150
```

Maybe an easy quick fix is to simply disallow user to declare Var with 't' + a number? Although I am slightly worried that this indicates that other CSE bugs exist when nesting variables.

**Comment by zvookin** [comment]
This was reported recently. I thought I filed an issue. Will look tomorrow.
I tried a couple fixes and they all had problems. Its likely time we
switched away from string typing via variable naming and add a flag for
compiler made variables plus whatever else we need.

**Comment by abadams** [comment]
The simplest fix is to probably just prefix all internally generated temporary names out of unique_name with '$'. $ is already forbidden in user-provided names.
