### ISSUE TITLE
apps/wavelet build failed on MacOS with standalone distrib halide

### ISSUE THREAD

**Issue by xbwee1024** [halide/Halide#4126]
Hi guys, 
When i build apps/wavelet on MacOS, it failed, log as following:

[10/55] Linking CXX executable examples/wavelet/haar_x.generator_binary
FAILED: examples/wavelet/haar_x.generator_binary
: && /Library/Developer/CommandLineTools/usr/bin/c++   -Wl,-search_paths_first -Wl,-headerpad_max_install_names -Wl,-force_load,./libhaar_x.generator_library.a examples/wavelet/CMakeFiles/haar_x.generator_binary.dirHALIDE_DISTRIB_DIR/tools/GenGen.cpp.o  -o examples/wavelet/haar_x.generator_binary  -Wl,-rpath,HALIDE_DISTRIB_DIR/bin -lz -lcurses -lm -lxml2 examples/wavelet/libhaar_x.generator_library.a HALIDE_DISTRIB_DIR/bin/libHalide.dylib && :
ld: file not found: ./libhaar_x.generator_library.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[11/55] Linking CXX executable examples/wavelet/inverse_haar_x.generator_binary
FAILED: examples/wavelet/inverse_haar_x.generator_binary
: && /Library/Developer/CommandLineTools/usr/bin/c++   -Wl,-search_paths_first -Wl,-headerpad_max_install_names -Wl,-force_load,./libinverse_haar_x.generator_library.a examples/wavelet/CMakeFiles/inverse_haar_x.generator_binary.dirHALIDE_DISTRIB_DIR/tools/GenGen.cpp.o  -o examples/wavelet/inverse_haar_x.generator_binary  -Wl,-rpath,HALIDE_DISTRIB_DIR/bin -lz -lcurses -lm -lxml2 examples/wavelet/libinverse_haar_x.generator_library.a HALIDE_DISTRIB_DIR/bin/libHalide.dylib && :
ld: file not found: ./libinverse_haar_x.generator_library.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[12/55] Linking CXX executable examples/wavelet/inverse_daubechies_x.generator_binary
FAILED: examples/wavelet/inverse_daubechies_x.generator_binary
: && /Library/Developer/CommandLineTools/usr/bin/c++   -Wl,-search_paths_first -Wl,-headerpad_max_install_names -Wl,-force_load,./libinverse_daubechies_x.generator_library.a examples/wavelet/CMakeFiles/inverse_daubechies_x.generator_binary.dirHALIDE_DISTRIB_DIR/tools/GenGen.cpp.o  -o examples/wavelet/inverse_daubechies_x.generator_binary  -Wl,-rpath,HALIDE_DISTRIB_DIR/bin -lz -lcurses -lm -lxml2 examples/wavelet/libinverse_daubechies_x.generator_library.a HALIDE_DISTRIB_DIR/bin/libHalide.dylib && :
ld: file not found: ./libinverse_daubechies_x.generator_library.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[15/55] Building CXX object examples/wavelet/CMake...generator_library.dir/daubechies_x_generator.cpp.o
ninja: build stopped: subcommand failed.

**Comment by xbwee007** [comment]
It seems like that I should explicitly add the property "LIBRARY_OUTPUT_DIRECTORY" 

diff --git a/halide.cmake b/halide.cmake
index 55c9efc52..87d62bf68 100644
--- a/halide.cmake
+++ b/halide.cmake
@@ -69,6 +69,7 @@ function(halide_generator NAME)
       target_include_directories("${GENLIB}" PRIVATE
                                  $<TARGET_PROPERTY:${DEP},INTERFACE_INCLUDE_DIRECTORIES>)
     endforeach()
+    set_target_properties("${GENLIB}" PROPERTIES LIBRARY_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})
     # Ensure that Halide.h is built prior to any Generator
     add_dependencies("${GENLIB}" ${HALIDE_COMPILER_LIB})
     _halide_force_link_library("${NAME}_binary" "${GENLIB}")

**Comment by xbwee007** [comment]
> It seems like that I should explicitly add the property "LIBRARY_OUTPUT_DIRECTORY"
> 
> ```shell
> diff --git a/halide.cmake b/halide.cmake
> index 55c9efc52..87d62bf68 100644
> --- a/halide.cmake
> +++ b/halide.cmake
> @@ -69,6 +69,7 @@ function(halide_generator NAME)
>        target_include_directories("${GENLIB}" PRIVATE
>                                   $<TARGET_PROPERTY:${DEP},INTERFACE_INCLUDE_DIRECTORIES>)
>      endforeach()
> +    set_target_properties("${GENLIB}" PROPERTIES LIBRARY_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})
>      # Ensure that Halide.h is built prior to any Generator
>      add_dependencies("${GENLIB}" ${HALIDE_COMPILER_LIB})
>      _halide_force_link_library("${NAME}_binary" "${GENLIB}")
> ```

This will make halide source tree build failed.

I thinks the right way is:
add following into your project toplevel CMakeLists.txt:

```cmake
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_MACOSX_RPATH ON)


set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
```
