### ISSUE TITLE
Build Android Executable

### ISSUE THREAD

**Issue by rocrover** [halide/Halide#4136]
Is there a way to build an executable on Android devices without using NDK? I come up with the following CMakeLists.txt. 

```
include_directories( ... )

# Generator
halide_library( static_lib
                SRCS static_lib.cpp 
                GENERATOR_ARGS auto_schedule=true 
                HALIDE_TARGET arm-64-android)

# Executable
add_executable( run run.cpp )
target_link_libraries( run PRIVATE static_lib )
target_compile_definitions( run PRIVATE HL_TARGET=arm-64-android )
```

But this has link error.
```
ld: ./genfiles/static_lib.a(static_lib.a.o): Relocations in generic ELF (EM: 183)
./genfiles/static_lib.a: error adding symbols: File in wrong format
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by rocrover** [comment]
It turns out that using either ndk-build or CMake + NDK is imperative for a successful Android build.

**Comment by v-diepttn147** [comment]
Hello @rocrover, I'm new to Halide and trying to cross-compiling `bgu` example for arm-64-android. Could you please share your cross-compiling process? I have been searching all over and could not find any proper instructions. Thank you in advance!
