### ISSUE TITLE
Buildbot tests for llvm-trunk should consider doing pulls less often

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4139]
It's pretty common that pulls from llvm-trunk end up triggering significant rebuilds of the tree, which can be a long pole for testbranch verification. We could probably get by just fine by limiting pulls from llvm-trunk to ~one per day (with some way to force the issue when necessary), and would likely improve build/test latency substantially.

**Comment by alexreinking** [comment]
Is this still to-do?

**Comment by abadams** [comment]
Pretty sure this was handled.
