### ISSUE TITLE
apps/autoscheduler assumes x86-64-avx2 without checking for it

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4147]
If you run this test on a pre-AVX2 machine, you may or may not crash with SIGILL, depending on the particular schedule(s) that get chosen (and thus whether AVX2 instructions are generated).

(1) At a minimum we should check at the beginning of the autotune loop and fail gracefully the HL_TARGET features aren't supported, rather than just crashing
(2) Should AVX2 be the default training target? Would (say) SSE41 be just as good?

**Comment by abadams** [comment]
2) Using the right target is important here. The difference between avx2 and avx512 can be massive, in either direction unfortunately. sse41 vs avx2 is similarly a change in vector size with large performance implications.

**Comment by steven-johnson** [comment]
This should be addressed by https://github.com/halide/Halide/pull/4145/commits/d7a9e9678129d77d380d9ebb391bbc1dabbc7068 when/if https://github.com/halide/Halide/pull/4145 lands
