### ISSUE TITLE
Should HL_PERMIT_FAILED_UNROLL be the default?

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4149]
The autoscheduler currently defines HL_PERMIT_FAILED_UNROLL=1, because sometimes the autoscheduler's model for what will and will not turn into a constant during lowering is inaccurate, because Halide isn't perfect at constant-folding. The result of this is that sometimes we end up with the autoscheduler generating a schedule that requires this to be defined... which is confusing to a user who just wants to autoschedule and doesn't understand why the super-fast schedule that was found from an overnight run craters when actually put into use for 'normal' code.

Should we... 
- Just legitimize failure to unroll loops into constants, maybe making it a warning?
- Prevent the autoscheduler from allowing these?
- Add a Feature (ugh) to allow this (instead of an env var) so it can be controlled more tightly?
- Something else?

**Comment by steven-johnson** [comment]
FYI: the schedule in question has lots of unrolls on Vars, e.g.

        .unroll(y)
        .unroll(x)

...is this ever a valid thing to try?

**Comment by abadams** [comment]
Yeah, if x and y are bounded (e.g. come from the inside of a split).

I had hoped that HL_PERMIT_FAILED_UNROLL was no longer necessary. The autoscheduler is supposed to be able to figure out which loops have constant bounds, and the underlying compiler is now better at handling unrolls of loops of non-constant extent (but which have constant upper bounds). Can you paste the extent of the loop in question from the stmt file?

**Comment by abadams** [comment]
(For autotuning, we should leave HL_PERMIT_FAILED_UNROLL off so that schedules that require it get culled).

**Comment by steven-johnson** [comment]
We're still setting HL_PERMIT_FAILED_UNROLL=1 in autotune_loop.sh -- if we don't want it anymore we should remove it.

Let me extract the relevant stuff from the .stmt file. (FWIW, commenting out all of the .unrolls() in this schedule doesn't affect the benchmark noticeably.)

**Comment by steven-johnson** [comment]
The loop in question looks like this in the .stmt file:

```
          allocate image_bounded_y[uint16 * 192] in Stack
          let t2853 = (image_downsampled_y.s0.y.yi.base + t2848)
          let t2852 = (image_downsampled_y.s0.y.yi.base + t2847)
          let t2851 = (image_downsampled_y.s0.y.yi.base + t2846)
          for (image_downsampled_y.s0.y.yi.yi, 0, 2) {
            let image_bounded_y.s0.y.max_2.s = ((((image_downsampled_y.s0.y.yi.yi*16) + image_downsampled_y.s0.y.yi.base)*4) + int32(window_height_offset))
            produce image_bounded_y {
              for (image_bounded_y.s0.y.y, 0, 4) {
                image_bounded_y[(ramp(((image_bounded_y.s0.y.y*16) + image_bounded_y.s0.y.max_2.s), 1, 16) % x16(64))] = (max(min(input_image[((max(min(ramp(((image_bounded_y.s0.y.y*16) + image_bounded_y.s0.y.max_2.s), 1, 16), x16(t2820)), x16(input_image.min.1))*x16(input_image.stride.1)) + x16((t2845 - t2828)))], x16((uint16)8255)), x16((uint16)64)) - x16((uint16)64))
              }
              for (image_bounded_y.s0.y.y, 0, 4) {
                image_bounded_y[((ramp(((image_bounded_y.s0.y.y*16) + image_bounded_y.s0.y.max_2.s), 1, 16) % x16(64)) + x16(64))] = (max(min(input_image[((max(min(ramp(((image_bounded_y.s0.y.y*16) + image_bounded_y.s0.y.max_2.s), 1, 16), x16(t2820)), x16(input_image.min.1))*x16(input_image.stride.1)) + x16(((t2845 - t2828) + 1)))], x16((uint16)8255)), x16((uint16)64)) - x16((uint16)64))
              }
              for (image_bounded_y.s0.y.y, 0, 4) {
                image_bounded_y[((ramp(((image_bounded_y.s0.y.y*16) + image_bounded_y.s0.y.max_2.s), 1, 16) % x16(64)) + x16(128))] = (max(min(input_image[((max(min(ramp(((image_bounded_y.s0.y.y*16) + image_bounded_y.s0.y.max_2.s), 1, 16), x16(t2820)), x16(input_image.min.1))*x16(input_image.stride.1)) + x16(((t2845 - t2828) + 2)))], x16((uint16)8255)), x16((uint16)64)) - x16((uint16)64))
              }
            }
            consume image_bounded_y {
              image_downsampled_y[ramp(((image_downsampled_y.s0.y.yi.yi*16) + t2851), 1, 16)] = (let t2417 = ((((image_downsampled_y.s0.y.yi.yi*16) + image_downsampled_y.s0.y.yi.base)*4) + int32(window_height_offset)) in uint16x16((((uint32x16(image_bounded_y[(ramp(t2417, 4, 16) % x16(64))]) + uint32x16(image_bounded_y[(ramp((t2417 + 1), 4, 16) % x16(64))])) + uint32x16(image_bounded_y[(ramp((t2417 + 2), 4, 16) % x16(64))])) + uint32x16(image_bounded_y[(ramp((t2417 + 3), 4, 16) % x16(64))]))))
              image_downsampled_y[ramp(((image_downsampled_y.s0.y.yi.yi*16) + t2852), 1, 16)] = (let t2418 = ((((image_downsampled_y.s0.y.yi.yi*16) + image_downsampled_y.s0.y.yi.base)*4) + int32(window_height_offset)) in uint16x16((((uint32x16(image_bounded_y[((ramp(t2418, 4, 16) % x16(64)) + x16(64))]) + uint32x16(image_bounded_y[((ramp((t2418 + 1), 4, 16) % x16(64)) + x16(64))])) + uint32x16(image_bounded_y[((ramp((t2418 + 2), 4, 16) % x16(64)) + x16(64))])) + uint32x16(image_bounded_y[((ramp((t2418 + 3), 4, 16) % x16(64)) + x16(64))]))))
              image_downsampled_y[ramp(((image_downsampled_y.s0.y.yi.yi*16) + t2853), 1, 16)] = (let t2419 = ((((image_downsampled_y.s0.y.yi.yi*16) + image_downsampled_y.s0.y.yi.base)*4) + int32(window_height_offset)) in uint16x16((((uint32x16(image_bounded_y[((ramp(t2419, 4, 16) % x16(64)) + x16(128))]) + uint32x16(image_bounded_y[((ramp((t2419 + 1), 4, 16) % x16(64)) + x16(128))])) + uint32x16(image_bounded_y[((ramp((t2419 + 2), 4, 16) % x16(64)) + x16(128))])) + uint32x16(image_bounded_y[((ramp((t2419 + 3), 4, 16) % x16(64)) + x16(128))]))))
            }
          }
          free image_bounded_y
        }
```

The generated schedule looks like this:

```
    image_bounded_y
        .store_in(MemoryType::Stack)
        .split(y, y, yi, 16, TailStrategy::ShiftInwards)
        // .unroll(y)   <-- this is the non-constant unroll
        .unroll(x)
        .vectorize(yi)
        .compute_at(image_downsampled_y, yi)
        .store_at(image_downsampled_y, y)
        .reorder(yi, y, x)
        .reorder_storage(y, x);
```

**Comment by abadams** [comment]
But all the loops there have constant extent?

**Comment by steven-johnson** [comment]
Let's see, extent of y there should bet2833, which is

    let t2830 = ((image_downsampled_y.s0.y.y.loop_extent.s + 31)/32)
    let t2831 = min(image_downsampled_y.s0.y.min.s, 0)
    let t2832 = int32(window_height_offset)
    let t2833 = min(max(((((((input_image.min.1 - t2832) + 3)/4) - t2831) + 31)/32), 0), t2830)

which is definitely not a compiletime constant (`window_height_offset` is an input to the pipeline)

**Comment by abadams** [comment]
Interesting. So why did the autoscheduler think it was a constant? That seems like it needs diagnosing and fixing.

**Comment by steven-johnson** [comment]
No idea offhand. This pipeline is likely way too complex to easily prune down to something public -- any suggestions you have for debugging would be welcome.

**Comment by abadams** [comment]
Is there a .bound directive? If so maybe this line is incorrectly being triggered: https://github.com/halide/Halide/blob/master/apps/autoscheduler/FunctionDAG.h#L1071

I.e. somehow those are constant bounds at autoscheduling time but not at normal compile-time.

The only way a constant bound can enter the system (I think) is in the span constructor in FunctionDAG. The places where the third argument might be true are where constant bounds are injected. So a possibility is that apply_param_estimates is replacing the param with a constant, and then the mutated expression is analyzed and found to be a constant. Is there a reduction involved? Maybe this apply_param_estimates:
https://github.com/halide/Halide/blob/master/apps/autoscheduler/FunctionDAG.h#L844
which feeds into this scope look-up:
https://github.com/halide/Halide/blob/master/apps/autoscheduler/FunctionDAG.h#L908
causes this code path:
https://github.com/halide/Halide/blob/master/apps/autoscheduler/FunctionDAG.h#L935
which eventually triggers:
https://github.com/halide/Halide/blob/master/apps/autoscheduler/FunctionDAG.h#L520
?

**Comment by steven-johnson** [comment]
The interesting thing here is that if I enable HL_PERMIT_FAILED_UNROLL, I *do* end up with loops over that var that are constant. So something is failing to prove it during unroll but simplifying it later? Investigating.

**Comment by abadams** [comment]
That *is* interesting. Unrolling happens earlyish because it makes other analysis easier, but maybe if unrolling fails we should have a late unrolling pass which gives it a second chance before throwing an error.

**Comment by steven-johnson** [comment]
Ah, I think there's a `likely_if_innermost` cancellation issue: the loop bounds turns out to be an expression that like
```
((let t7966 = lots and lots of let-exprs) in
(((t7966 - likely_if_innermost(t7966)) + 79)/16))
```

clearly, `t7966 - likely_if_innermost(t7966)` should always simplify to 0, and thus the overall value should be constant 5 regardless of all the let-exprs. Are we missing this simplification somewhere?

**Comment by abadams** [comment]
I guess it should simplify to likely_if_innermost(0), and then we need constant folding rules for likely-if-innermost... yuck. Or maybe we should have rules that pull likely_if_innermost as far out as the next containing min/max/select.

Or we could just try unrolling again after loop partitioning.

**Comment by steven-johnson** [comment]
Adding new rules to Simplify_Sub to handle this case would be easy (and actually does fix my failure case), but we'd probably just encounter this sort of thing later on in some other form. (`likely` and `like_if_innermost` are pretty horrible, TBH.) Not sure what the most robust fix is likely to be (no pun intended).

**Comment by steven-johnson** [comment]
...or, in UnrollLoops, we could just remove all the likely_if_innermost and likely calls (like we do for `can_prove`) before simplifying...

**Comment by abadams** [comment]
Oh yeah, where it gets more aggressive with the simplification we should totally be stripping likelies.

**Comment by steven-johnson** [comment]
I'm going to close this as https://github.com/halide/Halide/pull/4151 basically resolves it.

**Comment by steven-johnson** [comment]
I'm seeing another case where I think it's a bad choice (rather than a simplification)... the injection of the constant bounds seems to be at FunctionDAG.h:743:

                producer_required[i].union_with(Span(a, b, bounds_are_constant));

but the details of how and why this is a bad choice, I'm not sure yet. Investigating.

**Comment by steven-johnson** [comment]
I'm also pondering if the tiling code in AutoSchedule.cpp could be inserting constant spans (two locations) -- the thing that is going bad is non-monotonic, so maybe there's a bad assumption there.
