### ISSUE TITLE
Readable/Writable Output for onnx->Halide Conversion

### ISSUE THREAD

**Issue by chtsao8** [halide/Halide#4150]
Hello,

I was wondering if it was possible for a read/writable file to be created as output to the onnx->Halide conversion pipeline? Since the pipeline seems to only output an object file, this prevents me from writing a new schedule directly in Halide and I'd have to compile a new object file to run my PyTorch network in Halide with a new schedule each time.

If not, I'm looking into adding this functionality - any tips would be appreciated (:

**Comment by abadams** [comment]
That would be a source-to-source translation from onnx to Halide, which is quite a different approach. I think @jrk had a student working on that?

**Comment by jrk** [comment]
I believe @jerryz123 had a quick prototype. @awherr may have also?

**Comment by jerryz123** [comment]
@chtsao8 I'm not sure what onnx->Halide pipeline you are referring to. 
I see you submitted an issue to https://github.com/jerryz123/onnx-halide, which leads me to believe you are referring to that prototype.

That utility should also emit .cpp source for a Halide generator, which you can modify

**Comment by benoitsteiner** [comment]
@chtsao8: Have you tried to use the Model class in apps/onnx/model.py ? It allows you to load an onnx model and convert it to a Halide pipeline, call the old autoscheduler to generate a decent schedule for the pipeline (I still need to open source the wrapper for the new autoscheduler), and jit compile the pipeline by calling model.run ? We use this regularly in a pytorch -> onnx -> halide flow.

**Comment by chtsao8** [comment]
@jerryz123 @benoitsteiner I'm currently using the pipeline in apps/onnx, and using the autoscheduler to run the Halide-converted network. What I'm doing is running the compiled onnx_converter.generator on a .onnx file like so: 

bin/host/onnx_converter.generator -g onnx_model_generator -o file/destination/ -f model_name target=host auto_schedule=true model_file_path=models/model.onnx

The generated object files are then compiled separately with a .cpp file I make myself to specify the input/output and run the Halide converted network. The only issue with this is that it's hard to write my own custom schedule for the network without digging into the unordered map converted_model_.tensors found in onnx_converter_generator.cc (based on what @asaadaldien said in an earlier issue), but I'm still unsure on how to use this to write a custom schedule. 

The best option would be to have a source to source output for the PyTorch->onnx->Halide pipeline instead of compiling and running object files, since I'll be able to modify the code in Halide directly and write a scheduler for the network. I don't believe this pipeline has that functionality yet.

**Comment by steven-johnson** [comment]
I'm going to close this; please reopen if it still needs attention.
