### ISSUE TITLE
Fail compilation and execution. 

### ISSUE THREAD

**Issue by rodvieirasilva** [halide/Halide#416]
Hello, I am trying to run the first example in Ubuntu 14.4, but the following errors occur: 

g++ lesson_01_.cpp -g -I ../include -L ../bin -lHalide  -lpthread -ldl -o lesson_01
../bin/libHalide.so: referência indefinida para `std::__throw_out_of_range_fmt(char const_, ...)@GLIBCXX_3.4.20'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Then I tried this: 

g++ lesson_01*.cpp -g -I ../include -L ../bin -lHalide  -lpthread -ldl -o lesson_01 -shared -fPIC

Compiled normally, but when trying to run the generated file displays the following error:

Segmentation fault (core image recorded)

What will be the problem? is missing some library?

Thank you very much.

Sorry for bad english.

**Comment by zvookin** [comment]
@abadams Can this be closed?

**Comment by abadams** [comment]
Yeah, we do distros against lots of gcc versions now

**Comment by rodvieirasilva** [comment]
Yes, Thank you very much.
