### ISSUE TITLE
Runtime Error with GPU execution on camera_pipe

### ISSUE THREAD

**Issue by MaheshRavishankar** [halide/Halide#417]
I am trying to write a GPU schedule for the camera pipe apps. I believe the schedule I have should give good performance. It was working about 6 months ago, but with the latest version of Halide I am getting the following runtime error : 

Error:
CUDA: cuLaunchKernel failed (CUDA_ERROR_INVALID_VALUE)
Failure inside halide_dev_run
Aborted (core dumped)

I am pasting my version of the camera_pipe app below. There are slight differences between this and the current app version but nothing significant. I dont think there are any errors in my schedule, please let me know if there is. One of the previous papers of Halide showed performance numbers with GPU on the same app. Is this available somewhere?

------------Start of Camera Pipe app with GPU schedule
# include <Halide.h>
# include <stdint.h>
# include <cstdio>
# include <sys/time.h>

static double rtclock() {
  struct timezone Tzp;
  struct timeval Tp;
  int stat;
  stat = gettimeofday (&Tp, &Tzp);
  if (stat != 0) printf("Error return from gettimeofday: %d",stat);
  return (Tp.tv_sec + Tp.tv_usec*1.0e-6);
}

using namespace Halide;

Var x("x"), y("y"), tx("tx"), ty("ty"), c("c");
Func processed("processed");

Func hot_pixel_suppression(Func input) {
    Expr a = max(max(input(x-2, y), input(x+2, y)),
                 max(input(x, y-2), input(x, y+2)));
    Expr b = min(min(input(x-2, y), input(x+2, y)),
                 min(input(x, y-2), input(x, y+2)));

```
Func denoised("denoised");
denoised(x, y) = clamp(input(x, y), b, a);

return denoised;
```

}

Func interleave_x(Func a, Func b) {
    Func out("out");
    out(x, y) = select((x%2)==0, a(x/2, y), b(x/2, y));
    return out;
}

Func interleave_y(Func a, Func b) {
    Func out("out");
    out(x, y) = select((y%2)==0, a(x, y/2), b(x, y/2));
    return out;
}

Func deinterleave(Func raw) {
    // Deinterleave the color channels
    Func deinterleaved("deinterleaved");

```
deinterleaved(x, y, c) = select(c == 0, raw(2*x, 2*y), 
                                select(c == 1, raw(2*x+1, 2*y),
                                       select(c == 2, raw(2*x, 2*y+1), 
                                              raw(2*x+1, 2*y+1))));
return deinterleaved;
```

}

Expr absd(Expr a, Expr b) {
    return select(a > b, a - b, b - a);
}

Func demosaic(Func deinterleaved) {
    // These are the values we already know from the input
    // x_y = the value of channel x at a site in the input of channel y
    // gb refers to green sites in the blue rows
    // gr refers to green sites in the red rows

```
// Give more convenient names to the four channels we know
```

  Func r_r("r_r"), g_gr("g_gr"), g_gb("g_gb"), b_b("b_b");
    g_gr(x, y) = deinterleaved(x, y, 0);
    r_r(x, y)  = deinterleaved(x, y, 1);
    b_b(x, y)  = deinterleaved(x, y, 2);
    g_gb(x, y) = deinterleaved(x, y, 3);

```
// These are the ones we need to interpolate
Func b_r("b_r"), g_r("g_r"), b_gr("b_gr"), r_gr("r_gr"), b_gb("b_gb"), r_gb("r_gb"), r_b("r_b"), g_b("g_b");

// First calculate green at the red and blue sites

// Try interpolating vertically and horizontally. Also compute
// differences vertically and horizontally. Use interpolation in
// whichever direction had the smallest difference.
Expr gv_r  =    (g_gb(x, y-1) + g_gb(x, y))/2;
Expr gvd_r = absd(g_gb(x, y-1), g_gb(x, y));
Expr gh_r  =    (g_gr(x+1, y) + g_gr(x, y))/2;
Expr ghd_r = absd(g_gr(x+1, y), g_gr(x, y));

g_r(x, y)  = select(ghd_r < gvd_r, gh_r, gv_r);

Expr gv_b  =    (g_gr(x, y+1) + g_gr(x, y))/2;
Expr gvd_b = absd(g_gr(x, y+1), g_gr(x, y));
Expr gh_b  =    (g_gb(x-1, y) + g_gb(x, y))/2;
Expr ghd_b = absd(g_gb(x-1, y), g_gb(x, y));

g_b(x, y)  = select(ghd_b < gvd_b, gh_b, gv_b);

// Next interpolate red at gr by first interpolating, then
// correcting using the error green would have had if we had
// interpolated it in the same way (i.e. add the second derivative
// of the green channel at the same place).
Expr correction;
correction = g_gr(x, y) - (g_r(x, y) + g_r(x-1, y))/2;
r_gr(x, y) = correction + (r_r(x-1, y) + r_r(x, y))/2;

// Do the same for other reds and blues at green sites
correction = g_gr(x, y) - (g_b(x, y) + g_b(x, y-1))/2;
b_gr(x, y) = correction + (b_b(x, y) + b_b(x, y-1))/2;

correction = g_gb(x, y) - (g_r(x, y) + g_r(x, y+1))/2;
r_gb(x, y) = correction + (r_r(x, y) + r_r(x, y+1))/2;

correction = g_gb(x, y) - (g_b(x, y) + g_b(x+1, y))/2;
b_gb(x, y) = correction + (b_b(x, y) + b_b(x+1, y))/2;

// Now interpolate diagonally to get red at blue and blue at
// red. Hold onto your hats; this gets really fancy. We do the
// same thing as for interpolating green where we try both
// directions (in this case the positive and negative diagonals),
// and use the one with the lowest absolute difference. But we
// also use the same trick as interpolating red and blue at green
// sites - we correct our interpolations using the second
// derivative of green at the same sites.

correction = g_b(x, y)  - (g_r(x, y) + g_r(x-1, y+1))/2;
Expr rp_b  = correction + (r_r(x, y) + r_r(x-1, y+1))/2;
Expr rpd_b = absd(r_r(x, y), r_r(x-1, y+1));

correction = g_b(x, y)  - (g_r(x-1, y) + g_r(x, y+1))/2;
Expr rn_b  = correction + (r_r(x-1, y) + r_r(x, y+1))/2;
Expr rnd_b = absd(r_r(x-1, y), r_r(x, y+1));

r_b(x, y)  = select(rpd_b < rnd_b, rp_b, rn_b);


// Same thing for blue at red
correction = g_r(x, y)  - (g_b(x, y) + g_b(x+1, y-1))/2;
Expr bp_r  = correction + (b_b(x, y) + b_b(x+1, y-1))/2;
Expr bpd_r = absd(b_b(x, y), b_b(x+1, y-1));

correction = g_r(x, y)  - (g_b(x+1, y) + g_b(x, y-1))/2;
Expr bn_r  = correction + (b_b(x+1, y) + b_b(x, y-1))/2;
Expr bnd_r = absd(b_b(x+1, y), b_b(x, y-1));

b_r(x, y)  =  select(bpd_r < bnd_r, bp_r, bn_r);    

// Interleave the resulting channels
Func r("r"),g("g"),b("b");
r(x,y) = interleave_y(interleave_x(r_gr, r_r),
                      interleave_x(r_b, r_gb))(x,y);
g(x,y) = interleave_y(interleave_x(g_gr, g_r),
                      interleave_x(g_b, g_gb))(x,y);
b(x,y) = interleave_y(interleave_x(b_gr, b_r),
                      interleave_x(b_b, b_gb))(x,y);


Func output("output");
output(x, y, c) = select(c == 0, r(x, y), 
                         select(c == 1, g(x, y), b(x, y)));


Target target = get_jit_target_from_environment();

/* THE SCHEDULE */    
if( target.features & ( Target::CUDA | Target::OpenCL ) ){

  // Basic naive schedule
  g_r.store_at(processed,Var("__block_id_x")).compute_at(processed,Var("__block_id_x"));
  g_b.store_at(processed,Var("__block_id_x")).compute_at(processed,Var("__block_id_x"));

  r_gr.store_at(processed,Var("__block_id_x")).compute_at(processed,Var("__block_id_x"));
  r_gb.store_at(processed,Var("__block_id_x")).compute_at(processed,Var("__block_id_x"));

  b_gr.store_at(processed,Var("__block_id_x")).compute_at(processed,Var("__block_id_x"));
  b_gb.store_at(processed,Var("__block_id_x")).compute_at(processed,Var("__block_id_x"));

  r_b.store_at(processed,Var("__block_id_x")).compute_at(processed,Var("__block_id_x"));
  b_r.store_at(processed,Var("__block_id_x")).compute_at(processed,Var("__block_id_x"));

  r.store_at(processed,Var("__block_id_x")).compute_at(processed,Var("__block_id_x")).unroll(x,2).unroll(y,2);
  g.store_at(processed,Var("__block_id_x")).compute_at(processed,Var("__block_id_x")).unroll(x,2).unroll(y,2);
  b.store_at(processed,Var("__block_id_x")).compute_at(processed,Var("__block_id_x")).unroll(x,2).unroll(y,2);

}
else{
  // optimized for X86
  // Don't vectorize, because sse is bad at 16-bit interleaving
  g_r.compute_at(processed, tx).vectorize(x,8);
  g_b.compute_at(processed, tx).vectorize(x,8);
  r_gr.compute_at(processed, tx).vectorize(x,8);
  b_gr.compute_at(processed, tx).vectorize(x,8);
  r_gb.compute_at(processed, tx).vectorize(x,8);
  b_gb.compute_at(processed, tx).vectorize(x,8);
  r_b.compute_at(processed, tx).vectorize(x,8);
  b_r.compute_at(processed, tx).vectorize(x,8);
  // These interleave in x and y, so unrolling them helps
  r.compute_at(processed, tx).unroll(x, 2).unroll(y, 2).vectorize(x,8);
  g.compute_at(processed, tx).unroll(x, 2).unroll(y, 2).vectorize(x,8);
  b.compute_at(processed, tx).unroll(x, 2).unroll(y, 2).vectorize(x,8);
}
return output;
```

}

// Func color_correct(Func input, ImageParam matrix_3200, ImageParam matrix_7000, Param<float> kelvin) {
Func color_correct(Func input, Image<float>& matrix_3200, Image<float>& matrix_7000, float kelvin){
    // Get a color matrix by linearly interpolating between two
    // calibrated matrices using inverse kelvin.

```
Func matrix("matrix");
Expr alpha = (1.0f/kelvin - 1.0f/3200) / (1.0f/7000 - 1.0f/3200);
Expr val =  (matrix_3200(x, y) * alpha + matrix_7000(x, y) * (1 - alpha));
matrix(x, y) = cast<int32_t>(val * 256.0f); // Q8.8 fixed point
matrix.compute_root();

Func corrected("corrected");
Expr ir = cast<int32_t>(input(x, y, 0));
Expr ig = cast<int32_t>(input(x, y, 1));
Expr ib = cast<int32_t>(input(x, y, 2));

Expr r = matrix(3, 0) + matrix(0, 0) * ir + matrix(1, 0) * ig + matrix(2, 0) * ib;
Expr g = matrix(3, 1) + matrix(0, 1) * ir + matrix(1, 1) * ig + matrix(2, 1) * ib;
Expr b = matrix(3, 2) + matrix(0, 2) * ir + matrix(1, 2) * ig + matrix(2, 2) * ib;

r = cast<int16_t>(r/256);
g = cast<int16_t>(g/256);
b = cast<int16_t>(b/256);
corrected(x, y, c) = select(c == 0, r,
                            select(c == 1, g, b));

return corrected;
```

}

// Func apply_curve(Func input, Type result_type, Param<float> gamma, Param<float> contrast) {
Func apply_curve(Func input, float gamma, float contrast){
    // copied from FCam
    Func curve("curve");

```
Expr xf = clamp(cast<float>(x)/1024.0f, 0.0f, 1.0f);
Expr g = pow(xf, 1.0f/gamma);
Expr b = 2.0f - (float)pow(2.0f, contrast/100.0f);
Expr a = 2.0f - 2.0f*b; 
Expr z = select(g > 0.5f,
                1.0f - (a*(1.0f-g)*(1.0f-g) + b*(1.0f-g)),
                a*g*g + b*g);

Expr val = cast<uint8_t>(clamp(z*256.0f, 0.0f, 255.0f));
curve(x) = val;

Target target = get_jit_target_from_environment();
if( target.features & ( Target::CUDA | Target::OpenCL ) ){
  curve.compute_root().cuda_tile(x,32); // It's a LUT, compute it once ahead of time.
}
else{
  curve.compute_root().vectorize(x,8);
}
Func curved("curved");
curved(x, y, c) = curve(input(x, y, c));

return curved;
```

}

void camera_pipe_halide(Image<int16_t>& input, Image<float>& matrix_3200, Image<float>& matrix_7000, float color_temp, float gamma, float contrast, Image<uint8_t>& output){

  Var xi, yi;

  Func shifted("shifted");
  shifted(x, y) = input(x+16, y+12); 

  Func denoised("denoised");
  denoised = hot_pixel_suppression(shifted);
  Func deinterleaved("deinterleaved");
  deinterleaved = deinterleave(denoised);
  Func demosaiced("demosaiced");
  demosaiced = demosaic(deinterleaved);
  Func corrected("corrected");
  corrected = color_correct(demosaiced, matrix_3200, matrix_7000, color_temp);
  Func curved("curved");
  curved = apply_curve(corrected, gamma, contrast);
  processed(tx,ty,c) = curved(tx, ty, c);

  // Schedule
  Target target = get_jit_target_from_environment();
  processed.bound(c, 0, 3); // bound color loop 0-3, properly
  if( target.features & ( Target::CUDA | Target::OpenCL ) ){
    denoised.compute_root().cuda_tile(x,y,32,8);
    deinterleaved.store_at(processed,Var("__block_id_x")).compute_at(processed,Var("__block_id_x"));
    demosaiced.store_at(processed,Var("__block_id_x")).compute_at(processed,Var("__block_id_x"));
    corrected.store_at(processed,Var("__block_id_x")).compute_at(processed,Var("__block_id_x"));
    processed.compute_root().reorder(c,tx,ty).cuda_tile(tx,ty,32,8);

```
// denoised.store_at(processed,Var("blockidx")).compute_at(processed,Var("blockidx"));
```

  } 
  else {
    // Same as above, but don't vectorize (sse is bad at interleaved 16-bit ops)
    denoised.compute_at(processed, tx).vectorize(x,8);
    deinterleaved.compute_at(processed, tx).vectorize(x,8);
    demosaiced.compute_at(processed, tx).vectorize(x,8);
    corrected.compute_at(processed, tx).vectorize(x,8);
    processed.tile(tx, ty, xi, yi, 128, 128).reorder(xi, yi, c, tx, ty).parallel(ty);
  }

  // return processed;
  processed.compile_jit();

  output = processed.realize(2560-32, 1920, 3);
  double start,stop,timer;
  timer =0.0;
  for( int i = 0 ; i < 5 ;i++ ){
    start = rtclock();
    output = processed.realize(2560-32,1920,3);
    stop = rtclock();
    timer += (stop-start);
  }
  timer /= 5.0;
  printf("[Halide] Computation Time : %lf\n",timer*1000.0);
}

int main(int argc, char **argv) {
    // The camera pipe is specialized on the 2592x1968 images that
    // come in, so we'll just use an image instead of a uniform image.
    Image<int16_t> input(2592, 1968);
    // ImageParam matrix_3200(Float(32), 2, "m3200"), matrix_7000(Float(32), 2, "m7000");
    // Param<float> color_temp("color_temp"); //, 3200.0f);
    // Param<float> gamma("gamma"); //, 1.8f);
    // Param<float> contrast("contrast"); //, 10.0f);

```
// shift things inwards to give us enough padding on the
// boundaries so that we don't need to check bounds. We're going
// to make a 2560x1920 output image, just like the FCam pipe, so
// shift by 16, 12

// Parameterized output type, because LLVM PTX (GPU) backend does not
// currently allow 8-bit computations
// int bit_width = 8; //atoi(argv[1]);
// Type result_type = UInt(bit_width);

for( int i = 0 ; i < 1968 ; i++)
  for( int j = 0 ; j < 2592 ; j++) 
input(j,i) = rand()%256;

Image<uint8_t> output; // image size is hard-coded for the N900 raw pipeline

// These color matrices are for the sensor in the Nokia N900 and are
// taken from the FCam source.
float _matrix_3200[][4] = {{ 1.6697f, -0.2693f, -0.4004f, -42.4346f},
               {-0.3576f,  1.0615f,  1.5949f, -37.1158f},
               {-0.2175f, -1.8751f,  6.9640f, -26.6970f}};

float _matrix_7000[][4] = {{ 2.2997f, -0.4478f,  0.1706f, -39.0923f},
               {-0.3826f,  1.5906f, -0.2080f, -25.4311f},
               {-0.0888f, -0.7344f,  2.2832f, -20.0826f}};
Image<float> matrix_3200(4, 3); 
for( int i = 0 ; i < 3 ; i++ )
  for( int j = 0 ; j < 4 ;j++ )
matrix_3200(j,i) = _matrix_3200[i][j];
Image<float> matrix_7000(4, 3);
for( int i = 0 ; i < 3 ; i++ )
  for( int j = 0 ; j < 4 ;j++ )
matrix_7000(j,i) = _matrix_7000[i][j];

float color_temp = 3700;
float gamma = 2.0;
float contrast = 50;


// Build the pipeline
// Func processed = process(shifted, result_type, matrix_3200, matrix_7000, color_temp, gamma, contrast);
camera_pipe_halide(input,matrix_3200,matrix_7000,color_temp,gamma,contrast,output);

//string s = processed.serialize();
//printf("%s\n", s.c_str());

// In C++-11, this can be done as a simple initializer_list {color_temp,gamma,etc.} in place.
// Argument args[] = {color_temp, gamma, contrast, Buffer(input), matrix_3200, matrix_7000};
// processed.compile_to_file("curved", std::vector<Argument>(args, args+6));
// processed.compile_to_assembly("curved.s", std::vector<Argument>(args, args+6));

return 0;
```

}

**Comment by MDBrothers** [comment]
I see this error message when I have a long pipeline, with shared memory not being the issue. Interspersing compute_root helps. The autoscheduler handles this automatically for CPU code, but more attention from the coder is needed for GPU code.

**Comment by Poutsh** [comment]
@MDBrothers Hi, I'm facing the same problem right now, trying to schedule a long pipeline on GPU. Could you explain more precisely how you solved it?

**Comment by Poutsh** [comment]
@MDBrothers Thank you for your quick answer, I have this problem in one specific part of the schedule where I literally cannot use GPU or so I get this error but I have indeed a lot of inlining.

**Comment by Poutsh** [comment]
I've fixed my error, the reason was that a compute_at in my schedule was using too much shared memory per block so I changed it to a compute_root and arranged some gpu_tile to make it work correctly and optimized. compute_at creates temporary buffers so it doesn't have to recalculate everything. So it's not a good idea to use a compute_at in a function that uses tons of memory.

**Comment by MDBrothers** [comment]
Nice going @Poutsh ! I thought it was something like this.

**Comment by jrk** [comment]
There's a lesson for us here (which I think we all know, but on which we haven't taken much action):

Targets with more flexible memory systems tend to smoothly degrade when you make choices like this. e.g., you can use essentially as many live variables as you want due to inlining, or as much block-level storage due to `compute/store_at`, and you will just see performance degrade.

GPU targets have hard limits on many resources, and simply blow up when you overflow them.

Currently, we don't do much to catch these problems during lowering, so users see GPU API-level errors, which generally aren't very descriptive, are never tied to specific aspects of their Halide code, and usually appear at *run time*, not compile time.

Perhaps lowering for GPU targets should invest more effort in checking for common limits. There's some proliferation of details across GPU vendors, generations, and instances, and we probably don't want to be in the game of tracking and specifying all of these all the time, but I suspect there are low-hanging fruit, e.g. catching and reporting register, shared memory, and block size limits where the analysis is easy, for the last couple generations of NVIDIA hardware.
