### ISSUE TITLE
apps/HelloPyTorch test issues warning

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4176]
When I do `make test` for apps/HelloPyTorch, it passes, but I get this warning:

```
/usr/local/google/home/srj/.local/lib/python3.6/site-packages/torch/autograd/gradcheck.py:242: UserWarning: At least one of the inputs that requires gradient is not of double precision floating point. This check will likely fail if all the inputs are not of double precision floating point.
  'At least one of the inputs that requires gradient '
```

I don't know what this is or whether I should worry -- do I have a bad install? 

Ideally our tests shouldn't emit any warnings; if this is 'expected' then we should suppress it somehow (or, if that is infeasible, add comments stating that this is expected and why we can safely ignore it).

**Comment by mgharbi** [comment]
I ll look into suppressing it / remove this test. The test checks the gradient of the float operators, so the input are expected to not be double. But the torch helpers warns about potential precision errors.

**Comment by mgharbi** [comment]
#4217 should fix it
