### ISSUE TITLE
buffer_t should be defined in a public-facing header file

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#418]
The Halide buffer_t type is currently defined in buffer_t.h, which isn't directly exported; it's replicated into Halide.h but not HalideRuntime.h, which is a problem for code that doesn't want to link with libHalide (Halide.h brings in Introspection-related symbols that are hard to avoid).

This usually isn't a problem, as code that works with buffer_t is usually including at least one Halide-generated header file (which includes an inline definition of buffer_t); this is suboptimal if you want to make some utility code that operates on buffer_t but doesn't rely on any specific filter.

Suggestion: let's replicate the inlining of buffer_t into HalideRuntime.h to allow for this.

**Comment by steven-johnson** [comment]
This has now been pending for ~6 months; if the buffer_t work that is coming up isn't imminent, can we move forward?

**Comment by abestephensg** [comment]
Here is a PR for the branch I added last week. https://github.com/halide/Halide/pull/670

**Comment by steven-johnson** [comment]
Long since fixed.
