### ISSUE TITLE
CMakeLists.txt doesn't attempt to use `llvm-config --cxxflags`, but should

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4187]
Our Makefile has ~always used this to construct our options, but our CMake file hasn't.

Recently-ish, LLVM started requiring C++14 (and `--cxxflags` will include a string with `-std=c++14` in it), but our CMakeLists.txt explicitly specifies C++11, so we can't compile properly (at least on Linux).

As a short-term fix we can just upgrade our CMake file to use C++14; longer term we need to smarten our CMake build files.

**Comment by alexreinking** [comment]
Why does LLVM require C++14 in its interface? Generally speaking, these sorts of properties should be available on LLVM's exported CMake targets (ie. we should have to do much less of these shenanigans ourselves)

**Comment by steven-johnson** [comment]
> Why does LLVM require C++14 in its interface?

You are asking the wrong person.

**Comment by alexreinking** [comment]
LLVM 10+ requires C++14. http://llvm.org/docs/CMake.html#rarely-used-cmake-variables

We should just bump the number and forget about it. It should be backwards compatible with older LLVMs and the headers _should_ be forward-compatible (but we should test this).

**Comment by steven-johnson** [comment]
> these sorts of properties should be available on LLVM's exported CMake targets

That's only useful for people using CMake. As long as we have non-CMake builds, we'll have to use llvm-config (or dig into the CMake stuff manually in our build tooling)

**Comment by alexreinking** [comment]
Appears to be irrelevant in the new CMake build. If we run into issues again, we'll work through those on a case-by-case basis.
