### ISSUE TITLE
Not able to pass NAN value using select

### ISSUE THREAD

**Issue by BSYMAHESH** [halide/Halide#4213]
I am trying to pass NAN value based upon some condition to func Vq but i am getting 20 instead of NAN. 

 Vq(x,y) = select(xq(x,y) < 20, NAN, Expr(1.0f)); 

But
Vq(x,y) = select(xq(x,y) < 20, 100, Expr(1.0f));  is working fine.

Can any one please explain me why this is happening? How can I pass NAN value based upon some condition

Thanks

**Comment by steven-johnson** [comment]
Are you compiling with `strict_float`? If not, Halide is using the equivalent of `-ffast-math`, which is allowed to assume that NaNs and Infinities can never happen.

**Comment by steven-johnson** [comment]
I'm going to assume this is no longer active; please reopen if strict_float doesn't address your issue
