### ISSUE TITLE
Purge draft GitHub releases

### ISSUE THREAD

**Issue by jrk** [halide/Halide#4228]
I was seriously confused when looking at the Releases tab as a contributor, since it includes many ancient items in “draft” state at the top of the list. This hopefully doesn’t affect outside users, but it still seems like time to discard ~all of these draft releases. I am glad to do so if @steven-johnson / @abadams agrees.

**Comment by abadams** [comment]
👍

**Comment by steven-johnson** [comment]
SGTM

**Comment by jrk** [comment]
Done!
