### ISSUE TITLE
Autoscheduler produces schedule with update stage that fails to compile

### ISSUE THREAD

**Issue by kpassarella** [halide/Halide#4243]
The compiler failure message is 'Call to update with index larger than last defined update stage for Func "f1".'

The Func in question is doing an update of size 9-10 (it varies), so it seems like a parallelism and/or tail strategy issue.

The source code that produces this is proprietary, but I'm working on producing a simpler case that reproduces the issue. I'll share it here once it's done.

**Comment by steven-johnson** [comment]
assigning to @abadams to redirect as he sees fit :-)

**Comment by abadams** [comment]
That error message refers to the number of update definitions a Func has. I.e. calling func.update(2) on a Func that has fewer than 3 update definitions. So it shouldn't be related to loops or tail strategies. It's probably that the generated schedule source being used is out of sync with the actual algorithm, meaning that the schedule source is trying to schedule the update definition of a Func that doesn't have one. We should implement some kind of checking at the top of the generated schedule to check that at least the number of Funcs hasn't changed.

**Comment by steven-johnson** [comment]
> We should implement some kind of checking at the top of the generated schedule to check that at least the number of Funcs hasn't changed.

See also: https://github.com/halide/Halide/issues/4068

**Comment by kpassarella** [comment]
While I agree that that would be a good check to add, the algorithm here wasn't modified between generating the schedule and compiling, though, so out-of-sync issues shouldn't have been the cause for this error.

**Comment by abadams** [comment]
I would guess that it's out-of-sync in some other way then. E.g. the order in which the Funcs are put into a topological order is not consistent somehow.

**Comment by steven-johnson** [comment]
Is this still active?

**Comment by kpassarella** [comment]
I just synced to head and it still produces a schedule with that error. I haven't been able to successfully get a simpler case that reproduces it (but also didn't spend a ton of time on it, so I could try again). Feel free to close this if it's not possible to investigate without an example right now.

**Comment by steven-johnson** [comment]
I'm going to close this since the general issue is known and documented elsewhere, but this specific issue is too stale to be actionable.
