### ISSUE TITLE
Halide should adopt an explicit Code Of Conduct

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4256]
I don't think should be a controversial assertion at this point of time.

@zvookin suggested (offline) that the Contributor's Covenant would be a good starting point (https://www.contributor-covenant.org/version/1/4/code-of-conduct); I happen to agree (it's nicely short and to-the-point). In point of fact I was tempted to making it a fait accompli by opening a PR to land it as CODE_OF_CONDUCT.md, but discussion outside of a PR is surely a better way to go about doing this.

**Comment by abadams** [comment]
To my taste, I think llvm's is substantially better: https://llvm.org/docs/CodeOfConduct.html

It's more explicit regarding how we would like people to behave in an arguing-about-code/algorithms setting, and so is probably more likely to be directly applicable to a difficult situation than the contributor covenant. It also contains useful generalizations missing from the contributor covenant such as: "In general, if someone asks you to stop, then stop. Persisting in such behavior after being asked to stop is considered harassment."

**Comment by steven-johnson** [comment]
Also looks reasonable to me.
