### ISSUE TITLE
Derivate::get(unbounded) lacks tests

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4264]
From elsewhere: "Each Func in the forwards pipeline maps to multiple Funcs in the backwards pipeline. You get a bunch of boundary conditions injected to make the derivatives correct. The bounded flag lets you grab the Func before or after this boundary condition is applied, so if you want to just compute_root everything you might want to schedule both. So it's meaningful, if currently unused. Manually scheduling the reverse pipelines is... difficult."

This functionality is useful, but (AFAICT) untested; tests (and hopefully documentation) should be added to make this useful.

**Comment by abadams** [comment]
I believe the boundary conditions have mostly been removed at this point, so the unbounded variant doesn't exist anymore.
