### ISSUE TITLE
Build error due to missing detail::throw_cmdline_error in namespace

### ISSUE THREAD

**Issue by voidcycles** [halide/Halide#4270]
It looks like throw_cmdline_error should have been declared inside of the detailed namespace:
```
Halide/apps/autoscheduler/../support/cmdline.h: In member function ‘T cmdline::range_reader<T>::operator()(const string&) const’:
../support/cmdline.h:197:43: error: ‘throw_cmdline_error’ is not a member of ‘cmdline::detail’
     if (!(ret>=low && ret<=high)) detail::throw_cmdline_error("range_error");

```

This causes a build failure on master when building on Linux using GCC/G++ GNU 7.4.0

**Comment by steven-johnson** [comment]
Yeah, noticed that this morning -- fix is being rolled in to https://github.com/halide/Halide/pull/4269 which will land as soon as all the buildbots are green.

**Comment by voidcycles** [comment]
Woot!  Thanks!  I'll grab that changeset as soon as it goes green.
