### ISSUE TITLE
Cost of a reorder call

### ISSUE THREAD

**Issue by eloi-loomai** [halide/Halide#4291]
When I call the channels reordering function, how does Halide do that fast enough? On a large image, is that really copying the data or am I misunderstanding something?

Thanks.

**Comment by abadams** [comment]
I'm not sure which function you're referring to? Is this a method on Halide::Runtime::Buffer?

**Comment by eloi-loomai** [comment]
I mean in a scheduling like: `output.vectorize(x, vector_size).reorder(c, x, y).unroll(c);`

**Comment by ashishUthama** [comment]
There is no copy, it just changes the loop order, i,e
from say the default
 for c:
   for y
     for x
to  (with reorder(c,x,y)
 for y
  for x
   for c

The order of vars in the reorder call is from innermost to outer..

**Comment by zvookin** [comment]
There is also reorder_storage, which changes the memory layout. Once again
the directive itself doesn't copy anything, but of course both loop and
storage order have performance implications in various ways. Per the
question of copying, a stage in Halide is generally always reading one
buffer and writing another so the fact that there isn't another copy here
is unsurprising.

-Z-

**Comment by eloi-loomai** [comment]
Oh I see, yes makes sense.
