### ISSUE TITLE
failed when run  onnx app

### ISSUE THREAD

**Issue by FrancoisMoreau** [halide/Halide#4308]
Hi, 

I am trying to run the test, so I tried `make test`, however, it failed with error:

`if [ -f /onnx/onnx.proto ]; then \
	cp /onnx/onnx.proto bin/host/onnx/onnx.proto ; \
else \
	curl https://raw.githubusercontent.com/onnx/onnx/v1.4.1/onnx/onnx.proto > bin/host/onnx/onnx.proto; \
fi
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18918  100 18918    0     0  20756      0 --:--:-- --:--:-- --:--:-- 20743
/usr/local/bin/protoc --cpp_out=. bin/host/onnx/onnx.proto

cp bin/host/onnx/onnx.pb.h bin/host/onnx/onnx_pb.h
g++ -O3 -std=c++11 -I ../../distrib/include/ -I ../../distrib/tools/  -Wall -Werror -Wno-unused-function -Wcast-qual -Wignored-qualifiers -Wno-comment -Wsign-compare -Wno-unknown-warning-option -Wno-psabi -fno-rtti -DGOOGLE_PROTOBUF_NO_RTTI -Wno-sign-compare -Wno-unused-but-set-variable -I/usr/local/bin/../include -Ibin/host -fPIC -c onnx_converter.cc -o bin/host/onnx_converter_lib.o
onnx_converter.cc: In function ‘Node convert_random_node(const onnx::NodeProto&, const std::vector<Tensor>&)’:
onnx_converter.cc:2752:49: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
             seed = reinterpret_cast<int &>(fseed);
                                                 ^
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
cc1plus: all warnings being treated as errors
Makefile:37: recipe for target 'bin/host/onnx_converter_lib.o' failed
`

I tried to find any available documents about the if any lib/env I missed, but I found nothing. 
my gcc version: 5.4, llvm: 7
preinstalled: libprotobuf
Thanks.

**Comment by FrancoisMoreau** [comment]
the core problem is: 
`onnx_converter.cc: In function ‘Node convert_random_node(const onnx::NodeProto&, const std::vector<Tensor>&)’:
onnx_converter.cc:2752:49: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
             seed = reinterpret_cast<int &>(fseed);
                                                 ^
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
cc1plus: all warnings being treated as errors
`
I mean, Do I have to turn off the -Werror option?

**Comment by steven-johnson** [comment]
`-Wno-unknown-warning-option` is a red herring; the real issue here is `-Werror=strict-aliasing`, which (AFAICT) we don't have set in our build rules; it must be picking it up from your build environment somehow.

(Note that I'd be in favor of making the code strict-alias-clean so that this could be enabled everywhere, but I don't know how much work would be involved.)

**Comment by FrancoisMoreau** [comment]
I disabled it and it works! Thanks!
