### ISSUE TITLE
Debug build in Cross Compilation/AOT Compilation

### ISSUE THREAD

**Issue by arnablegend** [halide/Halide#4321]
I am trying to profile a Halide pipeline using VTune. One of the issues I ran into is that there is no debug symbols present in the object file generated.

I used the following API
```c++
void Halide::Func::compile_to_file(const std::string &filename_prefix,
                                   const std::vector< Argument > &args,
                                   const std::string &fn_name = "", 
                                   const Target &target = get_target_from_environment())
```

Running `file` on generated object file shows no `debug_info` present. 
Is it possible to generate the object file with debug symbols?

**Comment by abadams** [comment]
Unfortunately no, not really. Halide is embedded in C++, so it's not clear what standard debug symbols would even mean. What file and line number should we attach to a piece of machine-generated Halide imperative IR, created by a complex mixture of algorithm and schedule code? The best we can really do is the containing function name, which is already visible in the stack trace without additional debug symbols.

You should be aware of the built-in sampling profiler though. If you add -profile to your Halide target string you get a breakdown per-Func of runtime. Not as powerful as vtune obviously, but it does give you a sense of which Funcs are taking all the time.

**Comment by arnablegend** [comment]
@abadams thanks for the help. I have tried `xx-profile` option and got runtime per func.
I also tried `compile_to_c()` and then build with debug flag. I could check inside the pipeline with that.
