### ISSUE TITLE
All autoschedulers should be moved to a single location

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4349]
Currently we have the 'classic' autoscheduler baked into Halide, and the 'ML' autoscheduler living in apps/autoscheduler; soon we will also have the 'gradient' autoscheduler living in apps/gradient_autoscheduler.

We really need to refactor all of these so that:
- all are plugins ('classic' shouldn't be privileged anymore)
- all live somewhere other than apps/ (e.g. a new toplevel plugins/ folder or some such)
- all are built into distrib/ folder for binary distributions
- validation testing for all of them is available as part of the normal test suite (rather than via apps/)

**Comment by steven-johnson** [comment]
Ack, dupe of https://github.com/halide/Halide/issues/4349

**Comment by BachiLi** [comment]
Do we want to open this and close #4341? This seems much more informative.

**Comment by steven-johnson** [comment]
#4341 may or may not be worthy of a separate issue. Definitely leave this one closed as it's a dupe of #4349

**Comment by BachiLi** [comment]
But this is exactly #4349  ..?

**Comment by steven-johnson** [comment]
Whoops, copy-paste error! I meant #4350 4053
