### ISSUE TITLE
Usage of Feature::NoBoundsQuery

### ISSUE THREAD

**Issue by FrancoisMoreau** [halide/Halide#4363]
Hi, while I'm using halide, the feature::NoBoundsQuery makes me quite confused. 

When I DO NOT use this feature, it will generate a series of code check if the input/output buffer null, if it is, it will do halide_buffer_init(null_input_buffer). 
However, the pointer points to host buffer is still 0 after this halide_buffer_init, I wonder what's the point of this behaviour ? 
Thanks.

**Comment by abadams** [comment]
A bounds query lets you ask a Halide pipeline how large the inputs buffers need to be to compute a given output. You make an output buffer of the size you want, and then pass empty input buffers. It fills in the min/extent fields for you in the dim array. It doesn't actually allocate the buffers, it just tells you how large they would need to be to avoid out of bounds errors.

**Comment by FrancoisMoreau** [comment]
Thank you.
