### ISSUE TITLE
random_uint() alternates between an odd and even number every iteration

### ISSUE THREAD

**Issue by billythedummy** [halide/Halide#4377]
I'm trying to generate an array of random bits as `uint8_t`s in one of my Halide programs. I thought the easiest way to do it would be to just call `random_uint() % 2` and cast. However, it seems like the `random_uint()` function is not quite random enough for this since the numbers alternate between odd and even at every iteration. 

#### Code:
```
size_t size = 10;
uint8_t data[]
Halide::Buffer<uint8_t> view(data, size);
Halide::Var i;
Halide::Expr rand = Halide::print(Halide::random_uint()) % 2;
Halide::Func set;
set(i) = Halide::cast<uint8_t>(rand);
set.realize(view);
```
#### Output I got:
```
3843176938
275847699
3085079036
3680936357
2063419662
2527496247
778198816
1110494665
3524383794
3724898907
```

Not sure how high priority this issue will be since this use case might not be that widespread. Thanks in advance for looking into it!

**Comment by billythedummy** [comment]
nevermind, I just wasn't seeding the RNG.

**Comment by billythedummy** [comment]
Update: I realized I wasn't seeding the `Halide::random_uint()` so I changed that line to
```
Halide::Expr seed = (int) time(NULL);
...Halide::random_uint(seed)...
```
However, it seems like this issue still occurs.

My current workaround is just to use `Halide::random_uint(seed) / 10` instead and I'm getting more better results.

**Comment by abadams** [comment]
Like many simplistic random number generators, the low bits have a lower period than the high bits. If you want a single bit, use `random_uint(seed) >> 31`
