### ISSUE TITLE
standalone_autoscheduler_gpu condition failed

### ISSUE THREAD

**Issue by doronkuo** [halide/Halide#4386]
Hello, I'm trying to run some apps like camera_pipe.. on branch (standalone_autoscheduler_gpu) , when make test usually appear: Condition failed: at_or_inside_thread() at Autoscheduler.cpp 3715,
may I ask how to solve this bug, thanks a lots!

**Comment by abadams** [comment]
That's an experimental branch for research on automatic scheduling on GPUs in Halide. I wouldn't expect it to work at any given time - it's in heavy development. What are you trying to do?

**Comment by doronkuo** [comment]
I'm trying to hand-writing some gpu schedules on opencl device, but it's hard to get good performance. I am very interested in 2019 ml-based auto-scheduler paper, so try to use the standalone-autoscheduler-gpu branch, expected it can produce some good gpu-schedules.
But when testing some applications, it sometime get two errors:
- segfault at this line: `int64_t inner_extent = std::min(c->size[vectorized_loop_index], (int64_t)32);`, it seems that under certain scenario, the `c->size` is an empty vector.
(ref code)[https://github.com/halide/Halide/blob/standalone_autoscheduler_gpu/apps/autoscheduler/AutoSchedule.cpp#L3910%60]
- internal assertion (ref code)[https://github.com/halide/Halide/blob/standalone_autoscheduler_gpu/apps/autoscheduler/AutoSchedule.cpp#L3738]
And I know it still in development. Still thanks for your reply!

**Comment by steven-johnson** [comment]
I'm going to close this; please reopen if it still needs attention.
