### ISSUE TITLE
Incorrect Expr bounds calculated in FunctionDAG by Adams2019 autoscheduler

### ISSUE THREAD

**Issue by shubhamp-ca** [halide/Halide#4397]
https://github.com/halide/Halide/blob/a47d58e99724f282031655d5295fc9b904f565c0/apps/autoscheduler/FunctionDAG.cpp#L648

The code referenced above tries to calculate bounds of an expression for a given scope with rvar bounds, within FunctionDAG.cpp. It doesn't take into account function value bounds and fails if a Func is used as an expression. Concretely,
```
void generate() {
        input_clamped(x, y) = clamp(input(x, y), 0, 255);
        RDom my_r(0, input.width(), 0, input.height());
        hist(i) = cast<uint32_t>(0);
        hist(input_clamped(my_r.x, my_r.y)) += cast<uint32_t>(1);
        output(i) = hist(i);
    }
```
In the above code, the autoscheduler complains that region of hist is unbounded, though it is clearly bounded as input_clamped is clamped between (0, 255). Compilation aborts with the following error --
```
Condition failed: in.is_bounded():
Region computed of hist is unbounded: [((void *))neg_inf ((void *))pos_inf]
```
This is confirmed by simply replacing input_clamped reference inside hist update definition by "clamp(input(....))", in which case the autoscheduler is able to calculate the correct bounds for region of hist.

By adding function value bounds while calculating the bounds_of_expr_in_scope (tried locally), autoscheduler correctly calculates the bounds for the region to be computed. The problem is func_value_bounds are computed after this step by the FunctionDAG and are not available at this point. See --
https://github.com/halide/Halide/blob/a47d58e99724f282031655d5295fc9b904f565c0/apps/autoscheduler/FunctionDAG.cpp#L881-L885

Is there any reason they are calculated here (the above point being inside of a loop), as opposed to only once somewhere outside the loop? If the computation of func_value_bounds is hoisted out of the loop, it can be made available while calculating the bounds of expressions.

**Comment by shoaibkamil** [comment]
Andrew's on vacation for a couple weeks, so it might take a bit longer to answer this.

**Comment by shubhamp-ca** [comment]
> Andrew's on vacation for a couple weeks, so it might take a bit longer to answer this.

Sure. In the mean time, I will submit a corresponding PR so that it is easier see the change that I was referencing here.
