### ISSUE TITLE
CMake builds should probably use CTest instead of hand-rolled test rules

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4424]
CMake has some build-in support for building/running tests (https://cmake.org/cmake/help/latest/manual/ctest.1.html); I wasn't aware of this when I wrote the stuff we have now, and testing might be simpler and cleaner if we just used CTest instead. Not sure how much work it would be.

**Comment by steven-johnson** [comment]
(To be clear: it sorta-kinda does use CTest, but not in a very useful way.)

**Comment by alexreinking** [comment]
Closed by #4556
