### ISSUE TITLE
pipelines with no GPU API need to be able to handle output buffers with device_dirty already set

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4431]
https://github.com/halide/Halide/pull/4408 caused a failure in some Google-internal code that revealed an interesting failure mode:
- A test creates input and output Buffer<> fills both with arbitrary data via operator(); this means that both the input *and* output buffers have host-dirty set.
- Pass these to a function that operates on device; this ends up marking the output buffer as device-dirty, but (apparently) not clearing the host-dirty flag; now output buffer is in an illegal state (both dirty bits set)
- The test itself neglects to explicitly call copy-to-host, so it didn't notice the problem before; the change in #4408 injected a copy-to-host in generated code, which triggered a failure.

I ended up working around the issue by clearing the host-dirty flag for the output buffer in the test in question, but this brings up the issue of what the proper behavior here is:

- should we forbid output buffers from having any dirty bits set?
- and/or, should the code that sets device-dirty on output buffers be checking the host-dirty flag?

**Comment by abadams** [comment]
I would think that if an output is marked as host-dirty, and the pipeline wants to write to it on device, it should first do a copy-to-device, to for example preserve the region outside of the tile being written to. This must be missing from the pass that injects host<->device copies.

**Comment by steven-johnson** [comment]
> This must be missing from the pass that injects host<->device copies.

I was about to open an issue on this, but this is already an Issue. Maybe just change the description of this and assign it.

**Comment by abadams** [comment]
I'm having a hard time reproducing. Generated code only sets device_dirty if it has already copied to device, which clears host dirty. Is it possible the test does pixel access from C++ *after* writing to it on device? That would be a way to get both flags set.

**Comment by steven-johnson** [comment]
The case that I saw failing, was failing *inside* the halide-generated code; no C++ code was executed after that.

**Comment by abadams** [comment]
What I mean is, is it possible that the buffer got into the both-dirty-flags-set state outside of Halide, and it first caused a problem inside generated code? Because I can't see a way generated code could ever set both dirty flags.

**Comment by steven-johnson** [comment]
AFAICT, it got into host-dirty mode outside of halide (in C++ code); device-dirty happened inside of halide.

**Comment by abadams** [comment]
Do you have a repro? I tried a few things but I think Halide-generated code always does a copy-to-device on the output if it's going to write to it, which turns off the host dirty flag.

**Comment by steven-johnson** [comment]
I can make an internal-to-google repro, and from there I should be able to put together a public one.

**Comment by steven-johnson** [comment]
I went back to the original case and so far have been unable to repro, even with what should be the original conditions. I'll poke a little more but if I can't get a repro with modest extra effort let's just close this until we see another similar case.

**Comment by steven-johnson** [comment]
No luck in making a repro. Gonna close.
