### ISSUE TITLE
Is it possible to use global ids when generating OpenCL code?

### ISSUE THREAD

**Issue by Bastacyclop** [halide/Halide#4433]
Hi,

I tried only using `.gpu_threads()` without `.gpu_blocks()` hoping this would use global ids instead of workgroup and local ids when generating OpenCL code.
However this gives the error `Error: In schedule for f2, could not find dimension v3 to set to device API 2 in vars for function`.
Is it possible to use global ids when generating OpenCL code or do I have to use blocks / workgroups?

**Comment by Bastacyclop** [comment]
A related question would be: is it possible to use a dynamic block size that will only be known at runtime?

If I want to execute lines in parallel in groups of 8 I know that I can do:
```
.split(y, block, thread, 8).gpu_blocks(block).gpu_threads(thread);
```
But what if `8` comes from the OpenCL runtime?

**Comment by abadams** [comment]
You can split by a `Param<int>`, e.g:

```
    Func f;
    Var x;

    f(x) = 0;

    Var xo, xi;
    Param<int> p;
    f.split(x, xo, xi, p).gpu_blocks(xo).gpu_threads(xi);

    f.compile_jit();

    p.set(8);

    f.realize(100);
```

Note that I compile the pipeline before setting it to 8. You'd have to query the opencl runtime yourself to get the appropriate value for the Param.

Currently you have to use blocks/workgroups.

**Comment by Bastacyclop** [comment]
:+1:
