### ISSUE TITLE
bugs in fft2d_r2c fft2 apps/fft

### ISSUE THREAD

**Issue by JVision** [halide/Halide#4450]
Hi Team,

a bug was found in the fft library implemented in Halide. 
function fft2d_r2c in the directory apps/fft would trigger some crashes/exceptions when N0 and N1 is smaller than 16. 

A short example is given below. 

'
    Fft2dDesc fwd_desc;
    Fft2dDesc inv_desc;
    inv_desc.gain = 1.0f / (W * H);
    int W=8, H=8;
    ComplexFunc dft_in = fft2d_r2c(make_real(in), W, H, target, fwd_desc);
    ComplexFunc dft_out = fft2d_c2r(dft_in, W, H, target, inverse_desc);
    dft_out.compute_root();
    dft_out.realize();
'

Or replace the Makefile in the folder fft with the zipped Makefile, and run 
'
make test
'
the following messages will pop up.
'
bin/host/bench_fft 8 8 bin/host
Warning:
This pipeline is guaranteed to fail an assertion at runtime: 
halide_error_explicit_bounds_too_small("y", "constant_exterior", 0, 4, 0, 7)
Warning:
This pipeline is guaranteed to fail an assertion at runtime: 
halide_error_explicit_bounds_too_small("y", "constant_exterior", 0, 4, 0, 7)
Warning:
This pipeline is guaranteed to fail an assertion at runtime: 
halide_error_explicit_bounds_too_small("y", "constant_exterior", 0, 4, 0, 7)
Warning:
This pipeline is guaranteed to fail an assertion at runtime: 
halide_error_explicit_bounds_too_small("y", "constant_exterior", 0, 4, 0, 7)
Warning:
This pipeline is guaranteed to fail an assertion at runtime: 
halide_error_explicit_bounds_too_small("y", "constant_exterior", 0, 4, 0, 7)
Warning:
This pipeline is guaranteed to fail an assertion at runtime: 
halide_error_explicit_bounds_too_small("y", "constant_exterior", 0, 4, 0, 7)

'

[Makefile.zip](https://github.com/halide/Halide/files/3927637/Makefile.zip)

**Comment by abadams** [comment]
In general this pipeline doesn't work when the size of the FFT is not a multiple of the vector size. On AVX-512 machines I can only run it at 32x32. @dsharletg Any thoughts on what we should do about this, even if it's just a clearer error message?

**Comment by JVision** [comment]
If what I need is really a 8x8 tiled fft for an image with size 512x512, what is the correct efficient way to do? i prefer the halide way to fftw.

**Comment by steven-johnson** [comment]
See also https://github.com/halide/Halide/issues/4122

**Comment by dsharletg** [comment]
I'm working on improving this. There's no good reason for it to break like this.

Note that there are two errors involved here: one is simple and easy to fix (I think, still checking the solution). The other comes from the test the app runs, not the actual FFT itself. This one is more annoying to fix.
