### ISSUE TITLE
maximum buffer size is limted to  2G (2147483647) 

### ISSUE THREAD

**Issue by JVision** [halide/Halide#4460]
Hi team,

I am dealing with huge arrays and just discovered that the biggest array that I can deal with is limited to 2G. is this a known bug/issue? Any solutions. 

Here's the phenomenon. 

Error: Total allocation for buffer tile_normB.0 is 2547850240, which exceeds the maximum size of 2147483647

Thanks.

**Comment by abadams** [comment]
The -large_buffers target flag increases this to 64-bit indexing. It's not that way by default because it makes indexing math more expensive.

**Comment by JVision** [comment]
clear answer. gocha. Thanks.
