### ISSUE TITLE
Bounds inference for quiet_div

### ISSUE THREAD

**Issue by vksnk** [halide/Halide#4466]
I'm working on a GPU schedule for the image upsampling function and in some cases it asserts inside of the fuse_gpu_thread_loops. I think the issue is caused by bounds inference which returns pos_inf while estimating shared memory size. It looks like the reason is that expression which defines shared memory size contains quiet_div, which is not supported by the bounds inference (at least I couldn't find it mentioned anywhere in Bounds.cpp; there is handling of Div, though and if it matters divider in my case is constant and greater than zero, so it should work for my case). 

I saw https://github.com/halide/Halide/pull/4439, which seems to remove quiet_div completely and probably will fix this issue, but I figured still would post just in case.

**Comment by abadams** [comment]
quiet_div has indeed been removed
