### ISSUE TITLE
Accessing same memory location using float and int

### ISSUE THREAD

**Issue by yvn96** [halide/Halide#4471]
Hi,
I want to access value stored in a memory location and interpret it as a float or int type.
Example In C :
If I have
```
float int_to_float_halide() { 
    union {
        int i;
        float f;
    } t;

    t.i = 234234243;
    return t.f;
}
```
I am doing some operation in Int variable but using the float value. Is there a way this can be done in halide @abadams  ?

**Comment by abadams** [comment]
Store it as an int, and use `reinterpret<float>(some_expr)` to reinterpret the bits as a float instead when necessary. reinterpret is a no-op, it just changes the type.

**Comment by yvn96** [comment]
Thanks, working now.
