### ISSUE TITLE
-std=gnu++98 does not imply "no thread-syncing on static locals"

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4476]
A Googler comments:

>-std=gnu++98 has no effect on whether the compiler produces synchronization for function-local statics.  This is because gcc had the support prior to the standard anyway.  c++11 just mandated the behavior for everyone; this affected primarily Microsoft.
>
>Example on Haswell x64: https://gcc.godbolt.org/z/Dzx9tU
>
>Example on RISC-V: https://gcc.godbolt.org/z/ATXUYH
>
>If you don't want synchronization, the flag you should use is -fno-threadsafe-statics, example => https://gcc.godbolt.org/z/8ej1iO

**Comment by alexreinking** [comment]
Adding this to build system project since it's important to maintain this while I redo the libHalide target.

**Comment by alexreinking** [comment]
This is fixed in my cmake build branch.

**Comment by steven-johnson** [comment]
Should we also take the opportunity to enable C++11 for the runtime code (if we can disable threadsafe statics separately)?

**Comment by alexreinking** [comment]
It should compile with whatever the default language level is on the version of Clang that ships with the version of LLVM that you're linking against. That will be at least C++11 for Clang 8.0+
