### ISSUE TITLE
copy_to_host() not called when calling external function

### ISSUE THREAD

**Issue by zougloub** [halide/Halide#449]
I'm using an external C Func doing OpenCL computation, in the middle of an OpenCL pipeline.
Currently it looks like we have to retrieve the device buffer because Halide doesn't do it for me:

``` c++
extern "C" int run_some_code(buffer_t * in, buffer_t * out)
{
  get_the_data_to_the_device_creating_in_and_out_dev_if_needed();
  enqueue_opencl_computation();
#if defined(THIS_BUG_IS_FIXED)
  // This is what I'd like to do
  out->dev_dirty = 1;
#else
  // This is what I do to have something that works
  clFinish(queue);
  clEnqueueReadBuffer(queue, out->dev, CL_TRUE /* synchronous */, ...);
  out->host_dirty = 1;
#endif
}
```

Note: [ML ref for this issue](https://lists.csail.mit.edu/pipermail/halide-dev/2014-September/001144.html)

**Comment by dsharletg** [comment]
Sorry for the late reply, but I think this is intentional. We would not want to copy back to the host if you were going to do work with OpenCL in your extern stage. The intended fix is to call `halide_copy_to_host` on the buffer if you want to use it on the host.
