### ISSUE TITLE
Add task parallelism

### ISSUE THREAD

**Issue by jrk** [halide/Halide#45]
Just add an unordered flag to Block and throw them into the task pool.

**Comment by abadams** [comment]
Turned out to be more interesting than anticipated. See the async branch for prototype

**Comment by zvookin** [comment]
@abadams Can this be closed now?

**Comment by abadams** [comment]
No, async is not yet merged. It has a giant merge conflict with the storage folding changes

**Comment by jingpu** [comment]
Is there a PR for the async feature?

**Comment by abadams** [comment]
No, just a branch (async). It needs a nasty merge with master.

**Comment by abadams** [comment]
This was merged a while ago.
