### ISSUE TITLE
Allow static promises about values bounds of input images

### ISSUE THREAD

**Issue by jonbarron** [halide/Halide#451]
I am trying to do the following:
I have two n-length vectors x and y, and a 2xm list of pairs of indices into x and y. For each pair of indices, I would like to grab the value of x at index 1, and add it to the value of y at index 0, as follows:
y(pairs(0, i)) += x(pairs(1, i));
where i is an RDom over the height of pairs. Of course, this does not compile, as it's possible that the indices specified in "pairs" is outside of the range of x or y. To remedy this, I need to clamp the indices as follows:
y(clamp(pairs(0,i), 0, x.width()-1)) += x(clamp(pairs(1, i), 0, x.width()-1));
This works, but it does a lot of unnecessary and expensive clamping. It's also not necessarily the behavior I would like in this case, because if I had mistakenly set "pairs" such that the indices were out of range, I would rather the program crash than incorrectly access the elements at the beginnings or ends of x and y.

I would like to be able to guarantee to Halide that the values of "pairs" are within the range of x and y, to avoid this and to allow for no clamping. It seems like I could accomplish this by either providing a promise about the values present in "pairs", or perhaps a more loose promise that I will never try to access x or y out of their bounds.

( As an aside: the update y(pairs(0, i)) += x(pairs(1, i)) may have race conditions if elements of pairs(0, i) repeat themselves. They do not, by construction, and I am able to get the code to compile correctly by including allow_race_conditions() in the schedule. So, everything is okay on that front. )

**Comment by aTinker** [comment]
@zvookin  - I think I have a slightly different use case. 
Consider (simplified):

    #include <Halide.h>

    using namespace Halide;

    int main (int argc, char const *argv[])
    {
        Halide::ImageParam im(Halide::UInt(8), 2, "im"), lut(Halide::UInt(8),1,"lut");
        Halide::Var x("x"), y("y");
        Halide::Func limitedlut("limitedlut");
        // im(x,y) _will_ be one of [0 1 2 3 4];
        limitedlut(x,y) =lut(im(x,y));
        limitedlut.compile_to_file("limitedlut", {im, lut});
        limitedlut.compile_to_lowered_stmt("limitedlut.html", {im, lut}, HTML);
        return 0;
    }

I cant use a 1x5 LUT input to this function - the static bound check will assert. 

Is the only way forward right now to add a clamp? Maybe going with a full 256 element LUT would be more efficient (runtime wise) for me.

**Comment by abadams** [comment]
I'd just make lut size 256. If you don't control the allocation of lut,
then you could also lie, and tell Halide that lut is of size 256 even
though accessing anything beyond the first 5 elements would segfault.

**Comment by aTinker** [comment]
I added a

 clamp(im(x,y),0, 4)

From what I see in the HTML, that appears to have updated the assert to
check for 5 elements
and without any extra bound check happening in the loops.

This should be good enough for my use.

**Comment by dsharletg** [comment]
We also now have `unsafe_promise_clamped`.
