### ISSUE TITLE
ImageParams can be held by Exprs and also hold Exprs, so they can participate in reference cycles and cause leaks

### ISSUE THREAD

**Issue by abadams** [halide/Halide#4527]
E.g:
```
Halide::ImageParam result(Halide::type_of<float>(), 2); 
result.dim(1).set_stride(result.dim(0).extent());
```
We need to be able to detect cycles among Parameter objects. I don't think such a cycle can legally include a Function, (the Exprs in a Parameter can't call Functions), but this is probably unchecked, so some members of the cycle could be Function objects too.

It seems that everything that can be referred to by an Expr and also can hold Exprs needs to be cycle-aware.

**Comment by beauby** [comment]
Might be related to #2784?

**Comment by abadams** [comment]
Oh yeah, it's a duplicate of that.
