### ISSUE TITLE
correctness/atomics.cpp fails with CUDAVectorize engine

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#4554]
When running correctness/atomics.cpp with cuda enabled, llvm 9.0.1, and using the CMake build, the following happens:

```
alex@alex-ubuntu:~/Development/Halide/cmake-build-debug$ ./bin/correctness_atomics 
Error:
Line 244: Expected 77 instead of 76
Aborted (core dumped)
```

The CMake build is necessary because it defines LLVM_VERSION=90, whereas the Makefile doesn't.

HL_[JIT_]TARGET=x86-64-linux-cuda

**Comment by shoaibkamil** [comment]
Relatedly, this seems to be failing windows buildbots as well.

**Comment by alexreinking** [comment]
#4683 disabled these tests. Code comments suggest #4628 will provide a fix.

**Comment by alexreinking** [comment]
Since #4628 landed, I wonder if these tests work again?

https://github.com/halide/Halide/blob/26ebef3f0480eb65d1b79fefdac48d5682ec6021/test/correctness/atomics.cpp#L1249-L1255
