### ISSUE TITLE
Deprecate LLVM8

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4560]
LLVM labeled LLVM10rc1 recently, with a final tag in February; trunk is now version 11. We can soon look to remove LLVM8 support from Halide (in accordance with our policy of supporting trunk + two previous versions).

**Comment by cassianocasagrande** [comment]
Is it really needed to deprecate older versions?
Our build setup is constantly broken by changes on llvm dependency. I'm thinking of compiling an older commit only.

Best regards,

**Comment by abadams** [comment]
The LLVM API changes regularly. This means that new code we write could easily be broken for older versions of LLVM, and so we have to test every change against every LLVM version we support. But we only have the ability to test against so many versions without running out of buildbot capacity (and sanity), so we picked a policy of supporting LLVM trunk plus the two most recent releases (currently 8 and 9). This seemed like a lot of LLVM versions to us.

If you want (untested) support for older llvm versions, you can change the build to disable the check, but it's probably better if you just update llvm at the same cadence as updating Halide, or your could use one of the Halide binary releases with LLVM baked in.

**Comment by cassianocasagrande** [comment]
I see, I think I'll change my build setup to download the arm64 binary and then compile the Python bindings on top of it.

Best regards,

**Comment by alexreinking** [comment]
You might be pleased to know that the cmake improvements I'm working on should simplify getting precompiled Halide packages. It will likely also support automatically fetching and compiling compatible LLVM sources as part of the build.

**Comment by steven-johnson** [comment]
LLVM 10 should be release-tagged within a few days. I'm going to move forward with switching the buildbots over.

**Comment by alexreinking** [comment]
Closed by  #4665
