### ISSUE TITLE
camera_pipe hangs on hvx

### ISSUE THREAD

**Issue by cjluo-nuro** [halide/Halide#4571]
Hi, has any one tried camera_pipe examples on qualcomm hvx?

It hangs for me when I try to run it on qualcomm board compiled with hvx_128 feature.

Build environment:
LLVM 9.0.1
Version: release_2019_08_27
I build libHalide.a with the top makefile using LLVM 9.0.1,
then build the camera_pipe binary using bazel (locally reverted the bazel deprecation PR)

The execution hangs on the first remote execute:

However build bazeldemo works for me on hvx with the same build flow (I manually updated bazeldemo code to add hexagon scheduler in the generator).

LOG:
with libhalide_hexagon_host.so and libhalide_hexagon_remote_skel.so under /

adb shell 'HL_DEBUG_CODEGEN=10 LD_LIBRARY_PATH=. ADSP_LIBRARY_PATH=".;/dsp" ./camera_pipe_process bayer_raw.png 3700 2.0 50 1.0 1 /tmp/output.png'
input: bayer_raw.png
       2592 1968
Hexagon: init_hexagon_runtime (user_context: 0x0)
    halide_get_library_symbol('halide_hexagon_remote_load_library') -> 
        0x7f9e04f29c
    halide_get_library_symbol('halide_hexagon_remote_get_symbol_v4') -> 
        0x7f9e04f3b4
    halide_get_library_symbol('halide_hexagon_remote_run') -> 
        0x7f9e050748
    halide_get_library_symbol('halide_hexagon_remote_release_library') -> 
        0x7f9e04fa90
    halide_get_library_symbol('halide_hexagon_host_malloc_init') -> 
        0x7f9e0500ac
    halide_get_library_symbol('halide_hexagon_host_malloc_deinit') -> 
        0x7f9e05015c
    halide_get_library_symbol('halide_hexagon_host_malloc') -> 
        0x7f9e0501a4
    halide_get_library_symbol('halide_hexagon_host_free') -> 
        0x7f9e05059c
    halide_get_library_symbol('halide_hexagon_remote_poll_log') -> 
        0x7f9e04fb5c
    halide_get_library_symbol('halide_hexagon_remote_poll_profiler_state') -> 
        0x7f9e04fc58
    halide_get_library_symbol('halide_hexagon_remote_profiler_set_current_func') -> 
        0x7f9e04fd3c
    halide_get_library_symbol('halide_hexagon_remote_power_hvx_on') -> 
        0x7f9e04f4b8
    halide_get_library_symbol('halide_hexagon_remote_power_hvx_off') -> 
        0x7f9e04f568
    halide_get_library_symbol('halide_hexagon_remote_set_performance') -> 
        0x7f9e04fed4
    halide_get_library_symbol('halide_hexagon_remote_set_performance_mode') -> 
        0x7f9e04fe08
    halide_get_library_symbol('halide_hexagon_remote_set_thread_priority') -> 
        0x7f9e04ffe0
Hexagon: halide_hexagon_initialize_kernels (user_context: 0x0, state_ptr: 0x5574bb33c0, *state_ptr: 0x0, code: 0x5574af3e80, code_size: 21040)
, code: 0x5574af90c0, code_size: 103080)
    Initializing shared runtime
    halide_remote_load_library(libhalide_shared_runtime.so) ->         0x2500add0
    allocating module state -> 
        0x55b27efb50
    halide_remote_load_library(libhalide_kernels0.so) ->         0x2500b1c0
halide_device_and_host_malloc validating input buffer: buffer(0, 0x0, 0x0, 0, uint8, {0, 128, 1})
halide_device_and_host_malloc: target device interface 0x5574bb3100
halide_hexagon_device_and_host_malloc called.
Hexagon: halide_hexagon_device_malloc (user_context: 0x0, buf: 0x7fc9b64d18)
    allocating buffer of 256 bytes
    halide_malloc size=256 ->         0x55b27efb80
    host <- 0x55b27efb80
halide_device_and_host_malloc validating input buffer: buffer(0, 0x0, 0x0, 0, int16, {0, 4, 1}, {0, 3, 4})
halide_device_and_host_malloc: target device interface 0x5574bb3100
halide_hexagon_device_and_host_malloc called.
Hexagon: halide_hexagon_device_malloc (user_context: 0x0, buf: 0x7fc9b64d70)
    allocating buffer of 152 bytes
    halide_malloc size=152 ->         0x55b27efd80
    host <- 0x55b27efd80
halide_copy_to_host validating input buffer: buffer(0, 0x0, 0x55b27ee100, 1, float32, {0, 4, 1}, {0, 3, 4})
halide_copy_to_host validating input buffer: buffer(0, 0x0, 0x55b27ee200, 1, float32, {0, 4, 1}, {0, 3, 4})
halide_device_and_host_malloc validating input buffer: buffer(0, 0x0, 0x0, 0, uint8)
halide_device_and_host_malloc: target device interface 0x5574bb3100
halide_hexagon_device_and_host_malloc called.
Hexagon: halide_hexagon_device_malloc (user_context: 0x0, buf: 0x7fc9b64da8)
    allocating buffer of 129 bytes
    halide_malloc size=129 ->         0x55b27ef800
    host <- 0x55b27ef800
halide_copy_to_device validating input buffer: buffer(368066887264, 0x5574bb3100, 0x55b27ef800, 1, uint8)
halide_copy_to_device 0x7fc9b64da8 host is dirty
Hexagon: halide_hexagon_device_malloc (user_context: 0x0, buf: 0x7fc9b64da8)
Hexagon: halide_hexagon_copy_to_device (user_context: 0x0, buf: 0x7fc9b64da8)
copy_memory: no copy needed as pointers are the same.
halide_copy_to_device validating input buffer: buffer(368066887232, 0x5574bb3100, 0x55b27efd80, 1, int16, {0, 4, 1}, {0, 3, 4})
halide_copy_to_device 0x7fc9b64d70 host is dirty
Hexagon: halide_hexagon_device_malloc (user_context: 0x0, buf: 0x7fc9b64d70)
Hexagon: halide_hexagon_copy_to_device (user_context: 0x0, buf: 0x7fc9b64d70)
c.extent[0] = 4
c.extent[1] = 3
copy_memory: no copy needed as pointers are the same.
halide_copy_to_device validating input buffer: buffer(368066886912, 0x5574bb3100, 0x55b27efb80, 1, uint8, {0, 128, 1})
halide_copy_to_device 0x7fc9b64d18 host is dirty
Hexagon: halide_hexagon_device_malloc (user_context: 0x0, buf: 0x7fc9b64d18)
Hexagon: halide_hexagon_copy_to_device (user_context: 0x0, buf: 0x7fc9b64d18)
c.extent[0] = 128
copy_memory: no copy needed as pointers are the same.
halide_copy_to_device validating input buffer: buffer(0, 0x0, 0x7f9d277080, 1, uint16, {0, 2592, 1}, {0, 1968, 2592})
halide_device_malloc validating input buffer: buffer(0, 0x0, 0x7f9d277080, 1, uint16, {0, 2592, 1}, {0, 1968, 2592})
halide_device_malloc: target device interface 0x5574bb3100
Hexagon: halide_hexagon_device_malloc (user_context: 0x0, buf: 0x7fc9b65220)
    allocating buffer of 10202240 bytes
    host_malloc len=10202240 ->         0x7f9aaa9000
halide_copy_to_device 0x7fc9b65220 host is dirty
Hexagon: halide_hexagon_device_malloc (user_context: 0x0, buf: 0x7fc9b65220)
Hexagon: halide_hexagon_copy_to_device (user_context: 0x0, buf: 0x7fc9b65220)
c.extent[0] = 2592
c.extent[1] = 1968
halide_copy_to_device validating input buffer: buffer(0, 0x0, 0x7f9c466080, 0, uint8, {0, 2560, 1}, {0, 1920, 2560}, {0, 3, 4915200})
halide_device_malloc validating input buffer: buffer(0, 0x0, 0x7f9c466080, 0, uint8, {0, 2560, 1}, {0, 1920, 2560}, {0, 3, 4915200})
halide_device_malloc: target device interface 0x5574bb3100
Hexagon: halide_hexagon_device_malloc (user_context: 0x0, buf: 0x7fc9b65198)
    allocating buffer of 14745728 bytes
    host_malloc len=14745728 ->         0x7f99c98000
Hexagon: halide_hexagon_run (user_context: 0x0, state_ptr: 0x55b27efb50 (620802496), name: offload_rpc.processed.s0.__outermost_argv, function: 0x5574bb33e0 (0))
    halide_hexagon_remote_get_symbol offload_rpc.processed.s0.__outermost_argv ->         140075808
0, 368066886912
1, 368066887232
2, 368066887360
5, 368066887264
3, 368066887456
    halide_hexagon_remote_run -> 
hangs forever...

**Comment by dsharletg** [comment]
Can you try adding calls like this: https://github.com/halide/Halide/blob/master/apps/hexagon_benchmarks/process.cpp#L55-L60 (and the corresponding cleanup calls after the benchmark loop)?

I don't think this should fix the hanging issue, but you'll need this anyways to benchmark correctly (to avoid the overhead of turning HVX on and off each iteration of benchmarking), and it might help narrow down what is going on (if it still hangs in the pipeline, that would indicate there is a problem with the generated code).

I did just check this on the simulator, and it seemed to run OK, so I think it is unlikely that the generated code has a problem, I think the issue is more likely something going on in the runtime.

**Comment by cjluo-nuro** [comment]
> I don't think this should fix the hanging issue, but you'll need this anyways to benchmark correctly (to avoid the overhead of turning HVX on and off each iteration of benchmarking), and it might help narrow down what is going on (if it still hangs in the pipeline, that would indicate there is a problem with the generated code).

Thanks Dillon. I updated the skel version to be v62 and it fixes the issue.
