### ISSUE TITLE
CMake static-library build is broken on Linux

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4581]
On Linux, configure a build with HALIDE_SHARED_LIBRARY=OFF, then "make all -k". You'll fail a fair number of targets with "cannot find -lxml2"

**Comment by steven-johnson** [comment]
tagging @shoaibkamil as it may be related to the Makefile LLVM issue you are investigating (ie, I think the xml2 dep is coming in from LLVM but the CMake build doesn't try to detect the necessary system libs in the way that Make does)

**Comment by steven-johnson** [comment]
(Doesn't seem to replicate on OSX for me. Haven't tried WIndows or Mingw)

**Comment by shoaibkamil** [comment]
Hmm, with HALIDE_SHARED_LIBRARY=ON, do we get a static library?  Sorry, I'm confused given the title.

**Comment by steven-johnson** [comment]
> Hmm, with HALIDE_SHARED_LIBRARY=ON, do we get a static library? Sorry, I'm confused given the title.

Sorry, typo in my description, fixed now

**Comment by shoaibkamil** [comment]
Got it.  This definitely looks related, I'll take a look after #4576 is merged.

**Comment by alexreinking** [comment]
On `cmake-modern`, the command to build static libs is:
```
cmake -G Ninja -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release ../Halide
```
You can omit `-G Ninja` if you don't have `ninja-build` installed.

**Comment by alexreinking** [comment]
I ran a static build on Linux with `cmake-modern` and didn't encounter this issue. However, did run into problems with the autoschedulers that I need to iron out.
