### ISSUE TITLE
CMake shared-library build is intermittently broken on Linux?

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4584]
On Linux, configure a build with HALIDE_SHARED_LIBRARY=ON, then "make all -j$BIGNUM"; I very occasionally will fail with dependencies on libautoschedule.so not being built. Perhaps there is a missing dependency and it just usually happens to build in the proper order?

**Comment by alexreinking** [comment]
I haven't seen this happen again since `cmake-modern` merged.
