### ISSUE TITLE
How to set boundaries from going out of bound when "split & vectorize" are used

### ISSUE THREAD

**Issue by jsksra1** [halide/Halide#4617]
I used following scheduling:
```
	Halide::Var x_o("xOut"), x_i("xIn"), y_o, y_i;
	Add.split(x, x_o, x_i, 8);
        Add.vectorize(x_i);
```
And when ever my input is less than 8, then I am getting the following error:
`Error: Output buffer f2 is accessed at -3, which is before the min (0) in dimension 0`

How can we use "Halide::clamp" / "Halide::BoundaryConditions::constant_exterior" for the output function (in my case 'Add')? Or is there any way to overcome this?

**Comment by ashishUthama** [comment]
Have a look at https://github.com/halide/Halide/issues/3107.

You have a few options, either use specialize (shown in comments in the link above) to enable vectorization only beyond a certain size. Or like you noted, use one of the boundary conditions - there are examples in the apps/ folder. You essentially wrap your input, see pad function in [this example](https://github.com/halide/Halide/blob/master/apps/resnet_50/Resnet50Generator.cpp) - though, I think this also means your output might be larger than you would expect. So if you want to write general code which can handle various lengths, I would recommend using specialize.

**Comment by jsksra1** [comment]
Thanks!  It worked.

Specialize fits better in my usecase.
