### ISSUE TITLE
An error in llvm/Object/SymbolicFile.h : expected ')' before 'PRIxPTR'

### ISSUE THREAD

**Issue by YutRetr0** [halide/Halide#4636]
sys : WIN10 
cmake
mingw-64

when I build the halide(cmake -G "MinGW Makefiles" -DLLVM_DIR=..\..\llvm\llvm-install\lib\cmake\llvm\ -DCMAKE_BUILD_TYPE=Release  .. then mingw32-make), the error happend. Have someone built hailde in windows with mingw? HELP-_-

[ 35%] Building CXX object src/CMakeFiles/Halide.dir/BoundsInference.cpp.obj
[ 35%] Building CXX object src/CMakeFiles/Halide.dir/BoundSmallAllocations.cpp.obj
[ 35%] Building CXX object src/CMakeFiles/Halide.dir/Buffer.cpp.obj
[ 35%] Building CXX object src/CMakeFiles/Halide.dir/CanonicalizeGPUVars.cpp.obj
[ 35%] Building CXX object src/CMakeFiles/Halide.dir/Closure.cpp.obj
[ 35%] Building CXX object src/CMakeFiles/Halide.dir/CodeGen_ARM.cpp.obj
In file included from D:/projects/build_tools/llvm/llvm-install/include/llvm/Object/ObjectFile.h:24,
                 from D:/projects/build_tools/llvm/llvm-install/include/llvm/DebugInfo/DIContext.h:18,
                 from D:/projects/build_tools/llvm/llvm-install/include/llvm/ExecutionEngine/RuntimeDyld.h:18,
                 from D:/projects/build_tools/llvm/llvm-install/include/llvm/ExecutionEngine/JITEventListener.h:19,
                 from D:\projects\build_tools\Halide\src\LLVM_Headers.h:28,
                 from D:\projects\build_tools\Halide\src\CodeGen_ARM.cpp:11:
D:/projects/build_tools/llvm/llvm-install/include/llvm/Object/SymbolicFile.h: In function 'OStream& llvm::object::operator<<(OStream&, const llvm::object::DataRefImpl&)':
D:/projects/build_tools/llvm/llvm-install/include/llvm/Object/SymbolicFile.h:48:30: error: expected ')' before 'PRIxPTR'
   OS << "(" << format("0x%08" PRIxPTR, D.p) << " (" << format("0x%08x", D.d.a)
                      ~       ^~~~~~~~
                              )
mingw32-make.exe[2]: *** [src\CMakeFiles\Halide.dir\build.make:5577: src/CMakeFiles/Halide.dir/CodeGen_ARM.cpp.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:305: src/CMakeFiles/Halide.dir/all] Error 2
mingw32-make.exe: *** [Makefile:162: all] Error 2

**Comment by steven-johnson** [comment]
Sorry, but we no longer actively support building in MinGW. Maybe someone else can still help.

**Comment by YutRetr0** [comment]
Ok，I got it. So I have to build it with msvc. XD
