### ISSUE TITLE
Incorrect comment in rfactor

### ISSUE THREAD

**Issue by UncleHandsome** [halide/Halide#4637]
Hello
In the end of rfactor's comment:
`
for rxo = 0 to 11:
    f(x, y) = max(f(x, y), f_intm(x, y, u))
`
It seems it should be f_intm(x, y, **rxo**) instead of f_intm(x, y, **u**)

**Comment by BachiLi** [comment]
Should be fixed by #4715. Note that Halide devs are open for pull requests.
