### ISSUE TITLE
undefined reference to `Halide::Internal::Introspection::

### ISSUE THREAD

**Issue by YutRetr0** [halide/Halide#4645]
I'm trying to build sample project x, no idea of this error.
release package: arm64-linux
sys: win10
toolchains: android-ndk-r20/winx86_64/ndk-clang++

D:\projects\x\build\cmake_output/../../dep/halide/include/Halide.h:2557: undefined reference to `Halide::Internal::Introspection::get_source_location()'
D:\projects\x\build\cmake_output/../../dep/halide/include/Halide.h:2558: undefined reference to `Halide::Internal::Introspection::get_variable_name(void const*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
CMakeFiles/vpmfd.dir/D_/projects/x/core_lib/src/vpmfd_core_lib.cpp.o: In function `TestCompilationUnit':
D:\projects\x\build\cmake_output/../../dep/halide/include/Halide.h:2618: undefined reference to `Halide::Internal::Introspection::test_compilation_unit(bool (*)(bool (*)(void const*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)), bool (*)(void const*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&), void (*)())'

**Comment by alexreinking** [comment]
I'm not sure how our ELF introspection helper works, but I'm marking this down as a potential CMake / build issue.

**Comment by abadams** [comment]
It's just one of the functions in libHalide. This is usually the first missing reference if you #include Halide.h but don't link to libHalide. It could be that you included Halide.h instead of HalideRuntime.h in code that uses AOT-compiled Halide?

**Comment by abadams** [comment]
I should add that this symbol is one that gets referred when you include Halide.h and don't actually use anything from the header, because it's used in a static constructor. So it's often the one that shows up as an undefined reference.

**Comment by abadams** [comment]
Assuming this was resolved.
