### ISSUE TITLE
auto_schedule_unbounded_nonpure is broken

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4678]
At current top of tree, this fails with `Error: The pure definition  of Function g calls function sum in an unbounded way in dimension 0`.

**Comment by steven-johnson** [comment]
strangely, https://github.com/halide/Halide/commit/c924ea43efd317b933f6428dc53cf55142bb5324 (from https://github.com/halide/Halide/pull/4566) seems to be the injection point. Assigning to @vksnk for investigation.

**Comment by steven-johnson** [comment]
OK, a different commit from that same PR is being fingered now:

```
b5c8d8f52adb9a32dd79200654700990d4bafb6d is the first bad commit
commit b5c8d8f52adb9a32dd79200654700990d4bafb6d
Author: Volodymyr Kysenko <vksnk@google.com>
Date:   Thu Feb 6 11:21:03 2020 -0800

    Include more lowering stages in PrintLoopNest

 src/PrintLoopNest.cpp | 33 +++++++++++++++++++++++----------
 1 file changed, 23 insertions(+), 10 deletions(-)
```

reassigning to vksnk@

**Comment by vksnk** [comment]
Thanks. It does call print_loop_nest, I'll investigate.

**Comment by vksnk** [comment]
It fails during bounds inference and also fails in the same way if you do `compile_jit . Is it expected for this test?  I would guess no, but the test name has "unbounded" in it, which is exactly the error:

`The pure definition  of Function g calls function sum in an unbounded way in dimension 0`

so maybe it's intentional?

**Comment by abadams** [comment]
Did print_loop_nest run bounds inference before your change?

**Comment by abadams** [comment]
I'm wondering what the test is supposed to be verifying. I guess it was just a case that was expected to fail, but written in a way where it didn't?

I'd be inclined to just delete the test.

**Comment by vksnk** [comment]
No, it didn't run bounds inference before. It started to fail after I added bounds inference and some couple other passes into print_loop_nest.

**Comment by steven-johnson** [comment]
> I'd be inclined to just delete the test.

Aside from this outright failure, several of the `auto_schedule_xxx` tests are flaky. At some point we should decide whether this autoscheduler is still paying for itself.

**Comment by vksnk** [comment]
Test fails even with the default schedule (when autoscheduler is skipped) and in general, programs seems to be invalid.

Maybe, the intention was to check that autoscheduler doesn't fail in some specific bad way for this case and then manually inspect generated schedule for overall sanity? In any case, in the current form the test doesn't seem to test much,  so we either need to figure out what it's supposed to do and fix it or just delete it. I am also in favor deleting it. I'll wait a bit and if there are no objections, I'll delete it.

**Comment by steven-johnson** [comment]
I vote for deleting now to unbreak things. We can always undelete later if needed.

**Comment by abadams** [comment]
I also vote for deleting it. I suspect the test was written just as code to investigate what happens in this case and how to fix it, but it's not really a fixable thing.

**Comment by vksnk** [comment]
Good point, will do right now.
