### ISSUE TITLE
arm32 breakage in LLVM10

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4690]
correctness_simd_op_check is failing for arm32 builds under the LLVM10 branch ~(but not LLVM9 or trunk)~ and also LLVM11 (aka trunk); specifically, we segfault once trying to test the `vqadd.*` instructions.

The injection point is:

```
commit 9f15fcc2718f95f1dac9e6e57aa93d84e9709930
Author: David Green <david.green@arm.com>
Date:   Wed Nov 27 11:01:27 2019 +0000

    [ARM] Replace arm_neon_vqadds with sadd_sat

    This replaces the A32 NEON vqadds, vqaddu, vqsubs and vqsubu intrinsics
    with the target independent sadd_sat, uadd_sat, ssub_sat and usub_sat.
    This helps generate vqadds from standard IR nodes, which might be
    produced from the vectoriser. The old variants are removed in the
    process.

    Differential Revision: https://reviews.llvm.org/D69350
```

**Comment by steven-johnson** [comment]
(Yes, this was back in November 2019. Clearly our armbots weren't testing trunk properly.)

**Comment by steven-johnson** [comment]
cc @alinas

**Comment by dsharletg** [comment]
Meta question here: should we stop supporting arm32? Every ARM target I'm aware of is now 64-bit. We saw significant performance advantages of arm64 over arm32, so the only reason to continue supporting it is if there are users on 32-bit only systems.
