### ISSUE TITLE
Makefile is not setting SONAME for libHalide.so

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4738]
On Linux, our Makefile produces libHalide.so without SONAME set (CMake does this for us under the hood by default). We should be consistent between the two and either set (or not) in both places.

**Comment by alexreinking** [comment]
Since we're switching to SemVer, we should _definitely_ have SONAME set.

**Comment by alexreinking** [comment]
CMake in our latest releases sets the SONAME and creates the appropriate namelinks. I'm closing this since we aren't using the Makefile for packaging anymore and that's where this issue matters.
