### ISSUE TITLE
Can we cross-compile halide code without depending on "libdl.so"?

### ISSUE THREAD

**Issue by antonysigma** [halide/Halide#4791]
I am developing image processing code in a highly constrained ARM environment, in which linking to `libdl.so` is forbidden. From my understanding, the so called AOT generator requires the following build process (in pseudocode) to link to the `main.cpp` code to be able to run my algorithm written in `my_algorithm_generator.cpp`.
```Make
main:main.o my_algorithm.a -ldl

my_algorithm.a:my_aot_generator
    ./$< -g my_algorithm -e static_library,h -o . target=arm-64-linux parallel=false

my_aot_generator:CXXFLAGS+=-fno-rtti
my_aot_generator:my_algorithm_generator.o GenGen.o -lHalide
```

The problem is that my ARM environment does not allow dynamic linking to a shared library `libdl.so`. To make things worse, it does not allow operations like `dlopen` or `dlsym@glibc` at all in the ELF binary file. However, the toolchain does provide its own static `libc.a` library which provide symbols for static linking, such as `malloc`, `atan2f`.

I need a way to cross-compile the halide code without depending on `libdl.so`. How do I achieve that?

**Comment by abadams** [comment]
dlopen/dlsym in generated code is just used to load GPU/DSP APIs. If you can't even dlopen, I assume you're not using those. I think the simplest solution is to define your own implementations of the libdl symbols we use along the lines of the below, and link that into your final binary instead of libdl:

```
extern "C" {
void *dlopen(const char *, int) {return nullptr;}
void *dlsym(void *, const char *) {return nullptr;}
char *dlerror() {return "This is a fake version of libdl";}
}
```

You could also probably use objcopy + strip to remove all the symbols that transitively reference things from libdl, or use linker flags to define the libdl symbols as null.

**Comment by antonysigma** [comment]
Thank you @abadams . Linking against the dummy functions seem to work on x86 architecture. The compile executable does run without error. I am going to test it on my ARM environment to verify this again. 

Re: stripping symbols with `objcopy` and/or `strip`: I thought this is not possible as the symbols (`dlsym`, `dlpen`, etc) are undefined?

**Comment by abadams** [comment]
The symbols you would strip would be the ones that use those symbols, and the ones that use those transitively. I.e everything in this file: https://github.com/halide/Halide/blob/master/src/runtime/posix_get_symbol.cpp

I think that would remove the uses of the dlsym/dlopen.

**Comment by antonysigma** [comment]
Re: testing dummy `dlsym` functions: It turns out that my ARM execution environment is more constrained then I thought. Following your suggestions, I defined my own dummy functions `dlsym`, `dlopen` and `dlerror` etc. And since my environment is single-threaded, I took further action by not coding any `parallel` schedules in the Halide code. I was able to build the static library as a result. However, the linker then refused to link my static libraries to my executable, as shown in the error message below.

@abadams I need to rethink my approach to using Halide language in my environment, which is an SoC with single-threaded ARM with a Hexagon DSP. I suspect that using Halide just to utilize ARM NEON will only provide a marginal productivity gain in my project, compared to coding in Eigen or Armadillo. As to how to enable the DSP through Halide, I am not sure how to do that without calling `dlsym` or `dlopen`. I will open a new ticket regarding this question.

Either way, I was able to avoid the missing `dlsym` symbol error with your solution. Thank you very much for your help!

```
# Compiling main.o from main.cpp, using Halide::Runtime:Buffer wrapper class from HalideBuffer.h
atomic:553:2: error: <atomic> is not
      supported on this single threaded system
#error <atomic> is not supported on this single threaded system

# Compiling main.o from main.cpp, manually filling halide_buffer_t structs from HalideRuntime.h
Compile main.o success

# Linking main from main.o my_algorithm.a
my_algorithm.a (halide_runtime.o): In function `halide_spawn_thread':
posix_allocator.cpp:(.text.halide_spawn_thread+0x3d): undefined reference to `pthread_create'
my_algorithm.a(halide_runtime.o): In function `halide_join_thread':
posix_allocator.cpp:(.text.halide_join_thread+0x1a): undefined reference to `pthread_join'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
... ( 10+ more errors about missing pthread_* symbols)
```

**Comment by steven-johnson** [comment]
...I am truly mind-boggled at the idea that a C/C++ environment would provide a version of `<atomic>` that *fails to compile*.

It might be possible to add (say) `#ifndef HALIDE_NO_ATOMICS` around these inclusions (and uses), but it would probably end up being pretty invasive.

**Comment by antonysigma** [comment]
Again thank you for your solution of using a dummy dlsym for linking the static library. I am also puzzled at why they would design the C++17 toolchain that meets the language standard but not the standard libraries. I will ask further questions in #4819.

**Comment by pranavb-ca** [comment]
@antonysigma  - have you considered using Hexagon in standalone mode? In this mode, we pretend that the Hexagon DSP is the host and there is no other device. Your pipeline starts on Hexagon and ends there. The communication from the ARM to the DSP is done over fastRPC.
