### ISSUE TITLE
lesson 12 cannot detect GPU

### ISSUE THREAD

**Issue by XIAOYixuan** [halide/Halide#4818]
Hi all, 
```
Running pipeline on CPU:
Running pipeline on GPU:
Requested GPU(s) are not supported. (Do you have the proper hardware and/or driver installed?)
No GPU target available on the host
Testing performance on CPU:
0.4097 milliseconds
```

I got this when I run [lesson_12_using_the_gpu](https://github.com/halide/Halide/blob/005eedbc51704a184fd88b2d7e65307e149fa043/tutorial/lesson_12_using_the_gpu.cpp). 

I have tesla v100 with cuda 10.1 installed running on centos 6.3,  Halide is downloaded yesterday and compiled with llvm8.0/gcc 8.2. Googled the issue but still don't have a clue why lesson_12 failed to detect the GPU. Any response is appreciated

---

Update: after setting HL_DEBUG_CODEGEN=2, the logs say:
```
...
Adjusting refcount for module GPU by 1
host_supports_device_api: saw error (CUDA API not found: cuInit
 )
host_supports_device_api: saw error (CUDA API not found: cuDeviceGetCount
 10621 )
host_supports_device_api: saw error (CUDA API not found: cuDeviceGet
... // and more
```
looks like it failed at [DeviceInterface.cpp:50](https://github.com/halide/Halide/blob/3da506980c7ca2bee38710e0ce325398b6b4150b/src/DeviceInterface.cpp#L50)

---

Update again:
Resolved. Looks like something wrong with my gcc8, the dlopen() function failed to load libcuda. After re-compile everything with gcc5, now Halide successfully detect GPU.

**Comment by vksnk** [comment]
Do you have OpenCL installed in your system? It seems like on on Linux, the tutorial is trying only OpenCL target, so if you don't have it then that might be a problem. You can probably also try to uncomment Cuda feature flag (https://github.com/halide/Halide/blob/master/tutorial/lesson_12_using_the_gpu.cpp#L306)

**Comment by XIAOYixuan** [comment]
> Do you have OpenCL installed in your system? It seems like on on Linux, the tutorial is trying only OpenCL target, so if you don't have it then that might be a problem. You can probably also try to uncomment Cuda feature flag (https://github.com/halide/Halide/blob/master/tutorial/lesson_12_using_the_gpu.cpp#L306)

no,  I noticed that so I uncomment line 307
