### ISSUE TITLE
How to modify Halide to generate AOT target=arm-64-linux-single_threaded?

### ISSUE THREAD

**Issue by antonysigma** [halide/Halide#4819]
...I am truly mind-boggled at the idea that a C/C++ environment would provide a version of `<atomic>` that *fails to compile*.

It might be possible to add (say) `#ifndef HALIDE_NO_ATOMICS` around these inclusions (and uses), but it would probably end up being pretty invasive.

_Originally posted by @steven-johnson in https://github.com/halide/Halide/issues/4791#issuecomment-606138599_

Form #4791, it turns out that Halide language does not output a single-threaded static library with runtime. If I were to fork and edit the Halide project to support this feature, how extensive/invasive should I modify the source code? Where in the source tree should I start?

In particular, I am hoping to be able to build a static library through the following pseudo-code, by adding the `single_thread` tag to the AOT generator:
```make
TARGET = arm-64-linux-single_thread

# No dynamic loading allowed
main:main.o my_algorithm.a libc.a $(OTHER_STDCPP_STATIC_LIBRARIES)

my_algorithm.a:my_aot_generator
    ./$< -g my_algorithm -e static_library,h -o . target=$(TARGET)

my_aot_generator:CXXFLAGS+=-fno-rtti
my_aot_generator:my_algorithm_generator.o GenGen.o -lHalide
```

Here are the abridged description of the target execution environment:

My cross-compiler target is a bare metal ARM A53_64 single-threaded SoC with Hexagon DSP running a stripped down Linux kernel. The cross compiler can support C++17 syntax standard, but all threading related standard library (e.g. std::atomic, std::thread, std::mutex) are disabled at compile time. The compiled executable (for example, `main`) must be standalone. In other words, dynamic linking (e.g. `-ldl -lpthread`), and dynamic library/symbol loading (e.g. `dlsym()`, `dlopen()`) are forbidden.

**Comment by abadams** [comment]
Take a look at LLVM_Runtime_Linker.cpp in the Halide source. That shows you how target flags map to what gets included in the runtime. You can strip most of the OS-specific stuff in the runtime using the target flag "noos" instead of "linux" You'll need to provide definitions of any missing symbols yourself (e.g. halide_print, halide_error, halide_malloc). That might be the easiest route to avoid having to fork.

**Comment by antonysigma** [comment]
Thank you for your prompt reply! I will look into the file `LLVM_Runtime_Linker.cpp` for a start.

By the way, a quick build test on `target=arm-64-noos` results in error `No arm support for this OS`. Is this normal? I am using the following Halide release:

https://github.com/halide/Halide/releases/download/release_2019_08_27/halide-linux-64-gcc53-800-65c26cba6a3eca2d08a0bccf113ca28746012cc3.tgz

**Comment by abadams** [comment]
Oh, looks like code elsewhere in that file doesn't know what llvm target triple to use in that case....

Yet another option is arm-64-linux-no_runtime, with you providing definitions for everything missing. You could even do this by copy-pasting code out of src/runtime as needed.

**Comment by antonysigma** [comment]
Finally! I can compile and link with the following pseudo-code and the dummy file `halide_errros_dummy.cpp`.

As I cannot use Halide::Runtime::Buffer<> in `main.cpp` for the missing `std::atomic`, could you guide me to manuals on how to construct the `halide_buffer_t` struct?
```make
TARGET = arm-64-linux-no_runtime

# No dynamic loading allowed
main:main.o my_algorithm.o halide_errors_dummy.o libc.a $(OTHER_STDCPP_STATIC_LIBRARIES)

# main.cpp includes HalideRuntime.h for the halide_buffer_t structs

my_algorithm.o:my_aot_generator
    ./$< -g my_algorithm -e o,h -o . target=$(TARGET)

my_aot_generator:CXXFLAGS+=-fno-rtti
my_aot_generator:my_algorithm_generator.o GenGen.o -lHalide
``` 

Curiously, my environment does support `fprintf()` as the error printer; I will implement my own printer then.

**Comment by abadams** [comment]
halide_buffer_t is a pretty simple little struct defined here:
https://github.com/halide/Halide/blob/master/src/runtime/HalideRuntime.h#L1393

There's some basic example usage here: https://github.com/halide/Halide/blob/master/apps/HelloAndroid/jni/hello_wrapper.cpp#L81

You give it the address of the start of your data, and then an array of halide_dimension_t structs, each of which is the min coordinate (usually zero), and extent of each dimension, and a "stride", which is how many elements you must walk in the underlying array to move forwards by one in the given dimension. The address_of method shows you how the memory indexing works: https://github.com/halide/Halide/blob/master/src/runtime/HalideRuntime.h#L1497

**Comment by antonysigma** [comment]
I was able to run the Halide pipeline following the correction definition of `halide_dimension_t` struct. In addition, I implemented my own `halide_errors.h` to resolve the missing `halide_error_*` symbols. Thank you very much!

```c++
#include <cstdint>

// Backporting std::format from C++20 to C++17
#include "fmt/format.h"

#include "HalideRuntime.h"
#define WEAK __attribute__((weak))

// Low level logging API in C
extern "C" {
#include "their_log.h"
} // extern "C"


// the low level logging function did not support '%' syntax very well, so use fmt::format_to() instead.
template<class... Args>
void
LOGE (std::string_view fmt, const Args&... args)
{
  fmt::memory_buffer message;
  fmt::format_to (message, fmt, args...);
  their_log (LOG_MSG_ERROR, message.data());
}

static std::string_view
halide_type_to_string (const halide_type_t& t)
{
  switch (t.code)
    {
    case halide_type_int:
      return "int";

    case halide_type_uint:
      return "uint";

    case halide_type_float:
      return "float";

    case halide_type_handle:
      return "handle";

    default:
      return "bad_type_code";
    }
}

extern "C" {
...
  WEAK int halide_error_bad_type (void *user_context, const char *func_name,
                                  uint32_t type_given_bits, uint32_t correct_type_bits)
  {
    halide_type_t correct_type, type_given;
    memcpy (&correct_type, &correct_type_bits, sizeof (uint32_t));
    memcpy (&type_given, &type_given_bits, sizeof (uint32_t));

    LOGE ("{} has type {}{} but type of the buffer passed in is {}{}",
          func_name,
          //reinterpret_cast<halide_type_t>(correct_type),
          //reinterpret_cast<halide_type_t>(type_given)
          halide_type_to_string (correct_type),
          correct_type.bits,
          halide_type_to_string (type_given),
          type_given.bits
         );
    return halide_error_code_bad_type;
  }
...
```
