### ISSUE TITLE
Python bindings leak memory in AOT mode

### ISSUE THREAD

**Issue by Infinoid** [halide/Halide#4859]
The generated "python_extension" code leaks buffers.  The function `_convert_py_buffer_to_halide` accesses a buffer's memory by calling `PyObject_GetBuffer`.  At that point it holds a reference to the input buffer, and that reference is never released.

https://docs.python.org/3/c-api/buffer.html#c.PyObject_GetBuffer says:

> Successful calls to PyObject_GetBuffer() must be paired with calls to PyBuffer_Release(), similar to malloc() and free(). Thus, after the consumer is done with the buffer, PyBuffer_Release() must be called exactly once.

The generated code never calls PyBuffer_Release.

**Comment by Infinoid** [comment]
Here is a reproducer: https://gist.github.com/Infinoid/a90efd3b8b10c0859009f780b6033ac0

This reproducer calls an AOT-generated function 3000 times, with a newly allocated input buffer for each call.  The input buffers are allocated on line 30, and leaked on line 32.

It prints a progress bar as it works.  Once every 1000 calls, it prints how much memory it is using. 
 The output looks like this:

```
$ python3 leak.py 
clang-9 $(python3-config --cflags) -g -ggdb -shared -fPIC -Wno-unused-command-line-argument -o hlcopy$(python3-config --extension-suffix) hlcopy.py.cpp hlcopy.o $(python3-config --ldflags)
leaking memory:   0%|                                | 0/3001 [00:00<?, ?calls/s]
rss (bytes): 109780992
leaking memory:  32%|██████▊              | 973/3001 [00:02<00:05, 398.51calls/s]
rss (bytes): 3059380224
leaking memory:  65%|█████████████       | 1959/3001 [00:04<00:02, 441.93calls/s]
rss (bytes): 6008684544
leaking memory: 100%|███████████████████▉| 2995/3001 [00:07<00:00, 439.51calls/s]
rss (bytes): 8958259200
leaking memory: 100%|████████████████████| 3001/3001 [00:07<00:00, 426.85calls/s]
```

Every call adds about 3 gigs of memory usage.

**Comment by abadams** [comment]
IIRC this was @mgharbi 's code. I'll tag him.

**Comment by mgharbi** [comment]
Hum, @abadams this does not seem related to the PyTorch bindings. I am not very familiar with the pure Python bindings.

**Comment by Infinoid** [comment]
Same test script, with the #4861 patch applied:

```
$ python3 leak.py 
clang-9 $(python3-config --cflags) -g -ggdb -shared -fPIC -Wno-unused-command-line-argument -o hlcopy$(python3-config --extension-suffix) hlcopy.py.cpp hlcopy.o $(python3-config --ldflags)
leaking memory:   0%|                                  | 0/3001 [00:00<?, ?calls/s]
rss (bytes): 110231552
leaking memory:  32%|███████▎               | 955/3001 [00:01<00:03, 592.77calls/s]
rss (bytes): 110231552
leaking memory:  66%|██████████████▍       | 1975/3001 [00:03<00:01, 595.48calls/s]
rss (bytes): 110379008
leaking memory: 100%|█████████████████████▉| 2997/3001 [00:05<00:00, 598.76calls/s]
rss (bytes): 110383104
leaking memory: 100%|██████████████████████| 3001/3001 [00:05<00:00, 592.35calls/s]
```

...which looks fixed to me.

**Comment by steven-johnson** [comment]
I think that PythonExtensionGen was @matthiaskramm

**Comment by Infinoid** [comment]
I just re-tested, and master branch no longer leaks memory.  Closing issue.
