### ISSUE TITLE
OpenGL tests all fail on macOS

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#4885]
While the OpenGL tests build on macOS, they do not run. They all crash with

```
Error: (at /Users/halidenightly/build_bot_new/worker/mac-64-1000/halide/test/opengl/varying.cpp:62)
The pipeline returned exit status -1 but halide_error was never called.
```

With the line of the error suitably replaced for the test.

**Comment by abadams** [comment]
I think we need to fix openglcompute and get it widely tested and just delete the opengl backend. The current opengl tests should be cherry-picked into openglcompute tests where appropriate.

**Comment by alexreinking** [comment]
That would be good, but can we not let it block #4644?

**Comment by abadams** [comment]
Sure, but why would it? That PR doesn't turn on testing for opengl, does it?

**Comment by alexreinking** [comment]
Sorry, see halide/build_bot#60
