### ISSUE TITLE
max(a,b) - min(a,b) should generate absolute difference op on ARM

### ISSUE THREAD

**Issue by mmp** [halide/Halide#489]
See the test case below; I'm taking the absolute difference of unsigned two 8-bit values and storing it in a 16-bit value; this maps nicely to PSADBW on x86.

If I use either the ARM-idiomatic `select(a>b, a-b, b-a)`, I get instructions for the compare both subs, and then a bunch of logical ops to select between the two. Similarly if I try `max(a,b) - min(a, b)`.  The best code I get is from `abs(s16(a)-s16(b))`, but that still does a subtract and an abs.  (And is not great code on ARM).

Anyway, providing this would be great.

More generally, making a pass through the various x86 vector intrinsics would probable be worthwhile.  For example, in my max()/min() test, I note that it's doing actual compares rather than emitting PMAXUB/PMINUB, etc., so there may be other things to tune up on this front...

```
#include <Halide.h>
using namespace Halide;
#include <vector>

Expr u8(Expr v) {
  return cast<uint8_t>(v);
}

Expr u16(Expr v) {
  return cast<uint16_t>(v);
}

Expr s16(Expr v) {
  return cast<int16_t>(v);
}

Expr u32(Expr v) {
  return cast<uint32_t>(v);
}

Expr Select3(Expr x, Expr a, Expr b, Expr c) {
  return select(x == 0, a, select(x == 1, b, c));
}

int main(int argc, char **argv) {
  ImageParam in_(UInt(8), 1, "input");

  Var x;
  Func result;
  result(x) =
      u16(select(in_(x) > in_(x+8), in_(x) - in_(x+8), in_(x+8) - in_(x)));
//CO      u16(max(in_(x), in_(x+8)) - min(in_(x), in_(x+8)));
//CO      abs(s16(in_(x)) - s16(in_(x+8)));

  result.bound(x, 0, 16);
  result.vectorize(x, 8);

  Argument args[] = { in_ };
  std::vector<Argument> vargs(&args[0], args + sizeof(args)/sizeof(args[0]));
  result.compile_to_assembly("result.s", vargs);
  result.compile_to_lowered_stmt("result.stmt");

  return 0;
}
```

**Comment by dsharletg** [comment]
I think we now intend for absd to cover this use case.
