### ISSUE TITLE
Deprecate Visual Studio 2015

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#4890]
@steven-johnson and I were contemplating dropping support for Visual Studio 2015.

LLVM 10 has dropped VS 2015 support, so we're going to be forced to do so soon, anyway.

Does anyone still need to build Halide with VS 2015?

**Comment by steven-johnson** [comment]
We could argue support is dropped already, as we haven't tested on it for ~1 year.

**Comment by shoaibkamil** [comment]
Our use is VS2017+, so dropping 2015 should be ok for us.
