### ISSUE TITLE
Unable to run autoscheduler program in Windows using Visual Studio

### ISSUE THREAD

**Issue by anjugopinath** [halide/Halide#4893]
The following program 
[https://halide-lang.org/tutorials/tutorial_lesson_21_auto_scheduler_generate.html](url)

is compiled on Linux with the following command:
g++ lesson_21_auto_scheduler_generate.cpp ../tools/GenGen.cpp -g -std=c++11 -fno-rtti -I ../include -L ../bin -lHalide -lpthread -ldl -o lesson_21_generate

No instructions are given to compile it in Windows.

**Comment by alexreinking** [comment]
You should use CMake with Halide on Windows, for which more robust support is forthcoming. See #4644 

MinGW was deprecated in #4601 . See also #4593

**Comment by alexreinking** [comment]
I'm adding "Add CMake tutorial" to the TODOs in #4644

**Comment by abadams** [comment]
The tutorials intentionally do not use a build system. The intent is to minimize the number of layers of abstraction to begin with and force people to understand the raw compiler invocations. This is especially important for the generator tutorial because it uses staged compilation. Unfortunately this is all at odds with how people build things on Windows.

So I guess we need a later tutorial that's a Hello World for Halide in Visual Studio. Or maybe it could be an explanatory comment in a Halide CMake tutorial? I'm not sure what else you need to do in visual studio once you have a minimal cmake project.

**Comment by alexreinking** [comment]
> So I guess we need a later tutorial that's a Hello World for Halide in Visual Studio. Or maybe it could be an explanatory comment in a Halide CMake tutorial? I'm not sure what else you need to do in visual studio once you have a minimal cmake project.

This is the plan. VS2017+ has native support for CMake projects, so a tutorial that introduces how to build Halide with CMake suffices for all platforms.

**Comment by anjugopinath** [comment]
Can I use Cmake with the Halide binaries for Windows?
I have downloaded the binaries for Windows [halide-win-32-distro-800-65c26cba6a3eca2d08a0bccf113ca28746012cc3.zip](url) from this link [https://github.com/halide/Halide/releases](url).

**Comment by alexreinking** [comment]
You _can_ and should use CMake, but note that the support will not be as robust as in #4644 

See README_cmake.md for details on how to use it.

**Comment by anjugopinath** [comment]
1) In the README_cmake.md file, it is mentioned that a ".a" file will be generated. I need a ".lib" file for Windows. Is there a workaround.
2) Also, one of the commands is set(HALIDE_DISTRIB_DIR "/path/to/halide/distrib").
There is no "/path/to/halide/distrib" path in Windows. What is the corresponding path for Windows environment?

**Comment by alexreinking** [comment]
It should generate a .lib regardless. I'm guessing it says ".a" simply because that's the convention on Linux.

**Comment by anjugopinath** [comment]
Inside the root directory of halide binaries for windows, I have created a folder called autoschedule.
Inside this folder ,
1) I have added files lesson_21_auto_scheduler_generate.cpp and lesson_21_auto_scheduler_run.cpp.
2) I created a CMakeLists.txt file . The contents are:
-----------------------------------------------------
project(autoschedule)
cmake_minimum_required(VERSION 3.1.3)

set(HALIDE_DISTRIB_DIR "${CMAKE_CURRENT_LIST_DIR}/../../distrib")


include("${HALIDE_DISTRIB_DIR}/halide.cmake")


add_executable(autoschedule "${CMAKE_CURRENT_SOURCE_DIR}/lesson_21_auto_scheduler_run.cpp")
set_target_properties(autoschedule PROPERTIES CXX_STANDARD 11 CXX_STANDARD_REQUIRED YES CXX_EXTENSIONS NO)
target_include_directories(autoschedule PRIVATE "${HALIDE_INCLUDE_DIR}" "${HALIDE_TOOLS_DIR}")
halide_use_image_io(autoschedule)

file(GLOB GENS RELATIVE "${CMAKE_CURRENT_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/*_generator.cpp")
foreach(GEN_SRC ${GENS})
    string(REPLACE "_generator.cpp" "" GEN_NAME "${GEN_SRC}")
    halide_library("${GEN_NAME}" SRCS ${GEN_SRC})
    target_link_libraries(autoschedule PUBLIC "${GEN_NAME}")
endforeach()
-----------------------------------------------------
I am getting errors:
CMake Error at CMakeLists.txt:7 (include):
  include could not find load file:

    C:/Users/<username>/Downloads/halide-win-64-distro-800-65c26cba6a3eca2d08a0bccf113ca28746012cc3/halide/autoschedule/../../distrib/halide.cmake


CMake Error at CMakeLists.txt:13 (halide_use_image_io):
  Unknown CMake command "halide_use_image_io".


-- Configuring incomplete, errors occurred!
