### ISSUE TITLE
Unable to include multiple libraries generated by "compile_to_static_library" due to redefiniton errors in Windows

### ISSUE THREAD

**Issue by anjugopinath** [halide/Halide#4894]
I have written two programs in Halide using AOT feature. When I compile them with the command "compile_to_static_library", a .lib file and a .h file are generated for each of them. 
But , when I add both .lib files to the source code and build the solution, I get several redefiniton errors.

The solution in Linux is to append the flag -no_runtime while compiling them . The instructions for an equivalent flag/command in Windows is not mentioned.

**Comment by shoaibkamil** [comment]
The same should work for Windows: you can compile all the generators with a target that includes "-no_runtime", and then generate a standalone runtime with a generator (see tutorial #15).

Alternatively you can generate all but one of libraries with "-no_runtime" as part of the target, and then link them with the one library that didn't have "-no_runtime".

**Comment by anjugopinath** [comment]
May I know which version of g++ is required please? Installed mingw . g++ version is 4.5.2 . I tried compiling the file with the command "g++ -no_runtime 1.cpp". I got errors.

**Comment by shoaibkamil** [comment]
Sorry, I wasn't as clear as I could have been. "-no_runtime" is not a flag to g++, but rather it is part of the target.  When you call `compile_to_static_library()`, one of the parameters is the Halide target; that should be set to include "-no_runtime" (something like "host-runtime").

**Comment by alexreinking** [comment]
No version of GCC will work on Windows. MinGW support was dropped in #4601 see also #4593

**Comment by anjugopinath** [comment]
I was able to solve it by setting the target:
 Target target("no_runtime");
 output.compile_to_static_library("Func", { in}, "func1", target); // the expected target format is
//arch-bits-os-feature1-feature2.....
//if you omit arch-bits-os, it defaults to the host. So, I gave only the feature which is no_runtime

Thank You very much for the quick and correct response!
