### ISSUE TITLE
recompile with -fPIC on test_correctness_generator in CMake

### ISSUE THREAD

**Issue by bfloch** [halide/Halide#4895]
I am aware that there is a new CMake PR in progress via https://github.com/halide/Halide/pull/4644

For the time being I had similar errors like https://github.com/halide/Halide/issues/3747 with the suggestion to "recompile with -fPIC".

This happened during the build of Halide on a fresh Fedora 32. The errors appeared on the python bindings tests for `addconstant` and `user_context` in `python_bindings/correctness/CMakeLists.txt`

Adding the `POSITION_INDEPENDENT_CODE ON` property for the static libs within `halide.cmake` fixed it for me.

```
  set_target_properties("${BASENAME}_cc" PROPERTIES
    POSITION_INDEPENDENT_CODE ON
    EXCLUDE_FROM_ALL TRUE)
```

**Comment by alexreinking** [comment]
Ah, this is for the C backend. Thanks for pointing this out, I'll make sure to set these properties in my implementation, which just so happens to be my next TODO.
