### ISSUE TITLE
test_halide_blas fails with assert-check

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#4897]
Building the linear algebra app and running the tests now gives a single failure after #4874 was merged. I get the following output:

```
D:\Halide\cmake-build-release\apps\linear_algebra>.\tests\test_halide_blas.exe
Testing halide_blas with N = 768:
               Testing scopy: PASSED
               Testing sscal: PASSED
               Testing saxpy: PASSED
                Testing sdot: Error: Output buffer result is accessed at 0, which is beyond the max (-1) in dimension 0
```

----

64*7 = 448... what happened here? This is now crashing sdot on Windows for me. I get:
```
Testing sdot: Error: Output buffer result is accessed at 0, which is beyond the max (-1) in dimension 0
```

_Originally posted by @alexreinking in https://github.com/halide/Halide/pull/4874/review_comment/create_

**Comment by alexreinking** [comment]
Never mind. The CMake build wasn't passing `no_asserts` to the L1 blas generators like it needs to. Though I'm curious why this issue arises in the first place.

**Comment by steven-johnson** [comment]
All of these should pass without no_asserts -- that's just there for speed improvement, but shouldn't be used to mask actual errors. We need to fix it.

**Comment by alexreinking** [comment]
> All of these should pass without no_asserts -- that's just there for speed improvement, but shouldn't be used to mask actual errors. We need to fix it.

Okay, then I'm re-opening. Maybe @abadams can take a look?

**Comment by alexreinking** [comment]
All of sdot/ddot, sasum/dasum are affected.

**Comment by alexreinking** [comment]
Interestingly this only seems to happen with `test_halide_blas` and not `halide_benchmark`.
