### ISSUE TITLE
Allow contributors to delete mistakenly opened issues, like this one.

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#4903]
I thought I was typing in a different window and I **amazingly** entered just the wrong incantation to fully create a pointless issue.

Whoever has the ability to delete this issue entirely, should.

ETA: Laugh reacts only.

**Comment by abadams** [comment]
You're not the boss of me!

**Comment by steven-johnson** [comment]
(irrelevant me too comment about an entirely unrelated issue that is probably just a user config error that people will find on google when searching for the original issue)
