### ISSUE TITLE
cmake-modern branch does not always catch version mismatches between clang and llvm

### ISSUE THREAD

**Issue by Infinoid** [halide/Halide#4904]
I tried to build the current `cmake-modern` branch and it failed.  Here's what I did:
```
cmake -DCMAKE_BUILD_TYPE=Release ../git
make
```

And here's how it died:
```
[  3%] Generating initmod.allocation_cache_32_debug.ll
[  3%] Generating initmod.allocation_cache_32_debug.bc
/usr/lib/llvm-10/bin/llvm-as: initmod.allocation_cache_32_debug.ll:119:145: error: invalid debug info flag flag 'DIFlagTrivial'
!9 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "halide_mutex", file: !10, line: 112, size: 32, flags: DIFlagTypePassByValue | DIFlagTrivial, elements: !11, identifier: "_ZTS12halide_mutex")
                                                                                                                                                ^
src/runtime/CMakeFiles/Halide_initmod.dir/build.make:2170: recipe for target 'src/runtime/initmod.allocation_cache_32_debug.bc' failed
make[2]: *** [src/runtime/initmod.allocation_cache_32_debug.bc] Error 1
CMakeFiles/Makefile2:2125: recipe for target 'src/runtime/CMakeFiles/Halide_initmod.dir/all' failed
make[1]: *** [src/runtime/CMakeFiles/Halide_initmod.dir/all] Error 2
Makefile:182: recipe for target 'all' failed
make: *** [all] Error 2
```

It fails very early on.  I see a lot of these if I do `make -j8`, so I think everything fails this way.  I do not see these errors on master branch.

Full build log is here if needed: https://gist.github.com/Infinoid/291927fd71bc9826ed74b7494afa08c1

I get the same error for multiple values of `CMAKE_BUILD_TYPE`; I tried `Release`, `Debug`, `RelWithDebInfo`.

**Comment by Infinoid** [comment]
My machine has LLVM 10 and clang 10 on it, and had some older remnants of llvm 9 on it.  I think that somehow, it was trying to use LLVM 10, but invoked llvm-as-9 by mistake.

Removing the `llvm-9-tools` package fixed the problem.  Reinstalling the `llvm-9-tools` package does not reintroduce the problem - it builds fine for me now.

I think Ubuntu had a bad symlink for it in /etc/alternatives or something.  I am not sure why `cmake-modern` is different from `master` in this regard.  Maybe it calls the assembler explicitly now, and it didn't before?

Either way, it was clearly a badly configured build machine; closing.

**Comment by Infinoid** [comment]
(apologies for the state flapping.  I had thought I found the problem, but was mistakenly building against the wrong branch.)

**Comment by Infinoid** [comment]
When I build with `make VERBOSE=1`, I see that it is compiling with `clang-8` and assembling with `llvm-as-10`.

```
[  3%] Generating initmod.allocation_cache_32_debug.ll
cd /home/infinoid/workspace/halide/build/src/runtime && /usr/lib/llvm-8/bin/clang-8 -O3 -fno-vectorize -ffreestanding -fno-blocks -fno-exceptions -fno-unwind-tables -fpic -fno-threadsafe-statics -g -DDEBUG_RUNTIME -DCOMPILING_HALIDE_RUNTIME -DLLVM_VERSION= -DBITS_32 -m32 -target le32-unknown-nacl-unknown -emit-llvm -S /home/infinoid/workspace/halide/git/src/runtime/allocation_cache.cpp -o initmod.allocation_cache_32_debug.ll
[  3%] Generating initmod.allocation_cache_32_debug.bc
cd /home/infinoid/workspace/halide/build/src/runtime && /usr/lib/llvm-10/bin/llvm-as initmod.allocation_cache_32_debug.ll -o initmod.allocation_cache_32_debug.bc
/usr/lib/llvm-10/bin/llvm-as: initmod.allocation_cache_32_debug.ll:119:145: error: invalid debug info flag flag 'DIFlagTrivial'
```

CMake said up front that it detected LLVM 10, but it used clang 8.  I think it stems from my having libclang-8-dev installed, but not libclang-10-dev.

After removing libclang-8-dev and installing libclang-10-dev, the build works.  I can see in VERBOSE output that it is compiling with clang-10 and assembling with llvm-as 10.

After installing libclang-8-dev again, the build still works.  After removing libclang-10-dev again, now I get a detection error up front.  I think this is the right behavior.  Not sure why I didn't get it before, or how to get it again.

**Comment by Infinoid** [comment]
I can't reproduce this now, even if I use yesterday's system backup in a chroot.  Chalk it up to bad build environment, I guess.

**Comment by alexreinking** [comment]
> After installing libclang-8-dev again, the build still works. After removing libclang-10-dev again, now I get a detection error up front. I think this is the right behavior. Not sure why I didn't get it before, or how to get it again.

This might be because the dependencies it found were cached. Did you `rm -rf *` the build directory between invocations?

There's probably some work I can do to make finding Clang + LLVM a bit more robust.

**Comment by Infinoid** [comment]
I did do an `rm -rf *` in the build directory before each attempt.  I also disabled ccache as a possible source of confusion.

**Comment by alexreinking** [comment]
Okay, I'll leave this issue open for a while in case you are able to repro. Otherwise, feel free to close.

**Comment by Infinoid** [comment]
I've been trying, to no avail.  I'll open a new issue if I find a reliable way to reproduce the problem.
