### ISSUE TITLE
Unable to get optimal run time with Halide downsampling with blur

### ISSUE THREAD

**Issue by anjugopinath** [halide/Halide#4907]
I wrote a halide program using AOT feature and compiled it to a .lib file (Mine is a windows system). The function name is halide_pyrDown:
It involves downsampling and blurring an image.
https://gist.github.com/anjugopinath/2b4cd7f0e26f151662e3a655ea71548a

I call the function from a new file. (int error=halide_pyrDown(in,out);)
https://gist.github.com/anjugopinath/e78a6b7b3187d1d2c0e53767c22ded2a

The time taken comes to more than 1ms. While expected run time is around 60 microseconds. The dimension of the input image is 1920 by 1080. And depth is 8 bits.

**Comment by abadams** [comment]
Moving my suggested schedule from the gist to the issue for better searchability for other people. TL;DR: Find somewhere good to schedule the boundary condition (or a Func that wraps it - in this case the cast to int16). Don't inline it into a blur.

```
#include "halide_benchmark.h"
#include <Halide.h>

using namespace Halide;

int main(int argc, char **argv) {
    Var x, y;
    Func input16, downx, downy, output;
    ImageParam input(UInt(8), 2);

    Func in_bounded = BoundaryConditions::repeat_edge(input);
    input16(x, y) = cast<uint16_t>(in_bounded(x, y));

    downy(x, y) = (6 * input16(x, 2 * y) +
                   4 * (input16(x, 2 * y - 1) + input16(x, 2 * y + 1)) +
                   (input16(x, 2 * y - 2) + input16(x, 2 * y + 2)));

    downx(x, y) = (6 * downy(2 * x, y) +
                   4 * (downy(2 * x - 1, y) + downy(2 * x + 1, y)) +
                   (downy(2 * x - 2, y) + downy(2 * x + 2, y)));

    output(x, y) = cast<uint8_t>(downx(x, y) / 256);

    Var yi, xi;
    output.tile(x, y, xi, yi, 60, 27).parallel(y).vectorize(xi, 16);
    downy.compute_at(output, yi).vectorize(x, 16, TailStrategy::RoundUp);
    input16.store_at(output, x).compute_at(downy, y).vectorize(x);

    Buffer<uint8_t> in(1920, 1080);
    Buffer<uint8_t> out(1920 / 2, 1080 / 2);
    input.set(in);

    output.compile_to_assembly("/dev/stdout", {input}, Target("host-no_asserts-no_runtime-no_bounds_query"));

    for (int i = 0; i < 10; i++) {
        double time = Tools::benchmark(30, 30, [&]() { output.realize(out); });
        std::cout << "Time: " << (time * 1000000) << " microseconds \n";
    }

    return 0;
}
```

**Comment by anjugopinath** [comment]
This schedule is taking around 656100 ns or around 656 microseconds on my system. This is lesser than the opencv version. So, my goal is reached. Thank You very much!
 Still, I am curious as to what configuration your computer has since it takes only 90 microseconds. The configurations of my Dell laptop are:
XPS 15 7590 (model)
Processor : Intel(R) Core(TM) i7-9750H CPU@2.6 GHz
32 GB RAM
64bit OS, x64-based processor

You had also mentioned in Gitter about increasing the number of threads to reduce the run time even further. It would be great if you could share some links to the literature behind optimizing Halide code to get maximum performance depending on the system architecture. I am aware of "Target" . I am also aware of the parameters like Cache Size, maximum parallelism etc introduced through lesson 21 on autoschedulers. But, I am not sure how we can optimize the manual schedule based on these parameters.

**Comment by abadams** [comment]
I'm on a 16-core workstation with a i9-7960X in it. It has AVX-512. So based on core count difference and vector size difference my CPU could be 5.3x faster than yours. That would explain most of the difference.

Another thing that might make a difference here is windows vs ubuntu. Halide's thread-pools are different and this is a very cheap pipeline so it might be that our threading overhead is larger on windows.

**Comment by abadams** [comment]
You might want to try using other tile height than 27. I suggest trying 30, 45, 60, and 90. Those all give you a number of parallel tasks which is multiple of your core count, which might minimize the number of idle cores.

In general with scheduling you just try lots of things and see what works.

**Comment by anjugopinath** [comment]
Thank you very much!
