### ISSUE TITLE
CMake apps build changes on cmake-modern

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#4943]
In an effort to isolate the apps from the rest of the build, and to test our eventual distribution packages, the apps' CMakeLists.txt files were made _entirely standalone_ from the rest of the build. They call `find_package(Halide)` to load Halide and its special build rules for generators. They also define tests to run the apps on input images and ensure that nothing crashes.

The issue is that _building_ the apps therefore becomes part of _testing_ the app from the main build's perspective and @steven-johnson wants a way to validate that everything builds in a single command (ie. `cmake --build .`). Installing yourself and triggering external builds is not really ergonomic with CMake unless we want to switch to a super-build structure, which would require some filesystem rearrangement I don't think anyone particularly wants.

The compromise I came up with was to add a flag, `APPS_INTERNAL`, which changes the behavior to adding the apps (and their tests) to the main build and NOT testing them externally. By default, it is off, meaning that apps only rebuild when they are run as tests.

If anyone has a better solution, this issue is the place to discuss it before landing #4644 .

**Comment by abadams** [comment]
I agree that it would be nice to have a single command to build the world for testing, but I don't see that it needs to be "cmake --build .", especially if it complicates the build files.

Can't the buildbots just do: `cmake --build .; for app in ...; do pushd apps/${app}; cmake --build . ; popd` or similar?

**Comment by alexreinking** [comment]
The command to build everything would be `cmake --build . ; ctest -L apps`
