### ISSUE TITLE
Eigen benchmarking is a bottleneck

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#4944]
Eigen is very slow, especially for gemm at N=2560. The linear_algebra app takes 325 seconds with two blas-es plus Eigen to run, of which 144 seconds are dedicated to Eigen (44%).

I don't think we should be waiting for 2 minutes per configuration (maybe 10 minutes in a single buildbot) just to re-discover that Eigen is slow.

What should we do about this?

**Comment by zvookin** [comment]
Do we need to run *any* third party benchmark stuff unless it is producing
results we are validating against? Benchmarks to check performance are
great but I don't think they belong in CI testing.

**Comment by abadams** [comment]
Agreed. "Make test" in linear algebra doesn't run the benchmarks afaik

**Comment by alexreinking** [comment]
Okay, then that was a (non-)ehavior I didn't need to replicate. I'll have it skip the benchmarking tests

**Comment by alexreinking** [comment]
Fixed by #5482
