### ISSUE TITLE
Garbage buffers possible from imageio with NDEBUG

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#4971]
The following Halide program exhibits some bad behavior. The load_image call loads the buffer as 8-bit when using the `apps/images/grey_small.png` input image, breaking type-safety when `NDEBUG` is defined.

Furthermore, `load_and_convert_image` fails with an assertion check in this case when `NDEBUG` is not defined. It isn't clear to me what the right way is to run the homepage code (a fairly serious problem, imo) on a simple greyscale PNG.

```
#include "Halide.h"
#include "halide_image_io.h"

#include <iostream>

using namespace Halide;
using namespace Halide::Tools;

// Code from halide-lang.org
Func blur3x3(Func input) {
    Func blur_x, blur_y;
    Var x, y, xi, yi;

    // The algorithm - no storage or order
    blur_x(x, y) = (input(x - 1, y) + input(x, y) + input(x + 1, y)) / 3;
    blur_y(x, y) = (blur_x(x, y - 1) + blur_x(x, y) + blur_x(x, y + 1)) / 3;

    // The schedule - defines order, locality; implies storage
    blur_y.tile(x, y, xi, yi, 256, 32).vectorize(xi, 8).parallel(y);
    blur_x.compute_at(blur_y, x).vectorize(x, 8);

    return blur_y;
}

int main(int argc, char **argv) {
    if (argc < 3) {
        std::cout << "Usage: " << argv[0] << " <input-file> <output-file>\n";
        return 1;
    }

    // 1. Load the image from disk.
    Buffer<float> input = load_image(argv[1]);

    // 2. Define the points outside the image.
    Func with_boundary = BoundaryConditions::repeat_edge(input);

    // 3. Build the blur program.
    Func output = blur3x3(with_boundary);

    // 4. JIT compile and run the blur.
    Buffer<float> result = output.realize(input.width(), input.height());
    
    // 5. Write the code back out.
    save_image(result, argv[2]);

    return 0;
}
```

**Comment by abadams** [comment]
There are two issues here. The uncontroversial one is that load_and_convert shouldn't be failing to convert to a `Buffer<float>`. 

Then there's NDEBUG. NDEBUG is a ridiculous foot-gun. Nobody should ever define it in code that hasn't been thoroughly tested already, and it should be an explicit opt-in. But apparently cmake jams it in implicitly in release builds (can we get it to stop?). Looking through the asserts in Runtime::Buffer, I see some (in `operator()`) that would probably foil autovectorization of hot loops if they're left on by introducing control flow on values that might alias with the pixel data. If we can use __restrict to ensure this can't happen then maybe we can just use a variant of assert that's immune to NDEBUG and not worry about any performance hit.

**Comment by abadams** [comment]
Actually I suspect in the common case the value being tested is on the stack, whereas the pixel data is all heap data, so alias analysis should work out. Still needs checking. I'll test some things tomorrow.

**Comment by alexreinking** [comment]
> Then there's NDEBUG. NDEBUG is a ridiculous foot-gun. Nobody should ever define it in code that hasn't been thoroughly tested already, and it should be an explicit opt-in. But apparently cmake jams it in implicitly in release builds (can we get it to stop?).

No, and it's the expected behavior for many developers compiling in Release mode, especially on Windows. I don't see why this particular assert can be disabled at _all_. In the worst case, it's dwarfed by the cost of loading the actual image and is only checked once anyway (right?). In the best case, those handfuls of cycles save you awful UB bugs and development-time headaches.

**Comment by abadams** [comment]
This particular assert isn't usually performance critical, but there are other uses of assert in that file that are in performance-critical code, and the thinking was we'd developers to be able to turn them off, and that we didn't want to mix types of assert. The reason they're disableable at all is that after our experience with everyone and their dog writing a different wrapper for buffer_t we wanted a buffer class that left no room below it for something more efficient. 

I stand by my opinion of NDEBUG. It's one of the many things I hate about development environments that boil down complex compiler behavior to a handful of modes. Foot-guns should be explicitly opt-in (NDEBUG, march=native, fun safe math, strict aliasing, omitting the frame pointer)

**Comment by abadams** [comment]
idea from discussion offline: Buffer::assert_can_convert_from should not delegate to Runtime::Buffer::assert_can_convert_from, because NDEBUG might be on. It should do a separate user_assert. Then it does nice things like throw exceptions if exceptions are on.

**Comment by abadams** [comment]
ok, with that PR the only way I can get a garbage buffer with NDEBUG on is if I do this:

```
    Runtime::Buffer<float> in = load_image(argv[1]);
    Buffer<float> input(std::move(in));
```

This option throws a user_assert:
```
    Buffer<float> in = load_image(argv[1]);
```

This option doesn't work, because you can't use a Runtime::Buffer directly in JIT pipelines. That's not what it's for.

```
    Runtime::Buffer<float> in = load_image(argv[1]);
```

I was unable to repro the issue where just using ```Buffer<float>``` combined with load_and_convert_image produced a corrupted output.

I can fix up that one remaining garbage case with an extra check in load_image. I'll do that.

**Comment by abadams** [comment]
Done. Now there are two layers of protection.

**Comment by alexreinking** [comment]
> I stand by my opinion of NDEBUG.

My opinion on NDEBUG is this: It shouldn't exist at all but since it does, it should be treated adversarially and so library headers shouldn't use it.

MSVC has long enabled it by default in Release builds and CMake inherited that decision. C++ programmers expect their simple assignment statements to be type-safe, regardless. We can either adapt to that reality or frustrate our users.

> ok, with that PR the only way I can get a garbage buffer with NDEBUG on is if I do this:

So the move constructor asserts when NDEBUG is not defined?

> Done. Now there are two layers of protection.

:+1:
