### ISSUE TITLE
How to implement opengl code using Halide?

### ISSUE THREAD

**Issue by anjugopinath** [halide/Halide#4981]
I have the following opengl code:
https://gist.github.com/anjugopinath/783f15306fc225666ff8c42cef4fa4a0
How can I implement this using Halide?
1) pow(v3.xyz,v1.xxx)) [line no : 21] -> can I implement fast_pow ?
2) Is it possible to parallelize min and max operations ? Lines 21,22,25
3) Should I implement Buffer instead of vec3 and vec4?

**Comment by abadams** [comment]
pow/min/max should all be doable, but the opengl backend is sadly pretty busted right now so I wouldn't recommend it. We're working on fixing up the openglcompute backend as an alternative, but really you want to use cuda, opencl, metal, or d3d12

**Comment by anjugopinath** [comment]
Which one would be better out of cuda, opencl, metal or d3d12 ? it needs to run on an Android device
Could you give me some leads on how to implement it using one of them please?

**Comment by abadams** [comment]
On an Android device opencl would be the best of those options, but it's device-specific whether or not opencl will run.
