### ISSUE TITLE
Buffer Argument is NULL

### ISSUE THREAD

**Issue by anoop2705** [halide/Halide#4983]
Hello all,I am new to Halide and was given a image processing Pipeline. I am trying to understand this pipe line by printing values. Following the tutorial from https://halide-lang.org/tutorials/tutorial_lesson_04_debugging_2.html, I tried to print the values. It is giving me   errors.

 1.**Buffer argument in_patch is NULL** for **transform.realize(512,256,3)**.

 

Is there a way to work around the this error?

I have seen the syntax for Buffer and i think the pointer is linked in the line
               Input<Buffer<uint8_t>>   in_patch   {"in_patch"   , 3};

Any Help wil be highly Appreciated.

Thanks in advance

    #include "Halide.h"
    
    namespace {
    
    using namespace Halide;
    
    ///////////////////////// We will define a generator to auto-schedule.
    class AutoScheduled : public Halide::Generator<AutoScheduled> {
    public:
        Input<Buffer<uint8_t>>   in_patch   {"in_patch"   , 3};
        Input<Buffer<float>>   ctrl_pts_h {"ctrl_pts_h" , 2};      
        Input<Buffer<float>>   weights_h  {"weights_h"  , 2};       
        Input<Buffer<float>>   rev_tone_h {"rev_tone_h" , 2};       
        Input<Buffer<float>>   TsTw_tran_h{"TsTw_tran_h", 2};       
        Input<Buffer<float>>   coefs_h    {"coefs_h"    , 2};       
    
        Output<Buffer<uint8_t>> processed {"processed"  , 3};
    
        void generate() {  
        Var x("x"), y("y"), c("c");
       
            Func scale("scale");
            scale(x,y,c) = cast<float>(in_patch(x,y,c))/256;
    
            // Color map and white balance transform
           
            Func transform("transform");
                transform(x,y,c) = select(
                    // Perform matrix multiplication, set min of 0
                    c == 0, scale(x,y,0)      * TsTw_tran_h(0,0)
                          + scale(x,y,1)      * TsTw_tran_h(1,0)
                          + scale(x,y,2)      * TsTw_tran_h(2,0),
                    c == 1, scale(x,y,0)      * TsTw_tran_h(0,1)
                          + scale(x,y,1)      * TsTw_tran_h(1,1)
                          + scale(x,y,2)      * TsTw_tran_h(2,1),
                            scale(x,y,0)      * TsTw_tran_h(0,2)
                          + scale(x,y,1)      * TsTw_tran_h(1,2)
                          + scale(x,y,2)      * TsTw_tran_h(2,2) );
                          scale.compute_root();
                          transform.trace_stores();
                          scale.trace_stores();
                          TsTw_tran_h.realize(3,3);
                          transform.realize(512,256,3);
      
            processed(x, y, c) = cast<uint8_t>( min( max( transform(x,y,c) * 255, 0), 255 ) ); 
        }

**Comment by clutzweiler** [comment]
(Likely, I am not an expert either) The cause is mixing concepts from AOT (_Generator_) and JIT work-flows (_realize()_). At the time of calling, the _Input_ is not backed by an actual buffer (yet).

In order to run the pipeline and perform tracing, follow the usual two-step AOT work-flow as described in the _Tutorial Lesson 10_ and (most of the apps / tests):

1. Compile and run the generator to create the static library (after removing _realize()_).
2. Generate test program for running the pipeline which links against the generated library (e.g. as shown in _Lesson 10, Part II_ or all the _*_run.cpp*). This should output the tracing then. (As alternative to a C++ test program, Python / Matlab can be used as well, for the case you are already familiar with the corresponding work-flows.)

**Comment by anoop2705** [comment]
Hello Clutzwielr, Thank you for the reply.
 I was able to create the static library just by compiling. There is a test program that runs the pipeline with the generated static library. But I do not understand how can one print the values at this step. Can you please tell me how to proceed with this. I have attached the staticlibrary(.h), generator(fwd_v4) and the test program (scheduler_run)

[print_halide.zip](https://github.com/halide/Halide/files/4715227/print_halide.zip)

Thanks in advance

**Comment by clutzweiler** [comment]
There might be two approaches:

- Enable tracing when running the generator, e.g.: ```$ generator_bin target=host-trace_stores-trace_loads <all_other_params_as_usual>```.
- Wrap the _Exprs_ in the calculations in ```print()``` or ```print_when()```.

**Comment by anoop2705** [comment]
Thanks for your reply. It worked.

Also I wanted to let you know that one more reason for the problem was the auto schedule. I didn't consider that when printing the values. Most of the functions were inline and hence I wasn't able to print them, Once it was disabled, I was able to print everything.
