### ISSUE TITLE
Windows buildbots hitting assertion failures in LLVM

### ISSUE THREAD

**Issue by shoaibkamil** [halide/Halide#4996]
We're seeing the following error on a few tests:

```
Assertion failed: AfterInsn && "Expected label after instruction", file C:\build_bot\worker\win-64-testbranch-1000\llvm-project\llvm\lib\CodeGen\AsmPrinter\DebugHandlerBase.cpp, line 136
```

These seem to occur in tests that are manually setting the `Target::Debug` feature, and they've been showing up in OpenCL and D3D12Compute.

CC @alexreinking: May be related to Day 1 changes to remove debug info.

**Comment by alexreinking** [comment]
Lines 168 and 169 of src/runtime/CMakeLists.txt control the flags clang uses to compile the runtime CPP files into initmod.cpp s.

Try moving the `-g` option from RUNTIME_DEFINES_debug to RUNTIME_DEFINES and rebuild.

This change was made to match the Makefile, so if that fixes your issue, we'll need to dig a bit deeper to find the correct resolution.

**Comment by shoaibkamil** [comment]
Thanks, let me try that here: https://github.com/halide/Halide/pull/4994/

**Comment by alexreinking** [comment]
I wonder if this could be an issue with new MSVC. @steven-johnson -- you upgraded the buildbots's Visual Studio / MSVC recently, right?

**Comment by shoaibkamil** [comment]
That could possibly explain why I don't see it locally (I have VS2017, not 2019).

**Comment by steven-johnson** [comment]
Yep -- we are running VS2019 16.6.1

**Comment by steven-johnson** [comment]
According to bisect, the failure was injected in commit 8720d3753693220d989b8e1cce71593c4b934372 (Merge remote-tracking branch 'remotes/origin/openglcompute_reuse_shared_allocations' into halide-builder/origin/slomp/d3d12fix)

**Comment by steven-johnson** [comment]
...could it be the `halide_unused` stuff?

**Comment by shoaibkamil** [comment]
I can back out that change and try on the buildbot if you'd like.  I still can't get it to happen on my machine for some reason.

**Comment by steven-johnson** [comment]
Short version: I have no idea, and things are weird. On the hope that we just had a glitch in our build, I wiped all intermediate build products on the winbot and am going to let it regenerate everything overnight.

**Comment by alexreinking** [comment]
Wouldn't it be hilarious if MSVC 16.6.1 just broke like half of C++?

**Comment by steven-johnson** [comment]
> Wouldn't it be hilarious if MSVC 16.6.1 just broke like half of C++?

https://www.youtube.com/watch?v=hWP_q4os-5g

**Comment by shoaibkamil** [comment]
#5010 addresses this
