### ISSUE TITLE
Is it possible to vectorize this algorithm with Halide?

### ISSUE THREAD

**Issue by l-oneil** [halide/Halide#5020]
Hi, 

I've been trying to produce a vectorized implementation of the classic [Integral Image Algorithm ](https://www.mathworks.com/help/images/ref/integralimage.html) in Halide. 

I know that it is possible to vectorize this algorithm with intrinsics, as I have seen the [OpenCV implementation here](https://github.com/opencv/opencv/blob/25f3a11a161bfb2a753cc605e1856ae074627b41/modules/imgproc/src/sumpixels.simd.hpp#L117). 

I have been trying for a while now to understand a way to vectorize my implementation through the Halide schedule, but I am beginning to think this might not be possible via Halide scheduling. 

I would appreciate any advice on vectorizing this: 

    Var x{"x"}, y{"y"};
    Func out("out");
    Func in("in");

    // Create Input Image
    in(x, y) = 1;
    Halide::Buffer<int32_t> input = in.realize(width, height);
    
    // Integral Image Algorithm
    RDom r(input);
    Func integralImage("integralImage"), I("I");

    I(x,y) = Halide::cast<int32_t>(input(x , y));
    out(x, y) = 0;

    // Formula
    out(r.x +1, r.y+1) =  I(r.x, r.y)
                          + out(r.x, r.y+1)
                          + out(r.x+1,   r.y)
                          - out(r.x, r.y);

    Halide::Buffer<int32_t> output = out.realize(width+1, height+1);
    out.print_loop_nest();`

**Comment by abadams** [comment]
I don't think this is possible with scheduling alone. The usual way to vectorize/parallelize an integral image computation is to do it in two passes, first summing in y, and then in x (or vice-versa). An integral image is a special case of a separable iir blur where the filter is [1 1], so you could start with apps/iir_blur (which uses [1-alpha, alpha])

**Comment by l-oneil** [comment]
Thank you for the quick response! 
My understanding would be that I will achieve worse performance than this OpenCV implementation if I alter the algorithm to rely on 2 images passes? If we ignore parallelization to keep the comparison fair, would you agree?

**Comment by abadams** [comment]
Depends on what the OpenCV implementation does. There are other ways to vectorize the algorithm using tricks to decompose IIRs, but they incur additional compute overhead.

**Comment by l-oneil** [comment]
OK - thank you again, I'll have a good look over the apps/iir_blur implementation.
