### ISSUE TITLE
Intermittent failures building apps on Windows

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#5048]
We (@steven-johnson and I) have observed the following errors while building apps on CI. It's fairly reliable to reproduce on winbot-1, win32.

```
[when running a generator executable]
This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher
```

Known:

* Happens 20-25% of the time when running a script in a loop.
* Will NOT happen if [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) is running (of course)

Unknown:

* Does this happen on winbot-2? winbot-1 has a known-broken VS install.
* Does this happen on win64?
---
Script I'm using to poke the bear:
```
:repeat
rd /s /q apps\_Halide_install
rd /s /q apps\app_test_linear_algebra
ctest -R linear_algebra --output-on-failure --timeout 35
goto :repeat
```

**Comment by alexreinking** [comment]
Relatedly, we should just replace the winbots with more/faster computers that have modern GPUs.

**Comment by alexreinking** [comment]
I believe this is a Ninja bug. I repro'd locally (with much lower rate of failure).

https://github.com/ninja-build/ninja/issues/1802

**Comment by alexreinking** [comment]
Turns out this is Windows Defender getting in the way. My local build stopped repro-ing that bug when I added the build directory to the exclusions list. I have updated the configuration on the winbots and we'll see if that fixes it.

**Comment by alexreinking** [comment]
Advice from the Cpplang Slack suggests disabling the following:

- disable auto update
- disable Windows Error Reporting service
- disabled Windows Firewall
- disabled Windows Defender (for good)
- disabled Windows Update service
- disabled Windows Search service
- disabled New Network prompt

**Comment by steven-johnson** [comment]
Uh... this buildbot is naked on the public internet. Disabling that stuff on a Windows system seems like a Really Really REALLY **REALLY** Terrible, Horrible, No Good, Very Bad Idea. 

Is it really not possible to make a basic effing build system work reliably with those enabled?

**Comment by abadams** [comment]
Windows defender definitely cripples dev work unless you exclude the directory. It can add multiple seconds of latency before launching any freshly-compiled binary. Agree with Steven for the rest of it.

**Comment by alexreinking** [comment]
> Uh... this buildbot is naked on the public internet.

So they were running their CI in virtual machines. If anything goes wrong, it's easy to just re-image them.

> Windows defender definitely cripples dev work unless you exclude the directory. It can add multiple seconds of latency before launching any freshly-compiled binary. 

Yeah. Excluding the directory tells Windows Defender to stop scanning it. In this case, it's holding a lock on the file in between the link and execute build steps, which is causing the intermittent failures.

**Comment by alexreinking** [comment]
This was fixed as described above.
