### ISSUE TITLE
'distrib' directory missing in repo root

### ISSUE THREAD

**Issue by AlphaStream** [halide/Halide#5060]
This prevents apps from building, see https://github.com/halide/Halide/blob/85218960d4df43622711ed99c4a64e53125d9b74/apps/support/Makefile.inc#L6

**Comment by abadams** [comment]
The distrib directory is created with "make distrib" in the root folder.

Was the issue that you just ran "make" in the root folder (or in the root of an out of tree build)? We should possible add "distrib" to the list of targets that gets built just with "make"

**Comment by AlphaStream** [comment]
What I was trying to do is:
```
~/halide/apps/hexagon_benchmarks$ ./adb_run_on_device.sh
../support/Makefile.inc:44: /halide_config.make: No such file or directory
```
Thanks @abadams , `make distrib` from the repo root worked!

**Comment by abadams** [comment]
And was that the only thing you had done in the checkout? Maybe the fix is to add an explanatory error message in Makefile.inc if distrib doesn't exist.

**Comment by AlphaStream** [comment]
Yes, pretty much.

Adding an error message would certainly help. Fwiw, I also spent some time figuring out the 
`/bin/aarch64-linux-android-c++ not found`
error; turns out, one should also specify `ANDROID_ARM64_TOOLCHAIN`. Might be good to check if that is set upfront as well.
