### ISSUE TITLE
Coalescing scalar loads into vector loads

### ISSUE THREAD

**Issue by joesavage** [halide/Halide#5071]
As briefly discussed on [Gitter](https://gitter.im/halide/Halide?at=5ef46731fa0c9221fc5c6690), I've recently run into some situations in which the compiler currently emits many small scalar loads where I'd much prefer it to emit a few vector loads with some indexing.

Take, for example, the following kernel to perform a 12xK by Kx8 matrix multiply on AArch64:

```c
#include "Halide.h"

using namespace Halide;

int main(int argc, char **argv)
{
    // Declare arguments
    // NOTE: A is in 4x4 row-major blocks, B in 4x4 column-major blocks
    ImageParam A_blocks(type_of<uint8_t>(), 4, "A_blocks");
    ImageParam B_blocks(type_of<uint8_t>(), 4, "B_blocks");
    const Expr sum_size = A_blocks.dim(0).extent() * A_blocks.dim(2).extent();
    std::vector<Argument> args(2);
    args[0] = A_blocks;
    args[1] = B_blocks;

    // GEMM (in 4x4 blocks, calculating results row-major)
    Func AB("AB");
    RDom rv(0, 4, 0, sum_size / 4);
    Var ii("ii"), ji("ji"), io("io"), jo("jo");
    AB(ji, ii, jo, io)  = cast(UInt(32), 0);
    AB(ji, ii, jo, io) += cast(UInt(32), B_blocks(rv.x, ji, rv.y, jo)) *
                                         A_blocks(rv.x, ii, rv.y, io);
    AB.compute_root();

    // Rearrange outputs
    Var i("i"), j("j");
    Func gemm_12x8("gemm_12x8");
    gemm_12x8(j, i) = AB(j % 4, i % 4, j / 4, i / 4);

    // Constraints
    OutputImageParam output = gemm_12x8.output_buffer();
    output.dim(0).set_bounds(0,  8);
    output.dim(1).set_bounds(0, 12);
    A_blocks.dim(0).set_bounds(0, 4);
    A_blocks.dim(1).set_min(0).set_stride(4);
    A_blocks.dim(2).set_min(0);
    A_blocks.dim(3).set_min(0);
    B_blocks.dim(0).set_bounds(0, 4);
    B_blocks.dim(1).set_min(0).set_stride(4);
    B_blocks.dim(2).set_min(0);
    B_blocks.dim(3).set_min(0);

    // Schedule
    RVar fused("fused");
    AB.update(0).reorder(rv.x, ji, ii, jo, io, rv.y).fuse(rv.x, ji, fused);
    AB.update(0).atomic().vectorize(fused).unroll(ii).unroll(jo).unroll(io);
    gemm_12x8.vectorize(j, 4).unroll(j).unroll(i);

    // Compile for bare metal AArch64
    Target target(Target::NoOS, Target::ARM, 64);
    std::vector<Target::Feature> arm_features;
    arm_features.push_back(Target::ARMDotProd);
    target.set_features(arm_features);
    gemm_12x8.compile_to_file("gemm_12x8", args, "", target);

    return 0;
}
```

As in #5069, this generates an interleave-of-broadcasts pattern:

```
AB[ramp(0, 1, 4)]  += (uint32x4)vector_reduce(Add, (uint32x16((uint8x16)B_blocks[ramp(AB.s1.rv$y*B_blocks.stride.2, 1, 16)]) *
                                                    uint32x16(interleave_vectors(x4((uint8)A_blocks[t97]),
                                                                                 x4((uint8)A_blocks[t97 + 1]),
                                                                                 x4((uint8)A_blocks[t97 + 2]),
                                                                                 x4((uint8)A_blocks[t97 + 3])))))
```

Since the schedule then unrolls this loop over dimension `ii`, we end up with a bunch of these operations next to each other, as follows:

```
AB[ramp(0, 1, 4)]  += (uint32x4)vector_reduce(Add, (uint32x16((uint8x16)B_blocks[ramp(AB.s1.rv$y*B_blocks.stride.2, 1, 16)]) *
                                                    uint32x16(interleave_vectors(x4((uint8)A_blocks[t97]),
                                                                                 x4((uint8)A_blocks[t97 + 1]),
                                                                                 x4((uint8)A_blocks[t97 + 2]),
                                                                                 x4((uint8)A_blocks[t97 + 3])))))
AB[ramp(4, 1, 4)]  += (uint32x4)vector_reduce(Add, (uint32x16((uint8x16)B_blocks[ramp(AB.s1.rv$y*B_blocks.stride.2, 1, 16)]) *
                                                    uint32x16(interleave_vectors(x4((uint8)A_blocks[t97 + 4]),
                                                                                 x4((uint8)A_blocks[t97 + 5]),
                                                                                 x4((uint8)A_blocks[t97 + 6]),
                                                                                 x4((uint8)A_blocks[t97 + 7])))))
AB[ramp(8, 1, 4)]  += (uint32x4)vector_reduce(Add, (uint32x16((uint8x16)B_blocks[ramp(AB.s1.rv$y*B_blocks.stride.2, 1, 16)]) *
                                                    uint32x16(interleave_vectors(x4((uint8)A_blocks[t97 + 8]),
                                                                                 x4((uint8)A_blocks[t97 + 9]),
                                                                                 x4((uint8)A_blocks[t97 + 10]),
                                                                                 x4((uint8)A_blocks[t97 + 11])))))
AB[ramp(12, 1, 4)] += (uint32x4)vector_reduce(Add, (uint32x16((uint8x16)B_blocks[ramp(AB.s1.rv$y*B_blocks.stride.2, 1, 16)]) *
                                                    uint32x16(interleave_vectors(x4((uint8)A_blocks[t97 + 12]),
                                                                                 x4((uint8)A_blocks[t97 + 13]),
                                                                                 x4((uint8)A_blocks[t97 + 14]),
                                                                                 x4((uint8)A_blocks[t97 + 15])))))
```

From this, it's plain to see that the `A_blocks` loads in each operation are actually highly related. To generate the best code here, we really want to coalesce these scalar loads into a single vector load – `A_blocks[ramp(AB.s1.rv$y*A_blocks.stride.2, 1, 16)]` – and then simply index into this with `extract_element` as appropriate. Not only should this be cheaper than individual scalar loads, but it also permits the use of 'by element' operations that can forgo wasting vector space on repeated elements entirely (in this case, providing #5069 is also fixed, allowing for the generation of the indexed form of `UDOT`).

Unfortunately, though, this isn't currently what happens. Instead, the compiler emits scalar loads for each individual element, generating a bunch of `load i8` instructions in the LLVM IR. Then, since LLVM doesn't currently seem to be able to do this kind of coalescing for us either, we end up with a whole bunch of scalar operations in the final generated assembly. As [pointed out by @abadams](https://gitter.im/halide/Halide?at=5ef3b938405be935cdbe6b11), this can be resolved by explicitly vectorizing the `A_blocks` loads as follows:

```c
Var a_block("a_block");
A_blocks.in(AB).fuse(_0, _1, a_block).vectorize(a_block).compute_at(AB, jo);
```

However, it's not currently clear whether this should be required in order to get this kind of behaviour or whether the compiler should be able to coalesce these kinds of loads automatically. After all, it's fairly clear from the IR that these loads could be combined, and this is the kind of thing we should be able to handle in an optimisation pass if deemed desirable. Curious to hear any thoughts on this.

**Comment by abadams** [comment]
I think the best solution is explicit staging (.in().compute_at()), because you want to group together work required across different statements (the loads), and that's what compute_at is for. For things that occur within a single expression we should generate the best code we can, but we shouldn't be trying to do heroic cross-stmt optimizations when scheduling directives exist. In this particular case we could  do better codegen for the interleave of adjacent broadcasts: ```interleave_vectors(x4((uint8)A_blocks[t98 + 4]), x4((uint8)A_blocks[t98 + 5]), x4((uint8)A_blocks[t98 + 6]), x4((uint8)A_blocks[t98 + 7]))```

In @vksnk 's nested vectorization PR we could represent this as ```x4((uint8)A_blocks[ramp(t98 + 4, 1, 4)])```, so we'd at least do fewer loads (I think? It's a byte-aligned 32-bit load). It's not your desired solution though.

**Comment by joesavage** [comment]
Makes sense to me. Figured I'd file it just to make sure. Happy to consider this resolved.
