### ISSUE TITLE
Halide::Runtime::Buffer::for_each_value segfaults on an empty buffer

### ISSUE THREAD

**Issue by fbleibel** [halide/Halide#5077]
The following code crashes:
```
  Halide::Runtime::Buffer<int> b;
  b.for_each_value([](int v) {});
```

`for_each_value_helper` doesn't check that ptrs is a valid pointer before dereferencing [here](https://github.com/halide/Halide/blob/master/src/runtime/HalideBuffer.h#L1989).

(and a newly-created or empty buffer has data() == nullptr: https://github.com/halide/Halide/blob/master/src/runtime/HalideBuffer.h#L2073)

This behavior is surprising, and maybe it would be better to never call the callback for an empty buffer, e.g. by checking that `ptrs` is non-null in for_each_value_helper or for_each_value_impl?

**Comment by abadams** [comment]
Take a look at #5084 and tell me if you think an assert is sufficient to make this more friendly. I worry that making it a no-op will just mask a bug in the user code.

**Comment by fbleibel** [comment]
That commit looks good, but I think a noop is a more intuitive action to take here - if you have a container like a std::vector that you iterate over in a for loop, you expect that the for loop will do nothing if the container is empty. I don't think there .

I think for many use cases doing nothing would be more intuitive. E.g. if you want to apply a transformation to the input, you don't have to add  an if() to compute image statistics (<- the use case that prompted me to file a bug), etc. using for_each_value, the same function would work for empty buffers.

**Comment by abadams** [comment]
The crowd has spoken. I'll make it a no-op
