### ISSUE TITLE
Constraining the output buffer of a function doesn't have any impact anymore.

### ISSUE THREAD

**Issue by benoitsteiner** [halide/Halide#5095]
When possible, I tell Halide the exact layout of the output I want it to generate. This helps generate code that can be more efficient. For example, I use the following code, which is similar to what's done in test/correctness/constraints.cpp
```     f(x, y) = (x + y) * (x + y);
      g(x, y) = f(x, y) * 2.0f;
      h(x, y) = g(x, y) * 2 + 1;
      h.output_buffer().dim(0).set_stride(1);
      h.output_buffer().dim(1).set_stride(1000);
      std::cout << "Strides are " << h.output_buffer().dim(0).stride()
                << " and " << h.output_buffer().dim(0).stride() << std::endl;
```

However, I have noticed that this doesn't work anymore. Instead of printing constant strides, my program prints "Strides are h$1.stride.0 and h$1.stride.0" 

Any idea what's going on ?

**Comment by abadams** [comment]
Currently stride() always returns a symbolic variable. The stride constraint is stored elsewhere and used in lowering. Looks like you can query any previously set stride constraint on dimensions i with ```output_buffer().parameter().stride_constraint(i);```

So the assert injected in lowering is effectively

```output_buffer().dim(0).stride() == output_buffer().parameter().stride_constraint(0)```

Open for debate if this is the best behavior though.

**Comment by benoitsteiner** [comment]
Thanks, calling output_buffer().parameter().stride_constraint(i) returns the expected value. I'll leave the issue open in case someone is interested in improving the api.
