### ISSUE TITLE
Updating only host pointer in Halide::Buffer after calling its constructor 

### ISSUE THREAD

**Issue by jsksra1** [halide/Halide#5096]
Is there any way to just update the host pointer for a **Halide::Buffer** ?

What I mean is during runtime I wanted just to update "**buffer.contents.ptr->buf.buf.host**" as my dimensions and all other properties for the buffer remains same.

I just went to various members of [Halide::Buffer](https://halide-lang.org/docs/class_halide_1_1_runtime_1_1_buffer.html) but I realized that all returning new Halide::Buffer.

**Comment by abadams** [comment]
Most of the Halide::Buffer constructors result in it owning the memory, so you'll get a leak if you swap out the host pointer for many of them, and then a crash in the destructor when it tries to free it. The one that doesn't is the one that takes a raw pointer as the first arg. So use that, and then do this:

buffer.raw_buffer()->host = something_else

raw_buffer() gets you the underlying halide_buffer_t to mess with. Use with caution.

**Comment by jsksra1** [comment]
Thanks, this worked. 

I agree with you on the memory leak.
I am trying "JIT in loop" and in my case for every realize() call, all properties(dim, channels etc ) of Halide::Buffer except the memory location of the raw_buffer (host address) will remain same. And call to constructor and destructor of Halide::Buffer in the loop was degrading the performance.
And just updating of the memory location(the way you mentioned) solved the problem.
