### ISSUE TITLE
llvm is now better at autovectorizing 16-bit division by 3 than Halide's explicit vectorization

### ISSUE THREAD

**Issue by ohhuo0** [halide/Halide#5099]
I try to use Generators to generate AOT libraries, and compare the average filtering performance with opencv on the phone. When there is no content in schedule():
```
class HalideFunc : public Generator<HalideFunc> {
public:
    void generator() {
        mean filtering and something...
    }
    void schedule() {
        nothing
    }
private:
    Var x{"x"}, y{"y"};
    Func blur_x, blur_y;
}
```
Halide performance is only half of opencv. The strange thing is that I try to use schedule method in schedule():
```
class HalideFunc : public Generator<HalideFunc> {
public:
    void generator() {
        mean filtering and something...
    }
    void schedule() {
        blur_x.compute_root().vectorize(x, 8).parallel(y);
        blur_y.compute_at(blur_x, y).vectorize(y, 8);
    }
private:
    Var x{"x"}, y{"y"};
    Func blur_x, blur_y;
}
```
Halide performance is even greatly reduced. Where did i use Halide wrong?

**Comment by abadams** [comment]
I believe the problem is vectorize(y, 8). For one scanline of blur_x, you need one scanline of blur_y. But vectorize(y, 8) forces the computation of 8 whole scanlines of blur_y. Try changing it to vectorize(x, 8)

**Comment by ohhuo0** [comment]
Thank you, the performance after the modification is consistent with the default schedule()!
I want to ask another questions, when schedule() is empty, does it call Halide's autoschedule algorithm, when my compilation parameter target="arm-64-android", Is NEON used by default in Android?  the default schedule() seems to be the best performance, but still twice as slow as opencv.

**Comment by abadams** [comment]
Yes, neon is used by default. Halide does not use the autoscheduler by default though. If you leave schedule blank it just inlines everything (and then llvm might autovectorize it).

The fact that blur_x isn't your output makes me wonder if you have a whole extra stage that isn't scheduled at all. If you post the full algorithm I could have a go at writing a good schedule for it.

**Comment by ohhuo0** [comment]
I want to use Halide to implement my algorithm to get better performance, so I am testing the performance of Halide. And after your prompt, I re-viewed my generator, here is my generator:
```
class HalideFunc : public Generator<HalideFunc>
    {
    public:
        Input<Buffer<uint8_t>> input{"input", 2};
        Output<Buffer<uint8_t>> result{"result", 2};

        void generate()
        {
            Func clamped = BoundaryConditions::repeat_edge(input);

            Func input_16("input_16");
            input_16(x, y) = cast<uint16_t>(clamped(x, y));

            blur_x(x, y) = (input_16(x - 1, y) +
                            input_16(x, y) +
                            input_16(x + 1, y)) /
                           3;

            blur_y(x, y) = (blur_x(x, y - 1) +
                            blur_x(x, y) +
                            blur_x(x, y + 1)) /
                           3;

            result(x, y) = cast<uint8_t>(blur_y(x, y));
        }

        void schedule()
        {
        }

    private:
        Var x{"x"}, y{"y"};
        Func blur_x, blur_y;
    };
```
If I don’t consider the correctness of the blur result, and modifying blur_x and blur_y like this:
```
 blur_x(x, y) = (input_16(x - 1, y) +
                            input_16(x, y) +
                            input_16(x + 1, y)) /
                           4;
blur_y(x, y) = (blur_x(x, y - 1) +
                            blur_x(x, y) +
                            blur_x(x, y + 1)) /
                           4;
```
 Halide's performance is about 40%~50% faster than opencv.
I think it is because of the difference between val/4 and val/3? val/4 can be calculated with right shift, but val/3 cannot?

**Comment by abadams** [comment]
Is it cool if I record a video of me scheduling this algorithm? We need more educational material for what the scheduling process looks like in practice.

**Comment by ohhuo0** [comment]
Of course, that`s cool, I may need some information to understand the schedule process, THX !

**Comment by abadams** [comment]
Had to wait for a microphone to arrive in the mail. Here's the video: https://www.youtube.com/watch?v=UeyWo42_PS8&feature=youtu.be

The final schedule was:
```
        Var xi, yi;
        result
            .compute_root()
            .tile(x, y, xi, yi, 512, 20)
            .vectorize(xi, vec)
            .parallel(y);

        blur_x
            .store_at(result, x)
            .compute_at(result, yi)
            .vectorize(x, vec);

        input_16
            .compute_at(blur_x, y)
            .vectorize(x, vec);
```

Inlining everything (the default schedule) is pretty good for this algorithm because llvm does a good job autovectorizing in that case.

**Comment by abadams** [comment]
Actually with trunk llvm, it's even better if you leave off the vectorize calls. LLVM really does a great job at autovectorizing this code.

**Comment by steven-johnson** [comment]
> Actually with trunk llvm, it's even better if you leave off the vectorize calls.

That's great for LLVM but not so great for us. Is LLVM autovectorizing in a *different* way, or is it just that our vectorize code is less clean? IMHO it should be a goal that adding vectorize() schedule directives never results in substantially worse code than if LLVM chose to do an equivalent autovectorization on its own.

**Comment by abadams** [comment]
Yeah, I agree. It looks like llvm avoids the use of pmulhuw for the division by three, and instead does 32-bit multiplies and shifts! So it's a different integer division lowering which at first glance looks worse, but is actually faster. I need to investigate more.

**Comment by abadams** [comment]
Renaming the issue to the reason why the default schedule was good, and assigning myself.

**Comment by abadams** [comment]
That was a red herring. Our inner loop *is* better. The issue is that explicit vectorization changes which loop gets partitioned to eliminate boundary conditions, and it happens that it's better to just partition an inner loop for this app (usually it's better to partition an outer loop).

Best schedule I've found is now:

```
        result
            .compute_root()
            .tile(x, y, xi, yi, 512, 20)
            .parallel(y)
            .vectorize(xi, 32);

        blur_x
            .store_at(result, x)
            .compute_at(result, yi)
            .vectorize(x, 32);

        input16
            .compute_at(blur_x, y);
```

It's about 30% faster than not vectorizing things at all and leaving it to llvm, so it's a big additional step up.
