### ISSUE TITLE
CMake: Unable to call multiple halide_labrary()

### ISSUE THREAD

**Issue by SuTanTank** [halide/Halide#5127]
We have a large CMake project which consists of many algorithms and each of them are inside its own subdirectory. Now I'm trying to implement a few more with Halide. I can use ```halide_library()``` to create the generator and then I can use a wrapper library to call the generated halide function and handle convertion between ```Buffer<T>``` other data structure like OpenCV ```Mat``` since the library users don't know what Halide is. 

However, when I tried to add the second halide library, the second call of ```halide_library()``` failed with error message:
> add_library cannot create target "_halide_library_from_generator_rungen"
  because another target with the same name already exists.  The existing
  target is a static library created in source directory

this error message does make sense, so I'm wondering is it possible to get around this, or we just cannot have two halide_library() called in a single CMake project. 

A toy version of this file structure may be like this:
```
CMakeLists.txt  // HALIDE_DISTRIB_DIR is set
- filter1
  CMakeLists.txt  // halide_library(filter1 SRCS filter1_gen.cpp)
  filter1_gen.cpp
  filter1_wrapper.h
- filter2
  CMakeLists.txt  // halide_library(filter2 SRCS filter2_gen.cpp)  - failed here
  filter2_gen.cpp
  filter2_wrapper.h
```

**Comment by steven-johnson** [comment]
What version of Halide's CMake support are you using? (Our CMake build rules were rewritten from scratch a couple of months ago and are much more robust now.) Many of the examples in the apps/ folder use multiple calls to `add_halide_library()` (eg `camera_pipe`).

**Comment by SuTanTank** [comment]
I'm using the 2019.8 release. Which version should I use? Do I need to build the latest master branch?

**Comment by alexreinking** [comment]
Yes, update to master, read `README_cmake.md` and try again. We're not supporting the old CMake rules anymore.

**Comment by SuTanTank** [comment]
> Yes, update to master, read `README_cmake.md` and try again. We're not supporting the old CMake rules anymore. The structure will look something like this:
> 
> ```
> find_package(Halide REQUIRED)
> 
> add_executable(filter1.gen filter1_gen.cpp)
> target_link_libraries(filter1.gen PRIVATE Halide::Generator)
> 
> add_halide_library(filter1 FROM filter1.gen)
> ```

It's great to see Halide's is so easy to use with CMake now. I made a CMake project template using the new ```add_halide_library()```, and showing how to create filters in different subdirectories in a large algorithm library. Hopefully I can use Halide in the real product soon. 

Here is my CMake demo [https://github.com/SuTanTank/Halide_CMake_Demo](url)

**Comment by alexreinking** [comment]
I'm glad the new rules are working well for you! :)
