### ISSUE TITLE
Building apps/ under CMake needs some documentation

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#5132]
Right now, building apps under CMake has nonobvious bits and needs some documentation and/or cleanup:

- APPS_INTERNAL lets you control whether the apps are built 'internally' or totally separately, but it doesn't appear to be documented anywhere. It should be (at least in the comments), along with description of why you'd want to enable (or disable) this option (ie what are the tradeoffs)

- There doesn't seem to be any predictable way to build and/or test just a single app, and it varies by APPS_INTERNAL:
   - with APPS_INTERNAL=off, building of apps is deferred until CTest is run (I think)
   - with APPS_INTERNAL=on, you can pre-emptively build an individual app, but the names don't always match what you'd expect (eg apps/bilateral_grid is built via the `bilateral_grid_process` target)

(Ideally, we'd have predictable ways to build each app based on the obvious name, regardless of APPS_INTERNAL)

**Comment by alexreinking** [comment]
Assigning myself, since I wrote the code that implements this.

**Comment by steven-johnson** [comment]
It may be simpler to remove APPS_INTERNAL entirely to simplify the situation (IIRC it was added mostly at my request); the driving factor for it though wasn't to actually have it be 'internal' but rather to just have a way to ensure that all apps get built from a `make all` type of request.

**Comment by alexreinking** [comment]
> It may be simpler to remove APPS_INTERNAL entirely to simplify the situation (IIRC it was added mostly at my request);

It was. I think the apps should be validated against an install tree and `APPS_INTERNAL` defeats that purpose.

**Comment by steven-johnson** [comment]
OK, so let's definitely remove APPS_INTERNAL, that leaves us with a simpler set of cases.
