### ISSUE TITLE
Is it possible for Halide to generate C++ with intrinsics 

### ISSUE THREAD

**Issue by jsksra1** [halide/Halide#5147]
Just curious to know and I am working on AVX2 platform

Halide generators can generate C/C++, .o, .lib versions which can be integrated with codebases. Among them [.lib/.o is optimal](https://github.com/halide/Halide/issues/2663). And after looking at the Halide source code I believe that no where intrinsics (_mm256_add_ps etc) are referred for code generation.

Is there any possibility in future that Halide may support emitting intrinsics in the generated C/C++ code? Probably this way C/C++ code will be as optimal as the static library.

**Comment by zvookin** [comment]
The C++ backend can generate generic vector intrinsics. There doesn’t seem
to be much use case for generating architecture specific intrinsics through
the C++ backend and it would require adding the concept of architecture
specificity to that backend, which isn’t really there at present.

-Z-

**Comment by jsksra1** [comment]
I agree your point. Thanks!
