### ISSUE TITLE
Add compiler/platform support matrix to README.md

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#5154]
I was mildly surprised to learn that we don't support building Halide with Homebrew's GCC 10 on macOS. By my understanding, we support the following host compilers and platforms:

| Platform | Compiler | Version |
| --- | --- | --- |
| Windows | MSVC | 14.1+ (VS 2017) |
| Windows | MSVC | 14.2+ (VS 2019) |
| macOS | AppleClang | ?? |
| Linux | GCC | 5.0+ |
| Linux | Clang | 9+ |

Maybe this should just be pasted in to the README?

**Comment by abadams** [comment]
That's surprising. What goes wrong with homebrew gcc?

**Comment by alexreinking** [comment]
For one, `PATH_MAX` isn't imported correctly in `Utils.cpp` (needs the `<sys/syslimits.h>` header). I didn't get farther than that since I'm using Homebrew-installed LLVM, which is compiled against libc++, rather than libstdc++ and I haven't yet figured out how to force GCC to use it.
