### ISSUE TITLE
Make generators support object output in multi-config

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#5169]
End users might want to install the static libraries they create using Halide via CMake. Unfortunately, the current HalideGeneratorHelpers has to create IMPORTED STATIC libraries instead of plain old STATIC ones. IMPORTED targets cannot be installed. There are workarounds for this in CMake, but they are quite painful.

If we were to output _objects_ instead, then CMake could call the archiver on them, feel as though it had done something useful, and promote the generated library to plain old STATIC. However, this requires that we know ahead of time which files the generator is going to produce. The CMake helpers also require support for multi-target builds.

We should extend the `-e o[bject]` output mode of the generator in the following way.

1. Require that all targets in a multi-target list specify `no_runtime`. This is already how CMake does it.
2. Output `.o` files in the current directory whose names match the targets _as they appear on the command line_. ie. preserve "host".
3. The naming change should be reflected in single-target, no_runtime builds, too.
4. While we're at it, fix #5009.

**Comment by steven-johnson** [comment]
I am greatly irked that CMake apparently can't deal with static libraries in a sane way, but then, I don't know what I was expecting. (We should probably file an issue with Kitware on this.)

**Comment by alexreinking** [comment]
I think this would have some value outside of CMake land. It would make it easier to build bundled static libs from generator outputs in other build systems, too (no need to unpack us).

**Comment by steven-johnson** [comment]
> * Require that all targets in a multi-target list specify `no_runtime`. This is already how CMake does it.

Don't see why this *needs* to be a requirement -- we already have the logic to emit the runtime, might as well allow it.

**Comment by steven-johnson** [comment]
> * Output `.o` files in the current directory whose names match the targets _as they appear on the command line_. ie. preserve "host".

We currently aggressively normalize the string form into a `Target` object (in which the hostness is lost), to avoid the 'stringly typed' syndrome. I'll have to add some extra paths to

**Comment by alexreinking** [comment]
> Don't see why this _needs_ to be a requirement -- we already have the logic to emit the runtime, might as well allow it.

There was some comment in Module.cpp to the effect of "things are tricky if we variously include/not no_runtime". I thought adding this restriction would make life easier. Also, compile_to_multitarget should probably use `Target::get_runtime_compatible_target`. Got some duplicated logic there...

**Comment by steven-johnson** [comment]
> There was some comment in Module.cpp to the effect of "things are tricky if we variously include/not no_runtime".

I think that comment is stale wrt this issue (I'll fix it)
