### ISSUE TITLE
'Makefile' build is broken for OSX builds with LLVM trunk

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#5190]
On my local Mac, building libHalide via `make` (rather than CMake) and using current (Aug 17) LLVM trunk build, libHalide.dylib fails to build with: `ld: library not found for -llibz.tbd`

(The buildbots aren't failing because the Mac buildbot doesn't build testbranches against llvm-trunk, only llvm-11 and llvm-10)

**Comment by steven-johnson** [comment]
FYI:

```
$ llvm-config --system-libs
-lm -llibz.tbd
```

**Comment by steven-johnson** [comment]
Also note, this is building with XCode 11.x on Catalina.

**Comment by shoaibkamil** [comment]
I noticed this behavior with Big Sur betas. Are you seeing this on Catalina as well?

**Comment by steven-johnson** [comment]
> I noticed this behavior with Big Sur betas. Are you seeing this on Catalina as well?
> […](#)
> On Aug 17, 2020, at 8:47 PM, Steven Johnson ***@***.***> wrote: ﻿ FYI: $ llvm-config --system-libs -lm -llibz.tbd — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

yes

**Comment by steven-johnson** [comment]
This appears to have been fixed in upstream trunk LLVM
