### ISSUE TITLE
windows vcpkg instructions are missing python3

### ISSUE THREAD

**Issue by abadams** [halide/Halide#5207]
This is required now, I think? The instructions should be updated to include installing it via vcpkg, if that's the correct thing.

**Comment by abadams** [comment]
... I don't think it is - installing python3 via vcpkg did not give me a python3.exe. Installing python3 from scratch from python.org worked

**Comment by alexreinking** [comment]
Install Python 3 via the official installer to a global location (ie. in Program Files) along with the development files. Otherwise, install it wherever you like and set the hinting variables (ie. `Python3_ROOT_DIR`) for the FindPython3 module, documented here: https://cmake.org/cmake/help/latest/module/FindPython3.html

**Comment by alexreinking** [comment]
Also, Python 3 is only _required_ if you're building the Python bindings or using WebAssembly (via wabt) on Windows.

**Comment by abadams** [comment]
We should state that in the readme somewhere above the vcpkg bit.

**Comment by abadams** [comment]
Alternatively, the python bindings nicely turn themselves off with a message if you disable exceptions. Is it possible to get the python bindings and wasm backend to turn themselves off politely if no python3 is found? It's not clear from the error you get why python is required or how to disable the components that need it.

**Comment by alexreinking** [comment]
> Is it possible to get the python bindings and wasm backend to turn themselves off politely if no python3 is found?

Yes, it is possible. Just requires restructuring the way we detect Python. This is probably worthwhile because I'm nervous about a corner case where WABT detects a different Python version first.

**Comment by steven-johnson** [comment]
> Also, Python 3 is only _required_ if you're building the Python bindings or using WebAssembly (via wabt) on Windows.

Some of the apps/ require the python bindings, so they have to be skipped too.
