### ISSUE TITLE
Halide Util.cpp uses Win32 functions that are not encoding-safe

### ISSUE THREAD

**Issue by shoaibkamil** [halide/Halide#5223]
Instead of using `CreateDirectoryA()` and other `<foo>A()` functions on Windows, we need to use the corresponding `CreateDirectoryW()` and other `W()` suffixed functions in order to handle directories that may have characters outside the system encoding.  The original reporter at Adobe suggests:

> It is OK to use std::string as their cross platform API. They must decide to use UTF8 and then convert UTF8 to wstring (UTF16) before calling Windows APIs

Currently, trying to use Halide in a user account that has characters outside the system encoding results in an unhandled exception at line 399 of Util.cpp, here:

https://github.com/halide/Halide/blob/d046701e452dcda4fce315a7fe95179d0e43e5bd/src/Util.cpp#L364-L400

**Comment by alexreinking** [comment]
I took a crack at this in #5227
