### ISSUE TITLE
strict_float causes LICM in strange cases

### ISSUE THREAD

**Issue by dsharletg** [halide/Halide#5230]
I randomly noticed this snippet in some IR I was trawling through:

```
  let t39 = (float32)strict_float(0.000000f)
  for (sum_intm.s0.y, 0, 4) {
   let t40 = (f.extent.2*sum_intm.s0.y)*4
   for (sum_intm.s0.x, 0, 4) {
    let t41 = (f.extent.2*sum_intm.s0.x) + t40
    for (sum_intm.s0.z, 0, f.extent.2) {
     sum_intm[sum_intm.s0.z + t41] = t39
    }
   }
  }
```

It seems like we LICMed `strict_float(0.0f)`, when I don't think we would have done this if it were just 0.0f.

**Comment by zvookin** [comment]
I agree this is silly, and I'm not surprised it is happening. However, I'm having trouble proving to myself it's a problem. The issues would be breaking strictness of strict_float or performance loss. I'm not too worried about the latter as LLVM still knows it's a constant. Unfortunately it needs to be wrapped in strict_float to prevent combining and other simplifications. Is there a specific concern I'm missing or do you see a way it is going to cause problems with correctness or performance?

In general, strict_float is unsatisfying in that it has to be wrapped around so much stuff. I still don't have a better way to do it however.

**Comment by abadams** [comment]
The issue is that if it's lifted outside a kernel launch it'll get passed in as a scalar param instead of being an immediate in the kernel source. We just have to teach LICM that "strict_float" is one of those intrinsics that's free to compute, so there's no reason to lift it.
