### ISSUE TITLE
Win Distro builds are failing

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#5241]
Presumably related to recent CMake changes? We now fail trying to build debug versions of LLVM (which are known to be basically not-doable on Windows). See e.g. https://buildbot.halide-lang.org/master/#/builders/14/builds/4

**Comment by steven-johnson** [comment]
Routing to @alexreinking for initial thoughts

**Comment by alexreinking** [comment]
Not sure how this could be related to any of the contents of the Halide repo? This is happening inside LLVM's build. 

LLVM 11 hasn't been released yet, right? Is it possible this is due to an upstream change?

**Comment by alexreinking** [comment]
You could add `-DCMAKE_CXX_FLAGS="/bigobj"` to the CMake configure step for LLVM in the buildbot.

**Comment by alexreinking** [comment]
They apparently add that flag manually to certain files in their build. Seems like an upstream issue.

http://clang-developers.42468.n3.nabble.com/Windows-bigobj-td4063293.html

See the docs for bigobj, too: https://docs.microsoft.com/en-us/cpp/build/reference/bigobj-increase-number-of-sections-in-dot-obj-file?view=vs-2019

**Comment by steven-johnson** [comment]
OK, with /bigopt on for Windows Debug builds of LLVM, we no longer fail there -- we instead fail when trying to manually package up the 'distro' by copying files that are no longer where they used to be. At this point I suspect it's time to rewrite that part of the buildbot script to just use cpack instead.

**Comment by alexreinking** [comment]
Yup. I can help with that.
