### ISSUE TITLE
Typo in code

### ISSUE THREAD

**Issue by goelrohit1980** [halide/Halide#5249]
https://github.com/halide/Halide/blob/664dc4993b8f7ef320378f6318d7db1e09b3d44d/src/VectorizeLoops.cpp#L805

Correct code
for (size_t i = 0; i < op->**values**.size(); i++) {

**Comment by abadams** [comment]
I don't think this code is ever used (which is why it's not causing a crash). I'll just delete it for now, as clearly nobody was depending on it.
