### ISSUE TITLE
Scheduling tiles on a GPU, forcing a gpu-thread loop stride of 1 and reordering it with a reduction loop

### ISSUE THREAD

**Issue by sakehl** [halide/Halide#5261]
Hi,

First off, thanks a lot for creating this amazing language, I really enjoy programming with it.

Next off, the following questions I have been struggling with for a week now. Essentially, what I'm doing is porting the CUDA code found [here](https://github.com/benvanwerkhoven/kernel_tuner/blob/master/examples/cuda/pnpoly.cu) to Halide, and using all the optimizations which were applied. The first part, porting the formula went great, here is the code:

```c++
#include "Halide.h"
#define VERTICES 600
#define SIZE (int)2e7f

using namespace Halide;

class Pnpoly : public Generator<Pnpoly> {
public:
    Input<Buffer<float>> points{"points", 2};
    Input<Buffer<float>> vertices{"vertices", 2};
    Output<Buffer<int>> bitmap{"bitmap", 1};

    void generate() {
        Var x("x"), bx("bx"), tx("tx"), txx("txx"), xi("xi");
        RDom j(0, VERTICES, "j");
        Func bit("bit"), slope("slope");
        Expr px, py, vjx, vjy, vkx, vky;

        px = points(x, 0);
        py = points(x, 1); 

        vjx = vertices(x, 0);
        vjy = vertices(x, 1);
        vkx = vertices(x + 1, 0);
        vky = vertices(x + 1, 1);

        slope(x) = (vkx - vjx) / (vky - vjy);

        vjx = vertices(j, 0);
        vjy = vertices(j, 1);
        vkx = vertices(j + 1, 0); 
        vky = vertices(j + 1, 1);

        bit(x) = 0;
        bit(x) += select( ((vjy > py) != (vky > py)) && (px < slope(j) * (py - vjy) + vjx), 1
                              , 0
                              );

        bitmap(x) = bit(x) & 1; 
       

        assert(get_target().has_gpu_feature());

        //Schedule for the gpu
        const int block_size_x=128;
        const int tile_size_x=4; 

        slope.compute_root();   
        slope.gpu_tile(x, bx, tx, 32);

        points.dim(0).set_stride(2);
        points.dim(0).set_bounds(0, SIZE);
        points.dim(1).set_stride(1);
        points.dim(1).set_bounds(0, 2);

        bitmap.dim(0).set_stride(1);
        bitmap.dim(0).set_bounds(0, SIZE); 

        vertices.dim(0).set_stride(2);
        vertices.dim(0).set_bounds(0, VERTICES+1);
        vertices.dim(1).set_stride(1);
        vertices.dim(1).set_bounds(0, 2); 
    }


};

HALIDE_REGISTER_GENERATOR(Pnpoly, pnpoly_halide);  

```
I have 3 schedules, of which are two that are working, and the third that isn't working. They are here, with some comments with what they are supposed to be doing.

```C++
if(schedule == 0)
        {
            //This is the idea we want, we let each thread calculate a thread, but with reduction variable j, we want the 
            // tiles be calulated in the lower loop of the reduction variables. But the threads of a warp now access the memory
            // with a loop stride of 4, we would like this to be 1.
            bitmap.split(x, bx, tx, block_size_x*tile_size_x)
                .split(tx, tx, xi, tile_size_x)
                // .unroll(xi) 
                .gpu(bx, tx)
                ;

            bit.store_in(MemoryType::Register)
                .compute_at(bitmap, tx)
                .split(x, tx, xi, tile_size_x) 
                // .unroll(xi) 

                .update()
                .split(x, tx, xi, tile_size_x)
                .reorder(xi, j.x, tx)
                // .unroll(xi)
                ;
        } else if(schedule == 1){
            //This schedule does the same as above, but with a loop stride 1 as we wanted. BUT. 
            //The produced openCL kernel produces block_size_x*tile_size=512 "bit"s per
            //thread, but we only need tile_size_x=4 "bits".
            //Also there are barriers, which aren't needed.
            bitmap.split(x, bx, tx, block_size_x*tile_size_x)
                .split(tx, xi, tx, block_size_x)
                .reorder(xi, tx)
                // .unroll(xi)
                .gpu(bx, tx);

            bit.store_in(MemoryType::Register)
                .compute_at(bitmap, bx)
                .split(x, xi, tx, block_size_x)
                .reorder(xi, tx)
                // .unroll(xi)
                .gpu_threads(tx)

                .update()
                .split(x, xi, tx, block_size_x)
                .reorder(xi, j.x, tx)
                // .unroll(xi)
                .gpu_threads(tx) 
                ;
        } else  if(schedule == 2) {
        //This schedule is trying to have the coalesced access for the threads, thus a loop stride of 1 for threads tx
        //, whilst still able to reorder j.x and compute at the thread level. But it fails when executing with:
        //>> Error: Input buffer points is accessed at 20000126, which is beyond the max (19999999) in dimension 0
        //Looking at the generated bitmap loop nest, it doesn't consider the tx we split in "bit" as GPU thread anymore.
            bitmap.split(x, bx, tx, block_size_x*tile_size_x)
                .split(tx, xi, tx, block_size_x)
                .reorder(xi, tx)
                .gpu(bx, tx);

            bit.store_in(MemoryType::Register)
                .compute_at(bitmap, tx)
                .split(x, xi, tx, block_size_x)
                .reorder(xi, tx)
                // .unroll(xi)
                //We could also not assign tx to threads again. It will give in error in that case
                // .gpu_threads(tx)

                .update()
                .split(x, xi, tx, block_size_x)
                .reorder(xi, j.x, tx)
                // .unroll(xi)
                // .gpu_threads(tx) 
                ;
        } 
```

So essentially, I want to get the following loopnest:

```
consume slope:
  produce bitmap:
    gpu_block x.bx<Default_GPU>:
      produce bit:
        gpu_thread x.tx in [0, 127]<Default_GPU>:
          for x.xi in [0, 3]:
            bit(...) = ...
        gpu_thread x.tx in [0, 127]<Default_GPU>:
          for j in [0, 599]:
            for x.xi in [0, 3]:
              bit(...) = ...
      consume bit:
        gpu_thread x.tx.tx in [0, 127]<Default_GPU>:
          for x.tx.xi in [0, 3]:
            bitmap(...) = ...
```
But where variable `x.tx` has stride 1, and `x.xi` has stride 128. 

Schedule one has this loop nest, but has stride 4 for `x.tx`.
Schedule two does do this, but it can only calculate `bit` at level `bx`, which produces extra storage for `bit` and also produces barriers (when computed with the opencl backend) which are not needed. Schedule three tries to do this, but it just doesn't work, producing an error when executed, and the produced loop nest is completely wrong. 

Is there a way to produce the above loop nest, but with the stride as indicated? Or is this not expressible in the Halide language?

(The reason for this stride, is twofold: 1. it matches the original code 2. I believe it would lead to better-coalesced memory access. Although honestly, I'm unsure if it would actually improve performance).

I've attached a complete example, which generates some input code, and which can run and benchmark the original CUDA code and the halide code. In the `Makefile` the environment variable `CUDA_SDK` should point to where CUDA is installed, and `HALIDEDIR` to the halide install directory.  Then you can run `make bench` which should make everything and benchmark the code. (I'm working on ubuntu)
[SimpleHalide.zip](https://github.com/halide/Halide/files/5209558/SimpleHalide.zip)

I was unsure on how to make this problem any more simple as it is, and if this is the wrong place to ask this, please let me know. Thank you for your time.

**Comment by abadams** [comment]
On my machine there are lots of schedules for this that hit about 20ms (the same speed as the reference). The one that produces the loop nest you want is a little counterintuitive because it requires vectorizing an outer loop. In the cuda backend it hits 16.8ms for me, but in the opencl backend it's at 20ms:

```
        const int block_size_x=64;
        const int tile_size_x=8;

            bitmap.split(x, bx, tx, block_size_x*tile_size_x)
                .split(tx, xi, tx, block_size_x)
                .reorder(xi, tx, bx)
                .gpu(bx, tx)
                .vectorize(xi);
```

I've inlined `bit`, which makes a += loop that handles a single pixel inside the loop over xi, I've vectorized that loop, which is outside bit's loop over j. This turns all of the inner computations in the += loop into computations on vectors. These vectors get unrolled because cuda has limited simd support, but the effect is the loop nest you wanted.

**Comment by sakehl** [comment]
Hi Adam,

Thanks for looking into it. Looking at the code your schedule produces, this is indeed exactly matching what I was looking for. Thank you! Although, to be honest it is a bit counter intuitive to use vectorize for this.

On a side note, on my machine (Quadro M1200) schedule 0 still is the fastest (152 ms) (the opencl version, cuda is 216 ms). Your schedule takes about 182 ms for both opencl and cuda. Whilst the reference implementation is 153 ms. Which just shows that optimization differ for each machine.

Anyway, thanks again, and for me this issues is closed.
