### ISSUE TITLE
Realization of multiple outputs fails when a Func with more inputs is used.

### ISSUE THREAD

**Issue by alister-chowdhury** [halide/Halide#5327]
Hi there,

So while playing with realizing multiple Funcs at once, I discovered that if I had a Func with additional inputs the Pipeline would crash.
Weirdly, when the Func is used on its own, it works perfectly fine.
I won't pretend to be overly familiar with Halide, but this seems like a bug.

I've managed to reduce this to a (hopefully) simple reproduction case:
```c++

#include <iostream>
#include <Halide.h>


int main(void) {


    Halide::Var x, y, c;
    Halide::Var dx, dy;

    Halide::Func f, g, w;
    Halide::Func w0;

    f(x, y, c) = 0.0f;
    g(x, y, c) = 1.0f;
    w0(x, y, c, dx, dy) = f(x+dx, y+dy, c) - g(dx, dy, c);


    Halide::RDom roi(-1, 1, -1, 1);
    w(x, y, c) = 0.0f;
    w(x, y, c) += w0(x, y, c, roi.x, roi.y);


    Halide::Buffer<float> f_im(100, 100, 3);
    Halide::Buffer<float> g_im(100, 100, 3);
    Halide::Buffer<float> w_im(100, 100, 3);



    #define TEST_CASE 0

    // This will work
    #if TEST_CASE == 0
        Halide::Pipeline({f, g}).realize({f_im, g_im});

    // This will work
    #elif TEST_CASE == 1
        Halide::Pipeline({w}).realize({w_im});

    // This will not
    #else:
        Halide::Pipeline({f, g, w}).realize({f_im, g_im, w_im});
    #endif


    std::cout << "Success!\n";

}
```

I'm using Halide 10, on Windows 10, with VS2019.

When I set `HL_DEBUG_CODEGEN=2` I get the following:
```
... normal gubbins ...
Calling jitted function
Back from jitted function. Exit status was -4
User error triggered at D:\manual_build\Halide\src\Pipeline.cpp:896
```
Possibly a separate bug is that the actual user error messages never seem to print out either, but this is general area this bubbles up from:

```c++
    void report_if_error(int exit_status) {
        // Only report the errors if no custom error handler was installed
        if (exit_status && !custom_error_handler) {
            std::string output = error_buffer.str();
            if (output.empty()) {
                output = ("The pipeline returned exit status " +
                          std::to_string(exit_status) +
                          " but halide_error was never called.\n");
            }
            halide_runtime_error << output;
            error_buffer.end = 0;
        }
    }
```

If you need any more info please let me know.

**Comment by zvookin** [comment]
This code uses intermediate outputs as intermediate buffers in the
computation of another output. The bounds of outputs are fixed by what is
passed in at call time and and Halide cannot change them. In this case, the
are not big enough. The f and g outputs need to be bigger than w to provide
the bounds required to compute w.

Halide’s bounds inference mechanism could potentially tell you the required
bounds, though I’m not sure it handles output dependences like this.

The bug here is that the error message us getting lost. I doubt the program
crashes.

-Z-

**Comment by alister-chowdhury** [comment]
@zvookin 
Ahhhhh I see.

Yes, if I set the RDom to 0, 0, 0, 0 it all works happily.

And if I do:
```c++

    Halide::Func f0;
    Halide::Func g0;
    f0(x, y, c) = f(x, y, c);
    g0(x, y, c) = g(x, y, c);

```

As a redirect, it also seems to not crash.

**Comment by alexreinking** [comment]
> Possibly a separate bug is that the actual user error messages never seem to print out either, but this is general area this bubbles up from:

This is not a bug. This is just how Windows works. Don't allow your programs to throw uncaught exceptions. See the discussion here: #5210

**Comment by alister-chowdhury** [comment]
Ah!

Thank you clearing that up for me.
No bug here, just my lack of familiarity with  both Halide and Windows exceptions.
