### ISSUE TITLE
Publish on PIP/Conda

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#5360]
I'm splitting this out from the generic #4660 issue. We should investigate packaging Halide and especially the Python bindings for either or both of PIP and Conda.

Ideally these would be cross-platform wheels for Windows, macOS, and Linux (via the [manylinux](https://github.com/pypa/manylinux) images). We probably only need to support Python 3.8+, which is good since #4876 affects the autoschedulers on Windows.

**Comment by dragly** [comment]
@alexreinking has there been any concrete progress or made any plans regarding this issue? I am interested in contributing to solving this issue for PIP. I am starting to rely more on the Python bindings for Halide, and having official packages available would simplify a few common hurdles I have currently (like distributing the Python extension files with scripts).

**Comment by BachiLi** [comment]
@dragly I was supposed to work on this, but haven't got the time to do this at all. I'm happy to work with you and Alex to make this happen.

**Comment by steven-johnson** [comment]
> I am interested in contributing to solving this issue for PIP.

We'd love to have contributions in this regard.

**Comment by tyoc213** [comment]
I think I have one option that can serve to pip and conda, can make initial PR or just say what is the option

**Comment by dragly** [comment]
Great! Did you have any particular solutions in mind? I was thinking of looking into using `skbuild` (scikit-build) in setup.py to invoke CMake, but am still a bit unsure if that should be a secondary step after building Halide first or if that should just build the entirety of Halide with Python bindings in one go.

> I think I have one option that can serve to pip and conda, can make initial PR or just say what is the option

@tyoc213: Do you mean like a complete solution or an option like a CMake option? In any case, I am very interested in hearing your ideas or seeing your PR. It is just awesome if you have this solved already :)

**Comment by tyoc213** [comment]
Well not solved! only have a suguestion also pointed it here https://github.com/halide/Halide/issues/4660#issuecomment-770593470 which is [fastrelase](https://github.com/fastai/fastrelease) which will work for conda and pip.

**Comment by alexreinking** [comment]
Fixed by #8405
