### ISSUE TITLE
Undefined symbols trying to build with nix (mainly OS X)

### ISSUE THREAD

**Issue by spease** [halide/Halide#5367]
Example:
```
Undefined symbols for architecture x86_64:
  "_LLVMInitializeAArch64AsmParser", referenced from:
      void std::__1::__call_once_proxy<std::__1::tuple<Halide::Internal::CodeGen_LLVM::initialize_llvm()::$_0&&> >(void*) in libHalide.a(CodeGen_LLVM.cpp.o)
```

Linux also produces a slew of undefined reference errors, but these seem to be much more generic. I am including llvmPackages.llvm as either a buildInput or propagatedBuildInput (makes no difference).

Thanks.

**Comment by steven-johnson** [comment]
First guess is that you have an LLVM that was built without AArch64 support. Did you build it from source? If so, specify something like `-D LLVM_TARGETS_TO_BUILD="X86;ARM;NVPTX;AArch64;Mips;PowerPC;Hexagon;WebAssembly"` when configuring CMake.
