### ISSUE TITLE
c_source generation brokend on msvc: roundf/round already linked & cannot access private member declared in class

### ISSUE THREAD

**Issue by chkone** [halide/Halide#5403]
When we generate with autoscheduled with:
`Generator.exe -o src\autoschedule\. -g Arithmetic_XXX -f Arithmetic_XXX -e schedule,c_header,c_source -p autoschedule_adams2019.dll -s Adams2019 target=host auto_schedule=true machine_params=32,16777216,40`

Version: tag: Halide 10.0.0
Platform: Windows x64
Compiler: Visual C++ /std:c++lastest
Windows SDK: 10.0.16299.0

On the head of the cpp generated we have:
```
#ifdef _WIN32
     __declspec(dllimport) float __cdecl roundf(float);
     __declspec(dllimport) double __cdecl round(double);
#else
```

Which on my context (== compiler) generate those error:
```
Arithmetic_XXX.halide_generated.cpp(16,37): error C2375: 'roundf': redefinition; different linkage
C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\ucrt\corecrt_math.h(576): message : see declaration of 'roundf'
Arithmetic_XXX.halide_generated.cpp(17,38): error C2375: 'round': redefinition; different linkage
C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\ucrt\corecrt_math.h(532): message : see declaration of 'round'
Arithmetic_XXX.halide_generated.cpp(43,41): error C2065: 'roundf': undeclared identifier
Arithmetic_XXX.halide_generated.cpp(62,50): error C2264: 'round': error in function definition or declaration; function not called
```

math.h contains only:
```
#include <corecrt_math.h>

#ifdef _USE_MATH_DEFINES
    #include <corecrt_math_defines.h>
#endif
```

If I comment the two '__declspec(dllimport)' of roundf & round I got following errors:
```
Arithmetic_XXX.halide_generated.cpp(2747,14): error C2248: 'CppVector<uint8_t,8>::elements': cannot access private member declared in class 'CppVector<uint8_t,8>'
Arithmetic_XXX.halide_generated.cpp(2814): message : see declaration of 'CppVector<uint8_t,8>::elements'
Arithmetic_XXX.halide_generated.cpp(3236): message : see declaration of 'CppVector<uint8_t,8>'
Arithmetic_XXX.halide_generated.cpp(2744): message : while compiling class template member function 'CppVector<uint8_t,8> operator >(const CppVector<float,8> &,const CppVector<float,8> &)'
Arithmetic_XXX.halide_generated.cpp(3519): message : see reference to function template instantiation 'CppVector<uint8_t,8> operator >(const CppVector<float,8> &,const CppVector<float,8> &)' being compiled
Arithmetic_XXX.halide_generated.cpp(3515): message : see reference to class template instantiation 'CppVector<float,8>' being compiled
```

Something related to friendship & private members:
On my case:
`typedef CppVector<uint8_t, Lanes> Mask;`

Do we have a work around?
Could we have more option on the cpp file generated? For example having a code we can put at the begining (define etc.), modifying the include to replace math.h with other implementation (amd, libm, ...)?

Thanks

**Comment by mugwort-rc** [comment]
Hi, I had a compile error with the same problem.

The `round` functions must be commented out if you use the `/MT` option, while the `MD` option allows to compile the line without commenting it out.

According to the MSVC documentation, if built with `/MT`, then `_MT` is defined.
https://docs.microsoft.com/ja-jp/cpp/build/reference/md-mt-ld-use-run-time-library?view=msvc-160

Therefore, it would be correct to define it as follows.

```diff
 #ifdef _WIN32
+#ifndef _MT
 __declspec(dllimport) float __cdecl roundf(float);
 __declspec(dllimport) double __cdecl round(double);
+#endif
 #else
```


And the `CppVector::elements` member needs to be modify to a public member.

```diff
-private:
+public:
     template <typename, size_t> friend class CppVector;
     ElementType elements[Lanes];
+
+private:
```

But, CodeGen_C.cpp seems to be in the process of being refactored so I'm waiting for that to be released.
https://github.com/halide/Halide/blob/master/src/CodeGen_C.cpp

**Comment by steven-johnson** [comment]
The `CppVector::elements` issue is already fixed in master.  (This fix is unlikely to be backported to the 10.0 release branch; I'm not sure if it's been backported to the 11.0 not-yet-released branch or not.)

I'll open a PR to fix the _MT issue.

**Comment by steven-johnson** [comment]
https://github.com/halide/Halide/pull/5417

**Comment by steven-johnson** [comment]
fixed

**Comment by chkone** [comment]
[Tested][Fixed]
