### ISSUE TITLE
Internal compiler error when differentiating generators with scalar parameters.

### ISSUE THREAD

**Issue by abadams** [halide/Halide#5406]
Make a generator with a scalar input (the example generator in test/generators works) and try to take the derivative

```
abadams@anadams-work:~/projects/Halide_autodiff_generator_scalar_bug
$ make bin/example.generator
make: 'bin/example.generator' is up to date.

abadams@anadams-work:~/projects/Halide_autodiff_generator_scalar_bug
$ bin/example.generator -g example -o . target=host -d 1
Internal Error at /home/abadams/projects/Halide_autodiff_generator_scalar_bug/src/Generator.cpp:1544
Condition failed: input->parameters_.size() == input->funcs_.size():
Aborted (core dumped)
```

I imagine the issue is that in the reverse pipeline that scalar input needs to turn into a scalar output, which could be done as a zero-dim buffer but isn't. We at least need an error message here, but ideally we'd turn them into zero-dim buffer outputs.

Not sure who did the autodiff support for generators. Maybe @BachiLi ?

**Comment by steven-johnson** [comment]
Nah, almost certainly that was me. I'll take a look.

**Comment by clutzweiler** [comment]
Same as #4599.
