### ISSUE TITLE
Compile error occurs because no `operator^` in halide_generated.cpp

### ISSUE THREAD

**Issue by mugwort-rc** [halide/Halide#5415]
Using Halide-10.0.0-x86-64-linux-db901f7f7084025abc3cbb9d17b0f2d3f1745900.tar.gz

I was able to compile it by defining some `operator^` in CppVector.

**Comment by steven-johnson** [comment]
https://github.com/halide/Halide/pull/5416

**Comment by steven-johnson** [comment]
fixed
