### ISSUE TITLE
GPU does not receive input data

### ISSUE THREAD

**Issue by Infinoid** [halide/Halide#5443]
We have an app which allocates a Halide Buffer, gets a pointer to it with `buf.begin()`, and uses `memcpy` to copy values in from a data source.  Then we pass that Buffer to a Halide-generated function.  If the Halide function uses a CUDA schedule, it seems to receive only zeroes in that buffer.  If I schedule it for CPU, it seems to work correctly.

If I use syntax like `buffer(0)` to print any value in the buffer before calling the Halide-generated function, both the CUDA and CPU versions work correctly.

Does calling the accessor method set a dirty flag or something that's required for copying data to the GPU?

If relevant, I am using Debian Bullseye (testing) packages for clang (10.0.1-6), nvidia driver (450.66-1), and cuda (10.2.89-5).

**Comment by Infinoid** [comment]
Here is a reproducer: https://gist.github.com/Infinoid/d4260acda7a7e391c6affba704f13e85

It JIT-compiles equivalent CPU and CUDA algorithms, calls them both with the same input, and compares the outputs.  If the print statement on line 13 is commented, the CUDA version fails.  (It seems to receive a buffer full of zeroes).  If uncommented, the CUDA version produces the same results as the CPU version.

**Comment by Infinoid** [comment]
The issue happens with AOT compilation as well.  I used JIT for this reproducer to simplify compilation.

**Comment by abadams** [comment]
Yes, it's a flag issue. If you're going to fill a buffer in that way, you need to let Halide know that it has meaningful data in it by setting the host_dirty flag. Call Buffer::set_host_dirty() after the memcpy.

**Comment by Infinoid** [comment]
Thanks.  I had assumed the Buffer would be dirty by default.  It seems to work better with the flag.
