### ISSUE TITLE
Support float16 arithmetic on ARM

### ISSUE THREAD

**Issue by dsharletg** [halide/Halide#5449]
ARM has what seems like a full set of instructions for float16, but I've been struggling to generate them from Halide: https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/intrinsics?page=11&search=f16

We should be able to generate these, float16 is a major attraction to many developers for other targets like GPUs.

**Comment by l-oneil** [comment]
Hi, is there any update on when FP16 Neon support might get pushed into release? 

If not, is this planned to be worked on? Could somebody perhaps outline what work is required to add support for this? 
I'd potentially be interested in helping here, with some guidance.

**Comment by abadams** [comment]
I don't think anyone is currently planning on working on this. We'd welcome a PR. The way to start would be with some test cases that should generate float16 instructions but don't. E.g. maybe in test/correctness/simd_op_check.cpp. Then you'd see what llvm IR Halide is emitting, then you'd check what llvm IR llvm wants (typically I do this by grepping for the instructions in llvm's test/CodeGen/AArch64 folder), and then try to bridge the gap. E.g. maybe there are intrinsics we're supposed to be calling.

**Comment by steven-johnson** [comment]
#6102 has landed -- is there more work to do, or should we consider this done?
