### ISSUE TITLE
infer_input_bounds return undesired bounds when the program depends on the input size

### ISSUE THREAD

**Issue by BachiLi** [halide/Halide#5481]
Consider the following program, which outputs 0 for both the min and max of the input bounds.
```
#include <Halide.h>
using namespace Halide;
int main(int argc, char *argv[]) {
    ImageParam in(Int(32), 1);
    Var x;
    Func f;
    f(x) = in(min(x + 1, in.width() - 1));
    f.infer_input_bounds({42});
    Buffer<int> in_buf = in.get();
    std::cerr << "in_buf.dim(0).min():" << in_buf.dim(0).min() << std::endl; // returns 0, expects 1
    std::cerr << "in_buf.dim(0).max():" << in_buf.dim(0).max() << std::endl; // returns 0, expects 41
}
```

It seems that what happens here is that `infer_input_bounds` uses an "initial shape" of size 0 to execute the bounds query pass (https://github.com/halide/Halide/blob/59bbc4d577b75c294bc696ca45db88544fc3bfc0/src/Pipeline.cpp#L1212). During the first bounds query, `in.width()` returns 0, and `in` is accessed at -1, thus the bounds query determines that `in` only require size 1, and `in.width()` subsequently returns 1, and the fixed-point bounds query converges.

Any idea how to fix this?

**Comment by abadams** [comment]
Are those bounds really incorrect though? There's nothing in the program to indicate what the width of the input should be, and 1 works fine.

**Comment by BachiLi** [comment]
You are right. I guess then my question is: how do I tell the bounds inference that I want the input and output to have the same size?
