### ISSUE TITLE
opencl error: Cannot take address of function 'sqrt_f64'

### ISSUE THREAD

**Issue by Infinoid** [halide/Halide#5485]
Trying to calculate a 64 bit square root with opencl results in this error at runtime.

Here is a small test program:

```c++
#include <Halide.h>

using namespace Halide;
using namespace Halide::ConciseCasts;

#define N 256
int main() {
    Var x{"x"}, xi{"xi"}, xo{"xo"};
    Func thing{"thing"};
    thing(x) = sqrt(f64(x));

    thing.compute_root().gpu_tile(x, xo, xi, 64);

    Target tgt("host-opencl");
    thing.compile_jit(tgt);
    auto out = thing.realize(N);
}
```

Here's what I get when I run it:

```
$ clang++-10 -O3 -Wall -g -o test test.cpp -lHalide -lm -lpthread
$ ./test
terminate called after throwing an instance of 'Halide::RuntimeError'
  what():  Error: CL: clBuildProgram failed: <Unknown error>
Build Log:
ptxas fatal   : Cannot take address of function 'sqrt_f64' 
```

If I change `f64` to `f32`, it runs fine.  If I change `opencl` to `cuda`, it runs fine.

I am running on Debian bullseye (testing), with an nvidia GPU.  Here are some package versions:
```
||/ Name                    Version      Architecture Description
+++-=======================-============-============-==================================================================
ii  clang-10                1:10.0.1-8   amd64        C, C++ and Objective-C compiler
ii  llvm-10-dev             1:10.0.1-8   amd64        Modular compiler and toolchain technologies, libraries and headers
ii  nvidia-opencl-common    450.80.02-1  amd64        NVIDIA OpenCL driver - common files
ii  nvidia-opencl-dev:amd64 11.0.3-2     amd64        NVIDIA OpenCL development files
```

**Comment by steven-johnson** [comment]
I think you have to add `cldoubles` to the target string if you want to use 64-bit floats in opencl.

**Comment by Infinoid** [comment]
Thanks, the target string `host-opencl-cl_doubles` worked.

Is there a good way to get a clearer error message for this?  This seems like something that could be rejected at the code generation stage.

**Comment by steven-johnson** [comment]
> Is there a good way to get a clearer error message for this? This seems like something that could be rejected at the code generation stage.

Probably :-) A PR do to so would likely be welcomed.

**Comment by Infinoid** [comment]
#5610 added this error message.  Thanks @xndcn!
