### ISSUE TITLE
Visual Studio - Halide out of box experience small build instruction suggestion

### ISSUE THREAD

**Issue by ZoroDerVonCodier** [halide/Halide#5511]
As a first time user of Halide, I have found an easy trap to fall into that you might want to note in the build instructions for Visual Studio users.

When building a sample, by copying the sample code into a fresh 'DEBUG' build of a C++ console application, the console applications default debug settings must be changed when using the Release version of the Halide.dll:

1.) C/C++|Code Generation|Runtime Library: change from Multi-threaded Debug DLL (/MDd) to Multi-threaded DLL (/MD)
2.) C/C++|PreProcessor|Preprocessor Definitions: change _DEBUG to NDEBUG

Without these changes, such a sample crashes with an 'Access violation' within the Halide.dll.

**Comment by alexreinking** [comment]
This is a standard issue in Visual Studio -- you can't mix debug/release runtimes. Our release binaries are (correctly) compiled with /MD and our debug binaries are compiled with /MDd.

**Comment by ZoroDerVonCodier** [comment]
That is what I figured and was able to quickly get all of the samples running after getting that straightened out.  A note pointing this out on the VC portion of the build instructions may help other first time users stay on the right path quicker.  Just a minor suggestion.  Great work you all are doing.
