### ISSUE TITLE
Hexagon - LLVM "Calling a function with a bad signature!" failed: Error on Vectorize

### ISSUE THREAD

**Issue by AbyShk95** [halide/Halide#5516]
@pranavb-ca 

Vectorization seems to be working fine without .hexagon() directive.
However, the following error is presented upon the usage of .hexagon()

**Error**:
```
nn_resize: /local/mnt/workspace/bots/hexbotmaster_aus-05/halide-22/src/llvm/lib/IR/Instructions.cpp:315: void llvm::CallInst::init(llvm::FunctionType *, llvm::Value *, ArrayRef<llvm::Value *>, ArrayRef<OperandBundleDef>, const llvm::Twine &): Assertion `(i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!"' failed.
1164 Aborted                 (core dumped) ./nn_resize -o . -g nn_resize -f nn_resize target=arm-64-android-hvx_128

```
Following is the code used in the generator:

**Code**:
```
#include "Halide.h"

using namespace Halide;

class Resize : public Halide::Generator<Resize> {
public:
    Input<Buffer<uint8_t>> input{"input", 2};
    Input<float> scale_factor_x{"scale_factor_x"};
    Input<float> scale_factor_y{"scale_factor_y"};
    Output<Buffer<uint8_t>> output{"output", 2};
    Var x, y;

    void generate() {
        Expr x_coord = cast<int> (x / scale_factor_x);
        Expr y_coord = cast<int> (y / scale_factor_y);
        output(x, y) = input(x_coord, y_coord);
        }

    void schedule() {
        Var xi, yi;
        int vector_size = 128;
        output
            .hexagon()
            .align_storage(x, vector_size)
            .vectorize(x, vector_size, TailStrategy::RoundUp)
            .parallel(y, 4);
      }
};
HALIDE_REGISTER_GENERATOR(Resize, nn_resize);

```

- There is no issue when I comment .hexagon() in this code. 

- Using Qualcomm Hexagon SDK 3.5.1, Halide 2.2.03

Any suggestions would be really helpful!

Thank you...

**Comment by pranavb-ca** [comment]
Hi @AbyShk95  - what is the Snapdragon version you are using?

**Comment by AbyShk95** [comment]
Snapdragon 865

**Comment by dpalermo** [comment]
The problem is that you are trying to vectorize floating point which is not supported on the Hexagon DSP.  Hexagon only supports integer operations on vectors...which can also be used to perform fixed point ops on vectors.  From the look of your code, you are scaling indices by a given scale factor...which would imply a fairly small range (the image size), so I think fixed point should work just fine.  You can also get rid of the vector division (also slow) by instead multiplying by the reciprocal of the scale factor (in fixed point).  If you need any further details, just let us know here or on gitter.

**Comment by AbyShk95** [comment]
cast<int> doesn't help get rid of floating pt? Also is there any example for use of fixed point? @dpalermo

**Comment by aankit-ca** [comment]
Not really x / scale_factor_x calculation would still be in floating point. As @dpalermo said your scale factor can be approximated by a multiply and a shift. For eg; say you have a scale_factor 2.3

2.3 ~ 1024/445

        Expr x_coord = cast<int> ((x * 445) >> 10);

**Comment by AbyShk95** [comment]
Thank you! this helps...!

**Comment by dpalermo** [comment]
The cast to int will convert the result of the floating point expression into an int, but the operation will still be floating point.

A good example that uses fixed point is in Halide/apps/camera_pipe (search for 'fixed point' in camera_pipe_generator.cpp). 

If you have never used fixed point before, you first need to decide how many fraction bits you want.  Then multiply your float by 2^numbits and cast it to an int to turn it into fixed point...e.g. 8bits -> (int)(factor * 256).  To convert a fixed point value back to int, just divide by the same factor (e.g. fixpt / 256) or shift right to eliminate the faction (e.g. fixpt >> 8).  ...or fixed point back to a float, just divide by the factor as float (e.g. fixpt / 256.0f)

**Comment by dpalermo** [comment]
FYI, @aankit-ca 's scale factor example can also be viewed as performing the operation in 10-bit fixed point and immediately converting the result back to an int.

**Comment by AbyShk95** [comment]
Thank you so much @dpalermo
