### ISSUE TITLE
Not able to generate blur example for Hexagon DSP

### ISSUE THREAD

**Issue by mikbjorklund** [halide/Halide#5523]
It is not possible to enable the hexagon scheduling directive, (include the hvx target feature in the target.)

```console
~/Halide/apps/blur (master) $ HL_TARGET=arm-64-android-hvx_128 make
bin/host/halide_blur.generator -g halide_blur -e static_library,h,registration,stmt,assembly -o bin/arm-64-android-hvx_128 target=arm-64-android-hvx_128
free(): invalid pointer
Makefile:13: recipe for target 'bin/arm-64-android-hvx_128/halide_blur.a' failed
make: *** [bin/arm-64-android-hvx_128/halide_blur.a] Segmentation fault (core dumped)
```

**Comment by steven-johnson** [comment]
Tagging @pranavb-ca for initial triage

**Comment by pranavb-ca** [comment]
Thanks for bringing to my notice @steven-johnson. Will look into this this afternoon.

**Comment by pranavb-ca** [comment]
I coudln't reproduce this immediately, however @aankit-ca will dig deeper to double-check. BTW, I did have to add `CXX-arm-64-android-hvx_128` and `LDFLAGS-arm-64-android-hvx_128` to `apps/support/Makefile.inc`.

**Comment by dsharletg** [comment]
Hopefully HL_TARGET=arm-64-android-hvx_128 make bin/arm-64-android/... should work? If not we should fix that so it does. Adding a CXX-* and LDFLAGS-* for every combination of optional flags doesn't scale (what about hvx_128-profile? or profile-hvx_128? and so on...)

**Comment by aankit-ca** [comment]
Even I'm not able to reproduce the error and faced the same issue as @pranavb-ca .

HL_TARGET=arm-64-android-hvx_128 make bin/arm-64-android/test
can work with this change: https://github.com/halide/Halide/pull/5536

**Comment by mikbjorklund** [comment]
The actual reason why I raised this ticket is that I am not able to generate the halide_blur lib for hvx_128:
~/Halide/apps/blur (master) $ g++ -O3 -std=c++11 -I /home/mbjorklund/Halide/distrib/include/ -I /home/mbjorklund/Halide/distrib/tools/  -Wall -Werror -Wno-unused-function -Wcast-qual -Wignored-qualifiers -Wno-comment -Wsign-compare -Wno-unknown-warning-option -Wno-psabi -fno-rtti halide_blur_generator.cpp /home/mbjorklund/Halide/distrib/tools/GenGen.cpp -o bin/host/halide_blur.generator /home/mbjorklund/Halide/distrib/lib/libHalide.a  -ldl -lpthread -lz -ltinfo

bin/host/halide_blur.generator -g halide_blur -e static_library,h,registration,stmt,assembly -o bin/arm-64-android target=arm-64-android-hvx_128
free(): invalid pointer
Segmentation fault (core dumped)

Since the blur example is made to demonstrate that halide can run on the Hexagon DSP (according to the README) I think that arm-64-android-hvx_128 should be the default target, not arm-64-android.

The same error exists also in `Halide/apps/hexagon_benchmarks`, default is not arm-64-android-hvx_128, and when changing to target arm-64-android-hvx_128, I get the same generator crash, for example:
~/Halide/apps/hexagon_benchmarks (master) $ bin/host/conv3x3.generator -g conv3x3 -o bin/arm-64-android-hvx_128 -e object,c_header -f conv3x3a16 target=arm-64-android-hvx_128
free(): invalid pointer
Segmentation fault (core dumped)

**Comment by aankit-ca** [comment]
@mikbjorklund I tried building halide with both g++ and clang but could not reproduce your error. 
clang version 11.0.0
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

**Comment by mikbjorklund** [comment]
> @mikbjorklund I tried building halide with both g++ and clang but could not reproduce your error.
> clang version 11.0.0
> g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

clang version 10.0.0
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

I downloaded a prebuilt `clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04`

**Comment by aankit-ca** [comment]
@mikbjorklund I think the toolchain could be the only source of difference. Can you try building both Halide and LLVM with clang+llvm-11.0.0-...?

**Comment by mikbjorklund** [comment]
@aankit-ca I managed to run the blur example, I built clang & lllvm 11.0.0 from source and then it worked.
Thank you for the support. You could consider updating the README.md that calng 11.0.0 is requireed.

Also, I can not generate libs with the prebuilt halide 10.0.0 distro: 
`https://github.com/halide/Halide/releases/download/v10.0.0/Halide-10.0.0-x86-64-linux-db901f7f7084025abc3cbb9d17b0f2d3f1745900.tar.gz`

This is the error I get:
`-> ./halide_blur.generator -g halide_blur -e o,static_library,h -o arm64-v8a/ target=arm-64-android-hvx_128-debug
MinCmpXchgSizeInBits not yet supported for LL/SC architectures.
UNREACHABLE executed at /home/halidenightly/build_bot/worker/x86-64-linux-1000-cmake/llvm-project/llvm/lib/CodeGen/AtomicExpandPass.cpp:574!`

I need to run with a halide distro that I build from source (c1885fc71) with clang 11.0.0.
