### ISSUE TITLE
define_extern() should make it easy to match Target::UserContext

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#554]
When coding define_extern() in Generator, you currently have to do manual work to match the sense of Target::UserContext being used by the enclosing Generator (i.e.: you normally want to match the sense and pass the user context along). There should be a way to make it easy to do the right thing and hard to do the wrong thing.

**Comment by steven-johnson** [comment]
Adding another spin to this issue: if the define_extern() is to a hand-coded piece of C/C++ (ie not from Halide), then it's really hard to get this right; you have to explicitly check for Target::UserContext and build differently depending on whether it is set or not. 

Case in point: code I just found that doesn't use UserContext in its externs, because its normally used in an environment that doesn't care; trying to repurpose it into an environment that *uses* UserContext kills us when an extern needs to call a runtime function (eg halide_error):

    extern "C" int my_extern_func(buffer_t* in, buffer_t* out) {
        if (something_bad()) { halide_error(NULL, "Failed."); return -1; }
        ...
    }

If you are running in an environment where halide_error() really *needs* that user_context parameter, well, you're out of luck.

It doesn't appear likely that we're going to fix this anytime soon; AFAICT the only really robust way of solving this is to require that every Generator (and Generator-referenced extern) always have a user context, period, but there's too much resistance to that from an API point of view for me to push against.

(I may be able to address my short-term needs by giving up on using user-context for this and just using a thread-local pointer. Yuck.)

**Comment by steven-johnson** [comment]
Update to previous comment: using a thread-local is problematic as well, since halide runtime functions may be called from arbitrary threads in the halide thread pool, which won't have the right thread-local value. I going to see if I can make this work by overriding select portions of the halide threadpool, but it might take some additional surgery to make it efficient. Double yuck.

**Comment by abadams** [comment]
It's a hard sell to turn user_context on in the target for the codebase
you're working on? Leaving it on as a matter of local convention seems like
it would solve this issue.

**Comment by steven-johnson** [comment]
Leaving it on as a local convention would indeed solve the issue, but gives me pause: in this specific case, it implies that we'd turn it on by default for ~all of the Halide code inside Google, but leave it off by default for Halide outside Google, and I'm reluctant to promote a different standard inside of Google (vs the public world of Halide).

**Comment by dsharletg** [comment]
As a heavy user of extern stages and user contexts - I think this is currently not that bad. It makes sense for `define_extern` to have to pass the user context if it is necessary with `user_context_value()`.
