### ISSUE TITLE
Halide binary release

### ISSUE THREAD

**Issue by rodrigob** [halide/Halide#556]
This is probably a hopeless question but, when using the latest (stable) binary Halide build on a work station without root access nor recent llvm, I get

```
../bin/libHalide.so: undefined reference to `posix_spawn@GLIBC_2.15'
../bin/libHalide.so: undefined reference to `memcpy@GLIBC_2.14
```

`locate libc-2` returns `/lib/x86_64-linux-gnu/libc-2.13.so`.

It is there any hope of having Halide run on these machines ? 
(it works no problem on my laptop, where I have root access to install recent llvm).

**Comment by tamarnav** [comment]
Hi,
I have downloaded the latest halide release for linux as well as the llvm binar release an set the LLVM_CONFIG and Clang.
When trying to compile the tutorials I get the following errors:
![image](https://cloud.githubusercontent.com/assets/5797280/8318625/40edb8f8-19bb-11e5-815e-4edde9f9b8d8.png)

Any idea what am I missing?
