### ISSUE TITLE
Windows Makefile error message misleading

### ISSUE THREAD

**Issue by paulrdelg** [halide/Halide#5579]
Hello,

I think the line 20 of the Makefile should be spaces to be consistent with the other indentation styles. I know my example show I am running MINGW and I get a further issue, but I wouldn't see that error message initially without attempting it with MINGW.

The error message I received was:
`Makefile:20: *** recipe commences before first target.  Stop.`

The error message I should see is:
`Makefile:20: *** Halide no longer supports the MinGW environment..  Stop.`

My system:
OS: Win10
terminal: MINGW

Also, why would Windows/MINGW not be supported? It's really not MINGW that is not supported, its Windows in general no? The environment variable is set by Windows, if I understand correctly.

Thanks in advance.

**Comment by abadams** [comment]
To answer your second question: Windows is supported, via the cmake build. The makefile doesn't support it. mingw as an environment required lots of weird hacks in corner cases for things like symbol resolution when jit-compiling, and I was the only one using it (to the best of our knowledge), so we cut support for it.
