### ISSUE TITLE
Code simplification dimension agnotic

### ISSUE THREAD

**Issue by chkone** [halide/Halide#5599]
Is it possible to implement a "add" function agnostic to dimension without nested if/else?
```
UInt32 const uDim = // define the dimension of the output

Halide::Func A = // can be dim{ 0[Scalar], 1, 2, 3 or 4 }
Halide::Func B = // can be dim{ 0[Scalar], 1, 2, 3 or 4 }

Halide::Func C{  "Add" };

Halide::Var x{ "x" }, y{ "y" }, z{ "z" }, w{ "w" };
if ( uDim == 0 )
{
	C() = A() + B();
}
else if ( uDim == 1 )
{
	Int32 const uDimA = A.dimensions();
	Int32 const uDimB = B.dimensions();
	if ( uDimA == 0 )
	{
		if ( uDimB == 0 )
		{
			C( x ) = A() + B();
		}
		else if ( uDimB == 1 )
		{
			C( x ) = A() + B( x );
		}
		else if ( uDimB == 2 )
		{
			C( x ) = A() + B( x, 0 );
		}
		else if ( uDimB == 3 )
		{
			C( x ) = A() + B( x, 0, 0 );
		}
		else if ( uDimA == 4 )
		{
			C( x ) = A() + B( x, 0, 0, 0 );
		}
		else
		{
			assert( false );
		}
	}
	else if ( uDimA == 1 )
	{
		// ...
	}
	else if ( uDimA == 2 )
	{
		// ...
	}
	else if ( uDimA == 3 )
	{
		// ...
	}
	else if ( uDimA == 4 )
	{
		// ...
	}
	else
	{
		assert( false );
	}
}
else if ( uDim == 2 )
{
	// ...
}
else if ( uDim == 3 )
{
	// ...
}
else if ( uDim == 4 )
{
	// ...
}
else
{
	assert( false );
}
```

I checked the Halide::_ but wasn't able to find a good way to use it:
Expected usage:
`C( x ) = A( Halide::_ ) + B( Halide::_ );`

The idea is to implement an agnotic Add like numpy:
y = a + ScalarConst; => y( x ) = a( x ) + Expr( ScalarConst );
y = a + ScalarConst; => y( x, y ) = a( x, y ) + Expr( ScalarConst );
// ...
y = a + Vector; => y( x ) = a( x ) + Vector( x );
y = a + ScalarConst; => y( x, y ) = a( x, y ) + Vector( x );
// ...
y = a + Matrix; => y( x ) = a( x ) + Matrix( x, 0 );
y = a + ScalarConst; => y( x, y ) = a( x, y ) + Matrix( x, y );
// ...

**Comment by abadams** [comment]
I'm a bit confused by your example, because C(x) = A() + B(x, y) has an undefined variable in the RHS, and C(x) = A() + B() has a pointless variable on the LHS. What's wrong with: ```C(_) = A(_) + B(_)``` ?

**Comment by chkone** [comment]
Sorry wrong copy paste here the full version!
https://gist.github.com/chkone/f4efb852eaacbead82b5a17fec66841a

**Comment by abadams** [comment]
You can construct argument lists as  std::vectors of Expr objects, so when I want to be very generic I just do that. How about something like:
```
vector<Expr> a_args;
for (Var v : A.args()) a_args.push_back(v);
vector<Expr> b_args = a_args;
while (b_args.size() > B.dimensions()) b_args.pop_back();
while (b_args.size() < B.dimensions()) b_args.emplace_back(0);
vector<Expr> c_args = a_args;
while (c_args.size() > C.dimensions()) c_args.pop_back();
while (c_args.size() < C.dimensions()) c_args.emplace_back(0);
A(a_args) = B(b_args) + C(c_args);
```

**Comment by chkone** [comment]
In this case:
`C(x) = A() + B()`
The output is a 1D Buffer and the inputs are 2 scalars. Which stand for:
```
for ( int i = 0; i < size; ++i )
    C[ i ] = A + B;
```

"What's wrong with: `C(_) = A(_) + B(_)` ?"
Test case when I have a crash:
```
Var x{ "x" }, y{ "y" };
Func A, B;
A( x, y ) = Expr( 2.0f );
B( x, y ) = Expr( 3.0f );
Halide::Func C;
C( _ ) = A( _ ) + B( _ );

// Want to have the add working with:
// * A( x ) = Expr( 2.0f ); B() = Expr( 3.0f );
// * A( x,  y ) = Expr( 2.0f ); B() = Expr( 3.0f );
// ...

constexpr int uBufferSize = 8;
std::vector<float> oBuffer( uBufferSize*uBufferSize, 1321 );
Halide::Buffer< ConvType > output = Halide::Buffer< ConvType >( &oBuffer[ 0 ], uBufferSize, uBufferSize );
C.realize( output, target );
```
Tested with version from buildbot:
Halide-12.0.0-x86-64-windows-8383cc99b3ca366d26520bf9162537269c621599

**Comment by chkone** [comment]
> You can construct argument lists as std::vectors of Expr objects, so when I want to be very generic I just do that. How about something like:
> 
> ```
> vector<Expr> a_args;
> for (Var v : A.args()) a_args.push_back(v);
> vector<Expr> b_args = a_args;
> while (b_args.size() > B.dimensions()) b_args.pop_back();
> while (b_args.size() < B.dimensions()) b_args.emplace_back(0);
> vector<Expr> c_args = a_args;
> while (c_args.size() > C.dimensions()) c_args.pop_back();
> while (c_args.size() < C.dimensions()) c_args.emplace_back(0);
> A(a_args) = B(b_args) + C(c_args);
> ```

Close in time answer, missed this one.
I wasn't aware about this way to index functions.
Based on this code I came out with this solution to support other permutation:
Output: C
Input: A & B
```
std::vector<Halide::Var> argsMax = A.args().size() >= B.args().size() ? A.args() : B.args();

std::vector<Halide::Expr> a_args, b_args;
for ( Halide::Var v : argsMax )
{
	a_args.push_back( v );
	b_args.push_back( v );
}

while ( a_args.size() > A.dimensions() )
	a_args.pop_back();
while ( a_args.size() < A.dimensions() )
	a_args.emplace_back( 0 );

while ( b_args.size() > B.dimensions() )
	b_args.pop_back();
while ( b_args.size() < B.dimensions() )
	b_args.emplace_back( 0 );

std::vector<Halide::Expr> c_args = a_args.size() >= b_args.size() ? a_args : b_args;
while ( c_args.size() > outDim )
	c_args.pop_back();
while ( c_args.size() < outDim )
	c_args.emplace_back( 0 );
C( c_args ) = A( a_args ) + B( b_args );
```
