### ISSUE TITLE
[build] Linking to libHalide (CMake Halide::Halide) without -fno-rtti

### ISSUE THREAD

**Issue by jacobkahn** [halide/Halide#5600]
Brought this up offline, but opening for visibility — linking to the CMake `Halide::Halide` target when building from master (or `release/v10.0`) adds `-fno-rtti` to the compile flags of downstream projects. This generally restricts what Halide can be linked with.

This isn't the case for the vcpkg target (which I've since used successfully), so this might be a worthy change in CMake config for from-source builds.

cc @alexreinking

**Comment by alexreinking** [comment]
Just to be clear: which LLVM are you using? As in: how was it built? Halide intentionally matches the RTTI setting of LLVM.

**Comment by jacobkahn** [comment]
I was using a pre-built binary for LLVM 10 downloaded as a tarball from [here](https://releases.llvm.org/download.html).

It seems like the LLVM 11 built with `vcpkg` when building Halide with `vcpkg` is built without that flag, so that ended up working for me.

Given what you mentioned, if the tarball from their releases page has the flag, there's probably not much that can be done...

**Comment by alexreinking** [comment]
Yeah, the LLVM official releases are built without RTTI. If you (as many people do) need RTTI enabled in your application, you should build LLVM manually or use vcpkg.

**Comment by alexreinking** [comment]
Closing because our official binary releases (should) have RTTI enabled. If they don't, we can re-open.
