### ISSUE TITLE
 Output buffer output requires a buffer of exactly 2 dimensions, but the buffer passed in has 3 dimensions

### ISSUE THREAD

**Issue by KillerInk** [halide/Halide#5608]
hi with halide 8.0.0 and 10.0.0 that problem started.
So i decided to create a simple generator.
its not complaining about at build time. it happens when i run the generator.

```

#include "Halide.h"

using namespace Halide;
namespace {

    class Avarage_generator : public Generator<Avarage_generator> {

    public:
        Input <Halide::Buffer<uint16_t>> inputs{"inputs", 3};
        Output <Halide::Buffer<uint16_t>> output{"output", 2};

        Var x{"x"},y{"y"};

        void generate() {
            output(x,y) = (inputs(x,y,0) + inputs(x,y,1))/2;;
            output.parallel(y).vectorize(x,128);

        }
    };
}


HALIDE_REGISTER_GENERATOR(Avarage_generator, avarage_generator)
```

greets

**Comment by ashishUthama** [comment]
Based on the error (and having hit it a few times), likely the issue is in the code calling the generator/generated code. Inspecting the number of dims set to the output buffer you pass in should help.

**Comment by KillerInk** [comment]
Well input are two images with one color chan and I create it like that
Halide::Runtime::Buffer<uint16_t> inputs(width, height, 2)

Output is one image with one color chan. Looks like that
Halide::Runtime::Buffer<uint16_t> output(width, height, 1)

From that point dimens should be ok

**Comment by steven-johnson** [comment]
`Halide::Runtime::Buffer<uint16_t> output(width, height, 1)`

That has 3 dimensions; the third dimension has an extent of 1.

What you want is

`Halide::Runtime::Buffer<uint16_t> output(width, height)`

(From a memory-layout point of view, these are likely identical, but from a dimensionality point of view, they definitely are not)

**Comment by KillerInk** [comment]
wow its working, so simple 🥇  big thx
