### ISSUE TITLE
Remove implicit requirement that LLVM include x86, x86-64, arm, aarch64 support

### ISSUE THREAD

**Issue by shoaibkamil** [halide/Halide#5628]
As demonstrated by #5573, we now essentially require these four backends in order to compile the Windows runtime modules.  We should make it possible to compile Halide at least without arm/aarch64 LLVM backends, and if feasible without x86/x86-64 LLVM backends.

**Comment by alexreinking** [comment]
This is causing issues with our vcpkg port which allows users to build a subset of targets (eg. only x86 on x86).
