### ISSUE TITLE
no viable conversion from 'Halide::ImageParam' to 'const std::vector<Argument>'

### ISSUE THREAD

**Issue by Angerla** [halide/Halide#5629]
I run the example Halide, some compile error occured.I do not know whether it is the environment has some problem,I use such "cmd" to run the halide' file:
**clang++ "/run/shm/halide_h_namzn.cpp" -o "/run/shm/halide47_kvoje.bin"  -I "/home/zc/zc/Halid/Halide-build/include"  -L  "/home/zc/zc/Halid/Halide-build/bin" -lHalide -ldl -lcurses -lpthread  -DAUTOTUNE_N="4096, 4096" -DAUTOTUNE_TRIALS=3 -DAUTOTUNE_LIMIT=315360000**
and some  main error:
**1halide_h_namzn.cpp:23:17: error: use of undeclared identifier 'buffer_t'**
**2. halide_h_namzn.cpp:24:25: error: use of class template 'Halide::Buffer' requires template arguments**
****3.error:** halide_h_namzn.cpp:149:43: error: no viable conversion from 'Halide::ImageParam' to 'const std::vector<Argument>'**

the halidee_h_namzn.cpp file:
`#include <Halide.h>
#include <stdio.h>
#include <sys/time.h>
#include <unistd.h>

#include <map>
#include <string>

// How many times to run (and take min)
// #define AUTOTUNE_TRIALS 3

// Limit in seconds to try running for (0 = no limit)
// #define AUTOTUNE_LIMIT 0

// Size to run with
// #define AUTOTUNE_N 1024, 1024

inline void _autotune_timing_stub(Halide::Func& func) {
    func.compile_jit();

    // TODO: this assumes scalar/non-Tuple outputs - should generalize to a Realization
    std::vector<Halide::Type> out_types = func.output_types();
    std::vector<buffer_t> out_raw_bufs;
    std::vector<Halide::Buffer> out_bufs;

    for (int i = 0; i < out_types.size(); i++) {
        // Use the Buffer constructor as a helper to set up the buffer_t,
        // but then throw away its allocation which we don't really want.
        Halide::Buffer bufinit(out_types[i], AUTOTUNE_N);
        out_raw_bufs.push_back(*bufinit.raw_buffer());
        out_raw_bufs[i].host = NULL;
        // TODO: free the host pointer?!
        out_bufs.push_back(Halide::Buffer(out_types[i], &out_raw_bufs[i]));
        assert(out_bufs[i].host_ptr() == NULL); // make sure we don't have an allocation
    }
    Halide::Realization output(out_bufs);
    func.infer_input_bounds(output);
    // assert(output[0].host_ptr()); // for now, the API doesn't seem to allocate outputs
    
    // TODO: this should go into Func::infer_input_bounds(Realization)
    for (int i = 0; i < output.size(); i++) {
        assert(!output[i].host_ptr()); // for now, the API doesn't seem to allocate outputs
        buffer_t buf = *output[i].raw_buffer();
        
        // Figure out how much memory to allocate for this buffer
        size_t min_idx = 0, max_idx = 0;
        for (int d = 0; d < 4; d++) {
            if (buf.stride[d] > 0) {
                min_idx += buf.min[d] * buf.stride[d];
                max_idx += (buf.min[d] + buf.extent[d] - 1) * buf.stride[d];
            } else {
                max_idx += buf.min[d] * buf.stride[d];
                min_idx += (buf.min[d] + buf.extent[d] - 1) * buf.stride[d];
            }
        }
        size_t total_size = (max_idx - min_idx);
        while (total_size & 0x1f) total_size++;

        // Allocate enough memory with the right dimensionality.
        Halide::Buffer buffer(output[i].type(), total_size,
                      buf.extent[1] > 0 ? 1 : 0,
                      buf.extent[2] > 0 ? 1 : 0,
                      buf.extent[3] > 0 ? 1 : 0);

        // Rewrite the buffer fields to match the ones returned
        for (int d = 0; d < 4; d++) {
            buffer.raw_buffer()->min[d] = buf.min[d];
            buffer.raw_buffer()->stride[d] = buf.stride[d];
            buffer.raw_buffer()->extent[d] = buf.extent[d];
        }
        
        output[i] = buffer;
    }

    timeval t1, t2;
    double rv = 0;
    const unsigned int timeout = AUTOTUNE_LIMIT;
    alarm(timeout);
    for (int i = 0; i < AUTOTUNE_TRIALS; i++) {
      gettimeofday(&t1, NULL);
      func.realize(output);
      gettimeofday(&t2, NULL);
      alarm(0); // disable alarm
      double t = (t2.tv_sec - t1.tv_sec) + (t2.tv_usec - t1.tv_usec)/1000000.0;
      if(i == 0 || t < rv)
        rv = t;
    }
    printf("{\"time\": %.10f}\n", rv);
    exit(0);
}

#ifndef AUTOTUNE_HOOK
#define AUTOTUNE_HOOK(x)
#endif

#ifndef BASELINE_HOOK
#define BASELINE_HOOK(x)
#endif

#include <Halide.h>
using namespace Halide;

#define AUTOTUNE_HOOK(x)
#define BASELINE_HOOK(x)

int main(int argc, char **argv) {

    ImageParam in_img(UInt(16), 2);
    Func blur_x("blur_x"), blur_y("blur_y");
    Var x("x"), y("y"), xi("xi"), yi("yi");

    Func input;
    input(x,y) = in_img(clamp(x, 1, in_img.width()-1),
                        clamp(y, 1, in_img.height())-1);

    // The algorithm
    blur_x(x, y) = (input(x, y) + input(x+1, y) + input(x+2, y))/3;
    blur_y(x, y) = (blur_x(x, y) + blur_x(x, y+1) + blur_x(x, y+2))/3;
    {
        std::map<std::string, Halide::Internal::Function> funcs = Halide::Internal::find_transitive_calls((blur_y).function());

        Halide::Var _x0, _y1, _x2, _y3;
        Halide::Func(funcs["blur_x"])
        .split(x, x, _x0, 8)
        .split(y, y, _y1, 2)
        .reorder(_x0, _y1, x, y)
        .reorder_storage(y, x)
        .compute_at(Halide::Func(funcs["blur_y"]), x)
        ;
        Halide::Func(funcs["blur_y"])
        .split(x, x, _x2, 4)
        .split(y, y, _y3, 2)
        .reorder(_x2, _y3, x, y)
        .reorder_storage(y, x)
        .compute_root()
        ;
        

        _autotune_timing_stub(blur_y);
    };

    // How to schedule it
    blur_y.split(y, y, yi, 8).parallel(y).vectorize(x, 8);
    blur_x.store_at(blur_y, y).compute_at(blur_y, yi).vectorize(x, 8);  

    BASELINE_HOOK(blur_y);

    blur_y.compile_to_file("halide_blur", in_img); 

    return 0;
}
`

**Comment by abadams** [comment]
It looks like you're trying to compile code written for a very old version of Halide against current Halide master. The "buffer_t" struct was deleted years ago and that block of code would have to be written somewhat differently today. There isn't a simple fix.

**Comment by Angerla** [comment]
It seems the halide version is higher to compile the code, I want to ask whether I try to choose a lower version to compile the code can useful and what version is right if the way can do?

**Comment by abadams** [comment]
I'm not sure what you're trying to achieve. If you're trying to use the very old autotuner which I think that code is based on then  there are newer autoschedulers/autotuners that are much better. It's obsolete. If you really need to compile that code as-is then you'd have to hunt through Halide's history compiling it at different points in time until you find something that works. I'd start by figuring out when that code was written in the first place.

**Comment by Angerla** [comment]
Thanks for your help. I just learn about Halide and I want to run the project opentuner/example/halide. The code is from the project and seems very old. I will try other project. Thanks again.
