### ISSUE TITLE
warp shuffle intrinsics no longer work with cuda compute capability 8.0

### ISSUE THREAD

**Issue by abadams** [halide/Halide#5630]
We need to use the .sync variants starting from that version

**Comment by jinderek** [comment]
> We need to use the .sync variants starting from that version

Hi, @abadams. Is there anyone working on this? If not, can I take this issue? I have some experience with Halide and NVIDIA GPUs

**Comment by abadams** [comment]
Nobody is currently working on this. You're very welcome to open a PR.

**Comment by jinderek** [comment]
> Nobody is currently working on this. You're very welcome to open a PR.

👍 I'll begin to implement this in these days.
