### ISSUE TITLE
Release GIL in the generated Python extension source code

### ISSUE THREAD

**Issue by emilmelnikov** [halide/Halide#5631]
It would be very nice to have an option for releasing GIL in the generated Python extension source code (or maybe just always do this). I assume it should be OK since NumPy releases the lock too, so this ought to be the expected behaviour.

The change itself should be very simple: just wrap [call to the actual function](
https://github.com/halide/Halide/blob/9b99acb0b9033e7c90d369e14154332737db3a6b/src/PythonExtensionGen.cpp#L350) into [`Py_BEGIN_ALLOW_THREADS/Py_END_ALLOW_THREADS`](https://docs.python.org/3/c-api/init.html#c.Py_BEGIN_ALLOW_THREADS) macros.

**Comment by steven-johnson** [comment]
We'd welcome a patch that did this :-)
