### ISSUE TITLE
Rename master -> main branch

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#5666]
We should follow the lead of LLVM (etc) and rename `master` -> `main` -- GitHub has released a tool that purports to make this easier (https://github.com/github/renaming). 

IIUC, LLVM is maintaining a shadow-branch still named `master` for now; not sure if we should do that as well?

**Comment by alexreinking** [comment]
> maintaining a shadow-branch ... not sure if we should do that as well?

I say rip the band-aid off. If we're going to do this, we should set a date a few weeks out, bang pots and pans on the mailing list, Gitter, etc. and then make good on our promise. Changing "master" to "main" for Halide shouldn't cause more than a short interruption for anyone if they're forewarned.

**Comment by steven-johnson** [comment]
I'd be fine with a no-fallback position too.

**Comment by powderluv** [comment]
Any idea on when this is planned to happen ? All the other submodules we use at https://github.com/mmperf/mmperf are on "main" and I have to make a special exception just to update Halide. Thanks

**Comment by steven-johnson** [comment]
Yeah, we should get around to this soon. Since we are planning on doing a release of Halide 13 soon, it might be good to target immediately after that.

**Comment by powderluv** [comment]
thanks thanks. maybe there is a way to create an alias for main while the transition happens (like llvm).

**Comment by abadams** [comment]
I have pushed a branch called "main" which is just master.

**Comment by powderluv** [comment]
thanks thanks
