### ISSUE TITLE
RegionCosts doesn't handle the mux intrinsic

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#5723]
Recently converted from a helper into an intrinsic. Build apps/camera_pipe to see a large number of `Warning: Unhandled intrinsic call mux` emitted.

**Comment by abadams** [comment]
This is an interesting problem, because if the schedule unrolls the mux then the cost is just the average cost of the args, and if it isn't, it's the sum of the costs of the args. I guess that autoscheduler doesn't know to unroll muxes, so I'd better make it the sum.
