### ISSUE TITLE
Linking autoschedulers to generators is broken

### ISSUE THREAD

**Issue by rootjalex** [halide/Halide#5769]
Generators don't seem to be using autoschedulers on current master, i.e. if I change the default apps autoscheduler to adams2019 and add changes in the adams2019 autoscheduler, the autoscheduling command seems to complete immediately and doesn't appear to use a schedule different from the non-autoscheduled schedule. 

@abadams  Confirmed this issue for him as well, and says it look like the auto_schedule flag is being dropped, because the IR for autoscheduled and not is the same.

**Comment by abadams** [comment]
@steven-johnson Maybe a recent change to generator stuff dropped the auto_schedule generatorparam?

**Comment by rootjalex** [comment]
@steven-johnson 1be92c2cd5ae9f95e37576ffb653cbe4c3458dd0 seems to be the culprit, the prior commit properly enables autoscheduling.

**Comment by steven-johnson** [comment]
Investigating. At first glance, pretty baffling -- I don't see anything that looks related in that change, but we'll see...

**Comment by steven-johnson** [comment]
(1) can someone provide a specific set of build command(s) so I can be sure I'm looking at the same thing as you are seeing?
(2) this change passed all our tests, so clearly the autoscheduler isn't getting tested properly -- do we lack the right tests entirely, or do they exist but aren't getting run by the buildbots?

**Comment by rootjalex** [comment]
Sorry for the delayed reply, but you seem to have found it!

**Comment by abadams** [comment]
The autoscheduler gets tested, but it's limited to verifying that the schedules compile and run. This bug sneakily substituted a human schedule for every autoschedule. The autoschedulers themselves have some unit tests, but they wouldn't have caught this either.
