### ISSUE TITLE
GLSL backend/runtime produces unused boilerplate code

### ISSUE THREAD

**Issue by abestephensg** [halide/Halide#577]
The Vertex shader in the GLSL backend is produced in the runtime using a fixed template and as a result contains some code that might not be used in the fragment shader, e.g. the image coordinate varying pixcoord. This unused boiler plate should not be generated.

attribute vec4 _varyingf0_attrib;
varying   vec4 _varyingf0;
uniform ivec2 output_min;
uniform ivec2 output_extent;
void main() {
    vec2 position = vec2(_varyingf0_attrib[0], _varyingf0_attrib[1]);
    gl_Position = vec4(position, 0.0, 1.0);
    vec2 texcoord = 0.5 \* position + 0.5;
    vec2 pixcoord = texcoord \* vec2(output_extent.xy) + vec2(output_min.xy);
    _varyingf0 = _varyingf0_attrib;
    _varyingf0.xy = pixcoord;
}

Likewise, plenty of unused variables are defined in the fragment shader (e.g. _f0_extent_0, etc.)

varying vec4 _varyingf0;
uniform vec4 _uniformf0;
uniform ivec4 _uniformi0;
void main() {
  float _a0_varying = _varyingf0[2];
  int _f0_extent_0 = _uniformi0[0];
  int _f0_extent_1 = _uniformi0[1];
  int _f0_min_1 = _uniformi0[2];
  float _p = _uniformf0[0];
  float _t0_varying = _varyingf0[3];
  int _f0_s0_yXX_block_id_y = int(_varyingf0[1]);
  int _f0_s0_xXX_block_id_x = int(_varyingf0[0]);
  float _0 = _p \* 10.0;
  vec3 _1 = vec3(4.0, _0, _a0_varying);
  gl_FragColor.rgb = _1;
}

**Comment by steven-johnson** [comment]
Did the commit address this, or is there work remaining to be done?

**Comment by abestephensg** [comment]
There is still work to be done here.
