### ISSUE TITLE
cost_model.generator: symbol lookup error:undefined symbol: _ZN6Halide8Internal18GeneratorInputBase16verify_internalsEv

### ISSUE THREAD

**Issue by Angerla** [halide/Halide#5783]
I build the latest source code with make ,but meeting a error:

>  make[1]: Entering directory '/home/zc/zc/Test/Halide-master'
Looking for Halide distro at /home/zc/zc/Test/Halide-master/distrib. If this is incorrect, set the make variable HALIDE_DISTRIB_PATH
bin/binary2cpp baseline_weights < /home/zc/zc/Test/Halide-master/src/autoschedulers/adams2019/baseline.weights > bin/baseline_weights.cpp
g++ -c bin/baseline_weights.cpp -o bin/baseline_weights.o
g++ -O3 -std=c++11 -I /home/zc/zc/Test/Halide-master/distrib/include/ -I /home/zc/zc/Test/Halide-master/distrib/tools/  -Wall -Werror -Wno-unused-function -Wcast-qual -Wignored-qualifiers -Wno-comment -Wsign-compare -Wno-unknown-warning-option -Wno-psabi -fno-rtti -I/home/zc/zc/Test/Halide-master/src/autoschedulers/common /home/zc/zc/Test/Halide-master/src/autoschedulers/adams2019/cost_model_generator.cpp /home/zc/zc/Test/Halide-master/distrib/tools/GenGen.cpp -o bin/cost_model.generator -rdynamic -Wl,-rpath,/home/zc/zc/Test/Halide-master/distrib/lib/ -L /home/zc/zc/Test/Halide-master/distrib/lib/ -lHalide  -ldl -lpthread -lz
bin/cost_model.generator -g cost_model -o bin/cost_model -f cost_model target=host-no_runtime auto_schedule=false -e stmt,static_library,h,assembly
bin/cost_model.generator: symbol lookup error: bin/cost_model.generator: undefined symbol: _ZN6Halide8Internal18GeneratorInputBase16verify_internalsEv
/home/zc/zc/Test/Halide-master/src/autoschedulers/adams2019/Makefile:54: recipe for target 'bin/cost_model/cost_model.a' failed
make[1]: *** [bin/cost_model/cost_model.a] Error 127
make[1]: Leaving directory '/home/zc/zc/Test/Halide-master'
Makefile:2278: recipe for target 'distrib/lib/libautoschedule_adams2019.so' failed
make: *** [distrib/lib/libautoschedule_adams2019.so] Error 2
How can I solve this problem?

**Comment by alexreinking** [comment]
Does this happen when building with CMake, too? What's your compiler version?

**Comment by Angerla** [comment]
This happen when building with make. My Make version is : GNU Make 4.1. But I building with CMake successed. Thanks for your reply.

**Comment by alexreinking** [comment]
@abadams - any idea why this might happen?

**Comment by abadams** [comment]
It's a generator trying to resolve a symbol inside libHalide and failing. I'm a bit stumped as to how that could happen. This is just regular dynamic linkage.
