### ISSUE TITLE
Preallocated buffers.

### ISSUE THREAD

**Issue by S-o-T** [halide/Halide#5800]
If one have an estimate on upper bounds of pipeline's input\output sizes, it should be possible to avoid memory (de)allocation during the execution of pipeline, by (re)using the buffers provided as part of input\output data, structure (and, optionally,(de)allocation procedures) of which should be codegened as part of pipeline interface. Does Halide already have an implemention of such functionality and, if not, are there any plans to introduce such functionality?

**Comment by zvookin** [comment]
I call the generalization of this "Allocation Plans." The idea is there should be a way to hoist scoped resource allocation/deallocation to higher scopes, or orthogonally change the allocation method to use an LRU cache or suballocate from a larger block, etc. This is a research project, but very much in keeping with Halide's notion of scheduling and having a lot more information about what is happening.

The name "allocation plans" includes allocating things like GPU contexts, shader compilations, threadpool spinups, etc. Ideally I'd like *all* resources a Halide generated pipeline uses to be enumerable and controllable. If nothing else, this would given insight into what is being used.
