### ISSUE TITLE
[GSoC] Julia wrapper

### ISSUE THREAD

**Issue by johnnychen94** [halide/Halide#5801]
Hi,

My name is Jiuning Chen(Johnny Chen), I'm a second-year Ph.D. student in ECNU(East China Normal University), a GSoC 19 student in Julia, and also a core maintainer of [JuliaImages](https://github.com/JuliaImages/Images.jl) since that. My previous main research interest is low-level image processing (e.g., denoise) using filter techs.

Both Julia and halide have shown their great advantages in image processing and I want to see if I can try to get the best of the two worlds by providing a Julia interface to Halide. 

I've learned a lot from the halide paper when I try to optimize my Julia codes but never tried halide; it was quite a long time ago since my last usage of C++. To apply for the [Halide Code Generation For More Languages](https://github.com/halide/Halide/wiki/%5BGSoC-2021%5D-Halide-Code-Generation-For-More-Languages) GSoC project, I definitely need some refresh of my C++ knowledge, I'm wondering if you could provide some easy-to-start issues that I can work on to get a better understanding of halide (and of course C++) before I start to write my proposal.

Also, is this issue an appropriate place to update progress, or should I contact you via other channels/apps?

Best regards

cc: @zvookin @rootjalex @BachiLi

**Comment by rootjalex** [comment]
If you haven't already tried these out, the[ tutorials](https://halide-lang.org/tutorials/tutorial_introduction.html) are a good way to get more familiar with Halide.

I'm not sure about specific issues that are relevant to you at the moment, but Tzu-Mao recommended trying to understand our [PyTorch codegen](https://github.com/halide/Halide/blob/master/src/CodeGen_PyTorch.cpp) [module](https://github.com/halide/Halide/blob/master/src/CodeGen_PyTorch.h) as a good starting point.

The [gitter](https://gitter.im/halide/Halide) is a good communication method that we use.

**Comment by rootjalex** [comment]
A bit more on this, specific to Julia: after a quick glance over [Cxx.jl](https://github.com/JuliaInterop/Cxx.jl) and [CxxWrap.jl](https://github.com/JuliaInterop/CxxWrap.jl), CxxWrap seems to be the more plausible option for embedding (if there are others who are more familiar with Julia, please correct me). [This](https://github.com/JuliaInterop/CxxWrap.jl/issues/127) issue links to some examples that may be relevant

**Comment by johnnychen94** [comment]
I plan to follow a similar route [OpenCV-Julia binding project](https://github.com/opencv/opencv/wiki/OE-31.-Julia-Bindings) did since it's written in C++, too. So yeah I'll use CxxWrap. But before that, I'll need to try and learn the halide internals to understand it. I'll do a halide-Julia benchmark first in the next few days. Hopefully, I can put my hands on the wrapper project next weekend.
