### ISSUE TITLE
Having a issue realted to Halid

### ISSUE THREAD

**Issue by Rohan-Zanjal** [halide/Halide#5845]
![Screenshot (14)](https://user-images.githubusercontent.com/71709895/112305358-9965db00-8cc4-11eb-9839-dd2b170fde54.png)

What is the correct way to solve this issue

**Comment by shoaibkamil** [comment]
You need to run that command within the Halide source directory, which you can check out using git.  Something like:

```
> cd ..
> git clone https://github.com/halide/halide
> cd halide
```
Then you can run the CMake command you tried before.

**Comment by Rohan-Zanjal** [comment]
![Screenshot (16)](https://user-images.githubusercontent.com/71709895/112455423-b7dcdc80-8d7f-11eb-8b26-788d3c2e6286.png)

How can I solve this

**Comment by steven-johnson** [comment]
Please don't open issues for this sort of thing, they aren't the right forum. Please try the Gitter channel instead.
