### ISSUE TITLE
Error LLVM

### ISSUE THREAD

**Issue by Rohan-Zanjal** [halide/Halide#5851]
![Screenshot (16)](https://user-images.githubusercontent.com/71709895/112455625-e65ab780-8d7f-11eb-927d-910b2dc433d7.png)

**Comment by steven-johnson** [comment]
Please don't open issues for this sort of thing, they aren't the right forum. Please try the Gitter channel instead.

**Comment by Rohan-Zanjal** [comment]
Yaa,
Okk
