### ISSUE TITLE
Support for ClangCl (clang-cl) on MSVC

### ISSUE THREAD

**Issue by emmenlau** [halide/Halide#5852]
For a few years now, Microsoft has been (optionally) shipping the clang compiler frontend clang-cl with Visual Studio. Using clang on Windows has a number of benefits, most importantly to create often faster code and to provide more homogeneous error messages with other (Un*x-like) platforms.

Are there plans to support ClangCl on MSVC?

**Comment by steven-johnson** [comment]
There aren't any current plans (that I know of) to do so, but that's mainly inertia; we'd welcome patches to support this, but we'd also have to carefully evaluate our testing resources to ensure that we get good coverage on our buildbots, which are currently underpowered for Windows testing. (cc @shoaibkamil)

**Comment by emmenlau** [comment]
Solved in https://github.com/halide/Halide/pull/5876, thanks guys!
