### ISSUE TITLE
Install ‘’llvm[target-all,clang-tools-extra]:x64-windows‘’ wait too long

### ISSUE THREAD

**Issue by haikunzhang95** [halide/Halide#5855]
My platform is: Windows 10 x64. Follow the "Building Halide with CMake", I install ''libpng:x64-windows'', '' libjpeg-turbo:x64-windows'', and '' **llvm[target-all,clang-tools-extra]:x64-windows**'' respectively. I successfully installed the first two, but there was a problem installing the last package. When the Windows PowerShell display“**--Building x64-windows-dbg**”, the cursor keeps blinking, and notning happened. I waited for several hours and did not see the message of successful installation. So, what should 
I do? What is the possible reason？
Thank you all!

**Comment by shoaibkamil** [comment]
This is not a Halide  issue, please report problems with vcpkg to those developers.  However, I don't think there is a problem here:  LLVM takes a long time to build.  You can find logs under `VCPKG_ROOT/buildtrees/llvm, I believe..
