### ISSUE TITLE
Cannot build in Debug mode on Windows

### ISSUE THREAD

**Issue by wal-rus** [halide/Halide#586]
The currently available release of the windows binaries will cause a std::bad_alloc exception on the construction of nearly any Halide object (for example, Func) when _DEBUG is defined and linking with /MDd.  Release mode seems fine, I suspect some uninitialized memory might be the cause as the debugger reports trying to load from 0xcccccccc

**Comment by abadams** [comment]
I believe this was fixed by merging #610 - the nightly build folders now also contain a debug build. I'll make a new release when we figure out why 32-bit builds on OS X are failing.
