### ISSUE TITLE
Cmake Error

### ISSUE THREAD

**Issue by Rohan-Zanjal** [halide/Halide#5860]
![Screenshot (17)](https://user-images.githubusercontent.com/71709895/112829766-3783e780-90af-11eb-8a9e-21ed47aa112c.png)

Cmake Error

I have facing this Error from many days
Can anyone Help me to Solve this

**Comment by steven-johnson** [comment]
Do not open issues with questions and screenshots.

**Comment by Rohan-Zanjal** [comment]
sir can you please help me solve this error
