### ISSUE TITLE
typos in tutorial

### ISSUE THREAD

**Issue by aemior** [halide/Halide#5865]
I'm just learning Halide, I found some typos in [lesson 8](https://github.com/halide/Halide/blob/e0461e9c6d5ec5551a509d42aa0b3238b2f8aa56/tutorial/lesson_08_scheduling_2.cpp) might wrong. In [line 449](https://github.com/halide/Halide/blob/e0461e9c6d5ec5551a509d42aa0b3238b2f8aa56/tutorial/lesson_08_scheduling_2.cpp#L449) and [line 348](https://github.com/halide/Halide/blob/e0461e9c6d5ec5551a509d42aa0b3238b2f8aa56/tutorial/lesson_08_scheduling_2.cpp#L348), it says "-Stores : 39" and "-Stores : 56", I think it might be 41.

**Comment by BachiLi** [comment]
We welcome pull requests for such cases.
