### ISSUE TITLE
CMake Error in dependencies/llvm/CMakeLists.txt:

### ISSUE THREAD

**Issue by Rohan-Zanjal** [halide/Halide#5877]
D:\Halide>set IMPORTED_LOCATION=D:\vcpkg\buildtrees\llvm\x64-windows-rel\tools\lld\wasm\CMakeFiles

D:\Halide>cmake -G Ninja ^
More? More?                  -DCMAKE_BUILD_TYPE=Release ^
More? More?                  -DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake ^
More? More?                  -S . -B build
-- Windows: setting CMAKE_OBJECT_PATH_MAX to 260
-- Found LLVM 11.0.0
-- Using LLVMConfig.cmake in: D:/vcpkg/llvm-project/build/lib/cmake/llvm
-- Enabling AArch64 backend
-- Enabling AMDGPU backend
-- Enabling ARM backend
-- Enabling Hexagon backend
-- Enabling Mips backend
-- Enabling NVPTX backend
-- Enabling PowerPC backend
-- Enabling RISCV backend
-- Enabling WebAssembly backend
-- Enabling X86 backend
-- Compiling Halide WITHOUT RTTI.
-- Compiling Halide WITH exceptions.
-- Building autoschedulers enabled
-- Building tests enabled
-- Building Python bindings disabled
-- Building tutorials enabled
-- Building docs disabled
-- Building utils enabled
-- Configuring done
CMake Error in dependencies/llvm/CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "lldWasm" configuration
  "Release".

CMake Error in dependencies/llvm/CMakeLists.txt:
  Target "Halide_LLVM" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "D:/Halide/dependencies/llvm/"

  which is prefixed in the source directory.

CMake Error in dependencies/llvm/CMakeLists.txt:
  Target "Halide_LLVM" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "D:/Halide/dependencies/llvm/"

  which is prefixed in the source directory.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by dkurt** [comment]
resolved by https://github.com/halide/Halide/pull/6519
