### ISSUE TITLE
simplify often does not remove chains of unused Lets

### ISSUE THREAD

**Issue by abestephensg** [halide/Halide#588]
Usually calls to simplify(...) will remove Let and LetStmt nodes that define unused variables from the IR tree. In certain cases, especially when a let variable is used in another let statement whose variable is unused, simplify must be called repeatedly to remove all of the unused code.

CodeGen will unconditionally process these Lets even if they are unused. Halide will crash if the let values for the unused variables contain expressions that cannot be generated for a certain target.

**Comment by dsharletg** [comment]
The simplifier has been almost entirely rewritten since this was filed, going to close this as it's probably fixed.
