### ISSUE TITLE
Possible bug (buffer is accessed beyond the max)

### ISSUE THREAD

**Issue by lyudalev** [halide/Halide#5889]
Hi,
It seems that I'm stepping on a bug and it looks like Halide's bug :-(
Here is my example, running with Halide 11.01 release.

```
class Bug : public Generator <Bug>
{
public:
    Output <Buffer <float>> result {"result", 2};
    Input <Buffer <float>> in1 {"in1", 2};
    Input <Buffer <float>> in2 {"in2", 2};
    Input <Buffer <int>> mask {"mask", 2};
    Input <int> polarity {"polarity"};
    Input <float> limit {"limit"};
    Input <float> alpha {"alpha"};

    void generate ()
    {
        Var x ("x"), y ("y");

        auto shift_x = mask.width () / 2;
        auto shift_y = mask.height () / 2;

#if 1
        // crash:
        // halide_error: Input buffer in2 is accessed at 1280, which is beyond the max (1279) in dimension 0
        auto width = in1.width ();
        auto height = in1.height ();
#else
        // works
        auto width = 1280;
        auto height = 78;
#endif

        RDom inside (shift_x, width  - 2 * shift_x, shift_y, height - 2 * shift_y, "inside");

        Func in2_clipped ("in2_clipped");
        in2_clipped (x, y) = clamp (select (polarity == 1, in2 (x, y), -in2 (x, y)), -limit, limit);

        RDom box (mask);
        Func box_max ("box_max");
        box_max (x, y) = maximum (select (mask (box.x, box.y) != 0,
            in1 (x + box.x - shift_x, y + box.y - shift_y),
            std::numeric_limits<float>::lowest()));        

        result (x, y) = undef <float> ();
        result (inside.x, inside.y) =
            alpha * box_max (inside.x, inside.y) +
            (1.0f - alpha) * in2_clipped (inside.x, inside.y);

        RVar xo ("xo"), yo ("yo"), xi ("xi"), yi ("yi"), tidx ("tidx");
        result.update (0)
            .tile (inside.x, inside.y, xo, yo, xi, yi, 1280, 4)
            .fuse (xo, yo, tidx)
            .parallel (tidx);

        RVar ixo ("ixo"), iyo ("iyo"), ixi ("ixi"), iyi ("iyi");
        result.update (0)
            .tile (xi, yi, ixo, iyo, ixi, iyi, 32, 4)
            .vectorize (ixi, 32)
            .unroll (iyi);
    }
};
```
A simple change of the conditional compile directive commented in the code above switches between hardcoded width and height values and values derived from the input buffer. Somehow it cases a crash:
```
clang++ -march=native -O2 -g /mnt/halide/share/tools/GenGen.cpp bug_gen.cpp -I /mnt/halide/include -L /mnt/halide/lib -l Halide -Wl,-rpath /mnt/halide/lib -o bin/bug_gen
./bin/bug_gen -g bug -o bin -e h,static_library,registration,stmt,schedule,assembly target=x86-64-linux-avx2
clang++ -march=native -O2 /mnt/halide/share/tools/RunGenMain.cpp bin/bug.a bin/bug.registration.cpp -I /mnt/halide/include -o bin/bug_rungen -lpng -ljpeg -lz -lpthread -ldl
./bin/bug_rungen in1=random:0:[1280,78] in2=random:0:[1280,78] mask=constant:1:[3,3] polarity=1 limit=1000.0 alpha=0.1 result=bin/bug.tiff --benchmarks=all --benchmark_min_time=1 --parsable_output

halide_error: Input buffer in2 is accessed at 1280, which is beyond the max (1279) in dimension 0
```

Also, it runs fine without a schedule (that is, default one). Please advise.
Sincerely,
Lev

**Comment by abadams** [comment]
For a size 1280 input, the RDom "inside" has extent 1278, but you tile it with factor 1280. Halide uses a tile of size 1280, as requested, but masks off the last two elements of the tile with an if statement so that only first 1278 iterations do anything, but then bounds inference, after making its way through the maximum stencil, doesn't realize that this if statement means certain values from the input image aren't going to be read, and assumes the full tile is evaluated. Unfortunately the problem of inferring what regions will be accessed in the presence of if statements that affect control flow is very hard unless things are constants. Changing the tile width to 1278 fixes it. I also see a way to improve the compiler to make the original schedule work out, so I'll do that too.

**Comment by lyudalev** [comment]
Thank you for the interesting explanation. One more thing to notice though:
it also works fine if I change 'width' and 'height' to be input parameters
and not constants. I can use it as a workaround for now, although a real
solution with a schedule and an algorithm not depending on each other is
preferable.

**Comment by abadams** [comment]
See #5890 for a more robust fix.
