### ISSUE TITLE
Dynamically-typed scalar parameters

### ISSUE THREAD

**Issue by abadams** [halide/Halide#5953]
Currently we can specify an `Input<Buffer<>>` to a Generator, which means that the type is given by a GeneratorParam, or perhaps it's a pointer to or vector of `Input<Buffer<>>`, in which case the type is given as an argument to add_input in configure(). 

There's no equivalent way to do that for scalars. The add_input method for scalar parameters requires a static type, and Input<void> doesn't seem to be a legal type for a scalar parameter with type determined by GeneratorParam.

**Comment by slomp** [comment]
I'd also advocate for a more "generic" way to rely even less on encapsulated types.
For example, a generic declaration like `Input<void>` should allow for it to be later transformed into a "Buffer", or "Func', or "Scalar".
Something like: `::add_input(Layout, Type, Dim, Size)` (or add_scalar/add_buffer/add_func).

**Comment by abadams** [comment]
I'm not sure that could work, because different C++ syntax is available for scalar vs non-scalar input members (e.g. operator() exists)

**Comment by slomp** [comment]
Ah... indeed... :/

**Comment by steven-johnson** [comment]
To be clear: is the goal here to
- Allow declaring something like `Input<void>`, so that there is a required input, but whose type must be set in the build system?
- Allow calling `add_input(halide_type_t, ...)` from the configure method, to allow for dynamically-added inputs with dynamic type?
- Both?

**Comment by abadams** [comment]
Both.
