### ISSUE TITLE
Lowest supported Windows version

### ISSUE THREAD

**Issue by ongjunjie** [halide/Halide#5961]
The stack size expansion routine introduced in 59a04e4c68fae34d3dd59cfe2df586c0311cbaad uses the function `GetCurrentThreadStackLimits`. As this Windows API is only appered after Windows 8, or Windows Server 2012, the resulting binary can't run on Windows 7.

For now, support for Windows 7 can be easily restored by removing the check for remaining stack space and always expand the stack. The question to the dev team is should it be done? Understandably, supporting legacy systems require extra effort and resources. If the decision is to drop support for Windows 7 and earlier, it may a good idea to explicitly mention it somewhere.

**Comment by abadams** [comment]
Windows 7 went end-of-life over a year ago and stopped receiving security updates, so we can't really test on it without the test machine being insecure. If we can't test on it, we can't support it.

This only affects the compiler itself though. AOT pipelines compiled with Halide on a current OS may well still work on windows 7, though again this is not something we can test.

**Comment by alexreinking** [comment]
In #6034, we're explicitly setting a policy that we do not attempt to support the Halide _compiler_ (not AOT-compiled pipelines) on EOL platforms, like Windows 7, Ubuntu 19.04 (it is not LTS), macOS 10.13, etc.
