### ISSUE TITLE
Arithmetic operations of Generator Input are not associative

### ISSUE THREAD

**Issue by vakokako** [halide/Halide#5982]
Here is the code. The result depends on the presence of parentheses, even though it shouldn't:
```cpp
Input<int> aMaskSize = 5;

// wrong result (-3, 5)
Halide::RDom vBox(-aMaskSize / 2, aMaskSize);

// correct result (-2, 5)
Halide::RDom vBox(-(aMaskSize / 2), aMaskSize);

```

**Comment by shoaibkamil** [comment]
Halide uses Euclidean division, which will round toward -inf when the divisor is positive. So `-5/2 = round_to_neg_inf(-2.5) = -3` and `-(5/2) = -round_to_neg_inf(2.5) = -2`. 

[This explanation](https://harry.garrood.me/blog/integer-division/) may be helpful.
