### ISSUE TITLE
Duplicate -e argument specified in Makefile for bilateral_grid

### ISSUE THREAD

**Issue by TaylorZowtuk** [halide/Halide#6008]
https://github.com/halide/Halide/blob/75a079a853e98a7d1d7e2e685fb1242089a41460/apps/bilateral_grid/Makefile#L17

In the Makefile of bilatergal_grid, for the auto_schedule target, -e is specified twice, once as "-e $(GENERATOR_OUTPUTS)" and once as "-e static_library,c_header,schedule". 

In Generator.cpp's generate_filter_main_inner(), the arguments are parsed by creating a map and assigning key value pairs. This has the effect that only the last specified value for an arg will be used if an arg is specified multiple times (i.e. -e $(GENERATOR_OUTPUTS) is not used).
https://github.com/halide/Halide/blob/75a079a853e98a7d1d7e2e685fb1242089a41460/src/Generator.cpp#L810

This is a very minor issue but can give someone inspecting the Makefile the false impression that the $(GENERATOR_OUTPUTS) is used in some way (like that both of the values for the -e's might be appended together) for the bilatergal_grid auto_schedule target when it is not.

**Comment by alexreinking** [comment]
@steven-johnson - looks like you were the last one to touch this code. Can you take a look?
