### ISSUE TITLE
Segfault on Opentuner generated schedule

### ISSUE THREAD

**Issue by VinayVasista** [halide/Halide#602]
Hi,

I was trying opentuner to tune the local_laplacian app. Unfortunately all the schedules dumped were leading to segfaults. Here are the opentuner settings file and a generated random source I picked -
https://gist.github.com/VinayVasista/7c66ca40af892fb9a100
The codes are too long and tedious to read, so I wouldn't expect anyone to look at them in detail. Can anyone confirm whether this is reproducible and point out the reason for segfault, if you have any idea?

Thanks in advance

**Comment by VinayVasista** [comment]
Indeed I faced problems with the function names to use in tuner settings file, and finally resorted to setting each of them explicitly using literal strings. But otherwise everything was fine. The schedule found after 12 hours of autotuning ended up with exec time of ~300ms, while the one provided in the Halide source (after being tuned to the machine used) takes just around ~60ms on the same machine (16 cores, 1 thead pc).

Few other smaller pipelines seem to get good schedules performing close to those of what Halide source provides, but not better. However, the tuning time was not proportionate with the number of stages (12 hrs for all). I haven't tried feeding any seed schedules, but looks like its very hard for opentuner to always lead to anywhere near good schedules for medium/large apps much on its own, even after days.

**Comment by jrk** [comment]
Indeed, this is what I meant by struggling on larger pipelines. It's not so
much OpenTuner in general as the search heuristics and search space
representation in the Halide tuner in particular which are still too naive
to converge to high quality results on larger pipelines. We have prior
experience which suggests it should be possible to make this better (the
prototype autotuner used in our PLDI 2013 paper matched or exceeded
hand-tuned performance for everything in apps), but have not yet had time
to develop the OpenTuner-based autotuner to the same degree; it is much
more robust and maintainable on other axes, but still quite simple in its
search strategies.

**Comment by VinayVasista** [comment]
Yeah, I guessed that as it got more generic, loss of it's Halide-specificity might have been the reason for the average performance. In that case, it'll be really good to see an updated version of halidetuner. I hope that will be available soon.

**Comment by jrk** [comment]
Yes, it's a major area of interest, it's just been constrained by lack of
resources available to work on it.
