### ISSUE TITLE
Profiling halide Funcs on CPU

### ISSUE THREAD

**Issue by gchauras** [halide/Halide#604]
Is there any way we can get the runtime of each Halide Func for CPU. GPU debug targets show kernel execution time in the verbose output which can be parsed out and proves quite handy. Do we have something similar for CPU?

On a similar note, it would be really useful to have a Timer class that can simply return millisecond count. Right now, everyone writes their own timer and no believes each other's numbers unless they run it through their own timing code :)

**Comment by gchauras** [comment]
Can you tell me what the fields from HalideProf mean? Most are self explanatory. 
Fields: count, ticks-cum, msec-cum, %-cum, ticks-only, %-only
- just to confirm, ticks and msec are proportional
- what is the different between ticks-only and ticks-cum?
- the ticks-only count is negative sometimes - is that normal? 
I have no parallelization/vectorzation in my schedules.

**Comment by zvookin** [comment]
The only values are for time spent inside a given Func. The cummulative
ones include all callee Funcs as well. Ticks and time should be
proportional. Values are negative sometimes because HalideProf attempts to
take into account the overhead of the profiling mechanism itself. You can
add "-overhead 0" to turn the overhead accounting off.

-Z-

**Comment by gchauras** [comment]
Thanks.

**Comment by steven-johnson** [comment]
Re: the negative numbers, it's (unfortunately) a known problem that the
profiler isn't as accurate as we'd like. We've had "improve the profiler"
as a work item for a while now, but it's never bubbled to the top of the
stack. If anyone wants to take it on as a task, they are welcome to :-)
