### ISSUE TITLE
Batching of Funcs

### ISSUE THREAD

**Issue by twesterhout** [halide/Halide#6057]
Hello,

Suppose, I have some function which works on vectors:
```cpp
auto foo(Func x, Func y) -> Func {
    Func output;
    Var i;
    output(i) = sin(x(i) + y(i));
}
```
Is it possible to introduce another dimension and write a `batched_foo` in terms of `foo`? Something like this:
```cpp
auto batched_foo(Func x, Func y) -> Func {
    Func output, x_row, y_row;
    Var i, j;
    x_row(j) = x(i, j); // This doesn't work because "i" is undefined
    y_row(j) = y(i, j);
    output(i) = foo(x_row, y_row);
}
```
So basically I'm looking for a way to tell Halide to "slice" a tensor... Of course, it's possible to introduce batch dimensions from the start and write `foo` and `batched_foo` as:
```cpp
template <class Dimensions...>
auto foo(Func x, Func y, Dimensions... batch) -> Func {
    Func output;
    Var i;
    output(batch..., i) = sin(x(batch..., i) + y(batch..., i));
}

auto batched_foo(Func x, Func y) -> Func {
    Func output, x_row, y_row;
    Var i, j;
    output(i, j) = foo(x_row, y_row, i)(j);
}
```
but this is ugly and I'm hoping there's a better way.

Thanks!

**Comment by abadams** [comment]
There's actually builtin language support for this, using `Halide::_`:

```
auto foo(Func x, Func y) -> Func {
    Func output;
    Var i;
    output(i, _) = sin(x(i, _) + y(i, _));
}
```

The underscore binds to any number of dimensions in calls on the RHS, and reproduces those dimension in the LHS for the definition, so "foo" can be used for any dimensionality. An example of this is the downsample/upsample helpers here, which are used for both 2 and 3-dimensional Funcs elsewhere in this generator:
https://github.com/halide/Halide/blob/master/apps/local_laplacian/local_laplacian_generator.cpp#L228

**Comment by twesterhout** [comment]
This answers my question, thank you!
