### ISSUE TITLE
Cannot find GENERATING TRAINING DATA

### ISSUE THREAD

**Issue by minjac** [halide/Halide#6058]
Hi, I have learned Halide for a few weeks, but I do not know how to generate training data randomly for training cost model.
In _Learning to Optimize Halide with Tree Search and Random Programs_, the author says the source code is in the supplemental material, but I cannot found that.
I do not find source code about randomly generating training data in this project. Could you tell me where I could find this source code.
Thanks.

**Comment by abadams** [comment]
The supplemental material for that paper is the branch "standalone_autoscheduler". The random pipeline generator is here: https://github.com/halide/Halide/tree/standalone_autoscheduler/apps/random_pipeline

**Comment by ryanstout** [comment]
@abadams Just curious, any plans to merge in standalone_autoscheduler or standalone_autoscheduler_gpu? I would guess if I can get adams2019 trained on my hardware it would beat any of my hand done schedules. (Also, thanks for all of the hard work to create/maintain Halide!)

@minjac if you do figure out how to train the adams2019, please let me know the details :-)  I've got some armv7 and aarch64 hardware that I've been wanting to train on, but couldn't figure out how to get the training working.

**Comment by abadams** [comment]
Adams2019 was merged! It's in src/autoschedulers. If you have specific apps you want to schedule, I'd just use it in autotuning mode rather that worrying about doing a big training job.

**Comment by ryanstout** [comment]
@abadams thanks. I guess I was a bit confused since it looks like the random_pipeline stuff didn't get merged in. Unfortunately, my pipeline is using the python bindings, and I wasn't able to get it work with autotune_loop.sh (since it expects a generator).
