### ISSUE TITLE
[upstream llvm] removal of CodeGenOptions::StackAlignmentOverride

### ISSUE THREAD

**Issue by nickdesaulniers** [halide/Halide#6079]
I'm removing this upstream in https://reviews.llvm.org/D103048; IIRC Halide is using this.  Once rebased, `Module::getOverrideStackAlignment` should be used instead.

**Comment by steven-johnson** [comment]
Thanks for the heads-up! I'll update Halide once it's ready.

**Comment by steven-johnson** [comment]
We only 'use' it to initialize it to zero in the `TargetOptions` struct. For a value of zero, do we actually *need* to respecify it via Module::getOverrideStackAlignment, or can we just ignore it?

**Comment by nickdesaulniers** [comment]
fine to ignore; I doubt your users are messing with the stack alignment (unless they're the x86 Linux kernel, or mips).  Now the value is encoded in the IR via module level attribute, so that it's not lost during LTO.

**Comment by nickdesaulniers** [comment]
or if you're using a non-standard stack alignment on PTX (if that's even supported)
