### ISSUE TITLE
Stride confusion

### ISSUE THREAD

**Issue by popizdeh** [halide/Halide#6089]
I would expect the following generator to convert planar input buffer to line-by-line planar output buffer but instead I get `Error: Constraint violated: output.stride.2 (32) == 8 (8)` at runtime. Can someone please explain what's going on here? I've tried setting stride for dim(1) to 24 but that errors out as well.

```
class Testing : public Halide::Generator<Testing>
{
public:
	Input<Buffer<uint8_t>> input{"input", 3};
	Output<Buffer<uint8_t>> output{"output", 3};
	
	void generate()
	{
		Halide::Var x, y, c;

		output(x, y, z) = input(x, y, z);

		output.dim(2).set_stride(8);
	}
};

HALIDE_REGISTER_GENERATOR(Testing, testing)
```

```
Halide::Runtime::Buffer<uint8_t> input(data, 8, 4, 3);
Halide::Runtime::Buffer<uint8_t> output(8, 4, 3);
testing(input, output);
```

**Comment by abadams** [comment]
This issue that you're passing two planar buffers. You could do something like this:
```
Halide::Runtime::Buffer<uint8_t> input(data, 8, 4, 3);
Halide::Runtime::Buffer<uint8_t> output(8, 3, 4);
output.transpose(1, 2);
testing(input, output);
```

For full control, use the constructor for Halide::Runtime::Buffer that lets you specify an array of halide_dimension_t.

**Comment by popizdeh** [comment]
Thanks for the quick answer Andrew, this does what I wanted but unfortunately I still don't understand how exactly. I guess I'm surprised that stride is not mentioned anywhere in your answer, and my code doesn't seem to require the `set_stride` call at all? I was under the impression that strides are used to control this but you're changing the shape of the output buffer. I guess the shape controls the stride but I don't fully understand this relationship.

The code I posted was my first step in trying to understand strides. What I'm really trying to do is go from block based buffer of IDCT coefficients to scanline order pixel buffer.

So let's say I had a 24x16 pixel image, block size is 8x8. My input buffer would be 8x8x6 for 6 blocks of coefficients.

```
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 <- first 8x8 block, all bytes are zero
11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111
22222222 22222222 22222222 22222222 22222222 22222222 22222222 22222222
33333333 33333333 33333333 33333333 33333333 33333333 33333333 33333333
44444444 44444444 44444444 44444444 44444444 44444444 44444444 44444444
55555555 55555555 55555555 55555555 55555555 55555555 55555555 55555555 
```

I don't understand how to get this format in the output buffer?

```
00000000 11111111 22222222 <- first scanline of 24 pixels, first 8 pixels of first 3 blocks
00000000 11111111 22222222
00000000 11111111 22222222
00000000 11111111 22222222
00000000 11111111 22222222
00000000 11111111 22222222
00000000 11111111 22222222
00000000 11111111 22222222
33333333 44444444 55555555
33333333 44444444 55555555
33333333 44444444 55555555
33333333 44444444 55555555
33333333 44444444 55555555
33333333 44444444 55555555
33333333 44444444 55555555
```

**Comment by abadams** [comment]
The way to handle that output layout in Halide requires a 4D buffer. The input is 8x8x6x1, and the output is 8x3x8x2

**Comment by popizdeh** [comment]
Thanks mate!
