### ISSUE TITLE
Buffer::device_handle() to OpenGL

### ISSUE THREAD

**Issue by gchauras** [halide/Halide#609]
Can I use Buffer::device_handle() to transfer a CUDA or OpenCL buffer to OpenGL for display in a realtime application?

**Comment by dsharletg** [comment]
Not exactly Buffer::device_handle, but if you use Buffer::raw_buffer and set the dev field of the buffer_t to a cl_mem object created with clCreateFromGLTexture/clCreateFromGLBuffer, it should work. I believe at least for OpenCL, you'll need to create your own OpenCL context with OpenGL sharing enabled for this to work. I'm not as familiar with the CUDA mechanisms for this, but it's probably similar. 

I think I wrote a more detailed reply to the Halide-dev mailing list at one point on how to do this, but I can't find it right now.
