### ISSUE TITLE
Standard Bit Operator Intrinsics

### ISSUE THREAD

**Issue by kor01** [halide/Halide#6096]
How to call bit-related intrinsics such as __builtin_popcount __builtin_ctz from halide code?
It will be helpful in implementing spatial structures like sparse voxel octree.

**Comment by vksnk** [comment]
These ops are available as `popcount` and `count_leading_zeros` correspondingly, see https://github.com/halide/Halide/blob/master/src/IROperator.h#L1200-L1209

**Comment by kor01** [comment]
> These ops are available as `popcount` and `count_leading_zeros` correspondingly, see https://github.com/halide/Halide/blob/master/src/IROperator.h#L1200-L1209

Thank you, this is life-saving.
