### ISSUE TITLE
Halide::Runtime::Buffer does not use halide_malloc and halide_free.

### ISSUE THREAD

**Issue by mcourteaux** [halide/Halide#6127]
https://github.com/halide/Halide/blob/a914574d504bc137a9e23545bbbf5d5504f1c485/src/runtime/HalideBuffer.h#L743

The documentation of the class says that the default allocator functions are malloc and free, whereas the HalideRuntime.h specifies halide_malloc and halide_free for memory management.

Additionally, Halide::Runtime::Buffer does not allow for creating buffers with other allocators. You always go through an allocate() call using the default malloc/free, which is wasteful if you want to use a custom allocator afterwards.

**Comment by steven-johnson** [comment]
> You always go through an allocate() call using the default malloc/free

It's awkward, but you should be able to avoid this by calling the ctor with a NULL data ptr, then an explicit call to allocate(), eg

```
    std::vector<halide_dimension_t> dims = ...;
    HalideBuffer<uint8_t> new_buffer(nullptr, (int)dims.size(), dims.data());
    new_buffer.allocate(my_allocate_fn, my_deallocate_fn);
```
