### ISSUE TITLE
Buffer size for Tuple realization

### ISSUE THREAD

**Issue by gchauras** [halide/Halide#613]
If I define a func as:
f(x,y) = Tuple(A(x,y), B(x,y))

- Can I realize them in buffers of different sizes?
- Depending upon the realization buffers of f(x,y)[0] and f(x,y)[1] (or downstream usage), the bounds of x and y will be different for the two buffers. How does the bound inference for f work? Is it computed separately for the two realization buffers or taken as the superset?

If the bounds are computed as a superset, the bound inference for A and B will also get affected. However, I think the following hack still allows me to restrict the bounds of A and B.
f(x,y) = undef()
f(r1.x, r1.y) = Tuple(A(r1.x, r1.y), undef())
f(r2.x, r2.y) = Tuple(undef(), B(r1.x, r1.y))

**Comment by abadams** [comment]
It's an error if the buffers in a realization have different sizes. They're
supposed to all be the same size, so the bounds inference results for A and
B will be the same.

Your hack is interesting - I think it will still require the output buffers
to be the same size, but it will only fill in a part of each (and hence
bounds inference for A and B can be different, as you say).

**Comment by jrk** [comment]
Related: are multiple outputs (with non-share domains) still on the table?

**Comment by abadams** [comment]
They are, pending a few outstanding CLs. Separating the compile_to_foo
methods from Funcs (as Dillon is proposing) will make that more
straightforward: E.g we could end up with syntax like:

compile_to_object({func1, func2}, args, target);
