### ISSUE TITLE
Nested GuardWithIf generates predicated store on GPU

### ISSUE THREAD

**Issue by shoaibkamil** [halide/Halide#6157]
Recent changes to use predication always seem to have broken the ability on the GPU to have both the `gpu_tile` and `vectorize` tail strategy be `GuardWithIf`.  Here's a small repro:

```
#include "Halide.h"
#include <iostream>
#include <stdio.h>

using namespace Halide;

int main(int argc, char **argv) {

    Var x("x"), y("y"), xi("xi"), yi("yi");
    Func f("f");

    printf("Defining function...\n");

    f(x, y) = x * y + 2.4f;

    Target target = get_jit_target_from_environment();
    if (target.has_gpu_feature()) {
      f.gpu_tile(x, y, xi, yi, 8, 8, TailStrategy::GuardWithIf).vectorize(xi, 4, TailStrategy::GuardWithIf);
    }

    printf("Realizing function...\n");

    Buffer<float> imf = f.realize({32, 32}, target);

    // Check the result was what we expected
    for (int i = 0; i < 32; i++) {
        for (int j = 0; j < 32; j++) {
            float correct = i * j + 2.4f;
            if (fabs(imf(i, j) - correct) > 0.001f) {
                printf("imf[%d, %d] = %f instead of %f\n", i, j, imf(i, j), correct);
                return -1;
            }
        }
    }

    printf("Success!\n");
    return 0;
}
```

This causes the following error:
```
User error triggered at /Users/kamil/Documents/work/adobe/halide_master/src/CodeGen_Metal_Dev.cpp:422
Condition failed: is_const_one(op->predicate)
Error: (at test/correctness/gpu_vectorize.cpp:23)
Predicated store is not supported inside Metal kernel.
```

Everything seems to work fine if only using `GuardWithIf` for the `vectorize()` call, but not when both `gpu_tile()` and `vectorize()` use that tail strategy.

**Comment by shoaibkamil** [comment]
@dsharlet I think this was introduced by your recent change-- any hints on where I should look to start would be awesome.

**Comment by dsharletg** [comment]
It was probably this change here: https://github.com/halide/Halide/pull/6126/files#diff-2959004c67bb4caa6a994f4055f3867ba465ce9be739ff729cc9f616ec151d9eL399-L400

However, it would be unfortunate to add back all of that logic (a lot of plumbing of the target). I think it would be best if instead the backends that didn't support predicated load/store scalarized instead. Do you think that would be reasonable codegen for the GPU?

**Comment by shoaibkamil** [comment]
Yes, I think that would be reasonable-- I can do a more comprehensive performance check once we fix.  Would you like me to take a stab at it?

**Comment by dsharletg** [comment]
If you want to, if not, I can try to get to it later today.

**Comment by shoaibkamil** [comment]
I'm taking a stab at it, will create a draft PR.  Thanks @dsharletg!
