### ISSUE TITLE
run-clang-tidy.sh script is broken

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#6163]
At top-of-tree, running it locally (either directly or via make clang-tidy) fails with `*** No rule to make target `HalideIncludes'.  Stop.`. My guess is that some recent CMake change inadvertently broke it?

**Comment by steven-johnson** [comment]
Tagging @alexreinking to see if `HalideIncludes` rings any bells.

**Comment by alexreinking** [comment]
That's very strange... the `HalideIncludes` target is created here:

https://github.com/halide/Halide/blob/2b8ec44f2c1cc701e889718003f0f571dbb2ebe3/src/CMakeLists.txt#L356

**Comment by alexreinking** [comment]
I can reproduce this when the `CMAKE_GENERATOR` environment variable is set to `Ninja`. The script assumes Make will be used.
