### ISSUE TITLE
Incorrect bounds checking for some schedules

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#6186]
Run the following:

```
int main(int argc, char **argv) {
    Var x, y, c, chunk;

    ImageParam input(UInt(8), 3);

    Func intermed, output;
    intermed(x, y, c) = input(x, y, c);
    output(x, y, c) = intermed(x, y, c);

    // schedule
    intermed.compute_at(output, y);
    output.split(y, chunk, y, 64, TailStrategy::GuardWithIf);

    Buffer<uint8_t> input_buf(100, 100, 3);
    input_buf.fill(0);
    input.set(input_buf);

    auto result = output.realize({100, 100, 3});

    printf("Success!\n");

    return 0;
}
```

Expected: `Success`
Actual: `Input buffer input is accessed at 127, which is beyond the max (99) in dimension 1`

Initial debugging points to #6126 as the injection point.

**Comment by steven-johnson** [comment]
From looking at before-vs-after code, the issue appears to be related to the fact that we previously hoisted the `output.s0.y.guarded` variable out of the loop in which it was used, and it ends up being used for the bounds-checking requirement. 

In #6126, we (quite reasonably) stopped hoisting nonpure Exprs (ScheduleFunctions.cpp:326), and since `output.s0.y.guarded` is a call to `promise_clamped` (which isn't pure), we stopped hoisting it.

The part that I'm still scratching my head over is how this should have worked in the first place.

**Comment by steven-johnson** [comment]
FWIW, I can "fix" this my simply making that promise_clamped into a PureIntrinsic, but that makes me nervous; I feel reasonably confident that the specific promise_clamped calls that we insert in ApplySplit are safe to treat as pure, because, well, we were doing that before. But it seems like a bad precedent, and it also feels like this shouldn't rely on that.

**Comment by dsharletg** [comment]
Here's a slightly further simplified reproducer:

```
#include "Halide.h"

using namespace Halide;

int main(int argc, char **argv) {
    Var x, y, chunk;

    ImageParam input(UInt(8), 2);

    Func intermed, output;
    intermed(x, y) = input(x, y);
    output(x, y) = intermed(x, y);

    // schedule
    intermed.compute_at(output, y);
    output.split(y, chunk, y, 64, TailStrategy::GuardWithIf);

    Buffer<uint8_t> input_buf(100, 100);
    input_buf.fill(0);
    input.set(input_buf);

    output.output_buffer().dim(0).set_min(0).set_extent(100);
    output.output_buffer().dim(1).set_min(0).set_extent(100);

    auto result = output.realize({100, 100});

    printf("Success!\n");

    return 0;
}
```
