### ISSUE TITLE
 Local Laplacian example fails with armeabi or armeabi-v7a

### ISSUE THREAD

**Issue by yichang** [halide/Halide#619]
Hi! 

The LLVM fails when compiling the provided apps/local_laplacian/ examples to Android. In particular, the following errors show up:

SplitVectorResult #0: 0x7fd5c390df10: v8i32 = llvm.arm.neon.vcvtfp2fxs 0x7fd5c390ad10, 0x7fd5c390fb10, 0x7fd5c38faf10 [ID=0]

LLVM ERROR: Do not know how to split the result of this operator!

SplitVectorResult #0: 0x7f9e130cae10: v8i32 = llvm.arm.neon.vcvtfp2fxs 0x7f9e14084910, 0x7f9e130bdb10, 0x7f9e130c6d10 [ID=0]

LLVM ERROR: Do not know how to split the result of this operator!

Steps to reproduce (platform: MACOSX, Apple LLVM version 3.3.1):
(1) C++ on halide: 
halide_root=../../third_party/halide/
c++  ../../third_party/halide/apps/local_laplacian/local_laplacian.cpp\
    ../../third_party/halide/bin/libHalide.a\
    -I ../../third_party/halide/apps/support/\
    -I ../../third_party/halide/include/\
    -L ../../third_party/halide/bin/ -lHalide\
    -ldl -lpthread -lz -lpng16\

(2) Compile to different platform
for archs in arm-32-android,armeabi arm-32-android-armv7s,armeabi-v7a, x86-32-android,x86; do
    IFS=,
    set $archs
    hl_target=$1
    android_abi=$2
    mkdir -p halide_generated_$android_abi
    cd halide_generated_$android_abi
    HL_TARGET=$hl_target DYLD_LIBRARY_PATH=../../../third_party/halide/bin LD_LIBRARY_PATH=../../../third_party/halide/bin ../a.out 8
    cd ..
    unset IFS
done

Other syndromes: 
- It works for x86_ case
- It works for other examples like apps/bilateral_grid apps/blur
- I wonder if some operations in local_laplacian.cpp are not supported by current armeabi...

Thanks for the help!

**Comment by aam** [comment]
Couple more pieces of data: 
Android generation seems to work fine on LLVM trunk(3.6), but fails yet with different error on LLVM 3.5:
=== LLVM 3.6 ===
$ $LLVM_CONFIG --version
3.6.0svn
$ $CLANG --version
clang version 3.6.0 (trunk 225298)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
local_laplacian aam$ ./build.sh
arm-32-android...
done
arm-32-android-armv7s...
done
x86-32-android...
done

=== LLVM 3.5 ===
$ $LLVM_CONFIG --version
3.5.0svn
$ $CLANG --version
clang version 3.5.0 (219331)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
$ ./build.sh
arm-32-android...
Assertion failed: ((!From->hasAnyUseOfValue(i) || From->getValueType(i) == To->getValueType(i)) && "Cannot use this version of ReplaceAllUsesWith!"), function ReplaceAllUsesWith, file /Users/aam/Documents/halide-llvm_35/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp, line 5904.
./build.sh: line 5: 10731 Abort trap: 6           HL_TARGET=$hl_target DYLD_LIBRARY_PATH=../../../bin ../a.out 8
done
arm-32-android-armv7s...
Assertion failed: ((!From->hasAnyUseOfValue(i) || From->getValueType(i) == To->getValueType(i)) && "Cannot use this version of ReplaceAllUsesWith!"), function ReplaceAllUsesWith, file /Users/aam/Documents/halide-llvm_35/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp, line 5904.
./build.sh: line 5: 10733 Abort trap: 6           HL_TARGET=$hl_target DYLD_LIBRARY_PATH=../../../bin ../a.out 8
done
x86-32-android...
done

Here is build.sh I put in local_laplacian folder:
===
#!/bin/bash
c++ local_laplacian.cpp ../../bin/libHalide.a -I ../support/ -I ../../include/ -L ../../bin/ -lHalide -ldl -lpthread -lz -lpng16

for archs in arm-32-android,armeabi arm-32-android-armv7s,armeabi-v7a, x86-32-android,x86; do
IFS=,
set $archs
hl_target=$1
android_abi=$2
mkdir -p halide_generated_$android_abi
cd halide_generated_$android_abi
echo $hl_target...
HL_TARGET=$hl_target DYLD_LIBRARY_PATH=../../../bin ../a.out 8
echo done
cd ..
unset IFS
done
===

**Comment by yichang** [comment]
Alexander,

Thanks for sharing, and may I ask if you have any trouble compiling Halide with llvm 3.6?
I have the following error:

llvm/build/Debug+Asserts/bin/llvm-as build/initmod.cuda_32.ll -o build/initmod.cuda_32.bc
llvm/build/Debug+Asserts/bin/llvm-as: build/initmod.cuda_32.ll:1780:6: error:
unexpected type in metadata definition
!0 = metadata !{metadata !"int", metadata !1}

In #435  Andrew mentioned that Halide is not maintained for llvm 3.6 at this point.

**Comment by abadams** [comment]
We do maintain Halide for llvm 3.6 - in fact that's our primary llvm
version. However llvm 3.6 is the version under active development by the
llvm guys, so it keeps changing, and so we change Halide to match it. This
means we don't support *old* versions of llvm 3.6 - only the newest one
available via svn.

I also get Alexander's bug - the issue with llvm 3.5 appears to be llvm
barfing on the non-native vector widths. If you replace vectorize(x, 8)
with vectorize(x, 4) everywhere then it works. You might want to try that
too YiChang, your error looks similar.

**Comment by aam** [comment]
@yichang , I am able to build trunk llvm3.6 on Mac without problems now.
To build llvm I follow cmake-based steps from https://github.com/halide/Halide#building-halide with all targets and one additional argument LLVM_BUILD_32_BITS=OFF specified, so full list of defines for cmake llvm invocation looks like this:
```
-DLLVM_ENABLE_TERMINFO=OFF -DLLVM_TARGETS_TO_BUILD=all -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_BUILD_TYPE=Release -DLLVM_BUILD_32_BITS=OFF
```

**Comment by yichang** [comment]
Thanks Alexander's feedback. I tried LLVM 3.6 and it compiled.
