### ISSUE TITLE
prefetch ignores offset in some circumstances

### ISSUE THREAD

**Issue by abadams** [halide/Halide#6219]
Consider the following attempt to prefetch:

```

#include "Halide.h"

using namespace Halide;

int main(int argc, char **argv) {
    Func f;
    Var x, y;
    f(x, y) = x + y;
    f.compute_root();

    Func g;

    g(x, y) = f(x, y);

    Var xo, yo, xi, yi;
    g.tile(x, y, xo, yo, xi, yi, 8, 4, TailStrategy::RoundUp)
        .vectorize(xi)
        .unroll(yi);

    f.in().compute_at(g, xo).vectorize(x).unroll(y).prefetch(f, y, x, 123, PrefetchBoundStrategy::NonFaulting);

    g.realize({1024, 1024});

    return 0;
}
```

The prefetch doesn't actually look ahead to x + 123. It just prefetches the address it loads on the next instruction. Changing f.in() to vectorize(x, 8) doesn't seem to change anything, even though x is now the loop over vectors instead of the vectorized loop. Either way I get the IR:

```  
      prefetch(f, ((g.s0.x.xo*2) + t13)*4, 1, 16)
      f_global_wrapper$0[ramp(0, 1, 8)] = f[ramp(((g.s0.x.xo*2) + t13)*4, 1, 8) aligned(8, 0)]
      prefetch(f, (g.s0.x.xo*8) + t14, 1, 16)
      f_global_wrapper$0[ramp(8, 1, 8)] = f[ramp((g.s0.x.xo*8) + t14, 1, 8) aligned(8, 0)]
      prefetch(f, (g.s0.x.xo*8) + t15, 1, 16)
      f_global_wrapper$0[ramp(16, 1, 8)] = f[ramp((g.s0.x.xo*8) + t15, 1, 8) aligned(8, 0)]
      prefetch(f, (g.s0.x.xo*8) + t16, 1, 16)
      f_global_wrapper$0[ramp(24, 1, 8)] = f[ramp((g.s0.x.xo*8) + t16, 1, 8) aligned(8, 0)]
```

**Comment by steven-johnson** [comment]
Any idea if it worked prior to the recent restructuring of the prefetch directive? (ie, is it a new breakage or an always-broken thing?)

**Comment by abadams** [comment]
I am not sure. This was new code. I haven't used prefetch a lot, so I would not be surprised if it were already broken.

**Comment by abadams** [comment]
I can find a few things wrong. Prefetch works by taking the loop body from the first var, and replacing the second var with the second var + offset by wrapping an outer let stmt. 

1) This requires the second var to be an outer loop, or it won't have been defined yet. There's no check for this - it just silently doesn't work.

2) It also breaks if the second var is a loop with extent 1, because then the loop var isn't used in the body - it has been replaced with the constant zero.

3) Ah you say, why not just reorder the x loop outermost then? It's a vectorized loop so the effect is the same as if it were innermost! Well, vectorizing a prefetch statement aborts in codegen:

```    
  (int32x8)prefetch(x8(f), ramp((((g.s0.x.xo*2) + t13)*4) + 123, 1, 8), x8(1), x8(16))
...
Internal Error at /home/abadams/projects/Halide_gaussian_blur_app/src/IR.cpp:14 Condition failed: t.lanes() == v.type().lanes(): Cast may not change vector widths
```

4) In an attempt to get a nearby schedule, I tried the following:

```
  f
        .in()
        .compute_at(g, xo)
        .split(x, xo, xi, 4)
        .vectorize(xi)
        .unroll(xo)
        .reorder(xi, y, xo)
        .unroll(y)
        .prefetch(f, y, xo, 123 / 4, PrefetchBoundStrategy::NonFaulting);
```

This silently does nothing too. I fetch in the xo direction, xo has extent 2, and it's an outside the loop I'm fetching at, so it should work. right? It doesn't, because inside the y loop there are no more uses of xo anyway. It has been folded into one of the .base variables defined just inside the xo loop, so the box required does not correctly get wound forwards. The box-winding-forwards code also needs to capture and replay any outer lets that depend on the loop variable.

5)  Ok, this code should dodge all the issues above:
```
   f
        .in()
        .compute_at(g, xo)
        .split(x, xo, xi, 4, TailStrategy::RoundUp)
        .vectorize(xi)
        .unroll(xo)
        .reorder(xi, xo, y)
        .unroll(y)
        .prefetch(f, xo, xo, 123 / 4, PrefetchBoundStrategy::NonFaulting);

```

All uses of xo are inside the prefetch location, and xo has non-trivial extent, so they exist and haven't been replaced with constants. This time it doesn't work because the variable it rolls forwards is "f_global_wrapper$0.s0.xo", which is not correct. The loop variable is called "f_global_wrapper$0.s0.x.xo", so the fifth bug is that prefetch only works on unsplit loops.

**Comment by steven-johnson** [comment]
At least (1) and (2) are fixed by #6225. 

I wasn't able to repeat (3) -- can you provide an explicit repro snippet for me?

In (4) and (5), are you intending the function do a prefetch from itself?

**Comment by abadams** [comment]
In 4 and 5, f.in() is prefetching f, so it's not a function from itself.

**Comment by steven-johnson** [comment]
> In 4 and 5, f.in() is prefetching f, so it's not a function from itself.

Ah, gotcha. And I'm able to repro (3) now.

**Comment by steven-johnson** [comment]
Pretty sure this is fixed.
