### ISSUE TITLE
Internal error: Let of undefined

### ISSUE THREAD

**Issue by yongyi781** [halide/Halide#622]
The error occurs when compiling the following pipeline (doesn't matter whether it's JIT or compile_to_file, and the definition of myExtern doesn't matter):

	Func generate;
	generate(x, y) = x + y;

	Func copy;
	copy.define_extern("myExtern", { generate }, Float(32), 2);

	Func output;
	output(x, y) = copy(x, y) + generate(clamp(x, 0, 100), clamp(y, 0, 100));

	output.vectorize(x, 4);
	generate.compute_root();

	output.compile_to_file("test");

This is the output:

	Internal error at C:\Users\Yongyi\Documents\GitHub\Halide\src\IR.cpp:315
	Condition failed: body.defined()
	Let of undefined

The error goes away if you comment out the line output.vectorize(x, 4); In addition, it also goes away if output is just defined as copy(x, y) or as generate(clamp(x, 0, 100), clamp(y, 0, 100)). It somehow requires both of them to produce the error. I am completely perplexed.

**Comment by abadams** [comment]
An oversight in specialize branched loops. Should be fixed now.
