### ISSUE TITLE
Observing slow performance for Halide standalone on Hexagon/ HVX (even with autoscheduler)

### ISSUE THREAD

**Issue by saxena-ab** [halide/Halide#6231]
I am trying a Nearest neighbor image resize algorithm using Halide.
Following is the setup details:
- Hexagon SDK: 4.3.0.0
- Using standalone mode

Issue:
- Execution time for Halide is quite slow for Hexagon. Cpu execution with pure non vectorized C++ code is faster for the same algorithm.
- Tried some schedules using align_storage, vectorize, tile, split, parallel, but got the best performance with autoscheduler. However, that was still slower than C++ non vectorized version.

Resource & Code:
- I made a simple example here: https://github.com/AbyShk95/Halide_standalone_example

I would really appreciate it if someone could give some insight as to how I can get better performance and/ or point me if I am missing something with code setup of dsp.

@pranavb-ca  @dpalermo

**Comment by alexreinking** [comment]
> Hi, i am working on dsp recently and would like to know if Halide supports dsp v73 or newer? I only saw the latest it can support is v68

The Qualcomm release of Halide supports v79

https://docs.qualcomm.com/bundle/publicresource/topics/80-PD002-1/getting_started.html
