### ISSUE TITLE
Bounds inference confused by undef update definitions

### ISSUE THREAD

**Issue by gchauras** [halide/Halide#625]
It looks like bounds inference uses the domain of the RVar in the update defs as one of the factors in determining the bounds. This happens even if the update def is left undef() - in that case bounds inference should simply ignore the update, as it does if the pure-def is left undef(). 

"Why would someone do this is a fair question" - but I guess this still counts as a bug.

Reproducing example:

```
#include <iostream>
#include <Halide.h>

using namespace Halide;

int main(int argc, char **argv) {
    Func R("R"), S("S");
    Var x,y;
    RDom r(0,10);

    R(x,y) = 1.0f;
    R(r,y) = undef<float>();
    R(x,r) = R(x,r)+1;

    S(y) = R(0,y);

    S.bound(y,0,10);
    S.compute_root();
    R.compute_root();
    S.compile_to_lowered_stmt("stmt.html", HTML);

    S.realize(10);

    return 0;
}
```

**Comment by abadams** [comment]
Bounds inference happens before undefs are handled, so it treats storing an
undef the same as storing any other value. I'm loathe to call this a bug,
because it complicates things if people try to use undefs to affect bounds
inference. I'd rather keep them independent.

**Comment by gchauras** [comment]
OK. fair point.
