### ISSUE TITLE
Httpd Service not started with undefined symbol "dlopen" error

### ISSUE THREAD

**Issue by ashokrajag** [halide/Halide#6261]
Hi,

We are using an application that constantly functioning in RHEL 6.10. Our application internally uses an apache server (Version is 2.4.35). Now, we tried to upgrade the existing OS (RHEL 6.10) to RHEL 8.4. After upgrading to the new OS, httpd service (internal server) is not started and ends up with the below error.

> /xxx/xxx/xxx/apache/bin/httpd: symbol lookup error: /xxx/xxx/xxx/apache/lib/libapr-1.so.0: undefined symbol: dlopen

Also, we have tried installing the "libapr*" Package, but we got the below error,

> No match for argument: libapr1
> Error: Unable to find a match: libapr1

Post that, we downloaded the package from the website and installed it. But it also didn't help us.

Please let us know if you need any details and kindly provide us a way to overcome this issue.

**Comment by zvookin** [comment]
While this may be connected to Halide, it is a bit difficult to see how. It sounds like something is missing a ```-ldl``` flag on the link line or perhaps even needs to have it be made dynamically visible, though that really doesn't make sense for ```dlopen```. Halide doesn't depend on any apache stuff so far as I know.
