### ISSUE TITLE
Halide requires a version of LLVM/GCC that is too high

### ISSUE THREAD

**Issue by jinderek** [halide/Halide#6268]
Halide requires a version of LLVM/GCC that is too high, making it impossible to deploy on some machines.
On some machines, the GCC version is only 4.8.5.
Although it is possible to upgrade the GCC version of a machine, this causes some problems such as the cost of the upgrade and scalability (e.g. having a very large number of machines).

I wonder if there is a better way than upgrading the GCC version of the machine?

(Maybe Compiled AOT pipelines is an option?)

**Comment by abadams** [comment]
AOT-compiled Halide pipelines have very minimal requirements on the host system. They don't need a compiler or llvm version of any sort. If you're deploying to a large number of machines, either use AOT, or if you need JIT use containers that bundle the dependencies.

For the compiler itself (libHalide), we have a small team and it's not feasible for us to support very old compilers and llvm versions.
