### ISSUE TITLE
Unhandled intrinsic in C backend: absd

### ISSUE THREAD

**Issue by jaakkotuosa** [halide/Halide#637]
Hi!
I came across the following error:
```
Internal error at src/CodeGen_C.cpp:942
Unhandled intrinsic in C backend: absd
Aborted
```

It can be reproduced with this test program:
```
// g++ absd.cpp -L ./bin -lHalide -o absd && LD_LIBRARY_PATH=bin HL_TARGET=opencl ./absd
#include "include/Halide.h"

using namespace Halide;

int main(int, char**)
{
    Var x, y;
    Func f;
    f(x, y) = absd(x, y);

    f.gpu_tile(x, y, 10, 10);

    f.compile_to_file("foo", get_target_from_environment());
}
```

I saw absd was merged lately from https://github.com/halide/Halide/pull/615. Maybe `absd` support needs to be added to CodeGen_C.cpp? Or is there something funny with the test (it's not clear for me why C compilation is called in this case)?

**Comment by dsharletg** [comment]
Thanks for reporting this, I will fix it shortly. 

> Or is there something funny with the test (it's not clear for me why C compilation is called in this case)?

The reason this happens is that the OpenCL target uses the C backend internally to generate the kernel code (OpenCL C).
