### ISSUE TITLE
Compilation fails on Windows 10 Enterprise, Visual Studio 2019

### ISSUE THREAD

**Issue by ashishUthama** [halide/Halide#6411]
We use cmake to build the sln and then compile that.
Failure message:

2>S:\authama\3p\3p\derived\win64\Halide\src\Util.cpp(683,5): error C3861: 'GetCurrentThreadStackLimits': identifier not found

@alexreinking - noticed that we added this in https://github.com/halide/Halide/commit/59a04e4c68fae34d3dd59cfe2df586c0311cbaad 
Would you have any suggestions for me to try?

And https://github.com/halide/Halide/blob/master/README.md lists Windows 10 (20H2), not familiar with Windows - but I assume its not too different from Windows 10 Enterprise.

**Comment by alexreinking** [comment]
This API has been included since Windows 8 and Windows Server 2012.

I'm not sure what's going wrong for you.

Docs for reference: https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getcurrentthreadstacklimits

**Comment by ashishUthama** [comment]
Visual Studio does open that header when I look for its definition. Unsure whats going on right now. 

I plan to switch to the release binaries - so I wont be investigating this further.

**Comment by alexreinking** [comment]
Okay, we'll chalk it up to a random environment failure for now. If someone else hits this problem, we'll reopen this issue.
