### ISSUE TITLE
Issue with Realize Dimensions Incorrect

### ISSUE THREAD

**Issue by matthewwen** [halide/Halide#6417]
I'm using Halide 13
```
func(x, y) = Tuple(1, 2, 3);
return func.realize({num_width, num_height, 3}, target, map);
```
So the expected dimension for this is suppose to be 3, but on response variable, it says that the dimensions is 2. Isn't it suppose to be 3? This is running on JIT btw. 
```
Halide::Buffer<uint8_t> response = function_call("bggr"); // response.dimensions() == 2 not 3
save_image(response, output_img); 
```

**Comment by abadams** [comment]
What you have is a two-dimensional Func that returns a tuple of three values. I think you want:

```
func(x, y, c) = mux(c, {1, 2, 3});
return func.realize({num_width, num_height, 3}, target, map);
```
