### ISSUE TITLE
Update README.md with latest LLVM v13 toolchain.

### ISSUE THREAD

**Issue by derek-gerstmann** [halide/Halide#6420]
Now that LLVM/Clang v13 is out, we should probably update the README.md to indicate the currently supported toolchains and configs to match.

**Comment by alexreinking** [comment]
Are you referring to the https://github.com/halide/Halide#platform-support section? That isn't tied to the LLVM release, but to the buildbot hardware.

**Comment by derek-gerstmann** [comment]
Ah, okay! So we don't officially build against v13?

**Comment by alexreinking** [comment]
Our first-party binary releases of Halide N are built against LLVM N, but LLVM N±1 are supported. I don't think that's documented in the README anywhere.

**Comment by derek-gerstmann** [comment]
Ahhh ... so the officially supported toolchains are the lowest common stable version, but we build N+1 for releases too. Makes sense.

**Comment by derek-gerstmann** [comment]
Also, I just noticed that the drop of LLVM v11 support (and associated updates to docs) occurred after the v13 release which is what I was looking at, so the doc changes I was originally suggesting are already done.  Sorry for the noise.

**Comment by alexreinking** [comment]
> Also, I just noticed that the drop of LLVM v11 support (and associated updates to docs) occurred after the v13 release which is what I was looking at, so the doc changes I was originally suggesting are already done. Sorry for the noise.

Not noise! Those should be included in the 13.0.1 backport if they're not already.

**Comment by derek-gerstmann** [comment]
Oooh ... okay!  Should I backport #6396 too?

https://github.com/halide/Halide/pull/6396

**Comment by alexreinking** [comment]
> 
> 
> Oooh ... okay! Should I backport #6396 too?

Couldn't hurt!

**Comment by steven-johnson** [comment]
> > Oooh ... okay! Should I backport #6396 too?
> 
> Couldn't hurt!

A dissenting opinion: don't bother. There were followup changes that were ticklish to get right. We don't want to backport things that aren't bug fixes, and this isn't that.

**Comment by derek-gerstmann** [comment]
Good point.  I was hesitant to make any significant changes, and if this goes beyond docs, then I'd suggest we hold off for a minor release.

**Comment by alexreinking** [comment]
> A dissenting opinion: don't bother. There were followup changes that were ticklish to get right. We don't want to backport things that aren't bug fixes, and this isn't that.

A very reasonable dissent 🙂
