### ISSUE TITLE
Unknown CMake command "add_halide_library".

### ISSUE THREAD

**Issue by xuelimin** [halide/Halide#6427]
when I use the command：`cmake`，the error occur
`-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using /home/sunyanbing/xuelimin/Halide_old_history-release_2017_10_30/cmake_build/lib/bin/libHalide.so
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.0.6")
-- Found tiffxx: /usr/lib/x86_64-linux-gnu/libtiffxx.so
-- Found ZLIB: /usr/local/lib/libz.so (found version "1.2.8")
-- Found PNG: /usr/local/lib/libpng.so (found version "1.6.21")
-- Found JPEG: /usr/local/lib/libjpeg.so (found version "90")
CMake Error at CMakeLists.txt:47 (add_halide_library):
  Unknown CMake command "add_halide_library".

-- Configuring incomplete, errors occurred!
`
my halide is complete and no make error， cmake version is  3.20.6, I dont't konw the reason。

**Comment by alexreinking** [comment]
It looks like you're using a very old version of Halide:

> ```
> home/sunyanbing/xuelimin/Halide_old_history-release_2017_10_30/cmake_build/lib/bin/libHalide.so
> ```

Releases prior to 10.0.0 did not include this helper.
