### ISSUE TITLE
Func::compute_at(Var)

### ISSUE THREAD

**Issue by abadams** [halide/Halide#6466]
It would simplify some code I have if you could compute a Func at a Var without specifying the consumer Func. It would place a realization of that Func inside the outermost instance of that Var it finds enclosing each use of the Func. 

If you use a single consistent set of Vars, you could for example say `my_func.compute_at(y)` and have your func computed per scanline of output without knowing anything about the output Func.

The goal is to make reusable bits of code that are used in multiple generators a little easier to write. The alternative is plumbing a 'y' loop level all the way down from the ultimate Generator to the reusable piece of code, which is awkward in the code I'm dealing with.

**Comment by steven-johnson** [comment]
Interesting, can you throw in an example or two?

**Comment by abadams** [comment]
Sure. I'll make up a nastily-structured pipeline that wants to subtract some computed value from each scanline:

```
Var x, y;
class SomeClass : public SomeBaseClass {
  virtual Func do_the_thing(Func square_bias, Func input) override {
    Func to_subtract;
    to_subtract(y) = sqrt(square_bias(y));
    Func out; 
    out(x, y) = input(x, y) - to_subtract(y);
  
    to_subtract.compute_at(y);
    return out; 
  }
}
... lots of intervening layers of abstraction later ...

class MyGenerator : public Halide::Generator<MyGenerator> {
  Input<Buffer<float>> input; 
  Output<Buffer<float>> output;
  
  void generate() {
    output(x, y) = make_pipeline(input)(x, y);
  }
};
```
Imagine make_pipeline calls something which calls something which calls something which calls SomeBaseClass:do_the_thing on an instance of that base class. It goes through a vtable and might reach SomeClass, or it might reach some other child of SomeBaseClass. Currently I'd have to plumb a LoopLevel representing output scanlines all the way down to the Func, and pass it to all those other do_the_thing implementations even though they all ignore it except for this one.

**Comment by steven-johnson** [comment]
Hmm, yeah, sure sounds like it would make life easier; I'm just trying to figure out what the possible unexpected misbehaviors of this could be -- presumably cases where there are multiple valid possibilities for an outer `y` to be valid, but one to be dramatically worse performance-wise. 

I guess the answer is probably "If it could misbehave then don't use this form of compute_at()" but if it's easy to make this sort of mistake and hard to debug the reason, we could be gnashing our teeth in the future. 

Or am I just confused at your proposal and there isn't any actual ambiguity?

**Comment by abadams** [comment]
I think there's only one outermost 'y' surrounding any given use of the func, but someone could indeed accidentally use this to select that y when they wanted an inner y loop. I'm having a hard time coming up with an example though. I almost called in compute_at_outermost(y) instead of compute_at(y).

**Comment by zvookin** [comment]
IVars... You want IVars.

Adding the concept of "a single consistent set of Vars" without some formalism seems like asking for trouble. Particularly when Vars are matched by name. E.g. in any sort of library/component reuse situation this is unintentional variable capture waiting to happen.

Note this can be prototpyed as a scheduling helper function that works on the IR tree as well.

**Comment by abadams** [comment]
The whole point of IVars is that they were implicit, which these are not. But I'm not proposing adding a single consistent set of Vars here. I'm proposing a new form of compute_at which removes the Func parameter to decouple some things to add flexibility. It happens to work well if people are already using a single global set of Vars, but that's not a practice I'm endorsing.

**Comment by zvookin** [comment]
IVars also did not match by name. One had to have the same IVar object. The implicit nature guarantees that the use is coordinate wise consistent as well, but at the very least having the variable be "branded" reduces the chances of unintentional aliasing between two different uses.

There is another interesting property is there are boundaries from explicit Var to implicit IVar and from implicit IVar to explicit Var in the call graph and this might be interesting scheduling levels to be able to name. But that is much more speculative.

**Comment by alexreinking** [comment]
From a semantics perspective, dimension names (i.e. Vars) are meaningless without an associated Func, so there is an inherent risk of ambiguity. One resolution might be to reject any directives that result in an ambiguous compute location, but I imagine these will be fairly common. Another is your suggestion to name it `compute_at_outermost`, which at least gives a way to break ties, but I'm worried the behavior will make schedules harder to debug and read.

I think the "IVar" stuff predates me.

Finally, the code you posted appears to rely on introspection to give the Vars named `y` a consistent name. Is that right?

**Comment by abadams** [comment]
No, it looks for the outermost Var with the same .name() as the given Var. Introspection is not involved. If you use the same Var object for the caller and the callee, then it'll work.

It's much easier to make Var objects global and shared across a bunch of helper functions than it is to make output Funcs global and shared.

**Comment by abadams** [comment]
There's enough concern about ambiguity and readability that I'm not going to pursue this.

**Comment by alexreinking** [comment]
> If you use the same Var object for the caller and the callee, then it'll work.

Ah, I didn't notice that the vars were global in your example.
