### ISSUE TITLE
CUDA Target: segmentation fault for buffer with dimensionality exceeding the maximal expected dimension

### ISSUE THREAD

**Issue by graefm** [halide/Halide#6509]
If I understand the comment above the definition of `Buffer<T, D=4>` correctly, the number of dimensions of a buffer is allowed to exceed the template parameter D. However when using the default parameter for the CUDA target I observe segmentation faults for buffers with more than 4 dimensions. Below you can find a minimal reproducing example

```Cpp
#include "Halide.h"

int main() {
    using namespace Halide;

    Var i, j, k, l, m;
    Func f;

    f(m, l, k, j, i) = 0;
    f.gpu_blocks(i);
    f.gpu_threads(j);

    Target target = get_target_from_environment();
    Target target_cuda = target.with_feature(Target::CUDA);

    Buffer<int32_t> output{{1,1,1,1,1}};
    //Runtime::Buffer<int32_t, 5> output{{1,1,1,1,1}};
    f.realize(output, target_cuda);

    return 0;
}
```
If the template parameter is increased to D=5 the program works as expected. For the OpenCL target this is not an issue.

As a consequence I think the Python bindings may not be used together with CUDA for buffers with more than 4 dimensions.

**Comment by abadams** [comment]
Thanks for the bug report. I can repro and think I see what the problem is. Will open a PR to fix it shortly.
