### ISSUE TITLE
Target "host" does not imply native cpu

### ISSUE THREAD

**Issue by LebedevRI** [halide/Halide#6514]
While perhaps it does lead to the correct ISA set detection,
it seems e.g. for all X86 AVX2 CPU's, the haswell schedule model is used,
even if LLVM perhaps has one for this CPU. This is a bug

**Comment by abadams** [comment]
I think it's more of a missing feature than a bug. The Halide Target *only* lets you specify the ISA. It doesn't let you communicate to LLVM which processor generation to tune for and there's no way to do that right now. More target flags might be the simplest, though we'd have to add a lot of them.
