### ISSUE TITLE
performance_boundary_conditions is really flaky

### ISSUE THREAD

**Issue by LebedevRI** [halide/Halide#6593]
Out of all the performance tests, `performance_boundary_conditions` alone appears to be the most flakies of them all.
Has there been any thought on increasing the image size and/or running the test a number of times
to increase the length of the benchmark?

**Comment by steven-johnson** [comment]
`performance_async_gpu` is also a fairly frequent flake on Windows systems.

**Comment by steven-johnson** [comment]
performance_async_gpu fails a huge amount of the time on WinBot2 and WinBot1. We should either fix it, disable it, or replace those bots.
