### ISSUE TITLE
How to create a halide_buffer_t pointing to existing GPU memory?

### ISSUE THREAD

**Issue by ashishUthama** [halide/Halide#6600]
AOT scenario.
Parent process handles device allocations _and_ host<->device copies. 

Q1. How do I wrap allocated GPU memory in a halide_buffer_t?
Should this do it? (I dont get errors, and I dont see output GPU memory updated)
```
        hbuffer.host = NULL;
        hbuffer.device = reinterpret_cast<uint64_t>(devicePtr); // Allocated with cudaMalloc
        hbuffer.device_interface = halide_cuda_device_interface();
        // Indicate that the data is ALREADY on the device
        hbuffer.set_device_dirty(true);  
        // Set type, dimensions and dim fields
```

Q2. I am also unsure how to make halide use the parent process's  cuda context and stream. I assume I have to override some methods in the runtime? halide_cuda_acquire_context and halide_cuda_get_stream? I am still studying the code - the word 'context' appears overloaded so having a hard time understanding it. 

Any pointers for me to try?

**Comment by shoaibkamil** [comment]
For Q1, that does indeed look correct to me.  How are you checking the output GPU memory?  Did you call `cuCtxSynchronize()` or `halide_device_release()`?  IIRC, the Cuda backend will not issue a sync unless it is copying data back to host memory.

**Comment by ashishUthama** [comment]
@shoaibkamil - thanks! Yes, the parent process ensure synchronization (I assume with cuCtxSynchronize(), will double check) before copy back to CPU - which I then inspect.

If that looks good, my current suspicion is that my use of the default Halide cuda runtime likely means that Halide is using a different context than what the parent is on, so it essentially cannot see the original memory - and I am being lucky with a 'no crash' execution.

**Comment by ashishUthama** [comment]
Adding this (on Linux) did the trick:

```
#include <cuda.h>
extern "C" {
int halide_cuda_acquire_context(void *user_context, CUcontext *ctx, bool create = true) {    
    cuCtxGetCurrent(ctx);
    return 0;
}
}
```

I am not yet sure how to handle this on win64. 
And if the above is really enough, or if I am doing something that just happens to work, but is a foot gun in the long run.
