### ISSUE TITLE
The ${FILTER}_jit_wrapper() entry point needs documentation and tests

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#667]
We provide a wrapper function for calls with the suffix "_jit_wrapper", which lets us call by an array of void*... but I don't see any tests or explicit documentation for it. If we're going to officially support it (which would be nice), we should probably have both.

**Comment by steven-johnson** [comment]
Expanding a bit on this... the reason for bringing this up is that it would be handy when used in conjunction with metadata (issue 664) as a way to do automated testing, interpreter glue, etc., but I don't want to write code on top of it if this is something we don't want to fully support (ie, it's just an artifact of current JIT implementation).

If it *is* something we want to embrace and use for that purpose, we may want to consider renaming it to something less jit-specific (e.g. _jit_wrapper -> _arg_array or some such).

**Comment by dsharletg** [comment]
I believe I already renamed this from _jit_array to _argv in the modules
branch (not yet submitted). I'm not wedded to the name, just a suggestion.

**Comment by steven-johnson** [comment]
_argv is LGTM

**Comment by abadams** [comment]
Also fine by me.
