### ISSUE TITLE
How to modify Halide generator to emit new output format?

### ISSUE THREAD

**Issue by antonysigma** [halide/Halide#6690]
*(Forwarded from https://github.com/halide/Halide/pull/6637#discussion_r843007246:)*

Hi I am a fan of Halide toolchain, recently transitioning from GPU hardware to FPGA hardware. I wonder how I can modify Halide source code to output a custom language? In other words, how to I generate a `foobar` file using the generator `-e` option?

```Makefile
pipeline_name.foobar: %.foobar : %.generator.exe
    ./$< target=arm-64-linux-... -g pipeline_name -e 'cpp,h,html,foobar'
```

To be specific, I encountered a few forked projects aiming at exporting the Halide-defined pipeline to the vendor specific FPGA language. While they successfully implemented a new output format within Halide, they so far failed to integrate it to `Halide::Generator<>`. I know how to encapsulate their code into `Halide::Generator<>`, but I am not sure how I can modify Halide core code to add a new `-e=foobar` option.

Here's one example from [Halide-HLS](https://github.com/jingpu/Halide-HLS/blob/HLS/apps/hls_examples/camera_unsharp_hls/pipeline.cpp#L654-L663) :

```Makefile
# This generates two files: test-bench code, and the FPGA code for hardware synthesis.
# However, this returns error, because the "-e=hls" option is not yet implemented.
pipeline_name.hls.cpp: %.hls.cpp : %.generator.exe
    ./$< target=x86-64-linux-VivadoHLS -g pipeline_name -e 'cpp,h,html,hls'

pipeline_name.cpp pipeline_name.h: pipeline_name.hls.cpp
    # Do nothing. These are supposed to be generated alongside *.hls.cpp .
```

And the other example from [HeteroHalide](https://github.com/UCLA-VAST/heterohalide/blob/master/new/blur/blur.cpp#L88):
```Makefile
# This generates one file: python code for FPGA hardware synthesis
# However, this fails for two reasons:
# 1. "-e=hetero_cl_py" option is not yet implemented; and
# 2. Target feature "HeteroCL" is not yet defined.
pipeline_name.heterocl.py: %.hls.cpp : %.generator.exe
    ./$< target=x86-64-linux-HeteroCL -g pipeline_name -e 'html,hetero_cl_py'
```

**Comment by antonysigma** [comment]
Closing my own ticket because I realized both Halide-HLS and HeteroHalide are not merged upstream.

**Comment by steven-johnson** [comment]
> Closing my own ticket because I realized both Halide-HLS and HeteroHalide are not merged upstream.

AFAIK, Halide has never received a PR from either of these projects.
