### ISSUE TITLE
Errors reported by llvm::verifyModule ignored

### ISSUE THREAD

**Issue by abestephensg** [halide/Halide#673]
Halide calls llvm::verifyModule in CodeGen.cpp but doesn't do anything with the return value and implicitly passes null output stream so error messages are discarded.

```
// Finally, verify the module is ok
334	    verifyModule(*module);
```

Currently, CodeGen_PNaCL produces bad IR which is not caught until a later step in the pnacl tool chain attempts to verify the Halide generated module.

**Comment by abestephensg** [comment]
In this particular case, Verifier::visitModuleIdents in chromium branch LLVM 3.5 (for pepper_41) requires that MDNodes have exactly one operand. The same check appears in LLVM trunk.

The metadata format changed between 3.5 and trunk and it happened that the runtime .ll files used to generate the encoded modules in libHalide.a were not being cleaned by my build.  At runtime, when libHalide.a (built from 3.5 LLVM) used the modules generated by trunk clang, the metadata nodes were incorrect. libHalide caught but ignored the error, and then another 3.5 LLVM tool caught the problem later in the build.

**Comment by abadams** [comment]
Ah, sounds like that was painful to debug. I'll throw some asserts in
there. Not sure why the return value was never checked. I seem to recall
these tests failing at one point, so perhaps the semantics of those calls
changed.

**Comment by dsharletg** [comment]
Yes, I vaguely recall hitting asserts in verifyModule at some point.
Perhaps your LLVM is built without asserts turned on?

Either way, we should check the return value.

**Comment by abestephensg** [comment]
I am using an LLVM assert enabled build, but the Assert1 macro in LLVM's Verifier.cpp does not actually trigger an assert, instead it logs the message and sets the Broken flag in the Verifier.

Thanks for the patch!
