### ISSUE TITLE
62% performance regression introduced by Deprecate disable_llvm_loop_opt (#4113) (#6754)

### ISSUE THREAD

**Issue by froody** [halide/Halide#6784]
b38b6611b Deprecate disable_llvm_loop_opt (#4113) (#6754)

Compounding the effects of #6783 / 460c77e , the above commit causes a 62% regression for my pipeline on x86. My benchmark results:

Baseline(v14.0.0): 0.5851s
After 460c77e: 0.6914s
After b38b6611b: 1.1354s

I'm not sure if I can share the details of my pipeline but if you have trouble reproducing the problem then let me know and I'll see what I can do.

I am able to recover the performance to that of 460c77e by enabling loop opt:
```
t = hl.get_host_target()
t.set_feature(hl.TargetFeature.EnableLLVMLoopOpt)
self.func.compile_jit(t) # x86-64-linux-tune_znver2-avx-avx2-enable_llvm_loop_opt-f16c-fma-sse41
```

llvm-version: llvmorg-13.0.0
cmake invocation: 
```
cmake -G Ninja \
                 -DCMAKE_BUILD_TYPE=Release \
                 -DWITH_PYTHON_BINDINGS=ON \
                 -DPYTHON_EXECUTABLE=$CONDA_ENV/bin/python3.9 \
                 -DPython3_ROOT=$CONDA_ENV \
                 -DLLVM_TARGETS_TO_BUILD="host;JSBackend;WebAssembly" \
                 -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DCLANG_INCLUDE_TESTS=OFF \
                 ..
```
CPU: AMD EPYC 7742

**Comment by froody** [comment]
uh wrong bisect hash, checking...

**Comment by steven-johnson** [comment]
I'm going to close this as @abadams likely diagnosed the issue. Please re-open if not.
