### ISSUE TITLE
buffer_t dev field's type has recently changed but only implicitly

### ISSUE THREAD

**Issue by fkaleo** [halide/Halide#680]
Since the introduction of device_handle_wrapper by PR https://github.com/halide/Halide/pull/569 buffer_t.dev is not really an int anymore as it is now often casted into a pointer to a device_handle_wrapper. But it is still defined as an int in the buffer_t struct which leads to very unpredictable errors and crashes.
My programs were passing texture ids to the glsl backend until now via the dev field and the same programs are still compiling but of course are now crashing when the texure ids are casted and dereferenced.

Moreover, and that might be just me doing it wrong, when trying to use the new helper functions introduced to properly set the dev fields such as halide_opengl_wrap_texture, I am unable to find the proper way to link so that the function is found by the linker and I get errors such as:

```
phablet@ubuntu-phablet:~/filters-benchmarks/halide-brightness-opengl$ g++ -Wl,-O1 -o halide-brightness-opengl halide-brightness-opengl.o   -L/home/phablet/Halide-master/lib -lHalide -lQt5Gui -lQt5Core -lGLESv2 -lpthread 
halide-brightness-opengl.o: In function `profile(int, char**, Halide::Func (*)(Halide::ImageParam, QSize), QSize (*)(QSize), QPoint (*)(), Halide::Func (*)(Halide::ImageParam, Halide::ImageParam, QSize))':
halide-brightness-opengl.cpp:(.text+0x2d8c): undefined reference to `halide_opengl_wrap_texture'
collect2: error: ld returned 1 exit status
```

**Comment by abadams** [comment]
It was always intended to be an opaque 64-bit handle. Next time we change
buffer_t we'll probably change this to an id and a device interface
pointer, or officially make it a pointer to a struct containing the same,
as it is implicitly now. The change we made was the minimal change that
didn't break existing users of buffer_t, except for those manually setting
the device id field.

**Comment by fkaleo** [comment]
Thanks for the reply Andrew.
Opaque/implicit means that the compiler won't even emit a warning if the developer does something wrong. More generally, if we start saying variables are of type A when really they are of type B it is going to become a jolly mess.

Any idea what the proper way to link in halide_opengl_wrap_texture is?

**Comment by fkaleo** [comment]
Don't get me wrong, I'm all for API stability and you made the wise choice to minimize the breakage. I guess being part of the unlucky few was frustrating :)

**Comment by abadams** [comment]
Ah, I see your point. It wasn't intended to be type-safe before, but in the case of OpenGL texture ids it happened to be, so now your code is dereferencing small integers. Sorry for the breakage.

Perhaps @abestephensg knows the right way to wrap an OpenGL texture now.

**Comment by zvookin** [comment]
We debated about changing the name of the field and decided not to as it
would have required changing a lot of code that did not need to be changed
for correctness. (E.g. Code that initialized the field to zero.)
unfortunately we did not adequately publicize the breaking change when the
merge to master occurred.

The good news is there is now an API to convert between the underlying GPU
API data types and Halides dev field. These are exported from the GPU
specific header (e.g. HalideRuntimeOpenGL.h) and should be exported from
any Halide generated .o that is compiled with a Target specifying the GPU
in question.

-Z-


On Feb 22, 2015, at 4:17 PM, fkaleo <notifications@github.com> wrote:

Don't get me wrong, I'm all for API stability and you made the wise choice
to minimize the breakage. I guess being part of the unlucky few was
frustrating :)

—
Reply to this email directly or view it on GitHub
<https://github.com/halide/Halide/issues/680#issuecomment-75474604>.

**Comment by fkaleo** [comment]
Thanks @zvookin, so I guess it works with AOT but I am actually JITting here.

**Comment by zvookin** [comment]
I recently added some of the device API calls to libHalide.a so they can be
used in JIT scenarios. The GPU specific ones are a bit trickier to do, but
we should be able to come up with a solution. Feel free to file an issue on
this.

-Z-


On Feb 23, 2015, at 3:34 AM, fkaleo <notifications@github.com> wrote:

Thanks @zvookin <https://github.com/zvookin>, so I guess it works with AOT
but I am actually JITting here.

—
Reply to this email directly or view it on GitHub
<https://github.com/halide/Halide/issues/680#issuecomment-75526904>.

**Comment by abestephensg** [comment]
We should add some tests to test/opengl/ that exercise the JIT + app GL context & textures path.

**Comment by zvookin** [comment]
Closing this as it is largely moot since halide_buffer_t went back to dev just being the device API handle in most cases.
