### ISSUE TITLE
Build target with RISC-V

### ISSUE THREAD

**Issue by WCTchentao** [halide/Halide#6811]
when i want to build risc-v arch in linux，i get error as Unhandled exception: Error: RISCV not enabled for this build of Halide. 
my target configuration is "riscv-64-linux-no_runtime",  what ever how i changed the os and features i always get that error.

**Comment by LebedevRI** [comment]
Presumably that means the halide you are using was compiled without RISCV support.

**Comment by WCTchentao** [comment]
> Presumably that means the halide you are using was compiled without RISCV support.
thanks for your reply, but i can't find complie options for building halide with RISCV ，how to set configs?

**Comment by WCTchentao** [comment]
> ...or the LLVM version, if building Halide from scratch

thansk , i check my LLVM version, it's 12.0, i will use 13.0 or higher version, and try again

**Comment by WCTchentao** [comment]
thanks steven, i has solved this problem successfully according to your advice
