### ISSUE TITLE
Simplify lets before allocation bounds inference

### ISSUE THREAD

**Issue by abadams** [halide/Halide#686]
Allocation bounds inference relies on being able to do good interval arithmetic analysis, but takes place before any simplification of lets, which is when a lot of potentially helpful cancellations take place.

I just encountered a case where this caused a 2x overhead in memory footprint. Was not able to produce a smaller test case, so that's still todo.

**Comment by dsharletg** [comment]
This has probably improved a lot since filing, should it be closed?

**Comment by abadams** [comment]
While we have a simplify_correlated_differences pass now that should cover the specific case, allocation bounds inference still runs before the first simplification pass.

**Comment by dsharletg** [comment]
I think this is fixed now? It looks like allocation bounds inference is running after the first simplification.

**Comment by abadams** [comment]
Yes, we now do substitute in let values in the first simplification pass. We don't remove dead lets. We used to not do any substitutions in the first simplification pass.
