### ISSUE TITLE
runtime_internal_string_storage fails under ASAN

### ISSUE THREAD

**Issue by LebedevRI** [halide/Halide#6863]
@derek-gerstmann

There is a number of issues:
*
```
        StringStorage ss;
        halide_abort_if_false(user_context, ss.length() == 0);
```
is UB because `ss` is garbage and not zero-initialized
* `memcpy` in `StringStorage::prepend()` over overlapping memory ranges
* ???

**Comment by derek-gerstmann** [comment]
@LebedevRI Ooh, thanks for the report! Yes, I just built these against address sanitizer, and there's some obvious defects.  Very much in favor of adding an ASAN pass to the build to catch these types of issues. I'll clean things up and add a pull request.
