### ISSUE TITLE
Insufficient buildbot test coverage - no ASAN/UBSan?

### ISSUE THREAD

**Issue by LebedevRI** [halide/Halide#6864]
I'm not sure why bots aren't red - https://github.com/halide/Halide/issues/6863.

**Comment by steven-johnson** [comment]
ASAN we really should add. 

UBSan might be harder to do -- it turns out that a *lot* of C++ code relies on UB (cough) -- and even inside Google (where we loooove Sanitizers), that one is in the category of "don't expect it to work on a lot of code".

**Comment by steven-johnson** [comment]
Oh, I'm not *opposed* to trying UBSan -- but we may run into issues with dependent libraries we use being unable to pass with it enabled. Happy to try and see.
