### ISSUE TITLE
Bundling LLVM libs includes `__.SYMDEF` members

### ISSUE THREAD

**Issue by shoaibkamil** [halide/Halide#6876]
Observed on macOS with Xcode 13.4 (and Xcode 14 beta), CMake build.

If using `-DBUILD_SHARED_LIBS=OFF` and `-DHalide_BUNDLE_LLVM=ON`, the static library generated via CMake includes at least one extra `__.SYMDEF` member.  Newer toolchains (e.g. Apple clang 14) error out during link if multiple of these are in the generated library.

**Comment by shoaibkamil** [comment]
Additional information:

- The `__.SYMDEF` member is coming from `libLLVMSupport.a`.
- The reason this happens is down to `CMAKE_ASM_OUTPUT_EXTENSION` is unset, so the loop [here](https://github.com/halide/Halide/blob/967c3bf53d2e4143930dbda5ab581ebe334e845f/cmake/BundleStatic.cmake#L186) globs '\*' instead of (as in C/C++) '*.o'

It's unclear to me how we should be setting CMAKE_ASM_OUTPUT_EXTENSION.  Interestingly, CMAKE_ASM${ASM_DIALECT}_OUTPUT_EXTENSION _is_ set, so is this just a matter of checking if the former is unset and setting it to the latter, within our `BundleStatic.cmake` file?

**Comment by steven-johnson** [comment]
adding @alexreinking

**Comment by alexreinking** [comment]
> adding @alexreinking

If you _assign_ (on the right) an issue to me, it'll appear in my issues dashboard, which makes it a bit harder for me to lose track of.

**Comment by steven-johnson** [comment]
...didn't want to take the liberty of *assigning* it to you, just wanted you to see it, but, your wish is my command :-)

**Comment by shoaibkamil** [comment]
Any advice on how to fix would be much appreciated-- I could implement the simple check in my comment above, but if there's a canonical/more CMake-y way to do this, let me know.

For now, I worked around it by adding `-DCMAKE_ASM_OUTPUT_EXTENSION=".o"` to our command line when building Halide.

**Comment by alexreinking** [comment]
> For now, I worked around it by adding `-DCMAKE_ASM_OUTPUT_EXTENSION=".o"` to our command line when building Halide.

That's definitely wrong, as `CMAKE_<LANG>_OUTPUT_EXTENSION` is meant to be detected by CMake as a toolchain-derived value. It's "read only" or purely informational in some sense.

Can you tell me more about this `CMAKE_ASM${ASM_DIALECT}_OUTPUT_EXTENSION` that's set? Maybe the correct thing to do is to filter out `ASM` _without_ a dialect as a language.

**Comment by shoaibkamil** [comment]
I basically looked at CMake's source repo to find out what variables it sets up initially, by looking at the modules here: https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/

I noticed in https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/CMakeASMInformation.cmake, the variables for dialects are set, but I couldn't find anywhere (outside of specific toolchain files) where the non-dialect version of the variable is set.

**Comment by alexreinking** [comment]
Can you check whether `CMAKE_ASM_OUTPUT_EXTENSION` is _defined_ at all? As in, with `if (DEFINED ...)`? If not, that's the appropriate filter.

**Comment by shoaibkamil** [comment]
Yeah, it's not defined.  So I was proposing something like:

```
if (NOT DEFINED(CMAKE_ASM_OUTPUT_EXTENSION))
    message(VERBOSE "CMAKE_ASM_OUTPUT_EXTENSION is unset.  Setting it to ${CMAKE_ASM${ASM_DIALECT}_OUTPUT_EXTENSION}")
    set(CMAKE_ASM_OUTPUT_EXTENSION ${CMAKE_ASM${ASM_DIALECT}_OUTPUT_EXTENSION}})
endif ()
```

**Comment by alexreinking** [comment]
No, I don't think that `ASM_DIALECT` is guaranteed to be defined or set by CMake as it doesn't appear anywhere in the documentation. Actually, I see a bunch of places in the detection modules where it is explicitly _unset_ (try `git grep 'set(ASM_DIALECT)'` in the CMake repo). I would just update that loop to read:

```
            foreach (lang IN LISTS languages)
                if (DEFINED "CMAKE_${lang}_OUTPUT_EXTENSION")
                    list(APPEND globs "${stage}/*${CMAKE_${lang}_OUTPUT_EXTENSION}")
                endif ()
            endforeach ()
```

**Comment by shoaibkamil** [comment]
No worries :) SGTM, will create a PR shortly.  Thanks for the advice!

**Comment by alexreinking** [comment]
No problem. I'm going to open an issue (if one doesn't exist already) with upstream about this.
