### ISSUE TITLE
define_extern causes LLVM error

### ISSUE THREAD

**Issue by gchauras** [halide/Halide#689]
I am using extern definition for a Func and have the extern definition function declared as under:
```
extern "C" int copyFloat32(int bufferType, int p, buffer_t* copyTo, buffer_t* in, buffer_t* out);

Func f;
f.define_extern("copyFloat32", { bufferType, pParam, buffer, input }, Float(32), 2);
```
The cpp file that contains the definition of copyFloat32 is compiled and linked as all other cpp files in the implementation. This is giving me the following LLVM error:
```
LLVM ERROR: Program used external function 'copyFloat32' which could not be resolved
```
I am using JIT target is x86-64-linux-sse41-avx-f16c on Ubuntu with g++. This works fine on Macbook which uses clang++ to compile the Halide program. Do you think this is a LLVM issue or g++ issue.

**Comment by zvookin** [comment]
Try adding -rdynamic to the link line. The symbol has to be preserved and
have appropriate visibility to be found.

We'll be adding an API to pass a list of name to function map pings to be
used for resolving extend during JIT.

-Z-


On Feb 25, 2015, at 9:13 AM, Gaurav Chaurasia <notifications@github.com>
wrote:

I am using extern definition for a Func and have the extern definition
function declared as under:

extern "C" int copyFloat32(int bufferType, int p, buffer_t* copyTo,
buffer_t* in, buffer_t* out);

Func f;
f.define_extern("copyFloat32", { bufferType, pParam, buffer, input },
Float(32), 2);

The cpp file that contains the definition of copyFloat32 is compiled and
linked as all other cpp files in the implementation. This is giving me the
following LLVM error:

LLVM ERROR: Program used external function 'copyFloat32' which could
not be resolved

I am using JIT target is x86-64-linux-sse41-avx-f16c on Ubuntu with g++.
This works fine on Macbook which uses clang++ to compile the Halide
program. Do you think this is a LLVM issue or g++ issue.

—
Reply to this email directly or view it on GitHub
<https://github.com/halide/Halide/issues/689>.

**Comment by abadams** [comment]
Make sure you're including the flag -rdynamic on your gcc compilation.

LLVM is calling dlsym, which is not finding the symbol because on linux
symbols aren't findable in executables by default.

- Andrew

**Comment by gchauras** [comment]
I did not know that symbols are not findable. Works now. Thanks a lot.
