### ISSUE TITLE
Taskflow par_for support

### ISSUE THREAD

**Issue by antonysigma** [halide/Halide#6890]
I have a similar request to https://github.com/halide/Halide/issues/129#issuecomment-270738216 . Instead of using `tbb::parallel_for` to implement Halide parallel tasks, Taskflow has this async API:

```c++
#include <taskflow/taskflow.hpp>

extern "C" int taskflow_do_par_for(void *user_context,
                                 int (*f)(void *, int, uint8_t *),
                                 int min, int extent, uint8_t *state) {
    std::atomic<int> exit_status = 0;
    const auto step = 1;
    my_subflow::for_each_index(int (min), int(min+extent), step, [&](int idx) {
        const int job_status = halide_do_task(user_context, f, idx, state);
        if (job_status) exit_status = job_status;
    });
    return exit_status;
}
// ...
__attribute__((constructor))
void overrideWithTaskflow(){
  halide_set_custom_do_par_for(&taskflow_do_par_for);
}
```

The only catch is that Taskflow wants to provide a handle `tf::Subflow my_subflow` so it can schedule the parallel tasks dynamically in the global scope. For example, taskflow will load balance two or more competing par-for jobs. 

```c++
tf::Taskflow taskflow;
auto job1 = taskflow.emplace([&] (tf::Subflow& my_subflow) {
    aot_halide_pipeline1(input1, output1, /* my_subflow ?? */);
    // block here until Halide finished computing.
    subflow.join();
    // Do something with output1.
});
auto job2 = taskflow.emplace([&] (tf::Subflow& my_subflow) {
    aot_halide_pipeline2(input2, output2, /* my_subflow ?? */);
    // block here until Halide finished computing.
    subflow.join();
    // Do something with output2.
});

// Job 1 and job 2 will run simultaneously.
tf::Executor executor(n_workers);
executor.run(taskflow).wait();
```

How can I pass the instance `my_subflow` into `taskflow_do_par_for` ? Is it through the `aot_halide_pipeline_argv` API in the AOT generated function?

**Comment by abadams** [comment]
Add the user_context target flag, which will add an extra first arg to your Halide pipeline. You can pass in a void pointer, and it will be forwarded to the user_context to your do_par_for implementation.

**Comment by antonysigma** [comment]
Thank you @abadams for suggesting the flag `user_context`. While I am experimenting with the feature, I realized the statement `return exit_status` has undefined behavior. I suppose the custom function `taskflow_do_par_for` must not return till `halide_do_task` is completed?

Here's the most up-to-date code:
```c++
extern "C" int
taskflow_do_par_for(void *user_context, int (*f)(void *, int, uint8_t *), int min, int extent,
                    uint8_t *state) {
    std::atomic<int> exit_status{0};
    constexpr auto step = 1;

    tf::Subflow& my_subflow = *static_cast<tf::Subflow*>(user_context);

    my_subflow.for_each_index(int(min), int(min + extent), step, [&](int idx) {
        const int job_status = halide_do_task(user_context, f, idx, state);
        if (job_status) exit_status = job_status;
    });

    // Compile error: Unable to join the worker thread here.
   // subflow.join();

    // Segmentation fault: halide_do_task has not yet executed at this stage.
    // This always returns zero value.
    return exit_status;
}
```

**Comment by abadams** [comment]
That's right, do_par_for isn't supposed to return until the job is done.

**Comment by antonysigma** [comment]
Thank you. I stopped trying to integrate `halide_do_par_for` to Taskflow. It appears taskflow's async task scheduling API is incompatible with Halide. Perhaps in the future, I can still make the jobs to complete first before returning, e.g. via the c++20 `std::barrier` struct. For now, I will mark this ticket as unsolvable.

Thanks again for the input.
