### ISSUE TITLE
Compiler version requirements are too lax

### ISSUE THREAD

**Issue by LebedevRI** [halide/Halide#6892]
As per IRC disscussion, since LLVM<n> is required, that is the oldest clang version supported to build halide.
More importantly, the current supported GCC version is 7, which appears unreasonably old.

Given that LLVM13 is required, released aug '21, it does not seem prudent to require GCC9, released may '19.

**Comment by steven-johnson** [comment]
I don't think we've revisited the GCC version requirements in a while. The goal is really to have a baseline that is widely preinstalled on mainstream Linux versions, but what 'widespread' and 'mainstream' means is handwavy.  GCC9 sounds fine to me on the surface, but we should probably try to figure out what systems (if any) would be inconvenienced.
