### ISSUE TITLE
Nightly package builds

### ISSUE THREAD

**Issue by LebedevRI** [halide/Halide#6895]
While there's a CI, and it even builds some packages, this isn't quite it.
We //could// have proper nightly builds, similar to https://apt.llvm.org/.
In fact, i have already mostly have it working for main/amd64.

Questions:
* Is this something that we want?
* (required) Storage/distribution of the built packages needs solving. While we could put them up as a static github pages site, it will quickly break because of the resource usage restrictions.
* Where (on which hardware) do we perform the builds? I think, github actions may kinda mostly work, not sure.

Refs. https://blog.llvm.org/posts/2021-11-02-apt.llvm.org-moving-from-physical-server-to-the-cloud/

**Comment by alexreinking** [comment]
>Is this something that we want?

Yes. Preferably through GitHub Actions rather than our official buildbots. In fact, I would like all of our packaging workflows to happen there.

**Comment by LebedevRI** [comment]
> Yes.

Okay, that matches my expectations :)

> Preferably through GitHub Actions rather than our official buildbots.

Do you mean the control-wise, or hardware-wise?

I think, it could work, but i feel like the storage problem will need to be resolved first.

> In fact, I would like all of our packaging workflows to happen there.

**Comment by sylvestre** [comment]
Lazy copy and paste from IRC about apt.llvm.org:

on gcp, i have a shared drive which amd64 nodes are automatically mounting as nfs. They directly updated the repos on the nfs. For s390x and arm64 (hosted elsewhere), I have some ugly rsync from these nodes to the master
then, they are pushed to our (llvm) server with an rsync which is used by the cdn

**Comment by alexreinking** [comment]
@LebedevRI - why did you close this?
