### ISSUE TITLE
AutoSchedule - NewAPI with Adams2019 - Condition failed: pipeline_feat_queue.data()

### ISSUE THREAD

**Issue by soufianekhiat** [halide/Halide#6899]
Commit:
11a049c3967a277173e288ffd802f08ce1a1b78e
#6863 [- Fixes to make address sanitizer happy for internal runtime cl…

Calling:
```cpp
Target oTargetCPU = ...
Func oFunc = ...
AutoSchedulerResults oResult =
	oFunc.apply_autoscheduler( oTargetCPU,
	{ "Adams2019",
	//{ "Mullapudi2016",
		{ { "parallelism", "16" } }
	} );
```
Work fine with "Mullapudi2016" and assert with "Adams2019".
Assert:
Internal Error at F:\git\Halide\src\autoschedulers\adams2019\DefaultCostModel.cpp:139 triggered by user code at : Condition failed: pipeline_feat_queue.data() && "Call set_schedule_features before calling enqueue\n":

Did I miss something on the code convention of the new API?

**Comment by steven-johnson** [comment]
I've never seen that assert fire before, locally or elsewhere, so offhand I don't know what could be causing it. If you can post a more-complete piece of code that demonstrates the problem, I'd be happy to take a look.

**Comment by soufianekhiat** [comment]
Sure,
Here the full code that trigger this assert:
```cpp
#include <Halide.h>
#include <vector>

int main()
{
	namespace H = Halide;

	std::vector<float> src;
	src.resize( 256 );
	float xi = 1.0f;
	for ( float& x : src )
	{
		x = xi;
		xi += 1.0f;
	}

	int const iSize = static_cast< int >( src.size() );

	H::Buffer<float, 1> hBuffer( &src[ 0 ], { iSize } );

	H::Func f( "buffer_func" );
	H::Var x( "x ");

	f( x ) = hBuffer( x );

	H::load_plugin( "autoschedule_adams2019.dll" );
	H::load_plugin( "autoschedule_li2018.dll" );
	H::load_plugin( "autoschedule_mullapudi2016.dll" );

	H::Target targetCPU = H::get_jit_target_from_environment();

	f.set_estimates( { { 0, iSize } } );

	H::Pipeline p( f );
	H::AutoSchedulerResults result =
		p.apply_autoscheduler(	targetCPU,
								{ "Adams2019",
								//{ "Mullapudi2016",
								   { { "parallelism", "16" } }
								} );

	return 0;
}
```
Thanks

**Comment by steven-johnson** [comment]
OK, this is an interesting bug, stand by :-)

**Comment by soufianekhiat** [comment]
You mean the command line?
It use sharpmake (https://github.com/ubisoft/Sharpmake) to generate a Visual Studio project:
`/permissive- /MP /ifcOutput "..\..\..\..\tmp\null\win64\examples\release\" /GS- /GL /W4 /Gy /Zc:wchar_t /I"..\..\..\.." /I"..\..\..\..\extern" /I"..\..\..\..\extern\eigen" /I"..\..\..\..\extern\eigen\unsupported" /I"..\..\..\..\extern\fmt\include" /I"..\..\..\..\extern\halide\include" /I"..\..\..\..\extern\imgui" /I"..\..\..\..\extern\rapidjson\include" /I"..\..\..\..\src" /I"..\..\..\..\src\halidetk" /Zi /Gm- /O2 /Ob2 /Zc:inline /fp:fast /Zp8 /D "EIGEN_HAS_STD_RESULT_OF=0" /D "NDEBUG" /D "NOMINMAX" /D "RAPIDJSON_HAS_STDSTRING" /D "WIN32" /D "WIN64" /D "WINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP" /D "_CONSOLE" /D "_ENABLE_EXTENDED_ALIGNED_STORAGE" /D "_ENFORCE_MATCHING_ALLOCATORS=0" /D "_WIN32_WINNT=0x0600" /D "_MBCS" /fp:except- /errorReport:prompt /GF /WX- /Zc:forScope /GR- /arch:AVX /Gd /Oy- /Oi /MD /openmp- /std:c++latest /FC /EHsc /nologo /Ot`
