### ISSUE TITLE
swig 3.0.6 does not understand Halide.h

### ISSUE THREAD

**Issue by rodrigob** [halide/Halide#691]
When building the python bindings over the current master one get
```
Halide/python_bindings$ make
swig -c++ -python -w362,325,314,389,381,382,361,401,503,509 -I../build/include halide/cHalide.i
../build/include/Halide.h:4942: Warning 383: operator++ ignored
../build/include/Halide.h:4980: Warning 383: operator++ ignored
../build/include/Halide.h:5527: Error: Syntax error in input(3).
make: *** [halide/cHalide_wrap.cxx] Error 1
```
and this is using the latest swig version `3.0.5`.

The source of trouble `Halide.h:5527` seems to be 
``` 
EXPORT int (*argv_function() const)(const void **);
```
commenting it out allows to build a functional python module.

I am not a swig expert, not sure what is the good action plan (bug report to swig ? tell swig to ignore that line ?).

**Comment by steven-johnson** [comment]
Sounds like a SWIG bug --  "operator++ ignored" doesn't make sense given
that we don't overload that operator anywhere.

**Comment by abadams** [comment]
Looks like our iterator type for Scope overloads operator++. That's not
important for the python bindings.

The problem appears to be that swig doesn't understand a class method that
returns a function pointer. Maybe there's some trivial change we can make.
I'll try some things.

**Comment by zvookin** [comment]
I think this alternative syntax is equivalent:
  typedef int (*argv_wrapper)(const void **args);

  EXPORT argv_wrapper argv_function() const;

(Aside from introducing the extra type name.)

Can you see if that passes SWIG?

-Z-

**Comment by abadams** [comment]
Yes, that appears to be understood by SWIG. I'll make the change.

**Comment by abadams** [comment]
Pushed, but the swig wrappers are still broken due to the change to the
Argument constructor.

**Comment by rodrigob** [comment]
Should we open a specific issue regarding the Argument constructor ?

**Comment by rodrigob** [comment]
This bug has gotten worse with the current master.

Swig struggles with template parameter packs (`template <typename ...Args>`), does not understand anything about `GeneratorParam`  contructors.

I tried adding a bunch of `#if !defined(SWIG)` to blind SWIG from the problematic pieces of code, but then swig 3.0.6 (latest release) simply segfaults (bug report on this to be created).

I am starting to wonder if swig is the right tool for the job (since, by design, it struggles to follow-up C++ standards).

**Comment by phflot** [comment]
Here is a link to the corresponding swig bug report:
[https://github.com/swig/swig/issues/424]()

**Comment by rodrigob** [comment]
The swig side reports to have [fixed the issue](https://github.com/swig/swig/commit/117f6d0026ae0e52286c1e1a3750c682d081b53c), to be tried.

Even if swig does not crash, issue #814 remains.

I have created #821 as a new (cleaner) approach for the python bindings.

**Comment by rodrigob** [comment]
Now that #821 is merged, this issue is now obsolete.
