### ISSUE TITLE
Undefined symbol "program_invocation_name"

### ISSUE THREAD

**Issue by yurivict** [halide/Halide#6945]
```
===>  Building for halide-14.0.0
[  1% 6/63] cd /disk-samsung/freebsd-ports/lang/halide/work/.build/src/autoschedulers/adams2019 && /disk-samsung/freebsd-ports/lang/halide/work/.build/src/autoschedulers/adams2019/included_schedule_file.generator -r included_schedule_file.runtime -o . -e object target=x86-64-freebsd
FAILED: src/autoschedulers/adams2019/included_schedule_file.runtime.o /disk-samsung/freebsd-ports/lang/halide/work/.build/src/autoschedulers/adams2019/included_schedule_file.runtime.o
cd /disk-samsung/freebsd-ports/lang/halide/work/.build/src/autoschedulers/adams2019 && /disk-samsung/freebsd-ports/lang/halide/work/.build/src/autoschedulers/adams2019/included_schedule_file.generator -r included_schedule_file.runtime -o . -e object target=x86-64-freebsd
ld-elf.so.1: /disk-samsung/freebsd-ports/lang/halide/work/.build/src/libHalide.so.14: Undefined symbol "program_invocation_name"
```

FreeBSD 13.1

**Comment by steven-johnson** [comment]
We don't (officially) support building on any BSD distribution, but this might be fixable with some attention to Introspection.cpp, which assumes that glibc (or similar) defines `program_invocation_name` -- if you can find an equivalent in BSD that should work.

Alternately, just compile with introspection disabled (-DWITH_INTROSPECTION=OFF in Cmake)

**Comment by yurivict** [comment]
The problem still exists with ```-DWITH_INTROSPECTION=OFF```.

**Comment by steven-johnson** [comment]
> The problem still exists with `-DWITH_INTROSPECTION=OFF`.

That seems puzzling, since the only reference to `program_invocation_name` in Halide is inside `#ifdef WITH_INTROSPECTION`

**Comment by steven-johnson** [comment]
Closing this because Halide doesn't have the resources to support or test for BSD at this time. (We'd welcome patches that make BSD support better or more reliable, of course, but can't commit to keeping it working.)
