### ISSUE TITLE
Performance issues on AMD graphics cards

### ISSUE THREAD

**Issue by dvicini** [halide/Halide#696]
Hi,

I am currently working with Halide on two different machines, one with a Nvidia Gtx 580 and one with an AMD HD 7870 (both machines use Windows 7 64bit, tried with both the latest release Halide version and the latest nightly build). I mainly work on the machine with the Nvidia GPU. Today I discovered something odd: I know that code which runs fast on one GPU does not necessarily run fast on another GPU, but the time difference I get on my current code is really too big. Here is the complete code: (clock.h and image_io.h from the tutorials)

    #define _CRT_SECURE_NO_WARNINGS
    #include <Halide.h>
    #include <stdio.h>

    #include "clock.h"
    #include <algorithm>

    using namespace Halide;
    #include "image_io.h"

    Func boxblur(Image<float> input, int f)
    {
        Var x("x"), y("y");
        Func clamped("clamped");
        clamped(x, y) = input(clamp(x, 0, input.width() - 1), clamp(y, 0, input.height() - 1));

        const float normalizationFactor = 1.0f / ((2 * f + 1) * (2 * f + 1));
        RDom convRange(-f, 2 * f + 1, "conv range");
        Func convX("convX");
        convX(x, y) = sum(convRange, clamped(x + convRange, y));
        Func convY("convY");
        convY(x, y) = sum(convRange, convX(x, y + convRange)) * normalizationFactor;
            
        Var xo("xo"), yo("yo"), xi("xi"), yi("yi");

        // schedule
        clamped.compute_at(convY, Var::gpu_blocks()).gpu_threads(x, y);
        convX.compute_at(convY, Var::gpu_blocks()).gpu_threads(x, y);
        convY.compute_root().tile(x, y, xo, yo, xi, yi, 8, 8).gpu_blocks(xo, yo).gpu_threads(xi, yi);
        
        // alternative schedule: works on AMD, but still fairly slow
        //const int vecFactor = 16;
        //convX.compute_root().tile(x, y, xo, yo, xi, yi, 2 * vecFactor, 32).gpu_blocks(xo, yo).gpu_threads(xi).vectorize(yi, vecFactor);
        //convY.compute_root().tile(x, y, xo, yo, xi, yi, 32, 2 * vecFactor).gpu_blocks(xo, yo).gpu_threads(yi).vectorize(xi, vecFactor);
        
        Target target = get_host_target();
        target.set_feature(Target::OpenCL);
        convY.compile_jit(target);

        return convY;
    }

    int main(int argc, char **argv)
    {
        Image<float> input = load<float>("../../media/sibenik_bw.png");

        Func blur = boxblur(input, 3);
        // init gpu buffers etc.
        Image<float> output = blur.realize(input.width(), input.height());
        
        // performance eval.
        printf("Starting benchmark\n");
        double best_time;
        for (int i = 0; i < 3; i++) {

            double t1 = current_time();

            // Run the filter 5 times.
            for (int j = 0; j < 5; j++) {
                blur.realize(output);
            }
            // Force any GPU code to finish by copying the buffer back to the CPU.
            output.copy_to_host();
            double t2 = current_time();

            double elapsed = (t2 - t1) / 5;
            if (i == 0 || elapsed < best_time) {
                best_time = elapsed;
            }
        }
        printf("%1.4f s\n", best_time / 1000);

        save(output, "images_out/boxblurred.png");

        return 0;
    }

The code executes a simple box blur on the GPU. On the Gtx 580 the best timing is usually < 3 ms for a 1 MP grayscale image, while the same code takes more than 200 ms (!) on the HD 7870. I found that the "alternative Schedule" (see code) gives more reasonable performance on the AMD card, but of course is far from being a good schedule (shared memory unused). Are there any known issues with AMD graphics cards when using shared memory? I really want to use the schedule which uses shared memory, because this seems to be the smarter of the two (and also comes closer to the performance of the "optimal" CPU schedule from https://lists.csail.mit.edu/pipermail/halide-dev/2015-January/001341.html). And for my application I will run the simple box blur several hundred times...

Thanks for your help.

**Comment by abadams** [comment]
This is a neat example of OpenCL not really being very portable. I suspect
you'll need to detect if the card is nvidia or amd and use a different
schedule.

One thing that might be messing up the AMD card is some sort of bank
conflict into shared memory. You could try: convX.reorder_storage(y, x) and
see what that does.

**Comment by dvicini** [comment]
Hi Andrew,

Thanks for your reply. I tried the reorder_storage, but that did not seem to change anything. It's really strange how some schedules seem to be much much slower than expected. I also tried the following schedule: (knowing that it probably is not the fastest one)

    clamped.compute_at(convX, Var::gpu_blocks()).gpu_threads(x, y);
    convX.compute_root().gpu_tile(x, y, 8, 8);
    convY.compute_root().gpu_tile(x, y, 8, 8);

This schedule is also extremely slow (~110 ms), but gets 5 (!) times faster when I remove the first line and don't try to load the clamped image into shared memory. I have some basic CUDA experience and I think in CUDA this step would really help to speed up the computations, because the threads of convX would not have to look up the same data from global memory multiple times. Of course I am only speculating here, because I don't have CUDA installed at the moment (or better OpenCl for direct comparison). I don't really need a very fast AMD version right now, but I am still wondering why this kind of optimization fails horribly. A somewhat working AMD version is:

	Var x("x"), y("y");
	Func clamped("clamped");
	clamped(x, y) = input(clamp(x, 0, input.width() - 1), clamp(y, 0, input.height() - 1));

	const float normalizationFactor = 1.0f / ((2 * f + 1) * (2 * f + 1));
	RDom convRange(-f, 2 * f + 1, "conv range");
	Func convX("convX");
	convX(x, y) = 0.0f;
	convX(x, y) += clamped(x + convRange, y);
	Func convY("convY");
	convY(x, y) = sum(convX(x, y + convRange)) * normalizationFactor;

	Var xo("xo"), yo("yo"), xi("xi"), yi("yi");

    convX.compute_at(convY, Var::gpu_blocks()).gpu_threads(y).vectorize(x, 16).unroll(x);
    convX.update(0).reorder(x, convRange, y).gpu_threads(y).vectorize(x, 16).unroll(x);
    convY.compute_root().tile(x, y, xo, yo, xi, yi, 32, 64).gpu_blocks(xo, yo).gpu_threads(yi).vectorize(xi, 16).unroll(xi);
