### ISSUE TITLE
CMake and the "new build system" of Xcode : Part 2

### ISSUE THREAD

**Issue by slomp** [halide/Halide#6987]
This one is likely related to https://github.com/halide/Halide/issues/6976.

Weirdly enough, after deleting my `CMakeCache.txt` and running `cmake -S ../../ -DLLVM_DIR=/opt/homebrew/opt/llvm/lib/cmake/llvm -DHalide_SHARED_LLVM=YES -G Xcode`, I now got this:
(It doesn't look like anything has changed in `main`, so I am a bit puzzled)

```
CMake Error in python_bindings/test/generators/CMakeLists.txt:
  The custom command generating

    ThirdParty/Halide/build/xcode/python_bindings/test/generators/py_aot_addconstant.h

  is attached to multiple targets:

    py_aot_addconstant.update
    pyext_addconstant_module_definition

  but none of these is a common dependency of the other(s).  This is not
  allowed by the Xcode "new build system".
```

**Comment by alexreinking** [comment]
Thanks. I have my Mac up and running finally so I think I can test Xcode now.
