### ISSUE TITLE
Halide::undef<>() is unsafe to use at static-initialization time

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#706]
Some code in the wild was using undef<>() to initialize static variables, e.g.

     static const ComplexExpr undef_z(undef<float>(), undef<float>());

this can intermittently crash, because undef<>() uses Call::make(), which references Internal::Call::undef (a statically-initialized string); due to the classic Static Initialization Order Fiasco, if "undef_z" happens to have its ctor run before that of Internal::Call::undef, we crater.

(I'm guessing there are probably other calls that are similarly unsafe.)

We should either make these safe to use, or make them fail consistently rather than intermittently. (Simply documenting them as "don't use in this way" is unsatisfying as intermittent failures will almost certainly creep in.)

**Comment by abadams** [comment]
We could probably just change all the const strings in IR.cpp to const char *. A const char * -> string conversion whenever you construct an intrinsic is probably not going to have any effect on performance (relative to a string copy).
