### ISSUE TITLE
BoundaryConditions Bug with unbounded Dimensions

### ISSUE THREAD

**Issue by dvicini** [halide/Halide#708]
Hi,

I wanted to use a mirror image style boundary condition and tried using BoundaryConditions::mirror_image. My code is as follows:

	int main(int argc, char **argv)
	{
		Image<float> input = load<float>("../../media/sibenik.png");
		int width = input.width(), height = input.height();
		Var x("x"), y("y"), c("c");
		Func clamped; 
		//clamped(x, y, c) = input(clamp(x, 0, width - 1), clamp(y, 0, height - 1), c);
		clamped(x, y, c) = BoundaryConditions::mirror_image(input, 0, width, 0, height)(x, y, c);
	
		Func output;
		output(x, y, c) = (clamped(x + 10, y, c) + clamped(x - 10, y, c)) / 2.0f;
		Image<float> outputImg = output.realize(width, height, 3);
		save(outputImg, "images_out/clamptest.png");
		printf("Success\n");
		std::getchar();
	}

When I run this code, I get the error message:

    Error: Input buffer i1 is accessed at -10, which is before the min (0) in dimension 2
This confuses me, since dimension 2 should never be accessed at -10. I mean this is just the color dimension. The code works fine if I use the standard clamping instead (commented line in the above code). I also had a look at the source in BoundaryConditions.cpp and couldn't find an explanation for this error. The code works, if I also bound the color dimension like this:  BoundaryConditions::repeat_edge(input, 0, width, 0, height, 0, 3). However, this is not really what I need, since I want to use the color coordinate "as is", without any additional calculations. (also for eventual unrolling etc.). Looking at the Halide source code, I think bounding only the first 2 dimensions should work fine (line 119 in BoundaryConditions.cpp). I am using the latest Halide nightly windows 64 build. Image loading/saving code from the Halide tutorials.

Any ideas?

**Comment by abadams** [comment]
It's a bug. I'll figure out a fix.

A workaround is:

Func in;
in(x, y, c) = input(x, y, c);
Func clamped = BoundaryConditions::mirror_image(in, ...);

i.e. apply the boundary condition to a Func, not to an Image.

- Andrew

**Comment by abadams** [comment]
Fixed by fdbc6dd4183d90fa9ea48e429cbb853d7dac6923
