### ISSUE TITLE
[HVX] EliminateInterleaves is broken

### ISSUE THREAD

**Issue by rootjalex** [halide/Halide#7100]
On a benchmark I see the following pattern enter EliminateInterleaves:
```
x + interleave(y)
```
The output is:
```
interleave(deinterleave(x) + y)
```

I understand that EliminateInterleaves is supposed to push `interleave` towards the top of an `Expr`, but producing two swizzles from one swizzle seems like it does not follow a good cost model. I think the issue is simple to fix, this line:
https://github.com/halide/Halide/blob/8f210f1167e7454d7e33b38a1f9e583c29695070/src/HexagonOptimize.cpp#L1419

should probably use a `>` instead of a `>=`. I'm only opening this issue in case there's something more complicated that I don't understand happening - otherwise I'll just open a PR to fix this.

I also think FuseInterleaves should be merged with EliminateInterleaves, as they seem to essentially perform the same function, but FuseInterleaves only tries to fix widening ops while EliminateInterleaves tries to fix narrowing ops (in the `Call` visitor).

@pranavb-ca @steven-johnson

**Comment by steven-johnson** [comment]
Unfortunately, no, I have no thoughts on this. Is this in the category of "always been broken" or do we think it's a new breakage?

**Comment by rootjalex** [comment]
It looks like Dillon changed the behavior ~17 months ago to be less restrictive (it used to require `does_not_yield == 0` essentially). I think it's been broken since then.

**Comment by steven-johnson** [comment]
I leave it to the judgement of you and @pranavb-ca -- this is outside of my expertise

**Comment by pranavb-ca** [comment]
Hey, @rootjalex - I looked at this and I think you are right. I couldn't find a counter-example to argue against your change. I can push a change if you want or you could fold it into an upcoming PR if you are planning one imminently.

**Comment by rootjalex** [comment]
Awesome, thanks @pranavb-ca ! I have a small PR to merge with this, I’ll try to make it this week.
