### ISSUE TITLE
Halide eigenvector computation

### ISSUE THREAD

**Issue by gchauras** [halide/Halide#711]
I dont suppose the linear algebra has gone to the level of SVD or QR decompositions. Do you think there is any chance of beating eigen at these algorithms in Halide given performance improvement of basic matrix mult?

**Comment by kree-colemcalughlin** [comment]
I think there is a very good chance that we can beat Eigen across the board. The QR and SVD decompositions are even more interesting than the matrix multiply code, as they are much more complex pipelines and we can experiment with interesting schedules across the whole computation. That being said, you are correct in supposing that these algorithms have not been implemented yet. 

I started looking at dense QR decompositions using Householder transforms, with the work that is currently in the matrix_class branch. Unfortunately, I quickly ran into some fundamental limitations in that branch that will take quite a while to fix.

The other approach is to look at implementing a QR factorization generator. This would be analogous to the work that is currently pretty stable in the apps/linear_algebra directory, which implements the BLAS api in halide. So we could extend this work to parts of the LAPACK api, and implement subroutines like DGEQRF().

None of this work is on the immediate horizon, however, I may get to devote some time to it over the summer.

**Comment by gchauras** [comment]
Thanks. Good to know.
