### ISSUE TITLE
Can we collapse assert checks into a halide_runtime utility?

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#714]
All AOT-generated filters include lots of sanity assertions in the prologue; instead of explicit code, could we put the relevant things-to-check into a data structure and call a halide-runtime provided function to do the assertion check?

For an app that includes dozens of filters, this could provide meaningful code savings (especially for mobile platforms, where code size can be critical)

**Comment by abadams** [comment]
A lot of it is because every assertion generates a unique landing pad with cleanup code for all allocations before it. If we dynamically maintained an stack of cleanup code to run on assertion failure it'd be less code.

On a related note, I suspect we don't call device_free on assertion failure.

**Comment by abadams** [comment]
(and every allocation is an assertion too, so there are often lots of allocations in scope)

**Comment by steven-johnson** [comment]
I suspect the structured-errors-and-destructors patch addressed this as much as we're likely to anytime soon. Vote to close.

**Comment by abadams** [comment]
If we add a function call to check for buffer aliasing bugs then it may as well take on all the other input buffer checks, but that can be tracked in issue  #719
