### ISSUE TITLE
Unable to copy-n-paste auto-scheduled C++ code: GeneratorBase::pipeline is private

### ISSUE THREAD

**Issue by antonysigma** [halide/Halide#7148]
From the Halide tutorial https://halide-lang.org/tutorials/tutorial_lesson_21_auto_scheduler_generate.html:

> The generated schedule that is dumped to file is an actual
> Halide C++ source, which is readily copy-pasteable back into
> this very same source file with few modifications. Programmers
> can use this as a starting schedule and iteratively improve the
> schedule.

However, when I include the auto-scheduled header file by:

```c++
// foobar_generator.cpp
class FoobarGen : public Generator<FoobarGen> {
...
  void schedule() {
    #include "foobar.schedule.h"
    apply_schedule_foobar(this->pipeline, this->target);
  }
};
```

It returns compiler error:
```
 error: ‘Halide::NamesInterface::Pipeline Halide::Internal::GeneratorBase::pipeline’ is private within this context
      Func f104 = pipeline.get_func(86);
                  ^~~~~~~~
../source/subprojects/Halide-10.0.0-x86-64-linux/include/Halide.h:26820:14: note: declared private here
     Pipeline pipeline;
```

I am wondering if the tutorial is outdated? Do I expect to manually expose `Func f0` to `Func f104` manually as private members `private: Func Foobar::f0` in order to utilize the auto-scheduled schedules in C++ ? It sounds like a lot of manual work.

I am using Halide 10.0 by the way, but I can try again in Halide 14.0.

**Comment by ashishUthama** [comment]
Try using these as a workaround till someone else can give a better answer about the why: get_pipeline() and get_target()

**Comment by antonysigma** [comment]
Thanks @ashishUthama . The following pseudo code works for me.

Now, how do I help updating the tutorial page? Could you point me at the file that generate the HTML? I can contribute back with a PR.

```c++
void schedule() {
    #include "foobar.schedule.h"
    apply_schedule_foobar(get_pipeline(), get_target());
  }
```
