### ISSUE TITLE
Lesson2 jpeglib error

### ISSUE THREAD

**Issue by AndreiBaraian** [halide/Halide#7150]
Hello! I was trying to compile lesson02 and stumbled on this error: 

`
../Halide-14.0.0-x86-64-linux/share/Halide/tools/halide_image_io.h:31:10: fatal error: jpeglib.h: No such file or directory
   31 | #include "jpeglib.h"
      |          ^~~~~~~~~~~
compilation terminated.
`

The command used to compile: `g++ tut2.cpp -g -I ../Halide-14.0.0-x86-64-linux/include -I ../Halide-14.0.0-x86-64-linux/share/Halide/tools -L ../Halide-14.0.0-x86-64-linux/bin -lHalide 'libpng-config --cflags --ldflags' -ljpeg -lpthread -ldl -o lesson_02 -std=c++17`

Note: I have only downloaded the binaries from the release section, but no building with llvm. I am quite new to this, so I am not sure if it should be done or it can be ommited. 

For lesson 01, the compilation was successful.

**Comment by abadams** [comment]
This means you don't have the libjpeg headers on your system. It looks like you're on linux. If it's ubuntu or similar, try `sudo apt-get install libjpeg-dev`

**Comment by AndreiBaraian** [comment]
@abadams I've installed it, but now I got this `./lesson_02: error while loading shared libraries: libjpeg.so.9: cannot open shared object file: No such file or directory` . I though that somehow then the headers are added to the path automatically.

**Comment by AndreiBaraian** [comment]
Solved. One thing that I forgot was to recompile after installing the library. Also, if `sudo apt-get install libjpeg-dev` does not install v9 of the library, one can try the `sudo apt install libjpeg9-dev`. I've played with both of these, so not really sure which one was the solution. Thanks a lot!
