### ISSUE TITLE
[RISC-V] some vector schedules cause LLVM error

### ISSUE THREAD

**Issue by miles-rusch-berkeley** [halide/Halide#7158]
[matrix_multiplication.cpp.zip](https://github.com/halide/Halide/files/9966350/matrix_multiplication.cpp.zip)

the following vectorization schedule, defined in line 47, causes an error when compiling to RISCv Vector but not when compiling to ARM SVE:

    //ISSUE: no llvm error if we replace y with x in the following line:
    out.vectorize(y, vlen/arch_bits);

**Comment by miles-rusch-berkeley** [comment]
The error message is:

`Intrinsic name not mangled correctly for type arguments! Should be: llvm.experimental.vp.strided.store.nxv4f32.p0.i64
ptr @llvm.experimental.vp.strided.store.nxv4f32.p0.v32781f64
Internal Error at /Users/milesrusch/Documents/risc-v/rvv/llvm15/Halide/src/CodeGen_LLVM.cpp:632 triggered by user code at :
Condition failed: !verifyFunction(*function, &llvm::errs()):`

[matrix_multiplication.cpp.zip](https://github.com/halide/Halide/files/10127199/matrix_multiplication.cpp.zip)

**Comment by zvookin** [comment]
Fixed in https://github.com/halide/Halide/pull/7212 .

**Comment by miles-rusch-berkeley** [comment]
After pulling main with the patch, I am now getting a similar error:

```
 % source halide_gen_run.sh gaussian_blur
Intrinsic name not mangled correctly for type arguments! Should be: llvm.vector.insert.nxv8i8.nxv4i8
ptr @llvm.vector.insert.nxv8i8.v32i8
...
Intrinsic name not mangled correctly for type arguments! Should be: llvm.vector.insert.nxv8i8.nxv4i8
ptr @llvm.vector.insert.nxv8i8.v32i8
Internal Error at /Users/milesrusch/Documents/risc-v/rvv/llvm15/Halide/src/CodeGen_LLVM.cpp:632 triggered by user code at :
Condition failed: !verifyFunction(*function, &llvm::errs()):
zsh: abort      DYLD_LIBRARY_PATH=libHalide ./$1_gen
```
