### ISSUE TITLE
GPU code fails if image smaller than thread block size

### ISSUE THREAD

**Issue by dvicini** [halide/Halide#718]
Hi,

I've tried running very simple code in OpenCl (as I have done before). Consider the following code example:

```
int main(int argc, char **argv)
{
    Target target = get_host_target();
    target.set_feature(Target::OpenCL);

    Image<float> input = load<float>("../../media/rgb_non_pow2_small.png");

    Var x, y, c;
    Func f;
    f(x, y, c) = clamp(1.5f * input(x, y, c), 0.0f, 1.0f);

    f.gpu_tile(x, y, 256, 1);

    Image<float> output = f.realize(input.width(), input.height(), 3);
    output.copy_to_host();
    save(output, "images_out/test.png");
    return 0;
}
```

The code is pretty straightforward, but fails on certain input sizes. The code works fine, as long as the input image has a width of >= 256. It does not matter if the width of the input image is divisible by 256 or not. Halide seems to handle any boundary conditions fine. However, if the input has a width of less than 256 (here: image size of 130 x 217), the code fails with the following error message:

```
Error:
Output buffer f0 is accessed at -126, which is before the min (0) in dimension 0
```

Please tell me if I'm doing something wrong here, but it seems that the error checking which Halide does when the image size is not divisible by the block size is missing for this case. I am still working on windows 64 bit and got this issue on my AMD graphics card at home. (have not yet tried it on the Nvidia GPU in the lab, but I guess it's a Halide issue and not a GPU vendor specific issue)

Cheers,
Delio

**Comment by zvookin** [comment]
I don't see any bug here. gpu_tile is using the same split based mechanism
as vectorize, which introduces a constraint that the extent of a dimension
must be at least the size of the split on that dimension.

Originally, all Halide generated GPU kernels had an if statement around the
entire kernel to make sure the effective index was inside the actual valid
area of the computation. This  had a notable performance hit so it is just
as well this is no longer the case. However it now seems difficult to
handle the output buffer constraint as one cannot use BoundaryConditons on
an output buffer.

-Z-


On Mar 29, 2015, at 11:29 AM, dvicini <notifications@github.com> wrote:

Hi,

I've tried running very simple code in OpenCl (as I have done before).
Consider the following code example:

int main(int argc, char **argv)
{
    Target target = get_host_target();
    target.set_feature(Target::OpenCL);

    Image<float> input = load<float>("../../media/rgb_non_pow2_small.png");

    Var x, y, c;
    Func f;
    f(x, y, c) = clamp(1.5f * input(x, y, c), 0.0f, 1.0f);

    f.gpu_tile(x, y, 256, 1);

    Image<float> output = f.realize(input.width(), input.height(), 3);
    output.copy_to_host();
    save(output, "images_out/test.png");
    return 0;
}

The code is pretty straightforward, but fails on certain input sizes. The
code works fine, as long as the input image has a width of >= 256. It does
not matter if the width of the input image is divisible by 256 or not.
Halide seems to handle any boundary conditions fine. However, if the input
has a width of less than 256 (here: image size of 130 x 217), the code
fails with the following error message:

Error:
Output buffer f0 is accessed at -126, which is before the min (0) in dimension 0

It seems that the error checking which Halide seems to do when the image
size is not divisible by the block size is missing here.

Cheers,
Delio

—
Reply to this email directly or view it on GitHub
<https://github.com/halide/Halide/issues/718>.

**Comment by dvicini** [comment]
But how is the case when the block size does not divide the image size handled then? In the above example a block size of 128x1 works fine, and the image has a size of 130 x 217, which is not divisible by 128 in any way. This means there certainly are threads which would access the output (and input) buffer out of bounds. Or is this case somehow caught by GPU internal mechanisms? (btw. the behaviour is exactly the same here in the lab on a Nvidia GPU)

Is there any way to handle this issue? (except adjusting the block size to the input size of course) It is not terribly important for me at the moment, but still it would be nice to have a clean solution to this.

**Comment by zvookin** [comment]
Threads that are conceptually outside the image have their pointer accedes
adjusted to be inside the image. Due to efficiency concerns, this only
works for images with extent of at least one tile.

Adding "debug" to the target will write the generated OpenCL code to the
output. Note in the example code sent, the target is not used for anything.
Setting the HL_JIT_TARGET environment variable to "host-opencl-debug" may
be an easy way to get the target set up for realize.

-Z-


On Mar 30, 2015, at 1:29 AM, dvicini <notifications@github.com> wrote:

But how is the case when the block size does not divide the image size
handled then? In the above example a block size of 128x1 works fine, and
the image has a size of 130 x 217, which is not divisible by 128 in any
way. This means there certainly are threads which would access the output
(and input) buffer out of bounds. Or is this case somehow caught by GPU
internal mechanisms? (btw. the behaviour is exactly the same here in the
lab on a Nvidia GPU)

Is there any way to handle this issue? (except adjusting the block size to
the input size of course) It is not terribly important for me at the
moment, but still it would be nice to have a clean solution to this.

—
Reply to this email directly or view it on GitHub
<https://github.com/halide/Halide/issues/718#issuecomment-87590337>.

**Comment by dvicini** [comment]
I see. So manually adjusting the tile size is currently the best option?

About the target: I forgot the f.compile_jit(target) in the above code, yes. (even though this does not affect the error I get)

**Comment by zvookin** [comment]
For the input buffer, you can add an explicit boundary condition using
BoundaryConditions. For the output buffer, you will need to introduce
intermediate storage on the GPU. Adding compute_root to the scheduling of
the gpu_tile'ed Func is the easiest way to do so. It should be possible to
do so without actually introducing any additional memory usage or
device/host copies, though I don't think we can quite get that right at
present. (Doing it optimally involves copying from a GPU buffer to a
different host buffer, i.e. between buffers of different shapes, and there
is no support for that. I believe at present this will require one extra
device to device or host to host copy.)

-Z-

**Comment by dvicini** [comment]
Only adding compute_root() does not seem to change anything. (isn't compute_root the default for the function which is realized?) I can "solve" the problem by both clamping the input and copying the output of f (by computing f at root level and creating a new func which just copies the values of f. The new Func could be tiled 8x8 or something like that). Of course this has a small impact on performance and does not work for tiny images.

**Comment by zvookin** [comment]
Sorry, I mean introducing an extra Func and scheduling that compute_root on
the GPU. Something like so:

    Var x, y, c;
    Func input_bounded = BoundaryConditions::repeat_edge(input);
    Func f, g;
    f(x, y, c) = clamp(1.5f * input_bounded(x, y, c), 0.0f, 1.0f);

    f.compute_root().gpu_tile(x, y, 256, 1);
    g(_) = f(_);

    g.realize(...)

Sorry I have not compiled this...

-Z-

**Comment by zvookin** [comment]
"introducing an extra Func and scheduling that compute_root on the GPU" is
unclear. The new Func is on the CPU in the code given.

-Z-

**Comment by dvicini** [comment]
Yes, thats what worked for me too :)

**Comment by dsharletg** [comment]
It sounds like this was resolved, please reopen if necessary.
