### ISSUE TITLE
Lesson 9 and 12: Time duration mismatch

### ISSUE THREAD

**Issue by AndreiBaraian** [halide/Halide#7263]
Hi,

While trying the code from CVPR 2015 and benchmarking with my own written std::chrono::now() and the function from clock.h which was provided in lesson 9 and lesson 12, I have noticed an inconsistency in terms of reported time. In the clock.h header, it is already mentioned that the output of current_time() is in milliseconds, however in both lessons, the duration is computed by (t2-t1) / 100, but which results in deciseconds, not milliseconds.

**Comment by abadams** [comment]
It's divided by 100 because there are 100 iterations of the benchmarking loop.

**Comment by AndreiBaraian** [comment]
Indeed, my bad. Thanks!
