### ISSUE TITLE
CMake Cross-compilation for baremetal target

### ISSUE THREAD

**Issue by stevesuzuki-arm** [halide/Halide#7281]
### Background
As mentioned in [README_cmake](https://github.com/halide/Halide/blob/main/README_cmake.md#cross-compiling), Cross-compiling in CMake can be tricky, since CMake doesn't easily support compiling for both the host platform and the cross-platform within the same build. This gets more tricky when we target baremetal environment, where the application is built by somehow uncommon toolchain and the runtime runs without or limited OS support. Thus, we often end up with hacky workaround, which, as one can imagine, makes the build system inflexible and easy to break when updating. Also, I would assume this is probably raising the bar for users.

In this ticket, I'd like to address the identified issues in existing CMake build and bring proposal solutions for discussion.

### Issues

1. Halide CMake package asks `Threads` library as mandatory, which some of the baremetal toolchain doesn't have.
1.  `add_halide_runtime()` doesn't work with cross-compiler toolchain
1.  `add_halide_generator()` has an issue in exporting/importing the generator as package
1. Auto Scheduler is not available with the existing approach shown in [test/integration/xc](https://github.com/halide/Halide/tree/main/test/integration/xc)
1. Runtime support is poor for baremetal (this is inevitable by nature though)
1. There is no sample in `tutorial/` nor `apps/` from which users can learn quickly how to write CMake to cross-compile app with Halide.

**Comment by stevesuzuki-arm** [comment]
#7282 for Issue 1
#7283 for Issue 3
#7284 for Issue 2
#7285 for Issue 4
#7286 for Issue 5

**Comment by stevesuzuki-arm** [comment]
@alexreinking @steven-johnson may I ask you to review the PRs, please?

**Comment by alexreinking** [comment]
Definitely! Thank you for what appears to be a major contribution!

**Comment by steven-johnson** [comment]
> @alexreinking @steven-johnson may I ask you to review the PRs, please?

The CMake-specific changes are better handled by @alexreinking, I've assigned them to him.

**Comment by stevesuzuki-arm** [comment]
For Issue 6, I've added `HelloBaremetal` sample app in #7286. Now, all the PRs are ready to review.

**Comment by stevesuzuki-arm** [comment]
I appreciate for your quick feedback! I will have a look and update.

**Comment by stevesuzuki-arm** [comment]
Now that [HelloBaremeal](https://github.com/halide/Halide/tree/main/apps/HelloBaremetal) works, I will close this item and leave the remaining further rework to #7344
