### ISSUE TITLE
PyPI "daily" updates are broken

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#7293]
We attempt to do "daily" uploads of Halide-for-Python to the PyPI test server, but these don't work, because apparently the test server doesn't ever let you overwrite/replace an upload. Presumably we need to append a timestamp, hash, etc?

**Comment by dragly** [comment]
@steven-johnson I do not think the fix I attempted worked. The workflow complains that `--build-number` is not recognized as an argument. Maybe the issue should be re-opened?
