### ISSUE TITLE
Expose call_argv_fast from Callable

### ISSUE THREAD

**Issue by twesterhout** [halide/Halide#7314]
Dear Halide team,

Would it be possible to make [`Halide::Callable::call_argv_fast`](https://github.com/halide/Halide/blob/main/src/Callable.h#L284) public? Since `Callable` is currently not used in the tutorials and is not displayed by Doxygen, this change shouldn't affect too many users. And, of course, a big warning could be added to inform users about possible segfaults if `call_argv_fast` is invoked with wrong argument types.

### Motivation

I'm working on Haskell wrappers for Halide as part of Tweag Open Source Fellowship. Haskell has static typing and very good support for polymorphism, and that means that although I know the types of arguments when invoking the Callable, I can't pass them to C++ as template arguments. So what I'd like to implement is similar to what the Python bindings do in [`PyCallable`](https://github.com/halide/Halide/blob/main/python_bindings/src/halide/halide_/PyCallable.cpp#L54).
If there are other preferred methods of calling Halide pipelines with low overhead when argument types are unknown until the runtime of the program, any pointers will be highly appreciated.

Thanks,
Tom

**Comment by steven-johnson** [comment]
This sounds pretty awesome!

I'd definitely be willing to make it public, we'd just have to add the right amount of caveats in the documentation. (Of course, it's not really any more unsafe than the existing _argv calls provided by AOT codegen, so it's really a question of ensuring people realize it's public only for code of the sort you are talking about).

Please feel free to open a PR, and please keep us up to date on this work to the extent you can :-)
