### ISSUE TITLE
dependencies/llvm/CMakeLists.txt incompatible with latest llvm-project

### ISSUE THREAD

**Issue by MaskRay** [halide/Halide#7319]
According to https://reviews.llvm.org/D139752#4006602 , latest llvm-project would cause `<command-line>:0:70: error: token "=" is not valid in preprocessor expressions`. According to https://reviews.llvm.org/D139752#4104371 , it's likely a fault in Halide `dependencies/llvm/CMakeLists.txt`.

**Comment by alexreinking** [comment]
That doesn't seem to be relevant... that line has been there and working since like LLVM 12. I'm going to take a deeper dive.

**Comment by alexreinking** [comment]
Okay, using `separate_arguments` here _does_ fix things. It worked before because there weren't duplicates in `LLVM_DEFINITIONS` but the patch in question now duplicates `-D_FILE_OFFSET_BITS=64` which messes with CMake's argument de-duplication somehow. :facepalm:

**Comment by alexreinking** [comment]
The `-DHalide_TARGET` setting was irrelevant.
