### ISSUE TITLE
'halide_image_io.h' file not found

### ISSUE THREAD

**Issue by Carpetfizz** [halide/Halide#7364]
Unable to compile [lesson_02](https://halide-lang.org/tutorials/tutorial_lesson_02_input_image.html) using a brew+CMake Halide installation.

Platform :
* macOS 12.5.1
* Architecture : Apple M1 Max

Steps to reproduce :
1. `brew install halide`
2. Add Halide to `CMakeLists.txt`

```CMake
cmake_minimum_required (VERSION 3.10)
project(HalideTutorials)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED YES)
set(CMAKE_CXX_EXTENSIONS NO)
# Set LLVM CMake Config Directory :
set(LLVM_DIR "/opt/homebrew/Cellar/llvm@14/14.0.6/lib/cmake/llvm")
# Find Halide :
find_package(Halide REQUIRED COMPONENTS shared)
# Link Halide to all targets :
link_libraries(Halide::Halide)
# lessons :
add_executable(lesson_01 lesson_01.cpp)
add_executable(lesson_02 lesson_02.cpp)
```

3. Include offending header in source file :

```
#include <Halide.h>
#include "halide_image_io.h"
```

4. Error :
```
/Users/ajay/Documents/Code/halide-tutorials/lesson_02.cpp:2:10: fatal error: 'halide_image_io.h' file not found
#include "halide_image_io.h"
``` 

I'm able to `#include <Halide.h>` and I can pass `lesson_01` just fine, but I can't seem to include anything from the `tools/` directory.

Thanks for any assistance!

**Comment by steven-johnson** [comment]
...I wasn't aware that there was a `brew` install for Halide. I suspect that our CMake helper logic needs some tweaking. Tagging @alexreinking for his thoughts.

**Comment by alexreinking** [comment]
The `halide_image_io.h` header is provided by the `Halide::ImageIO` target, not by `Halide::Halide`. You must link to it, too.

Please see our documentation, here: https://github.com/halide/Halide/blob/main/README_cmake.md#imported-targets

**Comment by Carpetfizz** [comment]
Thank you Steven and Alex! I saw that section in the docs but have limited CMake knowledge to know that those were modules meant to be included and not automatically imported.
