### ISSUE TITLE
Is Int(8) overflow undefined behavior in Halide?

### ISSUE THREAD

**Issue by twesterhout** [halide/Halide#7365]
The following code fails with an exception:
```cpp
auto x = Expr{int8_t{-128}};
auto y = cast(x.type(), abs(x));
std::cout << evaluate<int8_t>(y) << std::endl;
```
The error is "Signed integer overflow occurred during constant-folding. Signed integer overflow for int32 and int64 is undefined behavior in Halide". What I'm wondering is, should it say that _any_ signed integer overflow is undefined? or is there something wrong with my code? or could this be bug?

Thanks!

**Comment by abadams** [comment]
This is a bug. I'll fix it.
