### ISSUE TITLE
Backport #7315 to release/15.x

### ISSUE THREAD

**Issue by twesterhout** [halide/Halide#7382]
Hello,

I'm wondering whether #7315 could be backported to the release branch for version 15 of Halide. I'm relying on it pretty heavily in https://github.com/twesterhout/halide-haskell, and having a custom build of Halide is fine for development, but we're nearing the first release, and I'm hoping to use the Halide from https://github.com/NixOS/nixpkgs. Nixpkgs currently contains version 14 of Halide, but if #7315 was backported to release/15.x, I could make a PR for nixpkgs to include the version 15 of Halide.

Thanks!

**Comment by steven-johnson** [comment]
You bet, https://github.com/halide/Halide/pull/7383

**Comment by twesterhout** [comment]
Great, thanks!
