### ISSUE TITLE
more static promises about buffers

### ISSUE THREAD

**Issue by abadams** [halide/Halide#74]
Currently you can tell halide, e.g., that an input buffer will have a stride of 4 in the second dimension. You can make no such promises about the output buffer.

Halide also assumes that input and output buffers have unaligned base pointers. It may be useful to be able to make promises about this on arm (on modern x86 unaligned loads are fast if they happen to be aligned).

**Comment by zvookin** [comment]
@abadams can we close this now that set_host_alignment exists?
