### ISSUE TITLE
Explicitly Require C++11

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#741]
It seems we've finally gotten to the point where all of our platforms have the requisite level of C++11 support; I propose we codify this formally, ensure our build files specify C++11 everywhere, and remove the various ifdef's that limit certain features (eg Generators). This would also allow us freedom to use C++11 features more freely (eg variadic templates and unique_ptr).

**Comment by abestephensg** [comment]
+1

**Comment by abadams** [comment]
+1

**Comment by abadams** [comment]
This is done. Closing.
