### ISSUE TITLE
Precompiled Halide distrib tutorials do not compile

### ISSUE THREAD

**Issue by gchauras** [halide/Halide#742]
We are using Halide in Fredo's computational photo class and I was going to ask students to use the precompiled binaries. I get the following (and more) errors on Ubuntu, g++ 4.8.2, llvm 3.4.
```
g++ -std=c++11  -Iinclude -I. -g -Wall tutorial/lesson_01_basics.cpp bin/libHalide.a  -lz -lpthread -ldl -lncurses -lpng -o bin/lesson_01_basics
bin/libHalide.a(DeviceInterface.o): In function `std::bitset<21ul>::set(unsigned long, bool) [clone .part.8]':
DeviceInterface.cpp:(.text.unlikely._ZNSt6bitsetILm21EE3setEmb.part.8+0x1d): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
bin/libHalide.a(Func.o): In function `Halide::Target::set_feature(Halide::Target::Feature, bool)':
```
I am using the following line to compile the tutorials. Am I missing something. In general it would help if the precompiled distribs had a makefile. I am sure I am missing a compiler flag or link library.
```
CXX		      := g++ -std=c++11
HALIDE_INC := include
HALIDE_LIB := bin/libHalide.a

$(BIN_DIR)/%: tutorial/%.cpp $(HALIDE_LIB) $(HALIDE_INC)
	$(CXX) -g -Wall $< $(HALIDE_LIB) -lz -lpthread -ldl -lncurses -lpng -o $@
```

**Comment by abadams** [comment]
I think that's a libstdc++ version error. C++ libraries are annoyingly
non-portable. The prebuilts are compiled with g++ 4.9.2. If your system is
going to be the same as the students', then you could make your own
prebuilts. Use llvm 3.6 though.

**Comment by abadams** [comment]
I compile libHalide with gcc 4.8 I don't get that symbol. I'll email you a copy of those binaries to test.

**Comment by gchauras** [comment]
I also have a 4.8 machine. I will use that. In any case, its not clear that all students will have the same compiler. Some are even going to try windows.
