### ISSUE TITLE
GPU memory allocation bug (?)

### ISSUE THREAD

**Issue by dvicini** [halide/Halide#743]
Hi,

I´ve already posted this in the mailing list a few days ago (no replies though), but have now simplified the code example enough to post it as an issue.

I tried to get an algorithm to work on the GPU, which needs store some values in a small 2D window around each pixel explicitly. However, I get a CL_OUT_OF_RESOURCES error when using OpenCL and a Access Violation Exception when using cuda. Out of resources doesn't make too much sense I think, since I realize only over a 128 * 128 * 3 domain. My code is as follows: (note that in the example code the schedule is of course a really bad one, since I tried to make a minimal example)

    #include <Halide.h>
    #include <stdio.h>
    using namespace Halide;

    #define USE_2D
    int main(int argc, char **argv)
    {
        Target target = get_host_target();
        target.set_feature(Target::OpenCL);
        int gpu_tile_x = 8, gpu_tile_y = 8;

        Var x("x"), y("y"), u("u"), v("v"), c("c"); 

        Func f("f");
        f(x, y, c) = sqrt(x * y);

        int r = 1, wnd_size = 2 * r + 1;

        Func g("g"), h("h");
    #ifdef USE_2D
        g(x, y, c, u, v) = f(x + u, y + v, c);

        RDom rXY(-r, wnd_size, -r, wnd_size, "rXY");
        h(x, y, c) = sum(g(x, y, c, rXY.x, rXY.y));

        g.compute_root().reorder(u, v, x, y, c).gpu_tile(x, y, gpu_tile_x, gpu_tile_y);

    #else
        Expr xOffset = u % wnd_size - r;
        Expr yOffset = u / wnd_size - r;
        g(x, y, c, u) = f(x + xOffset, y + yOffset, c);

        RDom rX(0, wnd_size * wnd_size, "rX");
        h(x, y, c) = sum(g(x, y, c, rX));

        g.compute_root().reorder(u, x, y, c).gpu_tile(x, y, gpu_tile_x, gpu_tile_y);
    #endif

        h.compute_root().gpu_tile(x, y, gpu_tile_x, gpu_tile_y);
        h.compile_jit(target);

        Image<float> outputImg = h.realize(128, 128, 3);
        printf("Success\n");
        std::getchar();
    }

The code works, if I reduce everything to a 1D reduction by doing some index calculations by hand  (comment the #define at the top to run this code). Surprisingly, the code also works fine if a completely remove the color dimension, even for very large realization sizes. This is not a very good solution, since it makes the code hard to read and makes it harder to experiment with schedules.

I checked the stmt output and everything looks fine there, so I don't really know where the error is on the Halide side. I'm running the current Halide version (built with llvm 3.7, cloned from their repo yesterday) on Windows 64bit. I've run the code on two different machines, one with a Nvidia gpu and one with an AMD gpu, so I guess it's not a driver issue. 

Can anyone reproduce this problem on their machine? Any ideas what it could be? I don't like posting issues where it's so unclear what goes wrong, so if anyone has a hint how I could locate the error a bit better that would also help.

Thanks for any help.

**Comment by gchauras** [comment]
You can see runtime debug output by adding ```target.set_feature(Target::Debug)```. However, I think the clue is the stmt file. For the USE_2D case, you will see
```
for (g.s0.v, -1, 3) {
    for (g.s0.u, -1, 3) {
        g[(((((( ...
```
I think the -1 is causing some index to be less than 0. The non USE_2D case has loop indices starting at 0 to 9.

This was an issue before. There was some code in GPU backends to slide all indices to positive and I vaguely remember a small discussion over one of the posts. Maybe others can comment. But in meantime you can fix your bounds in the USE_2D case so that this does not happen. Again, I *think* this is the issue.

**Comment by dvicini** [comment]
Hi,

Thanks for your reply. 

What do you mean exactly by "fix your bounds"? I just noticed that sqrt(x * y) is maybe not the smartest test function since x or y can be negative in my code. Changing this didn't affect the error though. Also changing the 2D reduction to only run over positive offsets, e.g. using RDom rXY(0, wnd_size, 0, wnd_size, "rXY"), didn't change anything.

Using the Target::Debug feature I discovered that the extent of the allocated buffer for g is not the same for the USE_2D case as for the non USE_2D case. The non USE_2D case gives the following output: (I've now set **r = 2**, so the window has size **5 x 5**)

    CL: halide_opencl_device_malloc (user_context: 0x89f3b8, buf: 0x89c4a0)
        Allocating buffer of 4915200 bytes, extents: 128x128x3x25 strides: 1x128x16384x49152 (4 bytes per element)
    clCreateBuffer -> 4915200 0x1826180
This means the code allocates a buffer of the correct size. The USE_2D case however gives:

    CL: halide_opencl_device_malloc (user_context: 0x82eeb8, buf: 0x82bfb0)
        Allocating buffer of 983040 bytes, extents: 128x128x3x5 strides: 1x128x16384x49152 (4 bytes per element)
    clCreateBuffer -> 983040 0x1a15250

The allocation size clearly misses a " x 5" at the end. I now also understand why the code works when I remove the "c" dimension. Then the allocation for the USE_2D case has the size 128x128x5x5. The problem seems to be, that Halide currently cannot properly deal with buffers of dimension > 4 on the GPU (again, the code seems to work on the CPU, or at least USE_2D and non USE_2D give the same result). The stmt output also showed the correct allocation size, which in this case did not agree with the Target::Debug output. (I assume that the output given by Target::Debug is correct)

**Comment by abadams** [comment]
Ok, that narrows it down a lot. buffer_ts can't represent dimensions > 4,
but I thought the extra dimensions were supposed to get flattened down into
the last one for cpu-gpu stuff. I think I see the bug. I'll try to add some
test coverage here.

**Comment by abadams** [comment]
(btw, buffer_t's will soon be able to support an arbitrary number of
dimensions)

**Comment by abadams** [comment]
Ok, It would have been some pretty dubious code to make this work, so I
just added an explicit error instead (instead of memory corruption and/or
crashing).

**Comment by dvicini** [comment]
Hi Andrew,

Thanks for your help. An explicit error is already an improvement I think, because these kind of bugs are quite tough to locate otherwise. I'm looking forward to see buffer_t support more dimensions. :)
