### ISSUE TITLE
Writing Exprs to std::ostream causes a bus error on arm64-based Mac

### ISSUE THREAD

**Issue by twesterhout** [halide/Halide#7442]
Hello,

I'm having trouble with the `operator<< (ostream&, const Expr&)`:

  - It keeps failing for me in [halide-haskell](https://github.com/twesterhout/halide-haskell)'s CI on OS X.
  - Today, we tried running the same thing locally on an arm64-based Mac, and it fails in both halide-haskell's tests and Halide's [tutorial 4](https://github.com/halide/Halide/blob/main/tutorial/lesson_04_debugging_2.cpp).
 
I'm fairly certain that on arm64 the crash is not related to my Haskell code, because we can reproduce it by running:

```sh
clang++ -std=c++17 lesson_04_debugging_2.cpp -lHalide
./a.out
```

the error is `Bus error: 10` and the error code is `138`.

Clang version info:
```
clang version 11.1.0
Target: aarch64-apple-darwin
Thread model: posix
InstalledDir: /nix/store/bg0jhgp01ikl5zqi9x0g8hvn0mcbn3mg-clang-11.1.0/bin
```

We used Halide 15.0.0 from nixpkgs.

I think the failures in GithHub Actions are related to this, but there the code doesn't crash and I simply get an empty string when I try to print an `Expr`...

Sorry if this is not a very coherent bug report, but I'm failing to come up with any causes of such behavior and hence don't know what else to test.

**Comment by twesterhout** [comment]
@abadams thanks for the quick reply. That's definitely a possibility. Does anything in this file https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/halide/default.nix#L27 jump at you? Perhaps a missing CMake flag that we should add.

**Comment by abadams** [comment]
I don't see anything troubling. Maybe @alexreinking will have an idea.

**Comment by twesterhout** [comment]
I believe I've found and fixed the issue. It's related to the way Halide is built on Nixpkgs. The PR is here: https://github.com/NixOS/nixpkgs/pull/224473
Nixpkgs prioritizes PRs based on 👍, so please leave one if you feel that the PR is reasonable.

**Comment by alexreinking** [comment]
Seems like the issue is downstream. Feel free to re-open if something needs to change on our end.
