### ISSUE TITLE
Tutorial Harris Corner Detection shifted by two pixels

### ISSUE THREAD

**Issue by philipzimmermann** [halide/Halide#7451]
In the **tutorial_lesson_21_auto_scheduler_generate** you give an implementation of Harris Corner Detection. The pipeline ends with the following:
`output1(x, y) = harris(x + 2, y + 2);`
Why is this `x+2` and `y+2` there? I compared it to the Harris Corner output in OpenCV and the corner responses from Halide seem to be off by 2 pixels.

**Comment by abadams** [comment]
I believe it's so that the tutorial doesn't need a boundary condition, to make things slightly simpler.

**Comment by philipzimmermann** [comment]
Actually there is a `BoundaryConditions::repeat_edge(input);`

**Comment by abadams** [comment]
Weird, the harris corner detector in apps/ doesn't have one (nor does it have the shift). Time to go diffing in the git history...

**Comment by abadams** [comment]
I see no reason for it in the history. I'll just remove it.
