### ISSUE TITLE
No binaries in the release section

### ISSUE THREAD

**Issue by carlosal1015** [halide/Halide#7465]
In the README says

> Binary tarballs
> The latest version of Halide can always be found on GitHub at https://github.com/halide/Halide/releases

> We provide binary releases for many popular platforms and architectures, including 32/64-bit x86 Windows, 64-bit macOS, and 32/64-bit x86/ARM Ubuntu Linux.

but no binaries, for example Halide-15.0.0-x86-64-linux-d7651f4b32f9dbd764f243134001f7554378d62d.tar.gz.

**Comment by carlosal1015** [comment]
For example, https://github.com/halide/Halide/releases/download/v14.0.0/Halide-14.0.0-x86-64-linux-6b9ed2afd1d6d0badf04986602c943e287d44e46.tar.gz has folder called bin, but in 15.0.0 there no exists.

It breaks this [line](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=halide-bin#n34).

**Comment by steven-johnson** [comment]
Hm, yep, the bin/ folder (containing some utilities) is indeed missing in the 15.0.0 build. 

The good news is that we are just about to do a 15.0.1 release. I'll make sure those are included there.

(Tagging @alexreinking as an FYI)
