### ISSUE TITLE
Bus error/segmentation fault aot compilation python/c++ large images

### ISSUE THREAD

**Issue by bjanssen** [halide/Halide#747]
I have a python script that generates an object and a header file with a Halide program that performs a table lookup for each output pixel. I want to use this Halide program in a C program and adopted `lessen_10` in the tutorials to do so.
The problem is that, if the output size is too large, I get either a `bus error` or a `segmentation fault`.

The crash can be reproduced by first executing the following python script
```python
#!/usr/bin/env python
# @file aot_crash.py
from halide import *
import numpy as np
from numpy.random import random_integers

if __name__ == '__main__':
    lut_np = random_integers(0, 255, [9, 3, 3]).astype(np.uint8)

    x, y = Var('x'), Var('y')
    input = ImageParam(UInt(8), 2, 'input')
    lut = Image(UInt(8), lut_np )


    lookup = Func('lookup')
    lookup[x,y] = lut[1, clamp( input[x,y], 0, 8), 0]
  
    lookup.compile_to_file("lookup", Argument("input", True, UInt(8)))
```
The "strange" indexing of `lut` (compared to `lut_np`) is due to transposition that is present between NumPy and Halide ordering.

Then compile the following C file using
`$ g++ aot_crash_run.cpp lookup.o -lpthread -DSIZE=2048 -o aot_crash_run`
and running it: `$ ./aot_crash_run`.
```C
// @file aot_crash_run.cpp
// First run
// $ python aot_crash.py
// This generates lookup.h and lookup.o
// The compile this file using
// $ g++ aot_crash_run.cpp lookup.o -lpthread -DSIZE=1025 -o aot_crash_run
#include "lookup.h"

#include <stdio.h>

int main(int argc, char **argv) {
    uint8_t input[SIZE * SIZE];
    uint8_t output[SIZE * SIZE];

    buffer_t input_buf = {0}, output_buf = {0};

    input_buf.host  = &input[0];
    output_buf.host = &output[0];


    input_buf.stride[0] = output_buf.stride[0] = 1;
    input_buf.stride[1] = output_buf.stride[1] = SIZE;

    // The extent tells us how large the image is in each dimension.
    input_buf.extent[0] = output_buf.extent[0] = SIZE;
    input_buf.extent[1] = output_buf.extent[1] = SIZE;


    input_buf.elem_size = output_buf.elem_size = 1;

    int error = lookup(&input_buf, &output_buf);

    if (error) {
        printf("Halide returned an error: %d\n", error);
        return -1;
    }

    printf("Success!\n");
    return 0;
}
```
This will sometimes result in a `bus error` if compiled with the flag `-DSIZE=2044`.
If compiled with `-DSIZE=2045` it will either crash with a `bus error` or a `segmentation fault`.
When compiled with any `SIZE` larger than 2045 `aot_crash_run` will crash with a `segementation fault`.

**Comment by zvookin** [comment]
Your stack frame is right around 8 megabytes. I expect you're running into the stack limit of your system. Move the array declarations of input and output to be globals.

**Comment by bjanssen** [comment]
@zvookin you are right, thanks! 
Moving the array declarations to the globals works fine. Alternatively one can use `ulimit` to increase the stack frame, e.g.
`$ ulimit -s 65536`

**Comment by bjanssen** [comment]
Thinking about this, why does it fill up the stack? Are the inputs not passed as pointers to data, or are internal Halide routines not inlined?
