### ISSUE TITLE
Programmatically generating a pure function

### ISSUE THREAD

**Issue by yourslab** [halide/Halide#7490]
Take 3x3 blur as an example:
```
blur_x(x, y) = (input(x, y) + input(x + 1, y) + input(x + 2, y)) / 3;
blur_y(x, y) = (blur_x(x, y) + blur_x(x, y + 1) + blur_x(x, y + 2)) / 3;
```

What is the best way to define `blur_x` and `blur_y` so that any size of blur can be supported? For example, having a 100x100 blur instead of 3x3 by modifying a single constant. For loops don't seem to work well for this purpose due to limitations in defining pure functions.

**Comment by abadams** [comment]
You use an RDom for this, e.g:

```
Param<int> radius;
RDom r(-radius, 2*radius+1);
blur(x) += input(x + r);
```

See this section in the tutorial for more details: https://halide-lang.org/tutorials/tutorial_lesson_09_update_definitions.html
