### ISSUE TITLE
3D Buffer only stores first element of Realization

### ISSUE THREAD

**Issue by Carpetfizz** [halide/Halide#7504]
I'd like to generate a simple (10x10) *red square*

```C++
Var x, y, c;
Func f;
f(x, y, c) = {cast<uint8_t>(255), cast<uint8_t>(0), cast<uint8_t>(0)};
Buffer<uint8_t> output = f.realize({10, 10, 3});
save_image(output, "/tmp/output.png");
```

But I get back only a *white square*. I'm pretty sure `output` is only taking the first element of the `Tuple` and producing a grayscale image instead of an RGB image.

I've tried the following variants to no avail :
1. Explicitly specialize `Buffer` with the number of channels
```C++
Buffer<uint8_t, 3> output = f.realize({10, 10, 3});
```

2. Drop the color channel and try to get Halide to infer everything
```C++
f(x, y) = {cast<uint8_t>(255), cast<uint8_t>(0), cast<uint8_t>(0)};
Buffer<uint8_t> output = f.realize({10, 10});
```

3. Saving a `Realization` as an image (compiler error to no surprise)
```C++
Realization r = f.realize({10, 10});
save_image(r, "/tmp/output.png");
```

Apologies if this is more of a support question than a bug, but it's certainly unintuitive behavior which I could not find documentation for.

Thanks in advance!

**Comment by abadams** [comment]
A tuple-valued Func like that is going to give you three separate RGB buffers when you realize it. The first one will be white, and the second two will be black. I think what's happening is that in each case that realization is being implicitly converted to a buffer by just taking the first element of it, giving you just the white image. I believe the bug is that the operator that casts from a Realization to a Buffer doesn't have a user_assert in it to check the size of the realization is one.

So yes there's a bug here, but the bug is that you should have gotten an error message. To make a single red buffer, you don't want a tuple-valued func, you want a scalar func that has a value that depends on 'c' in someway. E.g:
```
f(x, y, c) = mux(c, {cast<uint8_t>(255), cast<uint8_t>(0), cast<uint8_t>(0)});
```

**Comment by Carpetfizz** [comment]
Understood, thanks so much for the fast reply! I have the `mux` implementation working but tried to move away from it since `select`/`mux` are discouraged in the [Tuple lesson](https://halide-lang.org/tutorials/tutorial_lesson_13_tuples.html).

```C++
    // However this method is also inconvenient for three reasons.
    //
    // 1) Funcs are defined over an infinite domain, so users of this
    // Func can for example access color_image(x, y, -17), which is
    // not a meaningful value and is probably indicative of a bug.
    //
    // 2) It requires a select, which can impact performance if not
    // bounded and unrolled:
    // brighter.bound(c, 0, 3).unroll(c);
    //
    // 3) With this method, all values in the collection must have the
    // same type. While the above two issues are merely inconvenient,
    // this one is a hard limitation that makes it impossible to
    // express certain things in this way.
```

(1) and (3) are obviously not concerns for this exercise but I'm curious if there's a performance hit as highlighted by (2). Will Halide's default schedule know to unroll the `mux` or will it have to be explicitly done?

**Comment by abadams** [comment]
Unrolling the mux will have to be explicitly done in the schedule. The usual pattern is f.reorder(c, x, y).bound(c, 0, 3).unroll(c);

**Comment by abadams** [comment]
Reopening because the missing error message is a nasty bug.

**Comment by Carpetfizz** [comment]
Thanks - and sorry for prematurely closing. Another limitation of using the `mux` is that I can't use it with `BoundaryConditions`. Not sure if this should be its own issue though.

For example, if I wanted to draw a red square inside a black square :

```C++
Var x, y, c;
Func f, fc;
Tuple background = {cast<uint8_t>(0), cast<uint8_t>(0), cast<uint8_t>(0)};
f(x, y, c) = mux(c, {cast<uint8_t>(255), cast<uint8_t>(0), cast<uint8_t>(0)});
fc(x, y, c) = BoundaryConditions::constant_exterior(f, background, {{0, 5}, {0, 5}})(x, y, c);
Buffer<uint8_t> output = fc.realize({10, 10, 3});
save_image(output, "/tmp/output.png");
```

Error :
```
Error: Can't index into a reference to Func "repeat_edge", because it does not return a Tuple.
```

**Comment by abadams** [comment]
'background' in this case should be a scalar Expr that depends on c, not a tuple. In this case cast<uint8_t>(0) would suffice.

**Comment by Carpetfizz** [comment]
That works, thank you.
