### ISSUE TITLE
Deprecate vs Remove `stmt_html` output for Halide 16?

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#7507]
With #7421 having landed, there is really not much use for the `stmt_html` output any more.

Ordinarily I'd say we should deprecate it, but (1) it will be hard to emit useful deprecation warnings for all use cases, and (2) I don't recall seeing a single use of it inside Google for several years now -- I wouldn't be surprised if the same is true externally.

So, taking a straw poll here -- does it make more sense to just rip off the band-aid, so to speak, and remove it entirely for Halide 16?

**Comment by shoaibkamil** [comment]
I think it's ok to remove it, but we may want to alias `stmt_html` to output `stmt_viz` or at least provide a reasonable error message-- but that seems just as hard as a deprecation message.

**Comment by slomp** [comment]
One thing to consider: compared to stmt_html, how long does it take to generate? And also, how long does it take to open it in a browser?

**Comment by abadams** [comment]
I propose that to a user of the releases, it should just appear as if the html output got better. So we don't introduce any "viz" names at all (which already collide with HalideTraceViz), and just swap in the new html output and delete the old one at the same time.

**Comment by steven-johnson** [comment]
Tagging @maaz139 as his input would be welcomed here

**Comment by maaz139** [comment]
> One thing to consider: compared to stmt_html, how long does it take to generate? And also, how long does it take to open it in a browser?
The new HTML is definitely slower to load. In general, html files above ~15mb were not working well in my experiments. I think there are ways to improve the HTML performance and it would be worth doing so if people are actively using the feature and running into this issue.

Other than performance, I don't see a reason to keep the old html file around. I would advocate silently swapping the new viz.html for the old html tags as Andrew suggested.

**Comment by antonysigma** [comment]
Chiming in... As a Nvidia GPU programmer, I am in favor of the new `StmtViz` output as long as we can bring back the `gpu_threads`, `gpu_blocks` IR visualization back in Halide 10. Ever since I moved to Halide 14, all the scheduled GPU code are visualized as assembly code.

The strength of `StmtViz` tool is to compare the IR and assembly code side by side, with cross referencing. However, if the IR visualization panel dumps the assembly code like what we do in Halide 14, it kind of defeats the purpose, right? 

The figure below shows how a generic code `blurred_x` , scheduled with `gpu_theads`, is visualized in Halide 10 and Halide 14.

![image](https://user-images.githubusercontent.com/12185630/232558221-25826389-9ccc-4663-881b-1ed649d2367c.png)

**Comment by maaz139** [comment]
Thanks for the feedback Antony! I agree, StmtViz should show IR code now that we have a separate assembly tab. I'll open an issue and look into it.

**Comment by steven-johnson** [comment]
As written, this issue is fixed, closing. (I presume we'll open a new issue for @antonysigma's request)

**Comment by mcourteaux** [comment]
I want the original HTML statement file back. The new version is SUPER slow in the webbrowser.

**Comment by maaz139** [comment]
Perhaps we can add lazy rendering for the visualization / assembly tabs. This should, in theory, restore the page responsiveness and load times to previous levels until the user explicitly requests the rendering of the new tabs.

**Comment by mcourteaux** [comment]
![image](https://github.com/halide/Halide/assets/845012/f1d2f46f-8eb9-45cb-a19b-7272ca49538e)

This message stays in the lower-left corner for me for a long while. When I check the network tab, it says that all the resources are cached, so I don't know what it's doing. Parsing the javascript file?

**Comment by steven-johnson** [comment]
Out of curiosity, what browser / hardware etc are you using? (I'm not aware that anyone else involved in the review of this noticed a meaningful slowdown, so it may be something specific to your setup that we can address somehow)

**Comment by mcourteaux** [comment]
> Out of curiosity, what browser / hardware etc are you using? (I'm not aware that anyone else involved in the review of this noticed a meaningful slowdown, so it may be something specific to your setup that we can address somehow)

An 48GB memory, 8-core machine.

![image](https://github.com/halide/Halide/assets/845012/3c527eb3-16be-44bf-af4c-eb4cfc28ad29)

Running Mozilla Firefox 115.0.2

Lemme try this in Chromium real quick...
Same for Chromium: it took 12 seconds for the page to load.

Feel free to try this for yourself:
[neonraw_denoiser_f8_k7_p1-x86-64-linux-avx2-fma-profile_by_timer.stmt.html.zip](https://github.com/halide/Halide/files/12164986/neonraw_denoiser_f8_k7_p1-x86-64-linux-avx2-fma-profile_by_timer.stmt.html.zip)

**Comment by antonysigma** [comment]
> Same for Chromium: it took 12 seconds for the page to load.

@mcourteaux I am afraid the Halide team (as well as me) are not too familiar with the Javascript and ES6. Have you considered reaching out to the original author of the PR?

Chiming in... Could you please post a screenshot of the waterfall diagram representing the load times? This is what I have on my machine, rendering the same HTML you uploaded earlier:

![image](https://github.com/halide/Halide/assets/12185630/026ae89a-9e1c-4083-a6a7-b9cf48b1b9d5)

**Comment by mcourteaux** [comment]
In Chromium, I can record a profile:

![image](https://github.com/halide/Halide/assets/845012/729f044e-e31a-4d73-8d9d-0d6f409a6340)

(The waterfall for network resources is useless, it's instantly loaded. The bottleneck is indeed some script running).

The script in question is the one that starts inline at line 8898. The call stack is this very non-helpful thing...
![image](https://github.com/halide/Halide/assets/845012/7841fe83-2770-4b05-b06e-e564448c3dd5)

**Comment by mcourteaux** [comment]
Aha! I caught a very useful profile!
![image](https://github.com/halide/Halide/assets/845012/343c91e1-a5aa-4f58-8ac1-38f663743f5f)
All the time is spent in "init_tooltips" which is just waiting 100% of the time on jQuery selectors.



I'll upload it here. [Trace-20230726T110312.json.zip](https://github.com/halide/Halide/files/12170163/Trace-20230726T110312.json.zip)
Extract, and open it with Chromium in the Performance tab of the Developer Tools.

**Comment by mcourteaux** [comment]
I'll move this to a new issue and tag the right people.

**Comment by mcourteaux** [comment]
Opened #7712
