### ISSUE TITLE
Investigate Bazel for build systems

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#751]
We should investigate using Bazel (http://bazel.io/) as a replacement for Make and CMake for Halide build systems; based on experience using a similar system inside Google, it's an excellent fit for Halide and would simplify many things (especially Generator code).

(One important gating factor would be Windows support; the initial alphas of Bazel don't officially support Windows (though some success with MSYS has been reported).)

**Comment by jrk** [comment]
Neither Make nor CMake is ideal, and I trust the taste of everyone at Google on this, knowing that you've all worked with Blaze. But: I'd say our Windows support has to remain fairly first-class, which MSYS certainly is not. My take: Visual Studio project generation (a la CMake) is not important; natively using the Visual Studio toolchain to compile and link is.

**Comment by steven-johnson** [comment]
Agreed. (That's why this issue is "investigate" rather than "convert" :-) 

My assumption/hope is that Windows support in Bazel will become first-class eventually.

**Comment by steven-johnson** [comment]
An update on this one year later: Windows support is still not fully baked in Bazel, but progress is being made; it's probably a few months away (still) from being at a point where we could entertain building Halide fully with Bazel. That said, Bazel support for using binary distributions of libHalide to build AOT-compiled code is fully there for Linux and OSX hosts; I'm working on a PR for that now and opening a new issue to track it (https://github.com/halide/Halide/issues/1159)

**Comment by dsharletg** [comment]
Are we still considering bazel?

**Comment by steven-johnson** [comment]
Not really, and we actually removed the Bazel support we had in place as no one was using it. I still have the fantasy of being able to drop our CMake support and use Bazel instead, but I seem to be literally the only person who wants that, so, closing.
