### ISSUE TITLE
argmin returns value outside of the range of the function

### ISSUE THREAD

**Issue by Carpetfizz** [halide/Halide#7527]
The following code is expected to print out `0`
```C++
const RDom r(0, 0);
const Expr test = r.x * 500;
const Tuple result = argmin(test);
const Expr min = print(result[1]);
```
but instead it prints out a Mersenne prime : `2147483647`

**Comment by abadams** [comment]
Your RDom is of size zero, so it considered no input values and returned the largest possible signed integer.

**Comment by Carpetfizz** [comment]
Thanks! Good to know that it's not some uninitialized value.
