### ISSUE TITLE
PyPI Source Dist is broken

### ISSUE THREAD

**Issue by tdubose** [halide/Halide#7529]
As it says in the title, the current version of halide on PyPI-test (16.0.0) is broken for source dists.

This can be replicated on a system for which no prebuilt wheel is available (or using `-no-binary`);  I'm using macOS 13.3 and python 3.10. The error is occurring due to a CMake path-finding issue:

```
CMake Error at CMakeLists.txt:55 (find_package):
        By not providing "FindHalide.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "Halide", but
        CMake did not find one.

        Could not find a package configuration file provided by "Halide" with any
        of the following names:

          HalideConfig.cmake
          halide-config.cmake
```

Is it even possible to make this work out of the box, given the requirement for non-standard LLVM?

In any case, it would be nice at least if pip raised an error, or e.g. if source dists were disallowed entirely.

**Comment by alexreinking** [comment]
> Is it even possible to make this work out of the box, given the requirement for non-standard LLVM?

We would need to split things into three packages:

1. `halide-llvm`: the build of LLVM as-used by Halide
2. `halide-bin`: the C++ library and CMake helpers
3. `halide`: the Python bindings.

Each one depends on the previous.

(1) is the difficult part since LLVM's build is so time-consuming.

**Comment by alexreinking** [comment]
> or e.g. if source dists were disallowed entirely

In #8405 we decided against providing sdists because getting the dependencies right is too hard.

**Comment by tdubose** [comment]
@alexreinking Great news, very excited to start `pip install`-ing Halide!
