### ISSUE TITLE
Slow JIT time for compile-time sum accumulation loop

### ISSUE THREAD

**Issue by Carpetfizz** [halide/Halide#7537]
Consider the following program that generates the average image of some random noise (example attached) :

```C++
// Algorithm :
Var x, y, xo, yo, xi, yi, c;
Func f, g;
f(x, y, c) = mux(c, Tuple(0.0f, 0.0f, 0.0f));
uint32_t numSamples = 10; // x-axis of graph below
for (uint32_t i = 0; i < numSamples; i++)
    f(x, y, c) += mux(c, Tuple(random_float() * 255.0f, random_float() * 255.0f, random_float() * 255.0f));
g(x, y, c) = cast<uint8_t>(f(x, y, c) / Expr(numSamples));
// Schedule :
Target target = findGPUTarget();
auto ticJIT = std::chrono::high_resolution_clock::now();
if (target.has_gpu_feature())
{
    g.gpu_tile(x, y, xo, yo, xi, yi, 16, 16);
    g.compile_jit(target);
}
auto tocJIT = std::chrono::high_resolution_clock::now();
std::cout << "JIT time     : " << std::chrono::duration_cast<std::chrono::milliseconds>(tocJIT - ticJIT).count() << "ms" << std::endl;
auto ticRealize = std::chrono::high_resolution_clock::now(); 
Buffer<uint8_t> output = g.realize({500, 500, 3});
auto tocRealize = std::chrono::high_resolution_clock::now(); 
std::cout << "Realize time : " << std::chrono::duration_cast<std::chrono::milliseconds>(tocRealize - ticRealize).count() << "ms" << std::endl;
```

Even though the update definition is relatively simple, the time to JIT grows quadratically(?) with the the number of samples per pixel while the time to realize grows linearly.  I can understand the time to realize growing linearly since I'm doing more work per pixel but the faster growth of the JIT time is confusing. 

![Unknown-2](https://user-images.githubusercontent.com/2084896/235066513-107df542-d1be-4a3f-a7d6-d06c355b15fe.png)

Is there any way around this by using reduction domains? From my understanding the `RDom` variable needs to be used somewhere in the expression it's reducing in order for Halide to know what to generate the loop over. In this example I'm not really looping over a domain, just repeating the same calculation over and over again.

**Example Output**
![out](https://user-images.githubusercontent.com/2084896/235063581-ea0317d1-1900-40bc-be0c-fa317ce088c1.png)

**Comment by abadams** [comment]
Unfortunately the Halide compiler is indeed slower than linear, and this source code produces a large shader. In your example you're adding a large number of independent random floats. You can also achieve this with an RDom where the random float explicitly depends on the reduction variable. Personally I'd write it like this to make it clear what variables the noise depends on:

```
noise(x, y, c, z) = random_float() * 255.0f;
RDom r(0, numSamples);
f(x, y, c) += noise(x, y, c, r);
g(x, y, c) = cast<uint8_t>(f(x, y, c) / numSamples);
```

**Comment by Carpetfizz** [comment]
Thanks @abadams ! Not only did this make the time to JIT basically constant wrt `numSamples` it also made the time to realize significantly faster.
