### ISSUE TITLE
fuzz tests call ConsumeIntegralInRange() incorrectly

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#7546]
ConsumeIntegralInRange() returns a value in the range [min, max], but in several cases we call it in the form [min, max+1] (e.g. simplify.cpp:102, which should be `(0, op_count - 1)`. This causes intermittent segfaults, usually only in `-O3` mode. We should examine all the extant calls to `ConsumeIntegralInRange()` to verify/fix incorrect usage. attn @silvergasp

**Comment by silvergasp** [comment]
Ah my bad, I should have paid closer attention from the get go. I'll use/comment on the original PR #7512 to double check everything.

**Comment by steven-johnson** [comment]
as they say, there are 2 hard problems in computer science: cache invalidation, naming things, and off-by-1 errors

**Comment by silvergasp** [comment]
Haha, I'll have to borrow that joke
