### ISSUE TITLE
Halide::Tools::save_image() incorrect tag for PLANARCONFIG on 16-bit monochrome TIFF files.

### ISSUE THREAD

**Issue by philboske** [halide/Halide#7567]
I lost an inordinate amount of time trying to figure out why my relatively simple Pipeline was failing. Turns out the ```save_tiff``` implementation has a minor bug when saving 16-bit monochrome images. 

https://github.com/halide/Halide/blob/ae53d9b0346eedb675385a07c5d8faed760ba4bf/tools/halide_image_io.h#LL1889C79-L1889C99
```    tag++->assign16(284, 1, 2);                                            // PlanarConfiguration -- planar```

This should be changed to:
```    tag++->assign16(284, 1, channels == 1 ? 1 : 2);                        // PlanarConfiguration -- planar```

Not sure why this matters as https://www.awaresystems.be/imaging/tiff/tifftags/planarconfiguration.html states: 

> If SamplesPerPixel is 1, PlanarConfiguration is irrelevant, and need not be included.

Found this by reading a TIFF file with ```libtiff``` into a ```Halide::Runtime::Buffer<uint16_t>``` container, and then immediately writing that container out with ```Halide::Tools::save_image(input, "input_halide.tiff");```. Looking at the tags for my input image:

```
$ tiffinfo input_raw.tiff
TIFF Directory at offset 0x8 (8)
  Image Width: 2048 Image Length: 1536
  Resolution: 1, 1 (unitless)
  Bits/Sample: 16
  Compression Scheme: None
  Photometric Interpretation: min-is-black
  Samples/Pixel: 1
  Rows/Strip: 1536
  Planar Configuration: single image plane
  ImageDescription: {"shape": [1536, 2048]}
  Software: tifffile.py
```

Comparing to the Halide output:

```
$ tiffinfo input_halide.tiff
TIFF Directory at offset 0x8 (8)
  Image Width: 2048 Image Length: 1536 Image Depth: 1
  Resolution: 1, 1 (unitless)
  Bits/Sample: 16
  Sample Format: unsigned integer
  Compression Scheme: None
  Photometric Interpretation: min-is-black
  Samples/Pixel: 1
  Rows/Strip: 1536
  Planar Configuration: separate image planes
```

The very important and hard-to-spot difference is the **plurality** of the ```Planar Configuration``` field. Although ```Samples/Pixel``` is 1 and ```Photometric Interpretation: min-is-black```, readers were treating it as a 3-channel image.

With the proposed change:

```
$ tiffinfo input_halide_patched.tiff
TIFF Directory at offset 0x8 (8)
  Image Width: 2048 Image Length: 1536 Image Depth: 1
  Resolution: 1, 1 (unitless)
  Bits/Sample: 16
  Sample Format: unsigned integer
  Compression Scheme: None
  Photometric Interpretation: min-is-black
  Samples/Pixel: 1
  Rows/Strip: 1536
  Planar Configuration: single image plane
```

Happy to submit a PR if requested.

**Comment by abadams** [comment]
Thanks for the bug report. A PR would be much appreciated.
