### ISSUE TITLE
Failed to compile halide program on windows

### ISSUE THREAD

**Issue by Abderrahmene-KSM** [halide/Halide#7574]
I am trying to compile a basic halide code on windows11 , I am using this command (the program is in the Halide folder) :
 g++ -std=c++17  -I .\include  -L .\lib\Release -lHalide -lpthread    -o test  test.cpp

The error that I am getting is : 

c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text+0xed): undefined reference to `Halide::Internal::Introspection::get_source_location[abi:cxx11]()'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text+0x107): undefined reference to `Halide::Internal::Introspection::get_variable_name(void const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text+0xabc): undefined reference to `Halide::Internal::Introspection::test_compilation_unit(bool (*)(bool (*)(void const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)), bool (*)(void const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), void (*)())'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text+0xaf3): undefined reference to `Halide::Func::Func()'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text+0xaff): undefined reference to `Halide::Var::Var()'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text+0xb0b): undefined reference to `Halide::Var::Var()'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text+0xb58): undefined reference to `Halide::operator+(Halide::Expr, Halide::Expr)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text+0xba4): undefined reference to `Halide::FuncRef::operator=(Halide::Expr const&)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text+0xc81): undefined reference to `Halide::Func::realize(std::vector<int, std::allocator<int> >, Halide::Target const&, Halide::ParamMap const&)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZNK6Halide4FuncclIJRNS_3VarES3_EEENSt9enable_ifIXsrNS_8Internal19all_are_convertibleIS2_JDpT_EEE5valueENS_7FuncRefEE4typeEDpOS7_[_ZNK6Halide4FuncclIJRNS_3VarES3_EEENSt9enable_ifIXsrNS_8Internal19all_are_convertibleIS2_JDpT_EEE5valueENS_7FuncRefEE4typeEDpOS7_]+0xe2): undefined reference to `Halide::Func::operator()(std::vector<Halide::Var, std::allocator<Halide::Var> >) const'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZNK6Halide11RealizationcvNS_6BufferIT_XT0_EEEIiLin1EEEv[_ZNK6Halide11RealizationcvNS_6BufferIT_XT0_EEEIiLin1EEEv]+0x1d): undefined reference to `Halide::Realization::operator[](unsigned long long) const'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZNK6Halide6BufferIiLin1EE6heightIJEEEDTcldtcl7declvalIKNS_7Runtime6BufferIiLin1ELi4EEEEEL_ZNKS5_6heightEvEspcl7forwardIT_Efp_EEEDpOS7_[_ZNK6Halide6BufferIiLin1EE6heightIJEEEDTcldtcl7declvalIKNS_7Runtime6BufferIiLin1ELi4EEEEEL_ZNKS5_6heightEvEspcl7forwardIT_Efp_EEEDpOS7_]+0x52): undefined reference to `Halide::Internal::ErrorReport::ErrorReport(char const*, int, char const*, int)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZNK6Halide6BufferIiLin1EE6heightIJEEEDTcldtcl7declvalIKNS_7Runtime6BufferIiLin1ELi4EEEEEL_ZNKS5_6heightEvEspcl7forwardIT_Efp_EEEDpOS7_[_ZNK6Halide6BufferIiLin1EE6heightIJEEEDTcldtcl7declvalIKNS_7Runtime6BufferIiLin1ELi4EEEEEL_ZNKS5_6heightEvEspcl7forwardIT_Efp_EEEDpOS7_]+0x82): undefined reference to `Halide::Internal::ErrorReport::~ErrorReport()'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZNK6Halide6BufferIiLin1EE6heightIJEEEDTcldtcl7declvalIKNS_7Runtime6BufferIiLin1ELi4EEEEEL_ZNKS5_6heightEvEspcl7forwardIT_Efp_EEEDpOS7_[_ZNK6Halide6BufferIiLin1EE6heightIJEEEDTcldtcl7declvalIKNS_7Runtime6BufferIiLin1ELi4EEEEEL_ZNKS5_6heightEvEspcl7forwardIT_Efp_EEEDpOS7_]+0xab): undefined reference to `Halide::Internal::ErrorReport::~ErrorReport()'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZNK6Halide6BufferIiLin1EE5widthIJEEEDTcldtcl7declvalIKNS_7Runtime6BufferIiLin1ELi4EEEEEL_ZNKS5_5widthEvEspcl7forwardIT_Efp_EEEDpOS7_[_ZNK6Halide6BufferIiLin1EE5widthIJEEEDTcldtcl7declvalIKNS_7Runtime6BufferIiLin1ELi4EEEEEL_ZNKS5_5widthEvEspcl7forwardIT_Efp_EEEDpOS7_]+0x52): undefined reference to `Halide::Internal::ErrorReport::ErrorReport(char const*, int, char const*, int)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZNK6Halide6BufferIiLin1EE5widthIJEEEDTcldtcl7declvalIKNS_7Runtime6BufferIiLin1ELi4EEEEEL_ZNKS5_5widthEvEspcl7forwardIT_Efp_EEEDpOS7_[_ZNK6Halide6BufferIiLin1EE5widthIJEEEDTcldtcl7declvalIKNS_7Runtime6BufferIiLin1ELi4EEEEEL_ZNKS5_5widthEvEspcl7forwardIT_Efp_EEEDpOS7_]+0x82): undefined reference to `Halide::Internal::ErrorReport::~ErrorReport()'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZNK6Halide6BufferIiLin1EE5widthIJEEEDTcldtcl7declvalIKNS_7Runtime6BufferIiLin1ELi4EEEEEL_ZNKS5_5widthEvEspcl7forwardIT_Efp_EEEDpOS7_[_ZNK6Halide6BufferIiLin1EE5widthIJEEEDTcldtcl7declvalIKNS_7Runtime6BufferIiLin1ELi4EEEEEL_ZNKS5_5widthEvEspcl7forwardIT_Efp_EEEDpOS7_]+0xab): undefined reference to `Halide::Internal::ErrorReport::~ErrorReport()'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZN6Halide8Internal12IntrusivePtrINS0_13FunctionGroupEE6decrefEPS2_[_ZN6Halide8Internal12IntrusivePtrINS0_13FunctionGroupEE6decrefEPS2_]+0x1f): undefined reference to `Halide::Internal::RefCount& Halide::Internal::ref_count<Halide::Internal::FunctionGroup>(Halide::Internal::FunctionGroup const*)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZN6Halide8Internal12IntrusivePtrINS0_13FunctionGroupEE6decrefEPS2_[_ZN6Halide8Internal12IntrusivePtrINS0_13FunctionGroupEE6decrefEPS2_]+0x3c): undefined reference to `void Halide::Internal::destroy<Halide::Internal::FunctionGroup>(Halide::Internal::FunctionGroup const*)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZN6Halide8Internal12IntrusivePtrINS0_14BufferContentsEE6decrefEPS2_[_ZN6Halide8Internal12IntrusivePtrINS0_14BufferContentsEE6decrefEPS2_]+0x1f): undefined reference to `Halide::Internal::RefCount& Halide::Internal::ref_count<Halide::Internal::BufferContents>(Halide::Internal::BufferContents const*)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZN6Halide8Internal12IntrusivePtrINS0_14BufferContentsEE6decrefEPS2_[_ZN6Halide8Internal12IntrusivePtrINS0_14BufferContentsEE6decrefEPS2_]+0x3c): undefined reference to `void Halide::Internal::destroy<Halide::Internal::BufferContents>(Halide::Internal::BufferContents const*)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZN6Halide8Internal12IntrusivePtrINS0_17ParameterContentsEE6decrefEPS2_[_ZN6Halide8Internal12IntrusivePtrINS0_17ParameterContentsEE6decrefEPS2_]+0x1f): undefined reference to `Halide::Internal::RefCount& Halide::Internal::ref_count<Halide::Internal::ParameterContents>(Halide::Internal::ParameterContents const*)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZN6Halide8Internal12IntrusivePtrINS0_17ParameterContentsEE6decrefEPS2_[_ZN6Halide8Internal12IntrusivePtrINS0_17ParameterContentsEE6decrefEPS2_]+0x3c): undefined reference to `void Halide::Internal::destroy<Halide::Internal::ParameterContents>(Halide::Internal::ParameterContents const*)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZN6Halide8Internal12IntrusivePtrINS0_14BufferContentsEE6increfEPS2_[_ZN6Halide8Internal12IntrusivePtrINS0_14BufferContentsEE6increfEPS2_]+0x1f): undefined reference to `Halide::Internal::RefCount& Halide::Internal::ref_count<Halide::Internal::BufferContents>(Halide::Internal::BufferContents const*)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZN6Halide8Internal12IntrusivePtrINS0_18DefinitionContentsEE6decrefEPS2_[_ZN6Halide8Internal12IntrusivePtrINS0_18DefinitionContentsEE6decrefEPS2_]+0x1f): undefined reference to `Halide::Internal::RefCount& Halide::Internal::ref_count<Halide::Internal::DefinitionContents>(Halide::Internal::DefinitionContents const*)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZN6Halide8Internal12IntrusivePtrINS0_18DefinitionContentsEE6decrefEPS2_[_ZN6Halide8Internal12IntrusivePtrINS0_18DefinitionContentsEE6decrefEPS2_]+0x3c): undefined reference to `void Halide::Internal::destroy<Halide::Internal::DefinitionContents>(Halide::Internal::DefinitionContents const*)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZN6Halide8Internal12IntrusivePtrINS_16PipelineContentsEE6decrefEPS2_[_ZN6Halide8Internal12IntrusivePtrINS_16PipelineContentsEE6decrefEPS2_]+0x1f): undefined reference to `Halide::Internal::RefCount& Halide::Internal::ref_count<Halide::PipelineContents>(Halide::PipelineContents const*)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZN6Halide8Internal12IntrusivePtrINS_16PipelineContentsEE6decrefEPS2_[_ZN6Halide8Internal12IntrusivePtrINS_16PipelineContentsEE6decrefEPS2_]+0x3c): undefined reference to `void Halide::Internal::destroy<Halide::PipelineContents>(Halide::PipelineContents const*)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZN6Halide6BufferIiLin1EE23assert_can_convert_fromIvLin1EEEvRKNS0_IT_XT0_EEE[_ZN6Halide6BufferIiLin1EE23assert_can_convert_fromIvLin1EEEvRKNS0_IT_XT0_EEE]+0x82): undefined reference to `Halide::Internal::ErrorReport::ErrorReport(char const*, int, char const*, int)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZN6Halide6BufferIiLin1EE23assert_can_convert_fromIvLin1EEEvRKNS0_IT_XT0_EEE[_ZN6Halide6BufferIiLin1EE23assert_can_convert_fromIvLin1EEEvRKNS0_IT_XT0_EEE]+0x151): undefined reference to `Halide::type_to_c_type[abi:cxx11](Halide::Type, bool, bool)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZN6Halide6BufferIiLin1EE23assert_can_convert_fromIvLin1EEEvRKNS0_IT_XT0_EEE[_ZN6Halide6BufferIiLin1EE23assert_can_convert_fromIvLin1EEEvRKNS0_IT_XT0_EEE]+0x221): undefined reference to `Halide::Internal::ErrorReport::~ErrorReport()'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZN6Halide6BufferIiLin1EE23assert_can_convert_fromIvLin1EEEvRKNS0_IT_XT0_EEE[_ZN6Halide6BufferIiLin1EE23assert_can_convert_fromIvLin1EEEvRKNS0_IT_XT0_EEE]+0x264): undefined reference to `Halide::Internal::ErrorReport::~ErrorReport()'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZNK6Halide6BufferIvLin1EE10dimensionsIJEEEDTcldtcl7declvalIKNS_7Runtime6BufferIvLin1ELi4EEEEEL_ZNKS5_10dimensionsEvEspcl7forwardIT_Efp_EEEDpOS7_[_ZNK6Halide6BufferIvLin1EE10dimensionsIJEEEDTcldtcl7declvalIKNS_7Runtime6BufferIvLin1ELi4EEEEEL_ZNKS5_10dimensionsEvEspcl7forwardIT_Efp_EEEDpOS7_]+0x52): undefined reference to `Halide::Internal::ErrorReport::ErrorReport(char const*, int, char const*, int)'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZNK6Halide6BufferIvLin1EE10dimensionsIJEEEDTcldtcl7declvalIKNS_7Runtime6BufferIvLin1ELi4EEEEEL_ZNKS5_10dimensionsEvEspcl7forwardIT_Efp_EEEDpOS7_[_ZNK6Halide6BufferIvLin1EE10dimensionsIJEEEDTcldtcl7declvalIKNS_7Runtime6BufferIvLin1ELi4EEEEEL_ZNKS5_10dimensionsEvEspcl7forwardIT_Efp_EEEDpOS7_]+0x82): undefined reference to `Halide::Internal::ErrorReport::~ErrorReport()'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZNK6Halide6BufferIvLin1EE10dimensionsIJEEEDTcldtcl7declvalIKNS_7Runtime6BufferIvLin1ELi4EEEEEL_ZNKS5_10dimensionsEvEspcl7forwardIT_Efp_EEEDpOS7_[_ZNK6Halide6BufferIvLin1EE10dimensionsIJEEEDTcldtcl7declvalIKNS_7Runtime6BufferIvLin1ELi4EEEEEL_ZNKS5_10dimensionsEvEspcl7forwardIT_Efp_EEEDpOS7_]+0xab): undefined reference to `Halide::Internal::ErrorReport::~ErrorReport()'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\KASMI\AppData\Local\Temp\ccxttnkJ.o:test.cpp:(.text$_ZN6Halide8Internal26buffer_type_name_non_constIiEEvRSo[_ZN6Halide8Internal26buffer_type_name_non_constIiEEvRSo]+0x43): undefined reference to `Halide::type_to_c_type[abi:cxx11](Halide::Type, bool, bool)'
collect2.exe: error: ld returned 1 exit status

I will be very grateful if some one can help me

**Comment by shoaibkamil** [comment]
We no longer support using MinGW for compiling on Windows, and instead require MSVC 2019 or later.  Please see [the README](https://github.com/halide/Halide/blob/main/README.md#platform-support) for details on the supported platforms.
