### ISSUE TITLE
Simplification failure in fuzz/simplify

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#7584]
This may be hard to repro outside of Google until https://github.com/halide/Halide/pull/7566 is resolved, but Google fuzzing reported a failure in the simplifier test (ie, the Exprs don't equal each other), see below. I'm be attaching the fuzzer input file (which can be used to repro this once we are capable of building the fuzzers outside of Google.)

This one looks like a legit bug somewhere, and the Exprs below may be simple enough [no pun intended] to investigate now.

```
Running: /tmp/testcase-5126156915376128
Simplified Expr is not equal() to Original Expr!
Var a = -128
Var b = -128
Var c = -128
Var d = -128
Var e = -128
Original Expr is: (((((x2(ramp(-128, -79, 2))/x4(-1))/x4(-71)) + x4(-128)) + x4(-128)) + x4(-128))
Simplified Expr is: x4(-385)
In vector lane 1, original -> simplified:
   -386 -> -386
   -385 -> -385
```
[testcase-5126156915376128.zip](https://github.com/halide/Halide/files/11510118/testcase-5126156915376128.zip)

**Comment by abadams** [comment]
Can repro using #7566

Will take a look now.
