### ISSUE TITLE
BoundaryConditions overloads don't all work with Func

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#759]
Say you have code like

```
Func mask = ...;
Func mask_clamped;
mask_clamped(x, y) = constant_exterior(mask, 0)(x, y));
```

This may select this overload of constant_exterior:

```
template <typename T>
inline NO_INLINE Func constant_exterior(T func_like, Expr value) {
    std::vector<std::pair<Expr, Expr> > object_bounds;
    for (int i = 0; i < func_like.dimensions(); i++) {
        object_bounds.push_back(std::make_pair(Expr(func_like.min(i)), Expr(func_like.extent(i))));
    }

    return constant_exterior(Internal::func_like_to_func(func_like), value, object_bounds);
}
```

which will fail to compile, since Func has no min() or extent() methods.

**Comment by steven-johnson** [comment]
(To be clear: this may not be intended to work, but since the arguments are named "func_like", it's not unreasonable to expect Funcs to work)

**Comment by zvookin** [comment]
That does not work because a Func doesn't have any bounds. If you pass
explicit bounds, it should work.

-Z-

**Comment by steven-johnson** [comment]
Agreed; the issue here is really one of documentation / compilation error messages; the file comment says

    All functions in this namespace transform a source Func to a result Func

which isn't really true.

**Comment by dsharletg** [comment]
The documentation looks OK to me now.
