### ISSUE TITLE
Attribute 'readnone' does not apply to functions!

### ISSUE THREAD

**Issue by nicheng0019** [halide/Halide#7591]
Linux x86-64 , llvmorg version is 16.0.4, Halide version is 15.0.1, build Halide with cmake, the compilation result returned the following error:
FAILED: src/autoschedulers/adams2019/adams2019_cost_model.runtime.o /workspace/Halide-15.0.1/build/src/autoschedulers/adams2019/adams2019_cost_model.runtime.o 
cd /workspace/Halide-15.0.1/build/src/autoschedulers/adams2019 && /workspace/Halide-15.0.1/build/src/autoschedulers/adams2019/_Halide_gengen -r adams2019_cost_model.runtime -o . -e object target=x86-64-linux,x86-64-linux
Attribute 'readnone' does not apply to functions!
ptr @paddusbx16
Attribute 'readnone' does not apply to functions!
ptr @padduswx8
Attribute 'readnone' does not apply to functions!
ptr @psubusbx16
Attribute 'readnone' does not apply to functions!
ptr @psubuswx8
Attribute 'readnone' does not apply to functions!
ptr @packsswbx16
Attribute 'readnone' does not apply to functions!
ptr @packuswbx16
Attribute 'readnone' does not apply to functions!
ptr @packssdwx8
Attribute 'readnone' does not apply to functions!
ptr @wmul_pmaddwd_sse2
Attribute 'readnone' does not apply to functions!
ptr @llvm.x86.sse2.pmadd.wd
Attribute 'readnone' does not apply to functions!
ptr @abs_f32x4
Attribute 'readnone' does not apply to functions!
ptr @llvm.sadd.sat.v16i8
Attribute 'readnone' does not apply to functions!
ptr @llvm.sadd.sat.v8i8
Attribute 'readnone' does not apply to functions!
ptr @llvm.ssub.sat.v16i8
Attribute 'readnone' does not apply to functions!
ptr @llvm.ssub.sat.v8i8
Attribute 'readnone' does not apply to functions!
ptr @llvm.sadd.sat.v8i16
Attribute 'readnone' does not apply to functions!
ptr @llvm.ssub.sat.v8i16
Attribute 'readnone' does not apply to functions!
ptr @llvm.x86.sse2.psad.bw
Attribute 'readnone' does not apply to functions!
ptr @llvm.x86.sse2.pavg.b
Attribute 'readnone' does not apply to functions!
ptr @llvm.x86.sse2.pavg.w
Attribute 'readnone' does not apply to functions!
ptr @llvm.x86.sse2.pmulh.w
Attribute 'readnone' does not apply to functions!
ptr @llvm.x86.sse2.pmulhu.w
Unhandled exception: Internal Error at /workspace/Halide-15.0.1/src/CodeGen_LLVM.cpp:580 triggered by user code at : Condition failed: !verifyModule(*module, &llvm::errs()): 

Comment out the line fn->addFnAttr(llvm::Attribute::ReadNone); in the function CodeGen_X86::init_module in the file CodeGen_X86.cpp, the building succeed!

**Comment by abadams** [comment]
You should match the Halide version to the llvm version. There's no Halide 16 release yet, so to use llvm 16 you should use Halide's main branch. Halide 15 only supports llvm 15 and a few earlier versions.

**Comment by nicheng0019** [comment]
> You should match the Halide version to the llvm version. There's no Halide 16 release yet, so to use llvm 16 you should use Halide's main branch. Halide 15 only supports llvm 15 and a few earlier versions.

Ok, thanks!
