### ISSUE TITLE
Already defined symbols when linking more than one generated static library

### ISSUE THREAD

**Issue by MotivaCG** [halide/Halide#7592]
If you use compile_to_static_library to create static libraries when you try to import some of them you'll get several linking issues since symbols are duplicated like 

> default.halide_default_malloc already defined in xxxxxx

Is there any chance to bypass this? 

Regards, Víctor

**Comment by MotivaCG** [comment]
Btw I know that I can generate some of them with no_runtime feature, but then some of the platform specific runtimes are not linked like 

> 
> 1>local_laplacian_cuda.lib(local_laplacian_cuda.lib.obj) : error LNK2001: unresolved external symbol halide_cuda_initialize_kernels
> 1>local_laplacian_cuda.lib(local_laplacian_cuda.lib.obj) : error LNK2001: unresolved external symbol halide_cuda_finalize_kernels
> 1>local_laplacian_cuda.lib(local_laplacian_cuda.lib.obj) : error LNK2001: unresolved external symbol halide_cuda_device_interface
> 1>local_laplacian_cuda.lib(local_laplacian_cuda.lib.obj) : error LNK2001: unresolved external symbol halide_cuda_run
> 1>local_laplacian_opencl.lib(local_laplacian_opencl.lib.obj) : error LNK2001: unresolved external symbol halide_opencl_initialize_kernels
> 1>local_laplacian_opencl.lib(local_laplacian_opencl.lib.obj) : error LNK2001: unresolved external symbol halide_opencl_device_interface
> 1>local_laplacian_opencl.lib(local_laplacian_opencl.lib.obj) : error LNK2001: unresolved external symbol halide_opencl_run
> 1>local_laplacian_opencl.lib(local_laplacian_opencl.lib.obj) : error LNK2001: unresolved external symbol halide_opencl_finalize_kernels

(I've added runtimes only to local_laplacian_cpu.lib library)

**Comment by abadams** [comment]
Try generating a runtime (with the -r flag to any generator binary) with target host-cuda-opencl or similar to enable those features.

**Comment by MotivaCG** [comment]
Do you mean executing the .exe (windows) right? or can that be done in code too?

**Comment by MotivaCG** [comment]
For future readers you can add the other symbols to other library, in my case I've added all them to the CPU one:

`
		std::vector <Target::Feature> fets;
		if (disableRuntimeLibs)
		{
			fets.push_back(Target::Feature::NoRuntime);
		}
		else
		{
			fets.push_back(Target::Feature::CUDA);
			fets.push_back(Target::Feature::OpenCL);
		}`
