### ISSUE TITLE
Our version of PyBind11 is incompatible with Python 3.11

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#7617]
We have been using PyBind11 2.6.2 for a long time, I think mainly because it's preinstalled on various Ubuntu versions. Unfortunately, it's incompatible with the headers for Python 3.11 (see https://github.com/pybind/pybind11/discussions/4333), and they aren't going to do any fixes for an old version, so we really need to upgrade (this has rendered Halide unbuildable on my Linux box as it has been force-upgraded to 3.11).

**Comment by alexreinking** [comment]
This was fixed
