### ISSUE TITLE
compile_to_simplified_lowered_stmt should be simpler

### ISSUE THREAD

**Issue by abadams** [halide/Halide#763]
Currently it's not enough simpler to be useful. I propose emitting the loop structure after injecting realizations but before the rest of lowering. E.g:

f(x, y) = ...
g(x, y) = f(x, y) + ...

g.compute_root().vectorize(x, 8).parallel(y);
f.compute_at(g, x);

Would emit:

parallel g.y:
  for g.x.x:
    for f.y:
      for f.x:
        f[f.x, f.y] = ...
    vector for g.x.v0:
      let g.x = g.x.x*8 + g.x.v0
      g[g.x, g.y] = f[g.x, g.y] + ...

So you get the splits, loops, and realizations, but you don't see any bounds of things at all. It would be just enough to illustrate what your schedule is doing.

**Comment by jrk** [comment]
👍

**Comment by abadams** [comment]
See #766 for a prototype solution
