### ISSUE TITLE
Vulkan failures

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#7642]
Some recent tests are failing with e.g.

```
HL_TARGET=host-vulkan-vk_int8-vk_int16-vk_int64-vk_float16-vk_float64-vk_v13
HL_JIT_TARGET=host-vulkan-vk_int8-vk_int16-vk_int64-vk_float16-vk_float64-vk_v13
#CTEST_RESOURCE_GROUP_COUNT=
/home/halidenightly/build_bot/worker/halide-testbranch-main-llvm16-x86-64-linux-cmake/halide-build/test/correctness/correctness_gpu_data_flows
Error: VulkanBlockAllocator: Unable to allocate region! Invalid device memory handle!
Vulkan: Failed to allocate device memory!
Required regular expression not found. Regex=[Success!]
```

See 
https://buildbot.halide-lang.org/master/#/builders/58/builds/10/steps/36/logs/correctness_gpu_data_flows

**Comment by derek-gerstmann** [comment]
Strange … these seemed to pass on the release/16.x branch

**Comment by derek-gerstmann** [comment]
Looks like a sporadic failure on linux-worker-4 … we’ve had plenty of successful builds, so I’m not sure what’s triggering this. I’ll investigate further.

**Comment by derek-gerstmann** [comment]
Fixed with latest commits. Unable to reproduce.
