### ISSUE TITLE
Why aren't halide_set_custom_print, halide_set_custom_error (etc) in HalideRuntime.h?

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#769]
It would be useful to be make these public hooks, so that (e.g.) filters loaded and run via dlOpen() could have their output hooked. (As it is, they can be intercepted but aren't officially public.)

**Comment by zvookin** [comment]
Well, the idea is that outside of JIT, one is supposed to replace the
functions via linkage. If we start down this path, I think we need to look
at the entire design again. Lots has changed and JIT is a bit more sensible
now, but there are still a couple things I couldn't get to work because
user_context is not guaranteed to be provided to a callback. (It can be
NULL.) Moreover, whether a hook function is replacing the callback in a
certain scope or fo the entire process is tricky.

**Comment by steven-johnson** [comment]
This is a good point. 

My first reaction was "hook ALL the runtime functions!" via a function-pointer table; that would mean extra overhead for all runtime calls, of course (not sure how significant that would be). (It would also be a nontrivial breaking change for the runtime, too, of course.)

**Comment by abadams** [comment]
Yeah, the linkage option doesn't always work. I'd support putting these
functions in HalideRuntime.h. For precedent, see halide_set_trace_file and
halide_set_gpu_device. Users can either call it, or they can override the
matching getter.

Regarding scope, if this matters for an app, users can globally set a
custom whatever with something that dispatches off of their user context.

**Comment by zvookin** [comment]
Well, the idea is you could use link time replacement to raplce the whole
runtime with one that lets you do this if you want...

I think there is a far better design available here than the one we have
now, but it isn't clear to me it is just a matter of moving hook setters
into HalideRuntime.h. E.g. the hooks probably ought to be callback objects,
not function pointers, at which point a lot of the user_context issues
would go away. And the hook setters are effectively modifying global state,
unless we start using thread locals. We need to at least carefully document
how they interact with prior calls to Halide and how they interact with the
JIT, etc.

-Z-

**Comment by zvookin** [comment]
I believe the requested functionality is now in HalideRuntime.h, hence closing.
