### ISSUE TITLE
apps/ directory should put build products (+ temp) in one place

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#776]
Minor but annoying issue: building the apps/ directory leaves a lot of detritus in the subdirectories, some of which is marked with .gitignore and some not. We could update the .gitignore to handle all of these, but ideally we could move all of the build products somewhere (e.g. subdir of toplevel build/ folder).

**Comment by alexreinking** [comment]
Is this still relevant? The CMake build is out-of-tree by default.
