### ISSUE TITLE
how to get the value of a scalar output of a halide function

### ISSUE THREAD

**Issue by ygsaber** [halide/Halide#7774]
**Generator code:**

namespace {
class HalideMin : public Halide::Generator<HalideMin> {
    public:
	Input<Buffer<uint16_t>> input{"input", 2};
	Output<uint16_t> min_output{"min_output"};

	void generate() {
		Var x("x"), y("y");
		Expr height = input.height();
		Expr width = input.width();
		RDom r(0, input.width(), 0, input.height());
		min_output() = minimum(input(r.x, r.y));
    }
}
}  // namespace
HALIDE_REGISTER_GENERATOR(HalideMin, halide_min)

**Runtime code:**

    const int width = 2048;
    const int height = 1536; 

    Halide::Runtime::Buffer<uint16_t, 2> input(width, height);

    for (int y = 0; y < input.height(); y++) {
        for (int x = 0; x < input.width(); x++) {
            input(x, y) = 110;
        }
    }

     Halide::Runtime::Buffer<uint16_t, 0> min_output;
     halide_min(input, min_output);
     std::cout << "halide_min min_output: " << min_output() << std::endl;

I have tried min_output, min_output(), min_output(0), min_output.data(), *min_output.data(), *(min_output.data()), it seems only min_output.data() can print 0, but the correct value should be 110, while other forms give errors. I wonder how I can get the value of the scalar output of the halide function? Thanks!

**Comment by abadams** [comment]
That buffer is unallocated. To allocate a scalar buffer, do:

```
auto min_output = Halide::Runtime::Buffer<uint16_t, 0>::make_scalar();
```

**Comment by ygsaber** [comment]
Thank you! That works!
