### ISSUE TITLE
The metal runtime swallows some errors

### ISSUE THREAD

**Issue by abadams** [halide/Halide#7780]
The metal runtime discovers some classes of error via the command_buffer_completed_handler, but this doesn't surface the error to, e.g. the next halide_device_sync call.

**Comment by abadams** [comment]
(Discovered in #7770)

**Comment by shoaibkamil** [comment]
Some helpful info: https://stackoverflow.com/questions/17813870/how-does-a-block-capture-the-variables-outside-of-its-enclosing-scope

**Comment by abadams** [comment]
This can cause schedules that produce incorrect output instead of throwing an error, so I'm adding the bug tag.

**Comment by shoaibkamil** [comment]
Fixed by #8240
