### ISSUE TITLE
Wrong results when calculating mean value of an image using RDom

### ISSUE THREAD

**Issue by ygsaber** [halide/Halide#7784]
**Generator code:**

class HalideMean : public Halide::Generator<HalideMean> {
public:
	Input<Buffer<uint16>> input{"input", 2};
	Output<float> mean{"mean"};
	Output<float> sum{"sum"};

	void generate() {
		RDom r(0, input.width(), 0, input.height());
		sum() = (float)0.f;
		sum() += cast<float>(input(r.x, r.y));
		mean() = cast<float>(sum() / (input.width() * input.height()));
	}
};
}  // namespace
HALIDE_REGISTER_GENERATOR(HalideMean, halide_mean)

**test code:**

    const int width = 1000;
    const int height = 1000;
    Halide::Runtime::Buffer<uint16_t, 2> input_u16(width, height);
    auto mean_output = Halide::Runtime::Buffer<float, 0>::make_scalar();
    auto sum_output = Halide::Runtime::Buffer<float, 0>::make_scalar();

    for (int y = 0; y < height; y++) {
        for (int x = 0; x < width; x++) {
            input_u16(x, y) = 111;
        }
    }

    double t;
    t = Halide::Tools::benchmark(1, 1, [&]() {
        halide_mean_uint16(input_u16, mean_output, sum_output);
        mean_output.device_sync();
        sum_output.device_sync();
    });
        
        std::cout << "halide_mean_uint16" << " running time: " << t << std::endl;
        std::cout << "halide_mean_uint16" << " mean_output: " << mean_output() << std::endl;
        std::cout << "halide_mean_uint16" << " sum_output: " << sum_output() << std::endl;

**results:**
halide_mean_uint16 running time: 0.000954202
halide_mean_uint16 mean_output: 111.849
halide_mean_uint16 sum_output: 1.11849e+08
The results are not correct, mean output should be 111.

if I use width = 100, and height = 100, then the results are good:
halide_mean_uint16 running time: 3.35527e-05
halide_mean_uint16 mean_output: 111
halide_mean_uint16 sum_output: 1.11e+06

if I use width = 10000, and height = 10000, then the results are more far away from 111:
halide_mean_uint16 running time: 0.0943431
halide_mean_uint16 mean_output: 21.4748
halide_mean_uint16 sum_output: 2.14748e+09

I wonder why this happens and what is wrong here? Thanks.

**Comment by abadams** [comment]
This is a property of floating point math, and you can reproduce it in C. As the running sum gets larger and larger, adding 111 becomes more and more approximate, until it eventually does nothing at all, because it's smaller than the smallest possible increment to the running sum. So after a bit, you're effectively adding zero instead of 111. This makes the final mean smaller and smaller the larger the input is.

You can avoid this sort of problem by factoring the sum into multiple stages, e.g. by computing per-row sums and then summing them.

**Comment by ygsaber** [comment]
Good point! Thank you very much! I have solved the problem.
