### ISSUE TITLE
Missing check in split call that could lead to invalid schedules

### ISSUE THREAD

**Issue by TH3CHARLie** [halide/Halide#7827]
Found by fuzzer, consider the below example:
```cpp
#include "Halide.h"
#include <iostream>
using namespace Halide;

int main(int argc, char **argv) {
    Var x("x"), y("y");
    RDom r(-2, 5, -2, 5);
    Func f, g;
    f(x, y) = x + y;
    g(x, y) = 0;
    g(x, y) += f(x + r.x, y + r.y);
    RVar ryo("ryo"), ryi("ryi");
    g.update(0).split(r.y, ryo, ryi, 2, TailStrategy::RoundUp);
    return 0;
}
```
Halide disallows splitting RVar with RoundUp tail strategy so this example would throw an error
```
    if (exact) {
        user_assert(tail == TailStrategy::GuardWithIf || tail == TailStrategy::Predicate)
            << "When splitting Var " << old_name
            << " the tail strategy must be GuardWithIf, Predicate, or Auto. "
            << "Anything else may change the meaning of the algorithm\n";
    }
```
But I found you can bypass this check, i.e. splitting an RVar with this strategy, just do:
```
Var ryo("ryo"), ryi("ryi");
g.update(0).split(Var(r.y.name()), ryo, ryi, 2, TailStrategy::RoundUp);
```
This will end up splitting an RVar dim with RoundUp, leading to undefined results (possibly rewrite useful regions). The current implementation relies only on the Var's name matching, so this kind of intentional skip can happen.

**Comment by abadams** [comment]
We should be asserting that VarOrRVar objects passed to split have the same type (i.e. Var or RVar) as their entry in the dims list somewhere around Func.cpp::1131
