### ISSUE TITLE
Generator with F16C target emits emulation code for float16_t->float casts

### ISSUE THREAD

**Issue by AngryLoki** [halide/Halide#7836]
Checked with Halide-16.0.0. Generator target: `target=x86-64-linux-avx-avx2-f16c-fma-sse41` raises the following warning for float16 ->f32 conversion:
```
Warning: In function my_gen, (b)float16 type operation is emulated, which is likely to slow down the performance. If your target supports native (b)float16 operations, it could be improved by adding Target feature to enable it.
```

Generator code:
```
#include "Halide.h"

using namespace Halide;

class HalfFloatMatMul : public Halide::Generator<HalfFloatMatMul> {
public:
    Input<Buffer<float16_t, 2>> A{"A"};
    Input<Buffer<float16_t, 2>> B{"B"};

    Output<Buffer<float, 2>> output{"C"};

    void generate() {
        RDom r(0, A.dim(0).extent(), "r");
    	matmul(x, y) += cast<float>(A(r, y)) * cast<float>(B(r, x));
        output(x, y) = matmul(x, y);
    }

    void schedule() {
        if (using_autoscheduler()) {
            A.set_estimates({{0, 1024}, {0, 1024}});
            B.set_estimates({{0, 1024}, {0, 1024}});
            output.set_estimates({{0, 1024}, {0, 1024}});
        } else {
            matmul.compute_root();
        }
    }

private:
    Func matmul;
    Var x{"x"}, y{"y"};
};

HALIDE_REGISTER_GENERATOR(HalfFloatMatMul, my_gen)
```

I expect to see `vcvtph2ps` (`_mm256_cvtph_ps`) in generated assembly. Is it possible to change anything to emit it?

**Comment by abadams** [comment]
To be clear, you expect to see vcvtph2ps in the output, and you *don't*? I'm trying to figure out if the problem is that we're not generating vcvtph2ps when we should be, or if we're throwing a warning when we shouldn't be.

**Comment by AngryLoki** [comment]
I apologize for the confusing explanation. From previous pull-requests, I was under the impression that Halide recognizes F16C target (well, it allows to specify it as a codegen-feature). After that, I would assume that enabling this feature allows the generation of (F16C)[https://en.wikipedia.org/wiki/F16C] code. I tried to look in the Halide code, maybe somehow it is possible to vectorize it with (intrinsics)[https://halide-lang.org/docs/_i_r_operator_8h.html], but have not found one. Overall, my expectation was to achieve this conversion with normal `cast()` call. The `(b)float16 type operation is emulated` warning just provided me a notification about this (but I would still notice it since the generated code is too slow compared to handwritten code).

Therefore this is probably a feature request, not a bug report.
