### ISSUE TITLE
segfault on rfactoring an RVar produced by fusing a Var with an RVar

### ISSUE THREAD

**Issue by abadams** [halide/Halide#7854]
This crashes:
```
#include "Halide.h"

using namespace Halide;

int main(int argc, char **argv) {
    Func f;
    RDom r(0, 100);
    Var x, y;
    f(x, y) = 0;
    f(x, y) += r;

    RVar yr;
    Var z;
    f.update().fuse(y, r, yr).rfactor(yr, z);

    return 0;
}

```

I believe the issue is that the rfactor code has to handle splits, but doesn't correctly handle fusing a Var with an RVar to produce an RVar. Also it doesn't do enough validation. This should be an internal assert failure rather than a crash.

**Comment by abadams** [comment]
The fix is to forbid rfactoring over an RVar if that RVar has had a pure var fused into it

**Comment by alexreinking** [comment]
Why doesn't this just set `yr=r` and `z=y`?

**Comment by abadams** [comment]
That sounds more like a split than an rfactor. rfactor would be replacing the fusion of y and r with a single new pure Var z in an intermediate Func, and moving the reduction over yr (still fused) to the wrapper Func.

The problem with that is you need bounds for yr to do that transformation, which don't exist yet where rfactor is implemented because the bounds of yr depend on the bounds of y which are yet to be inferred, and even when inferred it places a nasty constraint on what the bounds of y can be.
