### ISSUE TITLE
"Can't index into a reference to Func "f", because it does not return a Tuple" for `Func` returning a Tuple with a single `Expr`

### ISSUE THREAD

**Issue by Carpetfizz** [halide/Halide#7860]
**Example**
```c++
Func f("f"), g("g");
Var x("x");
f(x) = Tuple(0.0f);
g(x) = f(x)[0];
```

**Error**
```
Can't index into a reference to Func "f", because it does not return a Tuple.
```

**Expectation**
A function that returns a `Tuple` with a single `Expr` should be indexed into using `[0]` to get the first element.

**Comment by abadams** [comment]
Halide currently considers single-element Tuples to just be Exprs, not Tuples, when you use them in a Func definition.
