### ISSUE TITLE
ld: error: undefined symbol: Halide::Internal::Introspection::get_source_location()

### ISSUE THREAD

**Issue by fjrdev** [halide/Halide#7861]
Im trying to work on the DSP of my Android device with Halide in Android Studio. Therefore I have pushed `libhalide_hexagon_host.so` and `libHalide.so` from the Qualcomm Hexagon SDK into the jniLibs folder of my application and linked the libraries in CMakeLists. I also took the HALIDE_Tools directory from the Hexagon SDK and included Halide.h to my native cpp file. Building the Application throws the following error:

```
ld: error: undefined symbol: Halide::Internal::Introspection::get_source_location() referenced by Halide.h:25153
```

**Comment by fjrdev** [comment]
@abadams thanks for the clarification! Is there a way of compiling Halide code in the app (arm64-v8a) without cross-compiling? I could not find a tutorial/documentation.

**Comment by abadams** [comment]
Do you want to use Halide as a JIT compiler inside an Android app? Android devices typically forbid JIT compilers, so I'm not sure if anyone has tried that. All the Android usage of Halide I'm aware of uses it as an AOT cross compiler.
