### ISSUE TITLE
Pass input buffers to Halide pipeline compiled to LLVM Module?

### ISSUE THREAD

**Issue by sumeetgadagkar** [halide/Halide#7863]
Let's say I create a pipeline as follows : 
```c++
    using Halide::Var;
    Var x;

    // Create input
    Buffer<int> testInput(4);
    for (int i = 0; i < 4; i++) {
        testInput(i) = i + 1;
    }

    // This class represents one stage in a Halide pipeline, and is
    // the unit by which things are scheduled
    Func f;

    // Here we define that the first stage should square each element of the input
    // Output should be 1, 4, 9, 16
    f(x) = testInput(x) * testInput(x);

    // Set the range estimate for the indexing variable x to min 0 and max 4
    f.set_estimate(x, 0, 4);
    auto pipeline = Pipeline(f);
```

I then compile this pipeline to LLVM Module as follows :
```c++
    Buffer<int> testInput(4);
    std::vector<Argument> inputs;
    inputs.push_back(testInput);

    // Get a target
    auto target = get_jit_target_from_environment();
    target.set_feature(Target::NoRuntime);

    pipeline.compile_to_llvm_assembly(LLVMIRFile, {inputs}, "testFcn1", target);
```

I then call this LLVM module in C++ code using LLVM JIT compiler. How can I pass a different input to this pipeline (different from testInput in the code above)?

**Comment by abadams** [comment]
The llvm assembly you produced should have a signature that takes a halide_buffer_t * for the input. You should be able to pass any buffer you like via that argument.

**Comment by sumeetgadagkar** [comment]
@abadams The function signature generated for the code above is : 
```c++
define i32 @testFcn1(%struct.halide_buffer_t* noalias nocapture readnone %b1.buffer, %struct.halide_buffer_t* noalias %f0.buffer) local_unnamed_addr #1
```
Assuming that the first argument `%b1.buffer` is the input buffer. It is not used inside the function body at all. 

Also inside the `testFcn1_argv` function the call to my function `testFcn1` is generated as :
```c++
%4 = tail call i32 @testFcn1(%struct.halide_buffer_t* undef, %struct.halide_buffer_t* %3) #7
```

Am I doing something wrong with the LLVM generation? Thanks!

**Comment by abadams** [comment]
It looks like you made a totally new Buffer to create the Argument vector instead of using the Buffer that was actually used in the pipeline. You should pass the Buffer that is actually referenced in the pipeline. If you don't it gets baked into the compiled code as a LUT.

**Comment by sumeetgadagkar** [comment]
Thank you! That fixed it!
