### ISSUE TITLE
Clarification needed on constructing a `Realization` from existing `Buffer`s

### ISSUE THREAD

**Issue by Carpetfizz** [halide/Halide#7870]
The [Realization](https://halide-lang.org/docs/class_halide_1_1_realization.html) docs say the following :

> A [Realization](https://halide-lang.org/docs/class_halide_1_1_realization.html) is a vector of references to existing [Buffer](https://halide-lang.org/docs/class_halide_1_1_buffer.html) objects.

But the code appears to be copying the `std::vector<Buffer<void>>` into `images` :

https://github.com/halide/Halide/blob/a24071c8304f41002f5f504fb9a4942e8a60abe6/src/Realization.cpp#L30-L33

My guess as to what's happening is that copying a `Buffer` is "shallow" in the sense that the underlying data contained in its `RuntimeBuffer` does not get copied/moved, and copying a `Buffer` is basically like copying a pointer.

Some clarification on the ownership of `Buffer`s by a `Realization` would be much appreciated so we can know if it's safe or unsafe to access existing `Buffer`s after they've been used to construct a `Realization`.

**Comment by abadams** [comment]
Yes, Buffer objects are named shared pointers to actual image data.

Well... A Halide::Buffer is a named shared reference to a Halide::Runtime::Buffer, and a Halide::Runtime::Buffer (if it's an owning one) is a shared reference to actual image data.

What this means in practice is that if you copy a Buffer object with the regular C++ copy constructor, the new Buffer refers to both the same pixel values and the same metadata (e.g. sizes and device/host dirty flags).

If you copy a Runtime::Buffer in the same way, the copy refers to the same pixel data, but has its own metadata.

It's not the cleanest setup imaginable, but were a lot of constraints on the design.

**Comment by Carpetfizz** [comment]
Thanks for the clarifications, that makes sense!
