### ISSUE TITLE
GPU code shouldn't call halide_copy_to_device for output buffers

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#792]
It appears that the GLSL code calls halide_copy_to_device() for all buffers; this is necessary for input buffers, but not for output buffers (which should only need to ensure that the device field references a valid texture, not that the texture's contents matches host). (Might be true for all GPU backends, but GLSL is the only one I've tried.)

**Comment by aam** [comment]
copy_to_device calls seem to be triggered by host_dirty flag. How is host_dirty flag set in the case you are looking at?

**Comment by steven-johnson** [comment]
host_dirty and dev_dirty are both zero in the case I see.

**Comment by abestephensg** [comment]
If the host_dirty flag is not set, the GL runtime won't copy any data--there shouldn't be a corresponding call to halide_opengl_copy_to_device.

If Halide can determine that the entire buffer is written to by the filter, we could eliminate the call and ignore the flag, even if it is set.

**Comment by steven-johnson** [comment]
Yeah, I was confused here -- I didn't realize that halide_copy_to_device() could allocate-but-not-copy... which it can, meaning it's got a very misleading name :-/
