### ISSUE TITLE
halide_type_of uint64_t template specialization incompatibility with MAC (Apple Macintosh)

### ISSUE THREAD

**Issue by ivangarcia44** [halide/Halide#7921]
Halide has a uint64_t specialization for halide_type_of, but the definition of uint64_t is "unsigned long" in Linux and "unsigned long long" in MAC. And Halide does not have a specialization for the latter, which is an incompatibility in MAC. Can this be fixed?

Try this code to reproduce the compilation error:

```
#include <iostream>

#include "HalideRuntime.h"

typedef unsigned long linux_uint64_t;
typedef unsigned long long mac_uint64_t;

template <class T>
halide_type_t getHalideType(const T* in) {
    return halide_type_of<T>();
}

int main() {
    // In Linux uint64_t is defined as "unsigned long". This compiles:
    linux_uint64_t arr1[10];
    auto ht = getHalideType(arr1);
    std::cout << (int)(ht.bits) << "\n";

    // The MAC uint64_t is defined as "unsigned long long". This errors out
    // because there is no specialization available: "required from
    // ‘halide_type_t getHalideType(const T*) [with T = long long unsigned int]’ ...
    // HalideRuntime.h:2035:40: error: static assertion failed: Expected a pointer
    // type here
    // 2035 | static_assert(check_is_pointer<T>::value, "Expected a pointer type here");
    //
    // Note that it falls under the pointer type specialization because no base type
    // match was found.    
    mac_uint64_t arr2[10];
    auto ht1 = getHalideType(arr2);
    std::cout << (int)(ht1.bits) << "\n";
    
    return 0;
}

```

**Comment by abadams** [comment]
Why not just use uint64_t directly instead of rolling your own? On mac clang defines it as the compiler built-in type __UINT64_TYPE__, not in terms of unsigned long. If you really want to roll your own, e.g. because you're dealing with legacy code that does, you should be able to add a template instantiation of halide_type_of, but I don't recommend it.

**Comment by ivangarcia44** [comment]
Thank you for the quick reply. Sorry for the delay, I had to discuss this with my group. Our software does have an option to generate uint64_t, but we can't enforce this on all users. We will use C++ reinterpret_cast in our Halide use case to go from "unsigned long" to "uint64_t" since both have 64 bits. Thanks!
