### ISSUE TITLE
Could not parse built-in bitcode file

### ISSUE THREAD

**Issue by johningve** [halide/Halide#7936]
Hi, I am facing this error when trying to compile Halide function with `compile_to`:

```
 Internal Error at Halide/src/LLVM_Runtime_Linker.cpp:20 triggered by user code at : Could not parse built-in bitcode file halide_buffer_t_64 llvm error is llvm.bitcode:1
```

Any ideas what might have gone wrong here?

**Comment by abadams** [comment]
This means that the built-in runtime, which is a set of llvm bitcode modules stored as static data inside libHalide, is somehow corrupt, or doesn't match the llvm version currently in use (e.g. it was compiled for an older version).

I recommend just doing a full clean and rebuild of libHalide (if you built it yourself) or downloading it from scratch if you downloaded a precompiled binary.

**Comment by johningve** [comment]
Got it thanks! I was experimenting with cross compiling Halide and probably messed up something. I then realized that I don't need to cross compile after all, so I didn't investigate further.
