### ISSUE TITLE
Question: GPU kernel deduplication?

### ISSUE THREAD

**Issue by antonysigma** [halide/Halide#7944]
I have a gradient descent imaging algorithm having M identical steps of pipeline `auto f(Func) -> Func`, currently scheduled as M individual GPU kernels. Currently (Halide v16.0) the GPU steps "unrolls" and generate M identical GPU kernels.

```c++
// File 1: generator.cpp
Input<Buffer<float>> input;
std::array<Func, M> x;
Output<Buffer<float>> output;
Output<float> mean_square_error;

// generate
x[0] = input;
for(auto i = 1; i < M; i++) {
    x[i] = f(x[i - 1]);
}
output = x.back();

RDom r(...);
mean_square_error() = pow( input[M - 1](r.x, r.y, r.z) - input[M - 2](r.x, r.y, r.z), 2);

// schedule
for(auto i = 1; i < M; i++) {
    x[i].compute_root()
      // GPU schedules here
      ;
}
mean_square_error.compute_root()
      .rfactor(...);
      // GPU scalar reduction schedules here.

///////////////
// File 2: runtime.cpp
float mean_squared_error;
size_t N; 
for(auto k = 1; k < iter_max; k += M) {
    generated_pipeline(input, output, wrap_scalar(&mean_squared_error));
    if (mean_squared_error < threshold) { N = k; break; }
    std::swap(input, output);
}
```

Question: how do I modify Halide codebase to deduplicate the M identical kernels into one? Or, is there a Halide technique without modifying the Halide codebase?

The kernel deduplication feature enables algorithm explorations in two ways: 
1. benchmarking and fine tuning of the GPU kernels with `nsys` or `halide-profile` features;
2. analyzing the tradeoff between the number of `mean_square_sum` compute (i.e. ratio N/M), and the number of total iterations (N).

**Comment by antonysigma** [comment]
I am thinking about modifying the following lines of `add_kernel`, but I am not sure if it is the right place to start:
https://github.com/halide/Halide/blob/f25af7f4879b9e1d999be9b0229371337fc3a2a8/src/OffloadGPULoops.cpp#L183-L187

**Comment by mcourteaux** [comment]
This whole loop of `M` iterations is typically something I wouldn't write in a Halide pipeline. The step you repeat `M` times would be the pipeline instead, and you'd call it from C++ instead.

I haven't tried this, but perhaps, if you write this as an `RDom` reduction, Halide might produce less code?

**Comment by antonysigma** [comment]
Adding more context to the question:

> Quoting @jrk in Stackoverflow, dated Nov, 2015 https://stackoverflow.com/a/33472074/706334
> You're right to note that it isn't obvious how to express a dynamically-terminating (while) loop—they are not possible to express in pure Halide right now! This may change in the (indefinite, long-term) future but adding these would make looping Halide programs Turing-complete; without them, we can always analyze the bounds of your loops, but we them, we'd face the halting problem.

This ticket is about "unrolling" the dynamically-terminating (while) loop by M times in the Halide pipeline. And, how to modify the Halide compiler to deduplicate GPU kernels implicitly. The feature is driven by the wish to explore the trade offs between (M) iterations between termination criterion checking (an expensive scalar reduction op), and (N) the total number of iterations before termination.

**Comment by antonysigma** [comment]
> The step you repeat `M` times would be the pipeline instead, and you'd call it from C++ instead.

Thanks @mcourteaux . Do you mean by the following pseudo-code in `my_runtime.cpp` ? Sound like I need to handle the scope of `output_prev_iter` buffer manually.

```c++
# new_runtime.cpp
float mean_squared_error;
size_t N; 
input.set_host_dirty();
for(auto k = 1; k < iter_max; k += M) {
    for(auto i : iota(M)) {
        /* Generated pipeline 1 */
        generated_single_iteration_pipeline(input, output_prev_iter, output);
    }

    auto mse_wrapped = wrap_scalar(&mean_squared_error);

    /* Generated pipeline 2 */
    generated_check_mse_pipeline(output_prev_iter, output, mse_wrapped);

    mse_wrapped.copy_to_host();
    if (mean_squared_error < threshold) { N = k; break; }
    std::swap(input, output);
}
output.copy_to_host();
// return {output, mean_square_error};
```

**Comment by mcourteaux** [comment]
I don't understand why you would want that. The reduction op that is expensive can be a separate Halide pipeline. Then you explore the tradeoff between M and N with two for loops in C++.

```cpp
for (int it = 0; it < max_iter; it += M) {
   for (int inner = 0; inner < M; ++inner) {
      iteration_step(buffers, ...);
   }
   reduction_step(buffers, mse);
   if (mse <= threshold) { break; }
}
```

**Comment by mcourteaux** [comment]
Ah yes. You just added a comment. I didn't see it before posting my last clarification.

**Comment by antonysigma** [comment]
Mcourteaux indicated an [XY problem](https://xyproblem.info/) in the original question. Closing.
