### ISSUE TITLE
GuardWithIf is really slow on small-extent vectorized loops on architectures without predication

### ISSUE THREAD

**Issue by abadams** [halide/Halide#7947]
Two possible new tail strategies that could help:

RoundUpAndBlend, which would be like GuardWithIf but it would use a select instead of an if, so if GuardWithIf does something equivalent to:

f(x) = if x < extent then g(x) else dontcare

RoundUpAndBlend would do:

f(x) = select(x < extent, g(x), f(x))

I.e. it loads the vector it would store to, modifies some of the lanes, and then stores the result. This would be a race condition if there's an outer parallel loop in that dimension, so we'd have to check for that.

ShiftInwardsAndBlend would be similar, but shifting inwards instead of rounding up, so that the overall allocation bounds aren't expanded if the extent is at least one vector. It would be really useful for vectorizing pure vars in update definitions touching inputs and outputs when you expect the extent to be small.

Specifically, I want to use this schedule:

```
output.update().specialize(output.width() < vec);
output.update().vectorize(x, vec, TailStrategy::ShiftInwardsAndBlend);
```

**Comment by abadams** [comment]
A snag: The ShiftInwards variant requires loading a vector that partially overlaps the last vector stored, which stalls. The RoundUp variant works great.

**Comment by vksnk** [comment]
> A snag: The ShiftInwards variant requires loading a vector that partially overlaps the last vector stored, which stalls. The RoundUp variant works great.

Maybe it's possible to keep the previous vector around and shuffle (it sounds like it's going to be pretty complicated though)?

**Comment by abadams** [comment]
Yeah I considered that, but it seemed too hard. I found that it's fairly easy to cover the stall by just unrolling another dimension and moving it inwards.

**Comment by abadams** [comment]
This might provide a mechanism to solve #7819. Both new tail strategies are safe for sliding window, because they won't clobber values outside of the region computed.
