### ISSUE TITLE
Hiding LLVM symbols to avoid clashes with other libraries

### ISSUE THREAD

**Issue by jrk** [halide/Halide#796]
I'm helping @willcrichton integrate Terra and Halide into the same binary, and it's proving to be a mess. libTerra is built in much the same way as libHalide. Linking them into the same binary, not surprisingly, results in craziness with multiple initialization of LLVM globals, etc. Overcoming this requires custom-building/linking Halide, Terra, or both, to use a common LLVM. This same problem also came up when using the Intel OpenCL runtime libraries on Linux (where sharing LLVM libs isn't even an option, since it's not available as source).

Looking into this a bit, it seems it _should_ be possible to prune what symbols we export from `libHalide.*`. Specifically, this can be done using linker scripts on both [Linux](http://stackoverflow.com/questions/435352/limiting-visibility-of-symbols-when-linking-shared-libraries) and [OS X](https://developer.apple.com/library/mac/technotes/tn2185/_index.html#//apple_ref/doc/uid/DTS10004200-CH1-SUBSECTION5). Playing around, there are some caveats to trivial adoption (at least in the OS X case it seems you can't apply this to a preexisting .a to produce a new, export-pruned .a; you _can_ do it when linking `libHalide.a` into `libHalide.so`, which seemed to work smoothly, and you can probably also do it when assembling `libHalide.a` from individual objects), but it seems likely doable.

I did a really quick pass at grabbing what to export from a binary:

```
nm libHalide.a  | grep ' T ' | grep -vi llvm | sed 's/.* T _/_/' > symbols.txt
```

This gives exactly the format expected by `-exported_symbols_list` on OS X, but it would require an extra rewrite to stuff into a GNU `version-script`.

Thoughts?

/cc @zdevito

**Comment by abadams** [comment]
The simplest custom-building option is setting the environment variable
USE_LLVM_SHARED_LIB. It'll just make a .a with the Halide object files
only. In fact if that environment variable isn't set the Makefile goes to a
lot of extra trouble to unarchive llvm into object files, then ar them all
together with the Halide ones.

Being clever about symbol visibility is probably going to break the build
on annoying platforms like arm-linux. That part of the build is very
brittle - I've only found one path that works reliably everywhere. That
said, given that we do construct a directory of llvm object files to
include in the archive, we could probably do an objcopy on them or
something to change symbol visibility. But do object files in the same
archive resolve symbols against each other in some more intimate way that
object files from other linked archives? I'm not sure how that would work.

**Comment by willcrichton** [comment]
Ah, I didn't know about that option, it worked like a charm. Thanks @abadams!

**Comment by dsharletg** [comment]
This issue sounds resolved.
