### ISSUE TITLE
PR #7930 causes mismatch to the golden

### ISSUE THREAD

**Issue by vksnk** [halide/Halide#7960]
One of the tests at Google failed check against the golden data after #7930. It looks like this PR should change the output, so opening this to investigate. Let me know if the change is expected, in this case we'll just update goldens.

**Comment by abadams** [comment]
Does it change the golden with strict_float on?

Differences in loop partitioning can different floating point optimizations in tails vs steady state, which could change a golden that depends on float math. In the past I've seen this mess with demosaicking algorithms that make floating point comparisons to decide in which direction to interpolate.

**Comment by vksnk** [comment]
We usually have strict_float on, but let me check.

**Comment by steven-johnson** [comment]
This was an unstable schedule for floating point, I fixed it downstream
