### ISSUE TITLE
LLVM `TargetMachine ::registerPassBuilderCallbacks` interface is changed

### ISSUE THREAD

**Issue by hokein** [halide/Halide#8017]
A recent LLVM upstream patch [ffb1f20e0d8d](https://github.com/llvm/llvm-project/commit/ffb1f20e0d8db5cd2c2a0fa2db9951e97f215b92) changed `TargetMachine ::registerPassBuilderCallbacks` interface. We need to adapt this change for Halide (e.g. https://github.com/halide/Halide/blob/main/src/CodeGen_LLVM.cpp#L1247).

**Comment by steven-johnson** [comment]
See https://github.com/halide/Halide/pull/8018

**Comment by hokein** [comment]
Thanks!
