### ISSUE TITLE
Wasm testing has been broken for a few weeks

### ISSUE THREAD

**Issue by abadams** [halide/Halide#8037]
It looks like some dependencies are missing:

https://buildbot.halide-lang.org/master/#/builders/19

**Comment by steven-johnson** [comment]
WTF, how is it this hasn't been noticed?

**Comment by steven-johnson** [comment]
Ok, so this is happening only on mac-x86-worker-3 (AFAICT), but it *does* have the right Node installed and `which node` returns a path to it, so I don't know why CMake is failing to find it. Assigning this to @alexreinking for now for his mad CMake skillz

**Comment by steven-johnson** [comment]
> Ok, so this is happening only on mac-x86-worker-3 (AFAICT), but it _does_ have the right Node installed and `which node` returns a path to it, so I don't know why CMake is failing to find it. Assigning this to @alexreinking for now for his mad CMake skillz

whoops, ignore for now, had the wrong window open :-/
