### ISSUE TITLE
The version check in serialization is not checked at the right place

### ISSUE THREAD

**Issue by abadams** [halide/Halide#8101]
We need to check the version number *first*, before trying to serialize or deserialize anything. Currently if you pass a serialization file of the wrong version it can just crash before the version check.

**Comment by abadams** [comment]
There should be a correctness test that tests loading serialization files of the wrong version and makes sure the right error is generated

**Comment by abadams** [comment]
Did this ever get fixed?

**Comment by TH3CHARLie** [comment]
I believe so, I recently did something similar to the issue's description and triggered the proper check and error messages
