### ISSUE TITLE
Fuzzing Failures

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#8165]
Several fuzzer failures found by internal Google fuzzing tools. Opening them all here in a single issue. (Not clear if they all have the same cause or not.)
[testcases.zip](https://github.com/halide/Halide/files/14795956/testcases.zip)

**Comment by abadams** [comment]
For which test?

**Comment by steven-johnson** [comment]
whoops, sorry. 4744184440881152 is for fuzz-simplify; the others are fuzz-cse.

**Comment by abadams** [comment]
Something different must be happening inside google, because none of these fail for me on main
