### ISSUE TITLE
`debug` shouldn't print entry/exit for parallel closures (but does)

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#8184]
What it says on the tin -- it makes the `debug` feature near-useless if you have any parallelism in your schedule. Maybe it's useful for some corner cases but I haven't yet encountered such a case. Can we default it to off for these?

**Comment by abadams** [comment]
I think this change was unintended. It crept in when we move lowering of parallel closures into lowering instead of codegen. I agree it should be fixed.

**Comment by abadams** [comment]
Except the code looks like it's really just annotating the main LoweredFunc. I'll investigate.

**Comment by abadams** [comment]
ok, it looks like this was actually an intentional change, because code for it was added to LowerParallelTasks.cpp
