### ISSUE TITLE
CheckUnsafePromises inserts checks which get lifted out of `select()`, invalidating what it actually checks.

### ISSUE THREAD

**Issue by mcourteaux** [halide/Halide#8302]
As a follow-up to #8301, I started using `unsafe_promise_clamped` to circumvent the bounds-inference issue. Just to double check what I was doing, I enabled `check_unsafe_promises`, which caused my promises to be checked outside the `select()` which should represent an if-then-else.

So conceptually, what I'm talking about is this:

```cpp
    Buffer<float, 3> bufA({10, 10, 25}, "bufA");
    Buffer<float, 3> bufB({10, 10, 25}, "bufB");
    Buffer<float, 2> bufC({10, 10}, "bufC");
    Var x("x"), y("y"), i("i");

    Func concat("concat");
    concat(x, y, i) = select(
        i < 25, bufA(x, y, unsafe_promise_clamped(i, 0, 24)),
        i < 50, bufB(x, y, unsafe_promise_clamped(i - 25, 0, 24)),
                bufC(x, y));
```

Doesn't work with `check_unsafe_promises` as both checks end up being next to the `select()` statement, instead of being inside it.

**Comment by abadams** [comment]
Again, this is because select evaluates both sides, so your unsafe_promise_clamped calls don't actually hold

**Comment by abadams** [comment]
If you want an if statement, the only current way to get one is RDom::where

**Comment by mcourteaux** [comment]
So if I understand well, this unsafe_promise_clamped is actually really unsafe because it behaves like a blend rather than an if-then-else?

**Comment by abadams** [comment]
That's right.

**Comment by mcourteaux** [comment]
Okay, thanks. RTFM indeed. :stuck_out_tongue:
