### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by tamarnav** [halide/Halide#831]
Hi,
I have downloaded the latest halide release for linux as well as the llvm binar release an set the LLVM_CONFIG and Clang.
When trying to compile the tutorials I get the following errors:
![image](https://cloud.githubusercontent.com/assets/5797280/8318625/40edb8f8-19bb-11e5-815e-4edde9f9b8d8.png)

Any idea what am I missing?

**Comment by abadams** [comment]
What gcc version are you using? The precompiled binaries should work for
4.8 and 4.9. Otherwise you might need to build Halide yourself from source.

**Comment by tamarnav** [comment]
Thanks for the quick reply!
I am using 4.7.2.

**Comment by abadams** [comment]
Unfortunately you'll need to either update gcc or compile Halide from
source.

- Andrew

**Comment by tamarnav** [comment]
I have upgraded to gcc 4.9.2 and still getting errors:
![image](https://cloud.githubusercontent.com/assets/5797280/8417316/911a2b3c-1e60-11e5-8d95-79fc2006acfc.png)

Any idea?

**Comment by abadams** [comment]
Damn. Maybe you're accidentally using a downloaded gcc 4.8 release of
Halide? If not, at this point I'd just try to compile Halide from source.
Running make should work. There's also a cmakefile.

**Comment by tamarnav** [comment]
I am using the downloaded version configured by my company so I rely on IT (maybe I shouldn't...).
I have tried to compile halide but I get:
 "version 'GLIBC_2.14' not found (required by llvm_config)..."
so I guess it is something in my environment which is not set up, not related to halide.
If you have any idea, please let me know, I am kind of lost...
