### ISSUE TITLE
Output on failure on the build bots?

### ISSUE THREAD

**Issue by mcourteaux** [halide/Halide#8332]
From `ctest --help`:
```
  --output-on-failure          = Output anything outputted by the test
                                 program if the test should fail.
```

This would be very useful I think. Right now we are clueless as to what/why it failed.

**Comment by alexreinking** [comment]
We already capture the output `ctest --output-on-failure`

https://github.com/halide/build_bot/blob/22a4473a7c9113ca0b6f074f8292128d2976cc6f/master/custom_steps.py#L168

See the code that captures it here:

https://github.com/halide/build_bot/blob/22a4473a7c9113ca0b6f074f8292128d2976cc6f/master/custom_steps.py#L154

**Comment by mcourteaux** [comment]
Oh, oops. Thanks for pointing that out.

 >  Right now we are clueless as to what/why it failed.

I guess _I_ was clueless...
