### ISSUE TITLE
Error message "Cannot interleave native vectors of type float64x32" issued by Adams2019

### ISSUE THREAD

**Issue by jxl1080** [halide/Halide#8349]
When I ran my generator with Adams2019, I got the following error message. It doesn't happen when I don't use Adams2019. I don't really understand what it tells me and what I should do:
Unhandled exception: Internal Error at /home/halidenightly/build_bot/worker/halide-nightly-main-llvm19-x86-64-linux-cmake/halide-source/src/HexagonOptimize.cpp:46 Cannot interleave native vectors of type float64x32

Below is my Halide code:

#include "Halide.h"
#include <stdio.h>
using namespace Halide;
class mMatmul_matmul_out1_fcn_halide_generator : public Halide::Generator <mMatmul_matmul_out1_fcn_halide_generator> {

    public:
        Input<Buffer<double>> A1_in{"A1_in", 2};
        Input<Buffer<double>> B1_in{"B1_in", 2};
        Output<Buffer<double>> matmul_out1_fcn{"matmul_out1_fcn", 2};

        void generate() {
            RDom r(0, 62);
            matmul_out1_func(d1, d2) = sum(A1_in(d1, r) * B1_in(r, d2));
            matmul_out1_fcn(d1, d2) = matmul_out1_func(d1, d2);
        }

        void schedule() {
        // Schedule is determined by autoscheduler. Need to set estimate on buffer
            if(using_autoscheduler()) {
                A1_in.dim(1).set_estimate(0, 62);
                A1_in.dim(0).set_estimate(0, 62);
                B1_in.dim(1).set_estimate(0, 62);
                B1_in.dim(0).set_estimate(0, 62);
                matmul_out1_fcn.set_estimate(d1, 0, 62).set_estimate(d2, 0, 62);
            }  else {
                // Default schedule
            }
        }

    private:
        Var d1{"d1"};
        Var d2{"d2"};
        Func matmul_out1_func{"matmul_out1_func"};
};
HALIDE_REGISTER_GENERATOR(mMatmul_matmul_out1_fcn_halide_generator, mMatmul_matmul_out1_fcn_halide_gen)

I used binary 'Halide-18.0.0-x86-64-linux-b741d9c5b2705c45fd7c8462eb0b4bfa35a3e6d8.tar.gz' downloaded from: https://buildbot.halide-lang.org/

My command for compiling the Halide Genertor Class is:
$ g++ mMatmul_matmul_out1_fcn_halide.cpp -std=c++17 ....../Halide-18.0.0-x86-64-linux/share/Halide/tools/GenGen.cpp -L ....../Halide-18.0.0-x86-64-linux/lib -lHalide -I ....../Halide-18.0.0-x86-64-linux/include -o mMatmul_matmul_out1_fcn_halide

My command for running generator with Adams2019 is:
$ export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:....../Halide-18.0.0-x86-64-linux/lib
$ ./mMatmul_matmul_out1_fcn_halide -f myPipeline -g mMatmul_matmul_out1_fcn_halide_gen -e h,o target=hexagon-32-noos-hvx-no_runtime autoscheduler.parallelism=2 autoscheduler=Adams2019 -p ....../Halide-18.0.0-x86-64-linux/lib/libautoschedule_adams2019.so -o ./

**Comment by abadams** [comment]
That's an error from the hexagon backend. Adams2019 is designed for processors where you can vectorize any type. It looks like the hexagon backend as it stands refuses to codegen double vectors for that target.

**Comment by jxl1080** [comment]
> That's an error from the hexagon backend. Adams2019 is designed for processors where you can vectorize any type. It looks like the hexagon backend as it stands refuses to codegen double vectors for that target.

Thank you Andrew!
