### ISSUE TITLE
`test/integration/CMakeLists.txt` shouldn't consider `bsl` for `expect_shared`?

### ISSUE THREAD

**Issue by LebedevRI** [halide/Halide#8354]
So i'm finally looking into adding at least some autopkgtests to debian halide package,
and while expectedly, all integration tests that look for/expect `static` halide are failing,
i'm suspicious of the `check_builds_jit_BUILD_SHARED_LIBS_NO` test.
It doesn't actually fail with the `Halide `static` libraries were requested but not found.`
the other tests do, but passes successfully.

I'm wondering if the following change makes sense upstream?
```diff
diff --git a/test/integration/CMakeLists.txt b/test/integration/CMakeLists.txt
index 600b1d765..645b20451 100644
--- a/test/integration/CMakeLists.txt
+++ b/test/integration/CMakeLists.txt
@@ -17,20 +17,16 @@ foreach (bsl IN ITEMS "" "-DBUILD_SHARED_LIBS=NO" "-DBUILD_SHARED_LIBS=YES")
             if (comp MATCHES "shared")
                 set(expect_shared TRUE)
             elseif (comp MATCHES "static")
                 set(expect_shared FALSE)
             elseif (hsl MATCHES "YES")
                 set(expect_shared TRUE)
             elseif (hsl MATCHES "NO")
                 set(expect_shared FALSE)
-            elseif (bsl MATCHES "YES")
-                set(expect_shared TRUE)
-            elseif (bsl MATCHES "NO")
-                set(expect_shared FALSE)
             else ()
                 set(expect_shared TRUE)
             endif ()
 
             set(test_name "${bsl} ${hsl} ${comp}")
             string(REPLACE "-D" "" test_name "${test_name}")
             string(STRIP "${test_name}" test_name)
             string(MAKE_C_IDENTIFIER "jit_${test_name}" test_name)

```

**Comment by alexreinking** [comment]
It sounds like you're not building static Halide?

The test assumes you have both static and shared installed to the same prefix, and `BUILD_SHARED_LIBS` is treated by the package as merely a _hint_ rather than a binding requirement (that's what `Halide_SHARED_LIBS` is for), so it won't produce a failure.

You can skip these tests by passing `-E BUILD_SHARED_LIBS` to `ctest`.

I'm open to a patch that improves the test, but I don't want to just delete those lines.

**Comment by LebedevRI** [comment]
> It sounds like you're not building static Halide?

Yes.

If this doesn't seem worth the effort, please just close the issue :)

**Comment by alexreinking** [comment]
Sounds good! As long as you have a workaround 🙂
