### ISSUE TITLE
Homebrew not fails to provide suitable package for Mac with M1 chips

### ISSUE THREAD

**Issue by CambridgeZ** [halide/Halide#8424]
My Mac is with M1, but when I use homebrew to get the package, I always get the package for x86_64. We need support for apple M1 users

**Comment by alexreinking** [comment]
We do not control the Homebrew package. Please open an issue with the Homebrew maintainers, here: https://github.com/Homebrew/homebrew-core/issues

The recipe file is located here: https://github.com/Homebrew/homebrew-core/blob/master/Formula/h/halide.rb
