### ISSUE TITLE
Tutorial 22 README Mistake

### ISSUE THREAD

**Issue by borsakv** [halide/Halide#8437]
In "tutorial/lesson_22_jit_performance.cpp", the README at the top of the file contains a mistake:
![image](https://github.com/user-attachments/assets/39a14f09-125c-4b6d-bedc-4b1a0e3abbd4)

The last line should read:
// LD_LIBRARY_PATH=<path/to/libHalide.so> ./lesson_22

**Comment by abadams** [comment]
Thanks, will fix.
