### ISSUE TITLE
Index with select

### ISSUE THREAD

**Issue by soufianekhiat** [halide/Halide#8499]
Do we have a way to have conditionnal on argument of a func.
Illustraction of a toy example usecase:
```cpp
Func unary{"unary" };
std::vector< Expr > args = { /* ... */ };
bool is_scalar = /* ... */:
OperationType op = /* ... */; // An enum Cos, Sin, Max
Expr x = input( args );
unary( select( is_scalar, {}, args ) ) = mux( ( int )op, { cos( x ), sin( x ), maximum( dom, input ) } );
```
Expected generation:
```cpp
if ( is_scalar )
{
    float max_value = -FLT_MAX;
    for ( int k = 0; k < input_size; ++k )
       max_value = max( max_value, input_buffer[ k ] );
    unary_buffer[ 0 ] = max_value;
}
else
{
    for ( int k = 0; k < input_size; ++k )
       if ( op == 0 )
          unary_buffer[ k ] = cos( input_buffer[ k ] );
      else
          unary_buffer[ k ] = sin( input_buffer[ k ] );
    }  
}
```
I would be possible to do that if we have a "null" placeholder for arguments. Like that instead of having
```cpp
args = { _1 }
```
I could have:
```cpp
args = { select( is_scalar, _null, _0 ) };
```

Is that possible in theory/practice? Or conceptually it's not possible in Halide design?

**Comment by abadams** [comment]
Unfortunately no, a Func must have a fixed dimensionality known at compile time. You can approximate it by taking an upper bound of all the dimensionalities you want and just use zeros in the calls for the dimensions you don't want.
