### ISSUE TITLE
Python Halide bindings fail to import: ModuleNotFoundError: No module named 'halide'

### ISSUE THREAD

**Issue by chenrui333** [halide/Halide#8519]
👋 trying to build the latest release, but run into some regression test failure. The error log is as below:

<details>
<summary>error regression test failure log</summary>

```
  ==> python3.13 lesson_01_basics.py
  Traceback (most recent call last):
    File "/private/tmp/halide-test-20241217-47676-qvoyah/lesson_01_basics.py", line 11, in <module>
      import halide as hl
  ModuleNotFoundError: No module named 'halide'
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/12380413422/job/34556855710?pr=201454
relates to Homebrew/homebrew-core#201454

---

might be related to this change, https://github.com/halide/Halide/pull/8405

cc @alexreinking

**Comment by alexreinking** [comment]
How can I see the CMake configure log or run your build script locally?

**Comment by alexreinking** [comment]
@chenrui333 -- I think I found the problem. I left a review with suggested changes in https://github.com/Homebrew/homebrew-core/pull/201454

**Comment by chenrui333** [comment]
💯
