### ISSUE TITLE
Tutorials should cover Generator

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#852]
There doesn't appear to be any discussion of examples of Generator in our tutorials; we should (at least) add a tutorial section covering it, and/or consider modifying some of the existing tutorial stages to use Generator.

**Comment by delcypher** [comment]
One of the tutorials does discuss using generators (do we mean exactly the same thing here?). This is lesson 10

https://github.com/halide/Halide/blob/master/tutorial/lesson_10_aot_compilation_generate.cpp
https://github.com/halide/Halide/blob/master/tutorial/lesson_10_aot_compilation_run.cpp

I have some CMake changes coming soon that will make building this tutorial automatic

**Comment by steven-johnson** [comment]
No, we don't mean the same thing; it discusses AOT compilation, but not using the Halide::Generator class to encapsulate a Halide pipeline.

**Comment by delcypher** [comment]
@steven-johnson Ah ok. I always thought of the binary that generates the object file and header file as being "the generator" but I see what you mean now. Yes there should be a tutorial that covers using ``Halide::Generator``.

**Comment by abadams** [comment]
My current thinking is that the next three tutorials are generators, constraints, and then specialize. Each makes the next easier to discuss.
