### ISSUE TITLE
`_Halide_install_pkgdeps()` is broken

### ISSUE THREAD

**Issue by LebedevRI** [halide/Halide#8521]
The actual installation directory root is prefixed by [`${DEST_DIR}`](https://cmake.org/cmake/help/latest/envvar/DESTDIR.html),
and `_Halide_install_pkgdeps()` does not take it into account.
I'm not quite sure yet how to unbreak this,
and until then, can't package v19 for debian.

**Comment by alexreinking** [comment]
Does this patch work?

```patch
diff --git a/cmake/HalidePackageConfigHelpers.cmake b/cmake/HalidePackageConfigHelpers.cmake
index 4efe5ebf8..efdacba24 100644
--- a/cmake/HalidePackageConfigHelpers.cmake
+++ b/cmake/HalidePackageConfigHelpers.cmake
@@ -80,7 +80,7 @@ function(_Halide_install_pkgdeps)
     set(depFile "${CMAKE_CURRENT_BINARY_DIR}/${ARG_FILE_NAME}")
 
     _Halide_install_code(
-        "file(READ \"\${CMAKE_INSTALL_PREFIX}/${ARG_DESTINATION}/${ARG_EXPORT_FILE}\" target_cmake)"
+        "file(READ \"\$ENV{DESTDIR}\${CMAKE_INSTALL_PREFIX}/${ARG_DESTINATION}/${ARG_EXPORT_FILE}\" target_cmake)"
         "file(WRITE \"${depFile}.in\" \"\")"
     )
 
@@ -104,4 +104,4 @@ function(_Halide_install_pkgdeps)
         DESTINATION "${ARG_DESTINATION}"
         COMPONENT "${ARG_COMPONENT}"
     )
-endfunction()
\ No newline at end of file
+endfunction()
```

**Comment by alexreinking** [comment]
In the meantime, I'm not sure how you're using `DESTDIR`. Is there some reason you can't just set `CMAKE_INSTALL_PREFIX` to whatever you've set `DESTDIR` to? When invoking `cmake --install build`, you can set the `--prefix` so you don't even have to reconfigure / rebuild.

**Comment by LebedevRI** [comment]
> Does this patch work?

That was the obvious solution that looked too good to be true.
I don't know if this works in general:
* What happens if `DESTDIR` isn't slash-terminated?
* What happens if `CMAKE_INSTALL_PREFIX` is relative?

> In the meantime, I'm not sure how you're using `DESTDIR`. Is there some reason you can't just set `CMAKE_INSTALL_PREFIX` to whatever you've set `DESTDIR` to? When invoking `cmake --install build`, you can set the `--prefix` so you don't even have to reconfigure / rebuild.

`DESTDIR` is meant to relocate the entire install prefix, without actually changing or recording what said prefix is.
This is basic *nix packaging magic, i'm not doing that, packaging system does,
it is working as intended and will not be changed.

**Comment by LebedevRI** [comment]
Ok, looking through CMake repo searching for `DESTDIR` suggests that said patch should be fine, LG.
Thank you!

**Comment by alexreinking** [comment]
> Ok, looking through CMake repo searching for `DESTDIR` suggests that said patch should be fine, LG.

That's how I figured out the fix 🙂
