### ISSUE TITLE
Different linking behavior for LLVM between the CMake and Makefile build system

### ISSUE THREAD

**Issue by delcypher** [halide/Halide#857]
My recent attempts to get a TravisCI build working for Halide has revealed differences between the way the CMake and Makefile build systems uses LLVM. Most notably when using CMake the linker seems to be requiring more memory because the TravisCI build would fail to build the tests due the linker being killed.

So far I have observed the following differences
- `InitialModules` is a separate library in the CMake build system but in the Makefile system it is embedded. The CMake build system should be taught to build the `InitialModules` into `libHalide` and it should **not** be separate.
- It appears that the Makefile build system actually extracts the objects inside the LLVM static libraries and embeds them into its own library. This is **not good** from a linux distribution packaging perspective but there are some advantages to doing this. The CMake build system should be taught an new option (`EMBED_LLVM`) that is available when doing a static library build of Halide that mimics what the Makefile build system does. I don't think we can do this under windows.

**Comment by abadams** [comment]
USE_LLVM_SHARED_LIB controls this for the Makefile. Probably should name
the cmake option the same thing.

I think maybe the cmake build already does this. On linux nm shows all of
llvm inside of libHalide.so, and on Windows dependency walker claims no
dependency on llvm for any of the tests, and Halide.dll is far too big to
only contain our own code.
