### ISSUE TITLE
Decouple running of tests from the Makefile build system.

### ISSUE THREAD

**Issue by delcypher** [halide/Halide#858]
Currently the CMake build system builds tests but it does not run them (**not very useful**). The Makefile build system builds and runs tests at the same time.

I'd like to propose we remove the logic that runs tests out of the Makefile build system and instead use a portable method for running these tests that works for both build systems and on **all** the platforms we support. What I'd like is to have the build systems build all the tests but then have them invoke an external python script to run all the tests once they have been built.

For the python script I have two different suggestions:
- Use `llvm-lit`. This tool is available is available from PyPi as `lit` (`pip install lit`) and is a well tested tool used by LLVM. The only difficulty here is that we will need to figure out how to get it to run our tests. If we were using GTest for our tests then we wouldn't need to do anything because it already has in-built support for GTest but because we are not it will require some work to add support for our tests.
- Roll our own python script to run our tests.

I'd prefer to try the first option and if that fails then roll our own script.

Both of these suggestions would allow running a subset of tests by specifying the tests that need to be run on the command line.

This would add a dependence on Python for running tests but I really don't think that is a big deal. Python runs on most platforms.

**Comment by abadams** [comment]
Adding dependencies just for a refactor seems bad. Python doesn't typically
exist on Windows. The current solution is a powershell script on windows
and a bash script on linux/os x. (test/scripts/*).

**Comment by delcypher** [comment]
> Adding dependencies just for a refactor seems bad.

I'm proposing more than a refactor. I'm proposing that the testing is unified across platforms and build systems. There is no way to do this without introducing a dependency on something that works on all platforms.

> Python doesn't typically exist on Windows.

Yes python doesn't exist but it's easy to install and also you can't build LLVM without it!

> The current solution is a powershell script on windows
and a bash script on linux/os x. (test/scripts/*).

Sure but it would be much better to just have a python script do this.

- Only one thing to maintain
- Can potentially run much faster by running tests in parallel.

**Comment by abadams** [comment]
The makefile runs the tests in parallel: make -j32 run_tests. The powershell script runs all the tests on windows. While this could unify some code, I don't see that this would add new functionality. This is why I call it a refactor.

**Comment by delcypher** [comment]
@abadams One new piece of functionality would be support for running tests from CMake, currently that does not exist at all. It would also be very convenient to run any subset of the tests from the command line

**Comment by alexreinking** [comment]
This was fixed by #4556
