### ISSUE TITLE
Should we include all of HalideRuntime.h in every generated header file

### ISSUE THREAD

**Issue by abadams** [halide/Halide#872]
instead of just buffer_t 

This mirrors the way we include the entire runtime in every generated object. So this makes it match the object file better, and prevents incorrect signatures on runtime overrides.

It'll have the header guards, so as far as a compiler is concerned it should look the same as if there was include <HalideRuntime.h> at the top of the header.

**Comment by steven-johnson** [comment]
I think I'd rather go the other direction, and just do

#include "HalideRuntime.h" 

in the generated headers.

**Comment by zvookin** [comment]
It does seem like a fairly large number of lines to feed to the compiler
without some strong justification. It also isn't correct if compiling with
noruntime right?

-Z-

**Comment by abadams** [comment]
It'll still have the header guards around the block of code, so it's no
more lines to process than #include "HalideRuntime.h"

You'd skip it with NoRuntime. The point is to get the header to match
what's in the object.

**Comment by abadams** [comment]
(The reason I'm thinking about this is that we're going to have some
non-trivial amount of new stuff with the buffer_t changes.)

**Comment by zvookin** [comment]
In this model, we'd also include the device specific runtime routines for
any device APIs included in the target. E.g. if the target specifies CUDA,
HalideRuntimeCuda.h would also be inlined into the generated header.

My main objection is the number of lines of code appearing before the
compiler, but any project using more than a small number of Halide
generated objects should use noruntime and then link in one version of the
runtime. In as much as we are providing Halide build support in CMake,
Bazel, etc. we should support this latter model.

-Z-

**Comment by zvookin** [comment]
@abadams We resolved all of this didn't we?
