### ISSUE TITLE
SFML libraries issue

### ISSUE THREAD

**Issue by pallabkumar** [halide/Halide#874]
undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
how to solve this error..
my code :
#include <SFML/Graphics.hpp>
int main()
{

    sf::RenderWindow window(sf::VideoMode(200, 200), "SFML works!");

    sf::CircleShape shape(100.f);
    shape.setFillColor(sf::Color::Green);

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.draw(shape);
        window.display();
    }

    return 0;
}
console:
Building target: picGL
Invoking: GCC C++ Linker
g++ -L/home/guest/Desktop/workspace/SFML-2.3.1/lib -L/usr/lib -o "picGL"  ./src/picGL.o   -lsfml-graphics -lsfml-window -lsfml-system
/home/guest/Desktop/workspace/SFML-2.3.1/lib/libsfml-graphics.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
collect2: error: ld returned 1 exit status
make: *** [picGL] Error 1

18:12:11 Build Finished (took 565ms)

**Comment by delcypher** [comment]
What does this have to do with Halide?

**Comment by pallabkumar** [comment]
Actually i am trying to create a window where i load an image.. here it's just a code for creating a window..

**Comment by delcypher** [comment]
@pallabkumar But you're not doing anything with Halide here. This is not an issue with Halide and so should not be posted here so I'm closing this issue.

**Aside:** Your issue looks like there is a mismatch between the glibc version that was used to build libsfml and what is being used by your system's compiler. If you build SFML from source your problem will probably go away.
