### ISSUE TITLE
Building against Win32 trunk in VS2013: errors

### ISSUE THREAD

**Issue by ericbarnhill** [halide/Halide#900]
Hi,

I have some Halide code that compiles fine against glnx64 Halide trunk, however using Visual Studio 2013 against win32 Halide trunk I get some errors for Halide.h: 

c:\users\minor.sixth\documents\halide_win32\include\halide.h(1397): warning C4003: not enough actual parameters for macro 'max'
c:\users\minor.sixth\documents\halide_win32\include\halide.h(1397): error C2059: syntax error : '('
c:\users\minor.sixth\documents\halide_win32\include\halide.h(1397): error C2143: syntax error : missing ',' before '?'
c:\users\minor.sixth\documents\halide_win32\include\halide.h(1397): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\minor.sixth\documents\halide_win32\include\halide.h(1397): error C2059: syntax error : '?'
c:\users\minor.sixth\documents\halide_win32\include\halide.h(1397): warning C4183: 'Expr': missing return type; assumed to be a member function returning 'int'
c:\users\minor.sixth\documents\halide_win32\include\halide.h(1397): error C2208: 'const int' : no members defined using this type
c:\users\minor.sixth\documents\halide_win32\include\halide.h(1404): warning C4003: not enough actual parameters for macro 'min'
c:\users\minor.sixth\documents\halide_win32\include\halide.h(1404): error C2059: syntax error : '('
c:\users\minor.sixth\documents\halide_win32\include\halide.h(1404): error C2143: syntax error : missing ',' before '?'
c:\users\minor.sixth\documents\halide_win32\include\halide.h(1404): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\minor.sixth\documents\halide_win32\include\halide.h(1404): error C2535: 'int Halide::Type::Expr(void)' : member function already defined or declared
          c:\users\minor.sixth\documents\halide_win32\include\halide.h(1397) : see declaration of 'Halide::Type::Expr'
c:\users\minor.sixth\documents\halide_win32\include\halide.h(1404): error C2059: syntax error : '?'
c:\users\minor.sixth\documents\halide_win32\include\halide.h(1404): error C2208: 'const int' : no members defined using this type
c:\users\minor.sixth\documents\halide_win32\include\halide.h(2225): warning C4003: not enough actual parameters for macro 'min'
c:\users\minor.sixth\documents\halide_win32\include\halide.h(2225): warning C4003: not enough actual parameters for macro 'max'
c:\users\minor.sixth\documents\halide_win32\include\halide.h(2225): error C2059: syntax error : ')'
c:\users\minor.sixth\documents\halide_win32\include\halide.h(2225): error C2612: trailing ')' illegal in base/member initializer list
c:\users\minor.sixth\documents\halide_win32\include\halide.h(2264): error C2039: 'IntrusivePtr' : is not a member of 'Halide::Halide::Internal'
c:\users\minor.sixth\documents\halide_win32\include\halide.h(2264): error C2143: syntax error : missing ';' before '<'
c:\users\minor.sixth\documents\halide_win32\include\halide.h(2264): fatal error C1903: unable to recover from previous error(s); stopping compilation

Can anyone offer a suggestion?

**Comment by abadams** [comment]
Might be due to windows.h pulling in min and max macros? That would mess up
Halide.h pretty badly.

**Comment by ericbarnhill** [comment]
Aha, VS 2013 defaults to precompiled Windows headers. I turned them off and halide.h compiled without any trouble.
