### ISSUE TITLE
provide VS2015 builds (or make API STL-free ;)

### ISSUE THREAD

**Issue by Trass3r** [halide/Halide#911]
VS intentionally breaks STL binary compatibility between major versions.
Hence the prebuilt dlls crash due to functions like Buffer constructor taking a std::string.
Ideally those contact points would be STL-free.

**Comment by zvookin** [comment]
We will likely provide runtime only replacement versions of Buffer and
Image, which will effectively be header file only. The term "STL free" is
not well defined. (C++ does not define a subset of the library that is the
STL and even if it did it would be very unlikely std::string would be part
of the STL subset).

In practice the only way to get this degree of binary compatibility is to
make the interface between separately compiled code be C only. We strive to
do that for the runtime, but not for the language embedding.

-Z-

**Comment by kgnk** [comment]
Just looking at the exports of halide.dll, I see

```
class Halide::Func Halide::BoundaryConditions::mirror_interior(class Halide::Func const &,class std::vector<struct std::pair<struct Halide::Expr,struct Halide::Expr>,class std::allocator<struct std::pair<struct Halide::Expr,struct Halide::Expr> > > const &)
```

So a reference to a std::vector is passed. The bits of that object would be created by the runtime that the application was built with and then operated on by the runtime that Halide was built with.

It can be hard to maintain a C-ish interface with all that easy to use C++ library just sitting there. This is something my team has to deal with as well.

**Comment by zvookin** [comment]
BoundaryConditions is part of the language, not the runtime. There is no
chance the language part of Halide will be C-ish. We've had some
discussions about it, but it is an incredible amount of work and I'm
convinced it doesn't help anyway. (I have a recent report of a case where
linking two libraries which use different C++ sdlibs causes application
crashes even though the two libraries do not share any interface at all.)

This effectively means that JIT usage will require Halide be compiled with
the same C++ library as the app doing JIT.

AOT generated code should be more broadly usable without concern for which
C++ library the application is using. This means the runtime API has to
have any binary dependencies be C only.

-Z-

**Comment by abadams** [comment]
I've ordered a newer windows box. Hopefully it'll have enough horsepower to make releases with a variety of msvc versions for people.

**Comment by Trass3r** [comment]
Thanks very nice!
In the meantime I've manually extracted the VS2013 platform toolset from the installer to be able to use it without the full installation.

**Comment by kgnk** [comment]
> I have a recent report of a case where
linking two libraries which use different C++ sdlibs causes application
crashes even though the two libraries do not share any interface at all.

Multiple DLL's using different versions of the runtime DLL is ok (although not optimal). Static libraries have to be the same runtime version because they can only be linked with one runtime version or the other.

**Comment by alexreinking** [comment]
As of Halide 10 we only support VS2019.
