### ISSUE TITLE
Halide internal error on a "simple" program

### ISSUE THREAD

**Issue by AEHousman** [halide/Halide#918]
I'm assuming it's not something stupid I did because I've had people at work look at it, and it's been on stackoverflow for a day with no response. So I'm putting the issue here just in case it's a real issue.

See http://stackoverflow.com/questions/32193641/halide-internal-error-issue for details, please.

**Comment by abadams** [comment]
I think this is probably a bug. I'll investigate.

**Comment by abadams** [comment]
Yep, it's a dumb bug. Fixed pushed. Sorry for the frustration.

**Comment by AEHousman** [comment]
Not frustrated, just the normal growing pains. Halide is awesome!

**Comment by dsharletg** [comment]
It sounds like this was fixed, closing the issue.

**Comment by AEHousman** [comment]
Yup, it's fixed. Was I supposed to have marked it as closed? If so, I apologize for not doing so. Thanks for following up.

-- walt donovan

**Comment by dsharletg** [comment]
Don't worry about it, in general, none of us have been doing well at closing issues when appropriate :) I'm just going through the backlog and trying to find ones that should be closed.
