### ISSUE TITLE
Linking multiple compiled .obj files in the same project

### ISSUE THREAD

**Issue by winding** [halide/Halide#921]
I am using Halide for windows in Microsoft Visual Studio 2013. I separately compile two Halide functions into .h and .obj files. When I try to call either of them separately in a program, I get no errors. However, if I include and link to both of them in the same project, I get LINKING errors.

The snapshot of the error message is included. It seems that in each .obj file there are some common macros defined. I guess including more than one .obj file the compiler will complain about the redefinition of those common macros.

![halide_error](https://cloud.githubusercontent.com/assets/3420882/9535194/a4c63742-4cec-11e5-8e14-4778f4bb8368.png)

I am new to Halide, so it is also possible that I misunderstand its usage. So I would appreciate if anybody could elaborate on this or point out my misunderstandings.

**Comment by abadams** [comment]
Every object file generated by Halide contains a complete copy of the
runtime. On linux and OS X this is silently resolved using weak linkage.
Windows doesn't do weak linkage. You have a few options:

1) Tell the linker to ignore duplicate symbols with /FORCE:MULTIPLE
2) Compile your pipelines without the runtime using the target flag
Target::NoRuntime, then link in a separate copy of the runtime (any Halide
generator binary can make one for you with the -r command line flag).
3) Compile all your pipelines except for one with Target::NoRuntime.

**Comment by kgnk** [comment]
I'm sure there must be an object file section flag because MSVC has `__declspec(selectany)` but I don't know if that fits into how the runtime is built.

**Comment by winding** [comment]
I tried the first advice from abadams, and it works!

"Tell the linker to ignore duplicate symbols with /FORCE:MULTIPLE. "
