### ISSUE TITLE
Schedule reduction for histogram

### ISSUE THREAD

**Issue by winding** [halide/Halide#925]
I tried to build an efficient histogram generator for a 2D input image using Halide. Without scheduling, the whole code works, but not very different from the ordinary c++ code. So I want to add some split and parallelism scheduling to the code to accelerate it.

The gist of code is shown in the figure below:

![image](https://cloud.githubusercontent.com/assets/3420882/9620201/d635a54a-50e5-11e5-8d13-cecf69dcf262.png)

Unfortunately, I always get error saying that Halide cannot split the variables.

![image](https://cloud.githubusercontent.com/assets/3420882/9620244/30a8c3b8-50e6-11e5-8e32-223639d676d1.png)

If this is the case, how am I supposed to accelerate the histogram with Halide? I have tested both the Linux and Windows version of Halide.

**Comment by gchauras** [comment]
You cannot split r.x or r.y because there is a serial loop over these variables. Splitting them will create race conditions. You have to write a tiled implementation -- create a histogram for each image tile in parallel and then combine the histograms to get the global histogram.

**Comment by zvookin** [comment]
The number one issue with Halide as a language at present is that you
cannot solve this problem without changing the algorithm. If I get some
time later, I'll post some code to show how it is done. IT is relatively
straight forward, but it is very unsatisfying that this cannot be done in
the schedule.

-Z-

**Comment by abadams** [comment]
Gaurav and Zalman are correct. Here's what I usually write:

// Make a histogram per-row in parallel
RDom rx(0, width);
row_hist(x, y) = 0;
row_hist(im(rx, y), y) += 1;

row_hist.compute_root().vectorize(x, 8).parallel(y);
row_hist.update().parallel(y);

// Add the per-row histograms
RDom ry(0, height);
hist(x) = sum(row_hist(x, ry));

// This second stage can be vectorized across histogram buckets
hist.compute_root().vectorize(x, 8);

- Andrew

**Comment by Dr-Emann** [comment]
#1017 would fix this, I believe.

**Comment by zvookin** [comment]
We have a few things going on toward fixing this problem. Atomic updates
are one and should be a good solution on GPUs, but I doubt they're great
for histograms on multi-core CPUs.

-Z-

**Comment by abadams** [comment]
#1299 will fix this

**Comment by zvookin** [comment]
@psuriana's rfactor scheduling addition fixes this.
