### ISSUE TITLE
Internal error at e:\Code\Halide\src\CodeGen_LLVM.cpp:925

### ISSUE THREAD

**Issue by AEHousman** [halide/Halide#929]
symbol not found: foo1.min.4

The code that causes this is:

```
#include "Halide.h"
#include "halide_image_io.h"

using namespace Halide;

Var x, y, c;

Func foo(Func orig)
{
    Func p[4][4];
    for (int j = 0; j < 4; ++j)
        for (int i = 0; i < 4; ++i)
            (p[i][j])(x, y, c) = orig(x + i - 1, y + j - 1, c);

    Func foo1("foo1");

    foo1(x, y, _) = p[0][0];

    return foo1;
}


int main(int argc, char **argv) {
    Func orig_clamped("orig_clamped"), orig("orig"), baz("baz");

    Image<uint8_t> orig_uint = Tools::load_image("../foo.ppm");
    orig_clamped = BoundaryConditions::repeat_edge(orig_uint);
    orig(x, y, c) = cast<float_t>(orig_clamped(x, y, c));

    baz = foo(orig);
    baz.compile_jit();
}
```

Removing the "(x, y, _)" from the assignment to foo1 fixes the problem, but shouldn't there be a different error message if I'm violating a syntax rule?

**Comment by zvookin** [comment]
I'm surprised that line code code compiles as I thought the design we
decided on required wildcards to occur on both sides. E.g.
     foo1(x, y, _) = p[0][0](x, y, _);
(Removing the argument list on the left hand side simply reassigns foo1
with the contents of p[0][0], which is effectively he same thing, but it
may lose the name.)

I will investigate.

-Z-

**Comment by abadams** [comment]
I think saying p[0][0] in this context is identical to p[0][0](_), which
makes foo1 five-dimensional, which then barfs because outputs can be at
most four-dimensional, but apparently we're missing a sane error message
for this case.

I think you want foo(x, y, _) = p[0][0](x, y, _), or foo(_) = p[0][0];

**Comment by AEHousman** [comment]
Right -- I finally figured out the implicit index rule after rereading the comment on Implicit args a few times. I was posting this because it appears this should have a better error message.

**Comment by abadams** [comment]
Unlikely to still be relevant. Closing.
