### ISSUE TITLE
Tutorials build from source with llvm 3.5 crash under win64, fine under llvm 3.6

### ISSUE THREAD

**Issue by palgorithm** [halide/Halide#935]
If you build llvm and halide from source following the instructions in the Halide readme (using cmake and vs2013) you get a build without errors but the tutorials will crash when attempting to JIT the "MainShared" module. This seems to be due to a null pointer for the symbol __fixunsdfdi (and possibly a few others). I'm not that familiar with llvm but it I got the impression from the code that these are actually defined but have a null definition for the windows target? By this point I'd spent ~4 hours building llvm so apologies for not root-causing further.

Trying again with llvm 3.6 fixes this. So I guess there's something missing in 3.5 that is in 3.6 that is required.

**Comment by delcypher** [comment]
**Sidenote:** IIRC Halide's policy for supported LLVM versions is to support LLVM trunk, the current stable release and the previous release. Now that LLVM 3.7 has been released that means that Halide only needs to support trunk, 3.7 and 3.6. which means we probably should be dropping LLVM 3.5 support anyway which (by the sounds of it) would make this issue obsolete.

**Comment by dsharletg** [comment]
At this point, we've long dropped support for LLVM 3.5
