### ISSUE TITLE
Debug symbol parsing crashes for programs build with Xcode 7

### ISSUE THREAD

**Issue by jrk** [halide/Halide#936]
Updating tools to Xcode 7 seems to result in even trivial Halide programs crashing in the object file parsing:

    * thread #1: tid = 0x2dc0bd, 0x00007fff94e07d32 libsystem_c.dylib`strlen + 18, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x1d8301c20)
      * frame #0: 0x00007fff94e07d32 libsystem_c.dylib`strlen + 18
        frame #1: 0x00000001001adb09 libHalide.so`Halide::Internal::Introspection::DebugSections::parse_debug_info(llvm::DataExtractor const&, llvm::DataExtractor const&, llvm::StringRef, llvm::StringRef) + 9081
        frame #2: 0x00000001001ab66a libHalide.so`Halide::Internal::Introspection::DebugSections::parse_object_file(llvm::object::ObjectFile*) + 2042
        frame #3: 0x00000001001aa9e0 libHalide.so`Halide::Internal::Introspection::DebugSections::load_and_parse_object_file(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 128
        frame #4: 0x00000001001aa7f0 libHalide.so`Halide::Internal::Introspection::DebugSections::DebugSections(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 672
        frame #5: 0x00000001001a31f7 libHalide.so`Halide::Internal::Introspection::test_compilation_unit(bool (*)(), void (*)()) + 311
        frame #6: 0x0000000100000e92 test`HalideIntrospectionCanary::(anonymous namespace)::TestCompilationUnit::TestCompilationUnit(this=0x000000010000b7c8) + 34 at Halide.h:1673
        frame #7: 0x0000000100000bd5 test`HalideIntrospectionCanary::(anonymous namespace)::TestCompilationUnit::TestCompilationUnit(this=0x000000010000b7c8) + 21 at Halide.h:1672
        frame #8: 0x0000000100002b70 test`::__cxx_global_var_init() + 16 at Halide.h:1678
        frame #9: 0x0000000100002b89 test`_GLOBAL__sub_I_test.cpp + 9 at test.cpp:0
        frame #10: 0x00007fff5fc12f1b dyld`ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 265
        frame #11: 0x00007fff5fc13094 dyld`ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
        frame #12: 0x00007fff5fc0f6cd dyld`ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 305
        frame #13: 0x00007fff5fc0f553 dyld`ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 127
        frame #14: 0x00007fff5fc0f7c3 dyld`ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 75
        frame #15: 0x00007fff5fc020f1 dyld`dyld::initializeMainExecutable() + 208
        frame #16: 0x00007fff5fc05d47 dyld`dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 3515
        frame #17: 0x00007fff5fc01276 dyld`dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*) + 512
        frame #18: 0x00007fff5fc01036 dyld`_dyld_start + 54

This is using the 2015.08.05 and 2015.09.11 binary releases.

**Comment by abadams** [comment]
Will investigate when i get back. Workaround is to compile Halide with
WITH_INTROSPECTION off.

**Comment by zvookin** [comment]
Yes, I've been compiling WITH_INTROSPECTION=off for a while on the new Mac
OS X setup. I started looking at it but did not get very far. I can provide
a test environment if you need one.

-Z-

**Comment by jrk** [comment]
@abadams if it's easy, it's probably worth shipping a new binary release with this fix. I've had a number of users significantly confused and frustrated by this, now that 10.11 and Xcode 7 are several weeks into wide release. It currently gives a "WTF, Halide is totally broken" experience.

**Comment by abadams** [comment]
Release pushed
