### ISSUE TITLE
Consider Applying Analysis to Detect Integer Division By Zero

### ISSUE THREAD

**Issue by dan-tull** [halide/Halide#941]
Halide's bounds checking traps a lot of mistakes that would otherwise result in out of range indexing of buffers that could cause crashes.

It seems like similar analysis of the denominator in integer division operations to ensure the range of possible values does not include zero might be useful.

Here's a trivial example.

Because the size parameter includes zero, this code will crash for certain inputs. A more complex denominator expression would require more complex reasoning to determine if zero could occur.

```
Var x, y, c;

Param<int> size("size", 32, 0, 32);
result(x, y, c) = cast<uint8_t>(32 / size);
result.parallel(y).vectorize(x, 8);
```

Maybe this doesn't come up enough in practice to be important, but seems worth considering.

**Comment by abadams** [comment]
It may also be possible to prove that code can't overflow using the same mechanism. The problem with both is that the interval arithmetic is conservative, so you may be overloaded with false positives if this sort of checking is on by default. It could be useful as a static analysis mode. e.g. Pipeline::analyze(...)

**Comment by delcypher** [comment]
This is slightly off-topic but have you ever considered using an SMT solver in Halide to do a more sophisticated bounds analysis?

Something like Z3, STP or CVC4 could help here.

**Comment by dan-tull** [comment]
This makes me really wish I had access to a larger corpus of code written with Halide. When working on Lua tools here at Adobe, it was hugely beneficial to have a bunch of real world code to test new code analysis techniques for our linter.

**Comment by abadams** [comment]
integer division by zero is now well-defined
