### ISSUE TITLE
Lesson 9: Example C code doesn't seem to correspond with Halide code

### ISSUE THREAD

**Issue by delcypher** [halide/Halide#946]
In the first example covering update/reduction definitions the second update C code:

```C
        // Second update definition
        for (int x = 0; x < 4; x++) {
            result[0][x] = result[1][x];
        }
```

doesn't correspond to the second update/reduction definition ``f(x, y) = f(x, y) + 17;``

An additional comment on this section of the tutorial is it isn't explicitly said what order the update/reduction definitions are applied. I'm guessing in the order they are declared but that isn't really obvious until the equivalent C code is shown. I think there should be a comment being explicitly clear what order the update/reduction definitions are applied.

**Comment by abadams** [comment]
That section of C code corresponds to the Func g.

**Comment by delcypher** [comment]
Oops. My mistake.
