### ISSUE TITLE
[HelloAndroid] Gradle sync failed in Android Studio: Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by winding** [halide/Halide#955]
I tried to import the HelloAndroid project to Android Studio, but Gradle sync failed with an error that points to the following line in the file build.gradle: "apply plugin: 'android-ndk-classic' ".

The error message is "Cause: com/dmi/gradle/ndkclassic/AndroidNdkClassicPlugin : Unsupported major.minor version 52.0"

I am working on Windows 10 with Android Studio 1.3.2 and Java 1.7.0_79.

**Comment by abadams** [comment]
I updated gradle.build and jni/Android.mk using the one from
HelloAndroidCamera2. Let me know if it works.

**Comment by winding** [comment]
Gradle works now, and I can at least build the project, although some error prompts out... See the picture below for the detail.

![image](https://cloud.githubusercontent.com/assets/3420882/10772346/07d75cb2-7ccc-11e5-9705-008ac8a263e6.png)

Also, in the project structure, I cannot find any C++ source file or JNI related files...
![image](https://cloud.githubusercontent.com/assets/3420882/10772317/e7797dba-7ccb-11e5-88fb-13d7cec54679.png)

I typically use Halide in Visual Studio in which I manually add the path of Halide libraries to the project. Do I need to do similar things for Android Studio?

**Comment by abadams** [comment]
Weird - there should be a jni folder too. At this point I'm pretty out of
my depth unfortunately - I build these things on the command line from
linux.

**Comment by dsharletg** [comment]
This seems like more of a Gradle issue than a Halide issue, I'm going to close this old issue.
