### ISSUE TITLE
put back tutorial/image_io.h

### ISSUE THREAD

**Issue by mikeseven** [halide/Halide#957]
tutorial/image_io.h is used in CVPR2015 and was removed in 8/5 release.
CVPR2015 tutorial builds again if image_io.h from 6/3 release is put back.

**Comment by abadams** [comment]
Thanks, I've updated the CVPR tutorial repo to point to the newer location of image_io.h

**Comment by abadams** [comment]
For reference, that repo is here: https://github.com/halide/CVPR2015

**Comment by mikeseven** [comment]
Thanks Andrew.

Indeed, I realized afterward that halide_image_io.h was the new image_io.h.

Thanks for updating the tutorial. It is really great.


The only comment I would have is  to remove halide/ in all #include. This would make it easier with out-of-tree builds using cmake that typically generate include/ in Halide/build, not halide/.


There are few other places in the repos with the same problem that you might want to correct.


Thanks,


-- mike


________________________________
