### ISSUE TITLE
rename "interface" args in Halide.h to avoid problems with VS2015

### ISSUE THREAD

**Issue by mikeseven** [halide/Halide#960]
Visual Studio 2015 doesn't like interface as the name of function arguments. 
Please rename these to something else like "itf" or whatever else.

Thanks,

**Comment by zvookin** [comment]
Should have a fix in shortly. Is it only function arguments and not struct
fields this applies to?

-Z-

**Comment by mikeseven** [comment]
That's all I modified to build some samples in halide.h.

In image_io.h, all pointer parameters to check () in reading png files cause warnings and should be check (ptr!=NULL,...).

With these 2 fixes, samples build without warnings/errors on vs2015 and run correctly.

--mike



On Wed, Nov 4, 2015 at 11:51 AM -0800, "Zalman Stern" <notifications@github.com<mailto:notifications@github.com>> wrote:

Should have a fix in shortly. Is it only function arguments and not struct
fields this applies to?

-Z-


On Wed, Nov 4, 2015 at 10:32 AM, m1k3 <notifications@github.com> wrote:

> Visual Studio 2015 doesn't like interface as the name of function
> arguments.
> Please rename these to something else like "itf" or whatever else.
>
> Thanks,
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/halide/Halide/issues/960>.
>

-

**Comment by zvookin** [comment]
Should be fixed by 4e49cdf0417d741eb5c698d57c40490244ed6558  and 52f654ff8cb9db97185a466eac02139babef8ae3 .
