### ISSUE TITLE
Unhandled intrinsic in C backend (OS X Metal)

### ISSUE THREAD

**Issue by bobobo1618** [halide/Halide#966]
```
Internal error at /Users/lucas/Build/Halide/src/CodeGen_C.cpp:1064
Unhandled intrinsic in C backend: interleave_vectors
fish: './gpu.gen -g igd_demosaic -f ig…' terminated by signal SIGABRT (Abort)
```

This is the result of running the generator at https://github.com/bobobo1618/halideraw with  `-g igd_demosaic -f igd_demosaic -o . target=host-profile-metal`.

**Comment by dsharletg** [comment]
The C backend now handles interleave_vectors.
