### ISSUE TITLE
memoize and generators

### ISSUE THREAD

**Issue by mikeseven** [halide/Halide#971]
Not sure if this is expected or a bug.
When generating a pipeline with a generator, memoize() doesn't work, it has to be removed. But if I do compile_to_file() then it works.
I may be missing something but I don't understand why memoization wouldn't be generated...

**Comment by zvookin** [comment]
Please elaborate on "doesn't work". I.e. how does it fail?

**Comment by mikeseven** [comment]
Internal error at Halide/src/Memoization.cpp:85
Buffer parameter input encountered in computed_cached computation.
Computations which depend on buffer parameters cannot be scheduled compute_cached.
Use memoize_tag to provide cache key information for buffer.

… not sure what this means….

On Nov 9, 2015, at 5:34 PM, Zalman Stern <notifications@github.com<mailto:notifications@github.com>> wrote:

Please elaborate on "doesn't work". I.e. how does it fail?

**Comment by mikeseven** [comment]
And that’s what I was doing: luma.vectorize(x, 16).parallel(y, 16).compute_root().memoize();
A simple computation of luma from r,g,b values.

On Nov 9, 2015, at 5:39 PM, Mikael Bourges-Sevenier <mikael.sevenier@amd.com<mailto:mikael.sevenier@amd.com>> wrote:

Internal error at Halide/src/Memoization.cpp:85
Buffer parameter input encountered in computed_cached computation.
Computations which depend on buffer parameters cannot be scheduled compute_cached.
Use memoize_tag to provide cache key information for buffer.

… not sure what this means….

On Nov 9, 2015, at 5:34 PM, Zalman Stern <notifications@github.com<mailto:notifications@github.com>> wrote:

Please elaborate on "doesn't work". I.e. how does it fail?

**Comment by zvookin** [comment]
This error means that the computation you've asked to be memoized depends
on an input image. Halide does not do that by default as it would require
incorporating all the bytes of the image into the cache tag, and that is
going to use a lot of memory and be slow if the image is at all large.

The memoize_tag operator is used to wrap an Expr and either a) uses the
value of that Expr in the cache tag or b) allows providing other bytes to
use in the cache tag as extra arguments to memoize_tag. Generally for
images one might make an extern call to get a sequence of bytes that serve
as a unique ID for the input image.

Is it possible to look at the Stmt to see if an image is being used in the
computation you've asked to be memoized? I can't think of how using
Generator or not would matter here unless if one case an image has been
made into a constant and in the other it is not. (If it is constant inside
the Halide code, it will not need to be included in the cache tag at all.)

-Z-

**Comment by mikeseven** [comment]
Here is the code.

class LaplacianGenerator : public Halide::Generator<LaplacianGenerator> {
public:
  // parameters
  ImageParam input{UInt(8), 3, "input"};

  // return the Halide pipeline
  Func build() {
    // to take RGB interleaved data
    // Remove the constraint that prevents interleaved buffers
    input.set_stride(0, Expr());

    Expr w=input.width(), h=input.height();

    Func clamped("clamped"),luma("luma");
    Func gx("gx"), gy("gy"),lap("lap"), to_u8("to_u8");
    Var x,y,c;

    clamped(x, y, c) = cast<float>(input(clamp(x, 0, w - 1), clamp(y, 0, h - 1), c));

    luma(x, y) =  0.299f * clamped(x, y, RED) +
                  0.587f * clamped(x, y, GREEN) +
                  0.114f * clamped(x, y, BLUE);

    gx(x, y) = -luma(x - 1, y) + luma(x, y) * 2 - luma(x + 1, y);
    gy(x, y) = -luma(x, y - 1) + luma(x, y) * 2 - luma(x, y + 1);
    lap(x, y) = abs(gx(x, y)) + abs(gy(x, y));

    // to_u8(x, y) = cast<uint8_t>(lap(x, y));

    // schedule
    luma.vectorize(x, 16).parallel(y, 16).compute_root().memoize();
    lap.vectorize(x,16).parallel(y,16);

    return lap;
  }
};
RegisterGenerator<LaplacianGenerator> laplacian_generator{"laplacian_optimized"};

On Nov 9, 2015, at 5:46 PM, Zalman Stern <notifications@github.com<mailto:notifications@github.com>> wrote:

This error means that the computation you've asked to be memoized depends
on an input image. Halide does not do that by default as it would require
incorporating all the bytes of the image into the cache tag, and that is
going to use a lot of memory and be slow if the image is at all large.

The memoize_tag operator is used to wrap an Expr and either a) uses the
value of that Expr in the cache tag or b) allows providing other bytes to
use in the cache tag as extra arguments to memoize_tag. Generally for
images one might make an extern call to get a sequence of bytes that serve
as a unique ID for the input image.

Is it possible to look at the Stmt to see if an image is being used in the
computation you've asked to be memoized? I can't think of how using
Generator or not would matter here unless if one case an image has been
made into a constant and in the other it is not. (If it is constant inside
the Halide code, it will not need to be included in the cache tag at all.)

-Z-

**Comment by zvookin** [comment]
I'm not sure what you are trying to do here. Memoize caches a result for
future use and then reuses it if possible, including in future calls to the
same filter. In this case there is no other parameter except for the input
image, so if you were going to memoize, you'd want to do it on the entire
computation. That might make sense if the input image does not change much
and the laplacian is reused a great deal. In order to do that, you'd need
to come up with a reliable, small, id for the image. Possibilities include
taking a digest of the bytes of the image -- giving an index-by-hash
design, or using a counter that is incremented every time an image is
loaded. (The counter does not achieve reuse if the same image is reloaded
more than once.)

All that said, my guess is you do not want memoize here. Also, I have no
idea how this would work with compile_to_file outside the generator unless
memoize is getting dropped from the schedule.

-Z-

**Comment by mikeseven** [comment]
Thanks for the advice.
As I was benchmarking this function, I noticed that adding memorize() there does provide some speed up. The memoization on luma is good because gradient (gx and gy) reuse these values all the time and then lap is just the L1 norm of gx+gy. Sure, we are talking at ms improvements but that’s what I’m aiming for ;-)

When I use this method within a benchmark where an image is loaded, run through the function etc..., then compile_to_file() generates a reusable schedule. Maybe it drops memoize() but at least it works.

I have other more complex pipelines where memoization is even more important and put in a generator, I’m obliged to remove .memoize() to build. Maybe all I need is to tell Halide how big the cache could be e.g. the maximum image size I intent to use. How do I do that?

Thanks,

On Nov 9, 2015, at 6:17 PM, Zalman Stern <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm not sure what you are trying to do here. Memoize caches a result for
future use and then reuses it if possible, including in future calls to the
same filter. In this case there is no other parameter except for the input
image, so if you were going to memoize, you'd want to do it on the entire
computation. That might make sense if the input image does not change much
and the laplacian is reused a great deal. In order to do that, you'd need
to come up with a reliable, small, id for the image. Possibilities include
taking a digest of the bytes of the image -- giving an index-by-hash
design, or using a counter that is incremented every time an image is
loaded. (The counter does not achieve reuse if the same image is reloaded
more than once.)

All that said, my guess is you do not want memoize here. Also, I have no
idea how this would work with compile_to_file outside the generator unless
memoize is getting dropped from the schedule.

-Z-

**Comment by abadams** [comment]
memoize is only for when you want an Func's values to persist across
multiple runs of the entire pipeline. If the memoized stage depends on the
input, and the input image is changing with each run, then this makes no
sense. I think what you're looking for (compute a stage once and then load
its values at all uses instead of redundantly recomputing it) is just
compute_root, which you already have. That won't redundantly recompute luma.

**Comment by mikeseven** [comment]
Thanks for the details.


On Nov 9, 2015, at 6:56 PM, Andrew Adams <notifications@github.com<mailto:notifications@github.com>> wrote:

memoize is only for when you want an Func's values to persist across
multiple runs of the entire pipeline. If the memoized stage depends on the
input, and the input image is changing with each run, then this makes no
sense. I think what you're looking for (compute a stage once and then load
its values at all uses instead of redundantly recomputing it) is just
compute_root, which you already have. That won't redundantly recompute luma.

**Comment by zvookin** [comment]
I don't think there is an actionable bug here.

**Comment by mikeseven** [comment]
You are right. It was a misunderstanding of the memoize().
To confirm, I made more tests and indeed, it works very well and as expected.
