### ISSUE TITLE
Invalid shift transform

### ISSUE THREAD

**Issue by kgnk** [halide/Halide#975]
I did some bit tricks for 32-bit integers including code like `mask = x >> 31` which evaluates to -1 for values less than 0 and 0 for everything else. This got transformed to `mask = x / ( 2 ^ 31 )` but `2 ^ 31` is not representable as a 32-bit integer and ends up written out as `mask = x / -2147483648`. For negative values, this evaluates to +1.

**Comment by abadams** [comment]
Thanks. Will fix.
