### ISSUE TITLE
Tutorial Lesson 15:  undefined reference to `typeinfo for Halide::Internal::GeneratorParamBase'

### ISSUE THREAD

**Issue by navarrito** [halide/Halide#981]
Hi,

when compiling the lesson 15 of the tutorial (http://halide-lang.org/tutorials/tutorial_lesson_15_generators.html) in Ubuntu 14.04 with gcc 4.8 (and gcc 4.9 as well)  (halide-linux-64-gcc48-trunk-c815789464d4d0dc790ac13b084a4da44459983f.tgz) as proposed:

g++ lesson_15*.cpp ../tools/GenGen.cpp -g -std=c++11 -I ../include -L ../bin -lHalide -lpthread -ldl -o lesson_15_generate

The following errors appear:

/tmp/ccs1ErnY.o:(.rodata._ZTIN6Halide14GeneratorParamINS_4TypeEEE[_ZTIN6Halide14GeneratorParamINS_4TypeEEE]+0x10): undefined reference to `typeinfo for Halide::Internal::GeneratorParamBase'
/tmp/ccs1ErnY.o:(.rodata._ZTIN6Halide14GeneratorParamIN17MySecondGenerator8RotationEEE[_ZTIN6Halide14GeneratorParamIN17MySecondGenerator8RotationEEE]+0x10): undefined reference to `typeinfo for Halide::Internal::GeneratorParamBase'
/tmp/ccs1ErnY.o:(.rodata._ZTIN6Halide14GeneratorParamIfEE[_ZTIN6Halide14GeneratorParamIfEE]+0x10): undefined reference to `typeinfo for Halide::Internal::GeneratorParamBase'
/tmp/ccs1ErnY.o:(.rodata._ZTIN6Halide14GeneratorParamIbEE[_ZTIN6Halide14GeneratorParamIbEE]+0x10): undefined reference to `typeinfo for Halide::Internal::GeneratorParamBase'
/tmp/ccs1ErnY.o:(.rodata._ZTIN6Halide9GeneratorI16MyFirstGeneratorEE[_ZTIN6Halide9GeneratorI16MyFirstGeneratorEE]+0x10): undefined reference to `typeinfo for Halide::Internal::GeneratorBase'
/tmp/ccs1ErnY.o:(.rodata._ZTIN6Halide9GeneratorI17MySecondGeneratorEE[_ZTIN6Halide9GeneratorI17MySecondGeneratorEE]+0x10): undefined reference to `typeinfo for Halide::Internal::GeneratorBase'

To fix it, the flag -fno-rtti should be added:

g++ lesson_15*.cpp ../tools/GenGen.cpp -g -std=c++11 -fno-rtti -I ../include -L ../bin -lHalide -lpthread -ldl -o lesson_15_generate

**Comment by abadams** [comment]
Thanks

**Comment by victorygogogo** [comment]
still have a problem with this solution

xxx@U16-081:/data$ g++ ./Halide/tutorial/lesson_15_generators.cpp ./Halide/tools/GenGen.cpp -g -std=c++11 -fno-rtti -I ./Halidebuild/include -L ./Halidebuild/bin/ -lpthread -ldl -o lesson_15_generate
/tmp/ccbJZb7T.o: In function `Halide::Internal::check_introspection(void const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
/data/./Halidebuild/include/Halide.h:2320: undefined reference to `Halide::Internal::Introspection::get_source_location[abi:cxx11]()'
/data/./Halidebuild/include/Halide.h:2321: undefined reference to `Halide::Internal::Introspection::get_variable_name(void const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccbJZb7T.o: In function `HalideIntrospectionCanary::(anonymous namespace)::TestCompilationUnit::TestCompilationUnit()':
/data/./Halidebuild/include/Halide.h:2381: undefined reference to `Halide::Internal::Introspection::test_compilation_unit(bool (*)(bool (*)(void const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)), bool (*)(void const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), void (*)())'
/tmp/ccbJZb7T.o: In function `Halide::Type::operator==(Halide::Type const&) const':
/data/./Halidebuild/include/Halide.h:3279: undefined reference to `Halide::Type::same_handle_type(Halide::Type const&) const'
/tmp/ccbJZb7T.o: In function `Halide::Internal::IntImm::make(Halide::Type, long)':
/data/./Halidebuild/include/Halide.h:3541: undefined reference to `Halide::Internal::ErrorReport::ErrorReport(char const*, int, char const*, int)'
/data/./Halidebuild/include/Halide.h:3541: undefined reference to `Halide::Internal::ErrorReport::~ErrorReport()'
/data/./Halidebuild/include/Halide.h:3543: undefined reference to `Halide::Internal::ErrorReport::ErrorReport(char const*, int, char const*, int)'
/data/./Halidebuild/include/Halide.h:3543: undefined reference to `Halide::Internal::ErrorReport::~ErrorReport()'
/data/./Halidebuild/include/Halide.h:3541: undefined reference to `Halide::Internal::ErrorReport::~ErrorReport()'
/data/./Halidebuild/include/Halide.h:3543: undefined reference to `Halide::Internal::ErrorReport::~ErrorReport()'
/tmp/ccbJZb7T.o: In function `Halide::Internal::FloatImm::make(Halide::Type, double)':
