### ISSUE TITLE
Specifying boolean data type to the generator

### ISSUE THREAD

**Issue by aTinker** [halide/Halide#997]
With reference to using generators:
http://halide-lang.org/tutorials/tutorial_lesson_15_generators_usage.html

How should I be specifying a boolean type on the command line? (`output_type` in rhe tutorial).

I tried: `bool`, `boolean`, `UInt\(1\)`, all result in similar errors from the generator:

    Error:
    Enumeration value not found: UInt(1)Abort

**Comment by steven-johnson** [comment]
uint1 should be the proper syntax here.

**Comment by aTinker** [comment]
Appears to fail:

    Error:
    Enumeration value not found: uint1Abort

**Comment by aTinker** [comment]
Looking at:

https://github.com/halide/Halide/blob/master/src/Generator.cpp#L35

Maybe I can just add an entry for uint1?

**Comment by steven-johnson** [comment]
Yeah, but I don't think that will work; it would require that Halide
support buffer elem_size values that aren't even multiples of 8 bits, which
I'm pretty sure it doesn't (though I've never actually tried it, come to
think of it).

Your best bet is probably to use uint8 output for this case.

**Comment by aTinker** [comment]
Makes sense, since I immediately ran into #998.

I do think I can make some of my functions faster for boolean types when compared to uint8,  I'll have to figure out other ways to switch/specialize when dealing with an uint8 buffer.

**Comment by zvookin** [comment]
Are you expecting bool to be a bit-packed image or are you expecting it to
be 8-bits per pixel but the pixel values are asserted to be zero or one and
nothing else?

The former (bit-packed) is not supported by codegen. We should likely make
it an error to declare an image of type UInt(1) I think.

That said, I think type params to generators can be used in contexts where
bool makes sense and thus I think generator probably ought to support
"bool" as an enumeration member here.

-Z-

**Comment by aTinker** [comment]
The later -  8-pits per pixel but only the LSB matters, i.e zero or one.
Even though bool/boolean says nothing about the physical representation, I think most languages/people might still think of it as uint8 with 1/0 value - maybe CPP even defines it that way.

I agree, allowing UInt(1) leads one to believe that bit-packed data is supported. Maybe it should error on anything other than 8/16/32/64 for now. bit-packed data is interesting, but I think the effort to support it would far outweigh its usefulness.

**Comment by abadams** [comment]
If you just want bool in 8-bits, then that's supposed to work but is poorly
tested. I think this is just a missing enum for the generator and a bug in
natural_vector_size. It should use type.bytes() instead of type.bits() / 8.
We have an example here of a compute-root'd boolean function:

https://github.com/halide/Halide/blob/master/test/correctness/bool_compute_root_vectorize.cpp

- Andrew

**Comment by aTinker** [comment]
@abadams  - like this? 
https://github.com/aTinker/Halide/commit/ca0e365c4e34af5ebcf142048901ee2d795fc72a

Mind having a quick look at the new test point? If it looks right, then I guess there is another bug lurking in casting?
