### ISSUE TITLE
natural_vector_size fails for UInt(1)

### ISSUE THREAD

**Issue by aTinker** [halide/Halide#998]
I am trying to use the generator (http://halide-lang.org/tutorials/tutorial_lesson_15_generators_usage.html) with boolean data type specifications.

I first ran into: https://github.com/halide/Halide/issues/997. I tried to setup the default to be Uint(1) so that I could override for other data types in the commandline and use the default for boolean.

Running the generator (when a particular data type was UInt(1)), resulted in:

    Floating exception

Traced this to the use of `natural_vector_size` on this type in my code.

Digging up the source code - it looks like UInt(1) might not be handled well here:
https://github.com/halide/Halide/blob/master/src/Target.h#L241

Should Halide handle this? or is it better off for client code within the generator to specialize boolean types?

**Comment by zvookin** [comment]
Vector of bool is not really going to work in codegen at this point... It
should be an error, not a crash however.

I'm also fine with an issue being filed on needing better support for
bitpacked images or arrays, if that is what you are trying to do.

-Z-

**Comment by aTinker** [comment]
My goal is to work with CPP boolean arrays (uint8, with 0/1 values only) and CPP uint8 arrays. If I use uint8 for both - I am not sure how to specialize the implementation code for the boolean case. 

My intent was to use bool - but I got side tracked into trying UInt(1) as a workaround.

**Comment by aTinker** [comment]
I'll close this - I dont have a usecase for bitpacked data at this time, and I had not realized thats what UInt(1) represents.
