### ISSUE TITLE
Using Halide with Windows MinGW compilers

### ISSUE THREAD

**Issue by KlamerS** [halide/Halide#999]
Hi,

I have been working to get Halide working with the g++ and LLVM gnu toolchains on Windows. Find attached [patches.txt](https://github.com/halide/Halide/files/76229/patches.txt) needed to get the 2012-12-17 release to compile. Note you need the windows-gnu LLVM setup. With these patches Halide supports the Windows platform with a feature mingw (Target::MinGW) which maps to the windows-gnu LLVM target.

I started to work with the Makefile to make it compile. This needed quite some changes, with two incompatible with other (Linux type) environments: the first one is the definition of LIBDL, which shall e -ldl on Linux but empty using mingw, and the second one the definiton of SHARED_EXT which shall be .dll on Windows and .so on Linux. Note that using MinGW a .dll shall not be in the same directory as a .dll files if you want to use the shared library; as such I made the .a library to reside in .../lib rather then .../bin .

Please see attached the failures for the regression tests in [failures.txt](https://github.com/halide/Halide/files/76244/failures.txt). These mainly have to do with a not fully compatible math library within the MinGW environment. In addition (not in failures.txt) there are many errors in the generators tests related to LLVM not supporting weak linking on a Windows plaform. I have reported this weak linking issue with LLVM as https://llvm.org/bugs/show_bug.cgi?id=25996 . Full output of make -n run_tests is provided in 
[run_tests.txt](https://github.com/halide/Halide/files/76236/run_tests.txt) .

Please let me know what I can do to support this getting into the main Halide tree.

**Comment by zvookin** [comment]
Note the '.' characters were stripped from the URLs above. The following
are correct:
    Patches: https://github.com/halide/Halide/files/76229/patches.txt
    Failures: https://github.com/halide/Halide/files/76230/failures.txt
    Test output: https://github.com/halide/Halide/files/76236/run_tests.txt

-Z-

**Comment by delcypher** [comment]
@KlamerS If you submit a pull request someone can review your proposed changes. Are you aware that Halide also has a CMake build system? CMake is supposed to work with mingw so that build system might work better out of the box than the Makefile build system.

**Comment by abadams** [comment]
R.e. the weak linking issue: For msvc we somewhat crudely work around this
by adding a compiler flag that just allows duplicate symbols. You could try
something similar.

To get this mainstreamed we'd need a way to ensure it doesn't break, which
means a buildbot config for it. See
https://github.com/halide/build_bot/blob/master/master/master.cfg. The
config would probably look a lot like the linux one.

The patch to the makefile looks reasonable, but some of it needs to be
conditional (e.g. you globally removed -fpic and introspection). And yeah,
getting the cmake build working in mingw would also be good.

- Andrew

**Comment by KlamerS** [comment]
I worked around the weak linking issue by using
-Wl,--allow-multiple-definition during the compile/link command for the
generators.
I made the changes to the Makefile conditional (on OS equals Windows_NT)
including the -fPIC and introspection changes.

I tried to put it all in pull request. Being experienced (in day-to-day
usage) to SVN this is weird to me, let me know when I messed up.

The buildbot thing looks complicated to me. Does that mean I have to supply
a (slave?) machine on which the MinGW tests regularly run? How to specify
what extra stuff (MinGW environment) is needed? Note that compiling LLVM
seems to take ages -- making an automated build including an LLVM compile
quite time consuming :-(.

Added CMake support in a second GIT commit/push. Do I need to make another
pul request for that?
Cmake works for me when configuring with
/c/Program\ Files\ \(x86\)/CMake/bin/cmake -G "MSYS Makefiles"
-DLLVM_BIN=/c/prog64/LLVM_mingw/bin -DLLVM_LIB=/c/prog64/LLVM_mingw/lib
-DLLVM_INCLUDE=/c/prog64/LLVM_mingw/include -DLLVM_VERSION=37 ../Halide

Cheers Klamer

On Mon, Jan 4, 2016 at 6:49 PM, Andrew Adams <notifications@github.com>
wrote:

> R.e. the weak linking issue: For msvc we somewhat crudely work around this
> by adding a compiler flag that just allows duplicate symbols. You could try
> something similar.
>
> To get this mainstreamed we'd need a way to ensure it doesn't break, which
> means a buildbot config for it. See
> https://github.com/halide/build_bot/blob/master/master/master.cfg. The
> config would probably look a lot like the linux one.
>
> The patch to the makefile looks reasonable, but some of it needs to be
> conditional (e.g. you globally removed -fpic and introspection). And yeah,
> getting the cmake build working in mingw would also be good.
>
> - Andrew
>
> On Sun, Jan 3, 2016 at 2:51 PM, Dan Liew <notifications@github.com> wrote:
>
> > @KlamerS <https://github.com/KlamerS> If you submit a pull request
> > someone can review your proposed changes. Are you aware that Halide also
> > has a CMake build system? CMake is supposed to work with mingw so that
> > build system might work better out of the box than the Makefile build
> > system.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/halide/Halide/issues/999#issuecomment-168549417>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/halide/Halide/issues/999#issuecomment-168749997>.
>



-- 
Klamer Schutte
(+31) (0)79 3423924 / (0)6 51316671
Klamer.Schutte@gmail.com

**Comment by abadams** [comment]
Thanks! The PR looks good to me. I'll set up my windows test box as a mingw
build slave - I should just be able to clone the linux build slave config.
It will have to wait until later next week though - I have a big deadline
coming up next Tuesday.

**Comment by abadams** [comment]
We now have a release for mingw, and a working mingw buildbot. This is for 64-bit only though, right now.

**Comment by zvookin** [comment]
@abadams Can this be closed now?

**Comment by abadams** [comment]
It's still 64-bit mingw only. I don't ever plan to support 32-bit mingw. Someone can reopen this if they really care about that platform.
